### ISSUE TITLE
Selecting a history step the related module must expand automatically.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#10003]
**Is your feature request related to a problem? Please describe.**
"I always get frustrated when" I am reviewing the history to check for changes in the process, select a step and then have to go to the right pane and expand the related module if it is closed. The review process does not have an intuitive behavior. If users select a step in the history, the related module must be expanded just to see the parameters or change them.

If users like or dislike this type of behavior, then they should have the option to enable or disable this behavior in the darkroom tab of the darktable preferences window.

**Describe the solution you'd like**
Each time a step in the history is selected, the related module must be expanded to see the changes made to it, or simply to make a new setting.

**Additional context**

https://user-images.githubusercontent.com/67672868/133352582-e745dd28-4bbd-45a5-b110-7aaf61a8657c.mp4

**Comment by elstoc** [comment]
Hmm I think I would be equally frustrated if darktable _did_ do this. My most common reason to go back in the history is to undo the changes I've just made to a module. That doesn't mean I want to alter what I did in the _last_ module in the history stack. In fact I very rarely want to do this - I'm usually trying to go back to the last "good" point in the history.

**Comment by piratenpanda** [comment]
While it sounded intriguing the first time I read it, I think I am using it the same way @elstoc is using the history, so it would be confusing for me as well. Maybe both ways could be implemented by adding a "settings" icon next to the module in the history stack? Might be bad UI design though as one could trigger it accidentally.

**Comment by dterrahe** [comment]
Maybe it would be more logical/consistent to have _double click_ on a history item expand the module. Many file manager/dialog type situations work like that. I know @elstoc doesn't like double-clicks, but doesn't seem he wants this feature anyway? ;-)

I would like this feature as well. But maybe the history item should not stay selected, because otherwise changing anything in the module opened this way would remove all later changes in the stack. I don't think that would necessarily be the intention.

There might be a separate issue/bug here; a click on a history item selects it and takes us back to the state at that point in history. Clicking it _again_ unselects it, but we don't go back to "full history" again; you need to actively click on the last item in the stack (unless I'm missing something; haven't checked in the manual, excuse my laziness). So again we might accidentally remove all later changes if we now change something in any module.

**Comment by piratenpanda** [comment]
Snapseed does this nicely in my opinion, selecting an item in the stack moves one to the image with the changes up to this point in time, when clicking again options to modify or delete the selected item appears. When done, the changes are then applied to the whole stack of changes like @dterrahe suggests and I think this is what most users would expect to happen.

**Comment by dterrahe** [comment]
I'm sure if this gets implemented, the next request is to have the changes made in that history item (that you can now see in the tooltip) also be highlighted in the module itself...

Which would be ...interesting... to implement. It should then also work immediately when making any changes (since it would be simply all the changes against the last history item).

If I ever start on an overhaul of bauhaus, this would be a potential part of it.

**Comment by Mark-64** [comment]
@difrkaguilar I like your theme, what custom css do you use? ;-)

**Comment by difrkaguilar** [comment]
> I am using it the same way @elstoc is using the history

I also always use the history in the same way as you, when I select the last "good" point of the history as it is well, there should be no need to change it, but to display the parameters of this module to which the history refers, in this case if the module is previously deployed, you will still see the parameters. The idea is that the history will show the module to which it refers.

Other programs, such as Nuke, have a different philosophy, each node can be considered as a module making an analogy with darktable. The general configuration of the behavior of each node can be done in such a way that when the node is selected it automatically displays its contents. With the difference that in Nuke, although each node has an input and output, independently modifying each one does not destroy the sequence of the history, because what is created are connections between the input and output nodes. These can be added, modified or removed and their organization visually alters the result, but the connections are not lost. Of course, this is a different philosophy from RAW development programs.

> I'm sure if this gets implemented, the next request is to have the changes made in that history item (that you can now see in the tooltip) also be highlighted in the module itself...

This would be great as well :-)

Here is a short video that illustrates the functionality I am talking about.

https://user-images.githubusercontent.com/67672868/133466228-81ee737a-c40b-4d1f-b287-861acb366976.mp4

**Comment by difrkaguilar** [comment]
> @difrkaguilar I like your theme, what custom css do you use? ;-)

darktable-Pro-v2.css

[darktable-Pro-v02.zip](https://github.com/darktable-org/darktable/files/7171612/darktable-Pro-v02.zip)
And this two lines for LUA

/* Enter CSS theme tweaks here */

button#sm_started label { color: rgb(255,255,255); }
button#sm_stopped label { color: rgb(105,105,105); }
