### ISSUE TITLE
diffuse and sharpen crashes on large images

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#10017]
Using diffuse and sharpen with stitched panorama (almost 90 Mpx) makes dt crash with no message nor backtrace. This affects both GPU (Nvidia Quadro with 4 GB RAM) and CPU (with 32 GB RAM). For GPU, it seems to be a faulty tiling since the image has to be processed at least in 2 tiles. For CPU, I have no clue since there is no tiling involved.

I will investigate that later unless someone wants to do it before.

**Comment by paolodepetrillo** [comment]
For CPU it looks like it's just running out of memory. In process() it allocates a very large amount of memory, and the dt_alloc_ calls don't fail returning null at that point, probably because of [overcommit](https://www.etalabs.net/overcommit.html)? But then soon after, the Linux kernel's [OOM Killer](https://www.oracle.com/technical-resources/articles/it-infrastructure/dev-oom-killer.html) kills the process.

**Comment by ralfbrown** [comment]
And since the module doesn't have the ALLOW_TILING flag, the GPU path fails due to lack of memory and we fall back to CPU....
