### ISSUE TITLE
osmgpsmap version: permit > 1.0

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10033]
`cmake/modules/FindOSMGpsMap.cmake` states:

`libfind_pkg_check_modules(OSMGpsMap osmgpsmap-1.0)`

versions > 1.0 should be permitted

**Comment by parafin** [comment]
Hmm, I think it's kind of upstream issue - why does osm-gps-map include minor version in its library and pkgconfig name? If update doesn't break API, then it makes sense. It's even OK if it breaks ABI, because ABI is defined by soversion suffix, not soname...
For now I guess we should add all current releases here...

**Comment by parafin** [comment]
Current osm-gps-map release (1.2.0) still has -1.0 suffix, so there's no bug here yet. But in master PR https://github.com/nzjrs/osm-gps-map/pull/84 was merged, so next potential release will create a problem. I think that PR should be reverted if there are any plans for more osm-gps-map releases. Pinging @johnny-bit. I suggest closing this ticket in any case.

**Comment by johnny-bit** [comment]
I've pushed https://github.com/nzjrs/osm-gps-map/commit/a7ba58c01260336562dd8834c1ef5806233e050f - please check if that fixes the issue for you
