### ISSUE TITLE
Exporting photos in a collapsed group will only export the group leader photo

### ISSUE THREAD

**Issue by eoyilmaz** [darktable-org/darktable#10032]
Selecting a collapsed group shows in the title bar how many photos are selected, for example "21 images of 343 in current collection are selected" but when exporting this selection only 1 image is exported where as I expected all of the 21 selected images had been exported. Again, this happens when a collapsed group is selected and then exported.

Darktable 3.7.0+277~g0f575bc2b
Fedora 34

**Comment by phweyland** [comment]
This is coherent with the code. Only visible images are exported.
I can't tell if it's intentional or not.
However, this is not specified in the [doc](https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/export/).

**Comment by phweyland** [comment]
> This is coherent with the code. Only visible images are exported.
> I can't tell if it's intentional or not.
> However, this is not specified in the [doc](https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/export/). EDIT well, depends how we read  `to export all selected images`...

**Comment by elstoc** [comment]
So either we should update the prompt to say "1 image of 343 in the current collection is selected" or we ensure that all 21 images are treated as selected by the export function?

**Comment by phweyland** [comment]
Either way, but I think we should consistent, which may not be the case:
copy_history, export, styles apply on visible selected images,
metadata_view, color_label, rating, images, geotagging apply on all selected images,
metadata and tagging seem not to be fully consistent.

What should be general behavior ?
The wording could be as simple as `visible selected` or `all selected`.

**Comment by elstoc** [comment]
I thought everything was supposed to be using the `dt_view_get_images_to_act_on` function so I'm surprised it's not working consistently.

**Comment by AlicVB** [comment]
I'm quite reluctant to change this behavior : 
for "export" specifically, I'm quite reluctant to change the current behavior :  imho this will cause lot more problems, esp. because the main and "historical" use case of image grouping is RAW+jpeg... and you don't want to export both in this cases !

that said, I agree with @phweyland that we should at least explain and advertise what is is done, in usermanual and in the UI.
For the consistency, iirc we have : 
- metadatas things apllied to *all* images
- develop things applied to *visible* images

this is coherent with how dt works imho

@elstoc : `dt_view_get_images_to_act_on` as an option to get *all* or *visible only* images

**Comment by TurboGit** [comment]
> I can't tell if it's intentional or not.

Yes, that's an early design decision I remember. Only visible images should be handled.
