### ISSUE TITLE
Input NG: Consider grouping some global shortcuts

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10041]
In order to make the global shortcuts a bit easier to navigate, we should perhaps consider grouping some of them:

- A "switch view" group could contain all actions related to switching views
- A "panel toggles" group could contain all of the panel/header/toolbar toggle actions

**Comment by dterrahe** [comment]
These are currently still using the calls from the old framework supported by Input NG. This made the transition more manageable (and kept the translations). I did indeed plan to create groupings, but as part of a larger refactoring to get rid of most of the old-style calls and to add functionality so that for example panel "toggles" also support directly switching "on" or "off". But I kindoff ran out of motivation along the way as the lack of feedback suggested there wasn't much interest anyway.

**Comment by elstoc** [comment]
If you plan to do this, it would be best to do it before 3.8 as subsequent refactoring will break people's assigned shortcuts.

**Comment by dterrahe** [comment]
If I have the time and motivation I will _definitely_ do that.

But I was also thinking of a simple string replacement scheme to support old action paths when they get moved in a refactoring.
