### ISSUE TITLE
[FR] What's New dialog at first run after update

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#10055]
This idea was discussed in passing previously.

After each release, we see that people are confused by changed functionality even if it was highlighted in the release notes. A dialog that pops up highlighting just those major changes only once when running a new release for the first time _might_ reduce such confusions. I'm thinking particularly of Input NG, but also things like the crop/rotate restructuring and progressive moves towards scene-referred (including module deprecations).

This could also be useful for people running master; whenever a major PR lands, it could trigger a message asking people to test and report issues. Or just refer to the PR in question. Before the release (after sufficient testing has taken place) this message could then be replaced by a more user-oriented one.

So I'm thinking of a system with numbered messages (numbers to be issued by @TurboGit during or immediately after merge) where the last shown message is stored in darktablerc and any messages with higher number are shown at startup.

All messages to be shown when updating from an old release that didn't have the system yet.
No messages to be shown on a fresh install (empty configdir).

**Comment by elstoc** [comment]
Would a link to the news article / blog post be enough?

**Comment by dterrahe** [comment]
"expect breakage in _this_ area, read more about it _here_".

People won't click on the link and actually read, but what I'd hope for is that they remember being warned about _something_ and then when they have problems go and look at the release notes.

Or at least we can tell them they should have and they shouldn't complain now.

For testers I think being made aware that something(s) big landed can be very helpful (since the release notes are no help there and the git log may have accumulated a lot of small stuff if you haven't fetched for a while).

**Comment by AlicVB** [comment]
Good idea !
- For the release, we already have the release note in the repo. I would say we "just" have to reuse it as-it-is... a dialog with a textarea widget or something like that...
- For the dev version, maybe we can do the same with another "specific" file ?

But anyway, I'm not sure we have to put lot of efforts here as lot of people will not read that message anyway ;)

**Comment by dterrahe** [comment]
For devs, the point is not to _always_ have a dialog popping up, because people will ignore it.

You should _only_ see a dialog if the version you are running now has _important_ changes since the previous version you ran. So that will be a different list for each individual. This scheme will not work if people clear out their configdir each time, but I don't get the impression that's what people do...

**Comment by elstoc** [comment]
that's what they do if they have a bug sometimes so we do need to be careful about popping up lots of messages if someone does that.

**Comment by dterrahe** [comment]
> No messages to be shown on a fresh install (empty configdir).

**Comment by elstoc** [comment]
d'oh must read things

**Comment by MStraeten** [comment]
Since there aren’t new features every week or month reading the release notes twice a year after installing the new release might be sufficient.
For those running master: since that might have side effects it’s worth to check the latest commits before installing stuff, so also no need to have a changelog at start. 
And from a pragmatic side: who will maintain the most important changes list after each merged commit? ;)

**Comment by dterrahe** [comment]
The problem is _not_ that the information isn't around somewhere for people to find. It is that they don't go looking for it. And quite reasonably so; if there is something new and big that landed in master a week ago, that devs want feedback on, how would you know unless you read all commit messages in detail? And since those are ordered by commit, not merge, date, really important ones might be months back and hiding between one line margin fixes and translation updates. IRC and mailing lists don't work either due to the level of "polution" there.

Alternatives to this FR would be using a special format in merge commit messages for "important", "big" stuff. "ATTENTION: " "FEEBACK REQUESTED: ", but that would still only capture those who (remember to) go looking for it.

Just like @TurboGit now occasionally requests PR submitters to provide a blurb for the changelog, he could similarly request a pop-up message to be provided.

Again, the objective is to get more directed testing earlier and to avoid (some) duplicate issues being filed immediately after release. The Input NG PR was submitted 8 months and merged 3 months ago and I'm basically only now getting fundamental feedback asking to change the basics. This regularly happens in snowball fashion just before release (fundamental fixes breaking other stuff requiring more fixes and rethinks and larger changes plus added workarounds and optional switches that don't get any time for testing) and this just _doesn't_ increase the quality of the "finished" product. For one thing because devs who worked on something big a while back while they had excess time may have less availability when the feedback finally arrives much later. And enthusiasm levels are much higher if there is immediate engagement. Yes, all of this should happen _before_ PRs get merged, but we have already accepted that _that_ is never going to happen.

So great if you don't like _this_ idea, alternative suggestions are _very_ welcome, but some of us would really like to see an improved process rather than just give up.

As a test, without spending an hour digging, can you tell me what the big changes in 3.8 are that could still use more testing if you have an afternoon to hammer on it? If you have a quick way of finding out, please please I want to know!

**Comment by elstoc** [comment]
Functional changes can be found by searching for closed Pull Requests with the "documentation-pending" or "documentation-complete" tags. We could add another tag.

**Comment by dterrahe** [comment]
That is a VERY useful suggestion, thanks. Maybe a direct link could be added to README.md (under Development snapshot)?
 
Something like this:
https://github.com/darktable-org/darktable/pulls?q=is%3Apr+is%3Aclosed+label%3Adocumentation-pending%2Cdocumentation-complete%2C%22release+notes%3A+pending%22+sort%3Aupdated-desc

Problems are; 
- github doesn't support sorting on merge date :-(
- this does pick up some minor changes in spelling etc
- includes minor well-understood/tested additional functionality

So maybe a "feedback-needed/requested" or "testing-needed" tag? (I'd prefer using something existing to avoid unbridled expansion of tags, but maybe this really is something new?)

**Comment by elstoc** [comment]
Another tag seems like the best way to go, perhaps "merged-for-user-testing" or something like that

**Comment by elstoc** [comment]
> For one thing because devs who worked on something big a while back while they had excess time may have less availability when the feedback finally arrives much later.

This will never be resolved because everyone does what they can in the free time they have available. People doing the testing will almost never have sufficient time to properly evaluate/test a big change at the same time the developer has sufficient time to implement it.

**Comment by dterrahe** [comment]
> This will never be resolved

Is this an argument to not try to improve? To not at least _try_ to allocate those limited resources more efficiently?

_I_ believe that many people want to help out but don't know where to start.

Will any small step solve the problem and end world hunger? Uhm no.

**Comment by elstoc** [comment]
> Is this an argument to not try to improve?

Nope just to manage expectations.

**Comment by johnny-bit** [comment]
I personally am for this FR. Seems like a good idea just to have people notified that "stuff changed" with some nice blurb/infos. Fresh install COULD imo pop up a dialog about recommending to read manual/check out resources if that's your first rodeo with darktable :)

**Comment by difrkaguilar** [comment]
I make some mock ups about this FR and post to your analysis. The content of some tabs is dedicated only for developers and others to the info related to the release or the update. 

The image on top, maybe it's not the best move, but I put as a reminder of the release in the web page, an image per release.

There are other tabs I don't fill with info because don't know what kind of info would you like to include.

To make the user aware that all the information related to the new version or update has been provided, an option to not show this window again is included below. That would behave like this until a new version is released, or that this window is displayed again from an option in the configuration window of darktable.

Every other information must be show as a link to a browser included the commits.

**sample screenshots**

![dt_welcome_window_01](https://user-images.githubusercontent.com/67672868/135794399-bf931f0a-39d9-4e8f-8e23-a4471b9395ac.png)

![dt_welcome_window_02](https://user-images.githubusercontent.com/67672868/135794422-3ee35bee-4ddf-49f1-92be-8cd4a0ec9b5e.png)

![dt_welcome_window_03](https://user-images.githubusercontent.com/67672868/135794433-93268187-3e11-4c8b-a8d5-450bd385477d.png)

![dt_welcome_window_04](https://user-images.githubusercontent.com/67672868/135794443-fac3e6e3-5387-46b3-ab3f-54103c3c92d2.png)

**Comment by AlicVB** [comment]
your screenshots are nice, but tbh, I'm not sure it's worth the pain to develop such complex window. What I would propose : 
- add a whatsnew.md file which will be either a copy of readme.md for release versions, either a "manual" list of points requiring special test/attention from devs for master.
- show whatnew.md file at startup in a window with some choices "never show this window again" "reshow at next startup" "I've understood" (as usual, english needs enhancements)
- in the last case, store a hash of the file and verify at each startup if it has changed or not

That would have the advantage to be quite simple to implement and to keep up to date. For the master version, points requiring attention should be very few to not annoy devs (otherwise everyone will disable the window) For current master, I would say : 
- Input NG
- diffuse module
- c&r deprecate

How does that sound ?

**Comment by TurboGit** [comment]
I see that I'm tagged in this discussion and I had no time yet to read this! Sorry, I'll try to come back to this asap, probably after 4.0 or during Christmas break.
