### ISSUE TITLE
[FR] Darktable preference changes should be persisted immediately and not only upon exit

### ISSUE THREAD

**Issue by emoryy** [darktable-org/darktable#10056]
This is problematic for me because my PC oftentimes can't go down into sleep mode in a currently unpredictable manner. (I don't think that I can solve this underlying problem anytime soon.) At that time I can't do anything other than powering off the computer manually, which naturally means that the current memory state of every running program is lost. Together with any unsaved darktable preference change.

As I see a possible solution would be to simply persist any changes as soon as the user makes them.

An alternative solution would be to have a "save" button in the darktable preferences modal window. 

A concrete example that made me write this feature request was that at one time a few weeks ago I was experimenting with the "mouse wheel scrolls side panel by default" option, which I have turned on. Eventually I also have exited darktable, so the change was persisted. The nature of the sleep mode issue with my PC is like that at times it can make the sleep/wake up cycle without issue every day even for a few weeks. Then suddenly one day it just doesn't work again for days or weeks. This means that I can have a darktable instance running even for a few weeks without exiting. Eventually I decided that the "mouse wheel scrolls side panel by default" option is just not for me, so I turned it off, but of course I forgot to restart darktable to persist the change.
I believe so far I have forgot to make persist this setting change for the 4th time in a row. You could say that I just should have restarted darktable, but it so happens that every time I was that excited to go edit my photos, that I just immediately forgot about it. And I only realized my mistake when I started darktable anew the next time, and I wasn't able to scroll the sliders with my mouse wheel again.
Of course now I really have persisted reverting that specific option, but I can see myself potentially falling into the same pattern with another option in the future.

**Comment by quovadit** [comment]
I have exactly the same problem.
It would be great, if all settings get stored without the need to restart darktable.
In the preferences of modules (like collections, export, ...) there even is a 'save' button.
But it only gets permanently stored when restarting.

So if darktable crashes, I have to remember: what were the settings I changed since the last dt start.

I don't think it is necessary to permanently save everytime as soon as the user changes one value, but when closing the 'global preferences' window, of when clicking 'save' in the module preferences.
