### ISSUE TITLE
[FR] Input NG: Add option to switch fallbacks on/off

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10054]
We have been considering ways to make Input NG a bit less intimidating to new users and users of the existing shortcut system (in 3.6 and earlier), and to make it easier to cover in the user manual.

While the fallbacks system is powerful for people that want to use it, it can also add an extra layer of complexity that might confuse people already somewhat overwhelmed by the move to the new system (I think some people might even find the existing 3.6 system complicated).

The fallback system also adds an extra risk of unintended consequences. Even on the existing system I find myself inadvertently pressing keys that do something unexpected. For example, I map Ctrl+S to the module search but occasionally I miss the Ctrl key and enter slideshow mode by mistake. For this reason I have disabled a lot of pre-mapped shortcuts in 3.6. Fallbacks, for me, just add another set of things that might happen without me intending them to.

For people that only want to use shortcuts for a few minor things (changing the exposure being a common one) disabling the fallbacks will significantly simplify the interface.

I would like to suggest a new preference be added (to preferences > miscellaneous, alongside the module instance shortcut prefs) named "enable shortcut fallbacks". This preference should be disabled by default (which will make input NG function similarly to how the old system worked albeit with some bells and whistles).

If this option is un-ticked, the fallback actions should no longer be executed or displayed in the shortcut setup window. They should still be present (for when the user enables fallbacks) but hidden and non-functional.

This will also allow for fallbacks to be covered independently in the user manual (as an "expert" mode) making it easier to consume in smaller chunks.

**Comment by dterrahe** [comment]
I would add a checkbox in the shortcuts dialog, between the search boxes and the imexport buttons. Discoverability and such.

**Comment by elstoc** [comment]
Sure. Makes sense to me.

**Comment by dterrahe** [comment]
> For people that only want to use shortcuts for a few minor things (changing the exposure being a common one) disabling the fallbacks will significantly simplify the interface.

People who just want to use E+scroll to change exposure would do:
1. click shortcut button
2. move mouse to hover above exposure slider
3. press e
4. right-click to disable shortcut mapping mode

> This will also allow for fallbacks to be covered independently in the user manual (as an "expert" mode) making it easier to consume in smaller chunks.

The non-expert mode was meant to be the point-press approach described above. The reason the dialog is intimidating is because the _whole_ of it is "expert" mode. Yes, there are some shortcuts (the non-widget ones) that can only by set via the dialog, but a lot of those have defaults and are any of the others _required_ for beginners?

For the avoidance of doubt, switching off fallbacks would mean that in the above scenario the user would have to do:
3. press e and scroll
because moves (including scroll) are set up as fallbacks and without them you have to explicitly specify them in the shortcut itself.

**Comment by elstoc** [comment]
Understood. It's a case of ease vs simplicity. The fallback mechanism makes it easy to set up multiple shortcuts but it does so at the expense of making it more complicated to understand all of the stuff you've set up simply by pressing "e".

**Comment by dterrahe** [comment]
> Just pressing "e" would still enable the default action though (popup the edit for a slider)?

Yes.

But I use slider shortcuts for the "side effects", hardly ever for the default effect.

> We certainly need to think about any unintended consequences of this option though

One of those consequences would be that different people would use systems that behave wildly differently. Making support more difficult (finding out after pages of back and forth that neither side realised that the "bug" was caused by a different setting of the switch.) In this particular case, _hopefully_ it would be immediately obvious (but it should be an extra question in the bug template for people to ignore). But if we add more switches (with possibly "interesting" interactions), this will impose a very real cost. Also in less testing for all the different corner cases.

**Comment by dterrahe** [comment]
> Just pressing "e" would still enable the default action though (popup the edit for a slider)?

It doesn't hurt clarifying this again.

There are two separate default effects:
The first in the drop-down is used for **key presses**
The 2nd and 3rd are used for **moves** (up and down).

So if you map e+scroll to exposure, scrolling generates up and down effects.

If you map e to exposure, pressing (and releasing) e generates an edit effect (the popup).
Adding a scroll (with fallbacks disabled) would just give "e+scroll not assigned".
The generic move fallback says you can add any _move_ to a defined _key_ shortcut and immediately generate up/downs (next/previous etc)

**Comment by elstoc** [comment]
I'm just trying to find ways to limit the complexity. After 2 days now I'm still struggling with it.

**Comment by todd-prior** [comment]
Might be worth having a debug mode related to presets that would allow you to temp run DT on default mapping or shortcuts to try to sort out and issue. I guess you could just run with a new blank config but the debug mode would change only the presets?? If I am making any sense....People could develop a pretty sophisticated set of presets that might be hard to navigate but easier if all set to default just to trouble shoot....

**Comment by elstoc** [comment]
I think you can just delete/rename shortcutsrc

**Comment by dterrahe** [comment]
In the shortcuts dialog, you have export/import buttons (to save/restore your current settings) and a restore button that allows you to reload defaults (and if you tick the  "clear" checkbox, you'll have _just_ the defaults).

But yeah, you can just delete shortcutsrc as well and then restart. With the "restore" button you don't have to restart...

Let me know if you have any suggestions to make this more discoverable.

**Comment by todd-prior** [comment]
Ah you can tell I don’t have a shortcut riddled workflow…😊
