### ISSUE TITLE
documentation: Windows tools

### ISSUE THREAD

**Issue by audioscavenger** [darktable-org/darktable#10093]
**script tools for Windows**
- common.cmd
- darktable-generate-cache.cmd
- purge_non_existing_images.cmd
- purge_unused_tags.cmd

**Environment: library on Windows**
- library.db is by default under %LOCALAPPDATA%\darktable - not %APPDATA%\darktable as indicated at https://www.darktable.org/about/faq/#faq-windows-config

**How is the mipmap directory name matching the selected library generated on Windows?**
- the script purge_from_cache.sh indicate that `cache_dir=%cache_base%\mipmaps-%sha1sum%.d`
- when i calculate the hash with the correct Windows path ==` %LOCALAPPDATA%\darktable\library.db` i get a different hash

**Comment by Nilvus** [comment]
Your issue is not clear and this place is for darktable code an no more for manual.
If you suggest some update for faq in link you cited, please post it in website repository: https://github.com/darktable-org/dtorg
If it's for usermanual, then the good repository is: https://github.com/darktable-org/dtdocs

Of course, if possible, it's better to propose a pull request for any updates than an issue in related repository.

Think about closing this issue before posting in the good repository.

**Comment by audioscavenger** [comment]
i will try and find the correct repo
