### ISSUE TITLE
Color Calibration module - Temperature discontinuity at 4000K

### ISSUE THREAD

**Issue by NenadBrkic** [darktable-org/darktable#10135]
There is a discontinuity while using _temperature_ slider in **Color Calibration module**. When **D (daylight)** is selected as an illuminant, it gradually changes color temperature up to 3999K. Once it reaches 4000K, the colors change significantly, sometimes leaving a sweet point of WB unreachable.

It happens even when **Color Calibration** is the only active module. All adaptation methods are affected with this issue.
The issue arise when OpenCL is enabled and also when it is disabled.

I deleted _~./config/darktable_, but it didn't solve the issue.
I tried Nikon & Canon RAW files - the same issue happens.

![Untitled](https://user-images.githubusercontent.com/91759082/135698465-3782adfc-16b3-4749-8bc7-a3e4ed683930.gif)

===

**Darktable 3.6.1 (Latest) - built from source code**
**Non-standard tweaks**: Not used

**OS**: Ubuntu 20.04.3 LTS
**Device**: Acer Nitro AN515-52
**CPU**: Intel® Core™ i5-8300H CPU @ 2.30GHz × 8
**RAM**: 16 GB
**GPU**: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile]

**Comment by wpferguson** [comment]
At Daylight and 3999, if I convert to custom hue is 40.2 and chroma is 28.7.  Going back to daylight and setting temperature  to 4004 then converting to custom shows a hue of 49.7 and a chroma of 29.2.  I'm not sure if this is "wrong" or just how color calibration works.

**Comment by Mark-64** [comment]
it seems a glitch to me.
When slowly moving the slider (with right-click) the CCT switches briefly from daylight to black body when crossing 4000K and then back.
But if I set 4000K by typing the value, it stays on daylight.

**Comment by NenadBrkic** [comment]
@wpferguson, according to a diagram that @aurelienpierre presented in [https://www.youtube.com/watch?v=706r4PNv-wg&t=10s](url) at 12:15, we can see a very smooth curve without any kind of glitch... So, I still think that we have wrong behavior of Color calibration module.

**Comment by aurelienpierre** [comment]
There is a temperature discontinuity at 4000 K because daylight illuminant is not defined at T < 4000 K so we switch to blackbody illuminant when T < 4000 K. There is nothing we can do here, because daylight simply doesn't exist below 4500 K or so, such that 4000 K is already an extrapolation, and pushing it further would be completely meaningless.

> @wpferguson, according to a diagram that @aurelienpierre presented in https://www.youtube.com/watch?v=706r4PNv-wg&t=10s at 12:15, we can see a very smooth curve without any kind of glitch... So, I still think that we have wrong behavior of Color calibration module.

@NenadBrkic that curve is something completely different.

As confusing as it may be, this behaves exactly as it should. The most we can do is to clip the temperature range in GUI to 4000 K, but that causes other issues in case people want to switch between illuminants and still keep their temperature setting.

**Comment by NenadBrkic** [comment]
Thanks @aurelienpierre for clarifying this! :) I'll close this topic...
