### ISSUE TITLE
Strange behaviour when Copy & Import,/Add to Library on Windows 10

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#10232]
The new **copy & import** function is behaving very odd
on Windows 10. I have no idea if it is the intended behaviour or if

Something is just weird. For it is very unlogic compared to how other programs behave.
Let me try to explain:

1. I have a folder with some raw photos. It is in a local drive but in another location than my imported photos in DT.

2. I use the naming structure **$(EXIF_YEAR)-$(EXIF_MONTH)-$(EXIF_DAY)**

3. I select **copy & import** and all seems to go fine. When I look in the filesystem I can see that they have
     been moved to the location I want them to end up in. But when I use the **Collection/Files/folders** the new folders does not
     appear in DT.

4. Then I go to the **add to library** function and select the newly created folder and file and add them to DT once more.
     This is really problematic as I can not select a number of folders but have to repeat this for every new folder. 
     Normally you can just shift+click to select an interval of folders. Now I can see the folders in DT when using **Collection/Files/folders.**

5. When I restart DT I often (but not always)  get a popup window asking if I would like import the last imported files based on the sidecar files.

For me this behaviour is very odd and I think if I select **Copy & Import** all should be done in one sequence. Create
folder based on the naming structure, move the files, import them to DT database and update the folder/file-structure in **Collection/Files/folders.** And it should really be possible to select more than one folder in the import workflow.

**Platform**
* darktable version : 3.61
* OS                :  Win10 19042.1288

* Memory            : 32 GB
* Graphics card     : Gigabyte GeForce RTX 2070 SUPER OC 3X
* Graphics driver   : 30.0.14.9613
* OpenCL installed  : yes
* OpenCL activated  : yes

**Comment by Nilvus** [comment]
Of course, import module had been to designed to do all in one sequence when using copy & import. What you have seems to be a bug. But, we have had some issues posted quickly after 3.6.0 release in import in Windows fixed in 3.6.1 and no issues since yours in 3.6.1. So or it's a specific remaining one related to some specific config/use ones or something only related to your specific config. Could you precise an example of precise origin and destination path on which you have your issue? Could be related, maybe, to some specific path... or not... to check.

**Comment by Mark-64** [comment]
Yes, I can have a look, but I need from @bengtfalke more details on the folder structure that creates the issue, a screenshot of the Copy & Import dialog would help
