### ISSUE TITLE
problem with perspective module and ctl-z

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10294]
3.6.1

In darkroom mode:
- show perspective correction module
- click on automatically correct for vertical perspective distorsion or on analyze line structure in image
- ctl-z
- click again on automatically correct for vertical perspective distorsion or on analyze line structure in image

-> you get "data pending - please repeat"

moving back to previous image which has the perspective correction and the crop and rotate modules applied, you get it without cropping

**Comment by Nilvus** [comment]
This module will be deprecated for 3.8 and replace by a whole new module which will mix perspective one and rotation part from crop and rotate module. That last module will also be deprecated and be replaced by a crop only module one. This had been done because of some issues:
- they had wrong place in pipe
- and code being hard to maintain/update without breaking old edits
- and some other as I remember

See:
#8834
#8838
#9456

I so close as this will not be fixed.

**Comment by paolobenve** [comment]
> This module will be deprecated for 3.8

The same issue is present in an identical manner in rotate and perspective module (I updated the issue title).

I think that this bug can be reopened

**Comment by Nilvus** [comment]
> > This module will be deprecated for 3.8
> 
> The same issue is present in an identical manner in rotate and perspective module (I updated the issue title).
> 
> I think that this bug can be reopened

As written, this module is deprecated, so no bug fix. Use modules that replace it.
