### ISSUE TITLE
importing into existing film roll/directory

### ISSUE THREAD

**Issue by tpapp** [darktable-org/darktable#10315]
**Is your feature request related to a problem? Please describe.**

I would like to be able to *import images into existing film rolls (directories)*. This would help with, for example, incrementally importing photos for initial sorting and backup during traveling.

**Describe the solution you'd like**

Allow selecting an existing directory in the *copy & import* dialog.

**Alternatives**

A workaround is possible: manually copy images into an existing folder, then make darktable import them. This is a minor inconvenience, but this feature would simplify the workflow.

**Additional context**

Cf [discussion](https://discuss.pixls.us/t/import-into-existing-film-roll/27679).

**Comment by Nilvus** [comment]
It's already possible with copy & import button by using in jobcode exact same name as destination filmroll. It's just also depends on variables you use to import. It's also possible to import then move images directly in darktable with options in lighttable right panel.

**Comment by tpapp** [comment]
Thanks, I understand there are several workarounds, this would just be a convenience feature.

**Comment by Nilvus** [comment]
> Thanks, I understand there are several workarounds, this would just be a convenience feature.

It's not a workaround but a feature. Just use same jobcode and you import them in same filmroll (as said, depending on variable you use ; for example, I class my photos by year, month-year then jobcode, so of course when importing photos with same jobcode, they go in same folder/filmroll only if they have same jobcode in same month-year. And that's absolutely normal behavior. So what you want is already possible. Of course, I understand that a selectable way could be another possibility. So a feature to add but with a low priority because it is already possible, not by workaround but existing feature available for such use. What you want would just be a third way to do that.
