### ISSUE TITLE
Xmp - for the film roll 

### ISSUE THREAD

**Issue by Jopp-gh** [darktable-org/darktable#10362]
**Is your feature request related to a problem? Please describe.**

Usually I didn't save xmp files, because this creates too much clutter in my (film roll) folder 

**Describe the solution you'd like**

I never edit single images. And I assume, nobody working with Photography shots just a bunch of images. 
First I apply an adeguate style in batch then I fine tune, revise each image, adding bad/mediocre pictures to the stack of rejected images 

Lately, i considered backing up xmp files, but the current implementation is rather cumbersome. I wish we could save xmp files for a whole film roll, not for each and every photo. 

**Alternatives**

Currently i put xmp files in a folder inside my film roll and add inside, a screenshot of all the thumbnails of my film roll

**Additional context**

Please let us users decide if we want xmp files per file or film roll

**Comment by todd-prior** [comment]
I don't really follow you but why not just set them as hidden if they bug you and then they stay with matching raw files but you won't see them???

**Comment by phweyland** [comment]
> Lately, i considered backing up xmp files, but the current implementation is rather cumbersome. I wish we could save xmp files for a whole film roll, not for each and every photo.

Select the images, history stack / write sidecar files, all at once.

**Comment by todd-prior** [comment]
I am on windows…I have a little program called autover which watches my folders and versions my xmp files. I back up that folder created by autover. I now have every edited version of the file that I have ever done backed up…you can set the extent of the versioning…

As for folders I export using a file export syntax so it creates a folder that mirrors the raw file structure identically in a parent folder called edits….I don’t open this with DT so no xmp files get created and I use it for sharing and viewing my images on my phone or other so that there are no xmp files to deal with and I don’t corrupt DT by doing external file management if I delete something..….

**Comment by johans3** [comment]
> > Lately, i considered backing up xmp files, but the current implementation is rather cumbersome. I wish we could save xmp files for a whole film roll, not for each and every photo.
> 
> Select the images, history stack / write sidecar files, all at once.

Thanks @todd-prior , but I'm on Mac.

@phweyland 
I know the button to write all xmp files at once.

But my request is, to save all modifications of all images of a film roll in one (1) xmp file.
20 pictures - - > save history of all 20 pictures - - > 1 xmp file

**Comment by phweyland** [comment]
> my request is, to save all modifications of all images of a film roll in one (1) xmp file.
> 20 pictures - - > save history of all 20 pictures - - > 1 xmp file

Understood.

**Comment by todd-prior** [comment]
Won't work....


Get Outlook for Android
