### ISSUE TITLE
.FITS RAW file format for Astrophotography

### ISSUE THREAD

**Issue by FireNWater** [darktable-org/darktable#10371]
**Is your feature request related to a problem? Please describe.**
No

https://skyandtelescope.org/astronomy-blogs/imaging-foundations-richard-wright/astro-imaging-fits-format/

https://fits.gsfc.nasa.gov/fits_viewer.html

**Describe the solution you'd like**
Incorporate .FITS file format into darktable for subsequent processing in GIMP.  Lots of astrophotographers out there. . . 

**Alternatives**

**Additional context**

**Comment by ralfbrown** [comment]
Since dt can use ImageMagick/GraphicsMagick to load images, and at least IM supports FITS, it should just be a matter of adding the extension to the whitelist to support un-mosaiced images.  If the FITS file contains mosaiced data, it would take a lot more work to integrate, since the IM/GM support code is strictly for non-RAW images.

**Comment by kmilos** [comment]
FITS also supports bit depths greater than 16-bit and floats as well, so IM/GM would be a potential bottleneck here...

This probably means a new reader based on [`cfitsio`](https://heasarc.gsfc.nasa.gov/fitsio/).
