### ISSUE TITLE
Apply several style in series

### ISSUE THREAD

**Issue by GustavHaapalahti** [darktable-org/darktable#10434]
I would love to be able to apply several styles in series, for example make a style for some kind of base look and then apply another style after that without changing the main pipeline module settings. 

One solution would be to support several pipelines in series which you could add/remove, similarly how you can duplicate modules, but in this case you make a whole new pipeline where you can apply the "same" modules again, etc.
Another way to do this could be to make a module that can apply other modules, call it a style module if you will, then you can duplicate that module and apply several styles in the duplicated style modules.

I just thought this could be a cool and powerful feature.

**Comment by ralfbrown** [comment]
If your style contains named module instances, they will be applied as additional instances (unless an instance with that name already exists).

**Comment by GustavHaapalahti** [comment]
That's good to know thanks. 
Still it doesn't solve all the problems, for example applying a style twice or using an imported style that someone else made.

**Comment by MStraeten** [comment]
I interpret your feature request as an additional mode:
create new additional instances with a custom pipeline order for each module in the style

in  more then 95% of cases  this would mess up more than it brings benefits since it mixes scene referred and display referred parts of the pipe.

If you want this just to apply a look then you‘d better define luts instead of styles (btw: there’s a lua script for that)
