### ISSUE TITLE
documentation: Example images in docs?

### ISSUE THREAD

**Issue by will-ca** [darktable-org/darktable#10438]
**Which new feature or section need to be documented/updated**

What appear to now be obsolete versions of the documentation had a lot of example images in it:

https://darktable.gitlab.io/doc/en/modules.html

https://web.archive.org/web/20200111220403/https://www.darktable.org/usermanual/en/color_group.html

https://web.archive.org/web/20201111200853/https://www.darktable.org/usermanual/en/correction_group.html

https://web.archive.org/web/20201123144148/https://www.darktable.org/usermanual/en/module_groups.html

https://web.archive.org/web/20201111193625/https://www.darktable.org/usermanual/en/tone_group.html

https://web.archive.org/web/20200509201527/https://www.darktable.org/usermanual/en/effect_group.html

I personally found these really useful. It made it easier to scan through the docs to find which modules might give the effects I wanted, and when the module in question had non-obvious behaviour, it made it easier to understand what was going on.

Is there any chance of bringing these back? It looks like all the work to create and write captions for the examples has already been done anyway; It would be a shame to lose this resource.

![image](https://user-images.githubusercontent.com/37680486/142572410-7e7b697a-712f-47b4-a719-a3639e9b8bdf.png)

![image](https://user-images.githubusercontent.com/37680486/142572461-146b47e1-5623-4d92-9f13-2a3f3b70feb9.png)

![image](https://user-images.githubusercontent.com/37680486/142572531-fe6fab85-839d-4428-85dc-43207620ff15.png)

**Comment by elstoc** [comment]
This is a conscious (and much-debated) decision to reduce the amount of maintenance required and to improve the experience for translated manuals - since any images with text in them (screenshots of the modules) cannot be translated. The manual assumes that the user has darktable open in front of them (so can already see the module layout). Also, a lot of the images and examples were against modules that are no longer recommended and including the images was more likely to direct people to those modules.

We believe that we have included images in the new manual where they add to comprehension but are open to discussion if you want to argue for the usefulness of a particular set of guides. We will still very much err on the side of no images where practical, so a general "please put all the images back" discussion will likely go nowhere.

Either way this is not the correct repository for issues with the user manual - you need to raise an issue against the [dtdocs repo](https://github.com/darktable-org/dtdocs/issues)
