### ISSUE TITLE
Click on slider label should give the focus and not change the value

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#10478]
Currently, if you click anywhere inside the rectangular bounding box of a Bauhaus slider, the value will get changed using the x coordinate of your click, even though you are very far from the sliding bar (including a click on its label).

At the same time, the only way of giving focus to a slider is to click on it. Which means you can't give the focus without changing the value. 

But you may want to give only the focus to the slider in order to use arrows and MIDI controllers to actually change the value.

I propose that : 

1. any click outside of the sliding bar ± a safety margin does not record a value change, but only gives focus to the slider for later interaction,
2. a click on the numeric value directly opens the keyboard input/accurate selection widget (touch interfaces may not have right click),
3. in-focus sliders get a style hint, for example a different background & text color,
4. dynamic shortcuts (allowing to access directly a slider through a key) also give the focus to the slider.

**Comment by dterrahe** [comment]
I just submitted a fix for 1 and 2. It seems 3 is supposed to work, but somehow doesn't (maybe due to lack of CSS; it does however briefly show the label and value in bold when changing the value via the popup).

4 is imho not a good idea. If I already have the slider mapped to a "dynamic shortcut" so I can change it via key+mouse wheel, why would it then also focus so that it grabs the arrow keys? That just means that to scroll the center view via keyboard I will need to explicitly click on it to focus again.
