### ISSUE TITLE
prevent shortcuts on deprecated modules

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10477]
A number of deprecated modules appear in the shortcut mapping tab of the preferences screen. We should probably consider preventing people from assigning shortcuts to deprecated modules, or at least have a "hard-deprecated" flag so that we can remove some of them (olde worlde filmic for example). Similarly for the quick access panel.

**Comment by TurboGit** [comment]
Right, I'm leaning toward removing all shortcuts as soon as a module is deprecated. No need to introduce a hard-deprecated. When we deprecate a module we really want it to out of the GUI completely (with a small window where it is still in the deprecated group).

**Comment by dterrahe** [comment]
Just thinking out loud: my first response was; simple, just don't set up actions if the module is deprecated. But then thinking a little longer, that would also disable lua bindings for those modules. And in theory, those would still be nice to have, because then you could build a simple lua routine that reads slider values (via actions) from the old, deprecated, module, disables the module and then initialises the replacement using those values. Might be nice for people with a large database using those modules and a lua routine would be much easier for individual users to customise if needed/wanted. Rather than having one precooked migration in c that might have to make arbitrary choices. I'm thinking of a migration path for crop/rotate.
