### ISSUE TITLE
Drawn + Parametric mask combining

### ISSUE THREAD

**Issue by dweebler999** [darktable-org/darktable#10488]
Hi - I may be stupid but I find combining drawn and parametric masks utterly confusing! Almost always, I simply want to use a brush or path to add to or subtract from a parametric mask.....is there any easy way of simply having a single button to ADD to the mask with a brush or path, or SUBTRACT from it. I know it can be done, but the correct selection of polarities and combinations always defeats me.

Sorry if this is posed in very untechnical language!

**Comment by elstoc** [comment]
You might be able to do something in Lua. The only alternative might be to write yourself a cheat sheet: `inclusive=add; exclusive+inverted drawn mask=subtract`

I'm happy to add some examples to the user manual if you think it would help

**Comment by dweebler999** [comment]
Thanks for replying so quickly, but you are sadly talking to the coding-illiterate. I have no idea what Lua is. And the idea of actually writing code terrifies me....just not the way my mind works. I was hoping it might be addable as a feature?

**Comment by elstoc** [comment]
The problem is that the two examples you have given are only two possible ways of combining masks. When you get more than two variations, the buttons become a drop-down, which is what we have.

**Comment by dweebler999** [comment]
I guess my point was more that a much simpler way of getting to that combination would be great....it really isn't easy as it is, and is about the only part of darktable which has me tearing my hair out!

Would it help if I made a mock up of what I would love to see? 

Just to say, both para and drawn tools are brilliant, it's a matter of being able to use them together.

**Comment by elstoc** [comment]
> Would it help if I made a mock up of what I would love to see?

If you like. It won't be me implementing it (if it gets implemented at all) but it helps to have as much information as possible.

**Comment by dweebler999** [comment]
![image](https://user-images.githubusercontent.com/95092792/143677002-a6f2043b-f75c-4ea9-b89f-d91c5ca469d0.png)
Can you see this? Really very simple....effectively a version of drawn and parametric where the only options on the drawn mask are whether it subtracts from or adds to the para mask.....

**Comment by elstoc** [comment]
It _looks_ simple but when combined with all of the other options it just adds confusion in my opinion and is potentially hard to develop -- for example a "subtract drawn from parametric" option would have to ensure that (a) the drawn mask is inverted; and (b) the combine masks drop-down is set to inclusive. Then you'd need a lot of extra options for all the other variants you haven't asked for (for example "subtract parametric from drawn").

But then what happens if the user has created the drawn mask by drawing a circle and then inverting it? What was the user's intention in that scenario. The problem is that the drawn mask functionality has to function independently of the parametric mask functionality (assuming that inversion is intended to be _part of the resulting mask_). So the idea is that you (a) create the parametric mask (including optional inversion); then (b) create the drawn mask (including optional inversion); then (c) combine them using the combine masks drop-down.

Any option that automatically inverts one or more mask makes assumptions about the user's intention that may not be correct.

I do agree that the names of the existing "combine masks" options can be confusing so I can see an advantage in possibly renaming them but unfortunately to keep the flexibility all these options are required. I don't know what a better naming would be though.

**Comment by todd-prior** [comment]
@dweebler999 I went through this one time and tried to summarize it... I think your simple use case is pretty easy to remember as @elstoc  noted but for sure it can be confusing...I always tried to keep the math in my head so thinking of the mask as binary ie 0 for off and 1 for masked or on. Then then combining the drawn with parametric and you overlap them then there are area's of you image where both are zero and where one is unity and the other is zero and where both are one. The chosen mode with treat them such that in some cases you will only have a mask where both are 1 or it can be that the mask will include areas where either mask is 1....everyone just has to come up with a way that makes sense to them to visualize it ....For me I have an issue that the drawn masks start out showing a negative polarity and the parametric masks start as positive. I have come to just understand this but to me it doesn't make sense that in exclusive mode your mask will be the overlap of the two ie where both equal 1 but the drawn mask starts with a negative polarity that I equate with zero....anyway if you spend a little time it becomes fairly easy to get the mask you want....

**Comment by todd-prior** [comment]
> (b) the combine masks drop-down is set to inclusive.

I am curious, one thing I noticed recently (and I am not sure at this point that I can think of all the potential combinations), but I had thought inclusive and exclusive was just impacting the interaction between final drawn and parametric masks but it seems it also impact the channels of the parametric mask if that parametric mask is the result of more than one channel. I thought the parametric channels were always an "and" operation and inclusive and exclusive was reserved for the combining of the drawn and parametric mask.  

In trying to rationalize how this all would come together in certain instances , it may be that this setting should be independent as I suspect there could be a possible combination where you want the drawn and parametric masks to combine in one way and the the parametric channels to interact the opposite??  

So for example if you have to set inclusive or exclusive mode as you were mentioning above to get the drawn and parametric masks to interact the way you want, might this not alter the parametric mask if it was created using a different method and this will now change the parametric mask selection??  Maybe this is a non issue as the situation would be rare or I am overlooking something but if not then perhaps the parametric channels need a separate mode selector to fully control each channel independent of mode selected for combining with the drawn mask.

Just thinking out loud....I guess I need to try and create a working example to visualize this.
