### ISSUE TITLE
Same double click behaviour in Crop and Rotate

### ISSUE THREAD

**Issue by svenakela** [darktable-org/darktable#10486]
In the latest version (built locally) the Crop and Rotate are now two different modules. Now we have `crop`, and `rotate and perspective`.  The original behaviour was to double click the photo to finalise the changes. This is still the behaviour in `crop`.
In `rotate and perspective`I have to leave the module pane (i.e. click on another module) to activate the changes.

**Describe the solution you'd like**
I like the double click and it would be awesome if both modules adopted the same function.

**Alternatives**
in any case, it would be more logical if both modules have the same workflow. Being double click or not they are different now.

**Comment by AlicVB** [comment]
oh that feature is still present in crop ? I thought I have removed it some times ago...
iirc double-click to "apply" the crop is not really stable because it's in fact "playing" with the module focus which can left the module in an "intermediate" state in some cases.
I will look at this... (but I tend to go for removing the double-click)
