### ISSUE TITLE
Resume rating score in images previews

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#10503]
In past (before recent changes to lighttable, that are the subject of this ticket) I always rated with a red X the images that I had to erase. After having setted a score to all of them, I:
1) opened the lighttable view (probably the file manager view and/or culling)
2) sorted them by rating
3) then selected all the X rated images helped by the previews that showed rating when user passes the mouse over the image
4) erased the selected images
Now this is no longer possible because the only mode that shows images rating in their preview, while passing the mouse pointer over the image, is the culling mode, but such mode is so uncomfortable when it comes to mass select images.

So with this ticket I am demanding to resume the rating score preview on the images preview, in filemanager layout and zoomable lighttable layout

**Comment by Germano0** [comment]
Mah, after doing some editing, the rating previews resumed in file manager layout. They are still missing in zoomable lighttable layout. I think it may be a glitch

**Comment by dterrahe** [comment]
It is easier to select all rejected images by switching the "view" dropdown at the top to "rejected only" and then pressing Ctrl-A. 

Or are you after something else?

**Comment by AlicVB** [comment]
@Germano0 : if I understand correctly, the issue is that you don't see the rating stars+cross in lighttable, right ?
in this case, I think you have to play with the thumbnails overlays (https://darktable-org.github.io/dtdocs/en/overview/user-interface/top-panel/)
remember that the overlays settings are size dependent, so you can set different overlays for different thumbnails sizes. They are also dependent of the view mode. That may explain the differences you have between classic and zoomable...

**Comment by Germano0** [comment]
Indeed I found out that if I set 24 as zoom level I can see the ratings. If I set 25 I can no longer see the ratings.
We can close the bugreport since "it works for me".
Thank you
