### ISSUE TITLE
scene-referred workflow pipeline filmic rgb gets deleted from pipeline and right panel

### ISSUE THREAD

**Issue by dnlyko** [darktable-org/darktable#10547]
Open an image and the white balance is off so I correct it like this...
On the left panel pipeline history I select number 6 white balance
filmic rgb disappears from the right panel active modules list
On the right panel active modules list I select white balance module
I select the eye dropper and filmic rgb disappears from the left panel pipeline history

I tried it this way because when I try and edit the white balance by...
selecting white balance on the right panel active modules list
I select eye dropper then we get RED WARNING white balance applied twice and two read boxes beside color calibration and white balance on the right panel active modules list

![1](https://user-images.githubusercontent.com/38403574/144538235-4777bc35-c9fe-4b71-b009-ae7145232ed3.jpg)

**Comment by elstoc** [comment]
I think you are misunderstanding how the history stack works. If you click on item 6 (white balance) you have reverted to a point in your editing history (here, the modules that were automatically added by darktable) before filmic existed in the pipeline. Any edits you do after selecting item 6 will _intentionally_ destroy entries above that point in the stack.

It's hard to see why the warning message appears because you haven't shown the remainder of the white balance module in the screenshot. I suspect, though, it's because you have selected "modern" workflow in your preferences and you are using the wrong module to amend the white balance. With modern workflow you should correct white balance (chromatic adaptation) in the color calibration module and not the white balance module. Use of the white balance module for adjusting the white balance is the legacy approach. I suggest that you head over to the [user manual](https://docs.darktable.org/usermanual/3.6/module-reference/processing-modules/color-calibration/) to read up on this subject.

**Comment by dnlyko** [comment]
Thanks for taking the time to clarify that.  My bad.  I have been putting off reading the manual until the next version is released and then I was going to dive into it.  Yes I have 'modern' selected.

I mostly do live concert photographs that generally have all different light sources at once.  Getting the proper white balance is my biggest challenge and has always been my first step in my workflow.

**Comment by elstoc** [comment]
The color calibration module is best suited to managing white balance with multiple light sources (since it can be duplicated and masked). On that basis are you satisfied that there is no bug here and the issue can be closed?

**Comment by dnlyko** [comment]
Thanks, no bug here, just my ignorance is all.
