### ISSUE TITLE
Location of Contrast Equalizer in the Pipe Line

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#10546]
If the Contrast Equalizer is located prior to Filmic-RGB in the Pipe-Line then the Auto-Tune function of filmic does not function correctly.

I have been using the CE (with a preset) as a part of my standard processing for all images and have found that filmic misbehaves in the placement of the black slider. The black slider is always deployed at the extreme left hand side when auto-tune is used and I need to then manually correct the position.

The problem appears to be solved by moving CE in the pipe-line to be above filmic.

I do not know if this movement is detrimental to the designers overall processing strategy.

**Comment by aurelienpierre** [comment]
It's shit.

CE is a frequential operator that most users will use to sharpen and boost local contrast. There are different kinds of sharpening, but the most usual one is lens deblurring. Which means it should go in the linear part of the pipeline because lens blur happens on light, and scene-referred RGB is the closest to actual light we can get in a pixel pipeline. And that is why it goes before filmic by default.

But CE works in CIE Lab 1976, which is non-linear perceptual and display-referred. Which should be more suitable after filmic indeed. Which doesn't fit the lens deblurring use case at all.

So I don't think there is a solution here. 

In any case, you can make your own pipeline order presets and you can reorder the pipeline on a case-by-case basis, which is meant to specifically deal with these different use cases. You don't have to stick to defaults. And that's probably the best I can offer you.

Or… darktable 3.8 will introduce the _diffuse or sharpen_ module, which covers the same use cases as CE at the price of being much slower, but will work in linear scene-referred RGB instead. There are sharpening presets in there too.

**Comment by davidvj** [comment]
Closed the issue based on comments/explanation from aurelienpierre
