### ISSUE TITLE
unable to update a style 

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#10553]
after changing some settings in an image it's not possible to update a style based on this settings.

**To Reproduce**
1. define style
2. edit image, change settings of a module in the style
3. back to lighttable select edited image (click by mouse on it so it's highlighted)
4. select style, click on edit, select module to be updated, save
5. apply style to a different image
6. check settings of the module in darkroom
7 see error: unchanged settings are applied

**Expected behavior**
changes are taken over to the style

**Platform**

* darktable version : darktable 3.7.0+1614~g234334b5d-dirty
* OS                : OSx

**Comment by elstoc** [comment]
Reproduced on 3.7.0+1618~gda41f6724 on ArchLinux

**Comment by TurboGit** [comment]
I'll have a look. If you have bisected the commit introducing this issue it will help.

**Comment by TurboGit** [comment]
Note that this has been broken already... It seems that this part is fragile. I think it is almost release critical, so we need a fix for 3.8.

**Comment by elstoc** [comment]
>  If you have bisected the commit introducing this issue it will help

I don't know when this was last working as I've only just started using it when playing with white balance and diffuse presets. So even finding a start point for a bisect is difficult. I tried looking at the code but it's a bit hard to read.

**Comment by paolodepetrillo** [comment]
If I revert e667799 it seems to work in master. I didn't test the issue with multiple instances that the commit was intended to fix though.

**Comment by paolodepetrillo** [comment]
Not sure how this is supposed to work with multiple instances of modules, there are some nasty corner cases.. what do you do if there is a style created from one image with two instances of a module, and now someone wants to update one of those instances from an image that also has two different instances of that module; which one would be the source?

I guess the last resort fix might be to disable the update feature and instruct users to perform an edit in two steps by first removing the module from the style and then adding it back in.

**Comment by paolodepetrillo** [comment]
When the list of history items in the edit style dialog is populated from `dt_styles_get_item_list`, the NUM field for each item is set to the num of that item in data.style_items table, and the UPDATE_NUM field is set to the num of the most recent item of that operation in the currently selected image's history stack.

When the style is updated in `_dt_style_update_from_image`, upd->data (from UPDATE_NUM) is used to identify the item to get from the selected image's history stack, and list->data (from NUM) is used to identify the item in the style to be updated.

The e667799 change swapped list->data and upd->data causing the update function to stop working.

Regardless of this change, it seems like updating multiple instances never would have worked, because each style item that was selected for update would always take the params from the most recent item of that type of operation in the selected image's history, regardless of multiple instances.

**Comment by MStraeten** [comment]
can confirm the analysis above: my build from 28.3. (darktable-3.5.0+1603_g0ea35a5e54) was fine, from 6.4. (darktable-3.5.0+1649_g20585f7688) reproduces the issue. There was just one commit affecting styles in between ...

**Comment by TurboGit** [comment]
Thanks a lot for the hint on the wrong commit. This has definitely helped a lot to have a fix this morning.

Can you try #10555 ?
