### ISSUE TITLE
Number Pad Not Active while rating in LiteTable

### ISSUE THREAD

**Issue by dnlyko** [darktable-org/darktable#10628]
Windows insider version

**Comment by Nilvus** [comment]
Please precise which exact version/commit you use? Be more precise please on your issues. We set a precise template to follow for good reasons. If too much issues are posted without so few versions, we could close them without discussion. So few infos do not help darktable team to help fix issues...

If it's, as I suspected, you use master, you just have to set them in shortcuts dialog window. Some shortcuts are set by default, not all users can/want to use. that's why is customizable. Anyway, in case of, I ping @dterrahe as he works in new input system if he see something else.

**Comment by dterrahe** [comment]
The new input system allows assigning multiple shortcuts to be assigned to the same action. So if you want both "1" and "Num1" to set the rating to *, you can do so. Having them not automatically trigger the same action gives the flexibility to assign _different_ actions to them.

There are two ways to assign a key to the star ratings:
- visual mode: click the shortcuts button (next to the settings button), hover the mouse over the 1st (2nd etc) star and press the key you want to assign to it. After you have assigned keys to all stars, right-click to exit mapping mode.
- via the settings or shortcuts dialog: quickest is to duplicate an existing shortcut, so in the shortcuts list find "1 -> rating, one", double-click on it and press Num1. Unfortunately Gtk doesn't provide a different name for both 1s, so they'll look identical.

As an aside, if you have fallbacks enabled in the shortcut settings, you can also press any of the rating shortcut keys and then use the scroll wheel to increase or decrease the rating. So you don't _have_ to assign 5/6 different keys to this function; you could assign only 1 and use the others for something else.

**Comment by Nilvus** [comment]
So, if I understand correctly, we consider so that this just need that the user set shortcuts and so no update/fix here. If so, this so could be closed?
