### ISSUE TITLE
DT 2.6.3 on Windows: Open file from windows-explorer fails, if DT is already running

### ISSUE THREAD

**Issue by mr-mister123** [darktable-org/darktable#10647]
Some times ago i did a fresh reinstall of DT 2.6.3 downloaded directly from this git-repository (prebuild binary for windows 64bit).
If Darktable is not running, you can open raw-files from windows-explorer by double-clicking on them.
If DT is already running, message-window appears, telling that the database is locked trough an already running instance of DT (that's right, i know). but... before reinstalling DT it worked without any problems. Takeing a look at the official (linux-)documentation it says, that if DT is already running DBUS is used to triggger that instance and the file should be loaded in that running instance.
This doesn't work for me with this binary from the darktable github-repo.
But i know it worked before. 

Any ideas?

Greetz,
Karsten.

DT: 2.6.3
OS: Happens on win7 (64bit) and win 8.1 (64bit) - other windows-versions not tested

**Comment by Nilvus** [comment]
darktable 2.6.3 is a really old release. Or your precise a wrong version or so please update it. We are now on 3.6.1 and 3.8 will be released in about a week!

**Comment by mr-mister123** [comment]
Hi, you're complete right, 2.6.3 is a very old version. But... it was working before, thats why i'm asking. I thought, that it may be just a missing compiler-setting or something like this. I would re-compile it on my own then...

I'm a little in a hurry right now, but if i find some time, i'll check if it's working in current 3.8 release - and me be stay on it than (but actually i love the old 2.6x version, for my needs it was just perfect ;-) )

thx,
Karsten

**Comment by Nilvus** [comment]
Ok, so we can't provide support here for such old releases. And if it was working before with same version, that just means it's not related to darktable, or at least not directly. You certainly have some setting in Windows that cause that. On what you describe, instead of opening the file in opened application, Windows try to start another instance. That's why you have this message (database locked) and its a security to avoid launching 2 instances that will work on same database (bad thing). So check on Windows settting how it is set to open files. I can't help more here as I don't use since now since few years and this place is not a direct user support for old versions but a place to post issues to fix in darktable code (and it's not that here, particularly as it's an old version). Check on some Windows forum if a way to avoid Windows to launch again darktable (or any other apps) when opening a file and use opened one. And maybe some help could be possible in discuss.pixl.us forum.

I so close.
