### ISSUE TITLE
More powerful "manual" collections like in LR

### ISSUE THREAD

**Issue by ChristianBirzer** [darktable-org/darktable#10643]
**Is your feature request related to a problem? Please describe.**
It's not really a problem but since I work a lot with LR 6, I'm used to (and use very often) its collections where I can drag&drop images from different folders/other collections etc. into one common "place" to collect them for a certain usage. I know I can do similar things with hierarchical keywords but I think it would be much more intuitive and easier to use to have such collections, including (in a later step) the publish collections where you can link a export setting to a certain collection.
The main reason for my request is that I think the DAM in darktable is still not as powerful as the one in LR but there are not much things that I miss.

**Describe the solution you'd like**
First of all, since I'm a software developer, I would implement it by myself. But I'd like to do it in a way that fits into the concept and gets accepted by the maintainers and community.

I think about an additional side panel on the left side of the lighttable (let's call it "gallery", not to re-use the collection name) where I can add a hierachy of "albums". Then I can drag&drop arbitrary images from the thumbnail view into the albums to collect them. By clicking on an album, the thumbnails get filtered by its content.
There should also be a possibility to define one album as quick-target where you can add images with a single click or key shortcut.
The albums do not store much information, just the link to the image and (later for the publish stuff) a timestamp/last edit tag to determine if a image was changed after publishing (but that's another request...)

I'm not sure if it is best to add a new panel or use the existing collection panel. But since I'd like to navigate through my directories on the harddrive or filmrolls and drag images from there to the albums, it really should be a separate window.

**Alternatives**
Of course, adding tags/keywords to the images could do the job. But this could easily be confusing when you mix up tags that shall be exported with a lot of tags that are only for organizational reasons. Additionally, the browing and filtering through the tags is not as intuitive as browsing through a tree structure of albums.

Of course, the galleries should not break or disturb the way you can work with dt now. All existing filter/tag/etc mechanisms must still work. It's just an additional way to organize your pictures and workflow.

**Comment by MStraeten** [comment]
as long as you don‘t want to move around files on your disk it’s simply a different workflow/ui to assign hierarchical tags. 
Folders or filmrolls are also just a kind of tags since once imported any displayed hierarchical structure is simply database stuff…

**Comment by phweyland** [comment]
> adding tags/keywords to the images could do the job. But this could easily be confusing when you mix up tags that shall be exported with a lot of tags that are only for organizational reasons. 

That's the main purpose of "category" tags (which are not exported).

> the browing and filtering through the tags is not as intuitive as browsing through a tree structure of albums

With hierarchical tags/categories you have the tree ... your hierarchy of albums.

> Then I can drag&drop arbitrary images from the thumbnail view into the albums to collect them.

From lighttable you can drag & drop your images into tags.

Should I add that each tag collection holds its own images ordering.

**Comment by bengtfalke** [comment]
I am also a "migrant" from LR to DT. I think the suggestion to ad "galleries" is a good idea if it does not confuse the UI. I am used to it now but I do vividly remember how confused I was about the collections in DT and how I missed the folders and collections in DT. My first attempt to start using DT was a failure because of this and it took another effort of YT-studies to get the hang of it. Another missing thing from that stage was the copy & import and that has been fixed now... so why not try to make it easier for people coming from LR to get the hang of DT?

**Comment by parafin** [comment]
> so why not try to make it easier for people coming from LR to get the hang of DT?

I don't think it's a goal for darktable or any active darktable developers. This is a volunteer project, so it doesn't really benefit from more users moving away from LR.

**Comment by Nilvus** [comment]
I agree with @parafin. darktable had not been made as a replacement for LR nor to be a Lightroom clone or same ways to use. It's just a different software, for same use but a different way. I think so that darktable don't have to suit LR. If someone want to change his software (from any software to any other), he needs so to learn the new software, not wait to see the software works as he used to. All changes needs to learn new habits.

I have tried LR and don't like it and find same difficulties cited here by testing LR (before testing darktable). I don't like how LR is made. darktable was easier (though not easy) for me than LR and I never succeed to like LR. And i never wanted that LR works differently. I consider that it was not for me. Of course, we could ask for a feature/improvement but consider also that this could not be suitable for a software.

So this "FR" is already possible in darktable, and as powerful as LR but just a different ways. That's what @phweyland explained. And darktable is not LR and will not be LR (and I hope so!).

**Comment by MStraeten** [comment]
But of course you might provide a functional mockup - if that’s something beneficial for the current userbase of darktable then there’s a chance to get this into darktable.
Just being useful for those that doesn’t use darktable yet is not the best motivation for darktable developers ;)

**Comment by ChristianBirzer** [comment]
Thanks for all your feedback so far. Of course, as I initially said, tags can do the job. Maybe I just find it too confusing to mix up the different types of tags (category,private,normal) and don't see which is which at the first sight.
I just played a bit with tags to mimic the LR collections. Had a few crashes and some strange behaviour (collection tagging list tree can be expanded with a single click first, but after adding a tag, a double click is needed.... but all this I will sort up and put in different issues).
I try to make a plan in my head what is needed (for me) to have category tags (and tags in general) to be as easy to use like the stuff in LR. 
Maybe I'll start with a few tag improvements as suggestions (and work on dt).

_OT: And: Yes, dt is not LR and don't need to be an exact copy. But as I'm active in a local photo club I know how beginners think and search for a software that is powerful yet easy to use without studying a lot of documentation. Until version 6, LR was the software I recommended to everyone. But now I'm searchig (not only for myself) for a good alternative and I see dt could be that and I'd like to help to improve it to better fit the needs of new users (without annoying dt experts)._

**Comment by bengtfalke** [comment]
> > so why not try to make it easier for people coming from LR to get the hang of DT?
> 
> I don't think it's a goal for darktable or any active darktable developers. This is a volunteer project, so it doesn't really benefit from more users moving away from LR.

Well the name Darktable is obviously a play with the name Lightroom and that main construction of the UI is of course based on Lightroom so why stop there and say that we are not inspired by Lightroom as nobody can doubt that. I understand that it is no purpose to try to attract LR users but what wrong in using more parts of LR:s UI that works for people.

**Comment by Nilvus** [comment]
> Well the name Darktable is obviously a play with the name Lightroom and that main construction of the UI is of course based on Lightroom so why stop there and say that we are not inspired by Lightroom as nobody can doubt that. I understand that it is no purpose to try to attract LR users but what wrong in using more parts of LR:s UI that works for people.

This was it at the beginning. That doesn't mean it remains inspired by Lightroom. A lot of things have been added/modified since quite differently to Lightroom. darktable is more than 10 years old and what it is now is not what it was in 2009 when it was launched.A lot of things are completely different between darktable and Lightroom. So, no it is not (anymore) inspired by Lightroom.

**Comment by ptilopteri** [comment]
> Well the name Darktable is obviously a play with the name Lightroom and that main 
> construction of the UI is of course based on Lightroom so why stop there and say that we are > not inspired by Lightroom as nobody can doubt that. I understand that it is no purpose to try > to attract LR users but what wrong in using more parts of LR:s UI that works for people.

It isn't even "Darktable" but darktable

**Comment by parafin** [comment]
> > > so why not try to make it easier for people coming from LR to get the hang of DT?
> > 
> > 
> > I don't think it's a goal for darktable or any active darktable developers. This is a volunteer project, so it doesn't really benefit from more users moving away from LR.
> 
> Well the name Darktable is obviously a play with the name Lightroom and that main construction of the UI is of course based on Lightroom so why stop there and say that we are not inspired by Lightroom as nobody can doubt that. I understand that it is no purpose to try to attract LR users but what wrong in using more parts of LR:s UI that works for people. Christian Birzer is humble enough not to upset anybody in my view....

Nobody is upset. It’s just not constructive to use phrases like “why not do smth”, “what’s wrong with doing smth", because it won’t motivate anyone to do the work. Question always should be “why do it?”, not “why not do it?”. And usual answer for commercial software “to attract more users” doesn’t work here, because for free software users mostly generate support requests (more work) and not income. World domination is also not a darktable project ambition, I think. Instead new feature should be interesting for some developer to actually use it himself. E.g. simplicity (when applicable) benefits both new and existing users, but it’s often quite hard to actually implement, especially keeping the code itself simple (and so maintainable) too.

So I’m not necessarily against this FR, I’m just pointing out that some of the rhetoric (which repeats itself quite often) is not helpful.

**Comment by AlicVB** [comment]
> but all this I will sort up and put in different issues).
> I try to make a plan in my head what is needed (for me) to have category tags (and tags in general) to be as easy to use like the stuff in LR.
> Maybe I'll start with a few tag improvements as suggestions (and work on dt).

That would be great, thanks for that ! That's exactly the right way to follow imho. There has been a lot of improvements in this part of dt recently, but there's always room for enhancements or fix !
Maybe at some point we will state that categories aren't powerful enough and we need to develop something else, but let's first try it extensively and see what need to be enhanced to fullfill your needs...

**Comment by quovadit** [comment]
> it would be much more intuitive and easier to use to have such collections

@ChristianBirzer : I agree, that it would be great to improve collections in darktable, thanks for your initiative.

But instead of creating something new, we could start by improving the existing modules, in order to make them usable for DAM:

As "quick-target" I would use the color-labels (see issue #6675)

For "albums" I would definitely use the existing collections-module. As phweyland pointed out, all of the functionality is already there. In my opinion it's just the user interface that could be improved, in order to make it usable for DAM (see issue [#9664](https://github.com/darktable-org/darktable/issues/9664#issuecomment-890117538)). 

In this context it would also be important to keep the custom sort order when changing tags (see issue #10368)

**Comment by spaceChRiS** [comment]
I was pondering about this since I started using darktable. I never did use lightroom, but the feature you are describing was on my wish list since ever. There may even be some redmine feature requests about this. Therefore, I'll add my 2 cents, maybe it helps.

Thechnically, as discussed, I think all necessary features are implemented regarding the backend (database and such).

From an UX perspective, I still struggle to use these features as they are hidden in a given user interface. There are IMHO the following sub issues:

* The “albums” (category tags) are hidden and the interaction with other selections in the collection module are not obvious (e.g., creating works only in the tagging module, I cannot change an existing tag to become a category, what happens if I select a tag in the collections module, and then a category as second choice, what does it mean for sorting etc.).
* The recent collections are often not useful, see https://github.com/darktable-org/darktable/issues/1971

My suggestion for a proper UX [TM] would be to change the current collect images module such that there are 3 subsequent parts:
1. The top part allows to select categories only. It has a simple UI (e.g. only a drop down with all category tags). If it is left blanc, it simply does nothing, but when a category is selected, it will limit the accessible photos to this category. Sorting of a gategory is only affected when something is selected here.
2. The contents of the current collection module, maybe including some of the fixes that were linked earlier. It works as usual, but if in part 1. a category is selected, it acts only on the pictures in this category.
3. A quick filter panel, where the active collection can be narrowed down by simple UI elements, e.g. switches. Here one would be able to quickly narrow down the collection without spamming the recent collections module. Generic switches would be available (color labels, changed/exported, file format, aspect ratio, a date range picker, creator, … – you got the point). Furthermore, it would be possible to add your own switches, maybe in the preferences, such that, e.g., people doing analog photography could add a switch for the tag “analog”.

**Comment by spaceChRiS** [comment]
Hm, not to forget that 1. from my comment above is already implemented, but not as visible as it could be, see https://github.com/darktable-org/darktable/pull/5134. I hope my comment is not seen as criticism, as I am very thankful for all what we have with darktable, and in particular that we have the album implementation already.

**Comment by quovadit** [comment]
> The “albums” (category tags)

I don't think we should mix the album-feature with the existing category-tags, because
- not every category-tag is necessarily an album
  - e.g: all parts of a hierarchy (free nodes) are categories
- not every album should be a category
  - e.g: I do want to export my album-tags, in order to use it in my web-gallery as well

**Comment by spaceChRiS** [comment]
Hm, as far as I understand, the current implementation gives every tag the capability to have its own sort order. I think technically this is everything needed to make every tag an album tag. Everything else is probably UI work. Maybe a flag for tags is still needed to mark them as an album. If you read #5134, you will see that there has been an implementation which was even going a bit farther. However, this was then changed again due to reasons described there.

**Comment by phweyland** [comment]
The collection module is a bit complex but is able of a lot of logical combinations.

> The “albums” (category tags) are hidden

Hidden ? Once one has understood how to create collections (or albums) using tags I don't see the access to those collections more difficult than with Lightroom's static collections.
The doc could advertise a bit more this possibility. 

> I cannot change an existing tag to become a category

This is not correct, you can.

> what happens if I select a tag in the collections module, and then a category as second choice, what does it mean for sorting etc.

The doc says that tag collection sorting is effective for the first level collection of "collect module". So if the tag (your album) is not at the first level there is no tag's images sorting. If it's at the first level and you add some other levels, the order is applied to remaining filtered images.

> If you read #5134, you will see that there has been an implementation which was even going a bit farther. However, this was then changed again due to reasons described there.

I don't understand this. Do you mean tag's images ordering doesn't work anymore ?

**Comment by spaceChRiS** [comment]
Yes, you are correct regarding most of these points, I should better think before I write. Sorry.

> Lightroom's static collections.

As said, I never used it and therefore cannot compare. The only knowledge I have is from youtube, and only accidentally, not on purpose.

> Hidden ? Once one has understood how to create collections (or albums) using tags I don't see the access to those collections more difficult than with Lightroom's static collections.

Yes, it's very mighty (probably more than lightroom, this I don't know). The only thing that is “missing” is that it is not prominent nor unique. You have no list of your albums, you have to use the collections module with all the drawbacks (see above). It would probably already help to graphically highlight the first line of the collect module when tag is selected to make the user aware that something is special now.

> [changing tag to category] This is not correct, you can.

I was not able on 3.2.1, it may be possible in general and only be an issue on my side.

> The doc says [...]

Yes, my mistake, sorry!

> Do you mean tag's images ordering doesn't work anymore ?

No, I mean that it was once called “album” and then you braught the functionality even to every tag and removed album again. This is fine, but I think it is exactly what causes the misunderstandings here, see e.g. what @quovadit wrote.

Don't get me wrong, I am happy that you spent so much time and implemented all of this, and I am going to use all of this in future. I just wanted to give the OP some hints where to start when he wants to improve it even further. And I wanted to tell my UI idea for this. That's all.

**Comment by phweyland** [comment]
> And I wanted to tell my UI idea for this. 

Understood. Thanks !

**Comment by quovadit** [comment]
Some thoughts:
- it does matter, which criterion is the first one in collections module, which is quite strange
- the combination of multiple criteria is quite difficult to handle for frequent use

So I tried a mockup which splits the collections module into one easy to use 'navigate' module (just for the first-criterion) and the complex 'filter' module (for the combination of criteria).

![image](https://user-images.githubusercontent.com/5677563/147160703-92b98e01-2eef-4956-b464-a195f9ef3073.png)

- navigate
  - you can only select one criteria you would use to navigate through your entire catalog
    - folder / film roll (= with / without hierarchy)
    - tag / album (=special tag)
    - if you want you can also chose any other criteria (other...), e.g. date taken
  - album is just a special view for tags named album|whatever
  - you can create new tags (and therefor new albums) inside the 'navigate' module
  - albums can be renamed (without losing sort order)
- filter
  - this is the current 'collections' module with the possibility to combine multiple criteria
  - per default there is no criteria selected
  - the combination of criteria (and / or / except) can be selected via dropdowns between the rows
  - an X button on the right removes one row
  - the list of possible values (100, 125, ...) is shown directly underneath the corresponding criteria
  -  after you chose a filter, then a new empty row will automatically be added

The 'recen(tly used collections)' module could also be structured:
- last imports
  - = import timestamp
  - after importing images, the top entry of this list gets selected (instead of filmroll)
- recently used saved filter
  - only lists chosen 'presets'
- recently used custom filter
  - only shows filters manually defined in the filter-module
- recently used quick filter
  - only shows filters in the top-bar (rating, to-be-added: color-label)
