### ISSUE TITLE
LGTM: snprintf without proper checks can cause overflow

### ISSUE THREAD

**Issue by luzpaz** [darktable-org/darktable#10671]
[LGTM](https://lgtm.com/projects/g/darktable-org/darktable/?mode=tree&ruleFocus=1505913226124) identifies the following as vulnerabilities

https://github.com/darktable-org/darktable/blob/c6e8ed5447d57ba22a146f6d890462a80e002b8e/src/common/collection.c#L1993
https://github.com/darktable-org/darktable/blob/c6e8ed5447d57ba22a146f6d890462a80e002b8e/src/common/collection.c#L1998
https://github.com/darktable-org/darktable/blob/c6e8ed5447d57ba22a146f6d890462a80e002b8e/src/common/collection.c#L2004
https://github.com/darktable-org/darktable/blob/c6e8ed5447d57ba22a146f6d890462a80e002b8e/src/common/collection.c#L2006
https://github.com/darktable-org/darktable/blob/c6e8ed5447d57ba22a146f6d890462a80e002b8e/src/libs/recentcollect.c#L151

**Comment by ralfbrown** [comment]
All false positives.  buf/bufsize and out/outsize are being properly updated (and snprintf will never print beyond the given size).  LGTM was presumably fooled by those calls being inside for loops.

What *can* happen is that not all of the data gets written to the buffer because it's too small, which might cause incorrect behavior when later deserializing the result from the function in collection.c.

**Comment by luzpaz** [comment]
Got it, shall I close this ticket then?

**Comment by johnny-bit** [comment]
Yeah, those are all false positives. What would be great is to look at other warns in LGTM and try & fix them :)
