### ISSUE TITLE
macOS 12.1: Watermark placed in 3.6 moved in 3.8.0

### ISSUE THREAD

**Issue by chucko58** [darktable-org/darktable#10685]
**Introduction**

**Did you buy darktable from an application store ?**

Downloaded today from darktable.org

**Describe the bug/issue**

Photos I had previously watermarked in darktable 3.6, when opened in 3.8.0, now show the watermark displaced from its previous location. I use an SVG file as a watermark and usually locate it in the lower right corner of the image.

The attached screenshots show a representative thumbnail generated by 3.6 in the lighttable view in 3.8.0, the darkroom view in 3.8.0 of that same image, and the thumbnail when I return to the lighttable view.

I have confirmed to my satisfaction that the SVG file has exactly the width and height of the graphical content of the watermark.

**To Reproduce**

1. Place watermark in darktable 3.6 and save.
2. Open image in 3.8.0.
3. Observe location of watermark has changed.

**Expected behavior**

I expect the watermark to not move between releases.

**Screenshots**

[Before](https://www.dropbox.com/s/xaf8nb58ifq45q6/Screen%20Shot%202021-12-24%20at%205.38.34%20PM.png?dl=0)

[darkroom view](https://www.dropbox.com/s/cygnn2i8s14sagk/Screen%20Shot%202021-12-24%20at%205.40.58%20PM.png?dl=0)

[After](https://www.dropbox.com/s/0xgfu7r8sdir1e9/Screen%20Shot%202021-12-24%20at%205.41.34%20PM.png?dl=0)

**Screencast**

**Which commit introduced the error**

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.0 (release)
* OS                : macOS 12.1
* Memory            : 64GiB
* Graphics card     : 2x AMD FirePro D500, 3GB each
* Graphics driver   : Apple
* OpenCL installed  : Apple OpenCL 1.2
* OpenCL activated  : Yes

**Additional context**

I will attempt to reproduce this on my Linux machine (Ubuntu Studio 20.04).

**Comment by parafin** [comment]
Please provide SVG watermark file and XMP sidecar with it applied from version 3.6.1 so we could reproduce.

**Comment by chucko58** [comment]
[Sidecar file](https://www.dropbox.com/s/5dm2qbrry6p0bj9/4FRY2825.CR2.xmp?dl=0)

[Watermark SVG](https://www.dropbox.com/s/lo2905ullhy2181/ChuckosPhotos_Final.svg?dl=0)

**Comment by parafin** [comment]
I can confirm the issue. This is caused by librsvg update, see this PR for some details: #10506. Workaround is to modify SVG file to specify width and height in pixels on the root node (attached as txt file: [ChuckosPhotos_Final.txt](https://github.com/darktable-org/darktable/files/7779921/ChuckosPhotos_Final.txt)). For some reason newer librsvg renders this SVG with margins to make it square. I couldn't find a way to fix this in the time I could spend on this. Maybe someone else could take a look (perhaps @piratenpanda?). It might be a bug in librsvg or in dt, not sure. Main pointer to further debug this is that rectangle.y is not zero here: https://github.com/darktable-org/darktable/blob/b66b27832daf4f136091d205b14c151d2e4c8fd8/src/common/utility.c#L917

Removing it from that line doesn't fix the issue.

**Comment by parafin** [comment]
Scratch that, here's the fix: #10704

**Comment by chucko58** [comment]
I've confirmed the fix in darktable 3.8.1. Thank you!
