### ISSUE TITLE
No yellow border on grouped icons if group is selected

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#10703]
All in titles. In working in #10688 issue, I found that yellow lines are not displayed when group thumbnails is selected. It's displayed only when not selected. I will fix that whit #10688, so this issue is only here as a reminder.

Bug seen in actual 3.9 master.

**Comment by Nilvus** [comment]
@AlicVB: need help here too. When trying to fix that, I see that .dt_group_top (left, right and bottom) id are not set when thumbnail is selected. That's why we don't have yellow lines. So it's not CSS. We don't need/want yellow lines to be displayed all the times but we want them at least when hovering. It's ok when hovering for thumbnails not selected but no hovering possible to display those borders when thumbnail selected.

**Comment by AlicVB** [comment]
@Nilvus : here, the css class seems to be updated correctly, whatever the selected state. Are you sure it's not the cases for you ?

I've done some experiment with css, and I think this is due to the css rules priorities (I've always find them hard to understand)
Adding `#thumb_main.dt_group_bottom:selected #thumb_back` to the borders selectors solve the issue for me (just hope that there's no consequences)

**Comment by Nilvus** [comment]
CSS rules priorities is indeed not easy. I didn't tested that correctly and yes it worked. Thanks for your help.
