### ISSUE TITLE
cmake fails to find `<gio/gunixmounts.h>` in `collect.c` on NixOS for version 3.8

### ISSUE THREAD

**Issue by paperdigits** [darktable-org/darktable#10700]
**Did you buy darktable from an application store ?** No.

**Describe the bug/issue**

**To Reproduce**
When I try to compile, I get the error:

```
FAILED: nix/store/4xnai9jci10xlxmw7hf0p6nrg3mnhlxf-darktable-3.8.0/lib/darktable/plugins/lighttable/CMakeFiles/collect.dir/collect.c.o 
/nix/store/da9l6ifizmh883j94gzx5n51h8lrrp00-gcc-wrapper-10.3.0/bin/gcc -DAVIF_DLL -DDT_HAVE_SIGNAL_TRACE -DGDK_DISABLE_DEPRECATED -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_22 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_MIN_REQUIRED -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DGTK_DISABLE_DEPRECATED -DGTK_DISABLE_SINGLE_INCLUDES -DHAVE_BUILTIN_CPU_SUPPORTS -DHAVE_CONFIG_H -DHAVE_GAME -DHAVE_GMIC -DHAVE_GPHOTO2 -DHAVE_GPHOTO_25_OR_NEWER -DHAVE_GRAPHICSMAGICK -DHAVE_HTTP_SERVER -DHAVE_ICU -DHAVE_ISO_CODES -DHAVE_KWALLET -DHAVE_LENSFUN -DHAVE_LIBAVIF=1 -DHAVE_LIBHEIF=1 -DHAVE_LIBRAW=1 -DHAVE_LIBSECRET -DHAVE_MAP -DHAVE_OPENCL -DHAVE_OPENEXR -DHAVE_OPENJPEG -DHAVE_OSMGPSMAP_110_OR_NEWER -DHAVE_OSMGPSMAP_NEWER_THAN_110 -DHAVE_PRINT -DHAVE_SQLITE_324_OR_NEWER -DNATIVE_ARCH -DSQLITE_CORE -DSQLITE_ENABLE_ICU -DUSE_COLORDGTK -DUSE_LUA -D_RELEASE -D_XOPEN_SOURCE=700 -D__GDK_KEYSYMS_COMPAT_H__ -Dcollect_EXPORTS -I/build/darktable-3.8.0/build/nix/store/4xnai9jci10xlxmw7hf0p6nrg3mnhlxf-darktable-3.8.0/lib/darktable/plugins/lighttable -I/build/darktable-3.8.0/src/libs -I/build/darktable-3.8.0/src -I/build/darktable-3.8.0/src/external/LuaAutoC -I/build/darktable-3.8.0/build/nix/store/4xnai9jci10xlxmw7hf0p6nrg3mnhlxf-darktable-3.8.0/bin -isystem /build/darktable-3.8.0/src/external -isystem /build/darktable-3.8.0/src/external/OpenCL -isystem /nix/store/5idik4vmd83cnx5z4shg44s53l4n2whj-glib-2.70.1-dev/include/glib-2.0 -isystem /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/glib-2.0/include -isystem /nix/store/wqqwjjyygmjgmbmkhncq55yzrfgsj1ks-cairo-1.16.0-dev/include/cairo -isystem /nix/store/srqsdxbv4nsxmyl2nl1cpjwbxhawvzxg-gtk+3-3.24.30-dev/include/gtk-3.0 -isystem /nix/store/1y14888d7hg8djh0dzihlmj6905wrlmz-atk-2.36.0-dev/include/atk-1.0 -isystem /nix/store/kic3nfhbd52fnkvv8ymz14c7rx2x79mf-gdk-pixbuf-2.42.6-dev/include/gdk-pixbuf-2.0 -isystem /nix/store/xhfhdv452b3c9c8fvg160i6ag29kkzf4-pango-1.48.10-dev/include/pango-1.0 -isystem /nix/store/wp2lfivjbh8jjz09c5wghl40b2qjqfb5-harfbuzz-3.0.0-dev/include/harfbuzz -isystem /nix/store/jaw6h3zvnwlyl1jajdi0nbalwyq9f0v6-libxml2-2.9.12-dev/include/libxml2 -isystem /nix/store/7fb499a00xjdwazahl4m7s3w2gm2ch3c-libsoup-2.74.1-dev/include/libsoup-2.4 -isystem /nix/store/70j03g5609ksfiasylh7cgvplz9j2xh0-lensfun-0.3.2/include/lensfun -isystem /nix/store/8fx401pg1kb0l97g0517dybn9lcvvgfa-librsvg-2.52.3-dev/include/librsvg-2.0 -isystem /nix/store/4zb8wy4dp414vczn7yxxvs84pdj3rmx0-json-glib-1.6.6-dev/include/json-glib-1.0 -isystem /nix/store/3zby8md8vzkhss3j8m4916gif98q8q47-openjpeg-2.4.0-dev/include/openjpeg-2.4 -isystem /nix/store/qd1xyrbclka0lx1799lfxg2aylwmdpq4-libsecret-0.20.4-dev/include/libsecret-1 -isystem /nix/store/4qmsa0m2dqlipmxz9z1vr5lnwmxak0w4-graphicsmagick-1.3.36/include/GraphicsMagick -isystem /nix/store/pyz5dck6i6nn3rs3wvbf53hsfq38ygmz-osm-gps-map-1.2.0-dev/include/osmgpsmap-1.0 -isystem /nix/store/84rcvs6s32d217jgr6s16zsrf450qw0v-colord-1.4.5-dev/include/colord-1 -isystem /nix/store/4d2hmgvwxx5zn9qv9zkpddcf9l9sqjya-colord-gtk-0.2.0-dev/include/colord-1 -isystem /nix/store/hxf9dx7n8ii88bb00gvla0zncg4xgj4b-openexr-3.1.2-dev/include/OpenEXR -isystem /nix/store/j741vsis2kfcfrvf8y4s15s36hrqdm2l-imath-3.1.3/include/Imath -Wall -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wno-unknown-pragmas -Wno-error=varargs -Wno-format-truncation -Wno-error=address-of-packed-member -std=c99 -fopenmp -march=native -msse2 -g -mfpmath=sse -O3 -DNDEBUG -O3 -ffast-math -fno-finite-math-only -fexpensive-optimizations -fPIC -fvisibility=hidden   -include common/module_api.h -include libs/lib_api.h -MD -MT nix/store/4xnai9jci10xlxmw7hf0p6nrg3mnhlxf-darktable-3.8.0/lib/darktable/plugins/lighttable/CMakeFiles/collect.dir/collect.c.o -MF nix/store/4xnai9jci10xlxmw7hf0p6nrg3mnhlxf-darktable-3.8.0/lib/darktable/plugins/lighttable/CMakeFiles/collect.dir/collect.c.o.d -o nix/store/4xnai9jci10xlxmw7hf0p6nrg3mnhlxf-darktable-3.8.0/lib/darktable/plugins/lighttable/CMakeFiles/collect.dir/collect.c.o -c /build/darktable-3.8.0/src/libs/collect.c
/build/darktable-3.8.0/src/libs/collect.c:39:10: fatal error: gio/gunixmounts.h: No such file or directory
   39 | #include <gio/gunixmounts.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.8.0
* OS                : NixOS 21.11 / kernel 5.10.81
* Linux - Distro    : NixOS 21.11
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : no
* OpenCL activated  : no
* Xorg              : Yes
* Desktop           : Plasma
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : release

**Additional context**

I've tried a few variations on the patch https://github.com/paperdigits/darktable/commit/9a8cb704da40417a8f321ecc25f4c0dc95aa68d3.patch but none of them work.

**Comment by paperdigits** [comment]
ping @mkroehnert who was helping me in the NixOS matrix and @cryptomilk who knows the most cmake.

**Comment by markus1189** [comment]
I found https://github.com/NixOS/nixpkgs/issues/36468 when googling for this problem, but could not figure out how to add this in the darktable build as well. :(

**Comment by cryptomilk** [comment]
For including this library you need to set the include path. Looking at darktable we don't have a `FindGIOUnix.cmake`which would set the include path and

There is no `cmake/modules/FindGIOUnix.cmake`so the include path is not set where to find the header file.

**Comment by mkroehnert** [comment]
Hi all,

what we found out yesterday are the following things:
* the header file is not found, because the correct include directory is missing
* [FindGIO.cmake](https://github.com/darktable-org/darktable/blob/e8cb2cb1d9a2b34a4bbe27278247dae0ff09c3c8/cmake/modules/FindGIO.cmake#L14) searches for Glib via pkg-config and then checks for the `gio-2.0` module
* FindGIO.cmake only uses the returned values of `check_modules` for the following `find_library()` call as a path hint but not the `GIO_PKGCONF_INCLUDE_DIRS` variable (the library path could probably also be used from the check_modules call)
* GIO on NixOS comes with two pkg-config files
  * `gio-2.0.pc`
  * `gio-unix-2.0.pc` (this file can provide the missing include directory via pkg-config)

My current understanding is that there is a missing dependency to the `gio-unix-2.0` package/module on NixOS.
This might not occur on other distros, if header files are put into the GLib include directories.

My current proposal is to add `gio-unix-2.0` instead of only `gio-2.0` to the check_modules call and then append the found include directories to the main variable similar to
`list(APPEND GIO_INCLUDE_DIRECTORIES ${GIO_PKGCONF_INCLUDE_DIRS})`.

Since I do not know how the Gnome libraries are structured and should work together, I assume, that `gio-unix-2.0` is a platform dependent implementation for `gio-2.0`. If this is correct, it should be handled in the `FindGIO.cmake` file directly instead of a separate one.

Also, if the `FindGIO.cmake` is used in both Windows and Linux builds, the search for `gio-unix-2.0` must then be done conditionally.

**Comment by mkroehnert** [comment]
I just successfully compiled darktable 3.8.0 with nixpkg using the following modified `FindGIO.cmake`. Did not try to run it yet.

```
# - Try to find GIO 2.0
# Once done, this will define
#
#  GIO_FOUND - system has GIO
#  GIO_INCLUDE_DIRS - the GIO include directories
#  GIO_LIBRARIES - link these to use GIO

include(LibFindMacros)

# Dependencies
libfind_package(GIO Glib)

# Use pkg-config to get hints about paths
libfind_pkg_check_modules(GIO_PKGCONF gio-2.0 gio-unix-2.0)

# Find the library
find_library(GIO_LIBRARY
  NAMES gio-2.0
  HINTS ${GIO_PKGCONF_LIBRARY_DIRS}
)

# Set the include dir variables and the libraries and let libfind_process do the rest.
# NOTE: Singular variables for this library, plural for libraries this lib depends on.
libfind_process(GIO)

list(APPEND GIO_INCLUDE_DIRS ${GIO_PKGCONF_INCLUDE_DIRS})
```

The following changes for the nixpkg darktable file were provided by @paperdigits 
```
diff --git a/pkgs/applications/graphics/darktable/default.nix b/pkgs/applications/graphics/darktable/default.nix
index 50e26677377..09263d37612 100644
--- a/pkgs/applications/graphics/darktable/default.nix
+++ b/pkgs/applications/graphics/darktable/default.nix
@@ -7,12 +7,12 @@
 }:
 
 stdenv.mkDerivation rec {
-  version = "3.6.1";
+  version = "3.8.0";
   pname = "darktable";
 
   src = fetchurl {
     url = "https://github.com/darktable-org/darktable/releases/download/release-${version}/darktable-${version}.tar.xz";
-    sha256 = "sha256-or/HwQO4JJRUV6m/7Z5S8Af6HQMPnbyz/wMnhRvkLRQ=";
+    sha256 = "01gp9dg5wr2rg1k8cqs0l3s7ism8a4q8qypgwccd4jh7ip3wfr9f";
   };
 
   nativeBuildInputs = [ cmake ninja llvm pkg-config intltool perl desktop-file-utils wrapGAppsHook ];

```

One NixOS specific thing I found is the following warning (see also https://github.com/NixOS/nixpkgs/pull/135627)
```
CMake Warning at src/CMakeLists.txt:328 (find_package):
  Could not find a configuration file for package "OpenEXR" that is
  compatible with requested version "3.0".

  The following configuration files were considered but not accepted:

    /nix/store/405xsi3ww7bsxx49ml7vql73ihiif7km-openexr-2.5.7-dev/lib/cmake/OpenEXR/OpenEXRConfig.cmake, version: 2.5.7
```

**Comment by phweyland** [comment]
I'm the guilty guy for adding <gio/gunixmounts.h>.
This has been added to use `GUnixMountMonitor` instead of `GVolumeMonitor`, the last one not working as expected on Linux (to strike inaccessible files in collect module).
On windows <gio/gunixmounts.h> is not used.
Maybe the first to do is to check if that detection works without <gio/gunixmounts.h> on NixOS ...

**Comment by mkroehnert** [comment]
@phweyland if the CMake find module is updated with the changes above (making the dependency explicit), DT 3.8.0 compiles for me without any further changes.

What I do not know is, whether this also works for other Linux distributions, since I am not familiar with how Gnome libraries are expected to be used.

**Comment by paperdigits** [comment]
@mkroehnert for the OpenEXR, we need OpenExr v3, which I already packed. I have an open PR in nixpkgs to bump the darktable dependency to `openexr_3`

**Comment by parafin** [comment]
Actually openexr-3 is problematic with darktable right now, because of changed way to include its headers (with/without openexr/ prefix). Better stick with openexr-2.
