### ISSUE TITLE
click+drag rotation correction as a global shortcut

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10757]
There have been some (predictable) comments complaining about the loss of the crop & rotate module from darktable 3.8.

Personally the only thing that I really miss is the ability to right-click+drag to set the rotation from within the crop module. Going back and forth from crop to rotate & perspective and back again isn't the best workflow.

Would it be possible to activate this functionality using a keyboard shortcut (accessible from outside of the module) and have this change the parameter in the rotate & perspective module?

**Comment by dterrahe** [comment]
Something like this would be very useful. You wouldn't really need the right-click; just press&hold a key, move the mouse, release the key. So in inputng terms this would be a hold-toggle. It doesn't fit in the normal darkroom paradigm, so would be implemented outside it. In that way it would be similar to adjusting exposure by scrolling on the histogram. Without the complication of multiple instances. However, there could be clashes with other mouse operations. What to do if you are editing a mask, toggle this mode and left-click? Or if this button is pressed while in the middle of editing a shape? The different center screen modes are not that robustly fenced so this might need a lot of checks everywhere. Or, since this mode doesn't need any clicks or scrolls, just mouse moves, any other mouse actions could simply cause this mode to be silently dropped without a rotation adjustment and whatever other operation that is normally linked to that mouse action be performed as usual.

Thinking of alternative more generic approaches; the "focus" element of the iop modules could have a hold toggle added that switches focus back to the previously focused module when you release the mapped key. So you'd still fully switch focus to the r&p module while pressing a shortcut key (and have all the right-click+drag and possibly other functions you might want to use there) but you don't need to find another key to switch back. And this would then also work for other modules (although I can't think of any at the moment where it would be massively useful).

**Comment by AlicVB** [comment]
> the "focus" element of the iop modules could have a hold toggle added that switches focus back to the previously focused module when you release the mapped key

I quite like this idea. It can also be very useful for the crop module imo.

This cover the shortcut part, but iirc, we have also discussed some widgets at some point (or maybe I've discussed it alone, very possible :D) Thinking loud, this can takes the form of a "QAP only" widget in r&p and crop modules. Clicking on that toggle button would : 
- "freeze" all the modulegroup lib (except the button to exit the mode) (will need some new proxy functions)
- force the focus to the crop or r&p module
- for the crop module the "handle" are quite obvious to see, but for r&p we maybe need to have a "predrawn" line to adjust for better discoverability...
- second click on the toggle button validate the change, focus the module out and re-enable modulegroup

That would have the advantage to be "shortcutable" without any change in current infrastructure too...
Again, that's just a very early idea...

**Comment by elstoc** [comment]
Not sure I understand all of the conversation here, but the key feature for me is to keep the centre image unchanged (as if the crop module - or whatever the current gui module is - remains active) during the entire operation. If rotate and perspective becomes active during the process don't forget that the r&p module often displays a different sized image to the crop module (due to the fact that it also has internal cropping but shows the entire image, including black empty parts). This could mean that the size of the image changes during the process of dragging? Or are we trying to do this without r&p redrawing the screen?

My current method is to have a keyboard shortcut to focus both crop and r&p modules and flip between the two but this causes the centre image to change size more than once and is a little jarring.

**Comment by dterrahe** [comment]
These two statements seem to conflict:
> * will need some new proxy functions

> without any change in current infrastructure


> * focus the module out

It would not just have to focus out r&p; it would have to refocus (and therefore save) the previous module.


> don't forget that the r&p module often displays a different sized image

True! So having just a button press+mouse move (without any screen updates/focus changes) would be best (apart from discoverability).

**Comment by vsz1lu** [comment]
My user side solution:

shortcuts:
"x" : show rotate & perspective module
"shift+x": rotation value edit
"shift+alt+x": rotation value reset
"x, horizontal movement": lens shift vertical
"x, vertical movement": lens shift horizontal
"shift+ctrl+alt+x" : reset the whole rotate & perspective module

When I press "x" the rotate & perspective module is going to focus, but inactive. I can adjust what i want.

When I press "shift+x" the rotate & perspective module is NOT going to focus but active and the value edit floating window is opening. I can edit the rotation by mouse movement or numeric entry. When I move out the pointer from the floating window I can use the left good old click leveling method.

When I hold down the "x" I can correct the perspective by mouse movement. Very useful for short-legs grils ;)

The new shortcut system is more powerful what I imagine in first time :)

![Képernyőkép – 2022-01-02 17-14-37](https://user-images.githubusercontent.com/57588193/147882041-4fc0f55f-ef0d-494e-9603-6a1a4621c95b.png)

**Comment by elstoc** [comment]
@vsz1lu this is fine when you want to adjust the rotation by a known amount and/or judge it by eye. The feature I'm referencing here is the ability to set the rotation by drawing a line over a horizontal/vertical feature in the image. This sort of thing is hard to judge by eye, just by tweaking the slider values.

**Comment by vsz1lu** [comment]
> Though, as I've said in a previous comment, focusing the rotate & perspective modules is my current workaround, it would be nice not to have to wait for the screen to redraw three times during the process (once when changing focus, again when rotating, and again when focusing back again).

It's totally true, but depend on the personal workflow. I'm always crop the image at the finish of the editing - as we make in the lab with real prints. So the spearted rotate and crop is more comfortable for me as the previous method.

Judging by eye is the most effective way for leveling if You don't have a real hard h or v straight line on the image. The technically right leveling is not always and always same as the optically "right" for human eye.
Otherwise an automatic leveling (only rotating and not perspective correct) button is welcome in the rotate and perspective, maybe the structure analyse algorithm can find straight lines in the near middle of the images ;)

**Comment by AlicVB** [comment]
@elstoc : I understand that you want to avoid the image "jumping". That seems doable for the straightening line, but not for the cropping part. For that point, I can propose the following : 
- add a new toggle button somewhere (so it can be mapped to a shortcut and used graphically)
- enter a "special" overlay mode which disable temporarily the normal one
- draw a line in the middle that can be moved around to define the straightening and enable in parallel the ability to draw the line directly with the mouse
- apply the rotation via a proxy in the r&p module
- this "special mode" should be exited by untoggling the button or via any other action (click somewhere in modulegroup, etc...)

But we have to keep in mind that at this point the image *will* "jump", especially due to the eventual auto-crop part of r&p

@dterrahe : I don't really count a proxy as a change in infrastructure, as it's not invasive : it's "just" a way to interact with a specific module from outside. That doesn't means it's easy to code ;)

**Comment by elstoc** [comment]
Avoiding the jumping during the dragging was more what I was talking about - there's nothing to be done about jumping afterwards. I'm not even certain that this will be a better workflow than what I've called a workaround (even if it were to work perfectly) - it might only be really practical with crop and rotate in the same module - which kinda defeats the purpose of getting rid of crop & rotate.
