### ISSUE TITLE
Question: legacy_presets

### ISSUE THREAD

**Issue by HansBull** [darktable-org/darktable#10794]
Looking through the source code, I don't see any query on the `legacy_presets` table, except the big re-insert on each startup in `legacy_presets.h`.
Question to the devs that have been around for a long time: Is that still needed?

**Comment by johnny-bit** [comment]
Weeeeellll looking at the code it seems like the only place where it could be used is in auto-apply preset code for images from over 9 years ago? Looks like getting `DT_IMAGE_NO_LEGACY_PRESETS` flag off is a bit hard because you'd have to find eprfectly crafted XMP file...

TBH that could be interesting cleanup ;)
