### ISSUE TITLE
Unable to activate openCL on Linux (Manjaro) with Nvidia GeForce GT 730

### ISSUE THREAD

**Issue by ftastisch** [darktable-org/darktable#10832]
Hi,

I would like to use openCL with darktable 3.8.0 and installed a GT 730 in my PC. However, so far I am not able to activate openCL in darktable with this GPU.

In the meantime, the idea came up that the compute capability of this GPU (3.5 in this case) might not be sufficient for darktable, but I did not find a minimum compute capability that would be required by darktable. So the question is whether this GPU is not sufficient for darktable in general or whether it should work and there is bug in my setup (not necessarily in darktable).

Thank you!

**Comment by elstoc** [comment]
The [specifications page](https://www.nvidia.com/en-gb/geforce/gaming-laptops/geforce-gt-730m/specifications/) states that it only supports OpenCL 1.1. I think we require 1.2 now.

**Comment by johnny-bit** [comment]
Looking at https://browser.geekbench.com/opencl-benchmarks I'd say 730M looks like not up to task...

Anyway - for opencl support you'd need proprietary drivers seems like it's not possible yet to use nouveau for compute tasks (https://nouveau.freedesktop.org/FeatureMatrix.html) (gallium compute recently got support for opencl 1.2 and that's what darktable needs). With proprietary drivers the last drivers to support 730M were 416 series so i guess you'll be needing long-term 390 series. Even then - darktable won't be happy if opencl 1.2 is not supported (dunno if drivers provide that) so your experience may vary.

Since there's nothing darktable team can do about your HW/drivers situation consider closing this issue.

**Comment by johnny-bit** [comment]
Just as a tip - follow manjaro guides on enabling opencl for nvidia cards, start darktable with `-d opencl` and see where it takes you :)

**Comment by ftastisch** [comment]
Thank you @johnny-bit , that actually helped a lot as this "endeavor" confirmed that nvidia opencl is not yet working properly in my setup.
