### ISSUE TITLE
Including export parameters into duplicate of an image

### ISSUE THREAD

**Issue by pedjas** [darktable-org/darktable#10838]
**Is your feature request related to a problem? Please describe.**
I need to export the same image in at least two different versions, one for my personal archive/print and other one for social media, blog and other usage. Sometimes I even need to export more than two versions - some sites have different requirements in image sizes/proportions.

I use duplicate option to make duplicate of and photo and it allows me to make different edit, including cropping which works great.

But - export options are global. Those cannot be saved for each image. That means when I do export I need to remember to manually change path, file name and resolution before I do export. It often happens that I have to re-export image and that means I have to adjust export settings if I had to change it for other image (or duplciate). If I forget to change export settings that means that previously exported image would be overwritten.

**Describe the solution you'd like**
It would be great if there is option to save exporting settings with image duplicate so once it is set for duplicate it stays remembered and if repeated it will do exact the same export as set in the first place. If user changes to other image, then export settings should be adjusted to those set to that new image.

**Alternatives**
I tried to search for possible solution but could not find any. I am not experienced Darktable user so it may be that I am missing existing functionality.

**Additional context**

**Comment by ptilopteri** [comment]
why not set a style for your export size and group the images.  then export using the style

**Comment by pedjas** [comment]
Style can save export settings including export path and file name? I was not aware of that. Will try.

**Comment by elstoc** [comment]
I don't think styles apply to lib modules. You could use a preset though.

**Comment by pedjas** [comment]
I tried, style does not preserve export settings.
Preset do, but that means I would have to create preset for each photo which is not viable solution.

The whole idea of DarkTable that you set everything on a photo and whenever you get back to that photo, all settings are there is what I like about this program. Except it does not cover all settings, like export settings in this case.

**Comment by elstoc** [comment]
As you state in your initial post, the export module does not allow this. That is because modules in darktable are split into two distinct groups: utility modules (otherwise known as lib modules) like export are global and not linked to individual images; processing modules (otherwise known as iop modules) _are_ linked to individual images.

What you're asking for is a fundamental redesign and I don't know that it will be easy to implement.

**Comment by AlicVB** [comment]
That's a quite specific, although valid, workflow. imho, it's a typical job for LUA scripts !
With lua, you can export an image with specific parameters. So what I would do (if I've understand your situation correctly) is something like : 
- define 1 colorlabel/ tag or whatever for each type of images (it's up to you to choose them)
- create a lua script that will take the selection, and for each images in the selection : 
- read the colorlable/tag/whatever of the image
- export the image with the parameters needed for this type of images
- affect the script to a shortcut (you can also add button with lua, but this is a little more work)

**Comment by pedjas** [comment]
> As you state in your initial post, the export module does not allow this. That is because modules in darktable are split into two distinct groups: utility modules (otherwise known as lib modules) like export are global and not linked to individual images; processing modules (otherwise known as iop modules) _are_ linked to individual images.
> 
> What you're asking for is a fundamental redesign and I don't know that it will be easy to implement.

Maybe it is possible to create export configuration utility module (which is linked to an image) that would not do exporting but just contain export settings so when image is exported, global export module could read settings from utility export configuration module if it is active for the image? That actually may be very practical way to handle this allowing easy switching among global export and per image export settings.

**Comment by dterrahe** [comment]
> Maybe it is possible

Anything is possible. But if a specific approach is hardcoded into dt, it means maybe a few people are happy but others still cannot line this up with their preferred workflow. And if we support too many different ways of working, the flexibility necessarily leads to complexity, meaning it is harder to figure out how things are supposed to work (or even to know that somewhere what you want is available) and bugs are much more likely to happen because nobody can test all the possible combinations and developers, the main testers, don't use them anyway. So in the end _nobody_ uses them and it is all a lot of wasted effort and frustration.

That's why we try to be somewhat careful with piling up more stuff ("bloat").

The suggestion above is a very serious and honest one; _exactly_ for this kind of thing, there is a whole lua layer that should let you do what you want. And if _that_ is too limited in giving access to a particular existing feature you need, you can file a bug for that. Yes, you'll need to do/learn a little bit of "coding", but teach a man to fish etc. Lua is a very simple scripting language so it may turn out easier and faster to figure that out than to try to convince developers to make what you want (and help them debug).

This is not "us" telling you we won't help you. This is us thinking that lua will be the best solution for you and make you happiest.

But maybe you already went that way, in which case please close this bug.
