### ISSUE TITLE
Canon EOS 77D

### ISSUE THREAD

**Issue by IjhUDWzf** [darktable-org/darktable#10878]
I have tried to read and understood what I could, nevertheless I am pretty much a newbie in the world of raw.

In the [list](https://www.darktable.org/resources/camera-support/) I can see that my camera (Canon 77D) is missing the custom matrix. If I understand it correctly, this may be the reason why raw photos imported to darktable look dull and the colors are not anywhere near the reality. At raw.pixls.us the camera is not listed as missing and looking into the database, there already is a picture (and this camera can produce only one type of raw file AFAIK).

I am also not completely sure how this connects to an ICC or DCP profiles and if a photo of a color chart is needed for this type of support of the camera. Are any pictures I can provide without a color checker chart (as I do not own one) of any help to make the rendering of images from 77D any better?

Are there any other reasons why the picture look so dull?

Moreover, my camera is not available in the lens correction module. Is that because it is not listed by lensfun?

**Comment by johnny-bit** [comment]
Custom matrix is not needed

> Moreover, my camera is not available in the lens correction module. Is that because it is not listed by lensfun?

Camera IS supported by lensfun. If it's not on the list you gotta update your lens db - https://github.com/darktable-org/darktable/wiki/Camera-support#lens-correction (unless you are on windows... but that should have recent lensfun lib). I know it because I use it pretty much daily :) 

If that's all then please close this issue and have fun with your camera and learning darktable!

**Comment by IjhUDWzf** [comment]
> Custom matrix is not needed
Custom matrix is not needed for what I had described or at all for this camera?

> Camera IS supported by lensfun.
Thank you for the tip, I have updated the database and it works. I guess the information at the page I saw is outdated.

I understand that the point of shooting raw is to process the photos. However, darktable automatically sharpens the photo and does other things as well. Why not to make the colors "real world"? Moreover, I have checked photos from the database from other Canon cameras and some were much better regarding this issue (based on comparison of the raw file and the embedded jpg) - usually the cameras having the custom matrix were the better.

**Comment by johnny-bit** [comment]
> Custom matrix is not needed for what I had described or at all for this camera?

Honestly IMO custom matrix was pretty much a workaround on input profile to adjust colors in a static way. That is not needed since now we have scene-refered workflow and color calibration module which is FAR more flexible because instead of creating single custom matrix or basecurve or whatever you can shot color chart on the spot and reference it for perfect colors every time :)

So my answer would be: a custom matrix is not needed at all.

**Comment by johnny-bit** [comment]
Instead of custom matrix follow https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/color-calibration/#extracting-settings-using-a-color-checker and create preset that you autoapply - it would generate similar setup to custom matrix without much hassle.

**Comment by IjhUDWzf** [comment]
@johnny-bit Thanks.
