### ISSUE TITLE
darktable 3.8 - system crashs with hypervisor error after start

### ISSUE THREAD

**Issue by SSiefert** [darktable-org/darktable#10885]
My system results in a bluescreen with error "hypervisor error" when starting darktable 3.8. darktable 3.6.1 was working fine. The error occurs directly after darktable has been started an the UI is visible.

System:
Win10 21H1
Ryzen 7 1800X
Core isolation/memory integrity is activated in windows sercurity.

![signal-2022-01-14-064304](https://user-images.githubusercontent.com/4517738/149458198-17cf224c-257f-44ff-8369-75c271e68aa4.jpeg)

**Comment by parafin** [comment]
Most likely cause is GPU drivers. darktable itself shouldn’t be able to cause blue screen. You could try adding --disable-opencl option to darktable command to see if it helps. And try updating GPU drivers.

**Comment by SSiefert** [comment]
Thanks for response.

I checked my gpu drivers. They are up-to-date. GPU is radeon rx 5700 xt.

I also tried the command you named: --disable-opencl. Unfortunately it has no effect.

**Comment by SSiefert** [comment]
Any other ideas?

**Comment by victoryforce** [comment]
> Any other ideas?

I can only advise to turn off memory integrity in system settings. In any case this is a bug in Windows, this is not darktable fault.

**Comment by SSiefert** [comment]
Turning memory integrity off does not solve the problem too.
If the bug seems to be in windows ... is there any possibility to locate the origin via darktable, e.g. logging, etc. ... ?

**Comment by victoryforce** [comment]
No matter what the program does, the system should not crash. So there can be no doubt - it's the fault of Windows.

I'm not sure it will be possible to catch what darktable is doing at the moment of BSOD, as it is very likely that system will not have enough time to properly flush latest writings to disk. Not to mention that this logging will not show us the root cause of system fault.

You will be more likely to get help if you turn to Microsoft support and give them your BSOD minidumps.
