### ISSUE TITLE
Midi encoder for shortcuts

### ISSUE THREAD

**Issue by schmoelder** [darktable-org/darktable#10909]
**Introduction**
I have a rotary encoder on a midi keyboard which I would like use to for setting sliders. Since I only have a limited number of encoders, I would like to use some modifier for it.

**Describe the bug/issue**
When setting `e,CC16` for exposure and then `f,CC16` for FilmicRGB/White relative exposure, only the last setting will be active when turning the knob, regardless whether `e` or `f` is pressed.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'Shortcuts'
2. Go to `Processing Modules/Exposure`
3. Assign Exposure
4. Press `e` and rotate encoder
5. Go to `Processing Modules/Filmic RGB`
6. Assign White relative exposure
7. Press `f` and rotate encoder
8. Press `e` and rotate encoder > Filmic White relative Exposure is adjusted

**Expected behavior**
8. Press `e` and rotate encoder > Exposure is adjusted

**Edit** Sorry for my butterfingers, I accidentally pressed enter before I was finished.

**Comment by elstoc** [comment]
There's very little actual information in this issue. Most of the text you have included is the guidance (written by the darktable team) on how to raise an issue. Instead of just including the guidance verbatim, please use the guidance to write an issue and provide the information requested.

**Comment by schmoelder** [comment]
Sorry, I had butter fingers and accidentally submitted the issue while editing the post.

**Comment by MStraeten** [comment]
did you check what's in your shortcutsrc file? Maybe attach it so the result of your assignment can be checked.

**Comment by dterrahe** [comment]
Besides providing the shortcutsrc file; do you have fallbacks enabled?

> * Press `e` and rotate encoder

Are you keeping `e` pressed _while_ rotating the encoder?

> * Assign White relative exposure

Do you get a message asking you to overwrite the previous assignment?

**Comment by dterrahe** [comment]
> Tried both, keeping it pressed, as well as a sequence; they result in the same entry in the shortcutsrc.

That is strange; upon releasing the key, a shortcut should be created for _just_ the key press.

> * the buttons and encoders send Midi CCs

Have you tried configuring the buttons to send notes? That's the intended configuration. You should then be able to combine midi-button-press and midi-encoder-turns in one shortcut.

> * enocder 1 is used for the first slider of the module, encoder 2 for the second etc.

This is one of the ideas in https://github.com/darktable-org/darktable/issues/9487#issue-941202322 (last item under _widgets_). Not the highest priority on my list, but I (or someone else) might eventually get round to it.

**Comment by jerryhard** [comment]
for people who compile darktable is needed portmidi* (portmidi-devel) i have portmidi,portmidi-devel,portmidi-tools
I buy Xtouch mini - because is supported as primary, great idea, small and cheap device - dual layer - then is like double 
Maybe is good idea make some schema what is best, now i have exposure - A-1, color-temp- A-2 ... i have plan shadow-highlights.

for people need know f is supported or not ... 
from cmd must darktable write
[midi_open_devices] opened midi device 'X-TOUCH MINI MIDI 1' via 'ALSA' as midi0

My device come in MC mode (light orange led in "MC MODE")
unplud gevice, press and hold MC gummy button (white, left down), plug back to USB, wait light-off orange led ... and release button ... now is mode write to device memory and next power off-on be on standard mode and not in MC mode.

I write it, because i don't find all these info on web, some is in README in source code, where is write about portmidi library, on web is write about don't use MC mode.

HOWTO set - only double click in shortcut setting and press or rotate xtouch-mini button or potentiometer  and that is all.
 idea is use tablet-or-mouse + Xtouch-mini only ... but now is sometime needed CTRL,SHIFT,ALT 
 
 Maybe in feature we crete ideal layout for X-touch mini + printable layout with labels 
 
 some crazy howto with push button and potentiometer ... + template for crete own label 
 https://aperturized.com/lightroom-and-midi-33-my-midi2lr-setup.html

**Comment by MStraeten** [comment]
I doubt there’s such thing as an ideal layout ;) it depends on your workflow. I need the knobs  for exposure and the colorbalance rgb sliders - not representative for others.
Further an attached XTouch minimise just detected as midi0 if there are no further midi devices attached. 
so maybe better provide shortcutsrc layouts on discuss.pixls.us, so these can be adapted to the own midi config while importing.

**Comment by dterrahe** [comment]
> but now is sometime needed CTRL,SHIFT,ALT

You can define a midi key as modifier by mapping to `global\modifiers` and selecting the _element_ you want.
