### ISSUE TITLE
Theme: css file placed in $HOME/.config/darktable/themes does not find imports

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#10914]
**Describe the bug/issue**

A user made theme was made available on pixls: [My personal darktable theme](https://discuss.pixls.us/t/my-personal-darktable-theme/28942/)

After creating the themes directory in the local configuration directory, placing the theme inside it, starting darktable and selecting it the following error was shown:

`dt_gui_load_theme: error parsing combined CSS @import url('file:///home/jade/.config/darktable/themes/darktable-Pro-v02.css');: darktable-Pro-v02.css:19:29Failed to import: Error opening file /home/jade/.config/darktable/themes/darktable.css: No such file or directory`

The theme has this included at the top:

```
@import url("darktable.css");
@import url("darktable-icons.css");
```

Hardcoding the path+file solves the issue. 

**To Reproduce**

1. Create themes directory in $HOME/.config/darktable
3. Download and extract theme into this newly created directory
4. start darktable from a terminal
5. select theme
6. see error in terminal

**Expected behavior**

The created theme directory is the place to put your (local) themes. This is, however, not mentioned in the current docs. I tried putting the theme in $HOME/.config/darktable as a test but it isn't picked up from there.

If this themes directory is the de-facto location one would expect darktable to be smart enough to (also) look in its default themes location (/full/path/to/share/darktable/themes/) to find the imported files.

Expecting the user to use hardcoded paths ins't a good idea: It makes the created theme bounded to a specific OS and its directory structure. It might also run into users that have darktable installed in non-default locations. Sharing user created themes becomes a bit of a mess in this case.

**Platform**

* darktable version : 3.9.0+116 also 3.8.0
* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.11)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Sqlite        : 3.27.2
* Optimization  : None

**Additional context**

* Reproducible with other version(s)       : Yes (see above)
* Reproducible with clean config directory : Yes

I'm on Linux and cannot test if this is also the case for Windows and/or MacOS.

**Comment by Nilvus** [comment]
As you, @elstoc and @TurboGit, work both on related part (link CSS and editor ones), is one of you think (and can) is good to do that?

**Comment by elstoc** [comment]
All we do is create a pair of import directives to load the theme file and optional usercss file (the tweaks from preferences) -- Gtk handles any import directives within the theme files themselves. What this suggests is that instead of just loading the CSS files, we should parse them, look for any import directives that reference known style files and replace those import directives with their full paths. I think we considered something like this when we were looking at user themes and the tweaks in the preferences and it looked very hard to make it work.

Three alternatives occur to me that would stop us needing to do all this.

1. User places all of their custom tweaks directly in `~/.config/user.css` instead of in their own theme file. This way the "main" theme (selected in preferences) will always be loaded first. If the tweaks are based on a specific darktable theme, user should load that as their "main" theme.
2.  User places all of their custom tweaks in a css file in `~/.config/themes` and places a single import directive within the user.css file referencing that theme file. Same results as option 1 but keeps the theme separate.
3. We change darktable to always load an extra file when parsing the theme. First load the base darktable theme file, then load whatever theme the user has chosen (which might also be darktable.css) and finally load the user.css file. This has the downside that user themes can only assume the base darktable.css file and cannot load anything else.

On the whole, I think asking that users place full paths in custom theme import directives is probably still less bad than option 3. Options 1 and 2 don't require development.

**Comment by elstoc** [comment]
One more option, though I'm not sure it's a good one... 

On loading the preferences dialog, darktable looks for user-created theme files in the usual location. If it doesn't find any, darktable continues to function as today. If it finds any (files named `*.css`), then the current "theme" option in preferences is renamed "base theme" (with a list of the default darktable themes) and an extra option appears below it, "user theme", listing the user theme files found. The author of the user theme will have to tell the person loading it what base theme to use. Then darktable will load three files instead of two: the "base" theme, then the "user" theme and then the tweaks.

**Comment by Nilvus** [comment]
Thanks for your precise answer. Option 3 is clearly not good just because of the downside you cited. Last option you propose is better as option 3 but seems quite heavy and will add too much things to check on for darktable. So, I agree, not sure it's a good idea.

That way, remains option 1 or 2, those I have first think about and as you could see, I propose option 1 on my answer in pixl discussion where this issue come from. See: https://discuss.pixls.us/t/my-personal-darktable-theme/

**Comment by jade-nl** [comment]
Seen from a non-developer's point of view: I think option 1 would indeed be best.

This one seems to be the simplest to apply, has the least problems (user do not have to create a non existing directory for example) and circumvents complicating the existing code.

Maybe not the place to mention this but the docs do need an update concerning themes (whatever the method that's going to be implemented).

**Comment by elstoc** [comment]
> Maybe not the place to mention this but the docs do need an update concerning themes (whatever the method that's going to be implemented).

Would you mind raising an issue in the dtdocs repo please.

**Comment by Nilvus** [comment]
@jade-nl: and after raising the issue (by pointing if needed to this one), maybe so close this issue as the fix will so be manual update.

**Comment by jade-nl** [comment]
> raising an issue in the dtdocs repo

Done: https://github.com/darktable-org/dtdocs/issues/414

Closing this one.
