### ISSUE TITLE
Feature request : Protect from edition tag

### ISSUE THREAD

**Issue by GwenaelQ** [darktable-org/darktable#10946]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I come back to darktable and realize that I messed up with setting done long ago on an image and don't remember how to cancel those changes. 

**Describe the solution you'd like**
Please consider adding a very intuitive way to protect image from editing. Something like a "Selected > lock" command in lighttable

Images wich would be protected would be tagged "Darktable|locked" and when anything is done that would change the settings applied to the image a message like " Locked image, do you want to create a clone ?"

Thanks for listening

**Comment by UweOhse** [comment]
I would not go the metadata way for that, because you can get darktable to almost behave like you want it do by making the files readony (and that case needs to be handled better anyway).

With a readonly .XMP the darkroom will still allow "changes", but they will not be written to the xmp file anymore (though they are still written to the database, and the thumbnail will still be updated, which is a bit annoying, but you can work around that by "discard history" in the light table).
Some overlay message will remind you that the XMP can't be written (which is perfectly OK for me).

The patch i appended makes the readonly state visible in the thumb (minus-symbol), and allows to change it (selected -> ro / rw = readonly / readwrite).

It's not ready for prime time. I really should put the readonly detection in some helper / utility function), and think about whether to prohibit entering the darkroom for read-only files (possibly not), or to discard the history once the darkroom or that image in the darkroom is left.
I have no idea if it works on windows. It possibly will not even compile there.

[readonly.patch.txt](https://github.com/darktable-org/darktable/files/8104159/readonly.patch.txt)

Consider it a start.
