### ISSUE TITLE
Incorrect tooltips in color zones when selecting by lightness or saturation

### ISSUE THREAD

**Issue by Thanatomanic** [darktable-org/darktable#10962]
**Describe the bug/issue**
A hover tooltip with color names incorrectly shows up when 'select by' lightness or saturation is chosen in the `color zones` module. This should only happen when 'select by' hue is active.

**To Reproduce**
1. Activate color zones module
2. Set 'select by' to either lightness or saturation
3. Hover over one of the keypoints of the curve until the tooltip shows up
4. Move the mouse from left to right to see all colors of the rainbow pass

**Screenshots**
![image](https://user-images.githubusercontent.com/6567747/150666725-37519260-60f3-440a-b4bc-618dddfe9d0c.png)

**Platform**
Self-built darktable (3.8.0+116~gdb1e5fa4a) on Windows 10, and 3.8.0 release on Ubuntu 20.04 (grabbed from [here](https://software.opensuse.org/download.html?project=graphics:darktable:stable&package=darktable))

**Comment by dterrahe** [comment]
Those are the names of the _elements_ of the curve that you can assign shortcuts to. The same shortcuts will work in each mode, but will have different impacts. Since _hue_ is the default and since for example the loupedeck has sliders labelled with the color names, that seemed the best "compromise". But mode neutral suggestions are welcome.
