### ISSUE TITLE
saving sidecar files to a specific location

### ISSUE THREAD

**Issue by tpapp** [darktable-org/darktable#10978]
**Is your feature request related to a problem? Please describe.**

Occasionally, a standalone `xmp` sidecar file is useful for an image. One common use case is in the [play raw](https://discuss.pixls.us/c/processing/playraw/30) section of the forum, where people share their edits as `xmp` files.

Currently saving such a file requires writing it, then locating it in the relevant folder. Mirroring the functionality of *load sidecar file* of the *history stack* module which can load from arbitrary locations, it would be nice to be able to *save* to an arbitrary location with an export dialog.

**Describe the solution you'd like**

A new button *"save sidecar file as ..."* in the *history stack* module that would open a dialog box allowing the selection if a directory.

**Alternatives**

As mentioned above, writing then manually locating the file is possible. This is bit tedious and error-prone with duplicates though.

**Additional context**

See [discussion](https://discuss.pixls.us/t/save-as-sidecar-file/27547/).

**Comment by tpapp** [comment]
Let me clarify and rephrase: this is about `xmp` files that are decoupled from their corresponding raw files in the Darktable collections. You are right that just saving `xmp` files is generally useful, but we already have that and the user does not need to care about their individual location.

The feature request is for something else.

**Comment by jenshannoschwalm** [comment]
I absolutely don't understand this. "Side"car files are and must always be written beside the raw😀 (at least if having done an edit)

I never-ever had a problem locating the xmp file.

**Comment by Nilvus** [comment]
So if I understand correctly, you just want a way to save XMP file of an image where you want. If yes, It's already possible. A step-by-step:

-launch darktable
- select the wanted image in lighttable
- expand develop module in right panel, then click to save xmp button
- save it where you want

You're done!

**Comment by Nilvus** [comment]
Forget last comment (deleted) for those who see it here in their email. I forgot that this doesn't allow to save it where we want. That could just be a thing to update: allow to save where the image is or elsewhere if wanted.

**Comment by tpapp** [comment]
> "Side"car files are and must always be written beside the raw

Not necessarily. As mentioned in the issue, there are use cases for xmp files on their own, eg sharing edits with others who may already have the raw image.

> I never-ever had a problem locating the xmp file.

It is possible, so in that sense there is no "problem", the feature request is about making it more convenient.

**Comment by darkelectron** [comment]
Something that might be easy to implement could be a "locate in file manager" button or option. This would open the location of the sidecar file, and at the same time, the file would be selected.

**Comment by tpapp** [comment]
I think the issue is still open.

**Comment by Nilvus** [comment]
It's a bot @tpapp. This will not be close until a year regarding created date.

**Comment by StaggerLeee** [comment]
May I ask for a new feature ?

- Put a dot "." in the front od XMP filename(s) to be able to hide them in Linux file managers. Cheap fix at least for Linux systems.

**Comment by mxmilkiib** [comment]
Most of my images are in a write-only Syncthing folder, so I guess I can't really use darktable atm(?)

**Comment by ptilopteri** [comment]
you could copy them to a read/write location or change the
attributes in your write-only folder

**Comment by xxxserxxx** [comment]
Could this please be re-opened for consideration? I have a large library of images stored on BDXL disks, and would like to keep the sidecar files in an independent directory which I can repeatedly back up much less expensive but far less durable DVD-RW. Forcing the sidecar files to be colocated with the images is arbitrarily limiting:

- BDXL is archive media. They are not generally RW, and they're expensive.
- Even ignoring BDXL, artists may wish to store their source in immutable shares to prevent accidental damage. Backups alone are not sufficient; backups are often incremental, and incremental backups risk overwriting good data with bad data. When discussing large data sets like raw photographic sources, keeping non-incremental backups is expensive.
- Limiting sidecar files to colocation just because the name is "sidecar" is a silly, arbitrary reason. The solution to that is to change the name. Sidecar files represent modification operations; the fact that they're "sidecar'd" is an implementation detail, not a fundamental characteristic of their primary purpose.
- Users often desire source images to be immutable. This is even recognized in the non-destructive editing design of DarkTable; it is logical that source images to be stored on immutable media, and files representing mutable modifications be stored on mutable media.
- It is a challenge to link sidecars to the source images, but it's not an NP-hard problem, and the technical implementation is far less challenging than the more difficult -- but purely theoretical -- act of defining a process for how to cross-reference files. This challenge alone shouldn't be a reason to _not_ support separating sidecar from source files. There is no hard technical challenge to locating sidecar data separate from source images.

One possible solution to the linking problem is to support variable source references in `xmpMM:DerivedFrom`, or adding another attribute `xmpMM:sourceMedia`. In both cases, supporting variable references would be preferable, as the user could redefine references if (when) source media locations change. For example, in the configuration could be a place where users assign media to variable names `Disk 1 = /mnt/dvd` and in sidecars the setting `xmpMM:sourceMedia="Disk 1"` would be set when media is imported. While this feature could evolve QOL features (identifying removable media by metadata, allowing users to specify that media being added is on removable media, thumbnails for unmounted media), a bare minimum of allowing users to specify storing sidecar data in a different location than source files and simply showing an X when the source is missing would allow use cases such as mine: I want to be able to work on images stored on archival media and store the edit operation log on mutable media.

**Comment by jenshannoschwalm** [comment]
Sean, I think what you propose here is not what the title says, for me you suggest to decouple image from xmp location. I understand your usecase but don't think that many users/devs are affected.

I guess if this is really important to you, you should a) open a new FR ticket describing what you want/suggest and b) you might have to get into coding this yourself and do a draft PR so we could discuss.

**Comment by xxxserxxx** [comment]
This may be true; OP's intention seemed mainly for sharing sidecar files. I'll file an FR.
