### ISSUE TITLE
An unhandled exception occured - at program opening

### ISSUE THREAD

**Issue by LAinChgo** [darktable-org/darktable#11009]
I opened the program and the message was "An unhandled exception occurred" and indicated where the report file could be found.
I've attached the file to this report.
[darktable_bt_W1FKG1.txt](https://github.com/darktable-org/darktable/files/7951574/darktable_bt_W1FKG1.txt)

**Comment by Nilvus** [comment]
Sorry, I will close as there's too much info you provide. We provide a template issue to ask infos, it's there for reasons. And you file report doesn't provide any useful information to understand why darktable is crashing. So, if you want help, please provide a correctly filled issue. Help us to allow us to help you. Before, start launching darktable without OpenCL (if you use it) and/or try to update or downgrade your graphics drivers. Many Windows crash issues had been fixed because of bugged OpenCL graphics drivers.
