### ISSUE TITLE
shortcut incorrectly applied to focused instead of preferred module instance

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11023]
I have created a keyboard shortcut to allow me to adjust exposure with `e+scroll` and have chosen for it to be applied to the "preferred" instance. I would expect this to use the rules applied in preferences>miscellaneous. This works fine unless one of my instances has focus, in which case the shortcut is applied to the focused instance instead.

To reproduce, first set up multi-instance preferences as follows:

![Screenshot_2022-01-29_20-50-09](https://user-images.githubusercontent.com/9555491/151677149-88308f6b-b23d-4194-92b9-546f0201dbbf.png)

Then create three exposure instances on an image, the first and last of which are masked (so the exposure change shortcut should prefer the middle instance). Collapse all exposure instances and ensure that none of them have focus. In this case, "e+scroll" correctly updates the middle instance. 

Now toggle the "view mask" button in the module header of the first (masked) instance (this is how I discovered the issue) and toggle off again. The first module now has gui focus and, until you remove the focus, that module incorrectly has the shortcut applied to it.

I'm ok with it working this way, and can see a potential use case, but would prefer to be able to disable it (with an additional option in preferences > misc).

Originally spotted on 3.8.x branch (`3.8.0+141~gf8c72bea6`) but also reproduced on master (`3.9.0+192~gd535db9d8`).

**Comment by elstoc** [comment]
ping @dterrahe

**Comment by dterrahe** [comment]
This has been the case since https://github.com/darktable-org/darktable/pull/6875#issuecomment-765902713

It should be easy to add yet another option
`  const gboolean prefer_focused = dt_conf_get_bool("accel/prefer_focused");
`
and change
https://github.com/darktable-org/darktable/blob/d535db9d871cdf4c6677d21fc7c574bb2d33460a/src/develop/imageop.c#L2880
to 
`if(prefer_focused && darktable.develop->gui_module && darktable.develop->gui_module->so == module)`
and hope this doesn't break anything (or, alternatively, test).

But please please mark this as default TRUE in darktableconfig.xml.in so that the current behavior doesn't unintentionally change. Because one of the reasons this was done was to have a way of making blending shortcuts be in sync with normal module shortcuts, namely by focusing the instance, since the _prefer__ preferences don't make sense for blending and it therefore _always_ acts on the (last) focused module. This could be added to the `longdescription`.

**Comment by elstoc** [comment]
Sure this definitely makes sense for blending shortcuts but unfortunately it's possible to adjust focus without meaning to (as in the example I gave above) so it took me a while to work out why shortcuts worked this way.

Do we need to add some special handling for blending shortcuts or is that handled elsewhere?

**Comment by dterrahe** [comment]
> Do we need to add some special handling for blending shortcuts

I don't think so; they should just always apply to the last focused module that allows blending. But do test...

**Comment by dterrahe** [comment]
> they should just always apply to the last focused module that allows blending

Now realising, after being reminded of the many calls to `dt_iop_connect_accels_multi` while looking at #11037, that this is currently not the case at all. If enabled or expanded state of any module is changed, blending shortcuts are assigned to its preferred instance. So that will look somewhat random unless focus also changed. Needs to be fixed. I'll add a reminder to #11034. And then, if the new option in #11031 is disabled, it will be back to the maybe somewhat confusing rule discussed in #6875; blending will be active for the preferred instance of the currently focused module.
