### ISSUE TITLE
Console window stays open in Windows 11

### ISSUE THREAD

**Issue by wpwoodjr** [darktable-org/darktable#11021]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
After launching darktable the console window stays open.  It appears to be OK to close it manually.

**To Reproduce**

1. On Windows 11, launch darktable
2. Note two windows are visible, one is darktable, the other is a console window

**Expected behavior**
The console window closes after darktable is launched

**Platform**
* darktable version : 3.8.0
* OS                : W11 (Windows 11)
* Memory            :  16gb
* Graphics card     :  AMD Radeon Vega

**Comment by gi-man** [comment]
I'm on windows 11 3.8 and I dont see this behavior.

**Comment by mraonea** [comment]
Can confirm.

You need to enable the new Windows Terminal to see this issue:

https://docs.microsoft.com/en-us/windows/terminal/install

**Comment by mraonea** [comment]
This is due to the new default behaviour of "Close only when process exits successfully" in Windows Terminal.

**Comment by wpwoodjr** [comment]
> This is due to the new default behaviour of "Close only when process exits successfully" in Windows Terminal.

So whatever this window does is not successful?

**Comment by ptilopteri** [comment]
it probably means the terminal window will close when darktable successfully exits.
note: I am not a windows user

**Comment by Sonstwer** [comment]
I have the same issue, how do i prevent this from happening?

**Comment by Nilvus** [comment]
It's related to Windows terminal, not directly darktable. You have infos above and you could probably find informations about how to deal with Windows Terminal on Windows forums or Microsoft sites.

**Comment by victoryforce** [comment]
> I have the same issue, how do i prevent this from happening?

Probably, select an old, proven conhost.exe as the default terminal app instead of new and shiny Windows Terminal in the Windows settings.

**Comment by SoftwareBizId** [comment]
I have had same issues, solve to "hide"/exit console icon by:
1. Open where your shortcut file location (e.g. from start: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\darktable, because I pin it to Start)
2. Open properties (Right click the shortcut icon)
3. Select tab Options
4. Check: Use legacy console (require relaunch, affects all consoles)
5. On next launch, the console is hide/exit automatically

![image](https://user-images.githubusercontent.com/47493037/209507013-6c24b02e-8316-4966-87da-831ea4cbcfc6.png)

Hope this works for others as well.
