### ISSUE TITLE
dt3.8.1: Gtk-CRITICAL assert in history stack, mouse hover the "input color profile" step of some old edits

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#11129]
**Describe the bug**
In darktable 3.8.1, with some pictures edited several years ago, moving the mouse hover the history stack in the darkroom is triggering Gtk-CRITICAL assertions. More specifically, assertions come hovering the "input color profile" operation

`(darktable:35668): Gtk-CRITICAL **: 11:35:05.535: gtk_text_buffer_emit_insert: assertion 'g_utf8_validate (text, len, NULL)' failed`

**To Reproduce**
1. Enter in the 'darkroom' with one picture edited in an older version of darktable (back in 2017)
2. Move the mouse hover the "input color profile" step in history stack

"input color profile" settings:
- Input profile: standard color matrix
- working profile: linear Rec709 RGB
- gamut clipping: off

Please note that this issue is only observed with some images, edited several years ago with an old darktable version.
See xmp of one sample in attachment
I'm not able to reproduce this assert with brand new edits from darktable 3.8.1

**Expected behavior**
No Gtk assert

**Platform (please complete the following information):**
    OS: Ubuntu 21.10
    darktable 3.8.1

**Attachements**
xmp of edit creating the issue:
[DSC_7511_06.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/8055392/DSC_7511_06.NEF.xmp.txt)

**Comment by TurboGit** [comment]
Looks like some old version did not properly initialize the filename[] field in colorin.c

For example here in commit a961fa0c361307c2c7cbbe011bfb94fc2e1013b5

So, I suppose the filename may contain garbage and that's what I'm seeing in debugging. The only solution at this point is to double check that in introspection when we get a string that it is valid UTF-8 otherwise we drop it.

After looking at this though it seems to me that this Gtk-CRITICAL does not break the edit. At least we are safe!

**Comment by TurboGit** [comment]
@leclercj : See #11133

**Comment by leclercj** [comment]
https://github.com/darktable-org/darktable/pull/11133 is fine. thanks
And good to know we are safe with these old edits
