### ISSUE TITLE
The perspective correction module is not working correctly

### ISSUE THREAD

**Issue by Lorenzoeffe** [darktable-org/darktable#11158]
Good morning, 
I would like to point out that the perspective correction module, in the automatic version, does not seem to work correctly.
In previous versions of DT >3.8, the module worked, but now it corrects the perspective but stretches it.

Auto crop: Indifferent to the end of the test
Lens model: Indifferent to the end of the test
Automatically analyzes structure
Corrects automatically

The perspective is distorted, and stretched

**Comment by AlicVB** [comment]
Although there has been changes in the module for 3.8, the algorithm itself has not changed afaik...
Can I ask you the following : 
- does an image with perspective applied in 3.6 change when opened in 3.8 ?
- can you take following screenshot, done with the exact following steps : 
1. open an image in 3.6
2. discard the history
3. take screenshot n°1 (image uncorrected)
4. click on "automatic analyze structures"
5. take screenshot n°2 (with the control lines)
6. apply the correction
7. take screenshot n°3 (image corrected)
8. open same image in 3.8
9. discard the history
10. click on "automatic analyze structures"
11. take screenshot n°4 (with the control lines)
12. apply the correction
13. take screenshot n°5 (image corrected)

I know that's quite a big job, but I don't reproduce here, so we need help to understand the root cause...
Thanks !

**Comment by Lorenzoeffe** [comment]
OK !
As soon as I have time to take the test, I'll do it.

Lorenzo Fontanella

Il mer 16 feb 2022, 23:18 AlicVB ***@***.***> ha scritto:

**Comment by Lorenzoeffe** [comment]
Hello everyone,
screenshots performed.
Missing the initial 1 screenshots with the image just opened, but it matters little for the purpose of detecting the problem.

Greetings
Lorenzo

![Image 18 02 2022   155132](https://user-images.githubusercontent.com/50571973/154709389-77a00193-b4bd-4f40-bbf7-d889f37b121e.png)
![Image 18 02 2022   160826](https://user-images.githubusercontent.com/50571973/154709412-3c54eba3-0f3c-4f5b-8e65-1539d8f0d6bc.png)
![Image 18 02 2022   160821](https://user-images.githubusercontent.com/50571973/154709418-8e95022a-c09f-417c-98c8-17e053d2134b.png)
![Image 18 02 2022   155136](https://user-images.githubusercontent.com/50571973/154709433-91299c71-6859-4080-80e2-26667599fff4.png)

**Comment by AlicVB** [comment]
Well, there's some other things involved here : 
1. probably the most important : you don't have the same modules applied by default (certainly due to a switch to "filmic" pipe) And that change the resulting image (just see the exposure as the most obvious example, but I suspect other difference too). And of course the resulting analyze of the structres differ (see for example the corner between the right wall and the ground : they are blue in one case and yellow in the other, which means that thir validity differ)
2. in the second case, it seems you have not choosed the right "apply" button... and so you only correct vertical lines...

I fact I suspect that point 1 is what the cause of the difference you see... To be sure, you can redo the test, but use a jpeg file instead of a raw, so you are quite sure that the base image is the same...
Sorry again to annoy you... I know for sure how boring it is to switch between dt version...

**Comment by AlicVB** [comment]
> The problem lies as you pointed out in the difference in automatic detection

yes... and that point as not changed afaict...
So you confirm that with a (undistorted) jpeg file as source, you get different structures in 3.8 than in 3.6, right ?
Can you by any change share the jpeg file (put it somewhere on the web, I'm fear github apply some recompressing when posting inside issues directly), so I can test in my side and try to reproduce ? (put it somewhere on the web, I'm fear github apply some recompressing when posting inside issues directly)
Thanks !
