### ISSUE TITLE
Nonsensical casts in iop process functions

### ISSUE THREAD

**Issue by rabauke** [darktable-org/darktable#11164]
Not really a bug report, more an observation of a (possibly) bad pattern that can be observed in all image processing modules:

In all image processing modules we find in the `process` function:

```C
  const float *const restrict in = DT_IS_ALIGNED((float*)ivoid);
  float *const restrict out = DT_IS_ALIGNED((float*)ovoid);
```

where `DT_IS_ALIGNED` is defined as 

```C
#define DT_IS_ALIGNED(x) __builtin_assume_aligned(x, 64)
```

with

```
void * __builtin_assume_aligned (const void *exp, size_t align, ...)
```

Thus,
```C
  const float *const restrict in = DT_IS_ALIGNED((float*)ivoid);
```
casts the `void` pointer `ivoid` explicitly to a pointer to `float`, which is then implicitly converted to a pointer to `void` by passing it to `__builtin_assume_aligned`, which returns a pointer to `void`, which eventually is converted to a pointer to `float`.

I wonder, shouldn't this be just

```C
  const float *const restrict in = DT_IS_ALIGNED(ivoid);
  float *const restrict out = DT_IS_ALIGNED(ovoid);
```
(or
```C
  const float *const restrict in = (const float*)DT_IS_ALIGNED(ivoid);
  float *const restrict out = (float*)DT_IS_ALIGNED(ovoid);
```
when one wants to be verbose)?

**Comment by dterrahe** [comment]
> when one wants to be verbose

Looking across the code, we _DEFINITELY_ want to be as verbose as possible.

I agree that there is no point to explicitly casting any void pointer to any other type of pointer before assignment (whether to a void pointer or to a matching pointer type). But then, we regularly GTK_WIDGET() GtkWidget *s etc etc. The whole "better be safe than sorry" except it does affect performance (ok, minor since UI anyway) or (compile time) type safety; a forced cast actually _avoids_ type checking if the pointer happens to _not_ be to void.

Anyway, not sure if we'll get very far without a comprehensive cleanup as people will keep copying old patterns back in. And @TurboGit won't have time to "police" this anyway.

So I would suggest, unless you have wider ambitions with this, that there is not too much benefit highlighting this particular case. If you agree, you might as well close this.

(I know, I know, keeping the number of issues down to a manageable level is a lost cause by now)
