### ISSUE TITLE
Darktable 3.8.1. runs on the second monitor instead of the main monitor on Windows 8.1

### ISSUE THREAD

**Issue by MRedbook** [darktable-org/darktable#11185]
Unlike the previous versions (for example 3.8.0.) DT 3.8.1. runs on the second monitor that is defined in Windows settings. The main display is larger with high resolution. So, I have to move DT each time from second display to the first display.

My operating system is Windows 8.1. Until now this has not been an issue with the older DT versions. I will be pleased to hear any hint how to change this.

Best regards,
Mustafa

**Comment by MRedbook** [comment]
I guess, I solved the problem at least on my PC.

I edited Windows shortcut “darktable” to execute DT by right click on Features (Eigenschaften in German) and under the register “Shortcut (Verknüpfung)” I selected execute minimized instead of “normal window (normales Fenster)”. Thereafter DT 3.8.1. starts on the primary screen.

Since I use German version of Windows I do not know exact wording for the settings and options.

This try-and-error solution may be useful to identify the origin of the bug.

**Comment by lphilpot** [comment]
See full conversation: https://discuss.pixls.us/t/darktable-3-8-1-runs-on-the-second-monitor-instead-of-the-main-monitor/29511/3?u=lphilpot

Per above link -- FWIW, I’m seeing the same thing basically, on Windows 11, latest release, fully patched.

If I restore (normalize / free floating window) darktable, move it to the primary monitor and then without maximizing shut it down, it’ll start back up normalized on the primary monitor. I can then maximize. But if I shut it down maximized, it starts on the secondary monitor as defined in Windows (which is my laptop’s attached display).

This wasn’t happening before and I’ve also upgraded to 3.8.1. Whether or not it started precisely after the upgrade, I can’t say. Best I can recall, it started after I disconnected the laptop from its dock (including external / primary monitor) and then used darktable on the panel. After reconnecting, I’ve been unable to get darktable to start maximized on the external / primary monitor.

It’s the only app where I’ve had this issue. I initially was ready to lay this issue at the feet of the OS / window manager (dwm.exe in Windows, IIRC) instead of darktable since that’s what manages window placement and state. But only darktable is doing it, so there must be some kind of connection.

**Comment by lphilpot** [comment]
One other detail, on my system at least -- darktable initially starts on the correct monitor with a title bar and white maximized window but then switches and populates on the other monitor.

**Comment by lphilpot** [comment]
A workaround was found, per https://discuss.pixls.us/t/darktable-3-8-1-runs-on-the-second-monitor-instead-of-the-main-monitor/29511/21?u=lphilpot
