### ISSUE TITLE
Nintendo Switch Controller false mapped buttons

### ISSUE THREAD

**Issue by every-good-name-is-already-taken** [darktable-org/darktable#11192]
**Describe the bug/issue**
I want to use the wired Nintendo Switch Controller made by PowerA.
lsusb = ID 20d6:a711
[https://www.powera.com/p/nintendo/nintendo-switch/controllers/wired/wired-controller-for-nintendo-switch-white-1517033-01/](url)

But some buttons and sticks are mapped wrong and some are not recogized.
controller   >>>   darktable
dpad left = is ok
dpad right = is ok
dpad up = is ok
dpad down = is ok
button B = is ok
button X = is ok
left stick movement = is ok

button A = not recognized
button Y = button A
left shoulder = button Y
right shoulder = not recogized
left trigger = left shoulder
right trigger = right shoulder
left stick press = button back
right stick press = button start
small sqare button = left stick
small home button = button guide
small round - button = not recognized
small round + button = not recognized

* darktable version : e.g. 3.8.1 from OBS build service (latest release)
* OS                : e.g. Linux -  5.11.0-46-generic
* Linux - Distro    : e.g. Kubuntu 20.4
* Desktop           : Kde Plasma

**Additional context**
 - Can you reproduce with another darktable version(s)?
 yes with 2.9 snapshot from the master branch from OBS

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? 
 yes

 in Windows 10 the same buttons are not or wrong recognized

**Comment by dterrahe** [comment]
dt uses sdl2 for gamepads so the configuration for your controller needs to be corrected in sdl2. Does it work correctly in for example Steam?

**Comment by every-good-name-is-already-taken** [comment]
No it does not work in other software.

I used the SDL2 Gamepad Tool tor map the buttons and tried to  "Set  Mapping As Enviroment Variable" but nothing changed.
![image](https://user-images.githubusercontent.com/99798848/154937309-4e9d02fc-c810-4598-bc2c-d7bc26a4c63e.png)


then i tried:
 export SDL_GAMECONTROLLERCONFIG="03000000d620000011a7000011010000,Nintendo_Switch_PowerA,a:b1,b:b2,x:b0,y:b3,back:b8,guide:b13,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Linux,"
exec darktable

this partially work but the 2 trigger buttons are not reconized.
the next thing is how can this be done in windows?

**Comment by dterrahe** [comment]
Thanks for reporting back!

All my controllers worked out of the box, so I don't have personal experience with these configurations. Maybe others can help. I thought steam used sdl2 too and configuring a controller there might automatically get it recognized elsewhere. But it is entirely possible that there are separate databases.

The two triggers indeed don't do anything; they are funny kinds of joysticks that don't have a + and - and don't rest in the middle, so they are probably not that useful in dt except maybe as an additional standard button. I haven't had any feedback on this module (which wasn't meant as _that_ serious a project anyway; more a fun way to show the capabilities of Input NG), so suggestions are welcome. The triggers could probably be made to act as single/double/triple press depending on how far they are pulled.

**Comment by dterrahe** [comment]
> The funny thing is t SDL2 gamepad config tool recognize the trigger buttons but darktable does not.

Oh, but this is simply a matter of it not being implemented (in function `process_axis_and_send`) because I hadn't decided what to do with them yet. This was all built before the InputNG framework was finished so at that point it didn't matter much...

> Which controllers do you have?

ds4, xbox one and some vague ds2 clone. Triggers don't do anything for any of them.

> it would be great if there is one central place where users can upload their shortcuts for different devices

For now, the best suggestion I have is to propose additions to https://github.com/darktable-org/dtdocs/blob/master/content/special-topics/midi-device-support.md (maybe discuss with @elstoc first). It would only be a starting point, because everybody would have their own preferences. But it could serve to showcase the capabilities.

We could add standard layouts to dt itself and automatically prompt the user to import one when a known device is recognised. This is somewhat chicken/egg; when there are enough layouts available, there would be an incentive to implement this.

**Comment by elstoc** [comment]
Happy to include more device information in that section but I'd need you to review @dterrahe since I probably won't be getting into device-support specifics myself.

**Comment by dterrahe** [comment]
I'm happy to provide sign off if PRs are directly submitted to dtdocs. In this case I was thinking of a simple link to a file exported from the shortcuts preferences containing only midi mappings.

If we end up getting many of those for different devices and different variants for the same device, we'd probably want to put them in a table (rather than a link in a device topic) but lets not get ahead of ourselves; we may never receive more than a few.

**Comment by every-good-name-is-already-taken** [comment]
![IMG_20220221_192037.jpg](https://user-images.githubusercontent.com/99798848/155009239-3eb4119c-0092-4725-81a3-9b0a33d68f60.jpg)

**Comment by every-good-name-is-already-taken** [comment]
I want to start with my NES controller.
![155009239-3eb4119c-0092-4725-81a3-9b0a33d68f60](https://user-images.githubusercontent.com/99798848/155009751-cb0fbc10-7d01-4ff2-89b7-430daed75749.jpg)

Maybe it would be possible to add a folder to the darktable repository, something like this:
[https://github.com/every-good-name-is-already-taken/darktable-gamecontroller-presets/tree/main/NES%20Controller](url)

**Comment by dterrahe** [comment]
For game controllers I don't think it makes sense to create model-specific layouts, because SDL2 tries to map them all to standard controller layouts (two joysticks, dpad, AB, XY buttons, shoulder buttons and triggers). So a layout for one works on another. Unless it is very limited, like this NES one, but if at all, people would probably chose to use those in very personal ways.

It is different for midi controllers, since their layouts and capabilities very wildly and in some cases (loupedeck) are meant to use in very specific ways.
