### ISSUE TITLE
Last line in tooltips is "button" or "force"

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#11224]
Reproduce:
Hover mouse over a slider like for example the exposure slider.
Now the last line in the tooltip displays "button" or "force".

![Bild1](https://user-images.githubusercontent.com/57685590/155683362-91b0516a-e7f9-4f07-9ec5-6b874863a080.jpg)

This happens in my selfbuild (MSYS) master (3.9.0+542).

Does not happen in the regular 3.8.1.
EDIT: does also happen in 3.8.1, but the word "button" is displayed only when the mouse is at the right end of the slider.

OS: Win 10

**Comment by elstoc** [comment]
It does happen (for me) on 3.8.1. I think the intention is to show what sort of shortcut can be mapped when hovering over the area. When hovering over most of a slider you can map a normal slider value change (which respects the restrictions set in the slider boundaries). When hovering over the end of the slider, this changes to "force" (which allows you to change the slider but does not respect soft slider restrictions). When you hover over the button area of the slider (where the tooltip normally resides), a shortcut will activate the "button" (if present).

So I think this is expected behaviour but perhaps it should only show in the visual shortcut mapping mode, or when a shortcut has been allocated.

**Comment by TurboGit** [comment]
> So I think this is expected behaviour but perhaps it should only show in the visual shortcut mapping mode, or when a shortcut has been allocated.

Yes, we may want something clearer here. @dterrahe, an idea?
