### ISSUE TITLE
ru-Language support 

### ISSUE THREAD

**Issue by EvgMakaev** [darktable-org/darktable#11222]
**Is your feature request related to a problem? Please describe.**

In 3.8.1 there is not ru-Language support

**Describe the solution you'd like**

I have found a translater for russian language (GitHub: TeaPerson). Please help her, if she need any support
Thanks

**Alternatives**

**Additional context**

**Comment by Nilvus** [comment]
It's good you found someone for that. You could see here who had worked on russian language: https://github.com/darktable-org/darktable/commits/master/po/ru.po

Note that TurboGit didn't work on that, he just submitted russian update from @whiv77 person. TurboGit is french and doesn't speak russian.
You could see that @Timur Davletshin was the last main russian translator but I haven't seen him here since months. But maybe he will be able to help.

Apart of that, darktable team can't help more here.

**Comment by ptilopteri** [comment]
@Timur_Davletshin has posted on the mail list lately and appears
on irc frequently, but not for a few days.

**Comment by victoryforce** [comment]
It would be good to close this issue. Please do it, @EvgMakaev.
