### ISSUE TITLE
using libraw to support more format

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11235]
Now that we have LibRAW and the recent clean-up for the colorMatrix done for #10635, can we now use the new libraw library to support some more RAW formats?

We had discussed this briefly this before 3.8.0, let's revisit this idea now that we are not in a rush :)

**Comment by TurboGit** [comment]
@kmilos : We discussed that, what do you think? Any formats in mind?

**Comment by kmilos** [comment]
CR3 was easy/clear cut. Now we're getting into supporting particular models/modes (e.g. Sony lossless, Fujifilm lossy, Blackmagic and Apple DNGs) which makes it a bit more complex to manage unfortunately - I don't think having a mix of rawspeed and libraw for the same model but different modes is ideal, there might be some differences in how metadata and crops are interpreted so edits might not be preserved identically in the future?

I've seen there has been demand for PhaseOne IIQ, so that could be one candidate to fallback to LibRaw completely...? The open list is of course [here](https://github.com/orgs/darktable-org/projects/1).

**Comment by TurboGit** [comment]
@kmilos : Thanks for the feedback, I have tried to enable `IIQ` on LibRAW. It is loaded OK but dt crash just after :( So looks like there is more issues for supporting this format.

**Comment by TurboGit** [comment]
For the record, what I have tested is simply:

```
diff --git a/src/common/imageio_libraw.c b/src/common/imageio_libraw.c
index d3e9c477d..fa06d6c30 100644
--- a/src/common/imageio_libraw.c
+++ b/src/common/imageio_libraw.c
@@ -180,7 +180,7 @@ const model_map_t modelMap[] = {
 
 static gboolean _supported_image(const gchar *filename)
 {
-  const char *extensions_whitelist[] = { "cr3", NULL };
+  const char *extensions_whitelist[] = { "cr3", "iiq", NULL };
   char *ext = g_strrstr(filename, ".");
   if(!ext) return FALSE;
   ext++;
diff --git a/src/common/imageio_rawspeed.cc b/src/common/imageio_rawspeed.cc
index 2cd422bda..a0bb901e8 100644
--- a/src/common/imageio_rawspeed.cc
+++ b/src/common/imageio_rawspeed.cc
@@ -120,7 +120,7 @@ uint32_t dt_rawspeed_crop_dcraw_filters(uint32_t filters, uint32_t crop_x, uint3
 // as this issues lot of error message on the console.
 static gboolean _ignore_image(const gchar *filename)
 {
-  const char *extensions_whitelist[] = { "cr3", NULL };
+  const char *extensions_whitelist[] = { "cr3", "iiq", NULL };
   char *ext = g_strrstr(filename, ".");
   if(!ext) return FALSE;
   ext++;

```

**Comment by TurboGit** [comment]
No incentive to move this forward at the moment.
