### ISSUE TITLE
Inconsistent lighttable rating behavior when grouped - keyboard and mouse give different results

### ISSUE THREAD

**Issue by andrewk8** [darktable-org/darktable#11243]
**Describe the bug/issue**
When grouping is enabled in lighttable, I've noticed an inconsistent behavior where sometimes ratings are applied to the group but sometimes individual images.  I shoot RAW +JPEG which are automatically grouped when imported.  I want my ratings to apply to both.

I shoot Sony, so ARW is the group leader.  But I prefer to do my first pass using the JPEG.  I stumbled on the below method, but ratings only works sometimes (mouse but not keyboard).

**To Reproduce**
* lighttable mode with imported raw+jpeg pairs
* toggle grouping on
* collections: film roll
* collections: add a filter to narrow down search on filename 'j' - now only .jpg version of group shows
* start sticky preview mode (f shortcut)

Stick preview mode shows only the JPEG versions of the filmroll.

If I use the mouse to click 'rejected' or a rating, I get a pop-up ... applying ... to 2 images (correct behavior).  But if I use the keyboard shortcuts r,0 ... 5, it applies only to the JPEG copy that's filtered (i.e. it does not apply the rating to the ARW member of the group that is filtered out).

If you've tried both ways, you have to exit sticky preview mode and un-group to check the ratings of the individual files.

**Expected behavior**
when grouped, the rating should apply to every image in the group (filtering the collection shouldn't matter).  You get a different result depending on whether you use the mouse (correct behavior) or keyboard (incorrect behavior).

**Platform**
* darktable version : 3.8.1
* OS                : Windows 10 x64 21H2
* Memory            : 32 GB
* Graphics card     :  NVidia GTX 1660

**Comment by dterrahe** [comment]
Is it a regression in 3.8? If not, then no.

**Comment by AlicVB** [comment]
Confirmed.
And I've found where it comes from :) (sadly it's not your fault @dterrahe... I'll have more work :-D)

But I don't agree on what should be the correct behavior : in your case, you add a filter to specify that you only want want jpeg in your collection. And we should *not* change, in any cases, images outside the collection.
- Your workflow is quite specific in fact (review with jpeg but edit with raw) and I'm not sure it's the best one (dt will try to use embeded jpeg by default, even in sticky preview)
- The opposite scenario is more useful imho : in order to set something specific only for jpeg : use the 'j' filter, select all and apply the change.

I'll have a look asap

**Comment by andrewk8** [comment]
@AlicVB like I mentioned, I shoot Sony.  So in the default grouping from import .ARW is the group leader.

In filemanger layout, after importing, grouping shows the embedded JPEG thumbnail.  But when I flip to sticky preview, it flashes the embedded JPEG for <1 second, then switches to the un-developed RAW (which is flat and under-exposed for Sony).   <-- So is *this* a different bug in lighttable (or related modules) showing the un-developed raw for an un-edited photo?

I was playing around with how I could get the JPEG to be the group leader instead of the ARW to make the first pass of sticky preview more useful (to me).  Filtering by file name (extension) was good enough.  And serendipity that I found a way to get the ratings to apply to both images.

Agree that with a collection filter, the operations should only apply to the active files.  But seeing only the un-developed images in lighttable mode is pretty annoying.

I'm new to DT and just switched to RAW+JPEG shooting.  So I'm not white sure what's normal.

**Comment by andrewk8** [comment]
So here's the start of my problem.  I'd rather evaluate images from a film roll using the SOOC JPEG before I decide to do any edits of the RAW. See attached video.

0:46, enter sticky preview. 0.7 seconds later, it changes to the un-developed raw.
0:48, right arrow key to go to the next image.  It shows only the un-developed raw, not the embedded JPEG.
0:50, right arrow key to go to the next image.
etc.

sticky preview shows only un-developed raw (except for 0.7 seconds). The thumbnails in the filemanager view are still showing the embedded JPEG.

_feature request_: change the group leader on the fly without having to un-group / re-group.

_bug_: why does sticky preview show the embedded JPEG for less then 1 second, then only the un-developed raws?
[Darktable 3.8.1 Windows.mkv.zip](https://github.com/darktable-org/darktable/files/8157537/Darktable.3.8.1.Windows.mkv.zip)

Bug?  New bug different from the original issue?

**Comment by AlicVB** [comment]
@andrewk8 : what you see is "normal" behavior when dt needs to develop raw instead of using jpeg : you first see the previous size (jepg) upscaled, and then the developped raw once it's ready...
To track down the problem, some questions : 
- just to be sure, can you verify that the setting "use raw file instead of embeded jpeg from size" is set to never ?
- what is your screen size ?
- can you share one of the problematic raw file by any chance ?

**Comment by AlicVB** [comment]
OK, thanks. The issue is that your APN seems to only embed a downsized jpeg, not the fullsize one : exiftool (for example) show a jpeg of 1616x1080 which is below thumb cache of size 4. But your screen needs an image of size 4... So dt has to get it directly from the raw file...
You don't see that for smaller size, as starting from size 3, dt can (and do) use the embedded jpeg.

So for this point, we can't do anything...

Anyway, thanks for the report. I start now to fix the first issue :)
