### ISSUE TITLE
Darktable pink issues in Image with Panasonic Lumix G80 / GX85

### ISSUE THREAD

**Issue by HATEbreedsHATE** [darktable-org/darktable#11331]
Hello everybody,

I am new to Darktable and having some issues with overexposed RAW images with my Lumix DMC-GX80 like in #10322 mentioned before. So firstly in the Lightroom, everything looks "fine" but after using the Darkroom the white colors had been interpreted wrong and changed permanently to pink.

**Screenshots**
![image](https://user-images.githubusercontent.com/9548441/158227128-d9752bc0-83ad-4c16-a11d-3787bc1472a2.png)
![image](https://user-images.githubusercontent.com/9548441/158228138-829c67ee-6b09-4ae1-91f4-73b4ea51de0a.png)

**RAW**
[P1000093.RW2](https://storage01madcat.blob.core.windows.net/pubexchange01madcat/P1000093.RW2)

**XMP**
[P1000093.RW2.xmp.txt](https://github.com/darktable-org/darktable/files/8247375/P1000093.RW2.xmp.txt)

**Platform**

* darktable version : 3.8.1-win64 (same issues with 3.8.0-win64)
* OS                : Windows 10 Education 64 Bit (10.0, Build 19044)
* Memory            : 16 GB
* Graphics card     :  AMD Radeon RX Vega
* Graphics driver   : Adrenalin 21.12.1 
* OpenCL installed  : yes
* OpenCL activated  : yes

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with with 3.8.0-win64**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**

Thanks in advance!

Best regards,
Markus

**Comment by Nilvus** [comment]
This is absolutely not the same issue as #10322. This is just caused by some wrong set highlights. And mostly because burned pixels. Click on button in bottom bar to show RAW overexposed ones and all are in pink part (not all pink part is burned pixels though). You could fix that by using reconstruct highlight module and reduce a little troncature slider (you could also test with 3 modes proposed. Most of the time, setting in this module shouldn't be change (except when you have that). You could also use with that color calibration module to adjust more if needed.

I so close as this is not an issue on darktable code but just how to use/fix raw with darktable. If you need more help on that, I suggest to start a thread on https://forums.pixls.us.

**Comment by HATEbreedsHATE** [comment]
Thanks for the fast and informative reply and sorry for the misinterpretation!

**Comment by Nilvus** [comment]
Just to correct my pixls.us link. It's https://discuss.pixls.us/

**Comment by befocken** [comment]
I just got into the same situation with the same camera, but I got to say that I do not understand where the issue lies and how to fix it for future images. Even if some pixels are "burnt out" (I guess you mean clipping at their max value?), shouldn't they be displayed as pure white then, instead of pink @Nilvus?
This issue also occurs without touching the highlights module at all (or resetting the history to "original", therefore seems to be the default behavior there? How is this not a problem with Darktable?
