### ISSUE TITLE
Cant select the All from the filter

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#11355]
**Describe the bug/issue**
Can't see the All when in darktable full screen view after selecting Rejected Only.

Workaround: select 2 star, then click again to select All. 

**To Reproduce**
With darktable in fullscreen (not lightable full screen). Select Rejected Only, then try to switch to All in the view selection.

**Expected behavior**
The selection populates in the visible screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/97920861/158820592-c72caf85-b0fa-4d7f-aeec-4b76c3b47e5e.png)

**Platform**

* darktable version : 3.9.0+219~g06ad12bae
* OS                : Windows 11
* Memory            :  16Gb
* Graphics card     :  Nvidia 3060
* Graphics driver   :  511.79
* OpenCL installed  :  yes
* OpenCL activated  : ON

**Comment by gi-man** [comment]
@AlicVB and @Nilvus This is happening in 3.9.0+798~g8152dd9d6 with the Sort By selection too. Maybe it was happening before but I did not notice. 

The scroll wheel workaround does help.

**Comment by Nilvus** [comment]
I remember this issue as a Gtk issue (I don't know if this had been fixed in Gtk or not and which version could be used in Windows) more than darktable one about such popup. It mainly depend on windows size and what space around. I have it some time but not often now. I don't check a way to reproduce nor will do it. It's annoying but if it remains a Gtk issue, darktable team can't do anything. But maybe @dterrahe has other infos or ideas about this issue and how to fix it as he assigned it to him.

**Comment by dterrahe** [comment]
Nothing to do with gtk; we position the bauhaus pop-up ourselves. These comboboxes _used_ to be standard gtk, but were changed to bauhaus to benefit from inputng; you can assign shortcuts to them and they will pop-up at the mouse cursor (even if the header bar is hidden). Well, they did before it got broken...

I'm almost done with a fix but trying to figure out if i can fix other things that recently got broken or if I'll leave them for now.

**Comment by Nilvus** [comment]
Ok, thanks for your answer. What was broken in those combobox?

**Comment by dterrahe** [comment]
Maybe fixed in #11359 I don't know yet. Rebasing off that now, which looks tricky...

**Comment by dterrahe** [comment]
Sigh.
