### ISSUE TITLE
Vectorscope display could use a little padding....on Windows at least... primary red node can be obscured or almost

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#11381]
Win 11
DT  3.9.0+776~g83a96dfd

![image](https://user-images.githubusercontent.com/44409419/159404574-9dfd8aaa-c33d-45c7-a89f-2d0b81b7470d.png)

![image](https://user-images.githubusercontent.com/44409419/159404675-b9645802-e985-4765-8008-e2e7da6c9568.png)

**Comment by dtorop** [comment]
I'll take a look -- not until next week at earliest though! I actually don't think it's that hard to change...

My memory is that the vectorscope is scaled so that the furthest color node from neutral (red in this case) precisely aligns with the edge of the graph. So nothing is being obscured in the graph. But this means that the red point is half-chopped, which may look awkward.

As a healthy image probably doesn't have a graph extending all the way to the edge of the scope, most always the graph shouldn't be obscured, just the color of the node...
