### ISSUE TITLE
FR: Make the grid button lines grey instead of red and green

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#11404]
The red and green lines are really hard on my brain as the colours create some strange contrast where the lines intersect. Is there a reasoning why this icon is not grey like all (except the ones where colours are necessary) the others?

**Comment by Nilvus** [comment]
Just because this icon had been done that way (I'm not the creator) and probably because this icon is related to the possibility to chose how to set guide lines, including colors of the lines!

Even if I don't like this icon, and maybe I will take time one day to rework it, I find this normal. And you have an icon a lot older that should also be hard to your brain and quite next to that icon, a little on the left on bottom toolbar. I talk about RAW overexposed toggle icon.

**Comment by Nilvus** [comment]
Icon updated on my PR #11559. You have screenshots on it

**Comment by elstoc** [comment]
That one was mine, and it was because when it was created it only allowed the guide line colours to be changed. Now it allows more stuff to be set as well as the colour I agree it makes more sense for to be grey.
