### ISSUE TITLE
Darkroom: selected image sometimes does not match selected thumbnail

### ISSUE THREAD

**Issue by jec993** [darktable-org/darktable#11411]
Darktable 3.8.1 Windows 11
Processor	AMD Ryzen 5 3600 6-Core Processor, 3600 Mhz, 6 Core(s), 12 Logical Processor(s)
Installed Physical Memory (RAM)	32.0 GB
OpenCL enabled

When using the keyboard to move next/prev image, sometimes the thumbnail changes to the next/prev image, but the "main"(large) image does not change. 

this does not occur all of the time, but often enough to be troublesome. 
there is no other selection or selectedImages in play.
when this occurs, edits apply to the "main"(large) image.

Repro:
select one image in darkroom, use keyboard to move to next/prev images.

in this screenshot, you can see that the thumbnail has advanced to the next image while the "main" image has not advanced.

![image](https://user-images.githubusercontent.com/43044672/160288673-28aa8263-cdc5-461d-9e76-cb153bfa9005.png)

images are all .nef from a D850
there are a lot of basic adjustments on each image (exposure, noiseReduction, lensCorrection, contrast, crop,...)

thank you,
-jec993

**Comment by domosbg** [comment]
That also happened if you select the picture by mouse from time to time in my installation.

![grafik](https://user-images.githubusercontent.com/88573684/164993043-c1d06431-a89e-4d23-bcb6-c4822d73c3af.png)

Two pictures in the thumbnail bar are light gray and the marker is on the wrong picture.

Unfortunately it is not 100% reproducable. It seems to happen if you switch fast between pictures (before the picture in the main view is fully processed (the working... tooltip is still shown)). 
Maybe the switching of the pictures colidates with the opening process of the pictures.

I work also with DT 3.8.1 on windows 11, but im 99% sure that the problem existed already in prior version of DT and also on windows 10.

**Comment by Nilvus** [comment]
Just seen that. it's normal behavior. To explain:
when selecting a new image (or move to next image), the top arrow is moved to next image to show (it's quick and let you know that you have correctly choose to change image). After that, thumbnail will be updated. Time for that is slower because this need to take account on modules used to process image. And depending on those AND your system configuration, it could be quick or slow. 

As @domosbg writes himsel: " (before the picture in the main view is fully processed (the working... tooltip is still shown)).". When "working..." message is shown, that just means that darktable is processing loading of the image (and so update of thumbnail in filmstrip.
