### ISSUE TITLE
RFC - have some pref only visible into an expert mode

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11420]
**Is your feature request related to a problem? Please describe.**

Too many preferences.

**Describe the solution you'd like**

Have some options only displayed in an expert mode.

**Alternatives**

Using an editor to manually edit `darktablerc`.

**Additional context**

Using an editor to manually edit darktablerc feel not a good point for dt which is at this stage very widely used. The project has grown to a stage where I feel this is not acceptable anymore.

Please, comment... What is your view on this?

**Comment by elstoc** [comment]
Are we talking about...

- Adding more options that are currently only in darktablerc, but hidden behind an expert mode
- Hiding some existing preferences behind the expert mode
- Some combination of the two

**Comment by TurboGit** [comment]
I would say some combinations of the two. Some prefs have been added but are very marginals so will be better not always displayed. Some options may be added to avoid the "use your editor to change bla bla...".

On my side, I may not be representative, I think I have changed less than 10 options in the prefs. Let me start dt and count...

Ok, I have changed exactly 15 options.

**Comment by elstoc** [comment]
> Ok, I have changed exactly 15 options

I count 20 on mine

**Comment by elstoc** [comment]
Or even just a tickbox that says "show additional options" or something

**Comment by ptilopteri** [comment]
or even "other" settings

**Comment by TurboGit** [comment]
> Are we talking about including additional options in existing tabs

Yes, that.

**Comment by elstoc** [comment]
This will make tabs scroll, which we were trying to avoid when we did the rewrite originally. Not necessarily an issue but worth mentioning.

**Comment by elstoc** [comment]
> or we may just require to start dt with a command line option to activate this mode

IMO it would be better as a switch in preferences. Having to quit darktable, open it with the new mode, close and then open again sounds painful (almost as bad as editing darktablerc).

**Comment by AlicVB** [comment]
not to speak that in darktablerc file, we have lot of obsolete entries. They stay and that's good for us, devs, that continuously switch between version, but that make direct editing almost impossible except for newcomers...

now (and just to contribute to the subject) I would do the reverse of what @TurboGit propose : adding a special tag "don't expose", and in an "expert" special tab, just show *all* the other entries defined in darktableconfig.xml.in
That would also require a search box on top, and ideally some keywords (that will be a lot of work...)

The reasoning here is that users (including "advanced" users) will have very few use of the "expert" tab, so better not make it mandatory to activate some prefs that would need to be deactivated soon after (or kept activated with messy prefs tabs)
And we would *never* have to say "edit darktablerc"

**Comment by quovadit** [comment]
I love the idea of limiting the shown preferences, but I would go even further:
- default: only show ~ 20 options, lot of users have changed
- advanced: as current view (~ 100 options)
- expert: show all options from darktablerc (~ 1000 options)

Because there will be very few / lot of options per tab, we could change to an endless scrolling across all tabs (like VSCode), and include a search bar which filters all entries matching the query

**Comment by Nilvus** [comment]
> I love the idea of limiting the shown preferences, but I would go even further:
> 
>     * default: only show ~ 20 options, lot of users have changed
> 
>     * advanced: as current view (~ 100 options)
> 
>     * expert: show all options from darktablerc (~ 1000 options)

> Because there will be very few / lot of options per tab, we could change to an endless scrolling across all tabs (like VSCode), and include a search bar which filters all entries matching the query

Too much. 2 modes is enough. Simplicity is often better. And which options goes to which mode? Not so easy for some with 2 modes, harder for 3. Last question about your proposal is: how do we know the about 20 options lot of users have changed. Probably easy for some of those but not for all. Just an example, except when I test CSS (and not always), I try to change font size setting but on normal use (so not CSS developer one), I never touch it. But if we hide that option on advanced or expert mode, i'm quite sure some will not like that.

**Comment by phweyland** [comment]
A simple dummy/simple view makes sense to me (as long as I can find there the "write xmp" one ... :), which may mean that the user should be able to select the settings he wants (not) to see there as @AlicVB is suggesting if I understand properly).

I would not like to lose the well (yes!) organized settings we have today, even if I have to scroll sometimes.
I don't like the endless list because it's not a good way to learn which settings are available.

I agree also we should not have to quit dt to switch from one mode to the other.

**Comment by parafin** [comment]
What is exactly the issue with editing darktablerc? Is it that users can't find it? Then "advanced mode" can just open a simple edit box with contents of darktablerc. We already have something like that for custom CSS.

Anything else is IMHO the same as adding more options to the preferences. I don't see the need for a special "mode" for that, just put them at the end of the tab and optionally inside the collapsible section (collapsed by default) called something like "More" or "Advanced".

In any case I don't see how expert mode of preferences dialog can completely replace the darktablerc editing, there are a LOT of lines in there.

**Comment by elstoc** [comment]
> open a simple edit box with contents of darktablerc

this would be a list of variables and current values, since the actual contents of darktablerc are only updated on exit but I take your point

> I don't see the need for a special "mode" for that, just put them at the end of the tab and optionally inside the collapsible section (collapsed by default) called something like "More" or "Advanced".

I think this is fairly close what we're talking about but having a 'per tab' advanced section is an reasonable alternative, rather than a global advanced toggle that exposes advanced options on all tabs.

> I don't see how expert mode of preferences dialog can completely replace the darktablerc editing, there are a LOT of lines in there.

A lot of them are just storage of variables used by the UI, where the UI is already used to access/update them (e.g. window sizes, saving of previous slider values in lib modules) and manual updating is simply not appropriate. I think the suggestion was that we only include those that are defined in darktabconfig.xml.in, which is a much smaller subset.

There may still be a need to access darktablerc to fix very specific issues but ideally we should never need to _advise_ someone to do it (like in the user manual) except for the most cornerest of corner cases (and to fix issues).

**Comment by parafin** [comment]
> There may still be a need to access darktablerc to fix very specific issues but ideally we should never need to _advise_ someone to do it (like in the user manual) except for the most cornerest of corner cases (and to fix issues).

How many of those are there in user manual? Maybe just add them to the preferences dialog instead of polluting it with all of the settings?

I guess my point here is that I don't see a problem clearly defined that we're trying to fix with "expert" mode. This should be the first step, instead of coming up with solutions. I hope the goal here isn't to make darktable "cooler" (because other cool dudes are doing it), but to solve an actual issue. IMHO "expert" mode isn't solving much.

**Comment by elstoc** [comment]
> How many of those are there in user manual?

Mostly opencl ones, plus maybe a handful of others.

**Comment by AlicVB** [comment]
> What is exactly the issue with editing darktablerc? Is it that users can't find it?

- deprecated entries stay forever in darktablerc (that's an advantage, but also makes it impossible for users to read it)
- lot of entries are not "real" settings, but just some values stored in order to retrieve them on next start



> How many of those are there in user manual? Maybe just add them to the preferences dialog instead of polluting it with all of the settings?

I take your point, and maybe the first thing would be to list the settings that would be useful to expose. We can't rely directly on `darktabconfig.xml.in` like @elstoc proposal as this file also contains "not real" settings (mainly initial state of things for the first start)

**Comment by elstoc** [comment]
> We can't rely directly on darktabconfig.xml.in like @elstoc proposal

I was more suggesting that things that _aren't_ in this file probably don't need to be included. Obviously we can't include everything here.

**Comment by jenshannoschwalm** [comment]
Just to mention my personal view on this.

I think we should offer options in a non-technical way (if possible) whenever that's possible.

Some options are only there because maybe we could not agree on "what is best" or "what is correct". One example would be the database cleanup. There are several options, i would suggest to only offer "automatic cleanup -> yes or no" as the details might confuse and don't lead to a better solution.

All options/switches that are "nice to have" should be visible. (This would be for the new module show-up) Here again only "gui animation -> on/off"

An "expert mode" would only be good for settings that might be necessary to avoid a bug. (As we have it for "enable opencl", that is only there because there might be a driver/platform issue and we would need to disable)

Some sort of integrated "conf editor" does not seem to be a good idea for me. This would possibly lead to "bad edits" and we would have to check mods for being good. Having this to be done via using an external editor has the advantage that only user knowing "what and how to do" get in touch with such settings. So at least - if we offer an integrated editor - we would need a flag in xml.conf marking that as "editable"

**Comment by Nilvus** [comment]
Thanks @jenshannoschwalm for such precise comment. I find it one of the best compromise and way to go for that.

**Comment by AlicVB** [comment]
> Some options are only there because maybe we could not agree on "what is best" or "what is correct"

I would add the case "I need a special setup because I have special hardware/requirement/workflow/..."

Let's take the example of the cache : we have now a very simple setting. That's great.
But we can't either forget the ones who have small disks space / need lot of space for something else or the contrary : a dt dedicated machine, where dt can eat all free space...

tbh, I don't care to edit darktablerc manually, but imho it would be really dangerous to advise user to do so... esp. for such "not so exotic" usecases

**Comment by jenshannoschwalm** [comment]
> I would add the case "I need a special setup because I have special hardware/requirement/workflow/..."

Fully agreed in general. Yet for me the problem is - how can we safely advise users to adopt to their needs. Just remember the amounts of simply wrong suggestions on "how to tune memory". 

> but imho it would be really dangerous to advise user to do so... esp. for such "not so exotic" usecases

Absolutely. At least 99% of users should be fine with options offered via preferences. And those options should be easy to read and easy to understand. So - non-technical term preferred. For example this screenshot
![Bildschirmfoto von 2022-03-31 18-21-19](https://user-images.githubusercontent.com/50982232/161103627-e7ca1fc4-217b-4a31-83d1-0598b24091bb.png)

Can you imagine a user understanding this? I don't - so rtfm one could say. Instead we should try to understand: "Why do we have this option" or "what problem do we want to solve" and find some "term" describing a solution. (BTW i don't know anthing really good for this specific problem.)

Here is another example
![Bildschirmfoto von 2022-03-31 18-26-21](https://user-images.githubusercontent.com/50982232/161113207-a2819a9a-69af-4766-9203-071d85ee0628.png)

3 options look really good to me - but what about "fragmentation ratio"? What is that and why/how should i care about it? I don't know and would have to look into some sort of sqlite doc (at least if i know that dt uses it) For me this is something that should just go and should not even be exposed by a conf value.

**Comment by AlicVB** [comment]
> Can you imagine a user understanding this? I don't

me neither (and it's my text :)). This is the typical example of a pref that shouldn't be exposed by default.
But that should be available somewhere for advanced user that use "specific" thumb sizes.

imho we should reduce the number of exposed item by default, but I'm against going the way of removing them altogether (== hardcoding them)
Once say that, the question remains : how do we let users access to those "not expose by default but still useful in some cases" preferences ? (and iiuc, that's the goal of this discussion)

**Comment by TurboGit** [comment]
I have removed 4.0 milestone as too much controversial yet for settling down for next release.
