### ISSUE TITLE
Retouch gets distorted in export (preview looks fine) 3.9.0+873~g730ee22ff 

### ISSUE THREAD

**Issue by spyfish** [darktable-org/darktable#11447]
**Introduction**
Ive removed some buildings with retouch healing tool, and looks fine in preview:
![image](https://user-images.githubusercontent.com/5610400/161378990-6bc5351b-b942-4ca3-88cf-e3bb839e03a8.png)
![image](https://user-images.githubusercontent.com/5610400/161379002-7f9a653d-6a8f-4be3-9543-9f451caadc5d.png)
![image](https://user-images.githubusercontent.com/5610400/161379010-968e08fe-3e3c-4f5f-9590-1eaff990cfb8.png)

However the actual export looks like this: (tried tif and jpeg) 
![image](https://user-images.githubusercontent.com/5610400/161379070-c199cc26-2559-42a7-a221-44c4a1b93a38.png)

**Describe the bug/issue**

**To Reproduce**
Load dng file and XMP and observe

Or Load just dng file, apply the retouch, export and observe. 

**Expected behavior**
Export to look like preview 

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.9.0+873~g730ee22ff 
* OS                : Win 10 21H2
* Memory            : 32GB
* Graphics card     : RTX 2070

It is very easy to reproduce, so didnt include any debug files.

**Comment by spyfish** [comment]
I wasnt able to attach the files 
https://easyupload.io/jop77z

**Comment by spyfish** [comment]
I also tested with Todds fresh portable build 3.9.0+925~g911f71370, exactly same. 
https://discuss.pixls.us/t/portable-custom-windows-build-of-darktable-with-sigmoid-filmic-v6-and-new-laplacian-hlr/30179

**Comment by spyfish** [comment]
Also reproducible with Bills 798 build.

**Comment by spyfish** [comment]
And 3.8.1

**Comment by AlicVB** [comment]
I can reproduce too.
- with or without opencl
- even with a "as clean as possible" enabled module list (wb + retouch + unremovable modules)
- even with only the "big" drawing shape. even if the source of this shape doesn't overlap the image border

You'll note that you can also see this when zooming at 100%. No need to export...

So it seems to be due to something wrong / a limitation in heal tool algo when the image is not 100%...

**Comment by spyfish** [comment]
@AlicVB  Thanks for confirming :)

**Comment by ralfbrown** [comment]
The healing code has a limit of 1000 iterations.  Each iteration diffuses color/texture by one pixel, so if the area being healed is more than 1000 pixels high/wide the colors can't be fully adapted.  Darkroom mode uses a reduced-resolution image, so it doesn't hit that limit in this case, while the full-resolution export does.  Note that we can't just arbitrarily increase the limit (though with recent optimizations we could probably raise it to 1500 or 2000), since the healing process might not converge to sufficiently small per-iteration updates to terminate on its own even with substantially smaller areas.

Workaround would be to split the healed area into smaller pieces.

**Comment by spyfish** [comment]
Ok, yeah i guess that makes sense. And this was a 48MP image. Splitting up doesnt work quite well, but doing this as a final step on exported jpeg worked quite well. For prints i guess just downres 50% may be enough. 
![DJI_0248-DeNoiseAI-standard](https://user-images.githubusercontent.com/5610400/161387230-299adab3-f02a-41e0-8c8b-f34c180c4adf.jpg)

**Comment by gi-man** [comment]
Since you are just trying to remove those buildings, I think cloning would be faster and more effective than healing.

**Comment by ralfbrown** [comment]
> Since you are just trying to remove those buildings, I think cloning would be faster and more effective than healing.

Faster yes, but you also need to find a patch of water which precisely matches the color of the destination around the edges....

**Comment by gi-man** [comment]
Clone the large area and the heal the edges.
