### ISSUE TITLE
FR : Add camera's white balance parameter as a condition to auto-apply a preset

### ISSUE THREAD

**Issue by Jiyone** [darktable-org/darktable#11479]
I'm sometimes doing some shooting using the same camera with my studio flash (Elinchrome rx ONE).
I have calibrated that light source in Color Calibration using a color checker and made a preset. 
So for all those pictures, I have to load the preset by hand to apply the color corrections ...

I'm always shooting with "auto wb" set on my camera and I have noticed I have quite the same value of white balance on my pictures shot under the same condition of light.
It would be great if possible to have a range of the camera's white balance r/g/b coefficients as a parameter to auto-apply a preset.
I think this could be useful in other situation where some other color-specific module should load one particular preset depending on that parameter.

**Comment by aurelienpierre** [comment]
**Note to myself:**

1. check if it's possible to directly use color temperature as a metric of camera WB instead of RGB raw coeffs, for better UI,
2. for the former, check if user presets are initialized after or at the same time as defaults settings, such that we can get a reading of the input profile matrix at user presets init, from which we can compute Correlated Color Temperature (CCT) from RGB raw coeffs and input matrix,

**Anyway:**

right now, CCT is computed in WB module and color calibration modules assuming input matrix is either embedded matrix (for DNG and EXR) or Adobe standard matrix, because these are known from EXIF readings and therefore can be used before the pipeline is inited **to** init the pipeline. That's wrong if a custom input profile is later applied, possibly as a user preset used by default.

Problem is, we do a full sequential pipeline init for defaults. If user presets are applied sequentially later, we can't use custom presets to properly init defaults settings, including CCT if custom input profile is defined.

Solution might be to interleave defaults and user settings at init time.
