### ISSUE TITLE
ILCE-7SM3

### ISSUE THREAD

**Issue by frozenemitt** [darktable-org/darktable#11494]
Added APS-C crop (on/off) in both compressed and uncompressed ARW for Sony ILCE-7SM3 to raw.pixls.us

**Comment by Nilvus** [comment]
Could you precise what this add to already closed and fixed issues about that camera? See #/8632 and ##8733
@kmilos: maybe you could amend my comment with more precise infos here. We are on 3 issues about same camera.

**Comment by frozenemitt** [comment]
@Nilvus, I am not sure if these ARW samples are needed to provide any functionality to Darktable. I saw [this comment](https://github.com/darktable-org/darktable/issues/8632#issuecomment-840102430) from @kmilos in #8632, and assumed the sample set is still needed. There does not seem to be any uncompressed or APS-C crop samples in raw.pixls.us prior to my samples being submitted. Please close this issue, or use the sample set to improve compatibility with ILCE-7SM3, as you see fit.

**Comment by Nilvus** [comment]
@frozenemitt: thanks for precision. This is so probably needed. I let @kmilos or @LebedevRI check that.

**Comment by kmilos** [comment]
Thanks for sharing the samples - although uncompressed should already work, it's good to have the complete set.

I know nothing about Sony's APS-C or aspect ratio modes, and whether the ARW files in those modes are any different from the FF ones (like it is the case for some Panasonics for example). We don't seem to do anything special for those for any of the Sony cameras so far, so that might, or might not be a separate issue (@LebedevRI does indeed request those samples at raw.pixls.us).

**Comment by kmilos** [comment]
If it's going by the older ILCE-7S, it looks like the APS-C ARW indeed contains 2.25x fewer pixels that the FF. That's the only cropped Sony FF sample we seem to have at raw.pixls.us, so thanks.

**Comment by frozenemitt** [comment]
@kmilos, @Nilvus, yes, uncompressed ARW do work with Darktable 3.8.1. Hopefully the full set is useful someday.
