### ISSUE TITLE
Bug or design how dt_iop_request_focus() is called

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#11535]
**Introduction**
While working on a module requiring some cleanup when it "loses focus" i implemented a gui_focus() callback.

This works fine if i collapse the header or open another module via click on the header bar, changing to another image in darkroom ...

**Describe the bug/issue**
BUT the callback is not taken via `dt_iop_request_focus()` (it doesn't reach that function at all) if i just (de-)activate another module via a click on the on/off button.

I would **not** have expected that but:
Is this a bug or a design decision?
(I don't know enough about dt GUI, bauhaus .. to know myself. 

Tested on current master

**To Reproduce**
I added a fprintf line into the start of `dt_iop_request_focus()`

**Comment by elstoc** [comment]
I'm pretty sure this is by design and I don't always want to change focus when enabling a module, though I pretty much always do if I'm expanding. You can Ctrl+click on the module's on/off button to give it focus. 

IMO focus should follow expansion (you expand a module so that you can interact with it) so the current functionality is correct. If we changed this functionality, the problem comes when you have a module expanded but then enable/disable another module. How do you get focus back to the expanded one? You can Ctrl+click but we shouldn't have to do that unless absolutely necessary as it's fairly hidden functionality.

**Comment by jenshannoschwalm** [comment]
Ok, i think i understood what you say and why that is good the way it is. And - thanks for the link.
