### ISSUE TITLE
filters for collections: NOT RAW filename filter removes raws

### ISSUE THREAD

**Issue by xfh** [darktable-org/darktable#11544]
I am using darktable master, 3.9.0+1205~g0d20418b5-dirty on Gentoo.

The filename extension filter `NOT RAW` doesn't work as expected.

Activating the  filter as bellow shows several RAW images in lighttable. In my case from different cameras (CR2, CR3 and NEF extensions).
![image](https://user-images.githubusercontent.com/9366771/163710001-9d4ad397-e03c-424e-8c08-07030a48a437.png)

If I open a file in darkroom and directly go back to lighttable, the image is no longer shown. Tthe filter does then work as expected for that particular image.

I am guessing only images that were not yet edited/opened in darkroom are affected.

Interestingly, the filter works correctly after a history refresh and also for newly imported images. Might be a migration issue?

**Comment by Nilvus** [comment]
Thanks for testing that. This huge add has surely some issues. I ping @AlicVB

**Comment by AlicVB** [comment]
I can reproduce, even with freshly imported images...
it seems that dt doesn't update the "image type" flags until at least the pipe as been run once...
@TurboGit @phweyland : can you confirm ?

if there's not other way, we may try to sort the files directly with there extension, with all the drawback (esp. how to be sure we have an up to date extension list)

**Comment by TurboGit** [comment]
> @TurboGit @phweyland : can you confirm ?

No the flag DT_IMAGE_RAW is set in `imageio.c` (so at import time) depending on the actual image loader used.

**Comment by AlicVB** [comment]
Then there's something strange... I've just done some tests : 
- empty db
- a folder with nef, cr2, arw and jpeg without any xmp
- import the image, verify that we see them in lighttable
- close db
- open library.db in an sqlite browser... all the flags are set to 1024 (`DT_IMAGE_NO_LEGACY_PRESETS`) no RAW/LDR flags :(

Maybe the reason why it's set on side is that you don't use embedded jpeg ?

That said, I'll look at the files you mention, because imho current situation is not good and may raise other issues...

**Comment by TurboGit** [comment]
> Maybe the reason why it's set on side is that you don't use embedded jpeg ?

That's the case and this is a highly probable explanation for the different behaviors we are experiencing.

**Comment by AlicVB** [comment]
right. So the actual situation is that we don't set this flags on import so for all the files not opened in darkroom (or other pipe compute like creating non-embedded thumbs), we have no way to know if they are RAW or not.
I have done some quick tests, and the problem is that even a minimal pass in rawspeed would slow down a lot the import process, so that's not an option...

So what I would propose is to use a list of extension for that. The question then is at which level to we want to do that : 
1. just inside the filename filter
2. globally inside dt, as a "first pass" that would be eventually corrected once the image is loaded for real.

2 would be better imho, bu that require way more work : 
- add some routines to be called during the import process
- upgrade the db to set the flags if it has not been set already (this may take some time for large db)

What do you think ?

**Comment by xfh** [comment]
It could also be some continuously running background job: 
1. find up to N images without the flag
2. analyze image
3. write flags to db
4. wait a tiny bit
5. restart at 1

Advantage would be that it doesn't slow down the import process (could even be disabled during import) and rawspeed could still be used as a more robust check if it's a RAW image or not.
The state in the database would eventually be consistent.

That said, file extensions would probably be much simpler to implement and work most of the time too...

**Comment by AlicVB** [comment]
> That said, file extensions would probably be much simpler to implement and work most of the time too...

yes, we have to remember that this is not a "critical" part here... and anyway the flags will be overwritten when the image is open in darkroom
