### ISSUE TITLE
FR: Reduce magenta in highlights

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#11587]
**Is your feature request related to a problem? 
Magenta in highlights

**Describe the solution you'd like**
A way to get rid of magenta highlights, ideally an easy way. I have a few ideas in mind:
- in filmic module, there is already a highlight reconstruction mask. It would be nice to have a slider to adjust the magenta out.
- Or make the same mask available to use in a second instance of color calibration module
- Or any other way not to have magenta highlights

**Alternatives**
Ive tried the highlight module with the new laplacian at 12 iterations and doing masks to find the magenta that yield somewhat ok results but it takes a long time. 

**Additional context**
I try to read the filmic reconstruction code and it seems to try to correct the rgb. I was looking to see if the was a power(intensity) factor that I could try to use, but I could not find one.

**Comment by aurelienpierre** [comment]
Thanks for raising this, we never thought about this.

Dealing with magenta highlights is an easy task because your computer knows what "white" or "magenta" is, even before we apply the input color profile and the white balance.

Also, we can reliably identify magenta for all cameras because, again, since we are before input profile in the pipeline, it's not at all random and based on vendor's heuristics. Camera manufacturer tag the faulty pixels with a "magenta" flag. 

Regarding what color to in-paint in the clipped magenta parts, the wizards in the computer will tell us what it should be. That will make the reconstruction fast too.

**Comment by gi-man** [comment]
@aurelienpierre You are a very smart fellow engineer. Ive read your technical reports and Ive seen your approach for deep technical knowledge around color management. I think the idea of using the laplacian is a great approach. But in my feature request, I'm not asking for black magic or the computer to guess for me. I'm just asking for the ability to let the user provide a final guide, a final tweak to the colors. The reconstruction process is an extrapolation and I think it should have a human being able to make a final adjustment. I dont think I'm asking for a challenging request. If there is already a way to accomplish this, I'm all ears. Thanks for your time.

**Comment by aurelienpierre** [comment]
What you are asking is dealing with color before colors are even defined, because there is no color profile nor white balance yet in this place of the pipeline. 

We already have a clipping mask mechanism in place. What more do you want users to do ? Manually pick up a solid color to in-paint ? There is already a module for that : https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/color-reconstruction/. 

It doesn't work remotely as good as you think it will, because it doesn't explicitly respect gradients.
