### ISSUE TITLE
Issues running tools/show_icons_in_paint_c.pl

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11631]
I am trying to find out if I can run some generic function to get images of all the icons in darktable for inclusion in dtdocs. This will probably require some modification of `show_icons_in_paint_c.pl` but at the moment it does not run.

I've managed to force it to run by changing line 147 to 
```
system("gcc `pkg-config --cflags --libs gtk+-3.0 json-glib-1.0 librsvg-2.0 lcms2` -lm -std=gnu99 -I$srcdir -o $tempdir/test $tempdir/test.c $srcdir/dtgtk/paint.c");
```
(added references to `lcms2` and `librsvg`, changed from `std=c99` to `std=gnu99`) but because `src/dtgtk/paint.c` now references `darktable.bauhaus->colorlabels` it will no longer run standalone.

Looks like this was broken by https://github.com/darktable-org/darktable/pull/11482

**Comment by elstoc** [comment]
Ping @AlicVB

**Comment by elstoc** [comment]
Longer term I'd like to get this to output separate png files for each icon in a subdirectory - if anyone knows how to do this it would be greatly appreciated.

**Comment by AlicVB** [comment]
@elstoc : yes, it's certainly me !
I don't really know how to fix the issue...
the problem comes from the fact that colorlabels colors are defined in css... and the colors from css are read inside bauhaus routines (for an historical reason certainly) but anyway the fact that they are defined in css will be difficult to handle without adding quite a lot of code...
if you want a temporary fix, to hardcode directly the values inside paint.c, I can do it and give you the diff, thought...

**Comment by elstoc** [comment]
I did the hardcoding myself and got some output but I'd like to not have to do it every time I want to produce the icons

**Comment by AlicVB** [comment]
hmm... so it's ok for your need with hardcoded value ?
if it's the case, I will try to do something...

**Comment by elstoc** [comment]
I think generally this script is just so that you can see all the icons if you need to choose or modify one for some purpose. At the moment it doesn't suit my needs because it just produces one massive image but it can probably be tweaked to instead produce a set of separate icon png files, that I can use in dtdocs. Either way, if I needed to show all the coloured icons with the correct colour, I'd probably do a screenshot directly from darktable.
