### ISSUE TITLE
deleting tag `darktable|problem|history-compress' on each startup

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#11637]
**Describe the bug/issue**

On each startup, I have this message in Terminal. A minor error, I don't see any other related issue.

**To Reproduce**
1. Launch darktable from Terminal
2. After darktable is launched, see on Terminal this message : 

`deleting tag darktable|problem|history-compress`

**Expected behavior**
No message on each startup (once could probably be ok but not each time)

**Platform**

* darktable version : actual master (appears since at least march. I see it by working on my CSS PR #11559 (I launched from Terminal each time when working on darktable code ; tested tonight with master and same error confirmed)
* OS                : Debian Sid

**Comment by Nilvus** [comment]
Sorry for this noise, I've just needed to reset collections module and I no more have this error now. Try 2 times to relaunch darktable. It's not the first time I reset collections modules though but first time I reset since I have seen that message AND have tags filter selected in collections module filters. I let this issue open few days in case this show something to fix (or no more).

**Comment by jenshannoschwalm** [comment]
From my memories this tag was introduced for dt 3.4 while working on history compression issues. Will fix it.

**Comment by jenshannoschwalm** [comment]
Also pinging @TurboGit here, i just checked - this tag was in fact introduced by me while we were working on the infamous ioporder 3.4 problems. We had a lot of history compression problems related to that and thus wanted a way to keep-a-note on what images had a problem while compressing history.

What solution whould you prefer?
1. As this problem is gone since long, lets get rid of this tag?
2. Just make sure the message is not shown by prohibitting the deletion of the tag if no image has it.
