### ISSUE TITLE
color picker in "color calibration" is broken 

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11649]
**Describe the bug/issue**

When using the color picker to set the WB the setting is wrong and seems completely off.

Is that only me?

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'darkroom'
2. Go to 'color calibration' module
3. Click on 'color picker'
4. Select a neutral area in the picture
5. See error, nothing see correct... color completely off and I have `(invalid)` of the left of the color patch next to the color picker.

Tested on many images.

**Comment by kofa73** [comment]
Do you, by chance, have a non-grey value as the _target_ of _spot color mapping_, left over from a previous application of the module? I had the same issue a few days before. See #11601.

**Comment by TurboGit** [comment]
@kofa73 : Thanks, that was my issue indeed. I had clicked the reset button and I would have expected the `color mapping` section to be reset too :(

**Comment by elstoc** [comment]
I'll just keep saying this... this functionality needs a separate color picker in the collapsible color mapping section.

**Comment by aurelienpierre** [comment]
> I'll just keep saying this... this functionality needs a separate color picker in the collapsible color mapping section.

No.

**Comment by elstoc** [comment]
> No. That just makes up for more steps when processing batches.

I'm not sure what you think I'm suggesting here. I'm suggesting a separate color picker in the collapsible section that acts on the chosen colour, while the existing color picker just does "grey". It's _not_ an extra step since, once you've expanded it, the collapsible section stays expanded -- it's just that the process requires you to click a different button. But a color picker that uses hidden settings is just odd, especially where the picked color is close to grey. I know your response in the past has been "use your eyes to know it's wrong", but as we've discussed recently, we should also consider the colour blind and people who just aren't that good at judging colour. I don't think this is an unreasonable suggestion.

**Comment by TurboGit** [comment]
A thinko, closing.

**Comment by mediatechnologic** [comment]
I started a discussion on pixls at ["srgb-calculation-of-exposure-module-and-color-picker-wrong"](https://discuss.pixls.us/t/srgb-calculation-of-exposure-module-and-color-picker-wrong/34204) with a couple of screenshots.
The solution to change module order to v3.0 JPEG does only solve to correct exposure influence. But the color picker itself does calculate min, max an mean values wrong. In addtion there is a strange overshoot when crossing dark/bright borders.
