### ISSUE TITLE
Ctrl+click to focus parametric mask sliders

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11692]
~~Add the ability to Ctrl+click on a widget (slider, combobox) to give it focus. This mirrors the Ctrl+click functionality on the module (via the module on/off button) and reinstates the functionality removed by #11660.~~

For the input/output sliders in parametric masks, Ctrl+clicking on the individual sliders should probably focus them too. This is currently done with right-click but I guess ideally right-click should bring up a bauhaus edit popup for consistency.

**Comment by dterrahe** [comment]
This now works for bauhaus sliders (since ctrl+click+drag will move it at .1* speed without repositioning on the first click). For combos this is imho not that much of an issue since clicking on them to open doesn't mess with the currently selected item.
Could you please retest and confirm if you agree?

That would reduce this issue to the parmask in/out sliders. I agree that ctrl-click should select. Maybe also clicking on one of the four labels should select corresponding slider. These don't seem like complicated changes; would you like to try your hand?

People with strong muscle memory might complain about changing right-click and personally I don't care enough about a popup here that I would put the effort into cloning the bauhaus one. From experience there, it could get finicky to say the least to make the popup-markers line up correctly with the non-popup ones so that there's no jumping.

**Comment by elstoc** [comment]
> This now works for bauhaus sliders 

Agreed

> Maybe also clicking on one of the four labels should select corresponding slider

Perhaps. I have to "engage brain" to recall that (and how) the numbers (labels) correspond to the sliders.

**Comment by dterrahe** [comment]
Since this now refers to input/output sliders only (I assume the dtdocs update is being tracked there) it could be beneficial to change the issue name? Many thanks!
