### ISSUE TITLE
Refrain from using convoluted shortcuts combinations

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#11748]
More and more default behaviours, in GUI, now rely on combinations of key modifiers (Ctrl, Shift) and clicks/scroll. This is great to avoid more buttons in UI, but unfortunately makes the use of Wacom tablets (and other touch screens interfaces) even worse than before (and it was already not great).

An image editor is not Vim, and we should work to make darktable more usable without a keyboard, not ground it more and more into convoluted key strokes combinations. 

Keyboard shortcuts should be optional at all time, not grounded into the core design of GUI interactions. There should always be a GUI alternative for people having only access to pointing devices. Ultimately, editing a picture should be doable only with a tablet and a pen.

Obvious offender: collection filters, where you need Ctrl + Click to pin/unpin.

**Comment by elstoc** [comment]
Core features should not be hidden behind modifiers, I agree. But niche stuff that most people won't use is fine IMO.

**Comment by AlicVB** [comment]
I perfectly agree with you... but there's a way more problematic area on that point imho : drawn masks ! (that remember me that I'll have to rework my branch that put the base of a fix for that...)

For the pin/unpin, I agree that it's not the best (and I'm open to other solutions), but that's way less critical imho, as I see that as a configuration of the interface, done 1 time and not changed so frequently...

**Comment by dterrahe** [comment]
> Ultimately, editing a picture should be doable only with a tablet and a pen.

I know that you know and this does in no way invalidate your point, but it may be useful for others to mention that since https://github.com/darktable-org/darktable/pull/11357 you can assign extra buttons on a tablet to the ctrl (or shift) key.

The approach taken on purely touch based devices (android and ios phones) is to have long-press instead of right-click or ctrl+click for second level features. This is of course not trivial to implement in a consistent way across the interface; it would need many adjustments/fixes even if the mapping long->ctrl was done centrally (in `dt_shortcut_dispatcher`).
