### ISSUE TITLE
guide overlay settings box contrast slider incorrect

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11756]
On the "darktable-elegant-grey" theme, within the popup box that appears when you right-click the guide overlay button, the contrast slider is different to the rest of the box. Also an issue (though less noticeable) on the default darktable theme.

darktable-elegant-grey
![Screenshot_2022-05-07_22-41-48](https://user-images.githubusercontent.com/9555491/167272603-dbe1008b-a625-4546-86b2-9607a93dc961.png)

darktable
![Screenshot_2022-05-07_22-43-29](https://user-images.githubusercontent.com/9555491/167272610-07f5b89a-c007-4404-8a1d-a1b2d6a7b31a.png)

**Comment by Nilvus** [comment]
Oups, will check. Thanks

**Comment by Nilvus** [comment]
@elstoc: fix is done. This issue comes when I fix (again) border on arrow in sliders you notice previously. To explain (and to let that a reminder for later), border around arrow on sliders are done by applying background color on all bauhaus slider. Probably something to rework on bauhaus Gtk code. Would be better to set transparent background on those AND apply a border on arrows. But work I don't know how to do that. We plan to work again on those bauhaus for darktable 4.2 with @AlicVB. Something to check/test to avoid such issues in the future.
