### ISSUE TITLE
The new Collections Filters module

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#11859]
I don't know if you'd call this a bug report or a feature request, or what.
I have concerns over the Collection Filters module, and the removal of the Recently Used Collections module.
I personally used the RUC list A LOT! I quite often search for an image, then search for some collection to compare notes, and then want to go back to the first image. This to-ing and fro-ing was very quick and simple with the RUC list.
Maybe I'm an outlier when it comes to usage, I don't know.
But I'd prefer to keep the module, over ditching it.

The Collection Filters module though, breaks your saved Collections, and to me this is a major failing.
If I go into the Collection Filters module and define a "date taken" range (my most commonly-used method of searching), then all of my other saved Collections are rendered useless until I clear the search parameters in the Collection Filters module.
If the CF module is here to stay, then this needs to be addressed pronto.
Unless I'm doing something wrong? If so, please advise! :)
Cheers.

Linux Mint 20.3
NVidia RTX3070

**Comment by ptilopteri** [comment]
I too, preferred the previous "collection" filter

**Comment by pehar1** [comment]
> But I'd prefer to keep the module, over ditching it.

The list is still available : _collections module -> history_

**Comment by brucewilliamsphotography** [comment]
> > But I'd prefer to keep the module, over ditching it.
> 
> The list is still available : _collections module -> history_

Gah. Sorry. Yes, I overlooked that.

**Comment by brucewilliamsphotography** [comment]
But the issue of this module breaking saved collections still stands. Or have I missed something there?

**Comment by pehar1** [comment]
> breaking saved collections still stands

I can not reproduce. With this settings

![collection-filter](https://user-images.githubusercontent.com/104291381/169641427-2957eb71-35d1-4be5-b941-15a0417418b4.png)

the saved collection "Berliner Mauerweg" is limited to the date range (capture time) selected. No images from other collections shown. The small bar chart shown above the dates is limited to dates occuring in the saved collection.

**Comment by brucewilliamsphotography** [comment]
What I'm saying is that if I go to the collection filters module and enter a date range to find some image/s, and I THEN want to recall a saved collection (which is based on a different date range), I have to clear the date range from the collection filters module beforehand, otherwise my saved collection says there are no images to display.

**Comment by Nilvus** [comment]
@AlicVB?

**Comment by pehar1** [comment]
Sorry, my bad, I misunderstood.

**Comment by AlicVB** [comment]
Yes, collections and collections filters are different modules... and for this one, it's not my fault, as it was working the same before ;)
If you works with 3.8 (or with 3.9 before the merge of the filters PR) : 
- select a filmroll
- add a new "rating" rule (not with the topbar, but a collection rating rule)
- reset the module and select again a filmroll
- use the topbar to filter with a rating
- use the recent collection module to revert to the "filmroll+rating" collection
- see that the topbar rating is not changed

Now I had proposed at some point to enhance the recent collection module in order to take account (possibly optionnaly) the collections and the filters. Sadly this proposal as not receive good comments...

Note also that if you prefer to work with the "legacy" recent collection module more than with the history button, there's an option in the collection module to get that.

**Comment by brucewilliamsphotography** [comment]
> Yes, collections and collections filters are different modules... and for this one, it's not my fault, as it was working the same before

Not sure what you mean by this? Before when? Before the CF module, we had the Recently Used Collections module, and that did not interfere with saved collections.
Almost all of my image searching is based on date ranges, and as I mentioned previously, having a date range defined in the CF module interferes with saved collections (in the Collections module) which are also based on date ranges.
If there's some part of this that I'm overlooking, please let me know.
I guess with the History button added to the Collections module, I can survive without the RUC module.
Cheers.

**Comment by AlicVB** [comment]
Sorry for being unclear...
What I mean is that collection and filters are different things that works like that : 
`SELECT images FROM database WHERE collection_rule_1 AND collection_rule_2 .... AND collection_filter_1 AND collection_filter_2 ...`

recent collection module (or its equivalent with the history button) only affect the `collection_rule_` part, and don't touch the `collection_filter_` (there's a specific history for filters in the module)

previously (in 3.8.1) you only have the "rating" possibility as collection_filter rule, that's why I've taken this example.

So, if you add a "date" rule in collection filter and another date rule in "collection" itself, that will interfere, for sure (same with all the other rules, including rating)

I hope it's more clear (or maybe I've not understood your concern at all)
