### ISSUE TITLE
Masks: How the manual says they work, and how they ACTUALLY work.

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#11860]
Hi Devs,
I'm sitting down to work on the next video in my new series on Masks, and I'm struggling with the outcome of building a Drawn and Parametric mask.
And I've just come to the realisation that the reason I'm struggling is because there is ZERO correlation between what the manual says, and how the masks actually work! Unless I'm completely misunderstanding the manual, which is not outside the realms of possibility!
To describe this behaviour would require me to write something rivalling Tolstoy's great masterpiece, so I've recorded a video (which is not being made public... this is the only place you'll find the link) which describes what I'm seeing.
Here's the link:
https://youtu.be/k4cp8p2KOj0
If this is just misunderstanding on my part, please set me straight! :)

**Comment by Nilvus** [comment]
I'm not sure to understand the issue but maybe it's the manual that is the issue. If it's related to doc, issues should be posted on dtdocs repository (not here so): https://github.com/darktable-org/dtdocs

**Comment by AxelG-DE** [comment]
What I see on the vid, masks behaviour is like always and forever. Didn't read the manual with my own eyes (using phone atm) but provided it is like Bruce said, a rework seems to be necessary. I guess @elstoc or @paperdigits could pick up

**Comment by brucewilliamsphotography** [comment]
Martin (not sure of your username on this board), I just responded re: your assertion that I had positive polarity on Cz and Hz. That actually is not correct. If you watch closely when I switched to Inclusive mode, you can see that the polarity changes to negative.

Nilvus, that's the thing. I am not sure if the issue is with the manual, the app, or the level of my understanding! :)

**Comment by paperdigits** [comment]
Instead of saying "the manual people will figure it out" can you please at least say what you think is wrong in the manual? Be as detailed as possible. Thanks!

**Comment by AxelG-DE** [comment]
@paperdigits in Bruce's vid you can see the discrepancies in a very detailed way. Put that in written Bruce would have actually copy-edited the doc :-P

**Comment by todd-prior** [comment]
I have inquired about this before. I will dig up the post on pixls and I believe I have comment here as well going back....I asked numberous times given the math that determines if pixels are masked and why the drawn mask is negative when it should be +...The best I can recall is I got that well it was always this way.......I will dig up the post...

**Comment by todd-prior** [comment]
@brucewilliamsphotography   Here is one of the times that I brought it up.....I also have a document that I worked up one time....for all combinations.....

https://github.com/darktable-org/darktable/issues/8172


Some musing I wrote over the years...one was an issue when there was a change to automatically change the polarity when the mode was switched between inclusive and exclusive...This was fixed...but for me this issue about the drawn mask having the "wrong" polarity didn't make sense..
[Combined Mask Breakdown.docx](https://github.com/darktable-org/darktable/files/8748260/Combined.Mask.Breakdown.docx)
[Combined Masks Updated.docx](https://github.com/darktable-org/darktable/files/8748261/Combined.Masks.Updated.docx)
[Inclusive Mask Bug Feb 2021.docx](https://github.com/darktable-org/darktable/files/8748262/Inclusive.Mask.Bug.Feb.2021.docx)

**Comment by todd-prior** [comment]
@brucewilliamsphotography  If you look at your mask around 8 min...your parametric is now neg (from selecting inclusive) ...so now selecting things not blue and your drawn mask is pos (should be neg) so selecting everything outside the circle... Inclusive is masked anywhere either mask is 1 so there is no mask only where both are zero...so that is parts that are blue and inside the circle.... if that makes sense...so again the only issue is that the drawn mask always shows as a + polarity when it has a value of 1 which makes no sense to me and why it clashes with the manual becasue the manual assumes correctly how it should behave IMO anyway....

Another thing i notice that you have to be careful of ...lets say you have 2 channels altered in your parametric mask under default conditions...if you select inclusive any non used channels change polarity to negative but your channels eg maybe hue and chroma stay positive...so if you go to add another channel to the parametric mask you have to be sure to note the polarity to be sure it is doing what you think.....it can certainly get tricky....

![image](https://user-images.githubusercontent.com/44409419/169667985-85c42f0a-8c4d-4483-9ba1-495833bc70a7.png)

**Comment by brucewilliamsphotography** [comment]
Todd, I was hoping to reach you via FB messenger, but I see you've disabled it.
Would you be willing to hop on a private video chat at some point? Because I am really struggling with this, and it's doing my head in! :)

**Comment by todd-prior** [comment]
Sure Bruce I have access to zoom and teams and so we could arrange a time if you think I could help...In a moment I decided to dump FB but I think I can still reactivate it


Get 
Outlook for Android

**Comment by brucewilliamsphotography** [comment]
No, don't do anything THAT radical! :)
Flick me an e-mail: studio@brucewilliamsphotography.com

**Comment by todd-prior** [comment]
Will do...I may have another reason I need to fire it back up at least in the short term anyway


Get 
Outlook for Android

**Comment by brucewilliamsphotography** [comment]
Ah crap.
user name is studio
domain is brucewilliamsphotography
and it's a .com
Sheesh.

**Comment by todd-prior** [comment]
> What I see on the vid, masks behaviour is like always and forever. Didn't read the manual with my own eyes (using phone atm) but provided it is like Bruce said, a rework seems to be necessary. I guess @elstoc or @paperdigits could pick up

In my opinion the documentation is correct and the error exists in the software currently. Specifically with drawn masks. Currently they are initially activated with negative polarity. I believe this is done as this would select all pixels when the mask is first used activated and there are no drawn elements yet added. At least this is what it seems.  Otherwise the code needs to be modified so that the initial ROI of a drawn mask is the whole image and that  drawn masks are added with a positive polarity and update the location of that ROI. This would be correct. 

Currently it seems that the drawn masks are applied with the polarity set to negative... Now lets say you add a circle. The polarity stays negative yet you clearly have a masked circle and now the rest of the image is unmasked. If you toggle the polarity now to positive the circle is now unmasked and the rest of the image is masked.... ie with positive polarity your drawn mask is not masked. To me this is misleading and comes perhaps from the initial ROI needing to be related to the presence of drawn elements that are not there yet....hence until a drawn element is added it should be the whole image. 

This gets carried through when combining parametric and drawn masks and as such leads to this inverted polarity that is at odds with the manual that to my way of thinking describes how it should be ie that the exclusive mask should be + for both elements and the inclusive one should start with drawn and parametric elements both set to negative polarity....

This may be a lot of work to fix but at some point it would useful and more accurately depict the constructed mask...

https://darktable-org.github.io/dtdocs/en/darkroom/masking-and-blending/masks/drawn-and-parametric/#typical-use-cases
