### ISSUE TITLE
Crash when filmic white relative exosure is set to 0 (zero)

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#11937]
dt crashes when setting white relative exposure to 0 (as in zero).

```
/tmp/portage/x11-libs/cairo-1.16.0-r5/work/cairo-1.16.0/src/cairo-arc.c:189: _cairo_arc_in_direction: Assertion `angle_max >= angle_min' failed.
Abgebrochen
```
Both master and 3.8.1 (gentoo's repo)

Got confirmed on IRC by two users.

Sorry for dirty short, I am on the way to leave...

**Comment by pehar1** [comment]
Confirmed with 3.9.0-1647-g2dfa2224d on Ubuntu 20.04.
Also immediate crash if any negative value is entered.

**Comment by Nilvus** [comment]
@aurelienpierre or @flannelhead: could you take a look on that issue?

**Comment by flannelhead** [comment]
The crash is due to a failed assertion:
```
darktable: ../cairo/src/cairo-arc.c:191: _cairo_arc_in_direction: Assertion `angle_max >= angle_min' failed.
```

GDB shows it comes from [this line](https://github.com/darktable-org/darktable/blob/ff519c5b057082f423189f3538fbdea69b55dd60/src/iop/filmicrgb.c#L3660). I'm not 100 % sure, but at least it seems on [this line](https://github.com/darktable-org/darktable/blob/master/src/iop/filmicrgb.c#L2805) the calculation blows up due to zero in denominator `white_log - grey_log`. This probably results in strange values when trying to draw the half-circles on the curve plot.

IMO it makes little sense to set `white = 0 EV` because that means just `white = grey`. Black point has a hard limit at `-0.1 EV`, should white point have a hard limit at `0.1 EV`? Currently it is `0 EV`. What does @aurelienpierre think?

**Comment by AlicVB** [comment]
or, if we want to keep the possibility to set white to 0, we can also just prevent the crash by changing line 3620 by `if(contrast_clamped && g->spline.x[3] != g->spline.x[1])` (as it's the culprit for this specific issue)
but considering this setting doesn't really make sense, I fear that we may have issue in other parts of the code anyway...

**Comment by aurelienpierre** [comment]
I tried replacing the only call to cairo_arc in filmic by cairo_rectangle and it still output the same error, so my bet is on bauhaus slider.

**Comment by aurelienpierre** [comment]
> Black point has a hard limit at -0.1 EV, should white point have a hard limit at 0.1 EV?

Yes.

**Comment by jenshannoschwalm** [comment]
I think this is not so bad. (Whatever sense it makes to set a value of 0 here)

The compiler options for this module allow -nan to be generated and exactly this is what happens for the angles when calling cairo_arc, checking both values before clling arc like `angle = fmaxf(0.0f, angle);` works fine.

**Comment by AxelG-DE** [comment]
Several times I read here, "makes **no sense to set value of 0** or lower"

Let me explain, **how it happened**:
- one of my pics, the automatic (eye dropper) set the value to something very low.
- I wanted to attenuate it
- accidentaly scrolled in the wrong direction
- BOOM
(later I just started digging)

**Comment by AlicVB** [comment]
@AxelG-DE : the question here is how to fix this "BOOM" :)
- either by not allowing to set 0 as a value
- either by fixing the issue in the drawing code itself

but in any cases, dt shouldn't crash, whatever the settings, valid or not ;)

**Comment by jenshannoschwalm** [comment]
I would opt for nan correction but it's aurelians baby so just commented.

**Comment by flannelhead** [comment]
I believe the filmic curve itself blows up (the line I linked above where division by zero occurs and the NaN propagates from there. I’ll verify that a bit later today). Hence I think white = 0 can’t be allowed because the filmic curve itself isn’t defined at that point.

@AxelG-DE sorry for bad phrashing earlier, I only meant it doesn’t seem to make sense in terms of the mathematical model. I can see how the situation occurs during normal usage.

**Comment by jenshannoschwalm** [comment]
Maybe the algo requires a fix (or it's the proper one)

But, Cairo never likes nan values for anything.
