### ISSUE TITLE
[FR] Force only GPU in some modules if OpenCL is available

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#11955]
**Is your feature request related to a problem? 
I recently took multiple images during a sunset. I used the highlight recovery GL with nice results. When I'm editing, at most the image takes 2sec for [full] in GPU. This is fine by me. 

But, I noticed when I switch to Lightview, culling/Fullscreen, darktable becomes very slow trying to process the [thumbnails]. Upon review, the CPU is 100%, while there is still plenty of memory (no tile). I used the -d perf to further evaluate and I noticed that some of the thumbnail processing is going into CPU. The ones in CPU path take 45 to 50sec just in the highlight recovery module vs 1s in GPU. The impact of CPU path is there also in the D&S module, but not at the same magnitude (~5sec vs 0.5s).

**Describe the solution you'd like**
I would like to be able to force those two modules to use the GPU path in all cases and maybe other modules in the future. This should be a user selectable option. 

**Alternatives**
I switched to the Very Fast GPU and it avoids the CPU path, but I dont think it is ideal to then never use the CPU for the other modules. 

Thoughts?

**Comment by MStraeten** [comment]
instead of switching to "Very fast GPU" better use default mode with custom `opencl_device_priority=1,0,*/!1,0,*/1,0,*/1,0,*/*` settings.
you can set a default priority - i used it to prioritize the dedicated GPU (1) over the on CPU GPU (0) except for preview (the default setting prioritizes the first GPU but thats the slower one in my config). So whenever possible (and  waiting for jobs) the fastest GPU is used and fallback to the slower GPU or CPU is just done if the fastest GPU is already in use.
depending on your systems configuration you need to try to find the optimum configuration.
