### ISSUE TITLE
Selecting items in lists (treeviews) stops shortcuts working

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11964]
If you select a list item in a module (for example, selecting an item in the collections module, choosing a mask in the mask manager module), darktable is no longer responsive to keyboard shortcuts until you focus another module or click the centre image. If a key combination is not handled by the list it should probably be passed to the shortcut system for processing.

Not sure if this will have adverse consequences though.

darktable 3.9.0+1673~g30ffb3b5d on ArchLinux

**Comment by dterrahe** [comment]
I'm afraid I cannot completely reproduce with 3.9.0+1622. What _does_ happen is that alphanumeric characters trigger an incremental search. So they _are_ handled by the list and therefore override any shortcuts. But for example F11 continues to work as a shortcut for fullscreen.

It would be nice if TAB takes the focus away from the list (like it does for entries). Rather, since it isn't handled by the list, it functions as a shortcut as normal (in my setup) and so immediately removes the sidepanels. Entries are special cased in `dt_shortcut_dispatcher`. Maybe changing
https://github.com/darktable-org/darktable/blob/b73707ef7782f4ad7aa36dca77b4c713228bac69/src/gui/accelerators.c#L3673
to
`if((GTK_IS_ENTRY(focused_widget) || GTK_IS_TREE_VIEW(focused_widget)) &&`
would work and have the desired effect. But tab handling in gtk can be surprising.

**Comment by elstoc** [comment]
Sorry I should have been more specific. I set Ctrl+P to open preferences and that was failing for me. I assumed it was more a more generic issue and I admit I didn't try other shortcuts.
