### ISSUE TITLE
X-Trans DNG files with ActiveArea not aligned at CFA boundary rendered with wrong colors

### ISSUE THREAD

**Issue by cytrinox** [darktable-org/darktable#11973]
X-Trans has a bayer matrix with 6x6 dimension. If the ActiveArea is not aligned at this boundary, for example `ActiveArea 5 0 200 3000`, darktable shows false colors for such files. In RawTherapee and Adobe Lightroom, the DNG file is displayed correctly.

![grafik](https://user-images.githubusercontent.com/509535/171986881-a4fefa74-59c3-4189-a552-7975c4fc719b.png)

This bug happens somewhere in rawspeed when reconstructing the original CFA pattern for position (0, 0).

This is just a tracking issue, we already found some solutions in https://github.com/darktable-org/rawspeed/pull/369.

**Comment by jenshannoschwalm** [comment]
I ran into a somewhat similar issue for aligning xtrans while tiling.
Just as an information, i think the xtrans demosiacers are all fine with 3x3 patterns, not sure if this also holds for this processing stage.
What you suggest in the pr seems to align to next lower 6x6 position, this might not always be best, you could also chose closest.
Also, if there is a "wrong" ActiveArea it might also means there are data used otherwise by the vendor in that area, so probably better rounding up?

The reason why rt works fine is very easy, it doesn't take care of that tag.

**Comment by cytrinox** [comment]
@jenshannoschwalm It would be very confusing if rt ignores this tag. The CFAPattern encoded in DNG is always aligned on ActiveArea, so rt needs a) crop first then apply CFA or b) shift CFAPattern. And I've some raws (GFX100) with large black areas an the right side which is cropped away by rt (because ActiveArea told them so).

What rt doesn't take care is the DefaultUserCrop and DefaultUserSize tags which is a second crop that should be applied after debayer active area. But this is not related to the problem here.

**Comment by jenshannoschwalm** [comment]
Sorry, you are absolutely righr

**Comment by jenshannoschwalm** [comment]
Sorry, you are absolutely right, I misremembered the tag names. And here a 6x6 aligned. But then how to treat a left border of 1? You should replace it by 6 to be safe
