### ISSUE TITLE
preferences: inconsistent padding

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11976]
The padding is not consistent between items in the preference dialog. For example, the modules section of the processing tab shows different spacing between checkboxes and comboboxes.

![Screenshot_2022-06-04_16-53-46](https://user-images.githubusercontent.com/9555491/172013741-be67d7ae-f356-48c5-a82d-bebe0c891473.png)

**Comment by elstoc** [comment]
@Nilvus: probably one for you

**Comment by Nilvus** [comment]
Shit. Bad one... Will check

**Comment by Nilvus** [comment]
It's a really bad one and it's probably there since the beginning. Maybe some contrast or something else that I improved let it a little more visible. There's no margin or anything with CSS that can set this difference.
The only reason is that the check is inside checkbutton box. That add 1px margin inside checkbox. Shitty thing by Gtk!

So the only way is to add a margin-left as a workaround and I don't like workaround... I will add it and checkbox are also a little too big...

**Comment by Nilvus** [comment]
Forget last comment. I have not correctly see the issue at first. They are in reality perfectly aligned. You need to zoom out a lot to see that. It's just about border set on check button that is between background color of main content and check button background color... And combo don't have borders...

**Comment by Nilvus** [comment]
@elstoc: #11980 fix that
