### ISSUE TITLE
Filmic v6 seems to hue-shift red

### ISSUE THREAD

**Issue by sh1llo** [darktable-org/darktable#12047]
Filmic v6, when operating on saturated red pixels, seems to hue-shift red toward blue.
I've finally managed to convince myself that his is a bug or a numeric problem in colorspace conversion by finding an example where filmic leaves the red channel nearly fixed, but very noticeably increases the blue channel, in pixels that are well below clipping or desaturation part of the curve. Here I believe it's correct to compare to scene->display passthrough by turning filmic off in pixels that don't clip, and further, I believe that v6 with preserve="no" should keep the original chroma in the shadows and midtones, so this doesn't seem to be a desaturation effect.
In any case, this happens regardless of preserve chrominance mode (I tested "no" and "max RGB").

![p2](https://user-images.githubusercontent.com/12864377/173868544-9cd73e10-d1ef-4cc3-a9bb-0c59de691c2a.png)
![p1](https://user-images.githubusercontent.com/12864377/173868549-645d8800-715d-4f66-8459-329daa60d40c.png)

**Comment by flannelhead** [comment]
Thanks for the report. Could you please share the raw image and an XMP which has filmic enabled?

**Comment by sh1llo** [comment]
[raw-and-xmp.zip](https://github.com/darktable-org/darktable/files/8925581/raw-and-xmp.zip)

raw and xmp as above.

And you're on to something. Display profile is system default, which seems to be the almost (but not quite) the same as sRGB. The working colorspace is REC 2020. Seems that changing the working colorspace to sRGB, Adobe RGB or REC709 works around the problem (but the result looks terrible), and changing display to REC709 or REC2020 also seems to fix the hue but looks awful on display (and probably doesn't fix the export).

That said, if this is a colorspace conversion problem downpipe from filmic, why does it go away after turning off filmic?

**Comment by sh1llo** [comment]
Histogram and softproof are also rRGB. Changing them to REC2020 still measures hue shift in the picker when switching filmic on/off.

**Comment by flannelhead** [comment]
Thank you for the additional information. I could reproduce the shift you described and this confirmed an initial suspicion I had – this is not a bug but filmic saving the hat from a gamut escape.

First, there's a bit of a gotcha with the color picker readings. These are taken after the image has been converted to the output profile. Now, there are profiles which have only a color transformation matrix (all the "linear" profiles in darktable) and ones that also have a so-called "tone response curve" (e.g. sRGB and typical display profiles).

The tone response curves are usually defined per channel, starting from input value zero up to the maximum of the medium. Due to this, any channel below zero gets clipped (individually from other channels, so this is not hue-preserving). You might know that out-of-gamut colors are caused either by negative RGB channel values or too high values (over max brightness of the medium, i.e. display).

Due to this, if you have the display profile combobox set to e.g. `sRGB` or `system display profile`, negative RGB values get silently clipped before the picker values are read (which are expressed in "histogram profile" coordinates). See https://github.com/darktable-org/darktable/issues/3271 for a detailed discussion. Despite the ticket being closed, the issue persists.

I made a few checks with the image you sent, in different profiles. First I set histogram profile *and* display profile to `linear Rec.2020` to have truthful picker readings in the `linear Rec.2020` without any extra clipping in between. I disabled filmic to see where we are before filmic kicks in.

![lin_rec2020](https://user-images.githubusercontent.com/5001906/174304113-a5d84ee2-f579-440f-9e24-34c8a656ad3b.png)

Fine, the hat is within the Rec.2020 gamut. This is a good starting point. Then I wanted to see if it fits within sRGB – for this I set histogram profile and display profile to `linear Rec.709` which has the same primaries as sRGB but without any nonlinear tone response curve (matrix only).

![lin_rec709](https://user-images.githubusercontent.com/5001906/174304425-42340ecb-c37e-47c7-9db4-02246657ed0c.png)

Notice that the green channel goes negative. This means the hat is out of the sRGB gamut, too red. To show the effect of the choice of display profile clipping, I then set display profile to `sRGB` and left histogram profile at `linear Rec.709`. You see the negative green channel is clipped to zero – there's a hue shift.

![srgb_rec709](https://user-images.githubusercontent.com/5001906/174305091-9475c86f-3c18-4d6f-80e3-1e8ad443e788.png)

Let's enable filmic and see what happens now. I've chosen again `linear Rec.709` as the display and histogram profile because the gamut escape was seen there.

![filmic_lin_rec709](https://user-images.githubusercontent.com/5001906/174305528-1d1f96a9-63fc-4564-b045-57274ed8ec07.png)

Now the green channel is zero and the red and blue are changed a bit because filmic reduced chroma to fit the pixel within the output gamut (linear Rec.709). Filmic managed to save it from getting clipped at output.

Hope I managed to explain what you're seeing!

Ps. Mind you, I just noticed there's `local contrast` after filmic in the XMP. I should've taken care to disable it in order to have nothing between filmic and output profile, but I believe these screenshots still hold valid in principle. You might want to consider moving `local contrast` before filmic in the future – ideally, filmic should be the last module before output profile precisely to avoid uncontrolled clipping. Other modules can't guarantee that.

**Comment by sh1llo** [comment]
Thanks for the detailed reply, and I think I understand - the fact that I didn't see negative green threw me off. However, I'd expect to see the same or similar hue (not necessarily saturation) with filmic off, when the gamut is stuffed into sRGB with perceptive intent - at least that's what perceptive intent claims to do. Does Display transform just silently clip? Also, is REC2020 -> sRGB still the correct default for web images? (at this point I wouldn't use github to ask, but the documentation doesn't say).

Regarding Local Contrast, I'm aware of the risk, but I was under impression that it's still not ready to handle scene referred workflow. For one, it has shadows/highlights sliders, but doesn't allow me to choose neutral grey pivot, suggesting that these are hardcoded with expectation that white is at 1.0. So I just run it with generous shadows and highlights slider settings.

**Comment by flannelhead** [comment]
Linear Rec.2020 -> sRGB is a sane default for web images. Linear Rec.2020 is large enough to handle most of the visible gamut, and pretty much every software (unless specially color managed) seems to assume sRGB input.

Re perceptual intent: see this discussion https://github.com/darktable-org/darktable/issues/11777

It seems it was assumed LittleCMS2 handles gamut-mapping at output profile conversion (and actually darktable uses its own code path for suitable profiles, i.e. matrix + tone response curves) but this doesn’t seem to be the case unless you use a special output profile that contains a LUT for the perceptual intent. Anyway, that would be a ”canned” gamut mapping transformation and I think we’re better off with filmic v6’s approach here as it can map to any output profile.

**Comment by sh1llo** [comment]
Understood, thanks!

**Comment by kofa73** [comment]
@sh1llo : If you agree this is not a bug, could you please close the issue?

**Comment by sh1llo** [comment]
No problem!

**Comment by jorismak** [comment]
@flannelhead 

> nothing between filmic and output profile, but I believe these screenshots still hold valid in principle. You might want to consider moving local contrast before filmic in the future 

local contrast default location is behind filmic ('so above it', between output and filmic). AFAIK it's also one who isn't scene-referred safe, so it should not go before filmic because it will clip data before filmic can process it. Am i right?

**Comment by flannelhead** [comment]
> local contrast default location is behind filmic ('so above it', between output and filmic). AFAIK it's also one who isn't scene-referred safe, so it should not go before filmic because it will clip data before filmic can process it. Am i right?

@jorismak: I haven't looked at the local contrast module myself so I can't comment on whether there's clipping or not, but I believe you're right in that it should be used in the display-referred part of the pipe. So my recommendation that you quoted is probably bad and I stand corrected. `diffuse & sharpen` is the proper scene-referred alternative to `local contrast` and one should prefer that instead. But if you have any module between filmic v6 and output profile, the gamut mapping result from filmic v6 is not guaranteed to hold valid. That's what I mainly wanted to say.

**Comment by sh1llo** [comment]
@flannelhead Well, I already commented on local contrast, so to clarify: I never actually tested it inside scene-referred pipe, so I have no idea if it clips if used before filmic. Something that definitely should be tested. But even if it doesn't clip, to make it ready for scene-referred it should at least have the ability to define pivot points for shadows/gray/highlights, as I mentioned in my previous comment.

I disagree that diffuse&sharpen module is the alternative, though. DS operates on one particular scale, while LC uses Laplacian pyramid to increase the contrast on each scale in a controlled manner. Furthermore, the original Laplacian local contrast research paper introduced that operator specifically as the correction for loss of detail after a global tonemapping, not something easily replaceable. (see: S.Paris, Local Laplacian Filters: Edge-aware Image Processing with a Laplacian Pyramid)

I'm leaving open the possibility that there is a high degree diffusion equation for DS that would iterate into the good multiscale local-contrast, but I don't know whether that exists. If anyone reading this comment knows, I'd appreciate the input.

**Comment by todd-prior** [comment]
@flannelhead   

"I made a few checks with the image you sent, in different profiles. First I set histogram profile and display profile to linear Rec.2020 to have truthful picker readings in the linear Rec.2020 without any extra clipping in between. I disabled filmic to see where we are before filmic kicks in.""

Could the gamut checking not be made to do this computationally in the background without you having to change the profiles??  Seems weird to live with this sort of issue and not find a way to correct it....
