### ISSUE TITLE
Map display: repeated clicks on minus button (to zoom out) zooms in instead.

### ISSUE THREAD

**Issue by pbb72** [darktable-org/darktable#12090]
When clicking repetitively on the zoom out-button ("minus" button) in the upper left of the map window, the map is zoomed in instead of zooming out.

This is because a click on the button is *also* interpreted as a click on the map! Quick repeated clicks to zoom out more, are this way interpreted as a double-click on the map and thus result in zooming in.

The same effect can be seen when repeated clicking on the navigation arrows in the round button above the zoom buttons. This also causes zooming into the area in the upper left.

Clicks on buttons that are displayed on top of the map, should not be sent on to the map itself.

**Comment by Nilvus** [comment]
Map is displayed by osm-gps-map library. So this issue is probably more for osm-gps-map repository than darktable one. Unfortunately, osm-gps-map is not highly updated...

See: https://github.com/nzjrs/osm-gps-map/issues

I let this open a little and ping @johnny-bit as he works on darktable and on osm-gps-map last year. But we do not see him often those past months, he is probably less available.

**Comment by Nilvus** [comment]
I close this as an upstream issue. If needed, you could post it on https://github.com/nzjrs/osm-gps-map/issues
