### ISSUE TITLE
darktable cannot see the correct dateTimeOriginal in a DNG file

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12137]
I have some dng files I received whose dataTime isn't recognized by darktable, it sees 1/1/1 0:00, while ghtumb correctly see it:

![darktable](https://user-images.githubusercontent.com/1417508/177450588-7baae663-5d3b-493b-8e10-702c1ca4acdd.png)

I cannot upload the dng file, github tells me that is exceeds the 25MB allowed, where can I upload it?

**Comment by kmilos** [comment]
Before sharing the file (using cloud service like Google Drive, OneDrive, Dropbox, etc.), you can inspect and share the output of `exiv2 -pa` on your file.

**Comment by victoryforce** [comment]
> Here is the output of exiv -pa on the dng file.

@paolobenve Thank you for provided metadata. It is not so necessary to share your file as the content of the image itself is not relevant, only the metadata is important. I just pasted the date-time metadata you provided into my image file and debugged the issue with it.

The problem is clear, I will soon create a PR that will fix this bug.
