### ISSUE TITLE
windows installer fails with just 0xc000007b error in event log

### ISSUE THREAD

**Issue by brettowe** [darktable-org/darktable#12166]
was trying to install darktable in a windows 10 pro 21H2 install and I get elevate to admin prompt and nothing else
checking windows event logs I see event id 26 with the message 
Application popup: darktable-4.0.0-win64.exe - Application Error : The application was unable to start correctly (0xc000007b). Click OK to close the application. 

I have tried back to darktable 3.6.1 and see same thing.
no alerts from antivirus or anything else.

Willing to test things if given a direction

**Comment by gi-man** [comment]
Try the fix is the last post of this issue: https://github.com/darktable-org/darktable/issues/10712

**Comment by brettowe** [comment]
yeap that allowed it to work.
for windows 10 you can add a single file bypass and avoid the reboot suggested in the other report.
windows security->app and browser control->exploit protection->exploit protection settings
then under program settings you can add a program to customize and do exact path.
after that look for mandatory ASLR and check override and turn it off.
I would suggest turning off the override after it's installed

**Comment by gi-man** [comment]
I run Windows 11 Home instead of Pro. The home defaults to: Force Mandatory ASLR being off instead of On. The Pro version of Windows is not that common, so that's probably why we dont see this issue that much. Disabling the Mandatory ASLR to install and then reenabling should work for now. 

I will explore if there is something we can do when we compile.

**Comment by brettowe** [comment]
I've used https://github.com/securitywithoutborders/hardentools  on my system so it might be that instead of just being pro instead of home.

considering darktable itself doesn't need the option just the installer see if there is some difference between how the 2 are made?

**Comment by brettowe** [comment]
the uninstaller has the same issue btw

**Comment by gi-man** [comment]
We compile/create the .exe file used to install and uninstall darktable. Windows 10/11 Pro is blocking it from running/installing because of that Force Mandatory ASLR protection being turned on only on the Pro version of Windows. The Force Mandatory ASLR is a feature that forces the random use of memory and closes an exploit vulnerability (a remote one). I will explore if we can add a flag in the compile of the .exe to enable the ASLR, or to see if MSYS2 supports it.   For now, you will need to turn the protection off, install/uninstall and then turn it back on (or keep it off).
