### ISSUE TITLE
[FR] Improve performance by compute modules only inside minimum bounding boxe arrround drawn masks

### ISSUE THREAD

**Issue by mfg92** [darktable-org/darktable#12183]
I'm offten using "diffuse or sharpen" to sharpen only the main subject of the image. For that I'm using a drawn mask arround the subject. As all know "diffuse or sharpen" can slow down the image pipeline quite a lot. In my case, most of the computation done in "diffuse or sharpen" will be ignored because of the drawn mask. For that reason it would be great if only those parts of the image would be processed by "diffuse or sharpen" that will actually end up in the final image. ("diffuse or sharpen" serves here as an example for slow modules in general)

A relatively simple solution for this would be to reduce the dimensions of the buffer that is processed by a masked module. To do that the axis-aligned [minimum bouding box](https://en.wikipedia.org/wiki/Minimum_bounding_box) arround the drawn mask has to be computed.

Here is an example image to illustrate a scenario where most of the processed buffer of "diffuse or sharpen" will be ignored, unless the module is only processed for the purple minimum bouding box.
![example](https://user-images.githubusercontent.com/11365250/179351034-433b53be-3716-4c3c-8547-7940dfe206b2.jpeg)

Things get more compilcated if the full power of masks is used:
1.  Multiple masks are used, I can see two solutions for that
   a) Use minimum bounding box arround all drawn masks
   b) Process module for each individual mask (and its curresponding minimum bounding box)
2. Drawn masks are used together with parametric masks
3. Mask refinment (especially feathering and blurring) are used

Furthermore, I guess that some modules would need extra space arround the minimum bouding box, e.g. "blurs".

So, to simplify things, this "cheat" could only be active if certain precondition are met (like no parametric mask are used).

I must mention that I only know a little about darktable's internals, therefore I can not judge how big the impact of implementing this would be. I'm interessted to hear your opinions.

**Comment by ralfbrown** [comment]
1b) would require a re-architecting of the pipeline to handle multiple ROIs for a single pixpipe run, and it would run into the same inefficiencies as tiling for modules that need a large neighborhood of pixels (e.g. for any wavelets-based algorithms, we need additional pixels equal to the size of the largest wavelet scale).

1a) is much simpler, but would still have some rather tricky aspects - we'd need to run everything before the blended module as if there were no masking, then copy just the bounding box (plus any neighboring pixels accessed by the module) for the module, then do the blending of the reduced-size module output with the full input.  We'd also want the option of still running on the full viewport even with masks, since all of the above will probably be slower for many of the simplest modules.

**Comment by aurelienpierre** [comment]
> A relatively simple solution for this would be to reduce the dimensions of the buffer that is processed by a masked module. To do that the axis-aligned [minimum bouding box](https://en.wikipedia.org/wiki/Minimum_bounding_box) arround the drawn mask has to be computed.

This simple solution will not work because the module works in wavelets space and needs a padding around the bounding box that is at least equal to the radius of the largest wavelet scale used in the computation. The largest wavelet scale is set to 2.5 times the radius center + radius span. Aka it will be close to the full picture in many cases.

**Comment by mfg92** [comment]
Thank you for your feedback.

So I get the feeling that you both don't value the benefits enough compared to the needed effort and furth code complication. I'm ok with that, of course.

@aurelienpierre 
At least for my use case that is not an isssue: When doing sharpening max(radius center + radius span) is 12px, so adding 2.5*12px=30px arround the bounding box wouldn't hurt to mutch.
