### ISSUE TITLE
Add high quality print option or one to print using system dialog

### ISSUE THREAD

**Issue by gnapiorkowski** [darktable-org/darktable#12221]
**Is your feature request related to a problem? Please describe.**
On my Epson xp-6000 with glossy paper this causes lines on the print.
In the `system print dialog (CUPS) -> Advanced tab -> Quality` I have the `Standard` and `High` option. In darktable I don't get that. I'm not sure what it does exactly, but it seems that Darktable uses something right between Standard and High. I get even wider spread lines with system print dialog on`Standard` setting. On `High` I get a perfect photo (it's really slow, the printer seems to go over dots over and over, with Darktable it's really fast - not sure if that helps). So my usual workflow is to export the photo, open it in GIMP and print from there.
Also the colors seem a bit flat with Darktable print.

_I've only recently started to use Darktable and I love it. The print module is awesome too, so it's a real pity that I can't use it as of now :/_

**Describe the solution you'd like**
I see two ways to address that:
1. (hard) implement a similar quality setting (or just use high all the time).
2. (maybe easier) Add option to "print with system dialog" (like Firefox does)

**Alternatives**
I will still need to spend a bunch of time exporting and opening it in GIMP to print.

**Additional context**
I experimented with every setting in DT print module, non of the helped. I tried upscaling the image, importing it again... So I'm 99% sure that I didn't miss anything and it's not my fault.

Image printed from Darktable
![darktable](https://user-images.githubusercontent.com/56068621/180486122-91c8653a-0522-45f3-b01b-1012733da7c5.png)
Image printed from GIMP (system dialog)
![system_dialog](https://user-images.githubusercontent.com/56068621/180486269-916136aa-3644-4d73-b1a5-ef4e0ee4bb7e.png)

**Comment by TurboGit** [comment]
May I suggest that you look for TurboPrint for Linux as CUPS has no color-profiles and won't render the print correctly. I'm using TurboPrint since many years now and I'm quite happy with the result. It is no free, but the license is really cheap and no way near the cost of a printer, paper and ink which are very expensive anyway.

BTW, I see some stripes on the GIMP print too even if not as visible.

**Comment by gnapiorkowski** [comment]
Wow, thanks a lot for this quick reply! :D The prints aren't perfect, the photo wasn't great quality, I also scanned it badly. But in person the difference is really apparent. The sharp small stripes you see I think are the artifact of scanning mostly. In person they are much softer and in GIMP version - not really visible.

Thanks for the suggestion. Despite the fact that I really don't like the idea of closed source I just tried turboprint trial version.
It looks very customizable, but 1. it crashes every time I try to add a custom paper after adding a first one; 2. I get the same issue still. I've set the quality to highest quality - 720p(not sure why there isn't 1444p, but nvm), however it still prints very fast and leaves the "lines". I looked through the options, but I don't see anything that would address that. So their "Print your documents, graphics & photos easily and in professional quality" doesn't cut it for me.

I think the issue is with the speed of printing rather than anything else.

As for the color profiles I honestly don't care that much. I print my work for myself, so I can just correct for what I see is wrong. I'm not looking for perfection, just saw an opportunity for improvement. :)

I will do my best to deep dive into the implementation of the xfce/cups print dialog (not sure whose it even is) and look for clues there.

I did a better scan this time. You can see the soft raibow'y/square'y stripes on the right side of the sky that I struggle with:
![turboprint-downsized](https://user-images.githubusercontent.com/56068621/180596851-81af1953-df31-46fb-b15b-64153fc94729.png)

**Comment by TurboGit** [comment]
@gnapiorkowski : Stange that TurboPrint crash for you. I'm using it since a long time and it works fine on my side. I have made lot of print in A4, A3 & A2 on an Epson 3880 & Canon Pro 1000 without any quality issue. Could that be an issue with the printer?

**Comment by TurboGit** [comment]
I understand also your comment about close source, but TurboPrint is not expensive and that's the only way to get decent print on Linux anyway. There is currently no open source module proposing proper color calibrated prints for printers and papers.

**Comment by gnapiorkowski** [comment]
I'm not saying that it's expensive. The version that supports my printer(Pro/Studio) costs over half as much as I paid for the printer. But it's ok. I wouldn't mind paying that much for something that adds value. But it doesn't for me. I am perfectly happy with the results I get with CUPS. And TurnoPrint doesn't even solve my "lines"/speed issue.I understand that if someone uses it professionally they might require more, but I don't, it's just an after hours hobby for me and I can compensate for the colors easily enough to get results that I'm happy with.

My deep dive resulted in finding CUPS ppd attribute `coups-OutputMode` that I think is responsible for that. Although I'm not 100% sure about that.

The GIMP print dialog seems to belong to GTK.
Here is the "High quality" setting [GTK/print settings](https://github.com/GNOME/gtk/blob/53013676309522d08e4f30257b7bfd17d68bead2/gtk/gtkprintsettings.c#L924).
And it's set for the cups backend here [GTK/cups backend](https://github.com/GNOME/gtk/blob/50e4ca8593d12b2de76e4d092d34ec7a1655ede8/modules/printbackends/gtkprintbackendcups.c#L6168,L6352) as OutputMode,
which seems to be defined here: [CUPS/ppd.h](https://github.com/apple/cups/blob/2201569857f225c9874bfae19713ffb2f4bdfdeb/cups/ppd.c#L495).

As for where that would fit into DT, I'm not exactly sure. I was digging through [darktable/cups_print.c](https://github.com/darktable-org/darktable/blob/07d86ce044805dbd6bf9df565fa6641d4fb95ab0/src/common/cups_print.c}, but I'm quite overwhelmed with C language at this point... :face_exhaling:

**Comment by gnapiorkowski** [comment]
A bit off topic, but re color calibration

>There is currently no open source module proposing proper color calibrated prints for printers and papers.

There seems to be an open source established way for color calibration. https://man.archlinux.org/man/cups-calibrate.8

**Comment by docrobs** [comment]
Perhaps I am being over-optimistic, but colour profiling in Darktable/Gutenprint/CUPS almost works perfectly. I used to use TurboPrint but have been trying to move to more conventional means of profiling with paper suppliers' custom profiles, which are available free of charge.

I use Darktable's Print module with colour management in the Gutenprint/CUPS driver turned off, to print the suppliers' colour patch templates. I put the received ICC files into DT's /color/out directory and the result for 99% of prints is perfect. The same ICC file will work with Qimage (run under WINE) and gives identical results. However using this ICC profile when printing from GIMP will not give accurate colours; I do not know why.

The 1% of prints where this fails have grey areas where there is a gradual change of luminance over a significant distance. Instead of a continuous unbroken change, the shades of grey change in distinct bands, which are clearly visible on the print. This behaviour is accurately reflected in the soft proof. It does not seem to occur in areas of colour, but only in desaturated areas.

Extensive tests with various profiles from different paper suppliers have proved conclusively that the fault lies in the production of the patch prints. Using a generic profile instead of the custom profiles will give inaccurate colours but there is no banding whatsoever. I have been unable to find the cause for this problem. Clearly Zedonet have an answer because TurboPrint, where colour management is entirely handled by the driver, does not exhibit any banding.

If this issue can be fixed, I can see no reason why Darktable (or Qimage) would not perfectly fulfil the final link in the workflow chain - the printing itself.

**Comment by Rudd-O** [comment]
It's terrible that t's 2025 and there's still no way to set high resolution printing in Darktable, thus it's in practice useless to print photos.

**Comment by TurboGit** [comment]
Again, I've been printing for many exhibitions without issue so your comment is misleading.

**Comment by Rudd-O** [comment]
It's cool that you can get by with default printer quality, but I wanted to print a 4x6 photo on my printer capable of 600x600 dpi.  No option is available in the Darktable print screen to turn that on.

**Comment by TurboGit** [comment]
That's a printer driver issue then. You should have an option to choose the quality on the printer driver settings.

**Comment by Rudd-O** [comment]
When I print in any other app, the dialog lets me select the print quality.  In Darktable it does not.

So, is it a driver issue?  It's probably not since nearly every other app lets me do this, and it works (print goes more slowly, quality is markedly superior on photo paper).

Do _I_ care if it's a driver issue?  No, not at all.  I just went back to printing with the GIMP and ditched Darktable altogether.

I'll untag myself from the bug now.

**Comment by ptilopteri** [comment]
* Rudd-O ***@***.***> [12-30-25 06:24]:
> Rudd-O left a comment (darktable-org/darktable#12221)
> 
> When I print in any other app, the dialog lets me select the print quality.  In Darktable it does not.

odd that.  must be local problem with dt install on your box.  has always
provided quality settings for me.
 
> So, is it a driver issue?  It's probably not since nearly every other app lets me do this, and it works (print goes more slowly, quality is markedly superior on photo paper).
> 
> Do _I_ care if it's a driver issue?  No, not at all.  I just went back to printing with the GIMP and ditched Darktable altogether.
> 
> I'll untag myself from the bug now.

yes, throw your hands up because you are unable to determine the cause of
a local problem.  no one can help you without you providing information
that will allow them the try to help your determine YOUR local problem.


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by Deltafire** [comment]
I'm also experiencing this issue, running Darktable 5.4.1 on Linux.

There does not appear to be an option to change the print quality setting, which seems to be fixed on 'Draft' or 'Normal'. I tried changing the default to 'High' in the Cups web interface, but this made no difference.

Should there be an option somewhere? Or perhaps the system print dialog should pop up when clicking the Print button.

Possibly related: the printer select drop-down doesn't drop-down or allow me to change the selected printer.

**Comment by GustawXYZ** [comment]
Hey @Deltafire unless someone updates the Darktable cups integration ([src/common/cups_print.c](https://github.com/darktable-org/darktable/blob/07d86ce044805dbd6bf9df565fa6641d4fb95ab0/src/common/cups_print.c)) the option won't be there, and there isn't much you can do about it, besides using a different app to print.

Unless this parameter is added - CUPS will just default to whatever's set as default - usually "Normal" or "Draft".

This is not a driver issue, just a parameter setting missing, because of which the default one is used.

Other option would be to implement "Print using System Dialog" in DT, but the DT print dialog is pretty good IMO, so this is probably not neccessary.

Some commenters mentioned it worked for them, so probably for their printers the default is "High", or they have a driver side setting, which would update those setting using some side channel, not supported on the stack I used though.
