### ISSUE TITLE
Denoise (profiled) interacting with OpenCL

### ISSUE THREAD

**Issue by tnargs** [darktable-org/darktable#12234]
**Describe the bug/issue**
Using DT 4.0.0 on MacOS Monterey 12.4 with M1 Silicon Mac Mini (16 GB). When OpenCL is enabled, turning on Denoise (profiled) module in Darkroom causes image to wash out (much brighter, very low contrast). 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open darktablerc file and change '1' to '0' on line starting with cldevice_v4_. This will allow OpenCL to be enabled.
2. Open DT Preferences/Processing and check the box next to 'activate OpenCL Support'. Leave defaults on the 2 dropdown lists below it.
3. Open an image file in DT/Darkroom and turn on 'Denoise (profiled)' module.
4. See dramatic change in image appearance (even though histogram is unchanged).

**Expected behavior**
OpenCL will cause DT to run faster and not images to look different. (BTW it doesn't run faster either)

**Screenshots**
See https://discuss.pixls.us/t/diffuse-or-sharpen-module-ouch/31821/13?u=t_n_args 

**Platform**
Using DT 4.0.0 on MacOS Monterey 12.4 with M1 Silicon Mac Mini (16 GB). 

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**

Note that I am not very technical and was encouraged to lodge this report when I opened the thread linked under 'Screenshots' above.

**Comment by jenshannoschwalm** [comment]
Thanks a lot for the report!

I don't know the opencl driver your system is using, it might be (technically speaking) cpu emulated, thus without a performance gain. Also that would disable opencl for darktable by default.

Please start dt on a console by using these options `-d opencl` and post the log you see. This would tell how OpenCL is configured on your system.

The specific problem with the profiled denoising module, can you observe it with all settings or is the issue depending on any setting?

**Comment by tnargs** [comment]
Hi, this is the log I got
[Darktable opencl log.txt](https://github.com/darktable-org/darktable/files/9206885/Darktable.opencl.log.txt)

**Comment by jenshannoschwalm** [comment]
Thanks,

1. your logs shows a common osx problem, because of some (still unknown) reason the OpenCL kernels can't be compiled in on run, you have to start dt several times to have them all up&ready. I don't know how often you have to dt, as i have heard maybe 3 or 4 times. So, if you did that, does the issue persist?

2. yes you have a GPU OpenCL device (although that seems to be pretty slow - yes i know the benchmark is misleading to the worse but - still bad) It might be worth to investigate the OpenCL performance for the un-affected modules. You can find out (to compare you would have to run this with opencl on and again with opencl off) by using the ``-d perf`` option. I (we) have no idea how good OpenCL might work on your hardware at all so if you could do checks and report back we might be able to give advice for other users or devs. 

So if after (1) the issue persists - can you identify settings in the denoise module that make the issue appear / disappear in a reproducable way? The more precise your informations are, the greater is the chance for us to detect the issue just by reading code. Would be cool ...
