### ISSUE TITLE
picker shortcuts do nothing when right panel collapsed

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#12255]
darktable 4.1.0+109~g4ea7e5d5c on ArchLinux.

I have a shortcut assigned to the filmic rgb "auto-tune levels" picker. However, if I collapse the right-hand panel in the darkroom, by pressing tab or collapsing the panel individually, the shortcut no longer works and nothing happens when I press it.

**Comment by elstoc** [comment]
@dterrahe please can you advise - I still have no idea how to navigate the shortcut code.

**Comment by dterrahe** [comment]
This could be fixed in _widget_invisible, but #11032 suggests that even if a widget is deliberately hidden because its functionality is currently not enabled, it should still be active and steps taken to switch modes when it is manipulated. This would apply to mask modes, but really any dropdown that reconfigures visibility of subsets of widgets within a module too.
