### ISSUE TITLE
Darktable for M2 Mac shows as "greyed out"

### ISSUE THREAD

**Issue by goprodiver** [darktable-org/darktable#12309]
I downloaded the latest dmg file from the DT website (darktable-4.0.0_arm64.dmg) and installed it on the MAC, I then opened the program and right away, the whole program was showing as "greyed" out rather than the usually black/dark grey colors. I have uninstalled and re-intalled it 3 times and ever tried the intel based file (darktable-4.0.0.dmg) and it does the same thing every time. I then procedded to import some images I had been editing on another computer (Ubuntu desktop) and the images show the correct colors while the rest of the application still shows "greyed out". See screenshot below.

<img width="1710" alt="image" src="https://user-images.githubusercontent.com/111137843/184386986-b1c65918-7398-4e82-8e62-590035974010.png">
*I added the red squares just to protect my privacy.

* darktable version : 4.0.0
* OS                : MacOS Monterrey 12.4
* Comp   : Mac Air with M2 chip

**Comment by pehar1** [comment]
This is one of the grey themes of the application, can be changed in preferences.

**Comment by goprodiver** [comment]
I'm dumb, thank you!

**Comment by Nilvus** [comment]
Grey theme is just now (since darktable 4.0) default recommended theme. That's why you have it by default on launch. It's for correct and better image processing. If you want to understand why, just check that article: https://www.darktable.org/2019/12/darktable-30/ (go on Major Features part and read text under first screenshot of darktable elegant grey theme).
