### ISSUE TITLE
global color picker accuracy

### ISSUE THREAD

**Issue by douzzer** [darktable-org/darktable#12310]
In #3271 and darktable-org/dtdocs#188, it was clarified that

>As the global color picker runs at the end of the preview pixelpipe, it receives data in display color space then converts it to histogram color space. If you are using a display color space which is not “well behaved” (this is common for a device profile), then colors that are outside of the gamut of the display profile will clip or distort.

However, I am finding (using DT4) that colors are distorted regardless of relationship to display gamut.  Specifically, if I pick colors from a numerically-generated grayscale gradient, the picker shows the correct R==G==B values only if I override the display profile with an ideal profile (e.g. the builtins like sRGB, AdobeRGB, ProPhoto, etc.).  With the physically measured display profile, there is deviation on all of the reported values, even though they are all well within gamut (gamut check on the display profile shows nothing out of gamut).

It seems awkward and fidgity to try to undo the display profile to get at the actual color, and it seems to me the only way to avoid these troubles is to have the global color picker jack into the pipeline earlier, when the data is still in the working space and untruncated.

**Comment by mediatechnologic** [comment]
Even with histogram and all other profiles set to "sRGB (web-safe) there is something heavily wrong with the color picker. For homegenous color areas the results are correct. But the calculated mean value is incorrect for mixed pixel areas, because the arithmetic average of sRGB values is calculated. That is wrong, nonsense and useless. Correct would be the conversion to linear intensity, making the arithmetic average and converting back to nolinear sRGB. You see this effect best with a 50 % white/black checkerboard. The brightness should correspond to sRGB = 188 and not 128 as it is currently the case.

Quite similar is another issue. Reduction of exposure to −1 EV does reduce full white areas of sRGB= 255 to 128 and not to 188. That is not, what a user does expect from EV variation. Am I wrong with this?

**Comment by mediatechnologic** [comment]
I started a discussion on pixls at ["srgb-calculation-of-exposure-module-and-color-picker-wrong"](https://discuss.pixls.us/t/srgb-calculation-of-exposure-module-and-color-picker-wrong/34204) with a couple of screenshots.
The solution to change module order to v3.0 JPEG does only solve to correct exposure influence. But the color picker itself does calculate min, max an mean values wrong. In addtion there is a strange overshoot when crossing dark/bright borders.

**Comment by douzzer** [comment]
Thanks @mediatechnologic for keeping the ball rolling on this.  I agree there's several things awry with the color picker, and it's often hard to figure out what it's doing.

**Comment by mediatechnologic** [comment]
It is not only the color picker, but also the image preview 
and also all displayed images in the darkroom edit mode.

I do not care about the preview (this is also wrong for most other image tools)
and I can live with the wrong color picker. But the displayed image should be correct.
And it is not correctly calcalated for any zoom level not equal to 100 %.

Open the attached color checkerboard PNG file in any tool including your browser
any you will immediately see, if the scaling is correct or wrong.
![ey-checker_area_v20230106_green+magenta](https://user-images.githubusercontent.com/20679721/211171652-52478b1a-b663-472f-ab87-6656d5f1493f.png)
The checkerboard file should be displayed in Darktable for all zoom factors
with perceived light yellow (188,188,128) and NOT with light red(188,128,128).

See also the screenshots and discussions at Pixls:
[Wrong RGB calculation in DT color-picker and display](https://discuss.pixls.us/t/rgb-calculation-color-picker-and-display-wrong-exposure-module-solved/34204)

I think, that this topic is much more important, than some cosmetic GUI addons in DT.
This because the displayed image is the base of interpretation for module adjustments
and the color and brightness of pixel processing in display should be fully correct.

sRGB standard IEC 61966-2-1 is now 24 years old and darktable should follow 
other tools like LR and Gimp, who do the sRGB-gamma-expansion/compression correctly.

**Comment by mediatechnologic** [comment]
The sRGB standard IEC 61966-2-1:1999 is still quite expensive for 185 CHF at [webstore.iec.ch/publication/6169](https://webstore.iec.ch/publication/6169) or for 254 USD at Amazon. But the nonlinear formulas for correct pixel calculations are well known and published e.g. at [en.wikipedia.org/wiki/SRGB](https://en.wikipedia.org/wiki/SRGB)

See my publication of graphical "gamma" curves at [www.mtlc.eu/dam/srgb.html](https://www.mtlc.eu/dam/srgb.html)
Nothing new, but a confirmation and clarification of the famous website
of Eric Brasseur about Gamma Error in Picture Scaling [www.ericbrasseur.org/gamma.html](http://ericbrasseur.org/gamma.html)

Most modules in DT state clearly the linear or non-linear processing, 
but why is this processing not done correctly for color picker and displayed image?

**Comment by mediatechnologic** [comment]
By the way, the export of downscaled images in DT does also calculate the pixels wrong (not linear).
That is even more severe. May be I miss a setting, but correct scaling on export should be default.

**Comment by dtorop** [comment]
@mediatechnologic @todd-prior Thanks for steering me to this. It's interesting! I appreciate that there's a good test case for this from @mediatechnologic. I haven't looked at the whole thread carefully yet, though.

There's probably a bunch of flakiness in all this color picker work which could use some thinking through. For example, if the final colorpicker is making a min/mean/max calculation in RGB space, how meaningful is this when the final #'s are shown in Lab or LCh?

I'm deep in some underpinnings changes to the colorpicker calculation code, and similar follow-ups to the histogram calculation code. If I do it right, the code should be more legible but have minimal user-visible changes, but at least it could make future changes/fixes easier.

Another question is just how right the colorpicker _needs_ to be. Obviously it shouldn't be embarrassingly wrong. But do we use it to get more of a relative sense (is this clipping? is this neutral?). Or do hit specific numbers in specific colorspaces?

**Comment by todd-prior** [comment]
@dtorop THanks for your comments... I guess the simple question that remains is it correct to just average pixels and use that result or should the values be the average of the linear pixel value operations and then converted back... It seems like DT makes a lot of effort to be as linear as possible and do as much math in a linear space then why would this not translate to the picker values reported... The bigger ramification is shown when you scale the display and the same non linear averaging happens to the pixels as you zoom out so the display color is a rose instead of a green... Obviously the checkerboard is not an image and exaggerates the issue but doesn't it still show that pixel values esp less than 100% zoom and weirdly also for any zoom > 100 except 200 400 800 and 1600... which appear okay while the rest are not.... so the calculations show by the picker are also being used for pixel display and arguably offering up the wrong color.....

**Comment by mediatechnologic** [comment]
Exactly Todd,

May be the color picker is not so important, but the scaled display in DT darkroom 
and especially the DT export is certainly much more relevant. 
Here is my raised issue of today about the same wrong pixel calculation of all scaled DT exports: https://github.com/darktable-
org/darktable/issues/13335#issue-1532913786

Yes, the checkerboard is exaggerating, but representing all fine details in any foto.

Best regards, Rudy
