### ISSUE TITLE
Very high contrast of blues in RAW rendering

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [darktable-org/darktable#12331]
I'm playing around with DarkTable and I've been running into some issues with the default render of RAWs and blown out blues in high brightness. 

For example, this is the rendering of a RAW file in DarkTable:

![image](https://user-images.githubusercontent.com/12765521/185053471-323f13de-ee1b-49a1-bbb2-a5e6f2b4d18b.png)

And this is the original image, as rendered by the manufacturers' software:

![image](https://user-images.githubusercontent.com/12765521/185052997-bac2c142-ab2e-42e1-aeb4-421c1853e471.png)

Normally I'd be okay with some differences as it gives a different feel to the images, but this is a super distracting level of blue in all of the photos that are shot in bright light and I cannot seem to find a way to remove it in post without causing a lot of changes to the image. 

I am wondering if there is a suggested way of approaching handling this to tone down the intensity to something closer to the desired image? (manufacturer)

**Comment by Nilvus** [comment]
It's not an issue. Remember first that a RAW development software like darktable is not to have same rendering as manufacturer's one (it would be so faster to use jpg) but let you have your rendering. Github is not a help support but is here to post bugs that can be fixed in darktable code.

Here is just how to deal with highlights. You could use highlights reconstruction section of filmic rgb and/or highlights reconstruction module (method with LcH is often the simplest and better one.

If needed, use pixls.us forum (https://discuss.pixls.us/c/software/darktable/19) and post your issue to have more help. Manual is also a good help.

**Comment by Nilvus** [comment]
Oh and think about searching highlight word on pixls.us forum before posting. You will find some topics that could be helpful. You could also find some good tutorials on Youtube about darktable and such related topics.
