### ISSUE TITLE
dt.gui.action() causes crash when setting values from lua script

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#12348]
**Describe the bug/issue**
Calling dt.gui.action() from a lua script with a request to set a combobox value results in a darktable crash.  

When @dterrahe and I worked on this originally we didn't have a very good idea of how to test it.  Now I have a better idea of how to test it so we can drive out the bugs we missed earlier.

**To Reproduce**

1. Unzip and add the included lua script to your lua scripts
2. Start darktable, enable the script and assign a shortcut to it
3. Open an image in darkroom mode and press the shortcut assigned to the script.  This should set the filmicrgb auto tune levels and set preserve chrominance to luminance Y.
4. darktable crashes

**Expected behavior**
filmicrgb levels are set by auto rune (works) and preserve chrominance set to luminance Y 

**Platform**
N/A

**Additional context**
 - Discovered while working with #12338
 - Can you reproduce with another darktable version(s)? **yes**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
  - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? yes
   - What lua scripts start automatically? none for this
   - What lua scripts were running when the bug occurred? smart_styles.lua

**Script**
[smart_styles.zip](https://github.com/darktable-org/darktable/files/9378508/smart_styles.zip)

**Comment by dterrahe** [comment]
After a bit of trace work...

First, apologies for misinforming you; to select a dropdown item, you have to add "item:" to the effect, so "item:luminance Y" in this case. After all, a combo could contain standard effects, like next/previous etc. With that change and just using the last line of your script, the combo does get updated.

Second; to just read the value via a dt.gui.action call, you have to pass NAN to the speed parameter (since 0 is a valid value in combination with the "set" effect). Can't remember what NAN is called in lua so haven't tested. With 0, it executes the default effect, popup, and the now focused popup window seems to confuse X when the next call tries to update the combo control, which is at that point not focused. Not sure how wide this problem is or what fix would be required. Normally, shortcuts can only be triggered when the dt main window is focussed, so simplest fix might be to check for that in dt.gui.action and return without doing anything when it isn't. But this might be overkill/limiting.

**Comment by wpferguson** [comment]
> Second; to just read the value via a dt.gui.action call, you have to pass NAN to the speed parameter (since 0 is a valid value in combination with the "set" effect).

I think this is mis-coded in action_cb() in lua/gui.c.  I thought (or misunderstood) that 0 and NaN had the same effect, to I translate 0 to Nan.  I'll fix it.

> Can't remember what NAN is called in lua

I just do
`NaN = 0/0`

I plan on coding up every type of manipulation that I can think of in a script, both to learn the ins and outs, and to provide us with a test script at the end that exercises all the possibilities.  I'll probably have lots of questions along the way.

Here's the first - Can I change the module order in the active modules list?

**Comment by wpferguson** [comment]
>  think this is mis-coded in action_cb() in lua/gui.c.

I mis-spoke.  The default is NAN and if an argument is provided I replace it with the argument.

**Comment by wpferguson** [comment]
> Normally, shortcuts can only be triggered when the dt main window is focussed, so simplest fix might be to check for that in dt.gui.action and return without doing anything when it isn't. But this might be overkill/limiting.

Maybe we just figure out the bad combinations and check for them (i.e. "selection" with no effect and a speed that's not NaN).

**Comment by wpferguson** [comment]
I went through the shortcuts module and figured out the effects for the elements so now I kind of know what's allowable.  The interface seems to work pretty well as long as you use the correct effects with the elements.  It's even good about rejecting bad choices such as `item: doesnt exist`.  It just prints an error and keeps going.

I did come across one problem.  If I try `dt.gui.action("iop/diffuse", 0, "presets", "next", 1.0)` that results in a crash even though `next` is listed in the effects drop down for presets in the shortcuts gui.  In the shortcuts gui I can assign a shortcut to a preset, but I don't get a tooltip when I hover.

**Comment by wpferguson** [comment]
Attached is a spreadsheet with elements and effects that I came up with.  I can take that and add a syntax checker to `action_cb()` in l`ua/gui.c` to at least make sure the effect is proper for the element which should get rid of most of the crashes.

[dt.gui.action.verbage.ods](https://github.com/darktable-org/darktable/files/9385935/dt.gui.action.verbage.ods)

**Comment by dterrahe** [comment]
> `next` is listed in the effects drop down for presets in the shortcuts gui

This was intended new functionality (#6651) but not trivial to implement because the "currently active" preset is not stored anywhere. I'll change to write a "not implemented yet" message to stderr, so maybe somebody will pick it up. The second and third _effect_ are reserved for _previous_/_next_ so this will work with fallbacks and mouse scroll etc. Definitely shouldn't crash!!

Actually; non of the iop/presets _effects_ have been implemented yet :-) They are just placeholders and all just show the presets popup (which then presumably triggers your crash as per bauhaus popup). My todo list at the time was huge and eventually I just set it aside until anyone expressed interest.

> Attached is a spreadsheet with elements and effects that I came up with.

There are quite a few more action types than just those two, with their own sets of effects. Such as utility module, dropdown, button, toggle, tabs etc and even specialised ones that are only used in their respective modules, like color zones.

> I can take that and add a syntax checker to `action_cb()`

This already happens in dt_action_process, so there's no need (and no easy way that doesn't require maintenance every time an action type is added or changed) to replicate that.

> Maybe we just figure out the bad combinations and check for them

I'm afraid we would be playing whack-a-mole and would need to export action type definitions from each source file that registers them with inputng (where now these definitions are designed to be localised). Plus it would make it more confusing for the user. A general rule that darktable.gui.action only works when there's no open dialog (unless speed=NAN) makes intuitive sense to me. If a script wants to open a (bauhaus popup) dialog, it should be the last thing it does anyway, because how otherwise is the user going to _use_ it?

> I plan on coding up every type of manipulation that I can think of in a script

Great! Being able to build some more automated testing (although a gui/screen is still required to run it so might not work in CI) was one of the goals of dt_action_process.

> Can I change the module order in the active modules list?

You came across instance/move up/down in your inventory.

There is no direct way to "set" (or read) the position of a module in the list. This would be new functionality; the meaning of a "position" number would need to be defined. Do we count from bottom or top? Do we count inactive modules? What do we do if the user requests an invalid position? (we don't have this problem with "move up/down" because that action simply gets deactivated when the first or last allowed position for a module has been reached).
