### ISSUE TITLE
CR3 files FROM EOS  not supported by dark table

### ISSUE THREAD

**Issue by jsepulvedaf** [darktable-org/darktable#12362]
CR3 files FROM EOS  R10 not supported by dark table

![image](https://user-images.githubusercontent.com/31807999/185758412-3e4655a7-082a-43fb-9090-6ac3de539e8e.png)

**Comment by victoryforce** [comment]
CR3 files from which Canon EOS camera model? Not supported by which version of darktable?

In any case, your issue is a statement of a certain fact. There is nothing useful in it that would help add support for the new camera. Therefore, the reaction to it can be "yes, we know" and closing the issue.

To help, you can check if sample images from this camera are available on [raw.pixls.us](https://raw.pixls.us) and add them to this site if not.

**Comment by jenshannoschwalm** [comment]
Could also be a problem with exiv2 not available with support as on fedora 36?

**Comment by wpferguson** [comment]
I believe that the R, RP, R5 and R6 are supported in darktable 4.0.  The R3, R7, and R10 are supported in master.

**Comment by jsepulvedaf** [comment]
> CR3 files from which Canon EOS camera model? Not supported by which version of darktable?
> 
> In any case, your issue is a statement of a certain fact. There is nothing useful in it that would help add support for the new camera. Therefore, the reaction to it can be "yes, we know" and closing the issue.
> 
> To help, you can check if sample images from this camera are available on [raw.pixls.us](https://raw.pixls.us) and add them to this site if not.

CANON EOS R10

**Comment by jsepulvedaf** [comment]
> CR3 files from which Canon EOS camera model? Not supported by which version of darktable?
> 
> In any case, your issue is a statement of a certain fact. There is nothing useful in it that would help add support for the new camera. Therefore, the reaction to it can be "yes, we know" and closing the issue.
> 
> To help, you can check if sample images from this camera are available on [raw.pixls.us](https://raw.pixls.us) and add them to this site if not.

DARKTABLE 4.0

**Comment by Nilvus** [comment]
Already fixed by https://github.com/darktable-org/darktable/pull/12124
