### ISSUE TITLE
Locked presets should be made auto-appliable

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12377]
dt 4.0

System presets are locked: the user cannot modify them.

If a user find one of them useful for his default workflow, he should be able to set its auto-apply feature.

This isn't possible in current dt.

I find that not logic: making a present auto-appliable doesn't mean modifying it.

Now, in order to make a system preset auto-appliable I must store it as a new preset, give it a new name, and then set the auto-apply flag.

As a consecuence, new images have that preset applied, but the preset menu shows 2 presets applied: the original and the copy. This confirms the idea that the auto-apply property doesn't belong to what defines the preset, and such should be modifiable.

Permitting to set the auto-apply flag in a system preset would avoid this inconcistency, too.

**Comment by elstoc** [comment]
The idea sounds good but currently the system presets are dropped and recreated every time you start darktable (because sometimes they are changed or removed in a new release).

I'm not sure how to easily go about what you suggest and still handle those future changes in releases. For example, I had the "basic colorfulness" preset (in color balance rgb) saved as my own auto-applied version and when darktable 4.0 was released the original was renamed (because it now uses a legacy implementation). But there have been occasions where default presets were dropped entirely.

The overhead of creating a new preset is not an issue for me and I prefer it that way (so I can easily see when my preset has diverged from the system preset).

**Comment by Nilvus** [comment]
Seems that we can close this one? @paolobenve, is it ok, regarding @elstoc answer?
