### ISSUE TITLE
Possible corruption of image-tags when using different library.db

### ISSUE THREAD

**Issue by reitger** [darktable-org/darktable#12378]
I think there is a possible problem with image tagging und using different library.db files.
As the tags are stored in data.db and the location of it cannot be changed, it is used together with whatever library.db you specify.
By using different library.db files you can easily corrupt your tags.
Asume you have 2 PCs with darktable and you want to take your library to the other pc whatever for.
Or 2 accounts on one PC sharing a library.db

PC1: data.db, libA/library.db
data.db.tags 
ID name      
1  aaa       
2  bbb       

library.db.tagged_images
imgid tagid
img1a 1
img2a 2

PC2: data.db, libB/library.db
data.db.tags 
ID name      
1  CCCC       
2  DDDD      

library.db.tagged_images
imgid tagid
img1b 1
img2b 2

now if you use libA/library.db on PC2 (copy/network share...)
img1a has tag CCCC instead of aaa
img2a has tag DDDD instead of bbb

So wouldn't it make sense to be able to have data.db and library.db in the same location to asure consistence between the two databases?
This aplies to geo-location-information too, I presume.

**Comment by MStraeten** [comment]
You're messing up databases - then the result might be corrupt. 
data.db is intentionally interchangeable, library.db isnt because it contains file system specific data.
So to be able to reuse one data.db on several computers then it doesn't make sense to integrate that into the library.db. 
If you want to edit tags once (e.g. to correct typos) the current implementation supports that. You can't have both: using tags by reference and by value. Both approaches have their positive and negative aspects...

**Comment by parafin** [comment]
Actually there is a problem, see #11171, so maybe this is just a duplicate?

**Comment by elstoc** [comment]
Yes I think this is just another side-effect of having an integer foreign key constraint that spans the two databases (and therefore means they can't really be refreshed independently). Either the tag dictionary needs to be moved into the library db or it needs to be keyed on the tag name rather than an integer sequence number and just act as a convenience lookup to save typing.

**Comment by gi-man** [comment]
I leverage the xmp and look for updated xmp files on startup to work around this issue. I have a shared drive location for my images and i can access them via fedora or windows. You have to maintain both instances on darktable to be the same release or master. The second thing is that you have to remember to Add to library on both systems to keep the files/tags in sync.

**Comment by reitger** [comment]
further comments see [https://github.com/darktable-org/darktable/issues/11171#issuecomment-1225858569]
