### ISSUE TITLE
Load more photos during full screen

### ISSUE THREAD

**Issue by Kainkun** [darktable-org/darktable#12409]
**Is your feature request related to a problem? Please describe.**
When I'm rating photos in fullscreen with arrow keys and numbers, every time I go to the next photo, it takes a second to load so I cant quickly rate photos.

**Describe the solution you'd like**
Have a setting that automatically pre-loads the next few photos (maybe a few previous photos too?) while in full screen.

**Alternatives**
Right now, I just hit forward several times and backward the same amount of times to "pre-load" images to rate quickly but it's still slow and tedious.

**Comment by Nilvus** [comment]
See #5171

**Comment by wpferguson** [comment]
darktable is already trying to generate the next image before you move to it.  The problem is that it takes 1-2 seconds to generate the image.  If you are on an image, wait a couple of seconds and move to the next one.  There wont be a wait.

The only way I know of to go through full size previews as fast as you want is to generate the image cache before you start either using darktable-generate-cache or a lua script that runs on import and generates the specified cache sizes you need.

**Comment by Kainkun** [comment]
Thanks @wpferguson do you know how to run darktable-generate-cache ? Is there a way to open darktable's CLI or is it something i somehow do from command prompt?

**Comment by Nilvus** [comment]
@Kainkun: just search darktable-generate-cache on the manual. You will have all infos. Launch is from command prompt (it's a script).

**Comment by victoryforce** [comment]
@Kainkun See https://docs.darktable.org/usermanual/4.0/en/special-topics/program-invocation/darktable-generate-cache/
