### ISSUE TITLE
Crash when adjusting masking of tone-eq

### ISSUE THREAD

**Issue by apostel338** [darktable-org/darktable#12430]
I get DT to crash reliably when adjusting the mask of tone-eq. I don't know if it's exclusively happening with these settings, I've just not found another way to reproduce yet.

Sometimes it crashes after a few seconds, somtimes it takes quite a while.

https://user-images.githubusercontent.com/96216629/188289081-88fb241d-cd39-4756-988e-8b2155a6b4f2.mp4

As you can see it's crashing without any message. Log from `AppData\Local\Microsoft\Windows\INetCache\darktable`:
[01.txt](https://github.com/darktable-org/darktable/files/9483460/01.txt)

Besides the lates nightly builds, I've got back to these versions while testing:
```
4.1.0+123~g51460ce3e
4.1.0+177~g8e7e79817
4.1.0+215~gab7e37433
```

215 is the first one to crash without message.

177 offers this error:
![177](https://user-images.githubusercontent.com/96216629/188289092-968548ff-8240-4ef5-b3c7-7bf888294f59.png)
[4.1.0-177 - darktable_bt_13GTR1.txt](https://github.com/darktable-org/darktable/files/9483461/4.1.0-177.-.darktable_bt_13GTR1.txt)

123 I've not been able to crash yet.

The crash happens with openCL on and off. Also with blank config folder.

System info:
[DxDiag.txt](https://github.com/darktable-org/darktable/files/9483502/DxDiag.txt)

**Comment by gi-man** [comment]
First, please try to use the github template to provide all the info. 

Second, I think this is likely the same cache issue(https://github.com/darktable-org/darktable/issues/12336) that was fixed a week ago with https://github.com/darktable-org/darktable/pull/12393

You can use the windows nightly builds to test the current master. https://github.com/darktable-org/darktable/actions/runs/2986265782 (today) or use the packaging instructions to build from git.

**Comment by gi-man** [comment]
I switched to windows and built. I was able to produce a crash on windows 11.

Current master 4.1.0+285~ga041e1991  +  PR 12427 (I wanted to build for the PR not for this issue)

Steps to reproduce:
1. Go to darktable
2. Go to Tone Equalizer
3. Adjust the masking filter diffusion to 3 (I could not get a crash on 1 or 2).
4. Click and slow drag the mask exposure compensation slide.

I tried doing fast clicks and I could not get it to crash. It seems that during the slow drag of the slide, it tries to determine multiple masks consecutive. 

@jenshannoschwalm I think this could be another cache issue.

**Comment by jenshannoschwalm** [comment]
I already spent some time on this issue this morning (because of waking up :-) and can confirm some crashing. 

Don't know yet what the exact problem is, i have a version here with much more debug output and on first sight it seems that we get a new cacheline allocated immediately before the crash.

The crash does not happen to be related to a double free or alike nevertheless, it seems to be somewhere in the pixelpipe ???

> it tries to determine multiple masks consecutive

Hmm, what do you mean here?

**Comment by apostel338** [comment]
Might be obsolete but

> First, please try to use the github template to provide all the info.
> 
> Second, I think this is likely the same cache issue(#12336) that was fixed a week ago with #12393

I'm sorry, I thought the video would show enough. It starts directly after entering the darkroom, so no steps are missing. I always think a picture tells a thousand words.

> You can use the windows nightly builds to test the current master. https://github.com/darktable-org/darktable/actions/runs/2986265782 (today) or use the packaging instructions to build from git.

The video shows `4.1.0+283~g5cca9d64b`.

> _**Besides the latest nightly builds,** I've got back to these versions while testing:_

I just highlighted 123, 177 and 215 because they differ in their behaviour.

If I can offer any more information or testing, please let me know.

**Comment by jenshannoschwalm** [comment]
Your report had enough information for me 😎

**Comment by gi-man** [comment]
> > it tries to determine multiple masks consecutive
> 
> Hmm, what do you mean here?

I just tried it in fedora 36 kde x11 on master and I was able to get it to crash too. 

What I mean is as you slide the "mask exposure compensation" in the tone equalizer module, the system redraws the histogram, preview and such because it is determining the exposure mask to use. Each time you slide and slowly "stop" sliding, it tries to do a new mask very quickly.

**Comment by jenshannoschwalm** [comment]
OK, I investigated further and I think I finally understand what goes wrong if there is repeated fire on one of the pixel pipes if memory restraints are significant.
PR following pretty soon, until then I suggest to use large resources setting...

**Comment by Mark-64** [comment]
@jenshannoschwalm 
Testing on Windows, where I can more reliably reproduce the fault, I get the crash also with resources set to large.
It gives me this message:
`Magick: caught exception 0xC0000005 "Access violation"...Segmentation fault
`
What worries me is that it is the same message of other crashes which I get randomly in several places on master recently

**Comment by jenshannoschwalm** [comment]
Yes, i did a lot of investigating the last days and i think i understand what's happening if putting the pipeline cache under stress like pressing a slider and force reprocessing by changing value.
That might lead to a situation where remaining parts of the pipeline still make use of cache lines that are currently cleared.

Until now we had - rarely - the situation where we might have wrong cache data, now we sometimes have a crash due to the cacheline deallocated. Working on this here - seems to be good now but give me some days again ...

**Comment by AxelG-DE** [comment]
I only fly over the things written here, sorry for that, because I am in a hurry.

@jenshannoschwalm I have the same crash. If you need me to test (and you know my setup :) ) you find me next week again on #darktable being at your service :)

**Comment by jenshannoschwalm** [comment]
I will ping you 👍 though no IRC any more for me.

**Comment by jenshannoschwalm** [comment]
I would really appreciate if you could all check the pr and try to get dt crashing.
Please use  - d dev - d verbose options for reports.

**Comment by AxelG-DE** [comment]
SIR @jenshannoschwalm I said I will test this week, how dare you to push before me testing it...
:-))))))

just wanna make you miss IRC.

I am late to the party but I also confirm, the issue is gone :smile:
