### ISSUE TITLE
Cannot open some png file ??

### ISSUE THREAD

**Issue by jadupl2** [darktable-org/darktable#12483]
Running Line Ubuntu 20.04, using the Flatpak from flathub, when I transfer my files from my Iphone to Linux everything is ok. **The file I have attached can be read and display by every program I tried,( Image viewer, Xnview, ...) But not in darktable** I got the skull image.

Can you Help Me ?
Thank you in advance

![2022_08_29_09_19_42](https://user-images.githubusercontent.com/6374153/189920204-922c617e-92a5-4cb8-9ede-f4c3cee52ecc.png)
![darktable_error](https://user-images.githubusercontent.com/6374153/189921122-60b67b4e-d564-42da-a242-bdfa12e5ed2f.png)

**Comment by kmilos** [comment]
This is not a PNG file.

Rename the extension to ".jpg".

Unfortunately, iPhones have been known to create/transfer images w/ wrong file extensions... (I know no phone that creates a PNG btw...)

**Comment by jadupl2** [comment]
Every time on an Iphone when you do a print screen it produces a PNG and
you cannot change this behavior.
The PNG attached was created from a print screen on an Iphone.

But you were right I changed the extension from PNG to JPG and it worked !!!
Thank you very Much

**Comment by kmilos** [comment]
Ah, yes, screenshots... In any case, this one is definitely a JPEG.

@jadupl2 Please close the the issue.

**Comment by jadupl2** [comment]
Thank you your solution worked

**Comment by pcanning** [comment]
Does darktable blindly use the extension to identify the file type?  On my debian/testing system running the file command on a JPEG file that has been renamed to xxx.png correctly identifies the file as a JPEG file.  It appears that the file command uses libmagic to do the work.  Would it make sense for darktable to use libmagic to help identify file types, either instead of the suffix or to produce a warning that the suffix of the filename is misleading/wrong?

**Comment by kmilos** [comment]
> Does darktable blindly use the extension to identify the file type?

Indeed. There is certainly room to improve on this, and patches are welcome.

**Comment by pcanning** [comment]
I've recently retired after a 40+ year career as a software engineer (primarily system software, but not GUI software, on both Unix and Windows) and I've been thinking about trying to contribute to the digikam and/or darktable software projects.  This seems like a good possibility for me to contribute.  I have not yet looked at the darktable code or tried building.  I can start reading the developers wiki and setting up a development environment, but can someone give me a pointer to the area(s) of the code responsible for identifying file types?

Do folks have a preference for one of the following options
1. darktable should use libmagic to identify file types instead of using the suffix of the filename 
2. darktable should use libmagic to identify file types, and fall back to the suffix of the filename if libmagic doesn't recognize the file
3. darktable should use suffix of the filename to identify file types and fall back to libmagic if the suffix isn't recognized (it doesn't seem like this would address the case describe in this issue)
4. darktable should produce a warning if the filetype based on lib magic is different from the file type based on the suffix of the filename (this probably requires some GUI work which isn't my area of expertise)
or prefer some other option?

**Comment by jadupl2** [comment]
Hi,

I would like option 2 :
'darktable should use libmagic to identify file types, and fall back to the
suffix of the filename if libmagic doesn't recognize the file'

I would put this as an option in the import module, that way we could
change the extension right away without changing anything else.

P.S. The possibility of renaming a file in Darktable would be appreciated.

Thank you, for your time and effort you put in making Darktable an even
more excellent product.
