### ISSUE TITLE
Refresh image folders to pick up new images

### ISSUE THREAD

**Issue by parisni** [darktable-org/darktable#12490]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I add new images in a folder and darktable has no way to refresh that folder to consider those images.

**Describe the solution you'd like**
I d'like a refresh folder button.

**Alternatives**
Automatically refresh folders

**Comment by elstoc** [comment]
You don't like re-importing the folder?

**Comment by parisni** [comment]
Well this lead to first remove the collection and recreate it. That's both time consuming, error prone and not intuitive

**Comment by elstoc** [comment]
Nope you don't need to do anything apart from import the folder again. There is an option to "select only new pictures" though I've not had any issues with re-importing everything - it won't overwrite your edits since anything in your local database is already reflected in the xmp files.

**Comment by parisni** [comment]
Thanks, this is the feature I was looking for. I still feel it is hidden for new users. Right click / refresh on collection is the first instinctive move anyone try IMHO

**Comment by elstoc** [comment]
The concept is that we import _images_ into darktable, not folders/directories. The ability to import all images in a folder at once is more a convenience thing, with collections being a way to filter those images you chose to import.

To "refresh" a folder we'd have to try to remember something about how it was originally imported (like whether jpegs were ignored, for example) and we don't store that sort of data at a folder level.

**Comment by spaceChRiS** [comment]
There's one drawback of the re-import: When using the input filters lua script to “prefer raw over jpeg” the import settings have to include the jpegs (this is a consequence from the re-done import dialog). A re-import button that remembers the import settings per folder would be very handy to not flood the library with duplicate jpeg images accidentally. And it would save a couple of clicks and searching the folder in the file dialog. Instead of a button, probably an option in the right-click context menu of film rolls would make more sense, in particular because it would remove the necessity to deal with what the button does when no film roll is selected.

**Comment by elstoc** [comment]
> A re-import button that remembers the import settings per folder would be very handy

That could get messy a few years down the line - I'm not sure I'd want to go down that road. Also what if you have done multiple imports from that folder with different settings?
