### ISSUE TITLE
Transform face tags regions when exporting.

### ISSUE THREAD

**Issue by pitbuster** [darktable-org/darktable#12589]
I do face tags with Digikam, but when exporting the face areas, Darktable just copies them to the exported file, without doing any transform. In cases where there is cropping or rotation/perspective corrections, this will mean that regions will be off and look weird in software that shows them ([pigallery2](https://github.com/bpatrik/pigallery2) in my case).

**Comment by dterrahe** [comment]
You might want to include an example tag in your submission, because there may not be many developers who know enough about digikam to create one themselves just to figure out what you are talking about. If you want someone to spend time on solving a problem that they themselves don't, and are unlikely to ever, have, you might want to "sell" it a little...

**Comment by raymondjohnson** [comment]
@pitbuster, I understand this problem exactly! I'm a bit shocked that someone has the exact same issue I do with the exact same applications and workflow I'm trying to use.

The problem is more widespread than you describe: I thought that if I cropped the images first in Digikam, the face tags would be dealt with correctly, but no luck. The tags are there but not where they should be when I crop. Given that Digikam has face-tagging abilities, it seems that it would get this fix first. For images I edit in Darktable, I think my workaround might be to re-edit the exported jpegs to fix any face tags of transformed and cropped images. It would be wonderful if Darktable fixed this, but I think Step 1 has to be to implement face tagging, and Step 2 can be making sure it works in this special (but annoying) case.

**Comment by pitbuster** [comment]
@dterrahe I will edit the original description to better explain the issue, the tags involved and mention other software/ecosystem that may show the issue (since I think they are standard tags). Thanks for the feedback.
