### ISSUE TITLE
Another ways to set resolution limits on export

### ISSUE THREAD

**Issue by ArmanHayots** [darktable-org/darktable#12592]
As example, VK only allows to upload photos, which have only width+height < 15 000. 
Some sites requiring photos not to be bigger than 2MPix (1920x1080, 1400x1400, 1660x1200 etc), and some of them just prohibits files by their size. 

So it's good if there will be ability to set not only max width or max height, but also max width+height, max width*height and just max size.

**Comment by vsz1lu** [comment]
Your problem is similar as entry for photography salons. But:

The maximum size is always what u set.

You have a 6000×4000px base image.
Your export set and output:
w: 3000; h: 0 -> **3000**×2000
w: 0; h: 1000 -> 1500×**1000**
w: 4000; h: 2000 -> 3000×**2000**
w: 1500; h: 1500 -> **1500**×1000

Simple set the the w and h 7500-7500, if you don't want to break the 15000px w+h rule. (Yes, you can't export 14 000×1 000px image, but why for social media?)

**Comment by ArmanHayots** [comment]
> Yes, you can't export 14 000×1 000px image, but why for social media?

Panoramas.

**Comment by ArmanHayots** [comment]
Still the same.

**Comment by ArmanHayots** [comment]
Still the same.

**Comment by victoryforce** [comment]
Do you expect that it will not be the same?
