### ISSUE TITLE
Any desire to change the highlights reconstruction module user interface [RFC]

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#12606]
**Is your feature request related to a problem? Please describe.**
We have new highlights reconstruction algorithms available giving better results than current default.

For me there are some questions i would like feedback before doing any pr.

Currently we switch on highlights reconstruction with "clip highlights" per default for raw images. I don't think this is good as of bad quality loosing lots of details. I propose either one of these
1. **module is disabled per default** this means the user would have to define a preset most likely.
2. **inpaint opposed per default** most likely a better result for most images

Do we want the order of algorithms in the menu to stay in order "as time of implementation" or per usability (for all sensors)?
1. **new suggested order** inpaint opposed -> reconstruct in LCh -> clip highlights -> segmentation based -> reconstruct color -> laplacian
2. **keep as is**

For me the usability of "reconstruct color" is very low. It creates artefacts you can't control and if it works without artefacts it creates an output that is very close to "opposed mean".
1. **remove reconstruct color from menu**
2. **keep as is**

**Comment by parafin** [comment]
Some highlights reconstruction method should be enabled by default, having it off is not a good option.

**Comment by TurboGit** [comment]
I would vote for "inpaint opposed per default".

Changing order, why not but this means we must be very careful to properly upgrade old edits. If this is done the order you propose seems ok to me.

Yes, I would hide "reconstruct color", to me it has rarely given proper result and often I get some banding on the images.

**Comment by ralfbrown** [comment]
> Yes, I would hide "reconstruct color", to me it has rarely given proper result and often I get some banding on the images.

Keep in mind that there will need to be code to unhide it for old edits using that method.  I personally don't use it either, as I've had the same experience of it creating artifacts all over.

**Comment by jenshannoschwalm** [comment]
So i take this as a go for
1. switch to "inpaint opposed" as default for all types of sensors.
2. hide "reconstruct color" in the menu as long as the edit history doesn't use it
3. use the order in menu as described above

**Comment by todd-prior** [comment]
This is funny I just posted today after rewatching one of AP's videos where he comments that clip highlights and LCH and color reconstruct are not compatible with CAT derived WB.... min 25 ish through 27:30. At that time the only option then in the module would have been guided Laplacian which he has gone on to show works best as a means to restore gradients and then finish things with filmic reconstruction.... so my comment was for sure if people are selecting the modern workflow in the preferences to me it makes sense that this will tweak what is set as the default for HLR as well.....

https://www.youtube.com/watch?v=F3CeJ1F4wV8&t=1670s

Many new users with the current defaults will be presented with those blues and other artifacts in highlights and blame filmic and or the software but just changing the approach or using one of the other new methods instead of the older ones really makes this happen a lot less often I woiuld bet..

  https://discuss.pixls.us/t/struggling-with-modern-white-balance-in-darktable/32317/31?u=priort

**Comment by Nilvus** [comment]
@jenshannoschwalm: I didn't had time to test your inpaint opposed PR before merging. After some testing since, this is definitely the best highlight recovery choice (by default). Guided laplacian is awesome but quite complex for a lot of users and really slow (need high resources so to use it comfortably).

So I'm definitely for your 3 "as a go for". And just again a big thank you for your work and improvements on darktable (that part and others).

**Comment by yungsyu99** [comment]
> **Is your feature request related to a problem? Please describe.** We have new highlights reconstruction algorithms available giving better results than current default.
> 
> For me there are some questions i would like feedback before doing any pr.
> 
> Currently we switch on highlights reconstruction with "clip highlights" per default for raw images. I don't think this is good as of bad quality loosing lots of details. I propose either one of these
> 
> 1. **module is disabled per default** this means the user would have to define a preset most likely.
> 2. **inpaint opposed per default** most likely a better result for most images
> 
> Do we want the order of algorithms in the menu to stay in order "as time of implementation" or per usability (for all sensors)?
> 
> 1. **new suggested order** inpaint opposed -> reconstruct in LCh -> clip highlights -> segmentation based -> reconstruct color -> laplacian
> 2. **keep as is**
> 
> For me the usability of "reconstruct color" is very low. It creates artefacts you can't control and if it works without artefacts it creates an output that is very close to "opposed mean".
> 
> 1. **remove reconstruct color from menu**
> 2. **keep as is**

**Comment by yungsyu99** [comment]
> **Is your feature request related to a problem? Please describe.** We have new highlights reconstruction algorithms available giving better results than current default.
> 
> For me there are some questions i would like feedback before doing any pr.
> 
> Currently we switch on highlights reconstruction with "clip highlights" per default for raw images. I don't think this is good as of bad quality loosing lots of details. I propose either one of these
> 
> 1. **module is disabled per default** this means the user would have to define a preset most likely.
> 2. **inpaint opposed per default** most likely a better result for most images
> 
> Do we want the order of algorithms in the menu to stay in order "as time of implementation" or per usability (for all sensors)?
> 
> 1. **new suggested order** inpaint opposed -> reconstruct in LCh -> clip highlights -> segmentation based -> reconstruct color -> laplacian
> 2. **keep as is**
> 
> For me the usability of "reconstruct color" is very low. It creates artefacts you can't control and if it works without artefacts it creates an output that is very close to "opposed mean".
> 
> 1. **remove reconstruct color from menu**
> 2. **keep as is**

Hi， I am a professional photographer, the darktable
 Is awesome ! The demosaic and denoise methods are comparable with Adobe Lightroom! Thanks for the nice work!  But, there is an annoying problem, in some cases, all the highlight recovery methods in darktable  cannot recover the natural highlight. The image after processing is kind of unnatural. At the same time, Lightroom can recover natural highlight details. Would you try to design a better highlight recovery method? See more details : https://discuss.pixls.us/t/extreme-highlight-recovery-in-darktable/28668
