### ISSUE TITLE
quick access auto tune levels filmic rgb

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#12665]
**Is your feature request related to a problem? Please describe.**
In shortcuts, it is possible to set a shortcut for filmic rgb auto tune levels. However, it is not possible to add auto tune levels to the quick access menu.

**Describe the solution you'd like**
Ability to add filmic rgb auto tune levels in quick access menu.

**Additional context**
dt 4.0.1
mint cinnamon 21

**Comment by dterrahe** [comment]
Separate buttons are not supported in quick access, because usually they are small so you'd want to be able to arrange a few of them on the same line, which would require extra configuration (reorderable?), which would make the whole quick access panel more complex, when it was meant as a very simple tool for beginners. Someone might at some point find the motivation to "fix" that, but in these areas there's the risk of significant blowback when you don't get it "right", which doesn't help.

At some point, rgb auto tune levels used to be a "fake" combo (with one unselectable entry serving as the label and the button being similar to color-pickers). That would have made it a candidate for quick access, but this was "fixed".

**Comment by SoupyGit** [comment]
I guess I don't understand the problem. Exposure, Filmic White and Black Relative sliders and Color Balance RGB White Fulcrum all have their auto buttons in quick access, next to the sliders. I'm not asking for the layout in quick access to be rearranged - that wouldn't be necessary. If a user added this, like adding any other parameter, it would simply be the addition of one extra line - the exact same one that is currently at the bottom of the filmic 'scene' tab.

Since White and Black Relative auto buttons can be added to quick access this is not high priority - but having auto tune levels would be superior, for it is one less click, which adds up to a lot on many images.

**Comment by dterrahe** [comment]
Those are different types of buttons; they are "quads". You can't add them to quick access without their accompanying sliders/combos. For what you want to work, you would have to lobby with @Nilvus to partially revert #11372. I give it little chance...

**Comment by wpferguson** [comment]
@SoupyGit I've already managed to script this so that you can select a set of images from lighttable, then cycle through them automatically applying filmicrgb auto tune levels and colorbalancergb white fulcrum.  I'm still working on making it robust.

**Comment by Nilvus** [comment]
> For what you want to work, you would have to lobby with @Nilvus to partially revert #11372. I give it little chance...

Are you sure? Having such thing on quick access panel for those who use it is more important than having hover effect on the picker. See  #12680
