### ISSUE TITLE
unwanted scroll of module making it unusable

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#12686]
On an HD screen doing a demonstration tonight I stumbled on a bug probably due to the new scrolling of module introduced recently.

The scrolling was making the module unusable, it was on an HD screen, and scrolling was activated when I was flying over the blend section. I have been able to reproduce this consistently following the procedure below:

To reproduce:
- On the RVB curve module
- Select drawn & parametric blend
- Scroll down the panel to be able to show all controls of the blend section and make sure the header of the module is not visible anymore.
- Fly over the parametric blend canal (g R V B ..)
- See the module scroll down to show the header on top... making the blend section outside of the panel (I was on a small HD screen).

I think this is due to #12637, @dterrahe sounds like this is for you :)

**Comment by dterrahe** [comment]
When the mouse hovers over a notebook tab, a resize is triggered (because the font for the tab temporarily changes) and propagated up the chain. The module cannot distinguish this resize from a resize triggered by an expanding section, so will try to make sure it fits on the screen completely and may move _up_. However I tried to prevent it from moving _down_, but it still seems to do that, but only when "scroll processing modules to the top when expanded" is on. I will look for a more complete fix or workaround.

Thanks for reporting.

**Comment by TurboGit** [comment]
BTW, this does not happen only when flying over the channel tab but also when dragging the controls on the parametric masks channels.

**Comment by Jiyone** [comment]
It happens to me too and it's very annoying 😐

**Comment by dterrahe** [comment]
Yeah, it can be rough. Thanks for volunteering to test master!

Next time, if the suffering gets too much, you could consider reporting it yourself instead of waiting for someone else. I'm trying to be responsive to bug reports and a <1d turnaround, partly due to time zones, isn't so bad of you take into account that the support is free.

Thanks again!
