### ISSUE TITLE
[shortcuts] when a module has 2 or more instances, the shortcut could rotatively open the various instances

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12695]
Dt 4.0.x

When a module has various instances and a shortcut is defined for opening/focusing it, the shortcut only opens the last generated instance of the module.

Example: `e` is the shortcut for the exposure module. If this module has 3 instances, hitting `e` opens/closes the last instance of it. The other instances aren't accessible via shortcut.

My proposal, applied to the example:

- a first hit of `e` opens the third instance, as now
- a second hit closes the opened one and simultaneously open the second instance
- a third hit closes the opened one and simultaneously open the first instance
- a fourth hit closes the first instance
- a fifth hit opens again the last instance
- etc.

**Comment by dterrahe** [comment]
In the shortcut definition you can choose which instance the shortcut should apply to. So you could have several shortcuts (e, double-press e, triple-press e) that could refer to different instances. There are some settings in preferences that determine whether the "preferred" instance depends on currently focused/enabled/expanded state of a module.

It seems like you want some combination of those two things, i.e. a numbered instance that is relative to the currently focused instance. I'm saying "focused" rather than "expanded" (which is really what you seem to be describing) because multiple instances can be expanded at the same time (by holding shift or change the relevant preference)., in which case it would be unclear what relative instance a shortcut would refer to. Also, what happens if none of the instances of the module your shortcut refers to is focused? Should we pick the first or last?

In theory I could add the options _next_ and _previous_ to the options _preferred_, 1..9 and -1..-9 that currently exist for the _instance_ setting of a shortcut. If used for anything else than a shortcut with element _focus_, you could see weird effects. For example when you set up a shortcut for a slider with instance _next_ then every time you scroll the mouse wheel it would move the slider in the next module, which would make that module focused, which would make the next scroll go to the _next_ module's slider, so you'd end up cycling through the modules as well as slightly moving the slider in each.

**Comment by dterrahe** [comment]
Without more input from you describing what it is you would actually _want_ there's not much I can do with this. Please reopen if you still feel this could/should be improved and provide concrete suggestions that do not conflict with current functionality. Thank you!

**Comment by paolobenve** [comment]
@dterrahe thank you for your explication. Forget the work "focus", my request was about showing/opening (I think it's the same thing) a module in darktable mode. I tried to modify the original post accordingly. Thank you for your patience!

Let me ask you something I still cannot understand:

> the options preferred, 1..9 and -1..-9

Actually I see +3..+9 and -3..-9. Why don't I see +1 +2 -1 -2? and what do those number mean? +2 = next + next?

Perhaps adding the _previous_/_next_ values to the _instance_ field in the shortcut definition could be the answer to my request. But it would require something quite difficult from the user.

Rather, I'm thinking on a default behaviour: if the _x_ shortcut shows/hides a module, when the module has more than 1 instance, its next activation (slower that the speed that makes it a double shortcut) shows the next instance of it, and so on.

This looks to me a simple enhancement which should create problems.

> Please reopen if you still feel etc.

How do I reopen it? I cannot see any way to do it.

**Comment by paolobenve** [comment]
ok.

What about simpy adding the _next_/_previous_ values to the instances drop down values?
