### ISSUE TITLE
Height issue on collections module list after going back from darkroom view

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#12713]
**Describe the bug/issue**

On actual master, and since few days, when I try to 'ctrl+scroll', I can do it to increase collections list when I stay in lighttable view.  But if I open an image on darkroom then go back to lighttable, ctrl+scroll on collections list do not work anymore.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Ctrl+scroll on collections list after first darktable launch and see that increase list height works
2. Open an image in darkroom view
3. Go back on lighttable and do again first step
4. See that height doesn't change but a number change when doing ctrl+scroll on top message info as thumbnail below:

![image](https://user-images.githubusercontent.com/45535283/198143799-dba2bd81-374f-44c5-a1b3-de730ce2d571.png)

**Expected behavior**

Ctrl+scroll should always work. And no "number" needed to display on top view.

**Which commit introduced the error**

I have few time to do that actually. If needed, I could try to do one in about a week (at least).

**Platform**

* darktable version : actual master
* OS                :  Debian Sid

**Comment by dterrahe** [comment]
There seems to be slightly different behavior depending on which property the collections module is showing. The single number (which #12718 attempts to clarify, which I still think is useful) has been there for a long time, so it confused me that you highlighted it as a regression, but it doesn't always seem to show (for example sometimes with filename, which I never use).

Does switching to a different property restore the correct behavior for you? Just to help me understand which interaction in this module is interfering with the correct behavior of the scroll wrapper.

In the tag module I haven't been able to reproduce incorrect behavior yet. Any further detail you could provide would be helpful.

**Comment by Nilvus** [comment]
> There seems to be slightly different behavior depending on which property the collections module is showing. The single number (which #12718 attempts to clarify, which I still think is useful) has been there for a long time, so it confused me that you highlighted it as a regression, but it doesn't always seem to show (for example sometimes with filename, which I never use).

I just never notice the number (and rarely use ctrl+scroll) and I don't say that is a regression. I just notice the number when Ctrl+scroll was not working, so thought that number is displayed without height increased. Just that. Of course, your PR remains useful.

> Does switching to a different property restore the correct behavior for you? Just to help me understand which interaction in this module is interfering with the correct behavior of the scroll wrapper.

Yes, switching to another property in collections module restore the correct behavior (and last size state). To precise, I want to set (and keep it even after darktable restart) a more important height. And given your feedback, that seems to be some sort of missing reset/restore state.

> In the tag module I haven't been able to reproduce incorrect behavior yet. Any further detail you could provide would be helpful.

Forget tag module by now, I just test it quickly but forgot to expand tags to allow height increasing. Just tested again and works correctly. Sorry for that but It was late when I check and posted that issue.

**Comment by dterrahe** [comment]
Something strange going on. The only property that I can "reproduce" some issue with, is filename (not coincidentally maybe; this is the longest list). When I switch to it, everything still works fine, but for some reason the size toast doesn't get shown. Until after a while (15 seconds, whatever) it _is_ shown again. And once, but I haven't managed to reproduce it a second time, I _could_ reduce the size of the list, but _not_ increase it above the "minimum" level.

I have no idea what's going on. I'll play around with it until I _do_ get an idea. If you have any suggestions or easy ways to reproduce (would be especially useful with empty database, so I can recreate exactly here, but that will be hard given that it seems the problem occurs with long lists?).

> a more important height. And given your feedback, that seems to be some sort of missing reset/restore state.

A greater height (more lines)?  I didn't intend to suggest there was a problem with reset/restore. I'm not aware of one.

**Comment by Nilvus** [comment]
It's indeed really strange. I have this with filmroll. See video I just made below.
I began the video after launching darktable on state you see. As you can see I set list height to 18. I go then to darkroom and when going back to lighttable, collections list height had been reduced after going back from darkroom view. I do not have so height set to 18 (toast number displayed) and I can't restore height list directly (toast number change when using ctrl+scroll but the height of the list do not change). This works then after changing collection property (here I switch to folder then back to filmroll and height is the one I set previously and I can change the height again with ctrl+scroll. I talk about some reset/restore state just because when going back from darkroom, I do not have the height I had set previously but this height is restored after switching property in collections module.

[Capture vidéo du 2022-10-29 19-01-57.webm](https://user-images.githubusercontent.com/45535283/198844237-5c178da2-5d45-433b-a3bb-35811973ef14.webm)

**Comment by Nilvus** [comment]
I change title here. @dterrahe: I don't know if my last comment and video help but with more tests, it's more about collections module list height issue, not ctrl+scroll. Seems that if height is higher than default one, going to darkroom then going back on lighttable reset collections module list height to default darktable one, not height manually set. To restore height manually set, this need to change filter property on that module or click on reset icon.

**Comment by AlicVB** [comment]
I experience a quite similar issue, thought not exactly the same...
For me, the size on startup is not good anymore, and you need to go to darkroom and back to lighttable in order to get it right...

I've found that the "first" culprit seems PR #12637 but : 
- before this PR : everything works well
- after this PR : it's even worse than in master : the scrolledwindow never get its right size... so I think there has been some other code in between than partially fix the issue...

That said, I've looked at the changes in this PR, and I've not found anything obviously wrong... @dterrahe : maybe that will help you (or not)...

I continue my test, in order to found the commit that mitigate the issue...

**Comment by dterrahe** [comment]
This issue (and #12885) is somewhat hard for me to experiment with because it (mostly?) seems to happen with large collections and I don't have mine available on my development machine, so I haven't managed to replicate there and therefore can't verify if possible solutions work. There seems to be an interaction here between the recent module scrolling code (which is triggered by the scrollable window within the module resizing) and the scrollable window resizing code (which is triggered by the window _within_ the scrollable window being _redrawn_). When I implemented _dt_ui_scroll_wrap_, it seemed reasonable that a resize of the content would trigger a "size-allocate" event and that this could be used to resize the scrolled window, but this did not reliably happen, so instead I do the resizing in the "draw" event (with the drawback that this happens much more frequently). Now it turns out this is also not reliable.

I suspect that there are some optimisations within gtk that skip calling redraw/resize events when data is late-loaded via a GtkTreeModelFilter. (I have to say the lifetime management of the `d->treefilter` in collect.c is "confusing"). So more workarounds/bandaids to make our response to them more reliable are required.

I would be really helpful if people were willing to test wild ideas I might come up with that I can't test (as mentioned above) on my side. One idea would be to create even more overhead by first completing a full redraw before doing a resize (which would trigger another full redraw). This might be possible by changing 

https://github.com/darktable-org/darktable/blob/8c31abfd716b8dc6a0c7a07be6d6f195298d679c/src/gui/gtk.c#L3173
to
` g_signal_connect_after(G_OBJECT(w), "draw", G_CALLBACK(_scroll_wrap_resize), config_str); `

If anyone could report back if that at all changes/improves the situation on their side, I would be grateful.
