### ISSUE TITLE
[jxl export] exported jxl image is different from the image in darktable

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12729]
I compiled darktable from master with a jxl compiled today from branch v0.7.x (up to date remote repository).

The exported image is notably different from the image I see in darktable.

The screenshot of the image in dt (the notification on the top right corner are not in the image):

![InDarktable](https://user-images.githubusercontent.com/1417508/198779043-ed7de1f4-fa41-4586-a15e-588821b62eac.png)

The screenshot of the exported jxl with default settings, as chrome shows it:

![jxlInChrome](https://user-images.githubusercontent.com/1417508/198778997-5f82cf4b-8f70-4481-a5fc-89daeb0cd503.png)

gthumb shows the image identical as chrome. The gthumb I have installed uses a jxl of date 2022-04-26 (release date of jxl 0.7). I don't know what jxl is used by my chrome 102.0.5005.115

I needed, I can upload the original CR3 (I'm avoiding because of its big size and my slow network).

**Comment by kmilos** [comment]
One thing to keep in mind: there is no native JPEG XL import yet, so this is going through GraphicsMagick which might not be handling the color profile reliably. Have you tried (re)setting the input profile?

**Comment by paolobenve** [comment]
I didn't import the jxl, I exported from raw CR3

**Comment by kmilos** [comment]
I just installed the 4.1.0+681~g19825f35c nightly build on Windows (left) and compared to Chrome 106.0.5249.121 (right). 

Can't reproduce unfortunately.

![image](https://user-images.githubusercontent.com/4973094/199036261-b046c1fe-776b-4209-bb05-abe0bed97edd.png)

I had a clean config folder, just imported [an image](https://raw.pixls.us/getfile.php/3204/nice/Leica%20-%20Q2%20-%2014bit%20uncompressed%20(3:2).DNG), did no further processing, and exported to JXL with default settings.

Have you tried discussing your color management setup on discuss.pixls.us, there have been a few of related topics there?

**Comment by paolobenve** [comment]
> Have you tried discussing your color management setup 

Well, I don't have any issue with color management when exporting to jpg or webp... Is there any reason why I should have them exporting to jxl?

**Comment by kmilos** [comment]
> Is there any reason why I should have them exporting to jxl?

Not 100% sure to be honest, I (we) are still on the learning curve. JPEG XL is a very complicated codec - unless you do lossless (which also means integer bit depth), it doesn't store pixels in their original color space by default (you do have an option to force it though, but efficiency goes down...). Then it's up to viewers to interpret this correctly.

Also, you never specified your output profile settings, display profile settings, export module settings, what you did exactly, etc., so that's why I suggested the forum. GitHub should be ideally a place for _precise_ and _reproducible_ bug description, not for exploration/speculation IMHO...

Again, you mention

> 2022-04-26 (release date of jxl 0.7)

[The release date of libjxl 0.7.0 was 2022-09-21](https://github.com/libjxl/libjxl/releases). There was no release nor did 0.7 exist on 2022-04-26.

**Comment by cytrinox** [comment]
gthumb shows a small color chart icon on top if it properly detects an embedded color profile. I've built gthumb few days ago from current master and it wasn't able to detect any color profiles in my jxl files. I assume support for NCX profiles (and/or icc profiles) embedded into jxl are not yet supported in gthumb.
You can try to specifiy the export color profile as sRGB in darktable, maybe this helps. But as I export my images usually in Linear Rec.2020, all my photos looks totally wrong hin gthumb.
