### ISSUE TITLE
lighttable: unwanted scroll

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#12730]
When the lighttable modules are expanded such that the panel has a scroll bar, expanding/collapsing a module causes the panel to scroll. Since I don't have the "scroll utility modules to the top when expanded" preference enabled, this is not wanted and means I always have to move my mouse and engage my brain to work out where the module has moved to.

darktable 4.1.0+678~ge99ae3751 on ArchLinux.

@dterrahe I guess this is one for you

https://user-images.githubusercontent.com/9555491/198828430-0f4334ff-d358-4a8e-9abd-f8d051f7d3ce.mp4

I would expect the module header to not move. _Perhaps_ it should scroll if the expanded module no longer fits within the panel, but not otherwise.

**Comment by dterrahe** [comment]
That is very strange. I've tried to reproduce here, but it definitely doesn't do that for me or it would have annoyed the hell out of me too! I can't seem to get OBS recording to work so can't prove it to you or use a video to work out together what might be different on your side :-/ As you say, only expanding a lib at the bottom (export for example) should scroll it up if it doesn't fit. For others the header should (and does, on my side) stay in the same place. Does this always malfunction like this for you are are there maybe moments (just after a restart?) where it temporarily works OK? Just trying to figure out some trigger...

But I did actually only now notice that there are different settings for "scroll-to-top" in lighttable (which was interpreted as libs) and darkroom (iops) which I broke in my changes (only the darkroom setting is used) so I'll submit a PR to restore that soon.

**Comment by elstoc** [comment]
Always happens for me on current master.

**Comment by dterrahe** [comment]
Actually, could it just be the bug I mentioned above, namely that for libs currently it looks at scroll-to-top for _darkroom_ modules? Do you have that switched on? Does switching it off help? If it does, I'm about to submit a fix for you.

tbh for _me_ scroll-to-top (either for libs or iops) is a suboptimal solution to the problem that you want to see the whole module when you expand it, which is why I implemented the "scroll when partially obscured" method in the first place. It scrolls the minimum needed to show everything, without always going to the top. But I understand people will have got the current method in their muscle memory and there is _also_ something to be said for always having you active module in the same spot.

**Comment by elstoc** [comment]
> Actually, could it just be the bug I mentioned above, namely that for libs currently it looks at scroll-to-top for darkroom modules? 

Yes you're right. I guess I can switch that off now with your new "make everything visible" change.

**Comment by dterrahe** [comment]
> Agreed

Still, _we_ may agree but others will still want their old way of life preserved. So thank you for reporting the regression I introduced!
