### ISSUE TITLE
Cant use any system keybindings in my DWM when Darktable window is active

### ISSUE THREAD

**Issue by VolkovIlia** [darktable-org/darktable#12737]
**Describe the bug/issue**

Cant use any system keybindings in my DWM when Darktable window is active

**Expected behavior**

use my system keybindings with `super` key

**Screencast**

https://user-images.githubusercontent.com/43730119/198902298-9f62050c-dbee-4a35-b5e9-f221035e6712.mp4

**Platform**

```
                   '                      user@comp
                  'o'                     ---------------
                 'ooo'                    OS: Artix Linux x86_64
                'ooxoo'                   Kernel: 6.0.2-artix1-1.1
               'ooxxxoo'                  Uptime: 29 mins
              'oookkxxoo'                 Packages: 1276 (pacman)
             'oiioxkkxxoo'                Shell: zsh 5.9
            ':;:iiiioxxxoo'               Resolution: 3840x2160
               `'.;::ioxxoo'              WM: dwm
          '-.      `':;jiooo'             Theme: Arc-Gruvbox [GTK2/3]
         'oooio-..     `'i:io'            Icons: Adwaita [GTK2/3]
        'ooooxxxxoio:,.   `'-;'           Terminal: st
       'ooooxxxxxkkxoooIi:-.  `'          Terminal Font: JoyPixels
      'ooooxxxxxkkkkxoiiiiiji'            CPU: 12th Gen Intel i7-12700K (20) @ 6.700GHz
     'ooooxxxxxkxxoiiii:'`     .i'        GPU: NVIDIA GeForce RTX 3080
    'ooooxxxxxoi:::'`       .;ioxo'       Memory: 2331MiB / 31837MiB
   'ooooxooi::'`         .:iiixkxxo'
  'ooooi:'`                `'';ioxxo'
 'i:'`                          '':io'
'`                                   `'

```

It just fresh install from archlinux repository 4.0.1 version

**Comment by dterrahe** [comment]
Do you have the problem with other keybindings as well? The default dwm bindings seem to use the alt (mod) key rather than super and they work fine for me. If it is _just_ the super key keybindings that are causing you problems, you'd have to help me configure dwm to expect those. Maybe send a config file (with instructions)?

**Comment by VolkovIlia** [comment]
> Do you have the problem with other keybindings as well? The default dwm bindings seem to use the alt (mod) key rather than super and they work fine for me. If it is _just_ the super key keybindings that are causing you problems, you'd have to help me configure dwm to expect those. Maybe send a config file (with instructions)?

Here is my config https://github.com/VolkovIlia/dwm/tree/bestfriend . The best way to check it is to install minimum artixlinux (or arch) and install [LARBS](https://larbs.xyz/) on virtual machine.

**Comment by dterrahe** [comment]
> The best way to check it

I can check default dwm relatively easily on my debian installation, but installing a whole distribution with a customized version of dwm is too much hassle for me; I would need to set up a development environment as well to do debugging. Maybe if you mention the specific version in the subject of this bug there could be other developers who have the same configuration and are interested in fixing it. Although at is likely we would have heard about this issue sooner if that were the case.

**Comment by mindtheegab** [comment]
to use super key :

/* key definitions */
#define MODKEY Mod4Mask

**Comment by mindtheegab** [comment]
also outside the scope of this particular issue but related since i couldnt use my shortcut to kill the app : sudo killall darktable doenst seem to work, i had to use xkill

**Comment by mindtheegab** [comment]
in case my previous comment was confusing this is the official doc on it https://dwm.suckless.org/customisation/windows_key/

**Comment by mindtheegab** [comment]
i just changed my config to ALT key and all the shortcut work correctly so definitely something to do with the Super key

**Comment by VolkovIlia** [comment]
> i just changed my config to ALT key and all the shortcut work correctly so definitely something to do with the Super key

So do I, standard DWM config works fine.

**Comment by mindtheegab** [comment]
ok good for a moment i thought Lukes build was the issue(i also use that)

**Comment by dterrahe** [comment]
> i thought Lukes build was the issue

My suggestion would be to reach out to the maintainer of the patched build or to the original authors of the wm and get confirmation from them that the changed configuration is fully supported and that what you are seeing is not expected behavior. This so far seems limited to just one altered build of a non-mainstream wm. If you decide to use that as your main driver, I'm afraid the likelihood that you are going to be the first (or 2nd) to encounter an issue with a non-mainstream application is somewhat increased. You may have better chances to get them to fix the issue, since kde and possibly others prove that can be done, than for dt to detect this specific version of dwm and alter its behavior based on that.

**Comment by mindtheegab** [comment]
thats fair but ive been using that build for years and darktable is the only software i ever had an issue with

**Comment by dterrahe** [comment]
There are probably not that many applications that have a shortcut system like darktable has since 3.8. If incompatibilities had been reported before, they might have been resolved. If you go for a fairly unique combination, that responsibility all comes down to you. Nothing wrong with that and I understand that must be frustrating, but neither party has provided you with guarantees or warranty; the GPL is pretty explicit about that.

I'm perfectly happy to see if I can work around your issue in a generic way, but that would mean providing me with a configuration of the _standard_ dwm (the one included in Debian; ok, that may _also_ have been patched, who knows, not me!) that allows me to replicate the issue easily so that I could test if a workaround _works_. Having to compile (and find/install dependencies) and install (without messing with my working setup) is not something I'm going to do. "Just" installing everything on arch would mean me setting up that environment (including the tools I use and have customized) before I can even attempt to _replicate_ and then _diagnose_ the issue and then experiment with solutions. You are expecting a lot from an unpaid volunteer.

**Comment by mindtheegab** [comment]
oh yeah i didnt mean it in a complaining way. so you are not getting that issue on debian + standard dwm?

**Comment by dterrahe** [comment]
It doesn't use the meta key for global shortcuts. As you found, Alt+ shortcuts work fine.

**Comment by mindtheegab** [comment]
oh ok if you ever have time to try https://wiki.debian.org/Dwm, it seems you shouldnt have to worry about dependencies

> 
> To get started, grab the source code by running the following in a terminal:
> 
> $ apt-get source dwm
> 
> Browse to the extracted directory:
> 
> $ cd dwm-*
> 
> Copy the template configuration file to one which will be used for customizations:
> 
> $ cp config.def.h config.h
> 
> Now open config.h in the editor your choice and make the desired changes. Though it is written in C, most of the preferences are self-explanatory.
> 
> Once your changes are complete, run the following command (as root) in the source directory:
> 
> # make clean install

**Comment by schwukas** [comment]
For what it's worth, I'm running into the same problem with i3wm. I realise this is _somewhat_ unrelated since this is about DWM but I managed to narrow down the cause to the use of `setxkbmap de -option caps:super` which maps the Super key to Capslock. 

1. Start Darktable and everything is working well.
2. Quit Darktable and run `setxkbmap de -option caps:super`
3. Start Darktable and notice that it shows the described behaviour.
4. Unfortunately i3wm does not seem to honor `setxkbmap de -option caps:none` or any other key mapping so a restart is required to undo the mapping and have Darktable work properly again.

Sounds quite weird but I hope it might help someone :cactus:

**Comment by VolkovIlia** [comment]
Any updates?(((
