### ISSUE TITLE
Absolute font text size for Watermark module

### ISSUE THREAD

**Issue by eslogan** [darktable-org/darktable#12813]
I think it would be useful to have an absolute sizing option for fonts in watermark's module text. By now, it can be scaled in relation to the image size, but this makes it unhandy to repeat a text watermark format in different pictures with different text on it.

i.e. if you edit photos of different authors, and you need to watermark their names in the same fashion for each of them, you could apply a text watermark and just write down the photographers name, but, at the same scale value, a shorter name like would look bigger than a longer name, having thus to resize it each time.

If there was an abolute font sizing, you could just choose a font size and position, save the values as a preset, and then just changing the text input.

**Comment by parafin** [comment]
SVG is vector graphics and darktable doesn't use size in pixels anywhere in its pipe either, so absolute font sizing isn't possible to have. But it's not what you actually need here. Right now scale is calculated based on horizontal size of the image and rendered SVG, having an option to define it as vertical size ratio will solve this issue. It's probably possible to workaround this limitation already by creating an SVG file where text is rotated 90 degrees and undoing the rotation in watermark iop settings.

**Comment by eslogan** [comment]
Thanks, very clever way to solve it on the way

**Comment by TurboGit** [comment]
We have an option to scale based on the image size, larger side or smaller side.

**Comment by parafin** [comment]
It doesn’t help, since it still uses horizontal watermark size, plus it depends on image orientation. Really, a new “vertical” option would be helpful to avoid the need for described above workaround.

**Comment by parafin** [comment]
right now default scale is <watermark width> / <image width> and we could add an option for <watermark height> / <image height>

**Comment by parafin** [comment]
Or rather it would make sense to provide all 8 options: two for nominator (watermark width and height) x 4 for denominator (width, height, longer border, shorter border)

**Comment by m-p-y** [comment]
In the linked PR four additional options to the "scale on" option of the watermark module are implemented, two of those referencing to the SVG height, as suggested. In addition I proposed a new text template, which also helps to get the same font height for different texts.

However, I haven't implemented all 8 options which are discussed above, maybe there would even be 16: (watermark width, height, longer border, shorter border) x (image width, height, longer border, shorter border). My feeling is that this will get rather confusing and for this problem of differing font heights it seems not needed.

@parafin: As you proposed to implement all 8 possibilities, please give me a note if you think that I should remove the "closes issue" keyword from the PR.

**Comment by parafin** [comment]
If it solves your issue, I would say it’s enough;)

**Comment by wohler** [comment]
In darktable 4.8.1, based upon this discussion, I discovered the scale on > advanced options > scale marker reference > marker height and scale marker to > smaller image border options. With these options, I can set the scale and the text size will be the same for portrait and landscape and for different length texts for other copyright holders. This is a big help! 

Unfortunately, I still need two presets for portrait and landscape because I still need slightly different x and y offsets in portrait and landscape mode for my watermarks in the lower right-hand corner.

Please let me know if there is an option combination that will allow me to place the watermark in the lower right-hand corner in the same position in the same size for both portrait and landscape, or whether I should submit another issue.

Thanks!

**Comment by m-p-y** [comment]
@wohler To my knowledge there is unfortunately no possibility to achieve what you want. The advanced mode is designed so that x-offset = 0.5 means that the watermark is shifted by half of the image width. In the _scale on -> smaller/larger border_ mode identical x/y-offset values give you identical x-/y-spacing but there you cannot get the same text size.

**Comment by wohler** [comment]
OK, thanks. I'll create a feature request for more absolute positioning of a text watermark.
