### ISSUE TITLE
reduce number of filmic tabs

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#12851]
**Is your feature request related to a problem? Please describe.**
New users often complain about the difficulty understanding all the different filmic parameters, while there can sometimes be a lot of clicking back and forth between tabs in filmic. Simplifying the UI design of filmic as per below might help ease these problems.

**Describe the solution you'd like**
Remove both ‘options’ and ‘display’ tabs, and redistribute their parameters into the other three tabs. Eg:

**range** [*]

use custom middle-gray values checkbox

SCENE
white relative exposure
black relative exposure
dynamic range scaling
auto tune levels

DISPLAY
target [**]
target black luminance
target white luminance

**reconstruct**

HIGHLIGHTS CLIPPING
enable/disable checkbox [***]
threshold
transition
display highlight reconstruction mask
iterations of high quality reconstruction
add noise in highlights
type of noise

BALANCE
structure/texture
bloom/reconstruct
gray/colorful details

**look**

color science
preserve chrominance
contrast in highlights
contrast in shadows
contrast
latitude
shadows/highlights balance
extreme luminance saturation
auto adjust hardness checkbox

Pros:
Fewer tabs means less clicking back and forth.
Parameters are all grouped neatly according to type. All reconstruct options in one place, all look options in one place, etc…
Less confusion for new users about what all the ‘options’ do. (Eg. Why do I click a checkbox for ‘use custom middle gray values’ and see nothing happen? Oh, I have to go back to ‘scene’, and ‘display’, tabs for that! Why do I add noise to highlights and see nothing happen? Oh, I have to do something in ‘reconstruct’ tab for that!)

Cons:
Takes up more vertical space.

*Thought of this name in exactly 0.01 seconds. You might think of something better.
**As per my idea suggested in #12850. If this idea is rejected, then leave it out.
***As per my idea suggested in #12847. If this idea is rejected, then leave it out.

**Comment by nicorikken** [comment]
I used to go back and forth as well until I read the manual. Now I can go through the process systematically and then the tabs really make sense. As far as I understand it the 'custom middle-grey values' chechbox is tucked away for a reason, the manual encourages the use of the Exposure module instead.

You specifically mention new users not understanding parameters. Then I think the tabs really make sense to keep some structure. For wel experienced users having a virtual layout could save some clicks, but that is fine because they need less guidance on how to use Filmic RGB.

**Comment by SoupyGit** [comment]
Two examples of going back and forth:

I often like to compare high latitude with safe contrast in shadow/highlights, and low latitude with hard contrast in shadow/highlights.

Sometimes seeing the effect of more high quality reconstruction iterations causes me to go back and tinker with the other reconstruct settings.

> As far as I understand it the 'custom middle-grey values' chechbox is tucked away for a reason, the manual encourages the use of the Exposure module instead.

Yes i understand the current reasoning, I just dont think it is 'tucked away'... all users are going to go into options tab at some point, and wonder what it all does. Better for them to tick the box and see the sliders appear immediately than tick it and scratch their heads. I am not suggesting we change the default state of that box being unticked.

If an option was so inferior as to always be unused, I personally think the correct approach would be to depreciate it (hide it), not put it in options tab.

Happy to hear arguments against my proposal though :)

**Comment by Nilvus** [comment]
Tabs have been structured by Aurélien for good reasons and filmic is very structured. Of course, there's cons about that but many more good reasons, like what explained @nicorikken. Thus, some are needed to be separated because not used often or no need to change them often. Having more vertical space will not help. We have had complaints about modules (like color balance rgb) with more vertical space and options.

It's impossible to have a really simple module with so much options. The only way to have a really simple module is have really few settings, like sigmoid. But that allow less fine-tuning. All things have pros and cons.

I let this open by now but I'm quite sure this won't change.

**Comment by TurboGit** [comment]
Yes won't change as explained by @Nilvus. We can't dismiss the work & design from the author of the module.

**Comment by SoupyGit** [comment]
On the matter of vertical space, color balance rgb has 18 lines. My proposal would have 13 lines max plus the graph, meaning it would end up about the same size - therefore not unreasonable by current standards.

And to be clear, it was not a dismissal, simply presenting an alternate solution. But if people are not willing to consider it, no problem.
