### ISSUE TITLE
Modules column changes width dep. on what is entered in the search field

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#12877]
Manjaro, nvidia, openCL, latest darktable-git (4.1.0+970~ga386abc5c), self-compiled.
Clean machine, fresh compile.

In darkroom, the width of the right column (the modules column), varies depending on what is entered in the module search field.
It ought to be static (and/or as dragged by user).

See enclosed screen dump:
Left part = search field is empty; column width = normal
Middle part = search field contains a single "l" (lower case L); column width grows
Right part = search field contains a non-existent module name "local q"; column width shrinks

![searchWidth](https://user-images.githubusercontent.com/19223977/201476164-0186223c-cc6d-409a-a9ea-fa098f8269df.png)

**Comment by pehar1** [comment]
Not able to reproduce...

darktable 4.1.0+970-ga386abc5c
OS : Linux 5.15.0-52-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:        3999372 kB
Graphics Card :     Product Name                    : GeForce GT 435M
Graphics Card : Driver Version                      : 390.154
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.1 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by dterrahe** [comment]
In the latest update (#12866) the _default_ width for the panel depends on the _natural_ width of its content (basically the width needed to show buttons and all text without any ...). This cannot be fixed because it is dependent on font size/screen resolution but also on the modules that are actually shown. Especially wide are deprecated modules, because they show a long text in red explaining their status. Since they are normally hidden, typing something in search that selects them ("f" will show defringe for example) causes the panel width to increase.

If you don't want this behavior, set an explicit panel width (by dragging its border). From that point, this width is used and there no longer should by any changing column width (unless the window size is changed or the other panel+top/bottom panel force a reduced size).

> It ought to be static ([...] as dragged by user).

Yes, that's how it is supposed to work. Please refine this issue if that is not the case for you.

**Comment by ClaesGitHub** [comment]
(Note: I am working with Fuji .RAF)
I have been bisecting, and arrived at this culprit:
```
a386abc5c1b0fc761399c8ddf7280a91a92fb74f is the first bad commit
commit a386abc5c1b0fc761399c8ddf7280a91a92fb74f
Author: hanno@schwalm-bremen.de <hanno@schwalm-bremen.de>
Date:   Sat Nov 12 09:30:36 2022 +0100

    Fix oversegmentation issues
    
    While investigating #12864 i checked the whole segmentation code again.
    
    There were in fact some bugs only evident in case of heavy segmenation that
    could have lead to out-of-bounds problems.
    
    Also added checking code for segmentation stacks and debugging output.

 src/iop/hlrecovery_v2.c | 23 +++++++++++++----------
 src/iop/segmentation.h  | 37 ++++++++++++++++++++++++++-----------
 2 files changed, 39 insertions(+), 21 deletions(-)

```

**Comment by dterrahe** [comment]
?

I already pointed out to you which pr introduced this behaviour and it seems your bisect went wrong.

With latest commit it should already be significantly reduced and otherwise you can set a specific width (by dragging the border of the panel) which completely fixes it.
