### ISSUE TITLE
issue when editing values in the preferences

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#12941]
Set a key shortcut with effect=set and try to edit the value, see:

![image](https://user-images.githubusercontent.com/467069/202751479-237865f7-6d56-4867-bb92-db817e87cebf.png)

The editing "entry" seems shifted somehow.

**Comment by TurboGit** [comment]
@dterrahe : Maybe one for you?

**Comment by dterrahe** [comment]
Seems that this was caused by 44936706d356b33644449b8b6ff5da44bd71526d

@Nilvus could you please have another go at that one?

BTW I just learned that tnum=1 _can_ be set from css. I thought before that code like this 
https://github.com/darktable-org/darktable/blob/0f6969e6336f88c01de876aa9ffbcfb6096a3484/src/dtgtk/range.c#L604-L608
was needed every time, but you can put `font-feature-settings: 'tnum';` in css. I wonder if we could not simply make that the default for _all_ our fonts, avoiding future issues like https://github.com/darktable-org/darktable/pull/12927 ?

**Comment by dterrahe** [comment]
I would leave it for now; it doesn't hurt.
