### ISSUE TITLE
No "album" category for tags

### ISSUE THREAD

**Issue by xarthurx** [darktable-org/darktable#12997]
**Introduction**
I came from LR and are finding if there's a functionality like the LR's collections and found this issue:
https://github.com/darktable-org/darktable/issues/10643

I learned that there's a type of "album" tag that you can use like the LR's collection, or Google Photo's "album" function, where a photo can belong to multiple "albums".

**Describe the bug/issue**
I'm not sure if it is a bug, but since there's no "question" issue and this question is related to the above issue, I'd like to ask here to see if this is a bug associated to Windows or just the functionality is removed.

**To Reproduce**
1. Find a tag, right click and "edit tag"
2. There is no "album" checkbox, like the one in https://github.com/darktable-org/darktable/pull/5134

**Expected behavior**
I can organize photos using the "album" tag system.

**Screenshots**
![image](https://user-images.githubusercontent.com/1921878/204052369-63476dd0-1acd-4a9b-9842-cab622b50148.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.1
* OS                : Win 11
* Memory            :  32G

**Comment by Nilvus** [comment]
This had not been added because you could do it by just creating an 'album' parent, then add/link tags. See comments on PR you linked, especially that one: https://github.com/darktable-org/darktable/pull/5134#issuecomment-631632489 (and comments above to understand more why).

So you can organize your photos using "album" tag system. Just create your tag hierarchy, starting by album parent tag. I let this open just for your answer but as this had already been discussed and it's already possible, no need to let that open. Feel free to close it yourself of course.
