### ISSUE TITLE
remove end empty space of the folder location in "copy & import"

### ISSUE THREAD

**Issue by xarthurx** [darktable-org/darktable#12991]
**Is your feature request related to a problem? Please describe.**

It is loosely related to: https://github.com/darktable-org/darktable/issues/10934

The actual problem is I accidentally add a <space> at the end of the folder name:
![image](https://user-images.githubusercontent.com/1921878/203937393-da7b495c-e146-45a3-b657-031ec515c139.png)

And **darkroom** won't import any image.

I've spent hours figuring out the issue and finally found it in the logs.

**Describe the solution you'd like**

Darkroom should ideally report warnings or just fix this issue automatically.

**Alternatives**

In such case, I think it make sense to just detect and remove any space at the end of the folder location, so that when concatenating the strings, no error will appear.

**Comment by erzsig** [comment]
I am a newbie here, and would be delighted to contribute to Darktable code. As I looked for a simple task, found this issue.
Please correct me, and clarify the planned fix for the issue.

I have tried adding trailing space to the folder locations on Ubuntu (Darktable 4.0.0).
As expected in case of a Linux system - it works correctly.
The only disturbing thing is that in the GUI of the file manager you see two seemingly identical paths. ("Darktable" and "Darktable ")
It is even possible to add a space to the filename pattern. But after a "successful" import Darktable does not open the file as the file extension is unknown (eg "ARW " instead of "ARW")

So the folder name problem is mainly Windows related.

All the same it would be more clear and painless for the users if Darktable would not allow trailing spaces in the folder and file names.

My proposal:
1, Trailing spaces should be removed  not only from the sub folder name but also the base name. Even better from each folder in the path.
2,Trailing spaces should be removed  from the file name also.
3, For the sake of consistent behavior the same should be done for the export.
To be considered:
1, Is the fix for windows only or generally for each operating system?
2, Is it acceptable for the users, that after this fix they cannot import more images into the old locations where folder names had trailing spaces?
3, Should Darktable follow the same rule (filtering trailing spaces from folder/file names) for each path it uses?

**Comment by erzsig** [comment]
So far I have created a fix, which removes the trailing spaces after the filename.
And for Windows only it removes the spaces from each folder name
