### ISSUE TITLE
Apply or remember sorting order when sorting on filename/rating etc

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#13015]
Love the new sorting buttons. 

But some sortings you naturally want to sort from high to low and others from low to high.  When changing the sorting, it would be nice if the direction changed as well.

Example: 
Filename sorting and Capture Time sorting both puth the oldest image on top and the latest below, so the display is a natural timeline of the event; it makes sense.
Then change to rating-sorting and all of a sudden, the lowest rating images are on top.  That makes no sense; Obviously I want to work with the highest rated images (they hae 4-5 stars for that reason).

**Comment by Nilvus** [comment]
On both case, it's by default from low to high, so it makes sense. What just make no sense for you is that you want what is not displayed. And that's why the "sort by" icon (![image](https://user-images.githubusercontent.com/45535283/204131284-2bac275b-da0a-42f6-9fe5-1b1e021db1c1.png)) on topbar is for: changing that to high to low.

About filename sorting and capture, it would also make sense to have recent ones at first, as well as actual behavior. This had not to be changed. If you want highest rated images at first (and that makes sense of course to want that), just click on "sort by" icon.
