### ISSUE TITLE
[Undesired Feature] Full Preview Layout mode not showing the Overlay

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#13036]
**Background:**
Last night I was working on culling multiple (+150) after import. I normally use the Full Preview Layout mode since I know that the image in front of me is the image that will get start/rejection (I dont trust the culling layout with the mouse Act On, see https://github.com/darktable-org/darktable/issues/6025) plus it is large enough to show the details (closed eyes), not sharp focus.

**Issue:**
Since https://github.com/darktable-org/darktable/pull/12784, the overlay block only shows if I move the mouse to the top section and then goes away. This was the intent/Feature of this PR. On the first image, this is not a big problem because I normally was already using the mouse, but as soon I use the keyboard arrow to see the next image, the overlay doesnt show. It will only show if I move the mouse. I dont want carpal tunnel syndrome :-) 

While the overlay staying in the way is bad since it can block the image, not having any information is also bad. I cant see the image filename, I cant see if I rejected it (when trying to select the best one from a series), I cant tell if I hit the arrow twice and skipped an image via the filename. 

**To Reproduce**
- Press F 
- Press right keyboard arrow

**Expected behavior**
 I understand the desire for the overlay not staying ON all the time. Therefore I see these options:

- I would like the overlay to show up for some amount of time (configurable) and regardless of the mouse position. The overlay should show automatically for some amount of time if: 
  -  image is just loaded (eg. press arrow to see new image) 
  -  whenever a change is performed (eg. press Reject, Star). 

- Address https://github.com/darktable-org/darktable/issues/6025 to use culling layout (image is not as large at full preview, but ok for me via using W key). 

**Workaround**
- Last night I used FileManager Layout mode, set to display 1 image and turned on Permanent Overlays.
- Or start using Geeqie for culling. 

**Which commit introduced the issue**
https://github.com/darktable-org/darktable/pull/12784

**Platform**
* darktable version : 4.1.0~git1117 OSB Master
* OS                : Fedora 36 KDE X11

**Comment by europlatus** [comment]
Can confirm the same issue. The annoying thing is that the behaviour seems to have changed since 4.0. 
The behaviour of the overlay only showing when the mouse is moved is very inconvenient and I don't understand the reasoning for why it only displays when you move the mouse in the upper half of the image. Is this not a bug?
Full screen preview is fairly useless for rating and culling without the overlay. Would be great if the previous behaviour was restored for 4.3 and perhaps the feature enhanced for 4.4 so we can adjust the stickiness timing and/or placement of the overlay.

**Comment by gi-man** [comment]
@europlatus technically 4.0 was broken and it was fixed. Read the related PR linked in the commit section. The next major revision of dt is 4.4 (there is not 4.3) in the summer.  This will get addressed.

**Comment by europlatus** [comment]
@gi-man Thanks for the info. Since I never used the filmstrip in the lighttable, I didn't see a way to see ratings and exif info in full screen preview, so the overlay was essential for me. I see now that others were using the filmstrip and didn't want the overlay being so sticky. I was wondering if there was a 4.3 bug fix release, which is why I mentioned the previous behaviour being restored for that release (thinking it was broken now). Anyway, for now, I will use the filmstrip to do what's needed, but looking forward to overlay functionality improvements because the filmstrip cuts down on screen real estate.

**Comment by AlicVB** [comment]
@gi-man : If I understand your issue (correct me if I'm wrong), there's 2 issues in one in fact : 
1. show the info by default when entering a new image
2. the fact that moving the mouse in the bottom part of the image doesn't show the info anymore

I completely agree with point 1. point 2 is more debatable...

btw,

> I would like the overlay to show up for some amount of time (configurable) and regardless of the mouse position. The overlay should show automatically for some amount of time if:

is already implemented, in the thumbnail overlay popup. What is tricky for full preview is that you first need to show the topbar (ctrl-shift-t) then you can click on the "star" to set the overlays and then hide again the topbar with same shorcuts

**Comment by gi-man** [comment]
@AlicVB I'm going to start with describing a bit my typical workflow, since I think extra background might help. Let say I'm taking Christmas portrait images of my kids and I have 5 similar images taken in quick succession (A,B,C,D,E). I import them into dt and do some simple tags in file manager layout. I quickly notice that in image A, the had their eyes close, so I select it with the mouse and hit R. I filter on the top to show all image but rejects. Why? I know I dont want to see it again and spend more time on image A.

My current process (4.0) was to then switch to Full Preview Layout (f) to do the culling there. Full Preview shows me the entire image at once and allows me to look for focus in the eyes. I would use the Overlay to see the current star rating and image number. I would navigate from image B to C via the keyboard arrow key. I would notice that C is out of focus, so (r)  then to image D and E. B, D and E would get at least 1 star or more. I would then continue to use the arrows to switch around until I ideally pick 1 image (lets say D) as the best one of that series. Once done I would move to the next series of images to eventually process in darkroom.

But the change above now hides the Overlay and when I switch with the keyboard arrows to the next one, the overlay doesnt show again unless I move the mouse. I quickly get lost if I'm on image B,C,D or E. I understand that Full Preview Layout is to view the whole image and having the overlay in the way is not correct. 

Ideally, I would use the Culling Layout (x) to do the culling, but it is too inconsistent because of the Act On. When I press (r) to reject an image, it is a mystery which image will get rejected if I did not place the mouse outside the culling area. I've made so many mistakes that I just stopped using Culling Layout.  There is another Act On Issue on GitHub, so I wont duplicate the conversation. In summary, I prefer not to use culling until the Act On is resolved.

My second option is to continue using the Full Preview Layout (f), but even with the ctrl-shift-t, currently (4.3.0+18~gf45cb8e6d) the overlay does not show unless I move the mouse. When I press the arrow to see the next image, the overlay will not show until I move the mouse to the top of the image. Hence, why I think:

- show the overlay by default when image is loaded (eg. press arrow to see new image) until  XX secs 
- AND also show the overlay whenever a change is performed (eg. press Reject, Star) until XX secs (this allows me to confirm it was image C that I just applied the reject to). 

Sorry if I was too long.

**Comment by europlatus** [comment]
I fully concur with @gi-man's findings and hoped-for behaviours. The fact that only moving the mouse in the top half of the image is a minor issue and not important. But the fact that the mouse is needed at all is the big one here.
However, ctrl-shift-t and then enabling permanent overlays for previews does show the star ratings (and exif info if permanent extended overlays are chosen) at the bottom of the screen, so this is a very good alternative to disappearing overlays. The only issue is more screen real estate being used up.

**Comment by AlicVB** [comment]
I'm currently on the overlays glitchs/issues raised recently (including this one)... I'll come back with something in few days. Just be patient, it's Christmas times here ;)

**Comment by gi-man** [comment]
AlicVB, there is no rush. Enjoy the Christmas time.

**Comment by quovadit** [comment]
After culling some images, I absolutely agree, that the disappearing overlay in 4.2 is annoying, because I have to repeatedly switch from keyboard (arrow-keys + numbers) to the mouse to see the metadata.

On the other hand I also did not like the permanent overlay in 4.0, which re-apperared everytime you move to the next image, because there are occasions, where I just want to see the (whole) image, but no metadata hiding parts of the image.


@europlatus: thanks for the tip, I did not know, there is this option 'preview overlays' to show metadata below the image in fullscreen/culling-mode.


So I would suggest three simple changes:
- rename the existing 'overlays' correctly 
  - the metadata below the image is no 'preview overlay' but kind of a 'custom-footer'
- make it easier to toggle them them on/off:
  - always show all 'overlay' options when clicking the star-icon, independent on the view I'm currently in 
  - add new keyboard-shortcuts:
    - 'i': show/hide infos in overlay-bubble
    - 'ctrl-i' show/hide infos in custom-footer
- arrange the metadata + rating-stars in custom-footer next to each other to use less space
