### ISSUE TITLE
Leica 240 noise profiles

### ISSUE THREAD

**Issue by marcomastri** [darktable-org/darktable#13083]
Hello, I tried to build the noise profiles for the Leica 240, I have a couple of doubts though:

1. When testing the profiles with `darktable --noiseprofiles presets.json` I still don’t see the ISO values, only the “generic poissonian” profile;
2. The exported JPGs from the script are all badly posterized, is it normal?

Please find attached the generated profiles:
[darktable-noiseprofile-20221205.tar.gz](https://github.com/darktable-org/darktable/files/10158573/darktable-noiseprofile-20221205.tar.gz)

The RAW files can be downloaded here: https://drive.google.com/drive/folders/1JZVUesDP4z3z1Kjh79AMGiEZoru6Ku7y

**Comment by kmilos** [comment]
> 1. When testing the profiles with `darktable --noiseprofiles presets.json` I still don’t see the ISO values, only the “generic poissonian” profile;

The make and model have to match what [rawspeed normalizes for dt](https://github.com/darktable-org/rawspeed/blob/ff4ef82d5087da042ee850f08da669d9879e6ceb/data/cameras.xml#L17054), not what the script (i.e. exiftool) reads directly, so in this case it should be just `M (Typ 240)` for "model" instead of `LEICA M (Typ 240)` in your presets.json file (and same for all the "name" entries).

**Comment by marcomastri** [comment]
Thank you! Here is the updated archive, then:
[darktable-noiseprofile-20221205.tar.gz](https://github.com/darktable-org/darktable/files/10169323/darktable-noiseprofile-20221205.tar.gz)
