### ISSUE TITLE
Colour calibration module degraded?

### ISSUE THREAD

**Issue by valvelifter1951** [darktable-org/darktable#13159]
I noticed that the recent release of dt (4.0.1) has changed the colour calibration grey tab and I can no longer enter negative values or values greater than one in the R, G, B channels for monochrome conversion using right-click and typing in values. I used to use this quite often to get a high contrast effect for my monochrome conversions. It looks like I will now have to revert to using Gimp to get the required effect. I don't know if this is an accidental change or deliberate.
I have searched issues for any reference to this but cannot find any.

**Comment by gi-man** [comment]
Please use the template to provide all the information. (eg. what OS? , self build?)

What version of darktable are you currently using? Is the current module you use called Channel Mixer?

**Comment by kofa73** [comment]
Maybe this?

https://github.com/darktable-org/darktable/commit/6a706d1547b15483ecdbfc6f326b591b9d7fbd43

**Comment by gi-man** [comment]
I think it is actually the desired intent of this PR https://github.com/darktable-org/darktable/pull/11257 via the removal of the soft limits(see the conversation around drawbacks). The OP is likely using 3.8 or an earlier version.

**Comment by valvelifter1951** [comment]
@gi-man What template? I think I have stated all relevant information, i.e dt version that I'm using and colour calibration module using grey tab to make a monochrome conversion. Any further information is just likely to cloud the issue. The OS is irrelevant but it's Linux mint 20.02, cinnamon 5.0.7 and it's not self build. The change happened after 3.8.1.

**Comment by gi-man** [comment]
The template is pre populated when your start an issue:

**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**


**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

**Expected behavior**


**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_




**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by Nilvus** [comment]
@gi-man: for this one, more infos were not needed (and darktable release was precised).

@valvelifter1951: as you can see with commit and PR pointed there, that module is not degraded. This had changed for reasons, to avoid drawbacks.
I fear so that this will not change now. Fortunately, darktable is powerful and versatile. You have many other ways to find what you want, even by using other tabs of same module, dealing with color balance, or quite some other ways.

**Comment by gi-man** [comment]
> for this one, more infos were not needed (and darktable release was precised).

I dont agree. We knew he just installed 3.8.1, but no clue what version he was using prior and the source of the build. I think we should add required fields in the Issue Template.

OP: S7habo has a 3 part youtube series around B/W conversions. It is really good and detailed using the current modules.

**Comment by aurelienpierre** [comment]
Negative values are mathematically sane and colorimetrically relevant in color calibration. Whatever code change now prevents them is to be called a regression and cannot be deemed intended by design because **I** am the designer.

Fix your shit, coding monkeys.

**Comment by MStraeten** [comment]
that limited range 0-1 on the grey tab was commited by the designer of that module on Nov 14, 2020 ;)

**Comment by dterrahe** [comment]
> that limited range 0-1 on the grey tab was commited

Not _really_ though, because this specific new range in introspection, which is used in `_iop_validate_params` and therefore would cause error messages to be printed when loading an image with settings outside this range, is later in https://github.com/darktable-org/darktable/commit/6a706d1547b15483ecdbfc6f326b591b9d7fbd43 overridden by generic calls to `dt_bauhaus_slider_set_hard_min/max` with the intended consequence of setting a different _soft_ range. Obfuscating true intentions of code without any commentary is a fun way for the hyper intelligent to trip up coding monkeys who later on foolishly try to create some order out of chaos. Those idiots are never able to distinguish between smart tricks and silly errors. Luckily _their_ fuckups are always eventually found out with 9 months of hard testing, by the hordes of people impacted, just in time to miss the _next_ release.

**Comment by Mark-64** [comment]
Assuming we are going to fix this in 4.2.1, should we perhaps put something in 4.2 release notes?
