### ISSUE TITLE
Can't select lens in "lens correction" module

### ISSUE THREAD

**Issue by st-binder** [darktable-org/darktable#13150]
for the latest version of darktable (git master) I was unable to select a lens in the lens correction module manually. The list of lenses disappears before I can make any selection. This is required for any manual lens or in my case any lens used with the Nikon FTZ adapter.

**To Reproduce**
1. Go to 'lens correction module'
2. Try to select lens manually
3. List disappears

**Expected behavior**
- Selecting lens is possible

Version: darktable git master / commit 4b3d410bc0a963b4357ad4c8fe4e1abd0a32d439
Platform: archlinux x86-64, gnome on wayland, opencl installed/active

**Comment by gi-man** [comment]
I cannot reproduce on fedora 37 kde x11 master

**Comment by st-binder** [comment]
no problems using darktable lens correction with gnome on x11, so the bug seems to be wayland specific

**Comment by Nilvus** [comment]
@st-binder: would be good if you can test older master and see which one introduce that issue on wayland. Note that wayland is not recommended actually for software like darktable as wayland lack color management support.

@sgotti has done great improvement last week on lens correction module. Maybe issue is from that. First merge was first of november, so try if possible latest commit on october.

**Comment by sgotti** [comment]
@Nilvus I tried a build of a commit (19825f35cd6f3967c0104740f428ea05286df8c7) before the merge of PR #12714 but I have the same issue on wayland.

**Comment by st-binder** [comment]
I prepared a testing environment and bisecting the code. I found that this bug was introduced in commit (https://github.com/darktable-org/darktable/commit/41948c9514e1a0a060a01ea8afc1046700e18dc7)

**Comment by sgotti** [comment]
Since that commit is the one that enabled the wayland gdk backend it's probably an issue in the lens module when creating the camera/lens menu that triggers only on wayland.

When i tested it this morning I noticed that the camera/lens menu disappears when the submenu should open (and probably the lens module is the unique creating a gtk menu with submenus).

**Comment by st-binder** [comment]
I noticed the same except for the very first item, which has a submenu.

**Comment by sgotti** [comment]
@st-binder Just noticed that I had the window maximized (was testing under gnome+wayland). When I tried with the darktable window not maximized the menus worked...

(/me switching back to my good old Xorg + i3...)

**Comment by arctic-alpaca** [comment]
I'm not sure if this is related, if not please let me know so I can open a separate issue. 

Since the update to 4.2.0, darktable frequently "crashes"/force closes for me. If started via console, I get the message `Gdk-Message: 11:28:10.301: Lost connection to Wayland compositor.`. Starting with `-d all` does not show any errors as far as I can tell. There does not appear to be a backtrace, I suspect it is because darktable does not actually crash. The issue is frequent, roughly every 1-10 minutes when actively using darktable.

I also noticed a general issue with interacting with the darkroom modules, often times I have to click multiple times to get the interaction to work. Contrary to the @st-binder , I don't have an issue selecting the camera in the lens correction module.

System info:
Operating System: Fedora Linux 37
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.0.13-300.fc37.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 2600X Six-Core Processor
Memory: 15,5 GiB of RAM
Graphics Processor: AMD Radeon RX 6800 XT

**Comment by gi-man** [comment]
@arctic-alpaca your problem sounds different. Please start a new issue. 

I run fedora 37 kde but with Nvidia and x11. Try via x11 and also try with opencl off.

**Comment by victoryforce** [comment]
> I'm not sure if this is related, if not please let me know so I can open a separate issue.
> 
> Since the update to 4.2.0, darktable frequently "crashes"/force closes for me.

Not being able to select a lens and a program being forced to close are definitely different things. So, yes, open a new issue.

**Comment by indy07cz** [comment]
I can reproduce an issue on Fedora 37, GNOME 43.2, Wayland with Radeon Vega Graphics, Kernel: 6.0.15-300.fc37.x86_64, OpenCL off. 
I have also problems as @arctic-alpaca said with interacting with modules (both left and right click). Everything work fine when darktable window is not maximized.

**Comment by Nilvus** [comment]
@arctic-alpaca and @indy07cz: just note, before opening issues, that using darktable on Wayland is not recommended until Wayland have color management supported. It's actually a work in progress on Wayland side. So Wayland issues will probably not be completely considerate and fixed before color management land on Wayland. Color management is just needed for a software like darktable. darktable works great on X11 (it has also since a long time color management).

**Comment by indy07cz** [comment]
@Nilvus got your point, and can't agree more, but there wasn't such an issue in previous versions of DT. Anyway Exec=env GDK_BACKEND=x11 workaround work's fine.
