### ISSUE TITLE
Create HDR segfault

### ISSUE THREAD

**Issue by meplan** [darktable-org/darktable#13162]
**Describe the bug/issue**
Selecting 2 or 3 CR2 files and using "create HDR"  of lighttable issue a segfault in 

dt_interpolation_resample_sse._omp_fn.1 () at /home/meplan/DTdev/darktable/src/common/interpolation.c:1663
1663	          vhs = _mm_add_ps(vhs, _mm_mul_ps(*(__m128 *)&i[baseidx], vhtap));

Same bug with or without opencl

**Platform**

* darktable version : 4.3.0 e
* OS                : linux kernel 6.0.12
* Linux - Distro    : fedora 37
* Memory            : 
* Graphics card     : NVIDIA Quadro T100
* Graphics driver   : xorg-x11-drv-nvidia-520
* OpenCL installed  : yes
* OpenCL activated  :  yes and no (same bug)
* Xorg              :  yes
* Desktop           : gnome
* gcc               :  12.2.1
**Additional context**
_Please provide any additional information you think may be useful, for example:_
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**

**Comment by Pseudomanifold** [comment]
Can confirm that this also happens with Darktable 4.2.0 and `.ARW` files. Even a single file is sufficient to reproduce this. Darktable will always segfault in `dt_interpolation_resample_sse._omp_fn`.

**Comment by jenshannoschwalm** [comment]
I am interested in getting this fixed. (So far i am absolutely unable to reproduce)

What are your system memories? What are the settings in "preferences->processing->darktable_resources? Anything changed manually?

**Comment by Pseudomanifold** [comment]
Thanks! I have 32 GiB memory and Darktable has been set to use "unlimited" resources. I can confirm that I experience the same issue with "default" resources. Image type does not seem to be the culprit here, by the way: I can reproduce this with `.NEF` and `.ARW`, and the original poster mentioned `.CR2` files.

Is there a way for me to provide you with a more meaningful log file? The last line I get before the crash when running with `-d all` is:

```
5.341084 [modify roi IN]        export       rawprepare.    (   0/   0) 3013x2012 scale=0.50  --> (   0/   0) 3024x2012 scale=0.50
```

It is sufficient for me to select a _single_ image to get the crash to appear.

However, the **good news** is that I found one potential culprit. In my `darktablerc`, I had

```
plugins/lighttable/export/resizing=scaling
```

The default `darktablerc` sets

```
plugins/lighttable/export/resizing=
```

With this setting, HDR creation does not crash any more! What does this setting correspond to in the end? Does this just control the way images are being exported (I am asking because I cannot remember changing this option manually).

**Comment by jenshannoschwalm** [comment]
Thanks,I will take care of this...

**Comment by jenshannoschwalm** [comment]
> However, the **good news** is that I found one potential culprit.

A good hint to start tracking this down to the roots :-) I think i know where the problem might be - and there are a few other issues that might be related - unfortunately i can't reproduce so far. Could you share a problematic image?

**Comment by Pseudomanifold** [comment]
Here you go, this is one of the problematic images: [DSC_0683.zip](https://github.com/darktable-org/darktable/files/10310568/DSC_0683.zip)

(I can reproduce this even with a single image; let me know if anything else is required)

Thanks so much for looking into this! My manual workaround solved the issue for me, though. Is this maybe just an issue of migrating configurations across different versions of Darktable? (I never created a new configuration during the last 2 years or so).

**Comment by meplan** [comment]
Thanks for the workaround which is also working for me. That's also the first time since a while that I have such compatibility pb in the darktablerc file.

**Comment by jenshannoschwalm** [comment]
> Thanks so much for looking into this! My manual workaround solved the issue for me, though. Is this maybe just an issue of migrating configurations across different versions of Darktable? (I never created a new configuration during the last 2 years or so).

Nope, you selected "scaling" via export preferences :-) But that is not valid for hdr merging at all.
