### ISSUE TITLE
half/non-working UI (workaround available)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#13166]
**Describe the bug/issue**

A half working UI, where parts are not shown or parts are shown when the mousepointer moves over it to disappear again after moving away.

I see this in the terminal:

`dt_gui_load_theme: error parsing combined CSS @import url('file:///home/jade/.local/dt.dvlp/share/darktable/themes/darktable-elegant-grey.css');: darktable.css:241:23'font-feature-settings' is not a valid property name`

Followed by hundreds of GTK related error messages.

**To Reproduce**
build latest development version of darktable and start it (darktable 4.3.0+3~gd1c663b66)

**Expected behavior**
Normal looking and stable UI

**Screenshots**

![scsh](https://user-images.githubusercontent.com/56407344/208493578-3c344159-9f07-460d-9ad6-99c62b7f4cb3.png)

and this is how it should look after starting:

![scok](https://user-images.githubusercontent.com/56407344/208494001-1d9b77b8-60cd-49ce-a268-46bdfaa007fb.png)

**Which commit introduced the error**
Don't know, haven't build/used the developers version in a while. The latest stable version (4.0.1, self build from source) does not show this behaviour.

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.13)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : clang 10.0.1 *or* gcc 8. Tried both.
* Cmake         : 3.18.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Sqlite        : 3.27.2
* Optimization  : -march=native -O3 -mtune=native-pipe

**Hardware**

* CPU              : AMD Ryzen 5 3600 6-Core Processor
* GPU              : GeForce RTX 2060 SUPER 7979 MiB
* Memory           : 32 Gb + 15 Gb Swap

**Additional context**

* Reproducible with other version(s)       : No, 4.0.1, self build, works.
* Reproducible with clean config directory : Yes
* Reproducible after removing xmp file     : n/a
* Reproducible with both RAWs and JPEGs    : n/a
* Reproducible after a clean start (all dirs deleted): Yes

---

**WORK-AROUND**

It turns out that this entry in **darktable.css** is the culprit:

`font-feature-settings: "tnum";`

Commenting that one out solves the problem for me.

---

There's another issue (https://github.com/darktable-org/darktable/issues/13084) that also seems to have this entry as its culprit.

Not sure what is does, but I do not see/notice any difference after commenting it out.

**PS:** Might be related to running on an old system. I'm in dire need of a new/fresh Debian install. Just wanted to put this out here so others might find it and use the work-around provided if need be.

**Comment by Nilvus** [comment]
Such issue is related to non-working CSS on your side. Line you pointed would have done same effect on other people if this was really the culprit. That line is just to allow correct rendering on some number for some fonts. Note that darktable stop if there's something else linking to darktable file (some lines inherit from other). So removing or commenting a line do not means that the line is the culprit. It's not so easy. And that line had been added and tested by few users (and use a lot probably by some more as it had been added about a month ago.
Thus, issue that line is not the culprit of #13084. It was a possibility but had been discarded. Issue #13084 as it explained on it, is caused by external library, not darktable code.

We all should have same issue if darktable CSS caused what you have on one user. And it's not the case. Be sure that you don't have CSS code on darktable preferences (remove it and try again if needed). Be sure you don't have any user.css file on your config folder and restart darktable. Your workaround is not the good way.

If you don't have CSS (or if removing your personal CSS if you have, don't fix that), be sure to clean build folder on your darktable source folder and destination folder (where you install darktable) before compiling darktable again. A good possibility of your issue is that some old CSS code (from 4.0.1) and last changes are in conflict.

**Comment by Nilvus** [comment]
You can see there what CSS line your removed does: https://developer.mozilla.org/fr/docs/Web/CSS/font-feature-settings

**Comment by jade-nl** [comment]
I'll have another look tomorrow, but I can already answer some of your suggestions/points:

* I do not use/have a user.css,
* I did not make any css changes via the *preferences -> general -> CSS tweaks* window.

So, I did not make any CSS related changes, only what darktable dictates is used (darktable.css + darktable-elegant-grey.css).

* As mentioned in my OP:
  *  I completely removed the build directory (and did a fresh clone instead of pull),
  * I completely removed the installed files before the clone/build/install process,
  * I removed the darktablerc file,
  * I even removed every file in ~/.config/darktable/.

So, at some point I basically started from scratch :-) All of that did not solve the problem. It might not be the good way (???) but the only solution atm is commenting out the line mentioned.

I agree with you that this issue probably should have turned up for others. Then again; How  many tested, as mentioned, with an old Debian system.

**BTW:** I'm not pushing anyone to spend (much) time on this. My gut tells me (yeah, I know) that this one might be related to running a rather old system. I'll start "kicking & screaming" once I upgrade and the issue is still there :-)))

**Comment by Nilvus** [comment]
Thanks for your precise feedback. I miss line about all dirs deleted (quite rare to see that one on an issue, a good point for you and a good miss for me ;-)!) So you OP is exactly what to do to avoid conflicts between old code and new one. So my suggestions are discarded.

As you talk about your old system, I read again your Gtk release and it's a quite old one. So remains possible that font-feature-setting CSS value was not supported correctly on that release (or bugged) on your Gtk release. I use Debian on my side to work on CSS and improve it but with Debian Sid, so rolling release of Debian!

I search on Gtk repository and I found that this had been implemented on a Gtk 3.24 release about 2 years ago and your Gtk release seems that to be near 4 years ago. So that explains your issue and confirm that it's due to your old release.
Found that issue for example: https://gitlab.gnome.org/GNOME/gtk/-/issues/41
And Gtk support added by that: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1477

I so close your issue and propose to add an info on release notes for users like you with old Gtk release. Will try to find what is the Gtk release who introduce merge above.

Thanks for all your precise infos.

**Comment by Nilvus** [comment]
I found minimum Gtk release for that setting: 3.24.15. See: https://download.gnome.org/sources/gtk+/3.24/gtk%2B-3.24.15.news

**Comment by parafin** [comment]
Then we need to bump minimal GTK version in documentation, cmake and release notes (Changed Dependencies section, which once again sadly wasn’t populated at all, but still remains for some reason).

**Comment by Nilvus** [comment]
I agree and preparing a PR for that.

**Comment by TurboGit** [comment]
I reopen to make sure the check for proper min Gtk version is done in CMake.

**Comment by jade-nl** [comment]
Most satisfactory outcome for this specific issue. 

Closing this one as https://github.com/darktable-org/darktable/pull/13169 takes care of this.

**Comment by jade-nl** [comment]
Just read that @TurboGit reopend this one, so I seem to have jumped the gun.

Close at your convenience!
