### ISSUE TITLE
Listed dependency on libavif version is, I think, incorrect

### ISSUE THREAD

**Issue by phrrk** [darktable-org/darktable#13164]
It is stated that building darktable with avif functionality is dependent on the installed libavif being >= version 0.8.2.  Following this commit #https://github.com/darktable-org/darktable/pull/12889/commits/acc7795d96999a2b7b38f64daed6ed4e79c0c1a5 This is no longer correct, and imageio_avif.c will not compile because avifStrictFlags  is not defined for this version.  It looks like the first time this flag appears is in version version 0.9.2.

**Comment by victoryforce** [comment]
Yes, you are right. Thanks for noticing. The minimum version of libavif should be 0.9.1.

**Comment by kmilos** [comment]
@victoryforce Do we want to raise the bar (what is e.g. the min Debian/Ubuntu shipping this version), or ifdef this? Sorry, not near my machine for days to check...

**Comment by victoryforce** [comment]
@kmilos  Debian has the required version since Debian 11 (via Debian 11 backports). For Ubuntu, Repology shows the required version since Ubuntu 22.04 and nothing for older distros, probably earlier versions of Ubuntu do not have libavif in the system repo. Fedora has the required version starting with Fedora 35.

**Comment by kmilos** [comment]
Thanks for checking! Fairly recent then, and not ideal...

Rather than excluding users or older distros, maybe it's ok to ifdef this particular call, so they can keep using older libavif with the dt 4.0 behaviour?
