### ISSUE TITLE
No more yes/no translation on Gtk dialogs popups

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#13289]
**Describe the bug/issue**

On Gtk dialog confirmation popup, yes/no are no more translate. I see that in French and it's the same at least on Italian version and Deutsch languages. It's so not a French translation issue.

**To Reproduce**
1. Select at least one image (be in another language than english of course)
2. Click on delete image (or remove images, the issue works on both) to delete it from darktable
3. See popup with yes/no and not text on language selected.

**Expected behavior**

Just have translated text.

**Screenshots**

![image](https://user-images.githubusercontent.com/45535283/211152891-4a7737c5-ec4c-45ae-8797-9103f44c65fa.png)

**Platform**

* darktable version : last master

**Comment by dterrahe** [comment]
#13248 put a _ marker in the text to indicate which letter can be used as a shortcut to pressing the button. The translations haven't been updated yet to _also_ put a marker that is correct for the respective languages. Once these have been updated as per normal procedure, everything will be alright again. @TurboGit are translations checked before 4.2.1? Otherwise you might want to revert that for the 4.2 branch.

**Comment by TurboGit** [comment]
Yes, we have some small changes in strings so the translation will be updated. Maybe not in all languages but that's really a minor issue that we have to live with for minor releases.

**Comment by TurboGit** [comment]
Fixed in French translation in master & 4.2 branch. Will be fixed eventually in other languages.

**Comment by Nilvus** [comment]
Thanks guys for your quick and precise answer (and fix!).
