### ISSUE TITLE
import: ignore Exif rating = TRUE is ignored for raw files containing XMP.xmp.Rating

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#13286]
during import 'ignore Exif rating = TRUE ' is ignored for raw files containing XMP.xmp.Rating so during import the custom set 'initial rating' value  is ignored:
![image](https://user-images.githubusercontent.com/39386816/211028699-ecbc37e6-44b3-4a62-8e7d-61b9fef3ca5c.png) 

**To Reproduce**
1. set "add to library" preferences:  check 'ignore exif rating' & set initial rating to 2 (some cameras uses a default rating 1) 
2. add cr3 file to library (e.g. https://raw.pixls.us/getfile.php/4662/nice/Canon%20-%20Canon%20EOS%20R6%20-%203:2.CR3)
3. check initial rating: 0 stars

some further checks:
Canon 5DmIV rating **not ok** (contains XMP.xmp.Rating 0): https://raw.pixls.us/getfile.php/983/nice/Canon%20-%20EOS%205D%20Mark%20IV%20-%20RAW%20(3:2).CR2
Nikon Z6 rating **not ok** (contains XMP.xmp.Rating 0): https://raw.pixls.us/getfile.php/3581/nice/Nikon%20-%20Z%206%20-%2014bit%20compressed%20(3:2).NEF
Nikon D7200 rating **ok** (doesn't contain XMP.xmp.Rating): https://raw.pixls.us/getfile.php/832/nice/Nikon%20-%20D7200%20-%2014bit%20compressed%20(Lossless)%20(3:2).NEF)

**Which commit introduced the error**
need to bisect - checked my older builds: issue was introduced between 20.10. (darktable-4.1.0+719\~g9ec4d3dce) and 06.11. (darktable-4.1.0+860\~g64a61e52e)

**Platform**
* darktable version : > darktable-4.1.0+860~g64a61e52e
* OS                : OSx

**Comment by zisoft** [comment]
I modified `./src/common/exif.cc` so that the _ignore EXIF rating_ checkbox is handled for XMP.xmp.Rating too and now it works as I would expect it to work:

if _ignore EXIF rating_ is checked, the rating gets overridden by the import settings (even if there is an xmp file with a rating besides the image file)

Maybe the import settings checkbox should be renamed to reflect that? (_igonore EXIF/XMP rating_)

I would like to ask for other opinions.
