### ISSUE TITLE
Tooltips at the bottom not visible

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#13312]
**Describe the bug/issue**
When hovering buttons near the bottom of the screen (e.g. culling), the tooltip is not visible

**To Reproduce**
1. Go to lighttable
2. hide filmstrip but show bottom panel
3. hover culling icon
5. tooltip is shown underneath -> outside of the window -> not visible

**Expected behavior**
Show the tooltip above, if there is not enough space underneath
(as it was until 4.0.1)

**Screencast**
[tooltip-4.2_NOK.webm](https://user-images.githubusercontent.com/5677563/211423923-9d8e2922-46e0-4b04-b098-a9ed436ebba1.webm)
[tooltip-4.01_OK.webm](https://user-images.githubusercontent.com/5677563/211423920-913b08be-98c2-4c34-867b-cd501e811873.webm)

**Platform**
* darktable version : 4.2.0
* OS : Manjaro Linux
* Desktop : Gnome 43.1
* Memory : 32 GB
* OpenCL installed : no
* OpenCL activated : no
* Graphics card : Mesa Intel® HD Graphics 630 (KBL GT2)
* Graphics driver : video-linux
* HiDPI (scale 200%)

**Comment by dterrahe** [comment]
#10853 ?

**Comment by quovadit** [comment]
thanks for the hint @dterrahe, forcing darktable to run on Xwayland with `GDK_BACKEND=x11 darktable` solves the issue

(same for #13311)

**Comment by Nilvus** [comment]
We should now have at least 3 issues now (2 are what you just posted @quovadit) related to #10853. Seems that native Wayland support is far from ready (and Wayland still do not have color management support). Maybe reverting #10853 should be done? Maybe that PR was proposed too early.

**Comment by dterrahe** [comment]
The problem is that gtk3 breaks in some places under wayland (tooltips placement and screen sizes, which may be the same issue). Trying to work around this may not be possible but is inadvisable anyway and gtk3 may never receive fixes in this area. So this may stay "too early" until #13236. If it is possible to revert #10853 and still allow users to force wayland (for those who see in benefit in that) then at least the bugs are not inflicted upon unsuspecting victims (and we might see fewer duplicates).

**Comment by parafin** [comment]
GDK_BACKEND=wayland can be used to force wayland, if #10853 is reverted

**Comment by kubrickfr** [comment]
> and Wayland still do not have color management support

It's a bit of an exageration. Wayland does not let darktable chose a color profile for surfaces, but most compositors support display calibration via colord.
Which means that if your screen is correctly calibrated, your images will still display correctly, and you can do gamut checking, it's just that you cannot do softproofing.
So you can edit, display, check (to some extent) and print your pictures and they will look perfectly fine. Just to set the record straight.

**Comment by Nilvus** [comment]
> > and Wayland still do not have color management support
> 
> It's a bit of an exageration. Wayland does not let darktable chose a color profile for surfaces, but most compositors support display calibration via colord. Which means that if your screen is correctly calibrated, your images will still display correctly, and you can do gamut checking, it's just that you cannot do softproofing. So you can edit, display, check (to some extent) and print your pictures and they will look perfectly fine. Just to set the record straight.

Wayland have a PR as WIP since about 3 years (and 2 years for mutter for example) about adding color management support. So, I don't see any exageration (or maybe Wayland developers themself exagerate). It's just a fact, even if you're right about all your words after "exageration". Exageration is just your interpretation.

See:
https://www.collabora.com/news-and-blog/blog/2020/11/19/developing-wayland-color-management-and-high-dynamic-range/
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/14
https://gitlab.gnome.org/GNOME/mutter/-/issues/1360

**Comment by kubrickfr** [comment]
Wayland is just the protocol that defines how applications communicate with the compositor.
The references you quote are correct: the wayland protocol does not define a way for applications to tell the compositor about anything color management related.
Compositors, on the other hand, can implement device color calibration, which most do.
So all I'm saying is: on darktable on wayland cannot do soft proofing. AFAIK that's the only feature that is not available in the particular context of darktable.
