### ISSUE TITLE
Rework the histogram gui

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#13338]
If #13275 gets merged, I am thinking to further refactor the histogram gui (as also suggested by  @dterrahe), in order to make it simpler and also easier to automate with actions.
My proposal is the following:

1) avoid the buttons cycling across many options, those are annoying. Replace with pop over menus, triggered by buttons (combo boxes are an alternative, but take too much room I believe.
So, for example

![image](https://user-images.githubusercontent.com/43290988/212476633-19f7aa72-55ce-4bd5-a296-8082c2e39848.png)

2) I would leave only one button on the left side, for mode switching. Actually we could put in the same pop over menu the three vectorscope options, so saving one button

3) On the right side (only visible when appropriate):

- orientation button
- linear / log button
- r/b/g channels
- color harmony pop over menu
- maybe, a brightness button (normal / high), as many find the scopes too dim

Feedback is welcome

**Comment by dterrahe** [comment]
> 1. Replace with pop over menus

Would not be my preferred approach. I'd show a row of 4 togglebuttons top-left, one for each of the modes.
Drawbacks: 
- takes more space (but remember this is only when mouse-overed).
- the non-active buttons need to be toggled off (trivial code. With one mode button you might want to change the icon?)
Advantages:
- easier to see which one is active (both icon and position)
- trivial to define and map shortcuts (one line and visual mapping works; also midi button lights indicate active one)
- individual tooltips could describe modes better.
- easier to rotate through if you often want to see all/a few of the histograms:
   move-click-move-click-move-click-move-click shows all, whereas with a popover/menu you'd have
   move-click-move-click x4 (and the moves are larger, back-and-forth, and the move target is only visible once the menu is open)

With your approach (if not using dropdown) actions need to be individually coded and if you want to have shortcuts show up in the tooltip for the popover-button, you need to define a dedicated action type with _elements_ for the different modes. This will be much harder for the casual user to map.

My second choice would be bauhaus combo, as then you do get a lot of shortcut functionality for free and you can scroll through options. But arguably icons top-left is "prettier" than text.

**Comment by Mark-64** [comment]
A row of radio buttons on the left is not a problem, I already drafted it

![image](https://user-images.githubusercontent.com/43290988/212479537-8d17f87f-1d09-4aa5-b721-72b185c94373.png)

By the way I implemented the `GtkDarktableRadioButtonClass`, so no need to toggle off manually the buttons. This  code could be reused in several other places in the gui. But...
Can't put there also the three vectorscope options, too many buttons.
Also the same approach is not doable with color harmony choice, there are 9 options.
I agree with your observations, but pop over menus are surely more compact

**Comment by dterrahe** [comment]
> This code could be reused in several other places in the gui.

I think many other places where maximum of 1 button in a group can be active also allows _0_ buttons to be active, so not really radio buttons. What uses are you thinking of?

> the same approach is not doable with color harmony choice, there are 9 options.

Just brainstorming here (without even having compiled that PR and not knowing anything about color harmonies); would it make sense to organise those 9 options in a 4x3 grid (bottom-right or toggled on/of with an always-shown button) with choices in each column having the same number of areas (so Monochromatic/Complementary&Dyad/Analogous&Split Complementary&Triad/Tetrad). Might be easier to visually pick the one you are after if the icons+tooltips are clear (unless the names are more self-explanatory than they seem to me). Again I'm just worried that if people regularly try out a few of those options to see which one fits (but I don't know if that is how this is going to be used at all!) then repeatedly opening a dropdown menu is going to be inconvenient.

**Comment by TurboGit** [comment]
@Mark-64 : I also prefer the buttons over the pop-up and this will be quite handy because the fact that the tooltip describes the next scope to be activated has always confused me.

**Comment by TurboGit** [comment]
@Mark-64 : No worry I really see your work (#13275) on vectorscope to be merged. This is planned for 4.4 on my side and as far as I know there was no veto on this nice work.

**Comment by Mark-64** [comment]
> I think many other places where maximum of 1 button in a group can be active also allows _0_ buttons to be active, so not really radio buttons. What uses are you thinking of?

![image](https://user-images.githubusercontent.com/43290988/212487797-c6f867d0-e9cc-4be5-a93d-6d86c693d5bd.png)

![image](https://user-images.githubusercontent.com/43290988/212487818-dea37c23-cea4-4a56-b980-21eb02b662a4.png)

![image](https://user-images.githubusercontent.com/43290988/212487843-964d727b-2e14-4579-bd4e-d2167bf32fa3.png)

Zero active buttons can be done with a dummy radio button that is not visualized.
Just for fun, I might try to apply the new class to those cases, let me see if I get a simpler code

But now we are off-topic

**Comment by Mark-64** [comment]
> I also prefer the buttons over the pop-up

Deal done, then.



> would it make sense to organise those 9 options in a 4x3 grid

An array of buttons? Maybe, but then 9 different icons to be designed.

**Comment by dterrahe** [comment]
> Zero active buttons can be done with a dummy radio button that is not visualized.

As long as clicking the active button again deselects it and selects the hidden dummy...

Definitely the code for the instances you highlight can use a cleanup (so much so that I never found the stomach for it).
 
> But now we are off-topic

Sure, but...
If you do decide to base this off a new GtkDarktableRadioButtonClass it would make sense to give some thought to setting up actions automatically (without needing separate calls to do it) and to use a new `_action_def_radiobutton` (separate from `dt_action_def_button` or `dt_action_def_toggle`) that has next/previous _effects_ (in 2nd and 3rd place; like _dt_action_effect_selection_); this would allow using scroll (or any other shortcut) to cycle through all options.

**Comment by HSUfineprint** [comment]
Could we put all view selection buttons on the left, and additional functions on the right? And use an auto drop down group menu when mouse hover? If that so, there will be only 3 buttons on the left, histogram/waveform/vectorscope, while mouse on the module. Another thing is rgb parade is a kind of waveform, should be in the same group menu, just like u*v*/AzBz/RYB in a vectorscope group. The menu is auto drop down when mouse on the selection buttons. No additional click needed. I could draw some schematic diagram later.

**Comment by parafin** [comment]
auto drop-down menu is a pain to use when it disappears unexpectedly

**Comment by HSUfineprint** [comment]
some ideas

1. Scope selection buttons on the left, 3 groups are "histogram" "waveform" "vectorscope".
2. When mouse hover, automatically show buttons in the group, no additional clicking needed.
  _another option: group icon is not auto expanding menu but a switcher, change scope view in it's group_
3. After choosing a scope view, the group button switched as well for quick selecting back.
   _choosing rgb parade then others, waveform button will stay rgb parade, click it can switch to rgb parade directly_
4. Function buttons on the right, show available buttons only.
5. Most function buttons are switch, no auto drop-down.
6. Combined color harmony display on/off and selection, use auto drop-down menu and harmony icons.
7. After choosing a harmony guide, menu icon changed as well, but icons won't switch, that keeps positions the same.
8. When mouse hover harmony icons, show corresponding names at the right bottom (or use toolstip).
  _Can also show actual sectors if resource consumption is insignificant_
9. If color harmony guide is on, when mouse is out of module only show sectors, more info when mouse hover.
10. If menu disappears unexpectedly is a big concern, harmony icon could be a menu open button as well, but it can still show current harmony guide.
  _Another option is 3x3 arrangement icons, easy to keep mouse in the focus area._
11. The toolstip should be the description of current scope, not the hint of next scope in sequence.

![scope design-selection](https://user-images.githubusercontent.com/109933528/212836224-edd9da03-d0f2-42b6-b774-7152f6458776.png)

![scope design-all](https://user-images.githubusercontent.com/109933528/212836266-966c1457-f1f9-4654-898e-651437e063a1.png)

![scope design-harmony](https://user-images.githubusercontent.com/109933528/212851753-0498b202-cb14-4b54-b624-aeb1e75772b7.png)

main feature:
- Make all scopes in 3 same type groups
  _radio buttons are easier to use, but it's too crowded_
- Use buttons rather than text menu
- Keep one click operation
- Redesign buttons
- Jzazbz button: Cartesian coordinates and z
- CIELUV button: iconic shape
  _I know the shape is u'v' not u* v*, but it's more recognizable and they are all part of CIELUV_
- RYB button: classic 3 color circle style
- Using color sectors as denotation of color harmony
  _color swatch icon in #13275 could be misleading, it usually means spot color control_ 

All buttons are here
![scope design-buttons](https://user-images.githubusercontent.com/109933528/212843230-2034eb9e-400c-4c71-9fbb-e3bb550ce957.png)

**Comment by TurboGit** [comment]
@HSUfineprint : I like the whole design! @Mark-64: What do you think?

**Comment by Mark-64** [comment]
Lot of material here, I need some time to digest...

**Comment by Mark-64** [comment]
I don't have clear how the button groups are supposed to work in this proposal, there are different options.
Let's take the histogram group as an example. Assume ryb is active, the button shows the corresponding icon. When mouse hover, we want to visualize:
1) the active ryb button and, underneath, the remaining inactive buttons (jzazbz, luv)
2) the active ryb button and, underneath, all the three buttons (jzazbz, luv, ryb)
3) the three buttons, where ryb is shown active

Pros and Cons
1) is more compact, but the position of the buttons is variable, which could be annoying especially for the color harmony group
2) the positions are fixed, but the active button is shown twice
3) fixed positions and compact, but the first button changes when mouse hover

I just don't want to spend time coding layouts which are then disliked

**Comment by dtorop** [comment]
So glad to see this conversation/work is happening. It looks like you all are near to consensus/plan, so don't want to mess with this, but a few random thoughts:

UI bikeshedding with apologies: At some point (if my memory is right?) Nautilus head a button in the top bar that switched between icon/list/tree view, but when long-pressed it showed a drop-down with a range of sub-options. Would some sort of custom widget like that be useful? Granted, that was for a space-constrained top toolbar, where it made sense to pack as many features as possible into a small space. And there's lots of space in the histogram.

But: The current buttons-appearing-on-mouseover GUI is a relic of a much simpler histogram. Early on, the choices were just logarithmic/linear and whether to turn on/off R/G/B channels. For that, it made sense for the buttons to disappear as in general the histogram was a set-it-and-forget-it feature (and selective display of channels would be rarely used). Once the waveform was added, it made _some_ sense to add one more button to swap histogram/waveform, as most people wanted either/or. And again the buttons/GUI could otherwise stay out of the way. Now we're in a much different situation, where people might really want to switch between waveform, parade, and vectorscope, or between horizontal/vertical waveform, or between JzAzBz or RYB display. Does this minimal UI serve us anymore? Should we do something as banal as having a bar at the side or bottom with dropdowns/buttons to turn on/off features and set modes? The current UI code really goes against the grain of what GTK allows, in order to get the current look. It uses GtkOverlay in  a non-standard way. And the use of GtkStack and hiding/showing of various buttons is hard to keep track of, and error-prone.

And further: Would it be possible to integrate the long-standing (and totally valid) requests for displaying both waveform and vectorscope histograms at once? Instead of making a sensible UI for the current histogram + waveform + RGB parade + vectorscope combo, should we split out lib/histogram.c into four panel elements (lib/histogram.c, lib/waveform.c, lib/parade.c, lib/vectorscope.c)? And have actions (which can be initiated via both keypress and buttons in the bottom toolbar) to turn on/off any of those scopes, and/or move them between the left and right panel? (Arguably, waveform and RGB parade are so similar, that they could be in the same panel module. Regardless, the code to calculate the waveform and vectorscope could move out to common/waveform.c and comment/vectorscope.c, to make lib/histogram.c less huge.)

**Comment by HSUfineprint** [comment]
My original idea is show active icon on the top, group icon. And show remaining inactive icons when mouse over.

Let's say vectorscope, if default sequence is azbz → LUV → RYB, it shows inactive azbz button. When I move mouse over, it shows LUV and RYB follow after azbz. If I click the LUV button, scope changes and group icon becomes LUV. If mouse over again, show gray-out inactive azbz and RYB icons. There are two icons in waveform group, and 3 icon in vectorscope group. I think that's okay for switching icon positions. (idea 3 in https://github.com/darktable-org/darktable/issues/13338#issuecomment-1385143862)

But color harmony is deferent, all 7 icons are fixed, will not change position after selecting. But I'm not sure about the default sequence of them. Always show all harmony buttons after group icon when mouse over. That will be help on remembering harmony position and quick selection. (idea 7 and pic. 3 in https://github.com/darktable-org/darktable/issues/13338#issuecomment-1385143862) And 3x3 icons may help menu display constancy, avoid disappearing unexpectedly.

We definitely need consensus here before actually coding works. Any suggestions for improving UI behaver are welcome.

**Comment by spaceChRiS** [comment]
> should we split out lib/histogram.c into four panel elements

Wouldn't it fit more into darktable's design to do it the other way 'round, to have the possibility to duplicate the histogram “module” and select another view in the 2nd instance? This would also reduce the clutter for those that only require one diagram shown at a time, which is probably the more common use case, in particular as vertical screen real estate is scarce …

**Comment by dtorop** [comment]
> > should we split out lib/histogram.c into four panel elements
> 
> Wouldn't it fit more into darktable's design to do it the other way 'round, to have the possibility to duplicate the histogram “module” and select another view in the 2nd instance?

A good point.

My memory is that it may take some attention to properly encapsulate the histogram lib so that it can be duplicated. And that the iop code (the right panel processing modules) is built to allow for an iop to be duplicated and dragged, but the lib code (histogram/history/metadata/navigation/etc.) doesn't have this capability built.

So to do this would take some more coding!

**Comment by spaceChRiS** [comment]
> but instead a series of on/off toggles on a toolbar to display either zero or one of each sort of scope

I understand your reasoning, but implementing it that way would remove the possibility to toggle between different scopes. It would always be “one on, the other off”. That would be for me the biggest drawback.

> Would we ever want >= 2 waveform scopes?

Once the power is given to The People[tm], I hear them asking for side-by-side linear and log histogram, or different vector scope views :grin: … That does not mean that I am all against multiple scopes, as you know, I am all for new features, but the current functionality is good, the one proposed in this thread with direct access to the different scopes instead of cycling through is great, and this functionality IMHO should not be removed by a multi-scope implementation.

> the GUI to control this will be different than the GUI for iops

Most probably yes, and I don't see an issue there. It's only about requiring two mouse clicks to switch to another scope with on/off buttons instead of one as proposed here. Maybe, an option would be to add a “sticky” feature (e.g. pin icon, or long-press action) next to the buttons that make this scope permanent …

**Comment by Mark-64** [comment]
Interesting discussion.
Waiting for someone willing to completely redesign the histogram lib, I will propose shortly a small PR with what I consider a usability improvement, as follows

![image](https://user-images.githubusercontent.com/43290988/213987740-e85d6587-e22d-4477-a452-ced4367f64a9.png)

A group of 4 radio buttons on the left controlling the main mode, removing the confusing "next mode" button. Those are easy to understand and to shortcut, with a fixed tooltip.
On the right, a variable group of buttons, which are the options for each specific mode
- linear / log scale
- orientation
- rbg channes
- color harmonies
- maybe, a brightness button (normal / high)

@HSUfineprint Your idea look nice in principle, and I spent quite some time trying to implement it, but from my half-working prototype, I see that:
- usability is not better than the pop over menu I proposed initially, Yes you save one click with the mouse hover behavior, but the other concerns highlighted by @dterrahe and @parafin remain
- the gui implementation is already quite hacky, with buttons on gtk overlays and the signals to manage the show/hide of the inactive buttons on mouse hover are a nightmare (at least for me). I couldn't manage to get a decent solution actually

For color harmonies I still have to think about a solution, maybe there a pop over menu is justified.

**Comment by dtorop** [comment]
@spaceChRiS:

> implementing it that way [via toolbar with a button for each scpe] would remove the possibility to toggle between different scopes. It would always be “one on, the other off”. That would be for me the biggest drawback

As each button would be tied to a particular lib implementing that scope in a widget, it would be the reverse: Clicking a button would hide/show that particular scope (histogram, waveform, rgbparade, vectorscope), and not alter any others that are shown. There _could_ be an additional UI feature to create the "one on, the other off" functionality. E.g. control-clicking a scope type button would show that scope and hide all the others.

> Once the power is given to The People[tm], I hear them asking for side-by-side linear and log histogram, or different vector scope views

Side-by-side is a whole other thing -- and more work on the core UI. But yes, that would be very nice. And yes, you're right, I could imagine someone would want to see different views of the same type of scope. I guess at some point it would be a re-implementation of a general purpose tiling window manager!

> the one proposed in this thread with direct access to the different scopes instead of cycling through is great, and this functionality IMHO should not be removed by a multi-scope implementation

Absolutely.

@Mark-64:

> Waiting for someone willing to completely redesign the histogram lib, I will propose shortly a small PR with what I consider a usability improvement, as follows

A contained usability improvement PR is a great idea. As to a complete redesign, I agree an overhaul is needed of the underpinnings, as it has grown so much. This can be orthogonal to the UI changes, or could be done with a mind to allowing for future UI improvements. Though I'm interested in this work, I don't think I could take it on for months, at best.

And there are also yet more possible scopes -- types and subvariants. The ideal UI change, whether usability improvement now or totally overhaul, would open the door for adding others in a way that keeps the code sane and the UI plausible.

**Comment by HSUfineprint** [comment]
The current propose has some issues I concern.

- **scope icons on the left cannot fully control scope choices**
_Waveform/rgb parade has independent icon, but vectorscop is not. It's an unbalanced menu. The icon level and logic has confusion. Another thing is it needs more clicks when you want to use RYB or other vectscopes._

- **color harmony button and separated menu means additional clicks**
_It's not that clean and easy to use than combining them in one button. Color harmony icons mixed texts menu also makes UI un-consistent._

- **the color swatch icon..**
_Already explained, color swatch means spot color control in most software but not color harmony._

- **vectorscope be rotated**
_Hue of azbz and u* v* scope is not the same with their original color spaces. But it might need another PR._

**Comment by Mark-64** [comment]
> * Waveform/rgb parade has independent icon, but vectorscope is not.

We could easily have 6 radio buttons instead of 4, but the logic here is to put on the left the buttons to switch among the more frequently used modes. We can discuss if waveform/parade are two different variants of the same view and deserve two different radio buttons (in my view they do), but surely I can't imagine a use case for switching frequently between color spaces in vectorscope. I believe people tend to use one type only and only occasionally switch to other types. You wanted to hide those less frequently used buttons (but this creates other issues), I want to separate them from the main buttons, it's not so much different.


> * color swatch means spot color control

Yes, but icons redesign will be the last thing. I like some of your proposed icons, but bear in mind that dt cairo icons are really a handful of pixels, especially on LoDPI displays and often the result is not in line with expectations...


> * Hue of azbz and u* v* scope is not the same with their original color spaces

From comments in the code, this has been a conscious design choice that I don't want to touch.

**Comment by spaceChRiS** [comment]
> I can't imagine a use case for switching frequently between color spaces in vectorscope

I guess that would mean that the “right side buttons” need to save their state during one edit, one session, and probably even across sessions for an efficient workflow. While this seems to be a big step compared to now, I would guess that this becomes more obvious with a new left side/right side scheme.

**Comment by HSUfineprint** [comment]
> We could easily have 6 radio buttons instead of 4, but the logic here is to put on the left the buttons to switch among the more frequently used modes.

That's why I use groups. And it can switch in all scopes, not only frequently used scopes but all scopes.

> I believe people tend to use one type only and only occasionally switch to other types.

Any choice comes with click, not only switching between them. If default scope is azbz, you need another click to change it to RYB, that's the point.

> You wanted to hide those less frequently used buttons (but this creates other issues), I want to separate them from the main buttons, it's not so much different.

Hiding buttons is not my intention, separating / organizing scopes is. Simply using 6 button is easiest way. Can't use it just because it will be too crowded.

> icons redesign will be the last thing. I like some of your proposed icons, but bear in mind that dt cairo icons are really a handful of pixels, especially on LoDPI displays and often the result is not in line with expectations...

I can provide all icon file if that will do any help. Surely, they are vector graphics and might need and fine turning on small scales for best visibility. Most important is color swatch icon will cause misunderstanding.

> this has been a conscious design choice that I don't want to touch

Understood that. It should be discussed in another issue anyway.
