### ISSUE TITLE
Drawn masks not saved in module presets and styles

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#13346]
**Describe the bug/issue**

Currently in DT 4.2 as well as on the master branch drawn masks are not saved within module presets, this limits presets to parametric masks only.
Interestingly enough, a reference to the shape is still saved. This can be checked by creating a preset, e.g. in the exposure module, adding a drawn mask with one shape, saving it to a preset and then creating a new instance and setting this newly created preset. Then this shape is used again, as expected.

However if you open up another image and want to apply this preset, the drawn mask shapes will be missing.

**Expected behavior**

Drawn mask & shapes are saved with presets.

**Platform**

* darktable version : 4.3.0+111~gca5265a51-dirty
* OS                : Linux
* Linux - Distro    : Ubuntu 22.04
* Memory            : 32 GB
* Graphics card     : AMD Radeon rx 5700 xt 
* Graphics driver   : amdgpu
* OpenCL installed  : yes
* OpenCL activated  : yes

**Comment by MStraeten** [comment]
drawn masks depends on geometric content of  the image - so usually can't be taken over in general. Parametric masks just depends on tonal/color/frequence information and can be applied for different images.
So the first doesn't make sense to be persisted in presets

**Comment by da-phil** [comment]
Of course generally you're right, however - at least for me - there are use-cases where you have presets which are specific for a camera, hence the geometry / image size is always the same. E.g. a preset for getting rid of a vignette for a lens which is neither covered in lensfun, nor writes correction data into the exif tag.
So I agree that it is a rather exotic use-case, but if more people are interested in it and it is not a big effort we could still think about, right?

**Comment by gi-man** [comment]
But you started this as a bug. But you are really asking for a feature request.

**Comment by MStraeten** [comment]
if it’s the intention to have reusable masks, then it might be better to enable occasional persisting of masks using the mask manager. But that might be not that simple since the drawn masks are relative to the image geometry (size, orientation,…) they were designed for. At least a quick (and dirty) solution for an edge case resulting in side effects occurring in the majority of use cases is very unlikely to be implemented in darktable ;)

**Comment by da-phil** [comment]
> But you started this as a bug. But you are really asking for a feature request.

You're right, in this case a feature request will be more appropriate. Then I'll close this defect and will write a feature request sometime with more specific information of how it could be implemented.

**Comment by TurboGit** [comment]
Presets are to be reused in long terms, so masks are not good to be kept there. For similar pictures you can copy/paste a module and there the mask is copied. So that means:

1. use the preset to have the global effect applied on the first image
2. add a mask to the first image for local adjustment 
3. copy/paste to the series of (mostly) identical images

This has already been discussed, it is not a good idea to have the drawn masks stored with the preset.
