### ISSUE TITLE
Overreliance on tooltips

### ISSUE THREAD

**Issue by prokoudine** [darktable-org/darktable#13383]
Since @dterrahe's suggestion to make small manageable proposals and group them makes a lot of sense to me, here is one of those.

As of today, various parts of darktable rely solely on tooltips to give users information how various things can be operated. In a number of cases, this means users will miss something or won't even get the information when they do read it. I've seen tooltips and other similar means failing to deliver vital info on many occasions in all kinds of applications, perhaps the most notorious ones being 1) the Ctrl+Alt+Drag combination to move selected pixels in GIMP, as very few people read the statusbar hint, 2) the tooltip in Ardour's mixer channel that tells the user to right-click to add a plugin, but shows up in a very specific region that is only 5px wide and 180px wide on a HiDPI display.

Here are the cases in darktable that I can think of immediately:

1. Histogram's height. By default, the histogram widget takes a tad too much space on 2560x1440 vertically, which leaves less space for controls of modules. It's possible to change that, but the information is in the tooltip. It _is_ possible to do all sorts of wonderful things like looking at the height of the active screen and setting it to a particular value to make better defaults. But it's also possible to make this feature more discoverable. This could be solved in a number of ways. One approach is to add scale/zoom buttons in the top left corner so that they wouldn't move when the vertical size changes. Just like other widgets in the histogram, they would only be visible on histogram hover. Possible counter-arguments: 1) is it something that is done as frequently as changing the type of the histogram? 2) if they aren't, how much of an obstruction to viewing the entire histogram would displaying them present while the pointer is over the histogram? Alternatively, if darktable ever gets rewritten with something like libpanel so that the histogram is inside a container with user-tweakable size, changing the height of the histogram would merely involve dragging its bottom border up/down, no extra buttons needed as long as the border stands out and hover on it changes the mouse pointer accordingly. Not a critical issue, just something to consider.

2. Navigation/Zoom presets. The drop-down list with zoom presets is activated by pressing a triangular button that says "Ctrl+Shift+N" in the tooltip (that's the entire tooltip) and is next to a tiny icon that has no explanation. At the very least, the tooltip should say what this widget does and that clicking here would open a list of zoom presets. I think it's entirely possible to come up with an even better solution (I'd need to think of one), but for now let's fix the tooltip :) Something like "Click to select zoom level from a preset, Ctrl+Shift+N to enable/disable the navigator" should do.

3. Rotation/Perspective module has a somewhat inconsistent interaction model. The rotation model is: read the tooltip for a slider, go to viewport, drag a line. The perspective model has variations that make sense in each respective case:

- Hover a button, read the tooltip, click the button, draw multiple lines
- Hover a button, read the tooltip, click the button, see an automatically created box, edit it
- Hover a button, read the tooltip, click the button, have automatic lines created for you, no more editing

The middle ground for both rotation and perspective correction would be having a button to click. I haven't seen one common solution across applications what to do next: some imply drawing a horizon line from scratch (e.g. Luminar), others render a segment to get started from (e.g. DxO PhotoLab). But darktable already has at least two modules that render on-canvas controls upon enabling these modules: graduated density and vignetting. And chances are that crop is joining them soon. So maybe it's rather the latter.

The "shortcut" solution would be, much like with the cropping proposal, to have a button in the top toolbar to activate rotation and automatically draw an initial horizon line. And maybe add a split button right next to it to activate one of perspective correction modes. Very rough sketch just to throw in an idea:

![image](https://user-images.githubusercontent.com/57467/213522500-62ee2812-77ba-48fc-9391-3c307251841a.png)

That said, the top toolbar - if it's interesting - should have its own proposal.

**Comment by dterrahe** [comment]
re 1) there is already a `dt_ui_scroll_wrap` that adds the ctrl+scroll = resize functionality to a whole bunch of text and list widgets. It can probably be extended to add a small bar underneath that can be dragged to resize. And then it can be somewhat generalised to also include the graphs that currently implement this functionality themselves.

The two drawbacks (that have curbed my enthusiasm for this mini project so far are that
- it takes extra space (for example between all text entry fields in the metadata). Which could easily trigger multiple rounds of CSS adjustments. Also see "will to live".
- It might make it trickier to manipulate the lower edge of a widget. If, just as an example, you've dragged the curve in color zones all the way to the bottom, it could be a little harder to pick it up again without inadvertently shrinking the whole widget.
No show stoppers as far as I'm concerned. Just stuff that might make implementing more tedious/less fun. Technical complexities could be a later issue.

re 2) It's worse; the navigation widget has no tooltip _at all_! (The ctrl+shift+N tooltip is auto-generated by the shortcut system). And that's a pity, because explaining that you could use it to move around in a zoomed image could also be helpful. The default zoom is "fit to screen" and shown as just [ ]. Having a percentage here would presumably convey _some_ indication of purpose. The "dropdown" at the bottom right is actually custom drawn onto the canvas, not a standard combobox. So you can't easily visually define shortcuts to it either. Could be cleaned up.

re 3) as #13353 already shows, people will have different opinions here.
How I use right-click-drag is; move mouse to top corner of wall, right-click hold, drag to bottom corner of same wall, release. If I had to use a default vertical or horizontal line that was already on the screen, I'd have to move to one end of that line, click+hold, drag to top corner, release, move to other end of line, click+hold, drag to bottom corner, release. Maybe every time I release a corner the image will be redrawn (?) (which could be expensive/time consuming), so maybe the points involved jump around?
I do something like this when I want to straighten _all_ corners of the wall; that's the middle (manual) structure button. I find it more tedious (but that one at least gives a more sophisticated result). If I were to lose the current way it works I would be sad. I would certainly not spend _my_ time and effort to get to that state. But maybe you are having something else in mind or would not mind having both approaches side-by-side (more complexity, double the bug potential, or more, since developers only test the approach they themselves use, more confusion for new users)?
If we move a line around (rather than drawing from scratch) what happens to that line when moving between images? Resets to default? Or when one of the other modes (also) changes the rotation? Maybe more questions, I don't know. I'm not saying that all those questions don't have obvious answers, but it may be that all of them explicitly need to be implemented/corrected if the "default" behavior of the algorithm doesn't correspond to the user's expectation.

Anyway, what I'm trying to say is; I know what you want is obvious to you (and the unmentioned details have obvious answers too) but it is not all obvious to _me_ (and maybe unobvious in different ways to other users). Yes, you can provide more specific descriptions, writing in minute detail all the possible user interactions, but that doesn't necessarily mean that many people will read (or understand; we're not all native speakers here) and still have the will to live. Quite often developers only realise there are un-intended/expected side-effects or interactions when they're almost done implementing (the whole 80-20 thing). I can only assume that they are even less evident to someone who hasn't worked with the code base.

I'm not trying to discourage you here; but _communication_ is one of the biggest challenges in this project and with _good_ reason (i.e. don't assume it is all just unwillingness; this stuff is _hard_ and people who really try burn out). I would completely understand if you didn't stick with it, gave it a little go, got frustrated and moved on. That's fine. And if you then felt a need to trash talk the people who just _didn't get it_ that's fine too. Many have got thick skin by now. But if you _are_ serious then you'll have to work hard at communicating and cooperating with people. And not necessarily me.

> the top toolbar - if it's interesting - should have its own proposal

Definitely. We can't just add buttons to the current toolbar. If there really _needs_ to be a separation between the lighttable and the darkroom versions, then that needs to be thought through first.

**Comment by AlicVB** [comment]
Well...there's many interesting points here : 
- about the "rotation" line : This has already be proposed long time ago, but not coded/tested for some reasons I don't remember (the complexity of c&r was certainly a part of the problem). As I imagine this feature, that would not remove the actual right-click + drag feature, which is way more quick for advanced users. For me the main issue is the next point...
- actually crop is applied when the module lost the focus. Although this is ok for experienced users, this is not really discoverable... and if we go for the "crop-rotate" buttons, we will have to rethink this part completely ! Not to speak about the straightening line from point 1 : how do we allow user to "validate" the changes ?
- for the topbar usage in darkroom, I completely agree that current "filters" have nothing to do here and that this area can be used for more useful things. The issue is that some users relies on it to filter the filmstrip... So we'll have to either remove the feature (and assume the worflow regression) or find a new way to filter the filmstrip...

**Comment by dterrahe** [comment]
> * actually crop is applied when the module lost the focus.

Crop, yes, but rotation is applied "immediately".

> * completely agree

> * nothing to do here

> * some users relies on it to filter the filmstrip

This is the essence of the discussions we are having. Are we having a popularity contest (_I_ don't care so go ahead and delete if my gang has 51%) or are we trying to keep as many people as possible happy (and then how do we weigh current users/developers with their worn in workflows vs hypothetical new users who, after having made it past the UX barrier could still be lost to "4th order anisotropy")?

**Comment by dterrahe** [comment]
A few more thoughts:

If you don't want to set up a github project to manage this set (including the next ones) of "bite-size" suggestions, then it would be helpful to submit them as individual issues (with clear titles). Multi-topic issues lead to confused discussions that fizzle out.

1. "Provide an alternative more discoverable way to resize graphs, entries and lists"
2. "Add tooltips to navigation thumbnail and zoom dropdown"
Of course "ctrl+shift+N" should not be hardcoded in the tooltip since it can be configure (or even removed completely!) by the user.

> 3\. The rotation model is: read the tooltip for a slider, go to viewport, drag a line.

Not really though; the first way of rotating is by _using the slider itself_ (either directly or via a shortcut/midi knob). The tooltip just shows an _alternative_ way. A slider is deemed to be "self-explanatory" or worthy of reading the manual for. For example the suggestion to add instructions to _each slider tooltip_ that you can use scroll and speed up/down by holding shift/ctrl or right-click and type a number was already shot down.
