### ISSUE TITLE
Stronger visual feedback for rejected status for currently selected images

### ISSUE THREAD

**Issue by ni-ka** [darktable-org/darktable#13403]
**Is your feature request related to a problem? Please describe.**
I review my images to identify high scoring keepers and images I will reject (and delete later).
When I change the rejected status on a selected picture, I don't have a clear visual indication whether the image is rejected or not. The icon changes but its a minimal change for color blind people like me (the change in scoring stars is much more obvious IMHO). I need to click to another image to confirm whether the image is rejected or not.  Hopefully the screencast below helps to understand:
[Kooha-2023-01-22-19-41-05 (1).webm](https://user-images.githubusercontent.com/1225776/213937464-ae4bcbf4-e744-4e12-9c55-7e86d2b606d4.webm)

**Describe the solution you'd like**
For the star rating of the image, it is very clear when an image has a specific score. A solution would be to provide a "filled" icon for rejected images. Like this for example?
![Screenshot from 2023-01-21 23-03-44-changed](https://user-images.githubusercontent.com/1225776/213937846-69cfb787-c677-4df7-b7a2-0afa00b24554.png)

**Alternatives**
Different shades for selection / rejected, red shade for selected image

**Comment by Nilvus** [comment]
Sorry but your proposal will be a no go. Full reject icon doesn't suit whole icons UI on different states. How can someone understand that full reject icon is a rejected one?

Note that it's hard to do (I work since nearly 3 years on that part) UI and have something that suit everyone. To be more precise, it's just impossible to please and take care of all users as UI choices also depends on users tastes and some specific users eyes (like color-blinded people as you).

Anyway, I agree that UI miss visual indication for selected rejected images. I will test but probably just make it red should be good.

**Comment by Nilvus** [comment]
Forget my last comment, I miss that this was already like i suggest, your whole images lost me. I so don't understand your real issue. There's a clear visual effect to show rejected images for selected ones. Maybe you put there too much infos but I'm now lost.

**Comment by Nilvus** [comment]
Oh note that stronger shade will unfortunately not be possible as this had been discussed a lot to find actual setting. Some wanted darker, some lighter. Actual setting was so something between and was validate by all developers/users who put feedback. You can find pull requests to show discussions (there's about 3 or 4 pull requests just to set, update how rejected images are rendered actually + icon that had been updated after).

Note so that all this is set by CSS, it's so easy to set your own setting that suit more your eyes. You could find them starting line 2152 on darktable.css file. I copy/paste below those lines:

```
/* Set rejected images */
.dt_thumbnail_rating_6 #thumb-image
{
  color: rgba(0,0,0,0.35); /* only the transparency is used to fade the image drawing */
}

.dt_thumbnail_rating_6#thumb-main:hover #thumb-image
{
  color: rgba(0,0,0,1); /* take back image to normal state by removing transparency when hovering the image */
}

.dt_thumbnail_rating_6 #thumb-back
{
  background-color: shade(@thumbnail_bg_color,0.75); /* also fade the thumb background */
  border: 1px solid shade(@lighttable_bg_color, 0.75); /* this is needed to have appropriate border colors and avoid visible differences in border regardless of not rejected images */
}

.dt_overlays_always .dt_thumbnail_rating_6 #thumb-ext,
.dt_overlays_always .dt_thumbnail_rating_6 #thumb-altered,
.dt_overlays_always_extended .dt_thumbnail_rating_6 #thumb-ext,
.dt_overlays_always_extended .dt_thumbnail_rating_6 #thumb-altered,
.dt_overlays_always_extended .dt_thumbnail_rating_6 #thumb-bottom-label,
.dt_overlays_mixed .dt_thumbnail_rating_6 #thumb-ext,
.dt_overlays_mixed .dt_thumbnail_rating_6 #thumb-altered
{
  color: rgba(0,0,0,0.15); /* add some transparency to infos items in thumbnail */
}
```

You could update last number, after the three 0. What they do is explained. Just copy/paste then part(s) you want to test/update on darktable main preferences (first tab), then update value and save to show your choice. If you find a setting that suit your needs, please post it there. I will see if this can be used on main darktable.css code (if it could suits many users and is not against discussions made in the past). Waiting now for your feedback.

**Comment by ni-ka** [comment]
@Nilvus thanks for the context and the info that you have been working on this for some time! Yeah I admit the images and their description were a bit confusing. I'll add a screencast with keypresses which should make it more obvious. I'll be on the computer later today.

Regarding the fill icon. What if the fill was red for rejected? That should make it obvious which is the rejected state. Personally I find that a filled icon always describes some active state - like checkboxes, or even the star scoring - but as you said, different tastes and perspectives.

**Comment by Nilvus** [comment]
I'm not sure screencast will help. I know which is the rejected state. Would be better to just amend your first post and remove unuseful images to just let states that confuse you (on what I understand, there's mostly 2 states). About filled red proposal, regarding all discussions we had, I fear that this will not be the way to go.

Just post what I suggest here and if you can, try some updates on code I post. If you find something good for you, just post what you change.

**Comment by ni-ka** [comment]
@Nilvus sure, i have amended the issue description and tried the red fill i suggested. I will play with the styles you mentioned (thanks btw for the example code) once I setup a development instance.

If possible, could you elaborate why you don't like the filled icon? it seems to me a similar semantic (filled=active) is used for the star scoring? I understand the red is probably quite intrusive, just trying to understand.

**Comment by Nilvus** [comment]
I didn't say that I don't like filled icon.
