### ISSUE TITLE
D90

### ISSUE THREAD

**Issue by AndyHit5687** [darktable-org/darktable#13494]
On my HP ZBook I have tried to tether my Nikon D90 but darktable says no camera support although I think it is in the supported list. I found and followed a video using zadig to force the winusb but the result was the same. Repeated on a second difference HP PC

1) Should D90 be tetherable, I have done this using another free app, or is it pending?

2) If it should work can anyone tell me how to diagnose the problem? I saw a reference to gphoto2 but I can't find a built version for Windows 10.

3) Any other suggestions would be gratefully received.

Andy H

PS: Sorry for using the new camera tag but I wasn't sure which was more appropriate.

**Comment by Nilvus** [comment]
Supported list is about reading and processing RAW, not tethering. Tethering is from Gphoto2 library, not darktable. See on Gphoto2 website (on what I quickly check, should be supported): http://gphoto.org/doc/remote/. As you use Windows, there's also the correct link with USB drivers. I don't use Windows.
If you want help about that, better go to [pix](https://discuss.pixls.us/c/software/darktable/19) for help. Search before discussions related to tethering on Windows (and winusb driver, I remember some threads about that) before opening a discussion.

Pixls.us forum is a good help forum and you should have more feedback. This place is about what developers could to do to improve darktable. So as this is not directly related to darktable (code), I close.

**Comment by ralfbrown** [comment]
Tethering goes through a third-party library, so it is entirely possible for darktable to support processing the images from a camera (and it works just fine with my old D90 images) but not support tethering because that library does not support the camera or the camera does not properly/fully support the underlying protocol (PTP?).

The commandline program 'gphoto2' is a wrapper around the library which dt uses.  You should check whether it works with your camera.  If it does not support the D90, then there is nothing more darktable can do for tethering until libgphoto2 supports the D90.

**Comment by oleastre** [comment]
For information, I just tested darktable capture with my old D90 on Fedora37. Works perfectly well, after mounting the camera in lightable.
So iit seems to be a specific problem of your windows build.

**Comment by TurboGit** [comment]
Indeed I kind of remember that the capture view is not stable (or even supported) on Windows at all.
