### ISSUE TITLE
Disable Close button when viewing image full screen in lighttable

### ISSUE THREAD

**Issue by LateJunction** [darktable-org/darktable#13514]
**Is your feature request related to a problem? Please describe.**

I am unable to prevent myself clicking on the 'close' button when I have finished viewing an image in Full Screen mode in lighttable (shortcut key 'F'). This seems the natural thing to do. Darktable promptly closes, which is not what I intended

**Describe the solution you'd like**

Disable the 'miimise', 'maximise' and 'close' buttons in the top right hand corner of the full screen view, possible popping up a message with words to the effect of "exit Full Screen first" if the user clicks on any of these buttons

**Alternatives**

Remove/Hide these buttons, replacing them with 1 button labelled 'return to normal view'. 

**Additional context**

**Comment by Nilvus** [comment]
Those buttons are not set by darktable but by window manager. So those can't be hidden, except if you are on fullscreen mode (I mean here for darktable window, I do not talk about full screen view of the image). To exit that mode, 'F' shortcut works, as well as classic escape shortcut.

On your issues,think also about 2 things:
- precise darktable version and OS at least as template issue ask you
- close duplicate issue when you opened 2 issues by error (I close the other)

darktable team can't do anything here.

**Comment by ralfbrown** [comment]
It should be possible by overriding the close request handler.  GTK docs:
```
GtkWidget::delete-event

The ::delete-event signal is emitted if a user requests that a toplevel
window is closed. The default handler for this signal destroys the
window. Connecting gtk_widget_hide_on_delete() to this signal
will cause the window to be hidden instead, so that it can later be
shown again without reconstructing it.
```
So if we connect a custom handler on starting fullscreen view and restore on leaving it, the custom handler could trigger the leave-fullscreen action.  The part that might be tricky is determining whether the signal was triggered by clicking on a window-manager control or actually quitting darktable, though I suppose for this particular setup it wouldn't be critical since the custom handling restores the default handling -- worst case, the user would have to type Ctrl-Q or Alt-F4 twice.

**Comment by LateJunction** [comment]
"close duplicate issue when you opened 2 issues by error (I close the other)" - oh, sorry about that - it was caused by ,y mot adequately understanding where to type  the required information. Thank you for closing the 'empty' version.

Yes, I am aware that the 'F' shortcut works to close that view - but habit from almost 40 years use of a WIMP interface causes me to instinctively click the close button. This then manifests itself, in my view, as a usability 'characteristic' of dt. Are you really saying dt can't do **anything** here?

**Comment by dterrahe** [comment]
> It should be possible by overriding the close request handler.

Already had started implementing this :-)

The problem is that there already is a global delete-event handler, so a second one never gets called. I extended that global handler to check for lighttable _view_ preview status, but the _layout_ selection also stores the preview status. So when you exit preview using the window close button, you cannot immediately reenter it; you have to correctly leave it first and then enter it again. To prevent accidents this should be enough.
