### ISSUE TITLE
dt-master build fails once using CMAKE_BUILD_TYPE="RelWithDebInfo" 

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#13667]
**Describe the bug/issue**
current master cannot build anymore when CMAKE_BUILD_TYPE="RelWithDebInfo" is set.

It builds just fine with CMAKE_BUILD_TYPE="Release"

(I am using [dt.bldr.sh](https://github.com/jade-nl/dt.bldr) since day-0, that is not supposed to be the issue)

**To Reproduce**
See description
[dt.build.1000.2023.02.18.1350.zip](https://github.com/darktable-org/darktable/files/10774270/dt.build.1000.2023.02.18.1350.zip)

**Expected behavior**
Build w/o crash

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.3.0+674~gec0e357b6
* OS                : Linux - kernel 6.1.12-gentoo
* Distro            : Gentoo Base System release 2.9
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-525.89.02
* OpenCL installed  : Yes (opencl-headers-2022.09.30)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.7
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.35
* gcc               : x86_64-pc-linux-gnu-11
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "RelWithDebInfo"

**Additional context**
_Please provide any additional information you think may be useful, for example:_

**Comment by ptilopteri** [comment]
darktable 4.3.0+674~gec0e357b6
OS: openSUSE Tumbleweed 20230216
6-core model: Intel Core i7 970
RAM: total: 35.23 GiB
NVIDIA GF106 [GeForce GTS 450] 
OpenCL installed
OpenCL not active
Xorg 21.1.7
Desktop Plasma5/KDE5
gtk2 2.24
gtk3 3.24
build type RelWithDebInfo

no crashes and no build errors

same with
Dell product: XPS 8950
RAM: total: 31.08 GiB
12th Gen Intel Core i7-12700 bits
NVIDIA GA104 [GeForce RTX 3060 Ti Lite Hash Rate]
openSUSE Tw
Plasma5/KDE5

**Comment by TurboGit** [comment]
I'm building with RelWithDebInfo also on my side but I'm using GCC 12.x.

**Comment by victoryforce** [comment]
@AxelG-DE Probably better to fix the issue title so that it more accurately describes what is being observed. Obviously, the compiler doesn't crash when building darktable, it's just that the compilation fails because of a compiler warning.

And I can't reproduce the issue either:
- darktable 4.3.0+674~gec0e357b6 (the same)
- GCC 11.3.0 on Ubuntu 22.04 (the version is very close, yours is 11.3.1)

@ptilopteri What's your GCC version?

**Comment by TurboGit** [comment]
Given the log I have just pushed a possible fix.

**Comment by AxelG-DE** [comment]
@TurboGit: because of my other issue I am still running an export, I will test after.

@victoryforce: sorry you are right, not dt crashes but the build. Changed

gcc-version is 11.3.1

**Comment by ptilopteri** [comment]
> @ptilopteri What's your GCC version?

12-2.4

**Comment by victoryforce** [comment]
@AxelG-DE Please test https://github.com/darktable-org/darktable/commit/4f3d272415854cc9660af78bba7e1ee84b7893b4. It may fix your issue. Our compilers (and all compilers in Github CI) have no problems with the current code so we can't check it

**Comment by AxelG-DE** [comment]
> Given the log I have just pushed a possible fix.

solved. THANKS!

**Comment by AxelG-DE** [comment]
> @AxelG-DE Please test [4f3d272](https://github.com/darktable-org/darktable/commit/4f3d272415854cc9660af78bba7e1ee84b7893b4). It may fix your issue. Our compilers (and all compilers in Github CI) have no problems with the current code so we can't check it

done, solved, closed :-)

**Comment by victoryforce** [comment]
Just to save this information here, which may be useful in the future and be found by search (or maybe we can now agree to change our default for warning options).

The compilation failure issue occurred because:
- We treat all warnings as errors
- Somehow -Wmaybe-uninitialized turned out to be enabled, even though we don't enable it and this option is not traditionally part of -Wall. My guess is that this is enabled in the distro defaults (you can see it via gcc -dumpspecs).

We can explicitly disable -Wmaybe-uninitialized to avoid such surprises in the future, since, as we can see, a situation is possible when this warning is turned on unexpectedly.

However, I suspect that it would be better to bite the bullet and instead enable this option despite the fact that it is famous for false positives. At least there has been only one occurrence of this warning in our codebase so far. So hopefully it won't be too difficult to maintain the code at a quality level where this warning doesn't trigger. @TurboGit What is your opinion? Is it worth it or not?

**Comment by TurboGit** [comment]
I would enable this option yes, as you said only one occurrence and even if there is false positive it could detect something really wrong.

**Comment by victoryforce** [comment]
> I would enable this option yes, as you said only one occurrence and even if there is false positive it could detect something really wrong.

OK, PR submitted.
