### ISSUE TITLE
nonsense tooltip on history stack items without changes

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#13739]
history stack items without changes (e.g. default modules) didn't had a tooltip indicating changes 
but there are tooltips maybe inherited from the history stack window

![image](https://user-images.githubusercontent.com/39386816/221349019-5d31124e-13cd-43b0-acdc-02c2a896400d.png)

**To Reproduce**
hover over the history stack with entries with and without changes

**Which commit introduced the error**
not yet done but introduced between build
darktable-4.3.0+390~gad064399e (01.02.23)
and 
darktable-4.3.0+537~gf4356b880 (09.02.23)

**Platform**
* darktable version : darktable-4.3.0+537~gf4356b880
* OS                : OSx

**Comment by dterrahe** [comment]
#13496 and #13523

You haven't stated your preferred "solution" to this "problem". _Mine_ would be to _always_ have a tooltip, even if the only change is that the module is enabled (or disabled). Because "history stack items without changes" shouldn't be there in the first place. If a tooltip is set, the automatic fallback to the list's tooltip (which, correctly, states that you can change its height using scroll) won't ever be shown.

**Comment by MStraeten** [comment]
If I scroll over a history item that has changes, I expect the change information and if there’s no change then I at least don’t expect that resizing info since that‘s not there with dt 4.2.1 and doesn’t gives history item specific information
