### ISSUE TITLE
too many (superfluous) entries in history

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#13733]
**Describe the bug/issue**

The crop module adds a new history entry each time it is changed.

**To Reproduce**

1. Go to 'darkroom'
2. Select 'crop' module
3. Change some params (size or move the area)
4. A new entry is created
5. Do again point 3, a new entry is created
6. See error, the last entry should have been modified and not a new entry created.

**Expected behavior**

The last entry should have been modified and not a new entry created.

**Platform**

* darktable version : d371ea8e08
* OS                : GNU/Linux
* Linux - Distro    : GNU/Debian sid

**Comment by TurboGit** [comment]
Seems like a feature in fact, this is done on purpose each time a module get in/out focus.

**Comment by Nilvus** [comment]
@TurboGit: I'm not sure this is only a feature. For some actions, maybe, but I see now (really recent, about few days probably) many entries added, even if I don't make anything on a module.

For example, on history below:

![image](https://user-images.githubusercontent.com/45535283/221408537-35d72e2f-cef3-4d49-8bfb-c577211f6d6b.png)

Only updates I've made are on steps 16 to 20. I didn't update steps 21 and 22, so why they are there? I have that on nearly all images I update that week (at least since 2 days as I didn't update images previous days).

-

**Comment by Nilvus** [comment]
More infos about that: I didn't reproduce that on another set of images I just processed. So I check back why I add those entries: they were auto-presets that have been applied on images when updating images, even If I don't want them. For step 22 above (Dématriçage), this was indeed good, as it was better to have RCD applied on that image, but not wanted for calibration des couleurs. So seems that sometimes auto-preset is applied when not wanted.

**Comment by Nilvus** [comment]
@TurboGit: what I explained above, only appears if workflow is set to none. Seems that there's some issues when workflow is set to none, that we don't have when a workflow is set (at least modern ones).
