### ISSUE TITLE
Darktable v.4.2.0/4.2.1 continual crash

### ISSUE THREAD

**Issue by FelixtheChat** [darktable-org/darktable#13788]
I need a bit of help.

I've chosen to use Darktable for a number of years now - it is my 'go-to' photo editor - part of a three-part workflow that begins in RAW with Photoninja (because this features a lens distortion widget that can be 'trained' to recognise and correct the aberrations present in all of my cameras - LCP's that don't exist in either the Adobe or Lensfun databases) The Photoninja 32bit floating point TIFF output from Photoninja is then handed off to Darktable for the enhancement and tidying process. Any final JPG image then has my logo applied with GIMP and the workflow ends.

I have upgraded Darktable every time an update has been made available. The updates are always the final working release of each version. This continued with an update from v.4.0.0 to v.4.2.0. As soon as v.4.2.0 was installed: the editor would crash part way through any editing process. These crashes were unpredictable and it did not appear that there was any one widget in particular that triggered the crash.

After giving up trying to edit my shots: I uninstalled v.4.2.0 and re-installed v.4.0.0 which then failed to load at all. Only after I re-installed v.4.2.0 and custom removed it and all orphan traces using a suite named "Bulk Crap Uninstaller" was I able to re-install v.4.0.0 and use it without any problem at all - I was back to normal.

When v.4.2.1 was released: I assumed that any potential cause for this editor crash had been spotted and addressed. I upgraded. v.4.2.1 behaved in exactly the same manner as v.4.2.0 - it continually crashed unpredictably part way through any attempt to edit any of my shots.

In order to continue using Darktable: I have had to use B.C.U again to re-install a working version of Darktable (v.4.0.0).

I have absolutely no clue as to why this is happening and I would genuinely appreciate any insights, or suggestions you might make.

Thank you for having the patience to read this.

Regards.

**Comment by pehar1** [comment]
Which OS ? Did you try to launch darktable with debug option -d all from terminal ? Where did you get the app from ? Please use the issue template !

**Comment by dterrahe** [comment]
> I assumed that any potential cause for this editor crash had been spotted and addressed.

Why would you assume this? You did not let the project know any of the details of the crashes you experience and you still haven't. Unless other people have the same issue you have (and then you'd probably have seen it mentioned in the issue reports in github) the developers probably don't know about any severe problems. Otherwise they would have tried to resolve them before release.

This is not Microsoft. We don't have an army of paid testers to try to spot all problems before release. The testers are _you_. The issue template is there to help you provide us with information that could help us help you. The information you _did_ provide is not really going to do that.

**Comment by victoryforce** [comment]
@dterrahe There is no need to be too emotional. It won't help the user, it won't benefit the project, you don't need it yourself.

**Comment by victoryforce** [comment]
@FelixtheChat If you were offended by something in the previous answer, please accept my apologies.

Could you answer a few questions?

- Was there any regularity in the crashes of the program? For example, always when performing the same operations or in the same processing module?

- If darktable does not crash immediately after launch, could you please go to the program settings (the gear icon on the top panel) and in the "processing" section, uncheck "activate OpenCL support". After that, restart the program and check if the crashes remain.

In general, it is best to do this with a new library to exclude the influence of a possibly damaged library, but if this is difficult for you, you can skip it.

**Comment by FelixtheChat** [comment]
Thank you for the courteous response. Genuinely appreciated.

No regularity regarding the program crash. I use a set series of processing
modules to enhance shots to my chosen "style". Sometimes the crash would
occur within the first two or three modules into the workflow: sometimes in
the penultimate step (colour look-up table).

I will try reinstalling v.4.2.1 and check if it might be an 'openCL
support' problem by unchecking the option. Your suggestions are gratefully
received.

Please bear in mind that I only know (a little about) how to use this
exceptional piece of software: I have absolutely zero competence regarding
the black magic of what makes it work - nor do I pretend to.

Thank you for having the patience to read this.

**Comment by dterrahe** [comment]
> @dterrahe There is no need to be too emotional.

> all the grace and patience of a snappy little terrier.

> it won't benefit the project

Oh, look, I had to laugh at the guy. He bit the hand of the guy who came to help him.

It doesn't help the project to signal that it is OK to come in and insult developers who have been working hard to make this program as good as they know how to. That leads to burnout and attrition. What in my initial reply in your eyes justifies that kind of response? Pointing out that the issue template is there for _his_ benefit, so we have the information to help him, not ours? 

> have fuck all to do with you.

They'll happily use the fruit of our labor though.

I agree that it could benefit the project if this person could be coaxed to provide some useful input that would help resolve crashes that other people experience too. But otherwise he might feel more at home in communities where insults are more readily accepted. I would suggest https://ansel.photos/

**Comment by victoryforce** [comment]
@FelixtheChat Although the circumstances of the crashes you describe do not allow us to clearly determine the cause, it is similar to the symptoms caused by buggy OpenCL GPU drivers.

Also try the following before testing. Open File Explorer, type %LOCALAPPDATA% in the path field and press Enter. Find the darktable folder and rename it to any other name. After that, you can run darktable, it will work as it did after the first run, with default settings and an empty library.

**Comment by victoryforce** [comment]
@dterrahe To me, your thoughts on this seem out of place right here. We can discuss these topics in darktable-management or another IRC/matrix channel. Thank you for your understanding.

**Comment by FelixtheChat** [comment]
This is the very first time I have attempted to submit a "bug report", so
please understand my complete ignorance of accepted form. I will follow the
steps you suggest about renaming the library. Thank you once again.

**Comment by TurboGit** [comment]
> Well, slap my wrists. We can't all be coding geeks and today was the first time I've even heard of GitHub let alone joined something like it. Your snotty attitude has really gotten my back up. Congratulations, if you are indicative of the lack of social skills in your wider community, small wonder people who have no idea about developing and coding have fuck all to do with you. Don't bother responding, I'm not in the least bit interested in sharing another word with an individual with all the grace and patience of a snappy little terrier.

Frankly your comment is not fair. @dterrahe replied to you asking for more information. In your original message there is nothing for use to help. You have installed, uninstalled, reinstalled... You didn't even tell us at which point it crashed. There is no need to be a developer, but you are still the user and so pretty well know that it crashed while doing something specific. Also, when this is know, have you tried to see if it crashes at the same point after restarting?

Last but no least... We have plenty of users on Windows but sadly very few developers. Sad to be said but it seems that Windows users doesn't care to share the load of work.

> This is the very first time I have attempted to submit a "bug report"

And what? You still have written text here... Just described as asked what crashes, in which circumstances... just as plain text in English.
