### ISSUE TITLE
module layouts reseting when opening after saving

### ISSUE THREAD

**Issue by EinzKleinNico** [darktable-org/darktable#13799]
**Describe the bug/issue**

When I create my own preset for the module layout and want to re-edit the layout all elements under the quick access tab that are not part of the 'standard ad list' (when you klick the + underneath the tab name) disapear.

It ONLY happens on the quick access tab and ONLY with elements that are NOT in the 'standard ad list'

**To Reproduce**
For example:
1. Go to 'Darkroom'
2. Click the hamburger menue for managing the layout presets
3. Click on 'manage presets'
4. Click on the '+' symbol below the tab name of the quick access tab
6. Click on 'all available modules' and choose on that is not already on the 'standard ad list' 
7. close the 'manage module layouts' window 
8. repeat step 2 + 3
9. See error

**Platform**

* darktable version : 4.2.1 (had the problem with earlyer versions too)
* OS                : Win10 
* Memory            : 8GB
* Graphics card     : Intel(R) HD Graphics 620

**Comment by ralfbrown** [comment]
Unable to replicate on Linux as described.  What I *was* able to do to get what looks like a replication (but isn't) is to start with one of the built-in presets active at step 2.  But then it's necessary to duplicate the preset to get the '+' below the tab names, and the new item only seems to disappear because duplicating a preset doesn't automatically make the new duplicate active.

If you were having problems with *any* editing of the layout, I would  have suggested checking whether there is a permissions problem or other reason why darktable can't write its data.db file.

**Comment by EinzKleinNico** [comment]
Well then it might only be on Win10? If I got time today I will try and screen record what's happening because what you describe with the duplication is not the problem that I have.

**Comment by EinzKleinNico** [comment]
So I finaly had time to come back to this today. 
I'm still able to reproduce the issue but I found something out...
If you add for exampel "lens correction - on-off" to the quick access panel but don't add it to one of the module groups, then close the "manage module layouts" tab and open it again to re-edit the preset the "lens correction - on-off" module disappears from the quick access panel.
BUT if you add the "lens correction - on-off" module to the quick access panel AND also add the "lens correction" module to one of the "normal" module groups and then close the tab again. The added modules do not disappear like before.
