### ISSUE TITLE
filmicrgb: preserve chrominance option with no name?

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#13971]
It is possible to select an item with no name. It is available in the drop-down, as well as when scrolling the mouse wheel. I assume it's the 'DT_FILMIC_METHOD_LAST' entry from https://github.com/darktable-org/darktable/blob/master/src/iop/filmicrgb.c#L119.

![image](https://user-images.githubusercontent.com/3177739/226161705-42c4d43d-0ea6-4a7c-bb86-082c83dc34ae.png)
![image](https://user-images.githubusercontent.com/3177739/226161754-66cd75d1-79ad-4cd7-ba76-3e11fcf6c3fe.png)

4.3.0+1280~g604e8f3446, self-built. Linux 5.19.0-35-generic, KDE 5.98.0, GTK 3.24.34, GCC 12.2.0.

**Comment by ralfbrown** [comment]
Confirmed.  Looks like hiding the legacy euclidean norm for new edits is only partially successful.

**Comment by ralfbrown** [comment]
Basically the same thing in Color Calibration as well.  Here the introspected enum has a LAST entry which doesn't correspond to any implemented method, resulting in a black image when the blank last line of the menu is selected.

**Comment by dterrahe** [comment]
> it looks like the introspection code is getting confused

Not really; it just adds all the enums to the dropdown, assuming that's what you wanted. If it wasn't they then need to be removed again (using ` dt_bauhaus_combobox_remove_at(g->..., ..._LAST);` which is done in a bunch of modules.

So for filmic, both DT_FILMIC_METHOD_LAST and DT_FILMIC_METHOD_LAST-1 (the legacy euclidean) need to be removed.

The pattern of adding a `_LAST` to an enum definition can be especially useful when they are autonumbered (and therefore the order is always predictable even when adding or inserting entries later). In this case, since an out-of-order numbering is used anyway, the "_LAST - 1" approach to deleting a legacy entry is not guaranteed not to break. So my preference would be to either use `dt_bauhaus_combobox_length` or `#define _LAST` outside of the enum and add some additional commentary in case of future additions.

@flannelhead would you mind having another look at #12887?

**Comment by flannelhead** [comment]
@dterrahe yes, I can look at that one. On a brief look the hiding implementation done in #12887 could use some cleaning.

The regression was introduced in ee3a34aeacefb2f7c07fc0495396eeb60256184e - before that commit, enum values without a `$DESCRIPTION` in the introspection comment were not introduced as entries to the combobox. I would just like to know the reasoning behind this change, and are there new APIs that should be taken in account when making comboboxes from introspected enums.
