### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by sheemon-lists** [darktable-org/darktable#13983]
**Is your feature request related to a problem? Please describe.**

I am SURE this is the wrong post to the wrong place but this forest has many trees and no good road sign a blind man can read.
So just yell at me where I should go.

Substantial photography experience.
Substantial computer experience
Meager windows experience
A collection of some 6000 images I scanned over some three years.
Searching for a tool to edit (crop. color correct, some editing, print) and compose the images into various albums by family members.
No darktable experience 
The system is a Desktop running Ubuntu 22.04.  all software is current releases in mid-March 2023
Storage is composed of various ZFS volumes, all mirrored and backed up.

Current Problem:

When trying to import some directories, the program displays some thumbnails and then crashes.

**Describe the solution you'd like**

First, import at least 10,000 raw images and display thumbnails without the program crashing.
When that is accomplished, I will say a huge, happy thank you and go to the next step.

Please show me a straightforward way to access a mailing list to join.  I am nearly blind and social media is very difficult for me.
I need time to process instructions and test suggestions.

**Alternatives**

If a mailing list is not available, what is a written, noninteractive way of communicating?

**Additional context**

I am eager to get this project going.  It is the legacy of my family.  I do not have unlimited time left to complete this important project and will appreciate any help I can get.

Sincerely

Simon Shapiro

**Comment by ralfbrown** [comment]
"darktable-users" mailing list - info: https://www.mail-archive.com/darktable-user@lists.darktable.org/info.html

You may have a corrupted image - if you try importing a subset of images from different directories than the ones on which you've experienced crashes, is the import successful?  dt shouldn't crash even with corrupted files, but one can't test every possible way a file could go bad.

You mention scanned images.  How large are these? (in megapixels, not megabytes, since file size depends on compression)  darktable needs *a lot* of memory to process images, though for thumbnails it can downsample early in the pipeline.  Processing an  image at full resolution requires an absolute minimum of 32 bytes per pixel, so a 100 megapixel image needs 3.2 GB of available RAM to do anything at all (and some of the processing  modules need several times as much when exporting).  We've recently fixed a number of potential crashes from failure to check for memory allocation failures when the operating system runs out of memory on large images.

10k files is no problem - my personal darktable library has 349k.

**Comment by kmilos** [comment]
> "darktable-users" mailing list

Or https://discuss.pixls.us forum.
