### ISSUE TITLE
lighttable: panel width changes when hovering image

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#14134]
### Checklist

- [X] I have checked [GitHub Issues](https://github.com/darktable-org/darktable/issues?q=is%3Aissue) and my problem is **not** described there.

### Describe the bug

In lighttable, the side panel widths jump when hovering an image

### Steps to reproduce

1. Open a collection in lighttable
2. Pull side panels to their max widths
3. Have more than one image side-by-side in the filemanager layout
4. Hover the cursors on different images or temporarily outside of the filemanager grid

### Expected behavior

panel widths don't change

### Logfile | Screenshot | Screencast

Screencast: 

https://user-images.githubusercontent.com/5001906/230467843-1457723b-0a15-4a6c-b3ad-3365b11c5a8b.mp4

### Where did you install darktable from?

self compiled

### darktable version

release-4.3.0-1607-g69620d805a

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel HD 520

**Comment by dterrahe** [comment]
This seems to be caused by differing contents in the metadata fields. When the left, top and right panels all contain some ellipsized strings, the allocation between them will be based on their natural widths. Except that in the case of the metadata textviews, I would not expect them to factor into this calculation for the right panel since they are wrapped in ScrolledWindows that have their `propagate-natural-width` property set to the default FALSE. So I'm not sure yet about the exact cause (or possible solution).

**Comment by dterrahe** [comment]
Setting the hscrollbar-policy to GTK_POLICY_AUTOMATIC seems to resolve the issue. I'm now wondering if it is possible to set the vscrollbar-policy to automatic as well in that case (need to look up the bug that needed that to be set to GTK_POLICY_ALWAYS as a workaround).

**Comment by dterrahe** [comment]
So the _good_ news is that     
```
gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(gtk_bin_get_child(GTK_BIN(swindow))),
                               GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
```
seems to work fine, both for this and the previous issue as far as I can tell.

The _bad_ news is that now, even though the horizontal scrollbar never appears because the text will be wrapped instead, there needs to be space for it. So the minimum size for the textview is now 1.5 lines. Unless we enable overlay scrollbars, but that has been disabled globally and will probably break loads of things (people's minds, for starters) when changed.

I hate this stuff.

**Comment by dterrahe** [comment]
Hold on! It turns out the _obvious_ solution (no idea why I didn't think about this _first_) is to use `GTK_POLICY_EXTERNAL` for the horizontal scrollbar.

Trivial PR coming up. We'll need @elstoc to test this one too...
