### ISSUE TITLE
Copy-Paste history stack kills darktable (Win)

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#14261]
### Describe the bug

Copy-Pasting history tack kills darktable. If the copy-paste is the first operation when starting darktable, it works as expected, but if an image has been edited darktable exits without any error message. Also applying a style or deleting a history stack after editing an image has the same effect. The copy-paste/applying style is applied on the first image before the crash.

If run from gdb the error doesn't occur, running from UCRT Terminal, it appears sometimes and generates Segmentation fault error message. When dt is run directly from Windows I happens always.

### Steps to reproduce

1. Open/Import a folder
2. Open an image and edit it
3. Copy-paste the history stack to another image
4. darktable exits

### Logfile | Screenshot | Screencast

[darktable-log.txt](https://github.com/darktable-org/darktable/files/11276639/darktable-log.txt)

### Where did you install darktable from?

self compiled

### darktable version

4.3.0+1661~g48f6e4b346 –>

### What OS are you using?

Windows

### What is the version of your OS?

Win 11 Enterprise 22H2

### Describe your system?

- Intel i7
- 32 GB RAM

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA T500, 527.27

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

- OpenCL doesn't have impact, dt crashes both with and without
- no issues on Fedora (with same version)
- no issues with Bill Ferguson's Win version (1800)
- same issue with latest 1824, built by myself (build type: release)
- no issues when running via gdb
- I have recreated the build directory
- I have a feeling that the issues have started after 4.3.0~1000 (around), cannot say for sure

Is there a way to provide more information?

**Comment by ansluk** [comment]
I have a very similar crash triggered by opening an image in darkroom, returning to lighttable and pressing duplicate. 
-> Magick: caught exception 0xC0000005 "Access violation"...

Rolling back a recent Msys ucrt64 upgrade and rebuilding fixed the issue, but the upgrade included quite many packages so I don't know which package update triggered the crash.

**Comment by victoryforce** [comment]
> Rolling back a recent Msys ucrt64 upgrade and rebuilding fixed the issue, but the upgrade included quite many packages so I don't know which package update triggered the crash.

@ansluk So you can update mingw package by package and see when a problem occurs. Otherwise, we won't know which package was the culprit and won't have a chance to understand and fix the issue.

**Comment by ansluk** [comment]
Right, builds are crashing after upgrading from mingw-w64-ucrt-x86_64-glib2-2.74.6-1 to mingw-w64-ucrt-x86_64-glib2-2.76.1-1.

**Comment by ansluk** [comment]
I think the latest commit related to this is f83e9ef Update info line when cropped size changes (https://github.com/darktable-org/darktable/pull/10979) from Jan 30. It adds raising DT_SIGNAL_DEVELOP_IMAGE_CHANGED to dt_image_update_final_size in image.c and is the reason the gui update for ioporder module is running from lighttable view. Perhaps it can be reverted or done differently?

**Comment by TurboGit** [comment]
> Perhaps it can be reverted or done differently?

Maybe but raising `DT_SIGNAL_DEVELOP_IMAGE_CHANGED` in this specific case seems a good thing.

> So why does this work with glib2-2.74-6 and not 2.76.1?

That's the question yes. On GNU/Debian sid I'm still using `2.74.6-2` and `2.76.2` is on the experimental branch. Maybe there is still bug in this version as not in stable yet?

Would be nice to have a report from other Linux users if they are using 2.76 or not.

**Comment by ansluk** [comment]
> > Perhaps it can be reverted or done differently?
> 
> Maybe but raising `DT_SIGNAL_DEVELOP_IMAGE_CHANGED` in this specific case seems a good thing.
> 

The important part would be to prevent the code in ioporder.c:update that references the (then freed) expander to run when in lighttable view. That could probably be fixed some other way. 

> > So why does this work with glib2-2.74-6 and not 2.76.1?
> 
> That's the question yes. On GNU/Debian sid I'm still using `2.74.6` and `2.76.2` is on the experimental branch. Maybe there is still bug in this version as not in stable yet?
> 
> Would be nice to have a report from other Linux users if they are using 2.76 or not.

It was pretty interesting to see the difference in how the memory position of the ioporder module expander was used after it had been deleted in the two glib versions. So if anyone has the time to check it out on linux, it would be fun to know.
I just left the memory watchpoint I mentioned in the comment above (on the address of the iopmodule expander) active and printed a backtrace to check callers everytime it was hit between switching from darkroom to pressing duplicate in lighttable. If calls were from darktable/glib I stepped up a few levels to be able to check with module/widget it concerned. 
With 2.74 It was all darktable, glib/ucrt related, with 2.76 it was a variety of threads. 
I read somewhere that a change between 2.74 and 2.76 was that resposibility for some memory management was transferred from glib to the os, but not sure what that means exactly.

**Comment by jenshannoschwalm** [comment]
> Would be nice to have a report from other Linux users if they are using 2.76 or not.

On Fedora 37 i have 2.74.7

**Comment by kmilos** [comment]
https://repology.org/project/glib/versions

**Comment by ptilopteri** [comment]
on openSUSE Tumbleweed I have 2.76.2

**Comment by TurboGit** [comment]
> on openSUSE Tumbleweed I have 2.76.2

Good, and do you get a crash?

**Comment by zisoft** [comment]
I can reproduce on a Mac (Ventura 13.3.1) as well with 

```
~ brew info glib
==> glib: stable 2.76.2 (bottled)
Core application library for C
https://developer.gnome.org/glib/

```

**Comment by ansluk** [comment]
Ok, I managed to get it to not segfault on windows with glib 2.76.
I also added some additional log messages. The log patch is attached if someone else wants to have a go. Sorry if it's ugly.

When it doesn't segfault I get failed assertions instead and dt_gtk_expander_get_header returns NULL.
Log messages below are from ioporder.c:update when called from lighttable view.

    34,2224 [ioporder_use_after_free] in ioporder.c:update, about to read header from expander at '0000014f54b80370' referenced by 'module order'
    34,2225 [ioporder_use_after_free] ioporder.c:update was called from lighttable

** (darktable.exe:3392): CRITICAL **: 11:25:56.561: dtgtk_expander_get_header: assertion 'DTGTK_IS_EXPANDER(expander)' failed

    34,2225 [ioporder_use_after_free] expander_get_header returned NULL (0000000000000000)

** (darktable.exe:3392): CRITICAL **: 11:25:56.561: dtgtk_expander_get_header: assertion 'DTGTK_IS_EXPANDER(expander)' failed
(darktable.exe:3392): Gtk-CRITICAL **: 11:25:56.561: gtk_box_pack: assertion 'GTK_IS_BOX (box)' failed
(darktable.exe:3392): Gtk-CRITICAL **: 11:25:56.561: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

When ioporder.c:update is called from darkroom everything looks ok, the expander has a correct label:

    24,9499 [ioporder_use_after_free] in ioporder.c:update, about to read header from expander at '0000014f54b80370' referenced by 'module order'
    24,9499 [ioporder_use_after_free] ioporder.c:update was called from darkroom
    24,9500 [ioporder_use_after_free] got header at 0000014f5638a3d0
    24,9500 [ioporder_use_after_free] The name of the header eventbox child is 'lib-panel-label'
    24,9500 [ioporder_use_after_free] The label of the header eventbox child is 'module order'

Linux:
I also tested under Ubuntu 22.04.2 LTS that I have installed in wsl. The Glib version is 2.72.4
It doesn't crash in ioporder.c:update when called from lighttable but reads the expander from the styles module instead.

When going from lighttable to darkroom a new expander is created for module order plugin.
    57.6404 [ioporder_use_after_free] created new expander at 0x561dd47ac790 for module 'module order'

All looks ok when ioporder.c:update is called from darkroom
    57.8766 [ioporder_use_after_free] in ioporder.c:update, about to read header from expander at '0x561dd47ac790' referenced by 'module order'
    57.8767 [ioporder_use_after_free] ioporder.c:update was called from darkroom
    57.8767 [ioporder_use_after_free] The label of the header eventbox child is 'module order'

When returning to lighttable gtk_widget_destroy is called on the expander.
    64.6064 [ioporder_use_after_free] in views.c:_remove_child, removing child at 0x561dd47ac790
    64.6064 [ioporder_use_after_free] child is an expander, calling widget_destroy

New expanders are created for the lighttable modules. The styles module expander is created at the same address as the former ioporder expander.
Perhaps the memory manager thinks it's a good fit space wise or it's a coincidence.
    64.6152 [ioporder_use_after_free] created new expander at 0x561dd47ac790 for module 'styles'

When pressing duplicate in lighttable the ioporder.c:update callback runs again referencing the expander with the same pointer as before.
Note the label of the expander header in last log line. 
    67.8993 [ioporder_use_after_free] in ioporder.c:update, about to read header from expander at '0x561dd47ac790' referenced by 'module order'
    67.8993 [ioporder_use_after_free] ioporder.c:update was called from lighttable
    67.8993 [ioporder_use_after_free] The label of the header eventbox child is 'styles'

So no failed asssertion because it's still an expander and I'm guessing no segfault because the memory hasn't been released to the os?

[ioporder_segfault_log.patch](https://github.com/darktable-org/darktable/files/11383233/ioporder_segfault_log.patch)

**Comment by lintujuh** [comment]
Copy-paste history stack works now in my 4.3.0+2190~gb8317267b6. I have only updated dt, I haven't updated my MSYS environment.

**Comment by jenshannoschwalm** [comment]
Isn't this fixed and can be closed?

**Comment by lintujuh** [comment]
Has not reappeared since 2190.
