### ISSUE TITLE
Exif data not exported to jpg

### ISSUE THREAD

**Issue by ladescamps** [darktable-org/darktable#14303]
### Describe the bug

Exif data are read correctly from .CR3 CANON R6 MKII, but absent when exporting to jpeg

### Steps to reproduce

Export file to JPEG

### Expected behavior

Exif data should be added to exported JPG files

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1-1.1+59.1    opensuse.org

### What OS are you using?

Linux

### What is the version of your OS?

LinuxMint 21

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment]
What metadata, if any, gets exported is a configurable preference settable in the export module.  Have you enabled ExIF tags there?
https://docs.darktable.org/usermanual/4.2/en/module-reference/utility-modules/shared/export/

If this is happening *only* for CR3 files, you may have a version of exiv2 installed which is not able to read the tags from the input file (because CR3 uses a different container format than all other raws).  Is darktable showing you proper metadata in the image information?

**Comment by ladescamps** [comment]
ouch, I'm so sorry, I use darktable for many year and I did'nt know that it was configurable preference settable in the export module. Is it a new feature, or was it enabled by defauyt in the previous version and not in this version?

Anyway it works great ! 

So sorry again...

**Comment by kmilos** [comment]
Please consider closing the issue then, and also please search before opening new ones: https://github.com/darktable-org/darktable/issues/12394 and https://github.com/darktable-org/darktable/issues/12352 etc
