### ISSUE TITLE
Inconsistencies in POT file, grammar

### ISSUE THREAD

**Issue by bgodole** [darktable-org/darktable#14387]
### Describe the bug

There are continuous efforts by darktable developers to correct various spelling and grammar mistakes in the GUI, and improve overall consistency. Here are a few more suggestions from a brief reading of the darktable.pot file.

1. 'selects' should be "select" ?
> "positive values selects areas with strong details,\n"
> "negative values select flat areas"

2. 'light table' is written as a single word in all other cases
> "Virtual light table, showing a collection"

3. 'userdefined' should be hyphenated, i.e. user-defined ?
> "no userdefined presets for favorite modules were found"

4. 'usermanual' should be spaced, i.e. user manual ?
> "access the online usermanual?"

5. should CW/CCW be lowercase or uppercase ?
> "rotate 90 degrees ccw", "rotate 90 degrees CCW", "rotate 90 degrees cw", "rotate 90 degrees CW" ...

6. uppercase ?
> "jp2"
> rgb
> cdl (as in "lift gamma gain|cdl|color grading|contrast|saturation|hue")

7. 'American' should be capitalized!
> "African-american"

8. should names be capitalized ?
> "reinhard", "drago", "thoby fish-eye"

9. should be capitalized in all cases, i.e. Piwigo, Lightroom ?
> "piwigo" ...
> "cannot find lightroom XMP!"

**Comment by victoryforce** [comment]
@bgodole Thank you for spotting these issues! I will prepare PR to fix.

**Comment by bgodole** [comment]
Thank you!

The names of file formats are sometimes lowercase/uppercase as well, e.x.:

> png (many instances)
> "jpeg"
> "jpeg xl"
> "j2k"
> "tiff"
> "exr"
> "rgbe"
> "pfm"
> pnm (as in "netpnm")
> "avif"
> "heif"

Should these also be properly capitalized (as you do for "GraphicsMagick") ?

> webp (to WebP)
> rawspeed (to RawSpeed)
> libraw (to LibRaw)

**Comment by victoryforce** [comment]
Well, I forgot to add one of the obvious points from your list (cw/ccw) in the PR, I'll add it to the next one. Of those that remain, there are valid points for which I want to take the time to check and research (I will explain below) and points where there is no need to make changes, because they will not be visible. Namely:

> cdl (as in "lift gamma gain|cdl|color grading|contrast|saturation|hue")

This is a list of aliases that we do not see in the interface, they are used in the search for modules and the search does not depend on the register of aliases. Therefore, the correction here will not change anything and is therefore unnecessary.

> "reinhard", "drago", "thoby fish-eye"

Fixed in modules where it will be visible, not fixed in a deprecated module whose interface is not shown, the module remains only to process old edits.

> 'light table' is written as a single word in all other cases

For the names of the working modes ("views") of darktable, a reference to the light table and the dark room of the times of analog photography was used. My understanding is that the two words in the names of these modes were merged into one to "terminologize" them, so we immediately understand that the text refers to the names of the modes, and not to concepts from film times. The text "Virtual light table, showing a collection" is used as a caption to an image that illustrates the program in metadata for inclusion in software centers. Here, the gluing words together is not necessary, here we just give the user a reference to the original term, to create an analogy with which the program mode is named.

> "African-american"

Yes it should definitely be capitalized, I just want to find what the most common name for ethnicity is in this context (African-American, Afro-American, perhaps there is another term for this ethnicity).

> "jp2"

This name is the file extension of the corresponding type (JPEG2000), and file extensions are traditionally written in lower case.

> rgb

As for the rgb, I'll go through the UI text again and see what can be fixed. Previously, I deliberately did not correct this particular term in module names, fearing that RGB in capital letters would dominate the actual module names written in lower case letters (while rgb is just a small clarification that we are facing a rework of the original version of the module that works in the RGB space).

**Comment by bgodole** [comment]
Thank you for the fixes, your time and the comments @victoryforce.

I am closing this as most of the issues here were addressed.
