### ISSUE TITLE
Unwanted scroll in sidepanel on mouse over in thumbnail list or film strip

### ISSUE THREAD

**Issue by ansluk** [darktable-org/darktable#14526]
### Describe the bug

Mouse over on a thumbnail in lighttables filemanager layout or the filmstrip in darktable causes the sidepanel to scroll to show the last expanded module if it's not fully visible at the bottom of the side panel. If the module is totally out of view the scoll will be queued and trigger when the panel is scrolled down to the point where the module becomes partly visible. The panel will then make a scroll jump to show the module completely.
This can be a bit annoying on a smaller screen in lighttable view when expanding the image information module at the bottom and then scroll up to double click a capture date in collections. When moving the mouse over to thumbnail view the left panel scrolls down to show image information fully. Collections are obscured and I have to scroll the side panel back to collections again to be able to select a new date.
Closing and expanding the collection module after expanding the image information module will stop this behaviour, but if this scrolling could be supressed with a resonable effort it would be great.

### Steps to reproduce

I have mouse wheel scrolls modules side panel by default activated
Resize the darktable window so that not both collection and image information modules can be completely visible at the same time when expanded.
Expand the collections module.
Expand the image information module.
Scroll back up to the collection module so that image information is mostly obscured.
Double click a capture date in collections to view the thumbnails.
Move mouse over a few thumbnails in central view and left panel will scroll down to show image information.

### Expected behavior

Darktable should not scroll the side panel on mouse over thumbnail

### Where did you install darktable from?

self compiled

### darktable version

4.3.0+2229~g68237e9f0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04 in wsl / Windows 10 msys ucrt64 

### Describe your system?

Gtk version in the windows 10 build is mingw-w64-ucrt-x86_64-gtk3 3.24.37.r22.gf1b6556-2.
In Ubuntu 23.04 its libgtk-3-0/lunar  3.24.37-1ubuntu1

### Are you using OpenCL GPU in darktable?

No

**Comment by Nilvus** [comment]
Your master is few days old. A PR merged 2 days ago could have fix that: #14512
Could you update master and test again? Please report result here and close that issue if fixed. Thanks.

**Comment by ansluk** [comment]
It's still present in current  master. I'll look around expander.c to see if I can find anything.

**Comment by Nilvus** [comment]
@AlicVB?

**Comment by dterrahe** [comment]
Scrolling is handled the "same" way in left and right panels; if the _focused_ module changes size, it is scrolled into view completely. But focus gets handled differently for the different kinds of modules; processing modules grab focus more aggressively when anything is changed in them, making it more likely that the right module is scrolled. Lib modules only get focus when expanded or, since recently, when a slider or dropdown is changed. An idea would be to assign and withdraw focus on mouse entering or leaving the module widget area. I'm away from my development machine until the end of the month so can't experiment if 1 this works and 2 doesn't have unintended annoying side effects.

Connect both enter and leave notify events to the same handler, passing it the module as user_data. Then something like
`darktable.lib->gui_module = event->type == GDK_ENTER_NOTIFY ? user_data : NULL;` might work.

**Comment by ansluk** [comment]
Thanks for explaining. I don't get is why those widgets claim they have been resized? On mouse over on the thumbnails it's usually just some text changing or highlighting in the module widget.

**Comment by dterrahe** [comment]
Changing text or even just font _could_ change size, so gtk recalcs and doesn't seem to compare with previous to see if unchanged, so propagates all the way up.
