### ISSUE TITLE
winget install does not work [Windows 11]

### ISSUE THREAD

**Issue by dreaddr** [darktable-org/darktable#14613]
Winget install via a user account (not root) does not work. It fails to locate the file in the user's temporary directory and cancels the operation. I have only faced this issue with darktable as other application installers work. Please look into this and fix this as winget is now an inbuilt package manager of Windows.

**Comment by MStraeten** [comment]
issues with winget better address at Microsoft ;)

**Comment by victoryforce** [comment]
> Winget install via a user account (not root) does not work.

Windows has no concept of a root user, so you probably mean problems when working from an account that does not have administrator rights. Such an account does not have the ability to elevate privileges to administrative ones, because it is simply not provided for by the account's capabilities. Therefore, when you perform an action that requires administrative privileges, Windows will simply prompt you to enter the credentials of an account that has such privileges. It's like a temporary login to Windows on behalf of another user, but only for one operation.

When you have performed the above-mentioned entry of credentials of a user who has rights to install programs, you are performing an action (running the installer extracted by winget to your user's temporary directory) on behalf of another user

> It fails to locate the file in the user's temporary directory and cancels the operation.

...and that's to be expected, since the other user usually doesn't have access to your home directory.

> I have only faced this issue with darktable as other application installers work.

No, they don't work. They could not work. At this point, winget tries to run the installer file it downloaded to a subdirectory of your home directory, but it can't access it.

> Please look into this and fix this as winget is now an inbuilt package manager of Windows.

There is nothing here that could be fixed in darktable. So I close this issue.

P.S. This could be fixed in winget, although I'm not sure if the fix will be accepted. This will include moving the temporary storage of the downloadable installers to a location where they are available to other users. To be honest, the use case presented in this issue is very perverse. If you want to install programs, add administrative rights to the account, or install under the login of the user whose credentials you enter to install.

**Comment by dreaddr** [comment]
> If you want to install programs, add administrative rights to the account, or install under the login of the user whose credentials you enter to install.

That is literally what I'm trying to do. I give it (the winget install prompt) escalation to run as an admin (which means its running with admin perms) but it (darktable) still doesn't install. 

> No, they don't work. They could not work.

The problem seems to be in locating the file itself, which I've had no issue with on other applications installed via winget. For example, I have no issue installing Kdenlive, GIMP etc. 

Also, yes, I mixed up root and admin because I jump between using both Linux and Windows. I'm just here to report an issue I faced, and IMO, I think you should try to understand the issue a bit more before closing it down. Just my two cents.

**Comment by ptilopteri** [comment]
If you stop and consider, darktable has no control over where you place it within your system nor how another application searches for it.  somehow your app, winget, must be able to locate it.  either you have placed it in a location not accessable to "winget" or winget is faulty in it's locating process.

**Comment by wpferguson** [comment]
darktable installs correctly on windows 11.  When you use winget to install it, it doesn't install.  This is a winget problem and should be reported to Microsoft.  The darktable devs don't control winget nor work on it.
