### ISSUE TITLE
Darktable does not see camera Nikon d500 (import, tethering)

### ISSUE THREAD

**Issue by makes3** [darktable-org/darktable#14623]
### Describe the bug

Darktable does not read connected camera. 

**env LANG=C gphoto2 --auto-detect**
Model                          Port                                            
----------------------------------------------------------
Nikon DSC D500                 usb:001,003     
 env LANG=C gphoto2 --port usb: --abilities
Abilities for camera             : Nikon DSC D500                              
Serial port support              : no
USB support                      : yes
Capture choices                  :
                                 : Image
                                 : Preview
                                 : Trigger Capture
Configuration support            : yes
Delete selected files on camera  : yes
Delete all files on camera       : no
File preview (thumbnail) support : yes
File upload support              : yes

**env LANG=C gphoto2 --port usb: --capture-image-and-download**
New file is in location /capt0000.nef on the camera                            
File capt0000.nef exists. Overwrite? [y|n] y
Saving file as capt0000.nef
Deleting file /capt0000.nef on the camera

**env LANG=C gphoto2 --port usb: --capture-image-and-download**
New file is in location /capt0000.nef on the camera                            
File capt0000.nef exists. Overwrite? [y|n] y
Saving file as capt0000.nef
Deleting file /capt0000.nef on the camera

**env LANG=C gphoto2 --port usb: --capture-tethered**
Waiting for events from camera. Press Ctrl-C to abort.                         
UNKNOWN PTP Event 0000, Param1 00000000
UNKNOWN PTP Property d1b1 changed
UNKNOWN PTP Property d1b1 changed
UNKNOWN PTP Property d1b1 changed
UNKNOWN PTP Property d1b1 changed
UNKNOWN PTP Property d1b1 changed
UNKNOWN PTP Property d1b1 changed
UNKNOWN PTP Property d1b4 changed
UNKNOWN PTP Property d1f1 changed
Saving file as _MAX8800.NEF
CAPTURECOMPLETE
UNKNOWN PTP Property d1b1 changed
UNKNOWN PTP Property d1b4 changed
UNKNOWN PTP Property 5008 changed
UNKNOWN PTP Property d1b1 changed
UNKNOWN PTP Property d1f1 changed
UNKNOWN PTP Property 5008 changed
UNKNOWN PTP Property d1b1 changed
Saving file as _MAX8801.NEF
CAPTURECOMPLETE
UNKNOWN PTP Property d1f1 changed
UNKNOWN PTP Property 5008 changed

### Steps to reproduce

1. conect the camera via USB
2. darktable on
3. tethering -> 'no camera with tethering support availabe for use'

### Logfile | Screenshot | Screencast

camctl.log

0,620965 [camera_control] creating new context 0x557a282ee6d0
0,621780 [camera_control] loaded 0 camera drivers.
1,034122 [camera_control] loaded 0 port drivers.
1,034180 [camera_control] 0 cameras connected

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

ubuntu 22.04

### Describe your system?

Micro-Star International Co., Ltd. MS-7C91
32,0 GiB
AMD® Ryzen 7 5700g with radeon graphics × 16
NVIDIA GeForce RTX 3060

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by paperdigits** [comment]
Are you using a .deb file, a snap, or a flatpak?

**Comment by makes3** [comment]
I'm not 100% sure, but probably snap (I checked in Ubuntu Software).

**Comment by paperdigits** [comment]
Since this is a snap, its a confinement issue, not a darktable bug. You can take it up with the snap packager.

**Comment by victoryforce** [comment]
@makes3 The darktable project does not provide first-hand and does not control the packaging of the program in flatpak and snap formats. It is also known about certain issues in snap/flatpak darktable packages, which are not found in the official builds of darktable and in the official packages of the distributions. I advise you to avoid installing darktable in flatpak or snap if possible.

The latest version with a slight delay after the release is built in OBS [for several of the most popular distributions](https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable). If you are on Ubuntu, there are PPAs ([Panda Jim's](https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/darktable), for example) that offer a fresh version even faster.

The problem you describe in this issue is [a flaw in creating a snap package](https://github.com/sergiusens/darktable-snap/blob/master/snap/snapcraft.yaml#L144-L148) that is at least 6 years old. I suspect all it needs to do is figure out what permissions the package needs, but the maintainers haven't done that yet.

Therefore, I am closing this issue, as fixing it is beyond our control.

P.S. To draw attention to this issue, I tag the maintainer of the darktable snap package, @sergiusens.
