### ISSUE TITLE
It appears xmp:s not read by different Darktable installations

### ISSUE THREAD

**Issue by macalje** [darktable-org/darktable#14683]
### Describe the bug

We have our photos on a network storage device. There are 3 computers accessing these photos with Darktable. 2 with Windows 10 and one with Linux Mint Cinnamon. When marking photos with stars and/or colors everything works fine on every computer. But, the markings made on one computer does not show up on another? I thought every computer would read the xmp-file and if that file was altered by another computer, these adjustments would show up on another computer, reading the same xmp aswell.

### Steps to reproduce

1. Set up darktable on 3 computers; 2 with Windows 10 and 1 with Linux Mint Cinnamon.
2. Keep photos with one xmp-file per image on a NAS. These pictures are imported to darktable database/library on every computer.
3. Rank and give color markings in Lighttable to photos in one compter (doesn’t matter which one).
4. Close darktable and shut down the computer.
5. Power up one of the other computers and start darktable.
6. In Lighttable mode, go to images that was marked and/or ranked earlier and now they isn’t?

### Expected behavior

Ranks and colormarkings should appear on every computer that has darktable installed sn the same picture file imported to its library.

### Where did you install darktable from?

darktable.org

### darktable version

4.2

### What OS are you using?

Linux

### What is the version of your OS?

Mint Cinnamon

### Describe your system?

Linux compter: home built, Intel i5 2:nd or 3:rd generation, 16GB RAM, 110GB SSD for OS and programs, over 1TB file storage. Pictures on a NAS.

Windows computer 1: home built, AMD 5-series recent generation (from 2021), 16GB RAM, 250GB SSD for OS and programs, over 1TB file storage. Pictures on a NAS.

Windows computer 2: Hp laptop, Intel i5-9:th generation, 8GB RAM, over 200GB SSD for OS, programs abd files. Pictures on a NAS.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia 610GT, Nvidia 1060GTX, Nvidia ?

**Comment by MStraeten** [comment]
is option ‚look for updated xmp files on startup‘ in preferences > storage set?

**Comment by macalje** [comment]
Thanks! Didn't now about that. I'll look it up this weekend.

**Comment by ralfbrown** [comment]
Another option would be to store the configuration directory (which includes the database) on the NAS by adding appropriate commandline options, but that has drawbacks as well:
1. only one user at a time across all connected computers
2. all computers must be running the same version of darktable (or at least close enough that they store compatible format versions of the database - but the equivalent requirement applies to sharing XMPs as well)

Note that as your library grows, "check for updated XMPs" will make darktable startup ever slower as it has to scan the entire library on disk.  That may eventually push you to using a shared config directory....

**Comment by macalje** [comment]
Ok, I'll tried MStraetens solution on my stationary Windows (my "main" computer which handles all my photos) and I really understand what ralfbrown means with _...will make darktable startup ever slower..._ :) That computer handles pictures from my grandfather and forward. Took a while to start up. I haven't tried it on the other computers yet, but I guess that it won't be the same issue there. That's because on these computers I only access last years photos and nothing more. Bur, Mstraetens solution did deliver exactly what I wanted.

The solution to keep the database on the NAS sounds appealing, but I guess I'll have one problem there: I'm not that advanced user of Darktable, so even if I understand what _...by adding appropriate commandline options..._ means, I don't understand how to do that in Darktable?

**Comment by ralfbrown** [comment]
You need to edit whatever shortcut you use to start up darktable to include the location of the configuration directory you want to use.

Not a Windows user; on Linux, most desktop environments will let you right-click on the program in their equivalent of the Start menu and select "edit".  In KDE, that gets you a window with four tabs (General, Permissions, Application, and Details).  On the Application tab, edit the field labeled Command: to insert "--configdir `<path>`" between the "/usr/bin/darktable" and "%U", where `<path>` is the full path to the directory on the NAS you would like to use for storing darktable's configuration and database files.  On Windows, you'd do something similar after right-clicking on the shortcut.

Darktable will create the directory if it does not exist, but you will probably want to create it and copy over the contents of /home/\<user\>/.config/darktable (actually, the Windows machine's equivalent, since you say that is the one with your entire image archive in its library) so that you don't need to re-import all your images and re-configure all your preferences and shortcuts.

One issue with sharing the database and config between Windows and Linux machines - Windows drive letters....  That results in different paths on different machines.  If all of your images are in a single directory tree, you can fix that in a couple of seconds each time you switch platforms (in Collection, select folder view, right click on the top-level folder and select "search filmroll", then input the location of the top-level directory on that machine).

**Comment by macalje** [comment]
Thanks for the clarifications.

When I started with the setup I also realized that on my main windows machine I have the jpg:s that I want to handle for selection to book projects from 3 different computers. But I also have a large number of raw-files, that I don't need to reach from the other machines.

If I understand the system and the suggested solution correctly, I will get my full library from my main computer moved to my NAS. So no I'm wonder if I really want to do that if I only want to "share"/"cowork with" xmp files from photos in subfolder to one of several "main" photo folders?
