### ISSUE TITLE
Tagging (keyword) input box (with ctrl+t) does not get focus - entering keyword won't work unless clicking on the input box

### ISSUE THREAD

**Issue by mlaverdiere** [darktable-org/darktable#14729]
### Describe the bug

With dt 4.4.0 on Fedora 38 Linux/GNOME/Wayland, when pressing ctrl+t to add keyword, the focus is not set to the little input box, so trying to enter keywords won't work and may trigger other actions linked to some shortcuts. To enter keywords, user has to click on the input box. Usually (before 4.2.1?), when pressing crtl+t, it was possible to enter keywords right away, as the focus was automatically set to the input box. This does not happen under X11, i.e. the input box get the focus.

### Steps to reproduce

1. Open dt in a Wayland session on Linux.
2. Select an image
3. Press ctrl+t
4. Try to enter kewords
5. See that the input box don't get the focus and that it is not possible to enter keyword unless clicking on the input box.

### Expected behavior

It should be possible to enter keywords right after pressing ctrl+t

### Where did you install darktable from?

OBS

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Describe your system?

GNOME, Wayland (X11 not affected by this bug),

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel® UHD Graphics (CML GT2)

**Comment by mlaverdiere** [comment]
Reopening this bug, since the fixes for bugs 13180 / 13867 did nothing for this particular bug. Confirming that it is a Wayland problem. When using dt 4.4.0 in a X11 session, everything works fine.

**Comment by mlaverdiere** [comment]
It appears to be fixed now on dt 4.4.2.

**Comment by hannonq** [comment]
@mlaverdiere so you are now able to use the tagging shortcut under Wayland on dt 4.4.2? 
I still have the same issue from [#13180](https://github.com/darktable-org/darktable/issues/13180) on dt 4.4.2. 

Running with `GDK_BACKEND=x11` works, but that's not an option for me because Xorg does't work with HiDPI dual monitor setup. Everything looks extremely blurry on my scaled 4K monitor.

So I'm curious if you found a fix, because I'm running dt 4.4.2 but the issue is still present.
