### ISSUE TITLE
What exactly is 'Standard Color Matrix' in 'input color profile'?

### ISSUE THREAD

**Issue by michaepr** [darktable-org/darktable#14735]
I would like to better understand the 'Standard Color Matrix' option in input color profile (I feel the documentation is not so clear on that). My current understanding is as follows:

- The output of the demosaicing step gives three ('R', 'G', 'B') values. These are not in a color space like (linear) Rec2020 but in the space defined by the sensor/filter on my camera. For example, the 'red' channel that my camera captures will not be the same red as in Rec2020. The input color profile converts the R, G, B values from the camera sensor profile to the working profile (eg linear Rec2020).

Is that correct? My second (main) question is:

- What exactly is the 'Standard Color Matrix' (for RAW files)? Is it the same for all camera models or is there some device-specific lookup? Where does it come from? Where can I find the coefficients of that matrix? (I looked for it in the source code but that was challenging since I'm not familiar with the code base ...)

Thanks for your help!

**Comment by ralfbrown** [comment]
Your understanding in the first bullet point is correct.

Standard Color Matrix is a model-specific 3x3 matrix mapping from the camera's R/G/B channels to (IIRC) the XYZ colorspace.  It's one of the things which needs to be set up in order to support a new camera model (usually extracted from DNGs produced by Adobe's DNG Converter), as it defines the color space used by the camera's sensor.

The values for each camera model are defined in Rawspeed and can be found in src/external/rawspeed/data/cameras.xml in your darktable source tree.

**Comment by michaepr** [comment]
Thanks for your fast answer, that's really helpful! 

Just one follow up: What's the target space of the matrices in cameras.xml? Is it CIE XYZ? (And does the 'input color profile' module then apply another transform from XYZ to the selected working space?)

**Comment by ralfbrown** [comment]
I'm not 100% certain the target is XYZ, but most other color transforms in dt go via XYZ and XYZ is the standard "connection space" used by ICC for both input and output profiles.
