### ISSUE TITLE
FR: Significant speedup when using OpenCL

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#14831]
**Is your feature request related to a problem? Please describe.**
Situation: When creating thumbnails or exporting images, when you have OpenCL, the CPU is not used.

Many computers have OpenCL and multiple CPU cores. 

Simple thought:
Darktable has two code-paths for rendering images; one for OpenCL and one for the normal CPU. 

If it is running OpenCL, and it is processing multiple images, it could feed some images into the CPU-processing.
Suppose the GPU is 4x faster than the CPU. Even then this would mean a 25% speed improvement at hardly any cost.

Example during rendering thumbnails:

![Darktable speedrun](https://github.com/darktable-org/darktable/assets/16322196/ad3ed7ed-e08f-4dcf-a6c2-6dccb04df641)

**Comment by jenshannoschwalm** [comment]
Well, pixelpipes simply don't work this way. Pipes might change from OpenCL to CPU codepath in many cases, a) modules might not have an OpenCL implementation at all b) might fall back to CPU because of tiling requirements on smaller OpenCL cards or some other reasons.

As dt might take a lot (or huge parts of your system memory) you might end up in memory requirements which are a) non-predictable and b) not to be reproduced for anyone.

So, not an idea to follow at all.

**Comment by jenshannoschwalm** [comment]
@ralfbrown i think "difficulty hard" is an under-estimation :-)

**Comment by rekcodocker** [comment]
Thanks, it was just a thought - like multitasking is a way to speed up using an already existing processing infrastructure.
If it does not work that way then this should not be attempted!
