### ISSUE TITLE
Graduated density module does opposite in 4.4.0, 4.4.1

### ISSUE THREAD

**Issue by broben2of3** [darktable-org/darktable#14844]
### Describe the bug

Graduated density module, in 4.4.0 and 4.4.1, does the opposite of what it used to do.  Photos that used it now show a lightening on the opposite side, instead of a darkening on the side it used to be.

### Steps to reproduce

Go to a photo that used the graduated density module before 4.4.0, you can visibly see the incorrect behaviour.

### Expected behavior

graduated density module should behave same way as pre 4.4.0

### Where did you install darktable from?

self compiled

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by ralfbrown** [comment]
Unable to reproduce, either with a new edit or with the sidecar from the integration test.  Please share a sidecar file showing the problem.

**Comment by broben2of3** [comment]
![_D786275](https://github.com/darktable-org/darktable/assets/117539930/f5f0428a-6efa-480a-987c-e8310554acc2)
![_D786275_1](https://github.com/darktable-org/darktable/assets/117539930/6092224e-9b8f-4321-aa86-a33cd7dd98fc)
[_D786275.NEF.txt](https://github.com/darktable-org/darktable/files/11960775/_D786275.NEF.txt)

Attached before 4.4.0, afterwards, and the sidecar file.  Note I changed the file ending of the sidecar file from .xmp to .txt so the Github uploader would accept it.

**Comment by ralfbrown** [comment]
So, the issue is with negative EVs, for which there is no regression test (yet).  Since your edit also has Negadoctor enabled, you brightened with graduated ND, which then gets inverted by negadoctor to a darkening.
The regression introduced by 4.4 is a shifting of the mid-line of the gradation due to adding 4 times the distance on every pixel instead of every fourth one (the update is in the inner loop instead of the outer loop), but only in the path for negative EVs.

There's also the unintuitive behavior that negative EVs brighten the portion that positive EVs leave unchanged and leave unchanged the portions that positive EVs darken.  That dates back to at least 2016, so making it behave more intuitively would break lots of old edits.

While I was at it, I checked on the issues reported in #13840.  The only thing I saw was a bright line at the point where the filter strength reaches zero, which color pickers verified as just a visual illusion (from the transition between gradient and uniform brightness).  But that's only visible with high EV settings *and* high hardness settings.
