### ISSUE TITLE
Linebreaks in metadata editor description stopped working

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#14877]
### Describe the bug

In previous versions of darktable one could introduce line-breaks with enter (or CTRL+enter, I don't remember).
Now pressing enter, along with pressing CTRL or other keys does not work anymore.

### Steps to reproduce

Select raw file in lighttable and open "metadata editor", now click into the "description" field and try pressing enter.

### Expected behavior

darktable should add a line-break

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+59~g6398066e16

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon rx 5700 xt

**Comment by ralfbrown** [comment]
Ctrl-Enter inserts a linebreak just fine for me on current (as of just now) master.
Plain Enter is used to save the current text in the field.

**Comment by da-phil** [comment]
Those are my shortcut settings, I even restored them to default, without success:

![Screenshot from 2023-07-17 00-13-34](https://github.com/darktable-org/darktable/assets/810285/7e42632f-7d88-4165-931a-e5c55d44cacd)

Does anybody have an idea what is going wrong here?

**Comment by dterrahe** [comment]
Your shortcut settings shouldn't make a difference as ctrl+enter handling is dealt with in the metadata widget code itself https://github.com/darktable-org/darktable/blob/059aa3a0b6f36e6962ac45886cffa46f47e18cb4/src/libs/metadata.c#L402 which takes precedence and nothing of relevance has chanced there in the last release.

You may try https://github.com/darktable-org/darktable/pull/14765 which attempts to make saving changes more reliable, but again shouldn't impact ctrl+enter handling.

Is there anything unusual about your system? Keyboard settings? gtk version? Do you have any issues with ctrl key detection elsewhere? (do shortcuts using it work as expected?)

**Comment by da-phil** [comment]
Thanks for your suggestions, I like the changes in your PR, although they do not fix it ;)
Maybe unusual about my setup is only that the keyboard is used behind a KVM switch, however I already directly plugged it into my PC to make sure the KVM switch is not doing some kinky stuff.
regarding gtk version: 3.24.33
regarding keyboard settings: nothing special I guess, however I have different input sources configured to allow typing Japanese and Chinese characters, but this setup did not change in the last years. I also just checked if I there is a CTRL+Enter shortcut set somewhere in gnome, but there isn't.

**Comment by da-phil** [comment]
> Your shortcut settings shouldn't make a difference as ctrl+enter handling is dealt with in the metadata widget code itself
> 
> https://github.com/darktable-org/darktable/blob/059aa3a0b6f36e6962ac45886cffa46f47e18cb4/src/libs/metadata.c#L402
> which takes precedence and nothing of relevance has chanced there in the last release.

After an experiment with inserting debug statements in this part of the code all seems fine, the following line is executed, however I'm not sure how it is even supposed to insert line breaks in the text fields:

https://github.com/darktable-org/darktable/blob/f8de8d155501a2c995d6b230ea9738961c6a47f7/src/libs/metadata.c#L410

It seems this function stopped working for me, maybe due to a change in logic in gtk widgets?
because when I do not register ``_key_pressed()`` inserting line-breaks works just fine.
I'm running ubuntu 22.04 with gtk3 version 3.24.33.

**Comment by da-phil** [comment]
I just learned that removing ``event->state &= ~GDK_CONTROL_MASK;`` makes it work again for me.
I also learned that ``_key_pressed()`` is executed 3x for only pressing CTRL once and 2x when I press CTRL+Enter. It's kind of weird, but I'm also not into how the gtk event loop works. I hope multithreading is not getting into the way of it...

**Comment by da-phil** [comment]
It seems also my laptop is affected by this issue and this does not have any fancy keyboard setup with KVM switch in between, however it runs the same OS (Ubuntu 22.04) with the same gtk version (3.24.33).
My post above explains a possible solution, which also just might be a dirty workaround, without understanding the underlying functionality properly.

**Comment by dterrahe** [comment]
I don't know what's going on in your specific case, but I'll try to explain what the code is _meant_ to do.

Normally, when typing an enter into a textview, the widget key handler inserts a new line. However, for the metadata fields we want enter to commit all the changes, so that's what the `else` of the `dt_modifier_is(event->state, GDK_CONTROL_MASK)` test does. To still enable newlines, we also check for ctrl+enter which we then want to be handled by the textview as if it was a normal enter (hence, insert a new line). If I now type an enter or ctrl+enter in any other textview, they do the same thing, but it seems that sometime in the past ctrl+enter would not work, so the ctrl needed to be stripped off the event before letting it be filtered by the IMContext and (if that doesn't fully deal with it) be handled by the widget event handler by returning FALSE. That's what the `event->state &= ~GDK_CONTROL_MASK;` does. It might not be needed as, since I said above, these days it seems that textviews accept enter and ctrl+enter interchangeably as a new line. Could you please confirm  that this is the case under your gtk version as well? (for example try the big css textview in settings/general).

The only other thing I can think of that differentiates your setup from ours is that you use Japanese and Chinese input methods. It is possibly that `gtk_text_view_im_context_filter_keypress` returns TRUE when it is fed a (ctrl+)enter, preventing further processing by the textview. Maybe there even was a recent change in gtk in that area? Not sure why that could have a different impact when called from a key-pressed handler rather than directly in the textview key handling. Is it easy to try switching off those input handlers?

**Comment by da-phil** [comment]
> Could you please confirm that this is the case under your gtk version as well? (for example try the big css textview in settings/general).

Yes, I can confirm that both pressing enter or CTRL+enter lead to a newline in this widget.
Tbh, I do not think it is due to some input method as this would mean Chinese / Japanese speaking folks would have filed an issue before.

Can you check if removing `event->state &= ~GDK_CONTROL_MASK;` on your end leads to undesired behaviour? 
Which gtk version do you use?

**Comment by da-phil** [comment]
After rebuilding DT from scratch I noticed that both my PCs did not show this issue anymore :sweat_smile: 
Maybe this was due to some older build artifacts this lurking around in the build folder, wouldn't be the first weird behavior caused by that...
I think this issue is safe to be closed.

**Comment by da-phil** [comment]
@dterrahe I'm re-opening this issue as it happens again on both my PC and laptop, both running ubuntu 22.04.
I'd like to collect feedback from other users using ubuntu 22.04 and created a PR: https://github.com/darktable-org/darktable/pull/15385
