### ISSUE TITLE
Andriod/iOS port

### ISSUE THREAD

**Issue by Nikita-Presnov** [darktable-org/darktable#14876]
Is it planned to port to mobile platforms?

**Comment by MStraeten** [comment]
no, there‘s no one working on that - btw that requires plenty of dependency libraries also be ported to those platforms.

**Comment by Nilvus** [comment]
We have few  developers and developing a software that works on Linux, MacOS and Windows correctly is not easy and some bugs remains on MacOS and Windows because we have few developers on such platforms. And a a software like darktable is I think better to use on a PC.

I so close as we probably never have darktable on such platforms. And not sure it's really worth the case to do it.
