### ISSUE TITLE
Keyboard shortcuts doesn't match actual key mapping

### ISSUE THREAD

**Issue by colinvidal** [darktable-org/darktable#14897]
### Describe the bug

Accelerators/shortcuts seems to follow OS input source order priority rather than the actually selected input source.

### Steps to reproduce

Repro on Debian 12 build using Gnome desktop environment:

- in OS/Gnome keyboard settings, set
    - "Francais (BEPO)" as first choice
    - "Francais (obsolete, variante)" as second choice 
- you'll now have in Gnome top bar a menu to select the actual keyboard mapping. Select "Francais (obsolete, variante)" 
- In Darktable, go to the lightroom mode
- select an image
- press 'f' key to toggle "full screen/preview" mode

Nothing will happen but a toast saying "_e_ not assigned" shows up. Turns out that F key of an AZERTY mapping matches E key of a BEPO mapping, so I assume that for whatever reason, Darktable picks the top mapping for accelerator detection when multiple mapping are available.

I suppose this can be reproduce easily with other mapping/shortcut combination.

### Where did you install darktable from?

Debian 12 repositories.

### darktable version

4.2.1

### What OS are you using?

Debian GNU/Linux

### What is the version of your OS?

Debian 12

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Mesa Intel Graphics (ADL GT2)

**Comment by rlefevre** [comment]
I'm not sure why this bug was closed, I can confirmed this is still the current behavior on Ubuntu 24.04 with Darktable 4.8.1, with both the AppImage and the ppa repository version. Please reopen this issue.

For example using Colemak keyboard layout on an Azerty physical keyboard. The "w" shortcut in lightable requires me to enter "z" key and therefore does not respect the configured keyboard layout. This is very confusing.

**Comment by rlefevre** [comment]
New issue here: https://github.com/darktable-org/darktable/issues/17968
