### ISSUE TITLE
darktable Windows - language is stuck on English

### ISSUE THREAD

**Issue by MrGamy** [darktable-org/darktable#14977]
### Describe the bug

As stated above, I can't get darktable to change the GUI language on windows. 
A clean reinstall, including deleting \AppData\Local\darktable, does not help. I also checked darktablerc in the AppData folder and the setting seems correct: `ui_last/gui_language=de`

The language displayed stays fixed to English, no matter which language I choose.
I also tried to install darktable on C: instead of a different drive to no avail.

### Steps to reproduce

install darktable on windows
go to the general settings
change the language
restart

### Expected behavior

GUI language changes to the specified language

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment]
I remember we (or rather, our users) have been bitten by this bug before. This is a Windows specific problem that does not occur on other platforms. There were something like two or three issues raised, but the solution to the problem was never found.

Can you tell me, please, what are your Regional settings in Windows?

**Comment by jchenaud** [comment]
Same problem
