### ISSUE TITLE
To have consistent keyboard shortcuts across the different views

### ISSUE THREAD

**Issue by fabiosirna** [darktable-org/darktable#15005]
**Is your feature request related to a problem? Please describe.**

In the darkroom view to quickly rotate an image you can hit [ or ].
The same shortcuts are assigned in the lightable view to:

- [ utility modules/timeline/start selection
- ] utility modules/timeline/stop selection

From a user and usability consistency point of view, it would be nice to have the same shortcuts in different views for those commands that do the same thing, such as rotation in this case.

**Describe the solution you'd like**

To assign the same shortcuts by default to those commands that are doing the same thing across different views.

**Alternatives**

Overall, user can override shortcuts according to their preferences but new users can be confused not having consistent shortcuts across their photography workflow.

**Comment by fabiosirna** [comment]
Hey @dterrahe thank you for your response.
I thought about the comment I made and I understand that the solution is not simple.

When I opened the request I was trying to configure a MIDI keypad (I have a roland TR8) to assign some functionality that I use often, such as navigating between images.

In darkroom mode:
- views/darkroom/image back 
- views/darkroom/image forward 

In lighttable mode:
- /views/lighttable/move/horizontal 

But you have to assign as effect → previous|middle|next

I understood this difference after your comment because I tried to figure out what I was missing. I can't do more similar examples because I don't know all the functionality, but if it happens I will update the comment.

On the user side, prably my frustration comes from the difficulty of interacting with the shortcut configuration.

In the UI there are two action lists and when I try to filter I don't understand the logic of the results. In the attached screenshots for example I would like to filter the /views/lightable actions to see what all the shortcuts are. The only way is often by trial and error.

From a user's perspective I expect to be able to do a few things:

- search by shortcut (e.g., ESC key or CMD+B combination or CC86 or C2 (36) in the case of a MIDI device) and see what function is assigned
- search for an action and see which shortcuts are assigned (this is possible to do but the filter does not return the result I expect)
- figure out if the same shortcut is assigned to multiple actions: I have seen that it is possible to assign multiple shortcuts to an action and if it is by design, I don't understand the advantage.

I am still experimenting and if I come up with a solution I will update the comment. In the meantime if there is anything I can do, let me know.

![SCR-20230811-oeou](https://github.com/darktable-org/darktable/assets/2249234/8f7f5bb5-f659-4fe7-9fb3-68db6508c97a)
![SCR-20230811-ogai](https://github.com/darktable-org/darktable/assets/2249234/9a93506d-159c-4444-93fb-fe03a38ab07f)

**Comment by dterrahe** [comment]
> there are two action lists

There is one actions list and one shortcuts list

> The only way is often by trial and error

You can also try reading the manual or tooltips. You could also try one of the recent nightlies with #14991 that hope to improve clarity a little bit (whether successfully or not I don't know because there's near zero feedback).

Clicking on an action or section (in the actions list) will filter the shortcuts list to only show shortcuts for the selected action/section. If no action is selected, all shortcuts are shown, divided in "active view" and "other views"; this helps to see which keys are available in the current view. Looking for consistency across views is maybe less of an everyday task for common users; it might be easier to look directly in shortcutsrc (after sorting it).

> * search by shortcut

The shortcuts list is ordered by key, so it should be easy to find the one you are after (but only per category, i.e. in "active" or "other views"

> * the filter does not return the result I expect

What do you expect?

> * I don't understand the advantage

Without being able to assign multiple shortcuts to the same action, you'd have to chose between a MIDI _or_ a keyboard shortcut instead of being able to use both. Many actions have multiple elements (for example a slider and a color picker), so you can set one shortcut for one and another for the other (possibly with different effects, for example "reset").

It would be very helpful if you tried, with your first impressions and confusions still in mind, to figure out (with the manual, tooltips and experimentation) all the functionality of the shortcut system and then suggest improvements that could help newcomers get up to speed quicker. For someone like me who knows all the ins and outs of the implemented approach (and the reasons why) it is nearly impossible to imagine themselves in their place.

**Comment by fabiosirna** [comment]
I am closing the issue because when I wroteit, I was not clear how darktable worked and I don't think the problem statement is clear.
