### ISSUE TITLE
Lens correction not applied with PEN-F, but same lens with E-P5 is working fine

### ISSUE THREAD

**Issue by steph72** [darktable-org/darktable#15101]
### Describe the bug

When processing images taken with the Olympus PEN F, the lens can't be found in the correction database

![image](https://github.com/darktable-org/darktable/assets/51749597/a1954452-9f2a-464a-93d8-ef2f65b7eaa4)

...but with pictures taken with the Olympus E-P5 and the (physically) very same lens, the lens is found and the corrections are applied ok:

![image](https://github.com/darktable-org/darktable/assets/51749597/5f3c18fd-0455-4d92-becb-b2d59591bbe1)

### Steps to reproduce

1. Import a picture taken with a PEN-F and the 17mm 1.7 lens
2. try to apply lens correction: camera/lens not found
3. Import a picture taken with the E-P5 and the same lens
4. try to apply lens correction: works

### Expected behavior

darktable should apply the lens correction regardless of what camera the lens is used on

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3 LTS

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q], nvidia-driver-535

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

If needed, I can supply RAW sample images.

**Comment by ralfbrown** [comment]
This is an issue with lenfun, not darktable.  lensfun needs to know both the camera and the lens to be able to properly adapt the distortion information to the body being used (specifically, it needs to know the crop factor).

You should run `lensfun-update-data` to get the current copy of lensfun's database, rather than the one pre-installed on your machine (which is probably two years old).  On my system, it includes the PEN-F.
