### ISSUE TITLE
reopen of #5893 #11137 #3619

### ISSUE THREAD

**Issue by Dannny1** [darktable-org/darktable#15160]
### Describe the bug

When it was closed as "not planned" at least warning at start would be nice, to notify user about the broken color management that can ruin their work.

### Steps to reproduce

in  #5893 #11137 #3619

### Where did you install darktable from?

darktable.org

### darktable version

3.0 - master

### What OS are you using?

Windows

### What is the version of your OS?

W8.1 - W11

### Are you using OpenCL GPU in darktable?

No

**Comment by MStraeten** [comment]
If you want these up to 3 years old issues to be reopened you should provide new reasons why.

**Comment by Nilvus** [comment]
On at least 2 issues, you have had answers. If you ignore them, that will not help... You precise here darktable 3.0 - master. So which one, master or 3.0 ? 3.0 is about 4 years old... Update your issue and precise recent infos and update on what you really want. Will be hard to help (and not close again your issue) if you provide so few infos and let only old infos...

**Comment by Nilvus** [comment]
Oh and please update your title to explain real issue for you!
I'm sorry but if in few days, this issue is not clear, I will close. We need to have clear issues and not too much, to see on what we can work. And this software is made in their free time freely by a small team of developers. We can't please all people. Thus, issues without activities are close in a year.

**Comment by Dannny1** [comment]
> If you want these up to 3 years old issues to be reopened you should provide new reasons why.

Why? was it solved? 

> Update your issue and precise recent infos and 

At this point it would be quite naive to think that it will help anything. Title , prepared nicely formatted text prepared to be used also elsewhere ... all closed.

> update on what you really want.

What i want? Actually not much. As i was told on forum that this is the proper place which users should follow to be informed about issues. So maybe it's all fine till some info is still present in issue.

And when i will see again users on forums confused and in despair about their scuffed images, i can instead of RTFM rub it in via these github issues and laugh at them that they do no know about it.
Because ... who reads the manual/notes anyway?

> I'm sorry but if in few days, this issue is not clear, I will close. 

I didn't expect anything else, i learn this lesson,  there is only close or autoclose.

**Comment by ptilopteri** [comment]
you really presume quite a lot on other people providing something for you for free and cannot be bothered to offer explanation of your needs with out deriding those same individuals.

**Comment by Nilvus** [comment]
So you really do not understand (do you want to?).
We solved many issues there, so no it's not only close or autoclave. It's about we can do something or not AND if users help us to help them... or not.

**Comment by Dannny1** [comment]
> you really presume quite a lot on other people providing something for you for free

Is it me who presume a lot? Or is it the presumption that my work (all the testing and retesting at least with each release) on this for all these years has no value and is "free", is core of the problem here, leading to such random closures? 
And we are not talking ignoring here.. but active action which make even harder to people to find out what is going on. That's imo special kind of evil.
Even tho this doesn't need to bother me as i don't depend on dt for my edits. 

> So you really do not understand 

No, i think you don't understand, i'm not talking other issues. 
But based on peoples comments dt don't have anybody who would be able to fix this, as it's windows specific.
And to let the users know.. well i don't want to repeat myself.

**Comment by wpferguson** [comment]
> as it's windows specific.

It may be specific to just your hardware and your configuration.  

In order for a dev to work on this, they first have to be able to recreate the problem.

Most (all?) the devs do not run windows. So, in order to recreate the issue they need to procure a Windows machine capable of running darktable and 2 monitors ($1.5K?).  Once they do that, they then need to run darktable and see if the problem occurs.  It may not depending on driver versions, display hardware, windows version, etc.

IF they can recreate the problem, then they start looking for the root cause.  It may be something in darktable or it may be a windows issue.  If they find an issue with darktable, then they try and fix it.    They may not be able to.  

So....

You have the hardware, software, and configuration to recreate the problem.

AFAICT you are the only one who has reported the problem.

You haven't supplied a list of hardware and software, so even if someone was willing to spend the money to buy the hardware and software necessary to troubleshoot this, they wouldn't know what to get.

This may be a case where you need to scratch your own itch (which is how most (all?) of the devs became devs).  That doesn't necessarily mean you need to fix it.  If you could just narrow it down to a section of code, that would be helpful.  Or, if you discover it's a windows/configuration/hardware/driver issue, then you could document it and help someone else out.

**Comment by dterrahe** [comment]
Now that #3619 has been reopened, can this issue be closed? Having a lot of duplicate uninformatively named issues makes it harder for users to find information they need.

**Comment by Dannny1** [comment]
> AFAICT you are the only one who has reported the problem.
> This may be a case where you need to scratch your own itch

I saw many people on various forums confused because of this, it's not just my hw.
As you may see e.g. here recently reported: #14784
It seem that another "lucky" person had to find about it the hard way.
So it's not nvidia issue either, as the hw ther is amd and competely different.

And as i wrote above i don't depend on dt; and also windows is not my only or primary platform, so it's not my own itch, i'm not so affected by it. However if there is a way how to prevent other people to go through same, it may be good to let them know if possible before they will butcher their edits.

**Comment by Dannny1** [comment]
> Now that https://github.com/darktable-org/darktable/issues/3619 has been reopened,
Thanks i'll close this.
