### ISSUE TITLE
Highpass module affects highlights outside the mask

### ISSUE THREAD

**Issue by MilanLes** [darktable-org/darktable#15162]
### Describe the bug

Using highpass module with drawn mask is affecting highlights of the image outside the mask. 

Changing blend mode to Normal or any "Lab..." mode will not change this highlight. With highpass module I'm using contrast enhancing blend modes which are all affected by this strange behavior (see images in attachment).

Attachment contains exported file without highpass module, with highpass module turned on (red circle to indicate the issue), screenshot of my darktable with mask shown, original RAW file, sidecar XMP file.

### Steps to reproduce

1. Open darktable
2. load image P5291741.ORF with corresponding XMP sidecar file
3. turn highpass module off

### Logfile | Screenshot | Screencast

[highpass module issue.zip](https://github.com/darktable-org/darktable/files/12503732/highpass.module.issue.zip)

### Commit

N/A

### Where did you install darktable from?

darktable.org

### darktable version

3.8.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro 22H2

### Describe your system?

AMD Ryzen 5 1600 Six-core Processor, 16 GB RAM, NVIDIA GeForce GTX 1060 6GB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1060 6GB, NVIDIA 31.0.15.3667

**Comment by ralfbrown** [comment]
Overlay is a display-referred blending mode.  All of the display-referred blending modes except "Normal" clip pixel values to the range 0..1 (-128 to +128 for the Lab 'a' and 'b' channels) because the math breaks down outside that range.  You'll need to reduce the brightness of the highlight to use Overlay blend.

If you want a contrast-enhancing blend without clipping, switch to "RGB (scene)" and use Multiply.
