### ISSUE TITLE
Consider adopting a Code of Conduct

### ISSUE THREAD

**Issue by trespaul** [darktable-org/darktable#15205]
In light of recent tensions in the community, I suggest adopting a code of conduct to reduce the likelihood, or enable swift resolution, of future conflict. The well-known and established [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) is the first option that springs to mind.

**Comment by Nilvus** [comment]
Tensions were already more than a year (about april and may 2022). I don't see also any since. Even if your proposal is interesting and worth considering, I'm not sure we have to go that way. Writing all things is not always the only and best way. As actually and tensions were for quite few weeks and no more there, is it really necessary?

**Comment by wpferguson** [comment]
I agree with @Nilvus.  I think anyone who was involved in (or had a front row seat to) last years incident never wants to see that happen again.

If you peel all the layers of that away, it was basically just a communications problem.  

I think that we as a community now watch for issues that have the potential to be a problem like that and try and step in early to make sure there is clear communication and understanding, so we don't end up there again.  Hence my comments on #15172.

**Comment by trespaul** [comment]
Thank you all for your replies.

I erred on the side of brevity because I'm mindful of your time, but I could have been more specific. I was personally in particular disappointed, when doing a deep dive into darktable, to find out about the rift that saw a contributor fork literally and metaphorically from the project. I'm aware I have no stake other than as a user and supporter of darktable (although I would contribute if I had the necessary technical skills!), so all I can say is that it is upsetting to learn of the conflict. So I thought I'd share the idea I had of adopting a CoC.

You're right that time has passed and things have settled. I thought, however, that a CoC could perhaps cement the knowledge gained from the experience, so as to have the burden of ensuring a welcoming community (and deciding what that means in the first place) not fall solely on the shoulders of volunteering individuals, but rather on the project itself — to have it built-in, as it were. (For example, on GitHub issues, every contribution page or box has a link to the project's contributing guidelines — a CoC would simply slot in there. Then, any inappropriate behaviour can be simply not accepted, without any tedious individual case-by-case justification via a discussion digging down to ethical first principles.)

(By the way, I realise that this might not be a priority at the moment, so please do close the issue etc. if preferred.)

**Comment by dterrahe** [comment]
> not fall solely on the shoulders of volunteering individuals, but rather on the project itself

Could you further explain the distinction you are making here? This project is nothing more than a group of volunteering individuals. There is no paid staff, no committees.

I agree with you that having a place to point to rather than starting from first principles can be useful, when and if the need arises. On the other hand, eventually it comes down to what each individual or the project manager is willing to put up with.

Having procedural discussions _on top of_ technical ones may not lead to a happier place. Already the length of discussions one has to contend with is a reason for complaints (and a reason for some to leave and start their one-man-band where they have full control and can insult and threaten at will; our CoC would have no "power" there).

But fully agreed with sentiments expressed earlier that currently there is no immediate need and the past episode only seems to have strengthened our "community".

**Comment by victoryforce** [comment]
@trespaul If you're talking about the case where one of the contributors left the project because of a different vision of darktable's development direction (I don't see it as _tension in the community_, that's why I asked), then I don't see how CoC could have prevented it. It is the same as traffic accidents cannot be prevented by adopting traffic rules.

Thank you, however, for your desire to help the project. But I agree with @dterrahe's point of view: "Having procedural discussions on top of technical ones may not lead to a happier place".

**Comment by trespaul** [comment]
@dterrahe I'm really glad to hear that the experience has been that the community has strengthened. Regarding the distinction, with "the project itself" I meant the whole, the collective, as opposed to the individual who may find themselves in a situation where they have to make a decision about how to act / respond / etc. So the whole point is to _avoid_ procedural discussion, since a code of conduct can be used as a handy reference, and also shifts "blame" for the decision away from the individual, both of which in turn makes it easier to make decisions. (So it's not up to the individual PM or whoever to decide how much _they_ are willing to put up with, but the community has already decided how much everyone is willing to put up with.)

@victoryforce well, it's of course not the forking itself that is unfortunate, but the circumstances under which it happened, i.e., the conduct leading up to it. Since I was not involved, I cannot say that one thing or another might have prevented it, but I imagine that a CoC could enable quicker recognition of unwanted behaviour in order for it to be addressed. The specific mechanisms for "enforcement" of the CoC would need to be established, but imagine for example a three-strikes rule that can be used to identify people who act detrimentally toward the project, and to remove them (or to give them a time-out) if they do not stop acting detrimentally. By the traffic analogy, I would argue that traffic rules are there exactly _to_ prevent accidents; everyone yields to the oncoming traffic when entering a traffic circle _because_ we have established that that is the safest behaviour. Without traffic rules one would have to stop and decide the best course of action at every intersection. So, the whole point is to avoid procedural discussion, not create more of it (granted, even if there has to be some admin done up-front).

But, regardless, if you say that there does not currently seem to be the need, then I'm happy. Thank you for your engagement and input (and reassurance)!
