### ISSUE TITLE
Vague tooltip in lens's manual vignette correction

### ISSUE THREAD

**Issue by lbilli** [darktable-org/darktable#15235]
### Describe the bug

This is a minor pet peeve, but in the `lens` module's `manual vignette correction` section, the tooltip over the mask icon simply reads "button".

Few descriptive words might be more useful.

### Steps to reproduce

- Go to lens module
- In the manual vignette correction section, hover over the mask icon to display the tooltip

### Expected behavior

More meaningful text is displayed

### Logfile | Screenshot | Screencast

![lens](https://github.com/darktable-org/darktable/assets/12815378/22ec1a55-2c19-4e62-be2a-560403c82a61)

### Where did you install darktable from?

OBS

### darktable version

4.5.0~git592.4fa7a254

### What OS are you using?

Linux

### What is the version of your OS?

openSUSE Tumbleweed

### Are you using OpenCL GPU in darktable?

None

**Comment by dterrahe** [comment]
It is even worse!! The only reason that superfluous "button" "tooltip" shows up is because none of those sliders have any tooltips set (if hovered they show the generic tooltip set at the collapsible section level). For buttons like this, that are linked to the "bauhaus" slider or combo to their left, there is no infrastructure to show an individual tooltip; they would just show the same tooltip as their widget.

I could add the needed functionality quite easily, but someone would have to offer to provide tooltips for all the color pickers and other tools that would benefit from it, otherwise it is not worth it.

**Comment by jenshannoschwalm** [comment]
> It is even worse!! The only reason that superfluous "button" "tooltip" shows up is because none of those sliders have any tooltips set

Understood :-) Will look into that pretty soon, working on embedded lens OpenCL implementation right now ...

**Comment by dterrahe** [comment]
Would you use a `dt_bauhaus_widget_set_quad_tooltip` if I implemented it?

**Comment by jenshannoschwalm** [comment]
Yes 😀
