### ISSUE TITLE
Cannot import styles

### ISSUE THREAD

**Issue by paeony** [darktable-org/darktable#15248]
### Describe the bug

"import..." button on styles module in lighttable returns an error on the command line but otherwise does nothing.

### Steps to reproduce

1. Install Darktable from Flathub
2. Go to lighttable
3. Open styles
4. Click on "import..."

### Expected behavior

Open an import dialog

### Logfile | Screenshot | Screencast

```
Gtk-Message: 22:09:55.716: Failed to load module "xapp-gtk3-module"

(darktable:2): Gtk-WARNING **: 22:10:00.817: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Portal operation not allowed: Unable to open application info file
```

### Where did you install darktable from?

flatpak

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 21.2 Victoria

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I get the same error if I try to import presets. Note however that the import module for photos works just fine.

**Comment by Nilvus** [comment]
darktable team do not provide support for flatpak packages. And sometimes, they are some specific issues from them. Did you try with a classic deb package? You can find them on OBS repository (see install page on darktable.org). Would be good if you test with deb package. I use master (so a little more recent than 4.4.2) but didn't see another issue nor fix about such issue. So probably an issue on your side and related to flatpak package. I let your issue open waiting for your feedback and if possible test with deb package. If the issue is confirmed to from flatpak package, think about closing it and go to pixls.us forums and still want to use flatkap to find help.

**Comment by paeony** [comment]
I tested 4.4.2 from OBS and it worked fine. So this is a flatpak issue. So I'll close this issue. Thanks!
