### ISSUE TITLE
Parametric mask - mousewheel operates on the wrong slider

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#15269]
### Describe the bug

Normal & desired behaviour:

When the mouse cursor is on one of the triangle-sliders, the mousewheel operates that slider.  This is perfect for fine adjustments.

Bug:
Sometimes the mousewheel operates on the wrong slider.  Example, the mouse cursor is on the top slider but the wheel operates on the bottom slider.   
In that case you have to click somewhere on the top slider, which unfortunately sets the slider to the location of the click.  After that the fine adjustments work again on the top slider.

### Steps to reproduce

Use parametric mask.

Click+hold to drag one of the triangles to a location.

Now, wherever the mousecursor is located, the wheel operates on that last slider instead of the one it is closest to.
 

### Expected behavior

Always operate the mousewheel on the closest slider.

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2 

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel UHD and intel driver

**Comment by dterrahe** [comment]
> click somewhere on the top slider, which unfortunately sets the slider to the location of the click.

Ctrl+click does not move the slider but _does_ select the closest triangle.

**Comment by dterrahe** [comment]
You can select one of the four triangles by right-clicking near it.

One of the problems I can see with scrolling the "closest" triangle is that scrolling makes it move and now it may not be the closest anymore. Or turning the scroll wheel might cause a small vertical mouse move and now you're scrolling the bottom instead of the top one.

But the bigger issue is that people seem generally unhappy with the four-way slider anyway. Fixing small annoyances on an old codebase feels especially pointless if presumably somebody someday is going to rip it apart and completely redo it. This is also why you can't set up shortcuts to these widgets.

**Comment by rekcodocker** [comment]
Are you sure?    It already moves the closest slider. Which is fine.
The problem is:  When I drag one of the sliders, then the behaviour changes. 

I am not unhappy with the four-slider, please do not make this issue part of a general unhappyness, which I do not share.

**Comment by dterrahe** [comment]
> Are you sure? It already moves the closest slider. Which is fine.

You are right; when no triangle is selected, the closest slider is scrolled and if you scroll for a while so that it isn't the closest anymore and then inadvertently make a small mouse move it may switch to another one unintentionally.

So maybe you could amend the title and description of this issue to say that "when a slider is selected, mousewheel operates that slider". To me, this seems absolutely intended (and wanted) behavior; I may not want to have to keep the mouse absolutely still to not be switched to another slider. If I use both dragging and scrolling, then probably scrolling is meant to make further small adjustments to the slider I just dragged. But as said above, if that isn't the case for you, you can (de)select a slider by right-clicking, which will not move it. I don't see any further "fixes" that wouldn't break other people's workflow. Please consider closing this issue.

> I am not unhappy with the four-slider

I'm not saying individual people are unhappy with _all_ of four-way slider, just that many people are annoyed by different aspects of it and to fix _all_ those things, a complete overhaul is probably the only solution. But even more likely there is no solution because people want different things and prioritise their own preferences. So the fact remains that this is an unrewarding piece to work on because the overall feedback on any change will be negative ("happy enough" people tend to stay quiet).
