### ISSUE TITLE
Getting cache folder used by darktable when using Lua api

### ISSUE THREAD

**Issue by gid000** [darktable-org/darktable#15262]
**Is your feature request related to a problem? Please describe.**

I could not find a way to get the actual folder I'm storing my cache imaged or the cache image path.

**Describe the solution you'd like**

If possible, and if that makes sense, to return the full path of the cache folder.  ie: `~/.cache/darktable/mipmaps-3811b20baa4325315445d9dda22ca5cb0f2a45ad.d/`.

**Alternatives**
Another alternative would be a method of any image to return the cached image path:
```
img:get_cache(4)
```
This would return the full path of the image on that cache.

**Additional context**

I would like to find the cached version of an entry so I can work on that.

Does that makes any sense?

**Comment by wpferguson** [comment]
The Lua API call just calls the same generate cache method used by darktable, thus the generated images are put in the same cache as darktable uses. 

The point of using the Lua API to create the cache is that you can be more responsive (i.e. I can create cache images after an import of after an image is edited in darktable view).

In the mipmaps directory, there will be a set of folders 0, 1,2, 3, 4, 5, 6, 7, 8, 9 that correspond to the mipmap size.  The actual cache images are located in those directories.  Not all those subfolders may be present, since the folders are created when the sizes required for you system are created.

The location of the cache directory is available from the API, https://docs.darktable.org/lua/stable/lua.api.manual/darktable/darktable.configuration/

**Comment by wpferguson** [comment]
Maybe it would help if you could explain what you are trying to do. 

Why do you need to retrieve the cache image?  That's what darktable does automatically.

**Comment by wpferguson** [comment]
Query the cache dir, then use the mipmap directory you get, the size you want, and the image.id

**Comment by wpferguson** [comment]
> You mentioned in a different thread depending on the binary/install method cache will be different folder.

I said it would be the same.  I've said that 2 or 3 times in different ways.

Like this...

`The Lua API call just calls the same generate cache method used by darktable, thus the generated images are put in the same cache as darktable uses.`


Let me try this

The is only **ONE** function in darktable that generates cache files.  Whether it's called internally by darktable, or called from a lua script, it's the **SAME** function.  

Since there is only **ONE** function, it uses the same mipmaps folder.

**Comment by wpferguson** [comment]
From above

The location of the cache directory is available from the API, https://docs.darktable.org/lua/stable/lua.api.manual/darktable/darktable.configuration/

**Comment by wpferguson** [comment]
I get a full path

```
    13.8240 LUA config dir is /home/bill/.config/darktable45
    13.8241 LUA cache dir is  /home/bill/.cache/darktable45

```

**Comment by wpferguson** [comment]
As I've said before......

There is a mipmaps folder with subfolders based on cache size


You're trying to do something with the cache that it's NOT designed to do.  There is no guarantee that the files will be there.  When the cache gets low on space it frees some up by deleting files.

If you  want to do image recognition, take the contrib/face_recognition.lua  and use it as a model of how to do it.

**Comment by wpferguson** [comment]
> So... as I've said before: why is the API returning only ~/.cache/darktable/

Because the darktable cache contains more than just mipmaps.  The opencl kernels are also cached after compilation.

Here's a script to find the mipmap folder.

[mipmap_folder.zip](https://github.com/darktable-org/darktable/files/12667145/mipmap_folder.zip)

**Comment by wpferguson** [comment]
Fixed.
