### ISSUE TITLE
Getting mipmaps cache folder via Lua API

### ISSUE THREAD

**Issue by gid000** [darktable-org/darktable#15291]
# Is your feature request related to a problem? Please describe.

I could not find a way to get the actual folder I'm storing my cache images or the cache image path. darktable.configuration.cache_dir returns the root folder of all cache, not only mipmaps.

Documentation still shows the original intention, but was fixed recently, thanks to @wpferguson. (vide #15262 discussion).

Yes, we could delegate this task to the script developer to find the exact mipmaps folder, but it would be much easier for them to get the actual folder those cache are stored from darktable API.

This will make things consistent and be prepared for future changes, avoiding breaking contributors scripts, if darktable decides to change those folders place. iiuc, the hash logic used by mipmaps folder is inside darktable, so wouldn't make sense to avoid duplication of that logic in many contributors scripts?

# Describe the solution you'd like

Since the documentation was updated, having another method to return the mipmaps folder: 
`darktable.configuration.mipmaps_folder` would return the full path of the cache folder. ie: ~/.cache/darktable/mipmaps-3811b20baa4325315445d9dda22ca5cb0f2a45ad.d/ (or ~/.var/app/org.darktable.Darktable/cache/darktable/mipmaps-xxxx), regardless of the actual installation method.

# Alternatives
Another alternative would be a method of any image to return the cached image path:

img:get_mipmap_cache(4)

This would return the full path of the image on that cache.

# Additional context

I would like to find the cached version of an entry so I can work on that.

**Comment by wpferguson** [comment]
I've already given you a piece of code that does exactly what you want.

This isn't worthy of an API change, since the information is easily accessible as I have already show you.

And I've also warned you about manipulating the cache directly or relying on something being there (since it's a cache and things come and go).

I've also told the the better way to solve you problem using the exporter to generate your images then running your object recognition script against that.

I'm really, really, really tired of this conversation.

**Comment by wpferguson** [comment]
To sum it up, this information is already accessible using the curren lua api and 9 lines of lua code.

**Comment by wpferguson** [comment]
> yet they exist for user convenience.

They exist for functionality.  If they didn't exist you couldn't write a lua script to manipulate darktable.

My rule of thumb, and the rule of thumb of my predecessors, is can it be done with the existing API?  If not, then we look at making a change.

Changing the API is not free.  Someone has to write the code, someone has to test it, and someone has to maintain it.  

If we start adding "convenience" functions then were does it stop?  What is the criteria that decides what is added and what is not.  If we add everything that gets asked for then we end up with an unmaintainable (and unusable) mess.

When I first started using the API I kept thinking if I only had this function or that widget, or ...  When I realized that wasn't going to happen, I dug in and learned the API and how to use it.  Once I reached that level of understanding I could finally appreciate what a great job @boucman, @houz, and others have done creating and maintaining the API.

Since I've taken over the API the things I've added create functionality that didn't exist.  For convenience, I've written several lua libraries with lots of functions to that people don't have to keep recreating the wheel.

If this is about convenience, then create a lua library, add the function to get the mipmap folder, include the library in your script and use your convenience function.

This is your third issue about this.  I'm beginning to believe that the only acceptable answer for you is I'll change the API.  Put yourself in my shoes for a second and try and look at it from my point of view:

1. You want to contribute a Lua script to darktable.  It's your first contribution.
2. You are just learning the API and don't have much understanding of it.
3. Your darktable experience is a couple of years or less?
4. You can implement the function you require in Lua, but don't want to.
5. In the 6+ years I've been doing this no one has ever asked for this function, so there's little to no need for it, or they just coded it themselves.
6. You've decided the API is not correct and needs changed.

What would you decide?
