### ISSUE TITLE
Soft proofing not working with profiled monitor

### ISSUE THREAD

**Issue by zk453** [darktable-org/darktable#15313]
### Describe the bug

Hello! it seems that the soft proofing function is not working, or i am doing something really wrong.
When i activate the softproof function, and change the softproof profile from the dropdown, nothing changes in the preview.
I have my calibrated display profile, and when softproofing to sRGB nothing changes on the preview, but the exported image is very different. In order to view the image properly as it will be exported, i need to change my display profile and not the softproof profile. I thought merely activating the softproof should display the sRGB image correctly.

I have attached various screenshots, on the left is the second preview window of darktable with sRGB display profile and on the right is the preview with softproof on and off

sRGB Display profile left, sRGB Display profile right
![Screenshot_20230923_215904](https://github.com/darktable-org/darktable/assets/36011542/80b69ca1-e0b0-4996-a677-a6181478d56e)

sRGB Display profile left, System default Display profile right, with softproofactive active
![Screenshot_20230923_215926](https://github.com/darktable-org/darktable/assets/36011542/0bd89140-044d-4849-8677-59432f4e5400)

sRGB Display profile left, System default Display profile right, with softproofing inactive
![Screenshot_20230923_215940](https://github.com/darktable-org/darktable/assets/36011542/b1271941-f0ec-4a81-9aff-5dd8537a7d02)

You will notice in the screenshot that the image on the left is more saturated and the base of the trunk is darker.

### Steps to reproduce

1) Use a non factory display profile.
2) Edit a raw file to get out of gamut colors
3) Change the softproofing profile while keeping the display profile to the default image and Notice that the preview image is not changing, but the histogram does
4) Change the histogram profile, and notice that the histogram does not change

### Expected behavior

change the histogram profile when the histogram profile option is changed, and change the preview colors to reflect the selected softproof profile

### Where did you install darktable from?

darktable.org

### darktable version

darktable 4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 23.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

gtx 1080ti, 11gb memory , driver version: 525.125.06

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I also uploaded the raw file with the xmp on google drive in case it aids with the debugging
https://drive.google.com/file/d/11H0LEAym1_-tMjGcDVtv9HmPRyq2TUds/view?usp=sharing

**Comment by zk453** [comment]
Is that the default behavior? I thought it would change the preview because it writes soft-proof on the bottom left corner.

**Comment by todd-prior** [comment]
> Is that the default behavior? I thought it would change the preview because it writes soft-proof on the bottom left corner.

I think this has been discussed at some lenght in the past I will try to find the relevant post or posts and update this reply...

**Comment by KarlMagnusLarsson** [comment]
I use an EIZO Color Edge CG279X Wide Gamut calibrated monitor and darktable 4.4.2 and git master development works for me when I soft proof. This is a somewhat subjective statement. 

1. I soft prof using sRGB when I have to fit a wide gamut range to smaller sRGB. When I put darkroom into softproof I can see the out of gamut colors change in darkroom main window.
2. I soft proof using a Durst-Lambda-C-print profile for Fujifilm photo paper (soft proof profile from printing company) before sending to printing company. This profile is more advanced and supports different rendering intents. Again, I can notice the loss of contrast when simulating the photo paper and the change in out of gamut colors depending on rendering intent. (I have LittleCMS2 activated in darktable).

I usually toggle gamut check first and any changes are confined to areas indicated by gamut check. 

I can not comment on the histogram. I have no insight into how it works. My default histogram profile is a non linear ProPhoto profile from RawTherapee (RTv4_Large), since i normally work in ProPhoto until committing for print or web.

**Comment by zk453** [comment]
@KarlMagnusLarsson does changing the display profile to sRGB, wield the same results as changing the softproof profile?
I tried littlecms2 and the softproofing still did not work.

If it works in your machine, there might be a problem with my darktable config.
I also deleted the config files for darktable and the issue still persists. So it is not a problem with my config.

**Comment by KarlMagnusLarsson** [comment]
@zk453 

> does changing the display profile to sRGB, wield the same results as changing the softproof profile?

I do not know. I have not tested. I am uncertain what that would mean. My calibrated monitor result is characterized in a device profile for my monitor. I would rather not change it to some other type of profile, like a sRGB working space profile for storage & archiving. 

I sometimes put the monitor itself in sRGB instead of the wide gamut monitor profile. This is useful if the source is not color managed and presuppose that everything is treated as sRGB (videos in web browser, in my case). However the darktable application _is_ color managed from the start.

@zk453, do you have a wide gamut monitor? For sure some saturated colors outside sRGB change when rendered via rendering intent in smaller sRGB space.  But if you have an sRGB monitor from the start, then this effect is not obvious if you soft proof sRGB. If you have an sRGB monitor (not wide gamut), then try and test with a printer softproof profile instead. Some printing companies offer these on their web pages. Printing can have large or small color gamut, but the contrast is usually lower, compared to a monitor and this effect is often quite noticeable, when softproofing.   

I suppose those who know darktable color management code can help you better than I can, when it comes to how darktable work and how to test.

I must say sRGB was a pretty smart choice, when developed. If I do not push color saturation and stay out of taking pictures of paintings, flowers, some insects or neon lights, then almost all I get fits in sRGB nicely, from the start. The Pointer’s Gamut – the coverage of all possible real surface colors is bigger than sRGB, but you have to work a bit to find it.

**Comment by zk453** [comment]
My monitor is not sRGB, but the softproofing does not even change the preview on the debug softproof profiles (The one that says BRG (for testing)
![Screenshot_20231001_235516](https://github.com/darktable-org/darktable/assets/36011542/5eb67105-c73a-4a45-8db2-5cc31c45f7f5)
![Screenshot_20231001_235536](https://github.com/darktable-org/darktable/assets/36011542/55f723d1-64bd-4e08-bc0d-d80d5ef9dcaa)
Changing the softproof profile does not do anything, but the display profile in the menu changes the preview

**Comment by parafin** [comment]
Why would BRG soft-proof profile change the output?

**Comment by KarlMagnusLarsson** [comment]
> @KarlMagnusLarsson does changing the display profile to sRGB, wield the same results as changing the softproof profile?

Hello again @zk453. I misunderstood your question. I thought of the system display profile (Gnome 4, Linux Debian, in my case). You meant: darkroom ->  toggle gamut check ->  display profile.

1) if I set darkroom ->  toggle gamut check ->   display profile = sRGB (web Safe) I get an over saturated display of the image in darkroom main window, if I use EIZO monitor native wide gamut setting (the profile my monitor uses, stored in semi persistent monitor memory).

2) If I set darkroom -> toggle gamut check ->   display profile = sRGB (Web safe) and my EIZO monitor to sRGB then I recover normal rendering (in sRGB gamut).

This is to be expected. If darktable application is told to render darkroom main window using display profile = sRGB (web Safe) then it will first translate darktable working space to sRGB and send it to my monitor. If the monitor is in native wide gamut state (case 1), then it is expected to get an over-saturated image.  sRGB is a small space, even not so saturated pixels pixels get 'large' coordinates. When these hit my wide gamut monitor (larger than sRGB) the pixels are interpreted correctly, as having 'large' coordinates, in wide space and are rendered super saturated. In 2) the the monitor is ordered to use sRGB and what darktable renders (sRGB) is correctly interpreted by my monitor, since monitor is in sRGB mode, I recover a nice image with normal saturation, but with limited sRGB gamut.

Again, for me, this is another  test which shows that my system is color managed and that darktable color management works.

**Comment by zk453** [comment]
@parafin  oh, so does softproofing only preview black level and contrast and doesnt change the color?

@KarlMagnusLarsson  I downloaded the icc profile of a printer and indeed it changed the preview. So i must be missing some essential understanding on how to utilize the color management tools of darktable. My problem arose because when i exported (sRGB, perceptual)  the image colors looked a lot more saturated in the browser window (opened on chromium) than the preview on darktable with the system display profile. But when i changed the display profile to srgb then the colors looked exactly like the ones on the browser. I thought softproofing would preview that change. Thank you for your patience Karl and sorry for taking up your time.

My display is just a little better than sRGB (calibrated with spyderx pro) do you have any recommended resources that i could look so i can understand color management better? and what would your settings be if your aim was color accurate photos for the internet (monitor set to sRGB, and display profile in darktable sRGB?)?

**Comment by parafin** [comment]
This just means that chromium isn’t color-managed. To emulate unmanaged apps you do exactly that - set display profile to the same value as export profile (so sRGB). Soft-proofing on the other hand assumes that everything is color-managed and allows you to see correct colors after they are fit into export profile (basically equivalent to converting to soft-proof profile and then to display profile). So soft-proofing does change colors at least by limiting the gamut, but that requires colors outside of said gamut (e.g. sRGB). This means colors can only get duller, not more saturated.

I think you mostly understand everything correctly, but made a wrong assumption that browser can be used as a reference for colors. You must use some color-managed image viewer instead.

**Comment by KarlMagnusLarsson** [comment]
> My problem arose because when i exported (sRGB, perceptual) the image colors looked a lot more saturated in the browser window (opened on chromium) than the preview on darktable with the system display profile. But when i changed the display profile to srgb then the colors looked exactly like the ones on the browser.

> My display is just a little better than sRGB (calibrated with spyderx pro)

@zk453, One has to take care when it comes to the application rendering the image. If chromium is color managed and it is able to find and use your system display color profile, then the same image should be rendered, but if chromium is not color managed, then sRGB color profile (on a monitor with gamut bigger than sRGB) will render saturated colors. I agree with @parafin that one must take care and use a color managed viewer. I am also on Linux and I use Geeqie as a color managed viewer. I think that 'Image viewer' from Gnome is also color managed. 

Try Geeqie http://www.geeqie.org/. `Check settings -> Color management` of Geeqie and try 'use system profile' or point to explicit icc profile for monitor. 

Take care of the of the desktop as well. On Gnome I configure  `settings -> color` to the icc profile of the monitor.

If you try a color managed picture viewer like Geeqie or 'Image viewer' from Gnome, then the display of the picture viewer will correlate nicely  to the darktable output.

**Comment by KarlMagnusLarsson** [comment]
> ) do you have any recommended resources that i could look so i can understand color management better?

https://docs.darktable.org/usermanual/4.2/en/special-topics/color-management/

https://www.eizoglobal.com/library/index4.html 'Color management for creators'

https://www.drycreekphoto.com/Learn/resources.htm 'Color management' section (books)

https://www.cambridgeincolour.com/tutorials/color-management1.htm

**Comment by todd-prior** [comment]
> do you have any recommended resources that i could look so i can understand color management better

Lot's of great info here... https://ninedegreesbelow.com/

**Comment by zk453** [comment]
Thank you for the resources and your time @KarlMagnusLarsson  @parafin  and @todd-prior!

**Comment by parafin** [comment]
I don’t know how many times one has to explain, that enabling soft-proofing doesn’t change the colors the same as changing the output profile… Rec2020 is very wide-gamut, so I would expect no changes at all when using it as soft-proofing profile.
The question might be is why histogram and color picker change values. It’s probably an old functionality before separate histogram color profile setting was introduced.

**Comment by todd-prior** [comment]
> I’ll admit that perhaps there’s something I don’t understand, but I would like to suggest – and I’m not trying to be snarky – that you consider that SP isn’t working properly. Or, if someone could help show how SP is supposed to function then that would probably silence the questions.

Dave ICC profiles have types. I think this is one function that will respond to the correct profile...If you use a printer profile... say out of the blue try this one.... 
[RR UPSatin 2.0 Ep7600.txt](https://github.com/darktable-org/darktable/files/13550807/RR.UPSatin.2.0.Ep7600.txt)
Rename it ICC... I guess I could have zipped it...github wouldn' let me load an ICC file... This is a printer specific... ICC and I think if you copy this to your color out profiles folder and set it as the softproof profile you will see changes in the display....the feature is for printing and not viewing other colorspaces...  Don't take my word for it but I think this is the issue with what you are seeing....

**Comment by parafin** [comment]
Choosing Rec2020 soft-proofing profile means you want to preview on your screen (whose gamut, I assume, is smaller than Rec2020) how image would look on some imaginary monitor that could display all Rec2020 colors. Please explain to me, what results do you expect and why?

**Comment by parafin** [comment]
Also please read #15590

**Comment by Dave22152** [comment]
Thanks Todd, I can see the differences in the profiles. This will help as I’m trying to work out some related issues I’m encountering during export. I appreciate your willingness to help, as always. Sent from my iPhoneOn Dec 4, 2023, at 3:04 PM, todd-prior ***@***.***> wrote:﻿

I’ll admit that perhaps there’s something I don’t understand, but I would like to suggest – and I’m not trying to be snarky – that you consider that SP isn’t working properly. Or, if someone could help show how SP is supposed to function then that would probably silence the questions.

Dave ICC profiles have types. I think this is one function that will respond to the correct profile...If you use a printer profile... say out of the blue try this one....
RR UPSatin 2.0 Ep7600.txt
Rename it ICC... I guess I could have zipped it...github wouldn' let me load an ICC file... This is a printer specific... ICC and I think if you copy this to your color out profiles folder and set it as the softproof profile you will see changes in the display....the feature is for printing and not viewing other colorspaces...  Don't take my word for it but I think this is the issue with what you are seeing....

**Comment by todd-prior** [comment]
There are a few export related threads and issues you might be able to check them out and get some insight... I found the first thing was that several windows file viewers do a crap job of color management or there is a misconfiguration between the OS and DT... Once I got my monitor calibrated and then made sure everything was using the same profile that really helped. I have been using lately an icc profile from color.org as it has a table so I can do perceptual and relative renders.... I found for me xnviewer was the best for viewing my exported files... I could set the same profile in my OS, DT, and that software to be sure they were all using the same output to the display. Many others you can't set it or you have to rely on the "system" setting. There are 3 icc profiles at color.org... 2014srgb.icc, a slight tweak on the srgb standard. Appearance and Perceptual. They can all do perceptual and relative renders and there are slight differences between them. I would say try the default DT one and compare it with these or one of Elle's profiles and see if you can find a result that works better for your exporting....

**Comment by Dave22152** [comment]
Thanks Todd.  Right now I’m trying to account for some differences between JPEGs exported on DT and how they’re displayed on IrfanView as well as Firefox, which led me to the softproofing question.  I’ll go through PIXLS again and check out your color.org site.

**Comment by todd-prior** [comment]
I’ll PM you at some point and share my experience with this and not distract the topic at hand here…
