### ISSUE TITLE
(4.2.1 and 4.2.2) darkroom segfaults in /src/common/imagebuf.h:73, dt_simd_memcpy._omp_fn.0 when opening an image

### ISSUE THREAD

**Issue by Xephobia** [darktable-org/darktable#15310]
### Describe the bug

I'm on gentoo, and installed darktable for the first time. When I try to open an image I imported (either by double clicking or clicking on "darkroom"), darktable crashes at "loading image IMG". I should mention that i use gentooLTO, but i've disabled lto and O3 (I still have graphite optimisations on which toggles `fgraphite-identity` and `floop-nest-optimize`

### Steps to reproduce

1.  Launch darktable
2.  Double click on an imported image
3.  Segmentation fault

### Expected behavior

darkroom should appear correctly

### Logfile | Screenshot | Screencast

[gdb.txt](https://github.com/darktable-org/darktable/files/12706074/gdb.txt)
emerge --info darktable : [emergeinfo.txt](https://github.com/darktable-org/darktable/files/12706080/emergeinfo.txt)

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Describe your system?

Gentoo, GCC 11, Wayland, gtk+ 3.24.38, libomp 16.0.6

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Tested with 4.2.1 and 4.2.2, same results
Affects both RAW & JPEG

**Comment by ralfbrown** [comment]
It's an unaligned memory access.  There have been many changes to the codebase between 4.2 and 4.4, so you should try with 4.4.  I took a look at the relevant bits of the code for a recent master and the relevant data structure is in an aligned allocation.

**Comment by shersunny** [comment]
1.) Make sure your Darktable installation is up to date. Run the following commands to update and rebuild Darktable:

sudo emerge --sync
sudo emerge --update --newuse --deep darktable

2.) Check for Known Issues:
It's always a good idea to check the Gentoo forums or Darktable's official forums for known issues and solutions related to your specific environment.

3.) Check Debug Information:
Run Darktable from the terminal with the --debug option to see if any error messages or debug information is displayed. This may provide valuable insights into what's causing the crash. For example:

darktable --debug

Look for any error messages or warnings that might help identify the problem.

4.) Disable Graphite Optimizations:
Since you mentioned you have graphite optimizations enabled, try disabling them to see if that resolves the issue. Edit your make.conf or relevant configuration file and remove any Graphite-specific flags. After making the change, rebuild Darktable and test if it opens images without crashing.

5.) Check Image Format and Metadata:
It's possible that the specific image you're trying to open has an issue with its format or metadata. Try opening different images to see if the problem is consistent. If it's only happening with one particular image, check that image's format and metadata.

6.) Create a New User Profile:
Sometimes, configuration issues can lead to crashes. Create a new user profile in Darktable by running the following command:

arduino

darktable --conf new

This will reset Darktable to its default settings for that user. Try opening images with the new profile to see if the issue persists.

7.) Check System Logs:
Review system logs to see if there are any relevant entries that might provide insight into the crash. You can use dmesg and /var/log for this purpose.

**Comment by Xephobia** [comment]
Hi, I'm sorry for the inactivity. The issue still occurs as of darktable 4.6.0, with lto and O3 replaced by O2 (and by consequent, disabling graphite), at the same place. I should also have mentioned I have some the `cet` and `hardened` USE flags on (description of the `cet` USE flag : ```When combined with USE=hardened, GCC will set -fcf-protection by default when building software. The effect is minimal on systems which do not support it, other than a possible small increase in codesize for the NOPs. The generated code is therefore compatible with i686 at the earliest.```)
