### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by mkz212** [darktable-org/darktable#15361]
1. Sync whole Darktable in iCloud - settings, presets, watermarks etc.
2. Easy way to add watermarks.
3. Option to batch merge bracketed images or/and option to import bracketed images and merge them during import.
4. "Mouse wheel scrolls modules.. " should be default enabled.
5. Sky replacement AI.
6. Option to select action after export, like open folder etc.

**Comment by ralfbrown** [comment]
dt has a Watermarks module, and you can create a style including an instance of it which gets applied on export, if you don't want to see the watermark while editing.

The project barely has enough resources to support the Mac port at all, let alone adding new Apple-specific features.  So don't hold your breath on iCloud support.

Similar for AI.  There's a video on Youtube showing how to use the Watermarks module to replace the sky with one from another image.

**Comment by mkz212** [comment]
Yes I know, but you need to add svg to specific folder - you cannot just select in darkroom panel any image to use as watermark.

**Comment by victoryforce** [comment]
> Yes I know, but you need to add svg to specific folder - you cannot just select in darkroom panel any image to use as watermark.

And then the user will guarantee that this image will always be in the same place on the file system? Do not forget that darktable is a non-destructive editor, you do not save the edited image, but create an edit history file (so called sidecar or XMP file). If editing depends on external files, they should be stored in a separate location so that you can transfer them to another computer when needed.

**Comment by difrkaguilar** [comment]
> 1. Sync whole Darktable in iCloud - settings, presets, watermarks etc.

As @ralfbrown wrote there are not enough devs to wotk in it.

> 2. Easy way to add watermarks.

There are some [RF] about if. #9955 #14338 #9991

> 3\. Option to batch merge bracketed images or/and option to import bracketed images and merge them during import.

Not suitable idea. in the lightable there are Merge HDR and other modules like Enfuse to accomplish this tasks in a better way.

> 4. "Mouse wheel scrolls modules.. " should be default enabled.

That's depending of the users.

> 5\. Sky replacement AI.

As other says darktable is a RAW developer, not a composition software as GIMP, Krita, Photoshop or Luminar. There are some workaround to do sky replacement using the watermark module, but it's not the best option.

> 6\. Option to select action after export, like open folder etc.

I set a [FR] about it but #11246 this is a hard task because the compatibility with different OS and managers.
