### ISSUE TITLE
darktable crashes importing folder of assorted images

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#15477]
### Describe the bug

Darktable crashes when importing a folder of assorted image types.  It does not crash if you only import Canon CR2 and CR3 files.

### Steps to reproduce

1. Gather some assorted image files (raws, dngs, tiffs) and make sure there more than just Canon raws.
2. Start an import
3. darktable crashes

### Expected behavior

a lighttable full of thumbnails to look at

### Commit

f3deba711d431c7f3ae6c5f0cfbcfa80de22f26c

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+970~g84c55f84cf

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

12th Gen Intel(R) Core(TM) i7-12800HX
32GB
4K

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia 535

**Comment by wpferguson** [comment]
bisect gives

f3deba711d431c7f3ae6c5f0cfbcfa80de22f26c is the first bad commit
commit f3deba711d431c7f3ae6c5f0cfbcfa80de22f26c
Author: Victor Forsiuk <vvforce@gmail.com>
Date:   Sun Oct 22 21:10:12 2023 +0300

    Calculate crop factor for Canon cameras

 src/common/exif.cc | 30 ++++++++++++++++++++++++++++++
 1 file changed, 30 insertions(+)

@victoryforce I tested to make sure it worked, I didn't think to test to see if it didn't.  Sorry

**Comment by wpferguson** [comment]
Maybe change the `else`  to an `else if` and make sure it's a Canon raw so that you don't get random images?

**Comment by victoryforce** [comment]
@wpferguson Thanks for the bug report and bisect!

I don't see how this code reading the Exif of a specific image currently being imported could cause a crash because of a particular set of images in the import session. So I suspect that there is one particular image in this set where darktable crashes.

May I ask you a favor to find this image?

> Maybe change the `else` to an `else if` and make sure it's a Canon raw so that you don't get random images?

There is actually `else if`, and we get into the newly added code if there is no `Exif.Photo.FocalLengthIn35mmFilm` tag in Exif and there is an `Exif.Photo.FocalPlaneXResolution` tag. This situation may not be specific to images from Canon cameras, so no manufacturer checks are done.

**Comment by wpferguson** [comment]
It appears to be something to do with RAF files.  Here's a link to a couple that it crashed on, https://drive.google.com/drive/folders/16CbKQf1U7W4r39nlb8mNv59pwlN0WBr7?usp=sharing

**Comment by victoryforce** [comment]
> It appears to be something to do with RAF files. Here's a link to a couple that it crashed on,

Thanks for the samples, now everything is clear! I should not have expected that all cameras strictly adhere to the Exif specification and should not "save" on checks, this is my mistake.

Tomorrow I'll add checks (to avoid trying to read a value when the tag isn't actually found) and also the ability to get information from alternative tags.
