### ISSUE TITLE
Second window do not change show crop region when using Retouch or Liquify

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#15501]
**Is your feature request related to a problem? Please describe.**

If an image has been cropped and we open Retouch or Liquify the whole image is displayed and the crop region drawn as an overlay. This has been done to make it possible to use some cropped region as source for Retouch for example. All fine.

The same behavior is done for the second window. I don't think this is necessary (we don't work on this view)  nor good. The second window should be kept as the view of the final image. 

**Describe the solution you'd like**

Never uncrop the second window.

**Comment by TurboGit** [comment]
@jenshannoschwalm : What do you think?

**Comment by jenshannoschwalm** [comment]
Absolutely. Only main window

**Comment by dterrahe** [comment]
Yep.

As you know, this means separate treatment of pipes for the different purposes and "smooth panning" (#15436/#15084/previous blocky approach) won't be able to simple scale up the preview image to fill in the unavailable parts. As long as _just_ the crop is switched off, #15436 could help pick up the right area in the preview anyway (since we're round-tripping to RAW coordinates) albeit at even lower resolution. But if there is framing applied after the crop then that won't necessarily work.

Snapshots have similar issues (the "global" preview doesn't apply to the snapshot).
