### ISSUE TITLE
Changing the module order frequently

### ISSUE THREAD

**Issue by jonasberge** [darktable-org/darktable#15519]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when using black and white LUTs and I have to push it up 4 times with the drop down menu and my mouse to put it under the "monochrome" module. There doesn't seem to be a shortcut for it and I can't change the order in module layouts presets. Dragging the module with a modifier key and my left mouse button also doesn't seem to work.

**Describe the solution you'd like**

Any of the above things I tried could be a solution, but a shortcut might be the simplest. Maybe allowing the "order position" to be stored in a module preset would also be nice. That way I can activate my preset and the module would automatically go to the position I want it to go. Would be nice.

**Alternatives**

**Additional context**

If there's a solution I don't know of, please tell me! Thanks.

**Comment by wpferguson** [comment]
You can move modules in the history stack by pressing control and shift, then left clicking on the module and dragging it to the position you want.

You can also create styles and include the module order so that when you apply it the module order is what you desire.

**Comment by dterrahe** [comment]
1. You can save a preset for module order (bottom right) once you have moved the module from its default place (the module order is "custom"). You might be able to auto-apply for certain kinds of images.
2. You can assign a shortcut key to the "instance" button of the module you want to move (using visual mapping mode). If you have shortcut fallbacks enabled (bottom of the shortcuts dialog) then holding that shortcut key and scrolling (or moving the mouse up/down) moves the instance position.
4. If you don't want to enable shortcut fallbacks in general, you can assign key+scroll (or other move) directly to the instance button. If you don't want to use visual mapping mode, goto shortcuts in preferences, double click on the processing module, perform the shortcut (for example hold i and scroll at same time) and then for the newly created shortcut (in the bottom half of the dialog, change the element from "show" to "instance"
5. Since there's also a fallback for "instance" (double right click) you could skip changing the element, i.e. just assign a shortcut to the module, and then use key+double right click+mouse move up/down. You then have the other fallbacks available too (single right click for presets, double left click for reset).
6. You can also assign a shortcut to the virtual processing module called `<focused>`, in which case it will apply to whichever module is currently focused.

Combined with @wpferguson's suggestions, i think you should be pretty well covered.

**Comment by jonasberge** [comment]
Thank you for your thorough comments! I also found the ctrl+shift shortcut in the docs now, after looking more closely.
