### ISSUE TITLE
[Security] lua used in this project is vulnerable

### ISSUE THREAD

**Issue by the-Chain-Warden-thresh** [darktable-org/darktable#15537]
### Version

latest

### What is the security issue or vulnerability?

As CVE-2022-28805 described, singlevar in lparser.c in Lua lacks a certain luaK_exp2anyregup call, leading to a heap-based buffer over-read that might affect a system that compiles untrusted Lua code. According to the CVE description, version 5.4.3 is affected by this CVE. However, lua 5.4.3 is still used in this project.
This can be easily fixed by apply the patch of this CVE ( CVE-2022-28805 ) , as listed in the next section.

### Security issue or vulnerability information

CVE-2022-28805's description:https://nvd.nist.gov/vuln/detail/CVE-2022-28805
CVE-2022-28805's patch commit:https://github.com/lua/lua/commit/1f3c6f4534c6411313361697d98d1145a1f030fa

**Comment by wpferguson** [comment]
My thought...
1. The internal Lua is turned off by default.  The build system Lua gets linked in at compile time, so it should be fixed.  We just need to see if the build system Lua is either security patched or later than 5.4.4.
2. My preferred method of fixing the internal Lua is to upgrade from 5.4.3 to 5.4.6 (current).  This takes care of the security issue and gives some bug fixes.
3. We are getting late in the 4.6 release cycle, so I'd prefer to do this early in the 4.8 cycle so that I have plenty of time to test.
