### ISSUE TITLE
relax CLang compiler version for the 4.6 release tarball

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#15659]
The current requirement is CLang-14. This compiler is not available in some "old" version like Debian-11 (not that old).

I'm still not sure to know what this is imposed as we have dt tested with CLang-12 in GitHub-CI.

I'm proposing to patch the darktable tarball to allow building with CLang-13 which will allow the release to be built available in more OS versions.

@victoryforce @jenshannoschwalm @dterrahe @zisoft @kmilos : As dt main devs I'd like your input on this?

TIA.

**Comment by victoryforce** [comment]
Platform and compiler version support policy essentially mean that we ___do not guarantee___ successful build of the program with older versions. That's all. This fact does not imply that it is necessary to make changes to Cmake files that ___prevent___ compilation with older compilers, even when in fact the source code compiles without problems with older compilers.

So my suggestion is to bring back the ability to compile with Clang 12.

**Comment by jenshannoschwalm** [comment]
I have no experience with this so no sound opinion.

**Comment by zisoft** [comment]
For macOS on github runners macos-12 is the oldest available release which comes with Xcode 14 (LLVM 14) so Clang 12/13is not an option here.

This does not prevent users with (virtual) machines running an older version of macOS to build dt, as long as the compiler is able to do that.

**Comment by dterrahe** [comment]
The only thing I can add is that I suspect most developers are running relatively up to date distributions, so they will likely not notice if an older compiler fails completely to build or produces faulty binaries. The normal PR checks don't seem to include an older clang anymore, so I probably wouldn't notice if I used any functionality that is only available/working/supported on newer versions. So if users compile with older tools (without being aware) we may not be able to reproduce or even think of the possibility that's the reason. If it were possible to recommend during build to upgrade (or require an additional action, suggested by build.sh, to enable older tools) then there might be less wasted time.

But otherwise I agree we don't need to _enforce_ restrictions unless we know they are really necessary.

**Comment by MStraeten** [comment]
even recent Xcode 15 supports building for macOS back to 10.13 - so not really an issue to build and run dt for quite old macs ;)

**Comment by jenshannoschwalm** [comment]
> If it were possible to recommend during build to upgrade (or require an additional action, suggested by build.sh, to enable older tools) then there might be less wasted time.

Could we add some build info into the debug log maybe?

**Comment by jenshannoschwalm** [comment]
Just mentioning #15600 here, a not understood issue maybe related to an elder clang version.

**Comment by TurboGit** [comment]
> Just mentioning #15600 here, a not understood issue maybe related to an elder clang version.

Yes, so to be really safe we may only allow CLang 13.x or newer.

**Comment by TurboGit** [comment]
My script failed, it change the source tree, but create_release build a tarball from git HEAD.
