### ISSUE TITLE
When using filmrolls in collections "sort descending" does nothing

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#15669]
### Describe the bug

I have my folders organized in yyyy.mm.dd and use filmrolls in the collections module. I usually used the descending option to have the newest filmroll on top. I don't know when this stopped working but the "sort descending" option just does nothing for me. 

### Steps to reproduce

- Use filmrolls in collections module
- Sort by folder name
- Select "sort descending" in the hamburger settings menu
- nothing changes

### Expected behavior

The order should inverse on activating "sort descending"

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+1216~g65ea7772f8

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux, latest updates

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD 6700 XT, ROCM 5.7.1

**Comment by FalCT60** [comment]
Sorry, I did not find this when opening mine.
The bug arose somewhere between 4.4.2 and 4.5.0.
So, I read that in issue #15671 the reason for this is that some users would not want reverse sorting for anithing else than date/time ?
I think this makes not sense at all and, moreover, this may lead to unconsistent sortings if date / time is modified in any way.
And I will add that the behaviour is buggy anyway, since when Descending is selected the oldest (in my case, as I name them upon their date) folder is displayed at he bottom of the list, just under the newest ones, until I click on the scroll bar and then the list is displayed old on top and new on bottom.
I think I am not the only one wishing to display the most recent folders on top, whatever their naming, and I do not appreciate to have to lose such a facility.
Please, give us back the possibility to reverse sorting the rolls whatever the scheme is used. Especially in cases such as mine, where the naming can be seen as date/time.
![Ascending](https://github.com/darktable-org/darktable/assets/49912948/242acc3a-d794-488b-aa4a-e3b70bf30631)
![Descending](https://github.com/darktable-org/darktable/assets/49912948/a391fc9d-9bcc-4bc2-821c-9aea49643677)

**Comment by TurboGit** [comment]
> I think this makes not sense at all

Do you have seen people asking for a dictionary (book) sorted in reverse order?

**Comment by piratenpanda** [comment]
File managers also have a-z and z-a options. I really don't understand why this simple option is not available. It's basically just reversing a list (I don't know how hard this is in dt).

**Comment by piratenpanda** [comment]
And when naming folders yyyy.mm.dd shooting name it's basically an option to have "newest on top" which is totally not weird to have for me

**Comment by TurboGit** [comment]
> And when naming folders yyyy.mm.dd shooting name it's basically an option to have "newest on top" which is totally not weird to have for me

I would argue that you can use a date/time collection.

Why you asked?

Simple if you ask for reverse order you'll get the proper order for date/time based collection (more recent first) but you'll get the Z-A sorting which is most of the time not what you want. So reversing all collections with the same preference is just wrong.

The solution, keep the sorting order of each collection independently and transparently (no option on the UI). Who want to implement that?

**Comment by piratenpanda** [comment]
> I would argue that you can use a date/time collection.

But all date/time collections like capture time or capture date destroys the folder structure I made on purpose to differentiate the shootings. Am I missing something here? Import time doesn't help either as I'd have to import 1000 folders in the proper order to make use of that

**Comment by zisoft** [comment]
@TurboGit we already had this controversial discussion in my PR #15671 

> So reversing all collections with the same preference is just wrong.

I think we still have a misunderstanding here. It is not about reversing _all_ collections, it is only about _filmrolls_ and this is exactly what can be set in the collection settings:

<img width="448" alt="Bildschirmfoto 2023-12-30 um 10 56 05" src="https://github.com/darktable-org/darktable/assets/4083281/e8d574e3-b84f-45ae-b67b-485eb5396517">

I organize my imports in a year/month folder structure so my film rolls look this:
<img width="331" alt="Bildschirmfoto 2023-12-30 um 10 51 55" src="https://github.com/darktable-org/darktable/assets/4083281/4a16763f-67e5-455c-b04f-867b678ea2e7">

and I have to scroll all the way down to reach the most recent.

With PR #15671 it looks like this and I have the newest right on top of the list:
<img width="325" alt="Bildschirmfoto 2023-12-30 um 10 55 39" src="https://github.com/darktable-org/darktable/assets/4083281/19b5ffd3-b020-47c0-bd44-d4a39b383d2c">


And the PR only works on filmroll folder names, no other collection type.

If this is really not wanted we should at least think about changing the collection settings dialog because this is simply misleading and will produce more issue reports like this one in the future.

**Comment by FalCT60** [comment]
> > I think this makes not sense at all
> 
> Do you have seen people asking for a dictionary (book) sorted in reverse order?

No, but one is still free to revert the side and start opening it from the end - what this is what becomes forbidden here.
sorting the filmrolls ascending or descending has always been possible, I don't understand why it suddenly would become not possible anymore. Nor do I understand what it implies from a dev's view, since (almost ?) all sortings can be reverse in every selector across all systems.

**Comment by FalCT60** [comment]
The screenshots show the bug I mentioned in a previous post:
Capture1 shows the display after switching from darkroom to lightable. Though the ascensor is at the bottom, the rolls are displayed from the top.
Capture2 shows the same without any action ; just inserting an usb media made the list more uncorrectly sorted: there are tenths of rolld between the last and the previous displayed rolls.
![Capture1](https://github.com/darktable-org/darktable/assets/49912948/48796525-1d12-4a8a-a3ca-212dbcce9ca0)
![Capture2](https://github.com/darktable-org/darktable/assets/49912948/b82d8457-e058-4f80-974e-70a81c03be24)

**Comment by EC1000** [comment]
Just update to 4.6.0 and encounter the same issue. I do hope that this can be improved and that https://github.com/darktable-org/darktable/pull/15671 can be considered.
