### ISSUE TITLE
A job keeps executing in the background for ~12s

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#15720]
### Describe the bug

When switching from darkroom back to lightable, a job keeps executing in the background. I tried to understand why via -d all -d verbose, but I dont get more information that rows and rows of this:

```
991.7450 [lighttable] expose took 0.0000 sec
1003.6788 [lighttable] expose took 0.0000 sec
```

I recreate it multiple times and every time is seem to last ~12s (1003 - 991)

### Steps to reproduce

1. Start darktable with -d perf or -d all 
2. Select an image and go to darkroom
3. Press l to go back to lighttable
4. notice the message repeat for ~12s

### Where did you install darktable from?

OBS

### darktable version

4.5.0~git1280.02cb5ada

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 39 KDE X11

### Describe your system?

Fedora 39 KDE, AMD 5600G, Nvidia 3060 12gb

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA 3060 12GB

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

No Lua scripts

**Comment by ptilopteri** [comment]
yes, I see it also

openSUSE Tumbleweed 20231122 | Linux 6.6.2-1-default x86_64 | 20-thr 12th Gen Intel(R) Core(TM) i7-12700 4900MHz | Load: 1.10 Tasks: 1733 | Mem: 8152/31819MB | Disk: 7217/16783GB | Gfx: @ 4480x1080

dt release-4.5.0-1277-gc426ece8f1

**Comment by pehar1** [comment]
Could reproduce with 4.5.0+1280~g02cb5adaf6, Ubuntu 22.04, seems to happen

- always when coming from darkroom
- always when coming from print view
- sometimes when coming from slideshow (about 50% of the cases)
- never when coming from map view

**Comment by jenshannoschwalm** [comment]
@dterrahe any idea about this? `expose` in views/lightroom.c ?

**Comment by ralfbrown** [comment]
Confirmed with 4.5.0+1258~g372dbabbd7, even on a folder/filmroll containing only a single image.  The expose is being called by _draw() in gtk/gtk.c, but I haven't yet been able to trace it back further since that function is a Gtk signal handler and I don't see any explicit invocations of the "draw" signal.

Could this have something to do with the new background thumbnail generation?  Although when I switch the setting from "Never" to "Small", I see thumbnail processing start before the twelve seconds of rapid-fire expose calls finishes.

**Comment by dterrahe** [comment]
Thanks @ralfbrown for the bisect. Did you look just at whether the expose message was printed or whether there was actually a difference in background processing? The PR you found I believe _only_ affects debug printing, not any actual functionality. What do you specify in -d?

A lot of expose calls isn't necessarily a problem (they likely happen at each mouse move). It is only if they trigger (more, unnecessary) background processing that we potentially have a (new) bug.

**Comment by jenshannoschwalm** [comment]
I checked with the backthumbs crawler disabled at startup and the messages still appear.

Those expose calls in lightroom view are fired also when no mouse movement is done.

**Comment by dterrahe** [comment]
> Those expose calls in lightroom view are fired also when no mouse movement is done.

They get triggered for many reasons. I'm just trying to figure out if they are triggered _more_ than "before" or just getting more reported because of the changes in debug printing.

I'm on my slow laptop, so bisecting is painful. :-)

**Comment by dterrahe** [comment]
@gi-man does it make a difference if you have "show scrollbars for central view" on or off?

**Comment by dterrahe** [comment]
> I don't see any explicit invocations of the \"draw\" signal.

FYI a "draw" will get sent at the next screen update to all widgets that were marked with `gtk_widget_queue_draw` or that were resized or otherwise dirtied.

**Comment by ralfbrown** [comment]
There is one behavioral difference between revisions that report all those expose events and those which don't - when all the events are reported, the outermost border on the thumbnail under the mouse doesn't redraw until after the events stop.  I do see events reported on mouse moves, but all my tests during bisection were with a completely motionless mouse, and the "good" commits did not show any additional expose reports on typing "l" to return to the lighttable.

**Comment by dterrahe** [comment]
Clearly I must have messed something up in that PR but I just don't spot what it is. The code is all meant to be functionally identical, except a few replacements of  `dt_get_times` with `dt_get_perf_times` which could cause breakage if `start` is used outside of `dt_show_times` or `dt_print(DT_DEBUG_PERF,`. It all looks fine to me though :-/

**Comment by gi-man** [comment]
> @gi-man does it make a difference if you have "show scrollbars for central view" on or off?

No difference. 

I'm using the keyboard to ensure no mouse movement. It is very peculiar that it is almost exactly 12 seconds.

I did notice that the same message shows up when moving the mouse thru images (Act On).

**Comment by jenshannoschwalm** [comment]
For some reason the output is triggered by `-d perf` not by `-d lighttable'. So that seems to be "something". I also checked reverting the flags like `  dt_print(DT_DEBUG_PERF | DT_DEBUG_LIGHTTABLE` with same results so it's not the order of flags.
I'm not sure atm if we are not hunting-for-nothing. @ralfbrown are you sure with your bisecting? Could we have introduced some gtk code depending on `-d perf` that does some fire-up for re-exposing?

**Comment by dterrahe** [comment]
>  that seems to be \"something\"

Definitely! I need to fine-tune (=fix) the condition in `dt_print`. Thanks for reporting!

Still doesn't explain a (new?) expose loop.

**Comment by ralfbrown** [comment]
I'm as sure about the bisecting as I can be without doing it all over again.  But I just tried `-d lightttable` and noticed something that's relevant which I had missed while being distracted with the scrolling output - on switching back to lighttable, the outer border of the selected+hovered thumbnail "breathes" for 12 seconds before snapping to its final color (it was that snap I had noticed previously, because the cycling doesn't end when the color matches the final static color).  It's fairly subtle, so I was never aware of it until just now.

I've looked in darktable.css and don't see anything that looks like an animation or transition which might be executing.

**Comment by jenshannoschwalm** [comment]
> the outer border of the selected+hovered thumbnail "breathes" for 12 seconds before snapping to its final color

I had to clean my glasses to see that too, but confirmed. Much better to see if you move the mouse away btw.

**Comment by AlicVB** [comment]
FWIW the animation has been added as a "replacement" of the old "put the last edited image as the first top-left place when returning in lighttable" which was causing misalignement and other troubles...
If it's really a needed/useful feature is a debatable point... I would vote to remove it ! (in 4.8 of course)

**Comment by jenshannoschwalm** [comment]
I would also vote for remove, eye candy almost invisible is no candy :-)

**Comment by victoryforce** [comment]
> I would also vote for remove, eye candy almost invisible is no candy :-)

My thoughts exactly.

The first time I noticed this (after a couple of years of using darktable) I was a bit confused and couldn't figure out what was going on. But after that I stopped noticing this animation again. :-)

**Comment by ralfbrown** [comment]
I'm fine with removing the animation as well, but if it is kept it should be sped up to make it more noticeable (either 2 seconds with 2 repetitions or 1 second with the existing three repetitions).
