### ISSUE TITLE
darkroom displays "working" when scrolling mouse even if fully zoomed in/out

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#15737]
Scroll to zoom out in the darkroom view. Even after the image is fully zoomed out, the "working" indicator still flashes over the image. Similarly when zooming in past the maximum zoom.

Does this mean it's trying to rerun the pipe? I suspect pipe caching means it doesn't do much but the "working" indicator suggests it's _trying_ to do something when it's not needed.

4.5.0+1294~g749a577100 on ArchLinux

**Comment by jenshannoschwalm** [comment]
I think this hast been like this for long, No? And yes, would be nice to have this not popping up

**Comment by elstoc** [comment]
No, I use 4.4.2 as a daily driver and I don't see it there, so it's an issue that has appeared in the last few months.

**Comment by elstoc** [comment]
Just running `-d perf` on master and performing a single "unnecessary" zoom out gives the following:

```
    89.8719 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    89.8758 [dev_process_image] pixel pipeline took 0.004 secs (0.002 CPU) processing `2017-09-22-15.20.31.0.cr2'
```

This pixelpipe run is not reported when I do the same in 4.4.2

**Comment by dterrahe** [comment]
> it's definitely running pipes.

Depends on what you mean by "running pipes". It may do a cache lookup, but since the image is immediately found there, nothing more.

> Which might also be related to unnecessary pipe runs.

Or not. A bisect would be helpful. I'm not being facetious; it is easy to go down the wrong rabbit hole when trying to fix a perceived issue.

The extra "working..." is somewhat annoying I agree. It is a result of all moves/scrolls/clicks that _potentially_ lead to a viewport change being centrally handled in `dt_dev_zoom_move` (rather than the logic regarding zoom levels etc being spread out all over the place). The intention was to then first do a cache lookup but that hasn't happened yet because, well, complexities.

I will do a simple compare before/after to see if anything has actually changed before requesting a screen refresh, but there's a risk that some needed updates get swallowed (maybe if zoom=fit before and after but the image size has changed or something like that). So this would need _serious_ testing so close to the release.
