### ISSUE TITLE
"only show" preset option not available in preferences dialog

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#15761]
If I create a new preset and choose "only show this preset for matching images", but I accidentally set the preset such that it never appears (e.g. I get a lens name wrong) it is impossible to remove this flag without first correcting the preset so that it is shown, or removing it entirely. This is because for some reason the dialog that appears when selecting it from preferences does not include this option:

From darkroom:
![Screenshot_2023-11-28_08-02-11](https://github.com/darktable-org/darktable/assets/9555491/7f2266b1-f27a-4d63-b525-164ff5863b7d)

From preferences:
![Screenshot_2023-11-28_08-02-40](https://github.com/darktable-org/darktable/assets/9555491/db90a27f-8e95-47fe-9d3f-9870a7132b73)

Similarly, the "reset" option is missing as well

darktable 4.5.0+1294~g749a577100 on ArchLinux

**Comment by elstoc** [comment]
Why is this an invalid bug?

**Comment by TurboGit** [comment]
As discussed in my proposed PR (closed now). There is no way to fix that, in preferences we don't have the context to update the presets. Yet having this entry in preference is nice as we can still change 80% of the presets parameters.

**Comment by elstoc** [comment]
Surely the module name is still available. If we just had a function that contained the list of iop module names and returned true if a given name was in that list, wouldn't that solve the problem?

**Comment by TurboGit** [comment]
Well I haven't found a solution because when in preference there is no IOP history. So nothing to do. That's quite simple. My first PR was using the `darktable->iop` list. It was ok only in darkroom BTW. But even if there we have a list of all IOP module and we can find a module given a name, what you get is a generic module without params only the default-params. Nobody want to create a preset using default params, this is what you get if you reset the module.

For this to work we need the history of a current dev. This is what we have when in darkroom and using the preset menu. We are linked with a module history with proper parameters & blend parameters.

So I'm pretty confident that there is no solution with how we present the presets in the preferences dialog.

> doesn't mean it isn't desirable to fix it

If I agree with that, I fail to see a proper way to fix this.

**Comment by elstoc** [comment]
> I fail to see a proper way to fix this

You can't add presets using the preferences dialog, you can only update/delete them, which means that the iop parameters will be unchanged from the existing preset record in the database.

So I would guess a possible solution would be to take a copy of the existing preset record from the database before opening the dialog, and then write a new one using the existing blobs from op_params and blendop_params plus the updated parameters from the dialog box.

That feels _possible_ (given that I could do it myself by just hand-editing the database) though whether it's the best solution is another question.

**Comment by TurboGit** [comment]
No the option "reset all module parameters to their default values" when unchecked need to have access to parameters & blending parameters of an history module.

**Comment by elstoc** [comment]
ok so we could just grey out that option?

**Comment by TurboGit** [comment]
> ok so we could just grey out that option?

If you prefer, yes.

**Comment by elstoc** [comment]
It was the "auto show" option that I was objecting to being missing, which means that it's not possible to alter presets that never show.

**Comment by TurboGit** [comment]
Ok, let me reopen and see if we can improve the GUI. This is fixes so maybe I'll still have time before the release.
