### ISSUE TITLE
When exporting an option to open the folder where it's exported at the end of the process. (FR)

### ISSUE THREAD

**Issue by ActarusLeGrand** [darktable-org/darktable#15891]
When exporting pictures, an option in that module to open the folder where it's exported at the end of the process automatically. So you save time looking where the picture is.

**Comment by ptilopteri** [comment]
when you have directed dt to place exported imates in a specific location, you  have difficulty locating those images ??? 

have been utilizing dt for ~15 years and never heard that one. 

are you on windows?

**Comment by ActarusLeGrand** [comment]
> when you have directed dt to place exported imates in a specific location, you have difficulty locating those images ???
> 
> have been utilizing dt for ~15 years and never heard that one.
> 
> are you on windows?

I do use windows.  I am trying to make  a suggestion to help the software development.  Some people should monitor those rooms, your comment is not appreciated.

**Comment by jenshannoschwalm** [comment]
> When exporting pictures, an option in that module to open the folder where it's exported at the end of the process automatically. So you save time looking where the picture is.

I don't think this is a good idea because by "open a folder" i guess you mean starting some sort of file explorer - whatever that is for the specific os. For me that would be "clobbering the desktop" so certainly to be avoided. We could add some extra button "export and open file explorer" but i would say "what for".

You might also export a bunch of files not at the same location. Open all those locations?

The chance for any of the devs being interested in implementing this seems pretty low. 

> Some people should monitor those rooms, your comment is not appreciated.

I guess you mean **this** issue tracker? For me the answer was not offensive at all - so why increasing "stress level"? For ideas like yours we would suggest "FR" for feature request in the title so we all know "Idea: feedback desired"

**Comment by victoryforce** [comment]
> I am trying to make a suggestion to help the software development.

@ActarusLeGrand  And it is very much appreciated, believe me. However, user suggestions are not always implemented, for various reasons.

In this particular case, I'm not even opposed to another checkbox in the export module interface, as I can imagine users whose workflow involves opening the export folder and viewing the exported images in an image viewer. And it's not some illogical wish, so why not.

Moreover, this idea was already proposed in the earlier issue and I once even spent some time on research and a very rough, quick-and-dirty and only partial implementation. It's been a sleepless night in the air raid shelter, so don't expect this to be a deep study of the subject, but two problems with this idea are obvious.

First, darktable supports three platforms (Linux, Windows, macOS), each of which has its own programmatical method for opening the file manager in a specific location. Therefore, this FR will require the efforts of, most likely, three developers to fully implement it.

The second (and the most important) point is that there is not always only one folder where the images are exported. The user can use substitution variables in any element of the export file path. I myself most often export in this way: the exported image is written to a folder, the path to which contains the year from Exif and one level deeper the month from Exif.

In this case, what should we open when the "open export folder" checkbox is enabled? I don't have a good answer. This is the main problem.

Perhaps you can suggest a logical behavior in such a case. Then this FR can be left open in the expectation that the developers will be able to allocate resources for implementation. Otherwise, I suggest closing the FR.

**Comment by parafin** [comment]
I suspect this is a good use-case for a lua script, and not core dt functionality.

**Comment by victoryforce** [comment]
> I suspect this is a good use-case for a lua script, and not core dt functionality.

+1, also using Lua solves the problem of an overfeatured interface: whoever needs it simply installs the Lua extension.

**Comment by ActarusLeGrand** [comment]
> > I am trying to make a suggestion to help the software development.
> 
> @ActarusLeGrand And it is very much appreciated, believe me. However, user suggestions are not always implemented, for various reasons.
> 
> In this particular case, I'm not even opposed to another checkbox in the export module interface, as I can imagine users whose workflow involves opening the export folder and viewing the exported images in an image viewer. And it's not some illogical wish, so why not.
> 
> Moreover, this idea was already proposed in the earlier issue and I once even spent some time on research and a very rough, quick-and-dirty and only partial implementation. It's been a sleepless night in the air raid shelter, so don't expect this to be a deep study of the subject, but two problems with this idea are obvious.
> 
> First, darktable supports three platforms (Linux, Windows, macOS), each of which has its own programmatical method for opening the file manager in a specific location. Therefore, this FR will require the efforts of, most likely, three developers to fully implement it.
> 
> The second (and the most important) point is that there is not always only one folder where the images are exported. The user can use substitution variables in any element of the export file path. I myself most often export in this way: the exported image is written to a folder, the path to which contains the year from Exif and one level deeper the month from Exif.
> 
> In this case, what should we open when the "open export folder" checkbox is enabled? I don't have a good answer. This is the main problem.
> 
> Perhaps you can suggest a logical behavior in such a case. Then this FR can be left open in the expectation that the developers will be able to allocate resources for implementation. Otherwise, I suggest closing the FR.

First I want to assure you that we are praying for your safety: physically, psychotically and spiritually of you and your loved one. and you martyred nation. May the guardians Angles protect you and your loved one.

Another way to implement it I was thinking, would be to export the video files to a specific folder chosen in the exporter and or in the settings. Thanks for your time to answer me, it's appreciated.

**Comment by ActarusLeGrand** [comment]
No, not as a Lua script, but build in DT.

> I suspect this is a good use-case for a lua script, and not core dt functionality.

No, not as a Lua script, but build in DT.

**Comment by jenshannoschwalm** [comment]
> No, not as a Lua script, but build in DT.

I don't think repeating this two times in a 3-liner will convince. You got some feedback and the message is like "devs are pretty reluctant to do so". That's the way the cookie crumbles ... What could **you** do?
1. accept and wait - often folks come up with ideas that won't be done by others
2. if you are really 'into it' you might leave the "have an idea" phase and start doing it yourself :-) That's how dt and other sofware dev works.

**Comment by wpferguson** [comment]
> No, not as a Lua script, but build in DT.

If you want the solution implemented in a certain way, then you should do it.  If you want a dev to do it, they will choose the implementation that works best to solve the problem.

> open the folder where it's exported at the end of the process automatically

This is a workflow, not functionality.  You want to save keystrokes and time by having darktable launch a file manager when certain events (an export) occur.  darktable is a raw processor, not an application launcher.

However, the design of darktable does allow for workflow automation using the lua scripting interface.  That's how darktable accomplishes panorama stitching (hugin), HDR (enfuse, enfuseAdvanced, hdrmerge, etc), external editing (gimp, etc), post export sharpening, etc.

**Comment by TurboGit** [comment]
> No, not as a Lua script, but build in DT.

But that's the solution.
