### ISSUE TITLE
Closing DT does not unlock the DB

### ISSUE THREAD

**Issue by DanKrabach** [darktable-org/darktable#16023]
### Describe the bug

After closing DT, the DB lock files `data.db.lock` and `library.db.lock` are not deleted.  When one restarts the app, error is thrown, DT creates error file and 

### Steps to reproduce

1. Start DT
2. Close out DT
3. Restart DT

### Expected behavior

Release the db locks and delete the lock files

### Logfile | Screenshot | Screencast

[darktable_bt_4F29G2.txt](https://github.com/darktable-org/darktable/files/13825203/darktable_bt_4F29G2.txt)
[darktable-log.txt](https://github.com/darktable-org/darktable/files/13825210/darktable-log.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Describe your system?

Processor	AMD Ryzen 9 6900HS with Radeon Graphics           3.30 GHz
Installed RAM	16.0 GB (15.2 GB usable)

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX6700S GDDR6 @ 8GB Driver Version 31.0.22023.1014

**Comment by ralfbrown** [comment]
How long did you wait before the restart?  darktable does some database maintenance on shutdown, after it closes its window.  This can take a minute or two with larger databases.

**Comment by gi-man** [comment]
And don't use the `unrestricted` memory setting. It is going to try to use more memory than it has available along with your iGPU also trying to use that memory.

**Comment by DanKrabach** [comment]
@ralfbrown  --As for time between, i had appointment so it was hours between ending the app and restarting. And my library is only around 100 picts.

@gi-man -- Thanks for tip. Likely changed by accident.

**Comment by victoryforce** [comment]
@DanKrabach 
This issue actually reports two problems:
- database lock files remained undeleted after closing the program.
- with existing lock files, the attempt to launch the program ends with a crash instead of a normal launch with a suggestion to delete the lock files.

The direct cause of the program crashing when trying to run with existing lock files is a bug that PR #16070 fixes. Accepting the above PR closed this issue, and I ask you to re-check if the first problem persists with the [next Windows nightly](https://github.com/darktable-org/darktable/releases/tag/nightly) that will contain this fix.
