### ISSUE TITLE
tone equalizer: graph and widget lose data when navigating history

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#16227]
darktable 4.7.0+433~ga7852b83f6 on ArchLinux

When navigating back through the history, the graph and mouse-pointer-widget no longer function correctly. 

Steps to reproduce:

1. Reset history on an image
2. Activate the tone equalizer (equalizer appears at top of history stack)
3. Click any history entry prior to the tone equalizer (graph disappears, widget displays "? EV")
4. Click back on the top of the stack (graph still does not appear, widget continues to display "? EV")

Once the tone equalizer ui has entered this state, no amount of collapsing/expanding/disabling/enabling/resetting will persuade it to start working again. The only way to get it working again is to exit the darkroom view and go back in again

Same issue encountered on 4.6.x branch both with and without OpenCL enabled

**Comment by ralfbrown** [comment]
Confirmed (exact same version), although I initially thought I was not reproducing it because the graph widget was still displaying the selected adjustments.  What disappears is the histogram in the background of the graph.  You can also get it back by nudging the exposure/contrast compensation sliders or any point on the graph, just as you need to do when first activating it.  So moving through the history clearly causes the module to lose its histogram information.

**Comment by jenshannoschwalm** [comment]
It's a pixelpipe "thing". If you are doing as described you will have data from later modules still in cache so the tone equalizer is not processed and thus does not know it should update the internals.

**Comment by ralfbrown** [comment]
I can take a look, but probably not until early March.  My guess is that this will require a mechanism for having modules reinitialize their internal data even when they are skipped due to their output being cached already.

**Comment by jenshannoschwalm** [comment]
We have had such a problem for internal histograms too. Will have a look.

**Comment by elstoc** [comment]
Fixed in #16266
