### ISSUE TITLE
darktable crashes after some time

### ISSUE THREAD

**Issue by realex64** [darktable-org/darktable#16250]
### Describe the bug

Darktable is crashing when i use the software. There is no hard work for cpu, i just click through my thumbnails pictures.
My system freezes completely. This happens all the time, sometimes sooner, sometimes later, but always within a few minutes (< 10).

This is what i did:

- One eye on taskmanager: the needed RAM grows over time, but never reach a significant consumption. The system freezes before
- CPU is in normal (low) area, no special values, until the system freeze
- i started with `darktable -d common >2&1 | tee mylogfile.log`, but i can see no lines which tell me about the problem

My system is Ubuntu 22.04.3 LTS, fully up to date. 
Darktable is: 4.6.0-1.1+72.1

Any help is very appreciated!

Kind regards

Alex

### Steps to reproduce

Choosing a folder with pictures
clicking throug the thumbnails in lighttable
or clicking through the timeline in darktable

### Logfile | Screenshot | Screencast

[darktable_debug.log](https://github.com/darktable-org/darktable/files/14168088/darktable_debug.log)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0-1.1+72.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3 

### Describe your system?

16 GB RAM
Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz / 8 Cores
 libgtk-3-0:amd64           3.24.33-1ubuntu2 amd64 
loginctl show-session c2 -p Type
Type=x11
  DEVICE:                   0: 'Quadro M2000M'
   PLATFORM, VENDOR & ID:    NVIDIA CUDA, NVIDIA Corporation, ID=4318
   CANONICAL NAME:           nvidiacudaquadrom2000m
   DRIVER VERSION:           525.147.05
   DEVICE VERSION:           OpenCL 3.0 CUDA, SM_20 SUPPORT

### Are you using OpenCL GPU in darktable?

Yes

**Comment by ralfbrown** [comment]
If you've set "darktable resources" on the "processing" tab of the global preferences to "unrestricted", set it to something else.

The fact that it takes multiple minutes to switch to a console is indicative of a massive jump in memory use swapping everything else out of RAM (including much of the operating system itself).  How many megapixels in the images you are working with when the problem occurs?  Are you using `diffuse and sharpen`, `filmicrgb` with highlight reconstruction enabled, `contrast equalizer`, `retouch` with wavelet decomposition enabled, or `astrophoto denoise` with low thresholds?  (all of those have high memory requirements)

"unrestricted" has been removed from master because it causes just this kind of problems.

**Comment by realex64** [comment]
> If you've set "darktable resources" on the "processing" tab of the global preferences to "unrestricted", set it to something else.

The configuration is "Standard".

The images are 4.592 x 3.448. 

I do no image manipulation so far. darktable crashes before.

Thank you for your tips.

Kind regards
Alex

**Comment by realex64** [comment]
OK, this is not the solution but one more hint: There is no error, when i use the laptop with no or one external monitor. With two monitors, the error is back.

I don't know, who is to blame: darktable, graphic-card, driver... 

For working with darktable i leave one monitor unplugged... so far this is a "solution" for me.

Kind regards

Alex
