### ISSUE TITLE
Purple instead of white on canon CR2 files

### ISSUE THREAD

**Issue by Aviator7559** [darktable-org/darktable#16268]
### Describe the bug

on an image with lots of white are (RGB 255 255 255)when the raw black/white point slider is dragged wayyy to the right, darktable renders the area as a magenta/purple color instead of white. this is also rendered as magenta on export. sidebar: it reminds me of the "black hole sun" glitch on Blackmagic cameras a while back

### Steps to reproduce

when the raw black/white point slider is dragged wayyy to the right, the white areas become magenta instead of staying white

### Expected behavior

keep the white areas white

### Logfile | Screenshot | Screencast

sorry, googled it & cant figure out where to find the log file :(

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Describe your system?

AMD 6900XT GPU

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD 6900XT 16GB windows driver version 31.0.23013.1023

**Comment by Aviator7559** [comment]
![_MG_6217](https://github.com/darktable-org/darktable/assets/146677160/34424a41-8b4e-4499-a4b2-65fb418303ba)
couldnt upload the raw file b/c it's more than 25MB, but heres a jpeg export showing the issue

**Comment by MStraeten** [comment]
works as designed: By shifting the whitepoint in raw black/whitepoint to the right you prohibit exclusion of clipped highlights. Those areas are then handled as valid raw values - so they won’t be white after applying the coefficients in white balance. 
since most sensors are more sensitive to green initial white balance usually corrects this resulting in those magenta areas in clipped highlights.
