### ISSUE TITLE
Requested Support: Pentax Q-S1 Camera

### ISSUE THREAD

**Issue by Lobalobo** [darktable-org/darktable#16281]
Request for support of Pentax Q-S1 Camera.

Just submitted a DNG file (the camera's only RAW format) to https://raw.pixls.us/ . Image was taken with Pentax Q Standard 01 Prime Lens: 8.5 mm f/1.9 Maximum Aperture.

Happy to submit other images (including from other lenses) if needed.

**Comment by kmilos** [comment]
Already done in https://github.com/darktable-org/rawspeed/pull/651 😉 

Thanks for the sample!

**Comment by kmilos** [comment]
@LebedevRI Is the sample verified, can we close this?

**Comment by LebedevRI** [comment]
I'm being a bit of a barrier chief (idiom not translatable) with DNG samples i'm afraid.
I have neither verified that, or many other DNG samples, nor deleted them,
because i'm afraid of RPU disk size footprint growth, without meaningful effect on coverage.
Unless we know the DNG is somehow special, they are more or less all good to use...

**Comment by kmilos** [comment]
Ok, makes sense, thanks for the explanation.

I don't expect any format weirdness for this model indeed.

**Comment by LebedevRI** [comment]
Yes, as i said, there is just no good solution.
We need the sample, but we have to be mindful of the amount of samples, too.
It sucks.
