### ISSUE TITLE
RGB Parade doesn't show same data as waveform

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#16332]
### Describe the bug

rgb parade doesn't show same data as waveform:
 
![image](https://github.com/darktable-org/darktable/assets/39386816/6698f63e-afb2-436f-9506-3f25f7e9de1d)

### Steps to reproduce

1. desaturate parts of an image
2. see the result in rgb parade and waveform

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+593~g455b9f599f

### What OS are you using?

windows 10

### Are you using OpenCL GPU in darktable?

Yes

**Comment by Jiyone** [comment]
I'm curious, what's wrong exactly in those scopes ? To me they are normally showing what they must show 🤷‍♂️

**Comment by MStraeten** [comment]
One displays the b/w and colored patches the other ignores the monochrome processing. Did you really compare the output of waveform and parade ?

**Comment by Donatzsky** [comment]
Seems to work fine to me.
The parade specifically shows each channel separately. And since each pixel is still defined as RGB values, it of course shows just that. Also, I don't think the histogram module has any particular notion of monochrome - it just shows the pixel values as they happen to be.

![image](https://github.com/darktable-org/darktable/assets/4938390/406fd2e9-3156-4b69-bcdb-4fe437bd86cc)

**Comment by elstoc** [comment]
I agree this looks correct to me. Monochrome pixels have R=G=B and therefore show white on the combined view (because equal R+G+B = white/grey) with the exception of the coloured pixels. The parade view correctly decomposes the monochrome pixels into their component colours.
