### ISSUE TITLE
Same folder is split into multiple locations in folders collections

### ISSUE THREAD

**Issue by odattner** [darktable-org/darktable#16536]
### Describe the bug

All my photos are under D:\Photos\yyyy\some_name. But, when viewing "collections|folders", the D:\photos top folder is split over multiple top trees. See attached picture. All the "2023" subfolders are actually the same folder on the hard disk. 
![darktable_rCA0XgNNvB](https://github.com/darktable-org/darktable/assets/165377158/6c134c63-e4e7-447b-9811-8effebb02fd4)

### Steps to reproduce

Selecting folders in the collections always brings up a list of "photos" top folders.
Most years are under the first one.
Year 2023 is split between about 7 top folders.
Year 2024 is in the last (for now) top folder.

### Expected behavior

Darktable should have all these under one top tree.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 home

### Describe your system?

I have a mini pc with three hard drives: c, d, and e.
c is the system hd.
d is internal and mainly for photos
e is an external usb backup

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I think I had the same problem in my previous version (4.2 or something close)

**Comment by ralfbrown** [comment]
Under Linux and Mac, "Photos/X", "photos/X", and "photos/x" are three distinct paths, but under Windows, they all refer to the exact same path.  My guess is that you've somehow added pictures at different times using different capitalizations.  You can fix this by right-clicking on the tops of the duplicated subtrees and selecting "search filmroll/folder", then entering the path to each using the same capitalization.

It may be worth normalizing paths on Windows, but then you wouldn't be able to share a library on a dual-boot system since the Linux side wouldn't be able to find any files that had capitalization changed....

**Comment by odattner** [comment]
Hi,
Thanks for the reply. 
Seems to have solved the problem.
