### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by sr66139p** [darktable-org/darktable#16558]
**Is your feature request related to a problem? Please describe.**
Because it's unverified, people who find darktable through Flathub won't know it's official.

**Describe the solution you'd like**
You can verify the app by adding a token to the website or verifying through GitHub

**Alternatives**
You could contact Flathub for manual verification

**Additional context**
Here's a link to Flathub's verification documentation for developers https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by victoryforce** [comment]
> Because it's unverified, people who find darktable through Flathub won't know it's official.

@sr66139p It's not official. We don't control these builds.

**Comment by victoryforce** [comment]
I'm tagging @paperdigits just in case, maybe I'm misunderstanding something about flathub verification. But if we are talking about whether the flathub package build is controlled by the same organization/team as the original program, then no, it's not. That is, the flathub build is unofficial. Accordingly, I will close the issue.

**Comment by paperdigits** [comment]
I've contributed to the flatpak and I try and keep an eye on what is there, but it is not official.

**Comment by root-hal9000** [comment]
@paperdigits @victoryforce I am honestly just about to install Darktable for the first time, but came here to open an issue just to let you know that the flathub URL on your website is broken - the www subdomain leads to an error page and has an invalid certificate - so  [https://WWW.flathub.org/apps/details/org.darktable.Darktable](https://www.flathub.org/apps/details/org.darktable.Darktable) is no good, but [https://flathub.org/apps/details/org.darktable.Darktable](https://flathub.org/apps/details/org.darktable.Darktable) works.

Anyway, I see now from searching and seeing this issue that it's not your official build, but since it's a link on your website's installation page, I thought I should let you know (I thought Flathub was down for a second haha)

![image](https://github.com/user-attachments/assets/517feb58-938e-48fc-ab15-e5ce5ce75ea4)

**Comment by paperdigits** [comment]
Thanks for the note. This needs to be filed against the website repo, dtorg.

**Comment by paperdigits** [comment]
I dunno it forwards to a page without the www for me.
