### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by odattner** [darktable-org/darktable#16582]
### Describe the bug

I had darktable (or the computer) crash on me while it was working on something and the database was corrupter.
I replaced it by deleting the data and library files and replacing them with snapshots from a couple of days ago. 
It worked insofar as the program opened with no error but there were no photos in the library.
I tried importing them back in. 
If I import a single folder, it works OK.
But since I have about a hundred, I wanted to save time and import the top folder so I check "recursive directory" and waited for it to populate the list of all XX thousand files. However - it gave me an error on importing anything other than the single picture in the top folder. I recreated it with subfolder. It would only import whatever was in the top subfolder and not import anything below that.

### Steps to reproduce

1. Go to Import > Add to library
2. Select "recursive directory"
3. Select a folder with subfolders as part of it
![darktable_ygCxuBa7ik](https://github.com/darktable-org/darktable/assets/165377158/2e2e9637-0d0e-4f26-948f-52e9fb79e498)
4. Click "add to library"
5. Only photos in the top folder are imported (in this case 2210/2256).
![darktable_17NHcVJAcM](https://github.com/darktable-org/darktable/assets/165377158/b3552a5d-46bf-4e94-a54e-08635e8007fa)

### Expected behavior

Darktable should inport all marked files

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 home

### Describe your system?

Win 11 home with two internal drives.
The photos are all on drive d (separate from the system files and documents folders on drive c).

### Are you using OpenCL GPU in darktable?

None

**Comment by odattner** [comment]
Managed to restore from snapshot so this issue is no longer an acute problem for me.

**Comment by jenshannoschwalm** [comment]
Import in recursive mode had a severe bug in 4.6

Just upgrade to 4.6.1 :-)

**Comment by karlpacchio** [comment]
I recently installed Darktable 4.6.1 (from the official site) on my 64-bit Windows 11 (Home edition) laptop. An issue I am encountering is that whenever I dropdown 'import', click 'add to library', select the image (which is in nef format), and finally click 'add to library' on the bottom-right of the 'add to library' dialog box, the Darktable application closes.

How do I go about resolving this error/bug?

![Screenshot 2024-04-24 150630](https://github.com/darktable-org/darktable/assets/168044203/c8915270-7acc-48c3-afa2-a1608058e026)

**Comment by victoryforce** [comment]
> How do I go about resolving this error/bug?

You wrote in an issue that describes a completely different problem, and it is already closed.

You should open a new issue with the following information:

- Check if there will be crashes when importing into an empty new database. If not, the problem is that your current database has been corrupted. To do this, you can temporarily rename the `darktable` folder in the `%LOCALAPPDATA%` folder so that a new one with an empty database is created when the program is launched. Or, if you can handle the command line, run darktable with the --configdir option, specifying any directory for the temporary database (it will be created).

- If the program crashes even when importing into an empty database, the reason may be in the image itself. Does it happen on a specific image or a subset of your images, a specific image format (check on images from another camera), all images? If the problem is with a specific image(s), please add it to the bug report.
