### ISSUE TITLE
Possible Lua upgrade issue

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#16812]
After last Lua changes I had not "script manager" showing up in the UI. I then decided to look at what was wrong this morning, using debug Lua trace I got:
 
`     2,5172 LUA ERROR : .../obry/.config/darktable-dev/lua/tools/script_manager.lua:63: attempt to index a function value (local 'gettext')`

To fix that I had to manually do:

```
$ cd ~/.config/darktable-dev/lua
$ git pull
```

Wondering if this upgrade bootstrap won't affect some other users.

**Comment by wpferguson** [comment]
Fixed by https://github.com/darktable-org/lua-scripts/pull/465.

I added gettext.binddomain back in and added the metadata block.  I tested all the scripts to make sure everything was ok, but I was using the new version of script_manager to test it with, so I didn't test the old version of script_manager.    It got reported on pixls.us and I fixed it then.  However, this did remind me to backport it to the API-9.2.0 branch, so that's taken care of too.
