### ISSUE TITLE
appImage: "/tmp/.mount_DarktaTmcr11/AppRun.wrapped: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [darktable-org/darktable#16871]
I have 4.6.0 from Gentoo repo that works, but not the appImage.

$ ./Darktable-4.7.0+1290.gc88724fea2-x86_64.AppImage 
/tmp/.mount_DarktaTmcr11/AppRun.wrapped: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

**Comment by victoryforce** [comment]
Please read https://discourse.appimage.org/t/how-do-distros-add-support-for-running-appimages/1648/9

**Comment by AxelG-DE** [comment]
I do run gentoo, but I have actually no idea what appimage even is, but seeing your error, I just asked google...
https://www.google.com/search?client=firefox-b-d&q=+libthai.so.0

**Comment by victoryforce** [comment]
@vitaly-zdanevich I see from your profile that you are a Gentoo contributor. Could you add the libthai package to the official Gentoo repo? This could make Gentoo compatible with AppImage.

**Comment by vitaly-zdanevich** [comment]
I can, but the point of AppImage is to have dependencies inside?

**Comment by vitaly-zdanevich** [comment]
> Could you add the libthai package to the official Gentoo repo?

This? https://github.com/tlwg/libthai

**Comment by vitaly-zdanevich** [comment]
But how Darktable from the Gentoo repo works without this library?

**Comment by victoryforce** [comment]
> I can, but the point of AppImage is to have dependencies inside?

No, if you mean ALL dependencies. Otherwise, each image would have to contain absolutely all base libraries up to and including glibc. In fact, appimage relies on a certain set of core libraries and packages everything else privately.

Due to the nature of Gentoo, appimage cannot be guaranteed to work on every user system. The user, for example, can make a kernel without FUSE support, and then no program in the appimage format will work.

> This? https://github.com/tlwg/libthai

Yes.

> But how Darktable from the Gentoo repo works without this library?

Because this library is not a _direct_ dependency of darktable, i.e. it is not required for darktable to work.

darktable AppImage is built in Ubuntu environment. Ubuntu has libthai and this library gets into transitive dependencies. However, libthai is included in the excludelist of the standard library deployment toolkit in appimage. That is, appimage relies on libthai to be provided by the host system.

**Comment by vitaly-zdanevich** [comment]
> libthai is included in the excludelist of the standard library deployment toolkit in appimage

Hm, so it means that it is impossible to include that lib to the AppImage?

**Comment by victoryforce** [comment]
> Hm, so it means that it is impossible to include that lib to the AppImage?

You can manually put anything you want into the appimage.  But the standard toolkit contains a blocklist:
https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist

See also https://github.com/AppImageCommunity/pkg2appimage/issues/538#issuecomment-1650971090

**Comment by vitaly-zdanevich** [comment]
> @vitaly-zdanevich I see from your profile that you are a Gentoo contributor. Could you add the libthai package to the official Gentoo repo? This could make Gentoo compatible with AppImage.

I found that it already exists in Guru overlay https://data.gpo.zugaina.org/guru/dev-libs/libthai/

I created issue to add to the main tree https://bugs.gentoo.org/933097

**Comment by ralfbrown** [comment]
Closing as this is something which needs to be addressed in Gentoo.
