### ISSUE TITLE
Enhancement: Filter for images with no tag attached

### ISSUE THREAD

**Issue by pozix604** [darktable-org/darktable#17130]
I want to search for images that have no tag attached.

My workflow as follows:

 1. Triage images
 2. Tag images with appropriate category
 3. Look at images not yet tagged and continue until done

I cannot do this because I cannot filter for images that have no tag attached.

**Describe the solution you'd like**
In collection filters, perhaps a tag-specific section that allows for more than just a text match.

**Comment by ralfbrown** [comment]
Are you having difficulties with the "not tagged" option when using the "tag" criterion in the collections module?  That should give you what you want when combined as a "narrow down search" rule with some other selection criterion such as filmroll.

All collections in darktable are what that other program calls a smart collection, so as soon as you tag an image while using such a collection rule, it will disappear from the lighttable since it is no longer untagged.

**Comment by ralfbrown** [comment]
No response from OP in over two months to either of the two existing ways which were suggested.
