### ISSUE TITLE
rotation and perspective" module not compatible with "retouching".

### ISSUE THREAD

**Issue by cjose38** [darktable-org/darktable#17297]
### Describe the bug

when using "rotation and perspective" with the "original framing" option, areas outside the selection are no longer available to the "retouch" module when the module is closed.
screenshots and attached image + xmp file.
if the "automatic cropping" option is deactivated, it works correctly.
![Capture1](https://github.com/user-attachments/assets/c4ee1ee6-5007-46ff-b9a1-e47eb1acbb72)
![Capture2](https://github.com/user-attachments/assets/02a0013b-b61f-4dbe-a753-b737b4a8383c)

### Steps to reproduce

use the file with its xmp as a zip file.
activate and deactivate the "rotation and perspective" module with and without the automatic cropping option.

### Expected behavior

DT should have the same result with and without the "auto crop" option.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

w10 pro

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA geforce RTX 3060 12 gb

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

[rawxmp.zip](https://github.com/user-attachments/files/16560810/rawxmp.zip)

**Comment by ralfbrown** [comment]
That's expected behavior when r&p is before retouch in the pipeline - the cropped-away data doesn't get sent down the pipeline, so retouch can't see it.  That's why the crop module comes after r&p by default, so that the data it crops away **is** available to retouch.

If you need some of the cropped-away area as source material in retouch, you can either turn off automatic cropping and manually crop, or use Ctrl-Shift-Drag to move r&p above retouch.

**Comment by ralfbrown** [comment]
Hmm, interesting.  Can reproduce, but you can move retouch down.  That puts it before orientation, which might not be desirable, in which case you can achieve the desired result by moving r&p to just below retouch and then moving retouch down.

There are some "fences" preventing modules from being moved to places where they can't work, e.g. most modules before demosaic can't move after because there are different kinds of data in the pipe before/after demosaic.  Presumably the one for retouch needs adjusting.

**Comment by pehar1** [comment]
> you can achieve the desired result by moving r&p to just below retouch and then moving retouch down.

If I correctly understand you then have :

- ...
- exposure
- rotate and perspective
- retouch
- orientation
- chromatic abberations
- ...

but this will no longer work if you change a parameter in "_orientation_". The longer I think about it, the more I come to the conclusion that there is no "correct" module order in this case. The "cleanest" solution is to turn off automatic cropping in "_rotate and perspective_" and cropping with "_crop_" module, leaving the module order at default for RAW input.

**Comment by ralfbrown** [comment]
No further followup in four months, so the mentioned workaround seems to have been satisfactory.
