### ISSUE TITLE
HelloGitHub Badge

### ISSUE THREAD

**Issue by 521xueweihan** [darktable-org/darktable#17315]
<img width="783" alt="image" src="https://github.com/user-attachments/assets/6f15dd41-82d6-4d49-96f5-b18c513e31c1">

🎉 Congratulations! Your [project](https://hellogithub.com/en/repository/7a0c25b4a3714592acff2ed9a855550c) has been featured and recommended by the HelloGitHub community. We invite you to join the HelloGitHub Badge Program. Joining will grant you the following privileges:

- **Community Recognition**: The badge indicates that your project has successfully passed the HelloGitHub community's stringent selection and recommendation process.
- **Increased Exposure**: Displaying the badge will draw more traffic to your project, attracting additional users and contributors.
- **Enhanced Interaction**: Users can quickly understand your project through the badge and engage with it (like, comment, bookmark).
- **Feedback Collection**: Gather genuine feedback from a broad user base, aiding in the continuous improvement of your project.
- **Special Identification**: Once verified, your comments will feature a distinctive mark and be prioritized for pinning.

📌 [Click here](https://hellogithub.com/en/repository/7a0c25b4a3714592acff2ed9a855550c/embed) to wear the badge and join the HelloGitHub Badge Program, allowing your open-source project to shine even brighter.

**Comment by victoryforce** [comment]
> * **Increased Exposure**: Displaying the badge will draw more traffic to your project, attracting additional users and contributors.

Dear @521xueweihan, 

Thank you for choosing us along with several thousands other projects on github for the initial content of your catalog! It is a great honor for us. I sincerely wish you success.

But after reading this marketing text, I was wondering if you could somehow logically explain how this badge can bring some benefits to us, rather than free advertising to you.

> 📌 [Click here](https://hellogithub.com/en/repository/7a0c25b4a3714592acff2ed9a855550c/embed) to wear the badge and join the HelloGitHub Badge Program, allowing your open-source project to shine even brighter.

P.S. Since we are photographic people, could you specify what brightness we can achieve when we will "shine even brighter" thanks to this badge.

**Comment by 521xueweihan** [comment]
@victoryforce Thank you for your reply.

If this message has caused you any distress, I sincerely apologize. However, this is not a mass marketing message but a choice I have made after careful consideration.

The [HelloGitHub](https://github.com/521xueweihan/HelloGitHub) open source project, which I have been continuously maintaining for 9 years, has allowed me to deeply understand the difficulties of building an open source project from scratch. Therefore, I hope to contribute to the darktable open source project, to help more people become aware of and fond of it, which is why I am willing to promote it.

At present, the HelloGitHub open source project has 80k stars, the website has a monthly PV of 400k, and there are 500k fans across the network. It is a pity that HelloGitHub has been spreading only in China before. Recently, I have just translated the website and content into English, preparing to let friends from abroad know what HelloGitHub has been doing.

Wearing the HelloGitHub badge first represents that you recognize HelloGitHub's promotion of the darktable project as a contribution rather than a traffic grab.

Next, let's talk about the benefits it will bring to darktable and the privileges you will enjoy:

1. When searching on the HelloGitHub website, it will have a recommended tag.
2. The recommended projects on the right side of the website will randomly feature darktable.
3. You can continuously collect user comments and ratings for darktable.
4. After claiming, your comments and replies to netizens will have the OP tag.
5. Carefully written Chinese introductions and project descriptions.
6. (In development) You will be able to post tasks related to darktable on HelloGitHub.

**Comment by victoryforce** [comment]
@521xueweihan Thank you, you are doing a great job and I am glad that your site has gained popularity in China. This always happens when you work hard on something. Catalogs and pages like "awesome lists" on GitHub usually get a lot of attention.

I absolutely did not understand why you are talking about some distress(?) that I should be experiencing, but maybe it is due to cultural differences.

I did not claim that your offer is a mass(!) marketing message. But it is marketing in its essence, I think there is no point in denying it. You want to "sell" us something, some benefit from advertising your catalog with a badge.

If you are interested, I can explain what the darktable project really needs and why none of the "benefits" you described will help us. If not, I won't waste your time.

P.S. By the way, it would be nice to have a translated darktable user guide for Chinese users. Unfortunately, among the huge number of Chinese speakers, there are still no translators who would complete this task.

**Comment by 521xueweihan** [comment]
@victoryforce I would like to hear more
