### ISSUE TITLE
Add other jpeg encoders like jpegli or mozjpeg

### ISSUE THREAD

**Issue by Today20092** [darktable-org/darktable#17544]
**Is your feature request related to a problem? Please describe.**

We should be able so specific what JPEG encoder to use.

**Describe the solution you'd like**

An option when exporting jpegs to be able choose the encoder.

**Alternatives**

None for this feature. Or just fully switch to jpegli for better compression efficiency.

**Additional context**

**Comment by victoryforce** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> We should be able so specific what JPEG encoder to use.
> 
> **Describe the solution you'd like**
> 
> An option when exporting jpegs to be able choose the encoder.

This is not a good solution:
- If jpegli is clearly better than libjpeg-turbo, then why build with both and give a choice?
- The user is not required to know any JPEG encoders and their characteristics and forcing the user to choose is a bad idea.

> **Alternatives**
> 
> None for this feature. Or just fully switch to jpegli for better compression efficiency.

As soon as jpegli gets at least the first stable release, will have production quality and will be available in distributions. Before that, there is no point in talking about it as an existing library.

Because of the above, I see no point in keeping this issue open. When the time comes, of course darktable will switch to the best encoder available on supported platforms.
