### ISSUE TITLE
My connected MIDI devices sends unassigned commands

### ISSUE THREAD

**Issue by johansmolinski** [darktable-org/darktable#17971]
### Describe the bug

This may be a bug, an unwanted feature or me not understanding how to deal with it. Anyway...

I have quite a bunch of connected MIDI controllers to my computer, as I use it for music production. I have no intention to use them with darktable. Some of them, including my wind controller, sends MIDI traffic all the time, which darktable seems to react to. I really need a way to disable MIDI input alltogether in darktable.

### Steps to reproduce

1. Connect a ton of chatty MIDI equipment to the computer
2. Start darktable
3. Look for messages like "2: G9 (127) not assigned" and note that the UI is very unresponsive
4. Also, if moving the mouse, it seems to add to the message, like "2: G9 (127), horisontal not assigned" (and the same but vertical if moving the mouse up and down).

### Expected behavior

Work smoothly without any MIDI related messages, as without the controllers connected

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Mac

### What is the version of your OS?

macOS Sonoma 14.4.1

### Describe your system?

Apple M1 Pro Max, 64 GB RAM

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by ralfbrown** [comment]
There's a compilation option to omit the MIDI support, but AFAIK there is no commandline switch or config option to disable MIDI.

The reason you are seeing extended messages when moving the mouse is because the darktable shortcut system allows you to combine a mouse move or scroll action with any held keystroke (and MIDI "note" commands are treated as keystrokes).  For example, I have my copy configured to adjust filmicrgb's white level by making a vertical mouse move while holding 'f' and the black level by moving horizontally while holding 'f'.

**Comment by jenshannoschwalm** [comment]
See https://darktable-org.github.io/dtdocs/en/special-topics/midi-device-support/ :-)

`-d input` would be the option

**Comment by MStraeten** [comment]
add a - in preferences > miscellaneous > interface > order or exclude midi devices to suppress all midi input

**Comment by jenshannoschwalm** [comment]
Closed as covered in manual, link above
