### ISSUE TITLE
Clicking on a utility module expands it, even when dragging

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#17973]
If I try to click+drag a collapsed utility module, the module expands before I can start dragging, making it harder to reposition. Ideally the header "on click" functionality should only function when the mouse button is released, and not after a drag operation has been completed.

darktable master 7c8ca813606

**Comment by dterrahe** [comment]
Hold shift+ctrl while clicking to avoid expanding.

**Comment by elstoc** [comment]
I'm not sure anyone will discover that if drag just works. Maybe we should require ctrl+shift in order to drag, so it's the same as for processing modules

**Comment by dterrahe** [comment]
processing modules no longer require ctrl+shift to start a drag either.

Connecting `_iop_plugin_header_button_press` and `_lib_plugin_header_button_press` to `"button-release-event"` instead of `"button-press-event"` seems to work well; if a drag is started, the button release event isn't delivered anymore. At the cost of a small decline in responsiveness.

Also partly solves #17889 for the case where the preset menu is called up by right-clicking anywhere else in the header (not on the preset button).

**Comment by elstoc** [comment]
> processing modules no longer require ctrl+shift to start a drag either.

I'm all for convenience but I'm not sure this is a good thing. IIRC one of the reasons for requiring Ctrl+Shift to drag iop modules was to be sure that it was a conscious choice and could not be done accidentally (since it actually changes the processing). If you expose a simple click+drag operation more people will foot-shoot without understanding the consequences.

**Comment by dterrahe** [comment]
An alternative approach could be to display a confirmation dialog with an explanation the first time a user performs a d&d.

**Comment by elstoc** [comment]
I think I'd still be a little worried about doing it accidentally. I'm one of those people who clicks stuff when I'm bored :)

**Comment by dterrahe** [comment]
<img width="136" alt="image" src="https://github.com/user-attachments/assets/73b167c2-ec1b-4160-95a3-561b41f74137">

**Comment by elstoc** [comment]
I'm sure you're making a really good point, but I don't get it

**Comment by elstoc** [comment]
In fact, because I have darktable modules automatically expand and scroll into view when I click them, it's really very easy to activate the drag ui accidentally

**Comment by dterrahe** [comment]
> I'm sure you're making a really good point, but I don't get it

No worries. The point I was unsuccessfully trying to make, was that if you want to protect people from accidental footshootery, then an option in the menu of a visible button is even more inviting/"discoverable" than drag&drop. So maybe we should hide/deactivate "move up"/"move down" in the instance button menu unless the button is clicked while holding ctrl+shift?

> Again, though, probably mitigated if the expansion is on mouse up

Have you tried the suggestion I made a few comments back? I doubt Pascal would still consider it for inclusion in 5.0 (I would definitely not suggest he did), but if you feel strongly enough about the regression and did sufficient testing to prove that this actually helps...

> connecting _iop_plugin_header_button_press and _lib_plugin_header_button_press to "button-release-event" instead of "button-press-event"

**Comment by elstoc** [comment]
> an option in the menu of a visible button is even more inviting/"discoverable" than drag&drop

I would argue it's quite laborious to use and much harder to click accidentally. I don't know, it feels less like a "ui only" thing when it's in that menu :shrug: 

> Have you tried the suggestion I made a few comments back?

No. Honestly it's so long since I've done any coding in darktable, I'm reluctant to even look at making changes at the moment. My head's in TypeScript these days.

**Comment by dterrahe** [comment]
You suggested there were two separate reasons for requiring ctrl+shift to d&d modules:
- to prevent accidental dragging (which might be less frequent or surreptitious if the module doesn't expand until mouse release)
- to prevent intentional dragging where the user doesn't understand the consequences. Presumably having to find the magic ctrl+shift combination in the manual means they'll also be exposed to the warnings therein. My point is that no safeguard like that exists when using the instance popup menu. Yes, the user might find it more laborious to shoot themself in the foot, but I doubt that will stop them. A popup with explanation could help at least a little here too, but as you may gather, this is not a target audience I feel particularly strongly about.

> I'm reluctant to even look at making changes at the moment.

If searching for two words and replacing `press` with `release` is too much effort, then we've also answered the question how much you care about the regression. There's no reason for me to care more than that.

**Comment by elstoc** [comment]
If you accept my PR to only perform module header actions on button release then we can allow a slightly less complex modifier like Ctrl. IIRC the _other_ reason we used Ctrl+Shift was that the other modifiers were all taken

**Comment by elstoc** [comment]
I raised https://github.com/darktable-org/darktable/issues/17982 to continue the discussion about whether we should use a modifier for drag-and-drop
