### ISSUE TITLE
LUA: using darktable.database.move_image() does not force a refresh of the new thumbtable 

### ISSUE THREAD

**Issue by dedenholm** [darktable-org/darktable#18019]
### Describe the bug

seems very similar to #4889.
when moving an image from one film to another using lua api calls, the change is not reflected in the lighttable until manually refreshing by opening another view and returning to light table.

the change is also not reflected in the collections module.

adding
 ``  dt_collection_update_query(darktable.collection, DT_COLLECTION_CHANGE_RELOAD, DT_COLLECTION_PROP_UNDEF,
                               g_list_prepend(NULL, GINT_TO_POINTER(imgid)));
    DT_CONTROL_SIGNAL_RAISE(DT_SIGNAL_FILMROLLS_CHANGED);
    dt_control_queue_redraw_center(); ``

to the end of dt_lua_move_image() in src/lua/database.c fixes the problem.

i have never touched c before, so someone who knows what they're doing should probably look it over properly.

### Steps to reproduce

1. run a script that moves an image from one film to another.
2. observe that no change has apparently happened.
3. move to darkroom view
4. move back to lighttable view
5. observe that the image is moved to a new film.

### Expected behavior

the moved image should appear in the new film without delay.

### Where did you obtain darktable from?

distro packaging

### darktable version

4.8.1-3

### What OS are you using?

Linux

### What is the version of your OS?

Arch linux x

### Are you using OpenCL GPU in darktable?

Yes

**Comment by wpferguson** [comment]
If I take an image that darktable knows about and remove it, then refreshing the collection to remove the thumbnail makes sense.  (I'm not sure we do this though, so I need to check).

If I take an image that darktable does not know about and import it so that darktable does know about it, then refreshing the collection to show the added image makes sense.

If I take an image that darktable knows about and put it somewhere else that darktable knows about then the correct behavior is workflow dependent.  For instance:

- I have a collection of _unedited images_ and another collection of _images to work on_.  I go through the _unedited images_ and pick one at a time and move the _image to images to work on_.  In this case staying in and refreshing _unedited images_ each time an image is moved is probably correct.
- I have a collection of _unedited images_ and another collection of _images to work on_.  I go through the _unedited images_ and pick 10 random images and move them to _images to work on_.  In this case changing the collection to _images to work on_ is probably correct and _unedited images_ doesn't need refreshed.

So my thought is the script should handle changing and refreshing collections in the move scenario since the script has more information available to use in making a better decision.  

Let me do some testing and see what I can come up with.

**Comment by dedenholm** [comment]
Exposing an API call to refresh the view would work nicely for my use-case at least, and would probably be useful in other scenarios too.

I don't know if its of relevance, but there is also no change when in darkroom view :

- I have collection A open, expecting new images to appear in the film strip at the bottom as my script moves them -- but no images appear. 
- The same goes the other way around, when moving images out of the viewed collection -- no images disappear

**Comment by wpferguson** [comment]
After testing...

delete image doesn't refresh either.  :smile: 

As I said before I think refreshing should be handled at the script level.  Here's how you refresh

```lua
local dt = require "darktable"

local function refresh_collection()
  local rules = dt.gui.libs.collect.filter()
  dt.gui.libs.collect.filter(rules)
end

local function delete_image(image)
  image:delete()
  refresh_collection()
end
```

This gives you the option of when you want to refresh, so if you want to make a bunch of changes then refresh you can rather than refreshing after each change.

**Comment by wpferguson** [comment]
I don't know if the refresh solution will work on the film strip or not.  I hate filmstrip and don't use it.  

Just tested, it works there too.

**Comment by wpferguson** [comment]
Also, `image:delete()` only removes from the database.  The file still exists on disk in the folder.

**Comment by wpferguson** [comment]
And the best news of all:  You have a solution now and don't have to wait for 5.2 next June. :smile:

**Comment by dedenholm** [comment]
It appears to be working just as i want. Much apprecciated!
