### ISSUE TITLE
Bottom filmstrip "there are no images in this collection" and bottom panel is missing in 5.0.0

### ISSUE THREAD

**Issue by KBlansit** [darktable-org/darktable#18102]
### Describe the bug

Bottom panel is filmstrip is missing and instead says "there are no images in this collection". Normally this is where I would see images in dark table.

Moreover, I cannot see the bottom bar that includes the presets, styles, second darkroom windows, focus peaking button, color assessment, etc.

### Steps to reproduce

I opened an image from the windows explorer, right clicked on the .arw file, and opened the file with 'darktable photo workflow software'.

### Expected behavior

Film strip and bottom panel should be present and working

### Logfile | Screenshot | Screencast

![screen shot](https://github.com/user-attachments/assets/6d78604d-3bba-4fee-ab4b-8078c76ad922)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

darktable 5.0.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Describe your system?

AMD Ryzen 7 5800X3D
32 GB (4 slots) running at 2133MT/s
NVIDIA 3060 Ti (8Gb)

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA 3060 Ti (8Gb)

**Comment by KBlansit** [comment]
Potentially additional information:
The file I am opening is from a SMB mounted NAS drive, but in darktable 4.8 on my laptop I can open these files without issue.

**Comment by ralfbrown** [comment]
Since no resolution was posted, here is what others who find this issue should try to resolve the situation.

For the missing filmstrip, try switching to lighttable and clicking on the reset button for the "collection filters" module.  There's an issue where it can filter out newly-imported images, particularly after the first time you import with 5.0.

For the bottom panel, try pressing Ctrl-Shift-B repeatedly to cycle through the four configurations of bottom panel until you get both parts showing.
