### ISSUE TITLE
Improve support for Wacom

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#1966]
Currently, darktable supports Wacom stylus pressure, but the buttons of the stylus and of the tablet cannot be assigned, and the gestures are not handled.

Basic gestures could be zoom, pan and scroll. Buttons could be used to define brush size, opacity and feathering.

**Comment by kamidon** [comment]
FWIW, I would find improvements to the support for Wacom graphics tablets very helpful. In particular, while I have a trackball with a mouse wheel attached to the primary computer where I edit photos, using it to adjust things like drawn mask shapes and feathering is extremely awkward in my setup and difficult to improve (especially so where I need to press a keyboard button like shift or control while simultaneously turning the mousewheel). If I could use the scroll ring on the tablet in place of the mouse wheel on the trackball it would solve my most significant issue. 

An enhancement that would be really nice as well but isn't as critical would be middle mouse button panning of both the lighttable and images in the darktable.

I would be happy to help with testing out any proposed changes.

**Comment by dterrahe** [comment]
I don't have access to a Wacom, but will be able to borrow a Huion tablet at some point to experiment. My understanding so far is that X tries to deal with buttons and gestures coming from tablets (with gtk3 generating GDK_TOUCHPAD_PINCH events and the like).

This may have the advantage that I wouldn't have to write a device handler from scratch for #8078 and could deal with tablets in a way similar to keyboard and mouse where events get translated to Key and Move calls in accelerator.c.

It might have the drawback that we would be dependent on X to configure the devices so plug and play might be impossible.

Separately, as far as I can tell any special support for tablets is dealt with at a lower level (masks? individual modules?) so those would have to be refactored to use the global shortcut system (which may need extensions to support the required functionality).

**Comment by dterrahe** [comment]
@kamidon if still interested, would you be able to provide feedback on #12561?

With the inputng changes any extra buttons on a tablet should/might now be supported to assign shortcuts to. Depending on how the scroll ring is presented by the drivers, it might also be handled in some fashion. Middle mouse button panning would require changes in the lighttable/darkroom view handlers.

**Comment by kamidon** [comment]
While trying out PR #12561 I attempted to map the buttons of my Wacom Intuos Pro Small to shortcuts and was unsuccessful. My setup is currently Gnome 42 on X (not wayland). I initially tried with the Gnome Wacom settings button configuration set to "Application Specific". In Darktable I tried mapping a shortcut by pressing the button on the tablet instead of a keyboard button in the procedure to assign shortcuts. Nothing at all happened when I pressed the button. It was still in the state to assign a key.

I also tried setting a keyboard shortcut mapping in the Gnome Wacom settings, using shortcuts unlikely to be typed, like ctrl-alt-shift-1, ctrl-alt-shift-2, etc. I was able to confirm these work in another application, but when I attempted to use them when assigning a Darktable shortcut I got the same behavior as above, it was as if I hadn't pressed the button on the tablet.

I'd be happy to continue to assist with troubleshooting why the shortcut system doesn't see the tablet buttons but will need some suggestions about where to look next.

**Comment by dterrahe** [comment]
It sounds like you have set the wacom up to emulate keyboard key presses. Is it possible to completely switch off this functionality? On my Huion by default button presses are sent as additional _mouse_ (not keyboard) button presses and InputNG tries to respond to those. Not sure why emulated presses would get ignored, but then I'm not sure _how_ they are being emulated (i.e. what kind of keyboard events gtk processes).

**Comment by kamidon** [comment]
I'm not certain, but I think in a modern Gnome environment, even when running on X and not Wayland, the tablet events are generated by libinput and I don't know of any way to disable whatever processing it is doing. I don't know if it is useful to you, but I do know that libinput has documentation on its tablet support here: https://wayland.freedesktop.org/libinput/doc/latest/tablet-support.html#

**Comment by vancouverbluesea** [comment]
I can see you guys are working on this feature. It would be really nice to have a better tablet support in DT.
