### ISSUE TITLE
Noise Profile Loading Error - Only "Generic Poissonian" Available

### ISSUE THREAD

**Issue by waterlubber** [darktable-org/darktable#2027]
**Description**
For whatever reason, the Noise Reduction (Profiled) option only lets me select Generic Poissonian as a preset. None of the built in ones or the custom one I made for my camera are available. This occurs with and without the --noiseprofiles command.

I experienced the bug on Linux Mint 18.3's binary (2.4.4) and on the one I just compiled (2.7.0). I have libjson-glib installed, version 1.1.2-0ubuntu1

**To Reproduce**
1. Create a noise profile for a Canon Powershot SX170IS, or use the ones I've attached
2. Launch darktable with the `--noise-profiles` option on presets.json
3. Open a .dng file from the camera in question
4. Note the lack of an option in the noise removal section

**Expected Behavior;**
A list of all the devices I have presets for, such as the one that appears correctly in the Lens Correction area.

![image](https://user-images.githubusercontent.com/7517025/51504990-1da13880-1db2-11e9-802a-453ff3ef3ad0.png)

**Platform:**
 - OS: Linux Mint 18.3
 - Version: 2.7.0
```this is darktable 2.7.0+270~g33fd8b6
...
compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled
```
Attached is the .tar.gz, presets.json and a couple RAW files from the camera.
[files.zip](https://github.com/darktable-org/darktable/files/2780880/files.zip)

Edit: This also occurs on my Arch Linux install, so it's not related to this particular system either.

**Comment by waterlubber** [comment]
I was able to resolve the issue by changing the noiseprofile.json model name from "PowerShot SX 170 IS" to "Canon PowerShot SX 170 IS." However, I still believe that the dropdown should show similar models of cameras or all models of cameras, as it would at least show the feature working. (or an error like "json file with matching model not found")

**Comment by aurelienpierre** [comment]
denoise **profile** means : if there is a noise profile for your sensor, use it, otherwise, fallback to a generic statistical method.

If you don't have access to custom profiles in the UI, it means there are none for your camera. So, please, [contribute with pictures.](https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/)

> However, I still believe that the dropdown should show similar models of cameras or all models of cameras, as it would at least show the feature working.

The feature works by using a **generic** method. Using a different profile from another sensor entirely defeats the purpose of having profiles (aka customized algorithm built for the specific noise stats of your particular sensor + ADC).

So, everything works as planned, but you might need to read the manual to get a sense of what's going on.

**Comment by rawfiner** [comment]
@waterlubber maybe this behavior comes from the fact of using dng and not the "real" canon cr2 raw file?

**Comment by Nilvus** [comment]
@TurboGit : maybe could be closed ?
