### ISSUE TITLE
Cyan/yellow fringing with 'reconstruct in LCh' in Highlight Reconstruction

### ISSUE THREAD

**Issue by Hodapp87** [darktable-org/darktable#2086]
NixOS and darktable 2.6.0 here.

When I put the Highlight Reconstruction module on 'reconstruct in LCh', I observe some strange cyan/yellow artifacts around certain details in a photo (possibly edges of blown highlights). This is visible at 100% and 200% zoom, and in the exported image.

Here's a 200% zoom showing the artifact:

![dt_artifact1](https://user-images.githubusercontent.com/896431/52542238-c1578600-2d6b-11e9-8e3f-8475b8a8d607.png)

If I use 'reconstruct color', the effect disappears:

![dt_artifact2](https://user-images.githubusercontent.com/896431/52542245-d8967380-2d6b-11e9-9251-ff98ff15e4ad.png)

Image is from an NEF from a Nikon D600:
https://hodapple.com/files/20170330_0004.NEF
https://hodapple.com/files/20170330_0004.NEF.xmp

**Comment by AxelG-DE** [comment]
With current Master and Linux, I checked for Olympus em5MK2 and D750. 
I do not have this phenomenon.

**Comment by aurelienpierre** [comment]
This option is broken from scratch. The module works on the RGB signal before it is even demosaiced, so before the input colour profile is applied. This input color profile holds the transformation camera RGB -> human-based XYZ -> human-based Lab, using adequate coefficients for each camera sensor. So, using Lab/LCh before that correction is done is conceptually wrong, because camera RGB are not colour at all before it's matched to human vision through XYZ. What is done is correcting human-based colour in camera RGB, it can't work.

**Comment by aurelienpierre** [comment]
Won't fix, we can't change the algo without losing compatibility. Checkout filmic reconstruction.
