### ISSUE TITLE
Ui font size is too tiny

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2225]
The general font size isn't comfortable to read if we need to read something (e.g. preferences). Would you be that nice and add some more font sizes?

**Comment by Nilvus** [comment]
Please search and read before posting issue. That's already known and it's possible to change the font size.

darktable is a Linux software on start. This font size is not the same on Linux and Mac. Font size could be changed by editing darktablerc file on your ~/.config/darktable folder. In that file, you just have to modify this line :
`screen_dpi_overwrite=-1.0`
Put value like 110 instead of -1.0 by default should be good. You just have to increase or decrease to adjust which size you want. Be sure to modify this file with darktable closed.

So, this will probably change and be better suitable for all OS with darktable 2.8.

**Comment by johans3** [comment]
Thank you! 
Would be great to have it as configuration in preferences

**Comment by Nilvus** [comment]
That's will normally not necessary on darktable 2.8. See that PR to understand why : https://github.com/darktable-org/darktable/pull/2037

And darktable 2.6 already make it possible to edit theme of darktable with css and make themes. You could see lots of ideas on the forum of darktable.fr website (in french but web translators could help. See the FAQ of the site for links about that.

**Comment by TurboGit** [comment]
Will be in the GUI redesign.
