### ISSUE TITLE
Ghost snapshot aside corrected picture - darkroom 

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2227]
I'd appreciate to see how far we modified our original picture in darkroom module by having a snapshot of the original picture aside the edited picture. 

Split screen vertical for portrait pictures, split screen horizontal for landscape pictures

**Comment by Nilvus** [comment]
I'm not sure to really understand what you mean but this is already possible. darktable have snapshots functions and you could split horizontally or vertically

**Comment by johans3** [comment]
I found the split screen. Better than to have 2 pictures on screen to compare after/before
:)

**Comment by TurboGit** [comment]
So please before opening a zillion of issues, read the manual :) You'll certainly discover lot of things!

**Comment by johans3** [comment]
Don't worry I'm used with bug hunting ;) 
Did a lot of coding myself over a decade

Yes I downloaded the manual but it talks about an older version 1.6 to be exact
The HTML version online is better but we can't download the whole book but only the current displayed webpage

**Comment by Nilvus** [comment]
Seriously, 1.6 ? 2.4 manual is here since a year and since few days, the 2.6 one is here. You don’t seem to be used and good searching. And bug hunting start by be sure to knowing well a software and not posting bug issue that are not ones. And manuals are in PDF... Yes one file for the entire manual... and, wow, that makes a book.
