### ISSUE TITLE
Expose opencl_synch_cache on preferences

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2230]
darktablerc->opencl_synch_cache is set to false by default and in my system using the cache with opencl makes it at least 10 times faster.

Having it on the preferences make it easy to play with it and see what configuration work best for each system. I'm sure that most people are not even aware of this setting.

**Comment by johans3** [comment]
Indeed - I've a relative powerful desktop Mac but the performance isn't butter smooth. I will try out your tips, thanks

**Comment by dtorop** [comment]
To clarify: With `opencl_synch_cache` set to false, is it true that the full pixelpipe is executed even when only a later iop (say "tone curve") is changed? And hence time-consuming earlier iops such as "demosaic" or "lens correction" will always contribute to the pipeline processing time under OpenCL? But that the cost of copying intermediate output from GPU to CPU is such that it is generally best to keep the image data on the GPU rather than copying it back to the CPU (and the cache) after each iop?

If so, would it make sense to selectively cache only the input buffer of the currently focused iop? That way future operations on the currently focused iop would be able to start from the cache, but there would not need to be many useless round-trips between GPU and CPU.

I'm looking at https://github.com/darktable-org/darktable/blob/f3aa9835b43b2378926e1cb88851fa032737f479/src/develop/pixelpipe_hb.c#L1696-L1724 for the code which currently syncs from GPU to CPU, and https://github.com/darktable-org/darktable/blob/f3aa9835b43b2378926e1cb88851fa032737f479/src/develop/pixelpipe_hb.c#L2305-L2310 for the code which currently tries to give priority to caching the currently focused iop.

Incidentally, here toggling `opencl_synch_cache` is a wash: it appears that the extra time spent copying memory obviates the speed-up of caching. But either way, it's laggy to update an iop's parameters, so I'm curious if caching and OpenCL could work together.

**Comment by dtorop** [comment]
See https://github.com/dtorop/darktable/commit/be46298e5c958b8c9617fd06e01979a40bdc44b0 for an attempt to deal with this by only copying from the GPU the input to the currently focused iop.

At quick testing this gives me noticeable speedup (over 2x). I'm curious how this seems from there.

**Comment by edgardoh** [comment]
In my system it doesn't seem to be that expensive the copy from device to host, as I said, I have a 10x improvement. Of course it depends of the module being edited, the position in the pipe, the earlier modules, etc.

I didn't try your approach, but having only the currently edited module in cache will make the entire pipe to be re-processed when another module is edited. Plus, this modification will require a lot of test, there are any number of possible scenarios here.

Did you compare this approach with just disabling this setting? If you don't have a slow down is still easier to expose this setting in preferences.

**Comment by dtorop** [comment]
I see a 2.1x speedup by enabling opencl_synch_cache vs 2.3x by only syncing the active IOP. So it is a marginal difference, and either is good. I do agree that making an existing preference visible will have less impact than altering pipeline code. The nice thing about syncing to CPU only for the focused iop is that it could be a general improvement for OpenCL users rather than something which needed testing on each computer. I imagine that the sync to CPU code is not currently well used, so there could be quirks in either case which no one has yet noticed.

This is with a pretty synthetic test where the pipeline includes white balance, highlight reconstruction, demosaic (Markesteijn 3 pass), basic adjustments, exposure, lens correction and two rgb curves, and I'm only adjusting the last of the rgb curves. I'm using a 4K display, which makes the lag all too noticeable, even without running numbers.

I agree it's worth worrying about complications of selectively syncing/caching modules. Will the cache hash algorithm make sure that everything is OK, or are there more wrinkles? I haven't tested any of this with real-world image work.

I've found that there's often a lag on the first parameter change to a newly chosen iop. As the cache is currently only 5 entries for the preview/full pixelpipes, for sufficiently complicated work the whole pipeline will need to be re-processed from at times.

**Comment by edgardoh** [comment]
With a 24Mp image, on the downsampled image, the copy device to host takes
0.002s, I can totally live with that on every single module, so just having
this setting enabled works for me.
As I said, I haven't done any testing, but unless there's a huge difference
in another driver/graphic card, having the focused module cached all the
time seems reasonable. Only way to know is that someone else do some
testing on this.

**Comment by dtorop** [comment]
Here with a 24MP image, the copy from device to host takes 0.02 sec. (and from host to device takes 0.007 sec.) for the downsampled image. This is on a laptop with a Quadro P4000,

**Comment by edgardoh** [comment]
That's some difference.

Instead of a true/false setting we can have a combo box: synch none / synch all / synch active module.

And set the default to active module, this seems to be the best for most people.

But I have no idea how to change the type of a config variable...

**Comment by dtorop** [comment]
I think so long as we keep "true" and "false" as the other two values of an enum config variable (beside "active module", changing the type of the config variable should be backward compatible. I'll try this out & commit something to https://github.com/dtorop/darktable/tree/opencl-with-cache if it works.

My OpenCL setup may be quirky (which got me looking at this issue initially), so take the 10x slower copy with a grain of salt. But then again if my setup is that slow, others may have the same situation.

**Comment by dtorop** [comment]
742cbc5e4461fcea1c6d4a913ac34a33513d4479 makes `opencl_synch_cache` a user-visible enumerated preference with the default "active module".

I'm reluctant to put too many tweakable params into the GUI if there is a general "right" option, but at least this way it'll be slightly easier to do comparison testing. My latest informal timing here for a particular pixelpipe is that "true" gives a 1.6x speedup and "active module" gives a 1.8x speedup.

It goes without saying that if you switch to preference to "false", the behavior will continue to be equivalent to "active module" until an earlier module in the pixelpipe is modified, invalidating the cache.

**Comment by edgardoh** [comment]
Looks good to me.

**Comment by dtorop** [comment]
Thanks. I used it all day yesterday with the config set to "active module". I didn't run into any quirks, and found it the missing link to make darkroom view adequately responsive. I'll hold off on making a PR though in case others have the chance to try the code.

Ideal (and this would be a new issue) would be some sort of self-monitoring/testing to recommend/tweak config based on hardware and how it's being used. Some of this already happens when `opencl_scheduling_profile` gets auto-determined on first use, but the choice of "very fast GPU" can be overoptimistic. If the priority is to get the full pixelpipe finished as fast as possible, "default" can be best. Another one to adjust is `plugins/darkroom/demosaic/quality` as "always bilinear (fast)" can be a notable speed-up (at least on x-trans). Another big slow-down can be `dt_colorspaces_get_matrix_from_profile()` silently rejecting LUT display profiles, causing `colorout` iop to fall back from OpenCL to the lcms2 on the CPU.

**Comment by edgardoh** [comment]
This can wait until the PR is in, so you can get feedback from the
reviewer, but if you want to remove the gui stuff that's ok with me. I
suggested it only to expose the true/false setting, but since the new
default already work very well and this is a one time setting that probably
only advanced users will tweak, having it hidden doesn't seem so bad.

**Comment by dtorop** [comment]
I rebased this and created PR #2367. I added one more commit as suggested and removed the config option from the GUI.

**Comment by edgardoh** [comment]
Thanks!

**Comment by AxelG-DE** [comment]
@edgardoh 
I don't know, you saw the last view comments on "my" issue [#2484](https://github.com/darktable-org/darktable/issues/2484)

At the end of that just successfully closed performance issue, I reported, all "versions" are fast. Subsequently I found out, that still 2.6.2 is a bit more responsive on WB sliders compared to 2.7 and it cannot be seen in `-d perf`

Than I changed _opencl_synch_cache_ from `active module` to `false` and the lag was (almost) gone.

I noticed that lag, when I yesterday night edited that [play raw on pixls.us](https://discuss.pixls.us/t/playraw-milky-way-over-geroldsee/11433/20?u=axelg) so not only on WB, is what I want to say....

Shall I open a new issue?

**Comment by edgardoh** [comment]
If you feel that the setting is not working then you can open an issue, but
so far it doesn't seem so.

When set to active module, dt uses the cache with opencl?

**Comment by AxelG-DE** [comment]
@edgardoh @dtorop  
It is working, but it seems buggy (as far as I am allowed to say so, as a non-dev). It is very hard to explain, but I will try in a new bug report and link it to this one here...

**Comment by dtorop** [comment]
@AxelG-DE 
Sorry to be absent from this conversation: lots of non-darktable things going on here. I'm looking over the #2514, though no promises of a solution from here!

**Comment by AxelG-DE** [comment]
@dtorop
You don't need to apologise. You guys making this great piece of software possible in your spare(!) time. So all my gratitude. 

Currently I'm really struggling with performance. After we successfully closed #2484, I seems to figure, even things improved tramendously, some things are still sticky.

Above mentioned stalls, they show in my logs 1.1-1.6 seconds. But my monitor actually stalls for approx 3s. Likely that would need a different bug report, just at this moment I cannot nail it down to something repeatable, reproducible :-(
