### ISSUE TITLE
Selecting unreadable files causes DT to hang

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2314]
**Describe the bug**
Some pictures are unreadable but still visible as thumbnails in darkroom. If you select such a file, then DT is gonna hang. 
Zooming-in (light table) reveals unreadable files. Zooming out produces a thumbnail for unreadable files (visible as bite skull) 

**To Reproduce**
0. Keep in mind an unreadable file (by name) -lighttable
1. Zoom-out using the mouse - light table (the unreadable file will get a thumbnail) 
2. Switch to the darkroom module 
3. Select a the thumbnail of our unreadable file 
4. Dark table will hang

**Expected behavior**
Replaceable bite skull icon and more compatibility for Mac. My usual files are Jpg, JPEG, CR2 (Canon eos raw) some PNG, tiff. 

**Platform (please complete the following information):**
 - OS: Mac 10.11

**Comment by johnny-bit** [comment]
I've tested and I found the following:

In case the file is not readable due to weird encoding - the darktable correctly informs user that it cannot read it
In case the file is not readable due to file damage - the darktable correctly informs user that it cannot read it (at least in case of rawspeed)
in case the file is removed - the darktable correctly informs user that file is unreachable.
in case the file is zeroed (meaning file has size = 0 and/or whole file is filled with zeroes) - the darktable correctly informs user that the file is problably damaged
in case the file is actual garbage (meaning totally random content) - the darktable correctly informs user that the file is probably damaged.

I haven't experienced hangs in all above testing be it on 3.2.1 or current master.

If you have particular file that manages to hang darktable - please open a new issue with the file attached so we can work out why and how darktable hangs on it.
