### ISSUE TITLE
Create original-state snapshot by default

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2315]
Snapshots are very useful to see progress, and I'd expect DT to create a default snapshot (from the unmodified original state) of every edited picture

I know I can go back in the history stack and create all the snapshots I want.. But that's not the point. It seems DT currently doesn't support any "snapshot automatism"

**Comment by johans3** [comment]
As for now, snapshots are generic and not specific per photo. 

E. G. When I create a snapshot and change to another photo my snapshot still refers to the old photo from before

I think snapshots should be specific for every photo and stay in cache for a bit / how long could be till quitting  / or by changing photo / or be another user preference

**Comment by pphotography** [comment]
**To your first post:**
I use snapshots a lot to see differences between my edits. Mostly I use them before activating a new module to compare my changes with the version before.

Sometimes I want to compare my edits with an 'initial' state to see what I've done overall. Using a snapshot from the unmodified image state often fails due to the following reasons:

- Crop and rotate. I cannot move the slider between before and after because I see different  parts of the image next to each other
- Underexposed images. Sometimes I have to increase exposure so far that the original image is too dark to compare with the edited bright one effectively. 
- Orientation. On rotated images I cannot compare before and after.

Usually I use one of these points to go back in history as far as I can to compare, but going back to the very first point often results in a state that I cannot compare with the final one.

**To your second post**
When you're using duplicates of an image with different edits you can compare them directly. Without this option this would not be possible anymore.
So I think this should be a configurable option in the settings.

**Comment by johans3** [comment]
@**pphotography **
I appreciate your comment very much! 

I do cut my pictures but not too often - that depends more on who gets the picture. Nevertheless I fully agree to your nice explanation. Thank you :)

**Comment by StaggerLeee** [comment]
I would like to ask for one new option. (Darkroom)
There is a place for one additional icon between those 7 icons for grouping modules (Favorites, etc,,,). Or where you find better place for icon, nevermind.

Make one new option (icon) as global ON/OFF (same priciple as deactivating separate module(s)) and give it function as:

- ON (global of course) = All edits persist as they are.
- OFF = reverts image to primary state (0 original, or similar), as when it was when RAW was imported and not edited.

This way we could skip taking snapshots for all images to preview before-after.

Somehow it is better to notice color shifts (those we self make with edits without beeing aware of), and it can be tricky when they play games if it is done with snapshot drag slider.

Or simply, make it possible to bind "0 original" in "history" to custom keyboard shortcut. This way is also possible to switch original vs edited very quickly, keep eye on some detail8s) in image and see tricky color shifts.

I am not talking merely about "white balance" but color shifts that occure and not are natural still. Can be best seen by keeping an eye on people clothes.

New filmic module tends to make those color shifts so one new approach to after-before would be maybe needed. It is not only filmic module, others can do the same.

To be able to bind "0 original" to custom keyboard shortcut would be more than enough.

**Comment by StaggerLeee** [comment]
Just  became aware of Ctrl + Z, Ctrl + Y shortcuts.
Ask for one additional click on 0 original if view is switched between Lighttable-Darkroom, but it is very enough and good.

**Comment by johnny-bit** [comment]
I thought about usability and universability of this request... and i think it's not very universal and certainly not for a core functionality.

There are 2 workarounds: attach a shortcut to "take a snapshot" action and simply use it whenever entering "fresh" image OR request new lua script here: https://github.com/darktable-org/lua-scripts/issues/new

I think that covers the initial request.

Per-photo snapshot might also not be "universal", but that imo should be separate issue in vein of "one issue per bug/fr" spirit :)

**Comment by wpferguson** [comment]
Issue created https://github.com/darktable-org/lua-scripts/issues/337

**Comment by wpferguson** [comment]
PR #9806 submitted that creates the API changes to implement this.

**Comment by wpferguson** [comment]
Finally got back to this... PR https://github.com/darktable-org/lua-scripts/pull/488
