### ISSUE TITLE
tone curve: drawn mask bypassed when using coloradjustment mode

### ISSUE THREAD

**Issue by DouglasRaillard** [darktable-org/darktable#2317]
**Describe the bug**
When using the tone curve module with a drawn mask and the coloradjustment mode, the drawn mask is ignored and the module is applied to the whole image.

**To Reproduce**
1. Enable the tone curve module
2. make a crazy edit to make the effect of the module obvious
3. Select "drawn mask" in blend mode
4. Draw a simple mask
-- at this point, only the masked area is modified by the module, which is what we want -- 
5. Set coloradjustment as blend mode
-- at this point, the mask feature goes banana and the whole image is modified by the module --

Note: this seems to only happen for tone curve module, other modules don't seem to have that issue.

**Expected behavior**
The mask should restrict the area of the image edited by the module, regardless of the blend mode.

**Screenshots**
This screenshot tries to show what went wrong:
* The left part is the vanilla image
* the right part has the tone curve module enabled setup with an obnoxious curve, and also the mask display enable to show that only a small spot should be modified. Even with the mask display on, the effect of the module can be seen.

![tonecurve+drawnmask+coloradjustment](https://user-images.githubusercontent.com/2179003/55283484-4dddf800-535c-11e9-9695-d63a572c5ddf.png)

**Platform (please complete the following information):**
 - Archlinux  
 - OpenCL not used

darktable 2.6.2
compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.1
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by douglas-raillard-arm** [comment]
The issue is still present in 3.0.0

**Comment by DouglasRaillard** [comment]
The issue is still present in 3.0.0

**Comment by RawConvert** [comment]
I was going to create an issue that an Exposure mask with coloadjustment blending results in the whole image being affected...
This is in the dt 3.4.0 release.

**Comment by johnny-bit** [comment]
@hlecleme - you've worked extensively on masks - what do you think about the issue here?

**Comment by ralfbrown** [comment]
I took a quick look, and `_blend_coloradjust` in develop/blends/blendif_lab.c is identical to `_blend_color` except that it always uses the output L value instead of always using the input L value.  For the latter, it doesn't matter what `local_opacity` is, and you get an unchanged output on the parts where the mask is zero.

But for the former, you get exactly the observed behavior, where the mask seems to be ignored (colors *do* shift only in the masked portions, it's just much less obvious than the luminance shift).  I don't know exactly how coloradjust is supposed to work, but a possible solution may be adding
```
ttb[0] = (tta[0] * (1.0f - local_opacity)) + ttb[0] * local_opacity;
```
where the comment currently says that ttb[0] stays unchanged.
