### ISSUE TITLE
Global color picker: replace dropdowns with buttons in UI

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2352]
**Is your feature request related to a problem? Please describe.**
When the user has to select an entry from a list of options in a user interface, dropdown menues are one way to implement this in a user interface.
They are handy when either the list is very long or the number of entries varies.

The downside of a dropdown menu is that the user has to click on the menu to see its values and he has to click a second time to choose an entry.

In the global color picker on the left side of the screen the user can choose between options from dropdown menus. But here only a few options are selectable:
- area, point
- min, mean, max
- lab, RGB

**Describe the solution you'd like**
Since there are only a few options I came to the idea of implementing the selections with buttons instead of dropdown menus.

The result would be something like in this mockup:
![colorpicker](https://user-images.githubusercontent.com/49001045/55688765-d112d580-597c-11e9-8f5e-5ff62bf752bc.png)
**Improvements:**
- User can see all available options
- User can select options with only one click

Opinions?

**Comment by junkyardsparkle** [comment]
Rectangular buttons like those are used to launch actions in the rest of the GUI. They should really be radiobuttons, perhaps similar to the ones that have already replaced the drop-down for blending options in the current development version:

![screenshot-1554701061](https://user-images.githubusercontent.com/4522189/55700521-6bc2e280-5984-11e9-85c7-0580ac9e14c9.png)

One advantage of the dropdowns is that they're easily extensible for any options added in the future. I find that once I'm familiar with a particular combobox, it's easy to just use the scrollwheel to select an option rather than multiple clicking.

**Comment by aurelienpierre** [comment]
It makes sense to use buttons (or, more precisely, tabs) for min/max/avg, but color spaces (Lab, RGB) could get more options in the future, so we need to keep them as a dropdown to be ready for that.

**Comment by dterrahe** [comment]
This module has been significantly rewritten and simplified since 3.2 (#6350). Unfortunately without taking this FR into account. The new implementation still uses dropdowns, which has the advantage that the module scales better with narrow panel width and that it is easier to support more color spaces (LCh, HSL and None have been added). 
![image](https://user-images.githubusercontent.com/1549490/101277732-5a138d00-37ae-11eb-8c5b-b5a6ca766190.png)

If you still feel there are significant issues please update this FR with suggestions or otherwise please close.

Thanks!

**Comment by dterrahe** [comment]
I'm closing this for now since there are no specific suggestions to improve the current version. Please feel free to reopen if you _do_ have suggestion.
