### ISSUE TITLE
Shortcuts: import/export in human readable format

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2363]
**Is your feature request related to a problem? Please describe.**
Under 'global preferences' -> 'shortcuts' the user is able to import/export all shortcuts. 

An exported file has a structure like this:

```
; darktable GtkAccelMap rc-file         -*- scheme -*-
; this file is an automated accelerator map dump
;
; (gtk_accel_path "<Darktable>/image operations/colisa/fusion/edit" "")
; (gtk_accel_path "<Darktable>/image operations/tonecurve/preset/contrast - med (gamma 2.2)" "")
; (gtk_accel_path "<Darktable>/image operations/levels/enable module" "")
; (gtk_accel_path "<Darktable>/image operations/colorreconstruct/hue/decrease" "")
; (gtk_accel_path "<Darktable>/image operations/grain/show module" "")
; (gtk_accel_path "<Darktable>/image operations/filmic/preset/14 EV (backlighting)" "")
; (gtk_accel_path "<Darktable>/image operations/zonesystem/show module" "")
; (gtk_accel_path "<Darktable>/image operations/lens/TCA B/reset" "")
; (gtk_accel_path "<Darktable>/image operations/splittoning/compress/decrease" "")
; (gtk_accel_path "<Darktable>/image operations/clipping/angle/increase" "")
; (gtk_accel_path "<Darktable>/modules/copy_history/paste all" "<Primary>v")
```

This is usable for backup/restore purposes, but to edit the shortcuts by a user outside of Darktable there are some obstacles:

- the list is not ordered, for example the shortcuts for a certain module are distributed randomly over several rows
- the list is not browseable
- it is hard to see duplicates of entered shortcuts

**Describe the solution you'd like**
Darktable should use a human readable format like CSV. A structure could look like this:

```
Level 1|Level 2|Level 3|Level 4|Key
modules|filmstrip|color yellow||F2
image operations|hazeremoval|fusion|reset|
modules|copy_history|paste all||<Primary>v
global|zoom out|||<Primary>minus
image operations|lens|enable module||
modules|filmstrip|color purple||F5
```

This format allows advanced editing possibilities, for example with a spreadsheet program like Libreoffice Calc:

- Since the parameters are in different hierarchy levels ('Global|zoom out' has got 2 levels and 'image operations|hazeremoval|fusion|reset' has got 4), the structure should be flattened to the maximum amount of hierarchy levels to create a two-dimensional table. In this particular case the user has 4 colums to navigate and filter and a 5th one with the hotkeys.
- The user can easily browse the structure by ordering or filtering the imported table by names (see below)
- The user can sort the list by shortcuts and easily see shortcuts that are missing or duplicates (see below)

**Additional context**
Filtering with Libreoffice Calc:
![libreoffice01](https://user-images.githubusercontent.com/49001045/55793507-5b655180-5ac3-11e9-859f-85664917ead9.png)

Ordering the shortcuts by name with Libreoffice calc to see missing and duplicate shortcuts:
![libreoffice02](https://user-images.githubusercontent.com/49001045/55793515-615b3280-5ac3-11e9-9747-834783c3c2bd.png)

**Comment by johnny-bit** [comment]
@dterrahe - maybe this myght be ineresting for input system too? :)

**Comment by dterrahe** [comment]
Of course I noticed this one! :-)

The config format for input NG is by necessity completely different; for one thing, there is no one->one/zero mapping between actions and shortcuts, since multiple input devices are supported and different shortcuts can have different qualifiers, for example speed or (multi-)instance. For another, because it is not using the gtk framework, there is no requirement to squeeze into their format.

The current config file prefers simplicity and flexibility. It has two parts, the LHS and the RHS connected by an "=". In each side, the different parts are semi-colon separated. On the left, there is at least a Key item (might be "None" if this is just a midi knob turn, for example). On the right side, there is at least an Action item, which is a slash ("/") separated path of any length (modules can use as many nested widget sections as they like). So the minimum is this:
`l=global/lighttable view`

Each side can have qualifiers. The shortcut could be a combination of a Key (with all modifiers) _and_ a Move, combined with all three mouse buttons, triple clicked. If a move is used to trigger a different action for an Up or Down move, then the direction (up/down) would also be there (not yet implemented). On the right side, an Action can be qualified by the applicable instance (first/last/+2/-2 etc) and by speed (*10). To be implemented: elements (colorpicker/min/max/node1/node2 etc)

So at the moment, a longest example would be:
`<Primary><Shift><Alt>s;vertical;left;right;middle;triple=iop/splittoning/shadows/hue;+2;*0.01`

For multiple devices of same type (two gamepads; maximum 10) an "n:" would be added before the Key or Move, so:
`2:<Button>B;3:<Left>Y=iop/filmicrgb/threshold`
would be moving the left joystick on your 4th gamepad up/down while holding the B button on the 3rd gamepad (silly example on purpose!).

Again, the underlying principle is simplicity and flexibility. In order to not restrict the features or types of devices that can be added in future, not too many assumptions can be made about the configuration format used. That does have the drawback that the format may not be completely automatically manipulated without knowing about those devices and features and which actions are in the same view (and would therefore clash if assigned the same shortcut). But at least the components can be found easily (split on = -> ; -> / ).

#8078 has a big [RFC] marker on it, so I'm _very_ open to suggestions (as long as people realise that I've put quite a bit of thought into this and that none of the choices are without drawbacks...)

**Comment by dterrahe** [comment]
To be clear, this is not set in stone yet, and to support fallbacks (i.e. for example modifiers without explicit key yet) or modifier keys combined with other devices (midi/game) I'm already half decided to drop the gtk way of representing modifiers in a machine readable way, between <>, and having them as separate qualifiers on the line. And then dropping <> completely and always have the driver name (and device number) for non-keyboard/mouse. So the above examples would then be:
```
s;ctrl;shift;alt;vertical;left;right;middle;triple=iop/splittoning/shadows/hue;+2;*0.01
game2:button b;game3:left y=iop/filmicrgb/threshold
```
