### ISSUE TITLE
drop down menus do not show current selection

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#2395]
when drop-down menus display possible options, current selection is not evident.  no color shift or indication which is current.

**Comment by aurelienpierre** [comment]
Current option is supposed to be one shade brighter. Is it not obvious enough or not visible at all ?

**Comment by ptilopteri** [comment]
it is definitely not obvious on my display which I have not adjusted
openSUSE Tumbleweed (current)

**Comment by ptilopteri** [comment]
* Aurélien PIERRE <notifications@github.com> [04-13-19 12:19]:
> Current option is supposed to be one shade brighter. Is it not obvious
> enough or not visible at all ?

it is visible but definitely not obvious.

-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Registered Linux User #207535                    @ http://linuxcounter.net
Photos: http://wahoo.no-ip.org/piwigo		    paka @ IRCnet freenode

**Comment by junkyardsparkle** [comment]
What I'm seeing, with no custom CSS file, is that the lighter foreground/text color gets a shade darker, but not the background, hence *decreasing* contrast. In a UI, this usually signifies *innactive* states. Since this hilighting doesn't persist anywhere visible after the selection is made, I think it could be made less subtle without worrying about it becoming distracting.

**Comment by ptilopteri** [comment]
in the drop-down, the option under the mouse is visibly lighter, but there is no indication what *was* current.  if on mistakenly makes a selection, there is no indication which to return to.

**Comment by Nilvus** [comment]
@ptilopteri and @junkyardsparkle : as some improvements as been made on css for this new UI, could you please test the last master revision and say if this issue is always on or could be closed ? I don't have this behavior on last one (I've made some tweaks with 2 PR since your issue).

If it's now ok for you, @ptilopteri please close this issue. If you think it's always here, please post a screen capture. Of course, be sure to have GTK >= 3.22 as this new UI need at least GTK 3.22.

**Comment by junkyardsparkle** [comment]
I can't build latest right now due to new GTK version requirements, but I think I was misunderstanding the issue anyway.

**Comment by ptilopteri** [comment]
@Nilvus visible and ok for me now.  closing
