### ISSUE TITLE
Filmic crashes

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2413]
[_IGP1545.DNG.zip](https://github.com/darktable-org/darktable/files/3081145/_IGP1545.DNG.zip)

**Describe the bug**
With the attached picture the activation of filmic module causes a crash
**To Reproduce**
1. Open this image
2. click on filmic module
3. enjoy the crash

**Platform (please complete the following information):**
 - OS: Ubuntu 
 - Version 18.10

**Additional context**
This happens with or without OpenCL. I'm posting a specific image, but this happens with all images (at least with DNG from Pentax)

**Comment by Nilvus** [comment]
Yes revision d5053b13 from Tobias make filmic crash. Revert back to revision before this one to have filmic ok with :

git checkout 1b2804a579555b0d483de8e62a28f7965d5e9edd

then

git submodule update

and compile again

It seems that this guy like to send revisions without consultation with other developers that could hassle users (like revert back awful and annoying 1st april game on its own way or change css on its own way ; why since darktable is themable ?) or modify other revisions that  other developers have discussed before sending them... I know that he is an old developer but darktable is a free and community software. And all choices have sides effects for all users, not one person or few ones, but lot of users. Ok, it's made on free time but all choices have consequences to have in mind...

I hope he will read this because I have enough to see that as a user (I'm not a developer, I only contribute on translating manual).

**Comment by TurboGit** [comment]
I have added a guard to avoid the crash. My fix is probably not the best one but at least filmic should be usable again. I agree @Nilvus it is quite painful to have to deal with those regressions.

**Comment by Nilvus** [comment]
Yes, it's fixed. Thanks @TurboGit for that.

**Comment by PaoloAst** [comment]
Thank you!

**Comment by AxelG-DE** [comment]
@Nilvus if you start studying commits in that detail, you are a dev in my eyes. Otherwise, how to categorize when I consider my self being a power user :smile:

If you want Tobias to read your comment above and giving him the chance to prove acting considerate, reasonable and objectively, you could have added @houz :wink:
May either one convince the other one. Me as a power user I appreciate all your guys efforts ans commitment.

**Comment by Nilvus** [comment]
> @Nilvus if you start studying commits in that detail, you are a dev in my eyes. Otherwise, how to categorize when I consider my self being a power user smile

Maybe but I don't have skills in coding and don't want to. But I like to know what I'm doing and understanding what I'm using and doing. I just read descriptions of new commits to understand what's new. That allow me to improve my use of darktable. And I have skills on understanding how hardware and software work and on analyse some problems. And after that If I could help, it's better ! So maybe I'm a power user too ;-)

> If you want Tobias to read your comment above and giving him the chance to prove acting considerate, reasonable and objectively, you could have added @houz wink

You're right, I forgot to add this.
