### ISSUE TITLE
Latest changes lead to an ugly and cumbersome interface

### ISSUE THREAD

**Issue by dkeats** [darktable-org/darktable#2416]
**Describe the bug**
The user interface, after update to **2.7.0~git1007.2c02989e8** shows interface changes that are not in keeping with the quality of previous versions
1. The font used for interface elements is too large, and this makes using the menus cumbersome. 
2. The excessive grey space around the image detracts from the image and reduces usable screen space.
3. With the clutter caused by large font size, the dropdown menus are hard to distinguish

**To Reproduce**
1. Open the application and look at it

**Expected behavior**
The earlier versions had a beautiful compact interface

**Screenshots**
Available if needed

**Platform (please complete the following information):**
 - OS: [Ubuntu 18.10 Gnome]
 - Version [18.10]

**Additional context**
It would be nice if we could have the much tighter and easier to use interface back or have a smaller font that does not look as ugly and space consuming. The grey around the image serves no purpose.

**Comment by TurboGit** [comment]
Yes a screenshot would be nice as we don't seem to have the same interface.

**Comment by dkeats** [comment]
![darktable_038](https://user-images.githubusercontent.com/1401367/56209723-7d774a80-6054-11e9-94c8-87934f32b0e7.png)

Screenshot. The latest push seems to be a bit better on the fonts, but it still feels clunky and cumbersome.

**Comment by rabauke** [comment]
I think it is very valuable that some efforts have been undertaken to revise the UI. The new UI is a step into he right direction. Nevertheless, some things need to be improved:

* Generally, there are to many different font shapes and font sizes used, which makes the UI rather disharmonious.

* In the blend mode drop down menu, it is very difficult to identify which mode is currently selected. (This problem was already present before the UI revision.)
![blend_modes](https://user-images.githubusercontent.com/1159508/56210400-0e9af100-6056-11e9-9b8d-d841c4c27fc5.png)

* The color picker symbol is rather bulky. 

* I do also not like the gray border around the center image but might get used to it. In particular if it would be darker.

**Comment by dkeats** [comment]
Yes, a just slightly off black colour for the border would be better. It would allow it to differentiate itself from the black background, but not be too distracting.

**Comment by Nilvus** [comment]
It seems that you don't have fonts added in the new css like Roboto or others so darktable use the default system font that doesn't fit to its UI. You can see which fonts used on the revision you have written by opening the darktable.css. On more recent revisions, you have to open the darktable-elegant css file. And see which fonts installed. You can also copy the file in your /home/"user"/.config/darktable/themes folder and add a font that could seem ok for you that you have on your system (or install fonts missing).

**Comment by dkeats** [comment]
I installed the Roboto font and that fixed the font.  It is back to awesome now :) Thanks

**Comment by Nilvus** [comment]
Because you use revision before the one change the CSS to have by default (even with Roboto fonts installed) font system. So what you described as a ugly and cumbersome interface. Revision 1490a9a5.
After that revision, Pascal Obry (@TurboGit) make another revision that add this darktable-elegant css. Revision 3a74e249.

**Comment by TurboGit** [comment]
> I installed the Roboto font and that fixed the font. It is back to awesome now :)

Good to hear that :) There is still room for improvement and this will happen in the coming weeks. I have fixed today some missing arrows in darkrroom style menu for example. Closing this ticket at this point.

**Comment by aurelienpierre** [comment]
> * The color picker symbol is rather bulky.'

I still find it rather small. Previously, because it was even smaller, I missed the button half the time and ended up setting the slider value to 100%. I updated the UI with 4K and touchscreens in mind.

> * I do also not like the gray border around the center image but might get used to it. In particular if it would be darker.

Actually, having a darker border will make the image look more saturated, less contrasted and brighter. Again, and for the last time, it's not intended to be beautiful, but to reduce the visual aberrations coming from the sourround when performing visual assessment.

> * Recently, so-called soft-bound sliders have been introduced, where the slider can be pushed beyond the usual bound by entering a numerical value. There is no indication that allows users to distinguish between these soft-bound sliders and ordinary sliders. (This is also not directly related to the recent UI refactorings, but should be fixed. Have no idea how this can be done without rendering the UI ugly.)

That has been there for a long time, the only novelty is the dot under the zero value (which makes formerly silent issues more obvious now).
