### ISSUE TITLE
Lighttable: missing Ctrl-Z zoom with areas in focus

### ISSUE THREAD

**Issue by surfermc** [darktable-org/darktable#2433]
**Describe the bug**
ctrl-z to zoom with areas in focus is missing from Lighttable

**To Reproduce**
Select image in Lighttable
Press ctrl-z no zoom with areas in focus

**Expected behavior**
Zoom with areas in focus

**Platform (please complete the following information):**
 - OS: Windows
 - Version: darktable-2.7.0+1026_gaa735136c-win64

**Comment by Nilvus** [comment]
Before sending this type of issue (that is not one), please read the manual (and/or see shortcuts in preferences dialog here) to understand why. Ctrl+z is not used for this function as it is used to undo things (like in lot of software). Now, to have areas, you have to use Maj+Z for zoom with areas in focus (or Ctrl+Alt+Z to have persistent one). Remember that shortcuts are also editable.

@TurboGit : I think you could closed this issue.

**Comment by surfermc** [comment]
I have read the manual, hence why I raised the issue. 
The manual for v2.6 and clearly states in Chapter 2.1 "ctrl-z fully zoom into the image and show areas in focus" This feature existed for v2.6 but does not work for 2.7.

**Comment by surfermc** [comment]
I have also added a snapshot from the shortcuts dialog
![darktable_2019-04-21_08-43-26](https://user-images.githubusercontent.com/5568665/56467057-a52e3000-6411-11e9-836c-84030643c2a2.png)

**Comment by Nilvus** [comment]
> I have read the manual, hence why I raised the issue.
> The manual for v2.6 and clearly states in Chapter 2.1 "ctrl-z fully zoom into the image and show areas in focus" This feature existed for v2.6 but does not work for 2.7.

Some people have already posted issue without reading or even knowing really how darktable works. So sorry if you read that.
That's strange since on the master branch and for some times now, normal behavior is having Ctrl+z for undo working.
Have you tried to delete and redo the shortcut ?

See what I have (I'm also using master branch so it's the same as yours. Only difference is I'm on Linux, not on Windows) :

![Capture-20190421101016-800x830](https://user-images.githubusercontent.com/45535283/56467339-e4fb1480-641d-11e9-8323-d2b5a53fbe77.png)

**Comment by parafin** [comment]
Try re-assigning the shortcut and retrying ctrl-z in lighttable (without restarting the DT). At least on Mac there is some bug with shortcuts where this workaround helps.

**Comment by surfermc** [comment]
I notice that by default two shortcuts are assigned to Ctrl+Z, preview with focus detection and undo.
Ctrl+Z by default is assigned to undo. Re-assigning Ctrl+Z to preview with focus detection makes it work.
What will be the default preview with focus detection shortcut in future. I will configure my machine to use this.

**Comment by parafin** [comment]
OK, so it's unrelated to macOS issue. This is a bug due to these 2 lines:
https://github.com/darktable-org/darktable/blob/379ed9e415e663fe529fc89ab06ff413e4233bd8/src/views/lighttable.c#L3746
https://github.com/darktable-org/darktable/blob/379ed9e415e663fe529fc89ab06ff413e4233bd8/src/views/lighttable.c#L3751

One of these needs to be re-assigned (probably focus detection).

**Comment by TurboGit** [comment]
Ah indeed! This was on my todo list and I forgot about it since I had changed all the accels to use:
'w' instead of 'z' to avoid conflicts with the undo/redo. I'll do that.
