### ISSUE TITLE
Panasonic TX1 camera support

### ISSUE THREAD

**Issue by bakubo** [darktable-org/darktable#2440]
I am running darktable 2.6.2 on Win10. I have raw files from several of the cameras I have used over the years and have been able to open them in darktable. Today I tried to open a Panasonic TX1 (ZS100, TZ100, etc. outside Japan) raw, but it gives me this message:

**failed to read camera white balance information from ‘P1000555.RW2’!**

At this point darktable hangs and I can’t do anything with it except to kill it. Any ideas?

I have tried more than one raw from the camera. All of them open okay with Photoshop CC ACR.

I tried to upload the raw file by dragging it to this message, but I got an error saying that the file type is not supported.  I uploaded it to the following location and the file is named P1000555.RW2:

https://raw.pixls.us/

**Comment by LebedevRI** [comment]
> I uploaded it to the following location and the file is named P1000555.RW2:
> 
> https://raw.pixls.us/

Thanks, but please upload the whole sample set for that camera - all aspect ratios.

**Comment by AxelG-DE** [comment]
I am on git-master +1047 and can confirm (if still relevant)
DT does not really hang, even it feels so. But if you double click on another foto in lighttable, it will react accordingly
Cheers
 Axel

**Comment by bakubo** [comment]
The Panasonic TX1 is the Japan name for the ZS100, TZ100, etc.  Different places around the world have different names.  It is the very annoying Panasonic practice.  This camera came out in January 2016.  It is not a new model.  I found this old thread about the ZS100 and TZ100.

https://redmine.darktable.org/issues/11950

**Comment by LebedevRI** [comment]
> It is the very annoying Panasonic practice.

Yep

**Comment by bakubo** [comment]
I see that darktable already has support for the Panasonic ZS100/TZ100 and the TX1 is the same camera.  I hope that the TX1 will be recognized soon.  Thank you.

https://www.darktable.org/resources/camera-support/

**Comment by LebedevRI** [comment]
> I see that darktable already has support for the Panasonic ZS100/TZ100 and the TX1 is the same camera. I hope that the TX1 will be recognized soon. Thank you.
> 
> https://www.darktable.org/resources/camera-support/

I have already stated the prerequisites:


> > I uploaded it to the following location and the file is named P1000555.RW2:
> > https://raw.pixls.us/
> 
> Thanks, but please upload the whole sample set for that camera - all aspect ratios.

**Comment by bakubo** [comment]
Okay, but why can't you use the full set that have already been uploaded earlier?  Here:

https://redmine.darktable.org/issues/11950

**Comment by LebedevRI** [comment]
That set is for `Panasonic DMC-ZS100`. This is `Panasonic TX1`.
Yes, i have noticed that they are just renames. The set is only needed for completeness.

**Comment by bakubo** [comment]
I uploaded 3 more files so that makes 4 in total:

**Panasonic: all the crops (1:1, 4:3, 3:2, 16:9)**

**Comment by LebedevRI** [comment]
Okay, i'm not sure if on https://raw.pixls.us/ it is written too tip-toey, but
"If your camera model can produce more than one type of output please consider uploading the entire set."
means that in this case, don't upload 3 missing samples, but upload 4 new samples.

**Comment by bakubo** [comment]
I have already uploaded a complete set of 4 photos.  You already have the ZS100, TZ100, and TX1 samples and you already have support for the ZS100 and TZ100 which are just different names for the TX1.  I get the distinct impression you just do not want to add the TX1 and are having fun yanking my chain.  If that is the case then just say you do not want to add the TX1.  I appreciate your work on darktable and I realize that may cause resentment since you are not getting paid for it.

**Comment by AxelG-DE** [comment]
@bakubo 
It is not my call, but I cannot help it, need to speak out, what I think.

I hope, my English is too bad to understand your irony, if any
Honestly, when I saw your post above, I felt embarrassed being a plain user of darktable and enjoy the developers efforts in creating such wonderful peace of software.

When you would scarifying a noticeable part of your spare(!) time and get a level of gratitude like what I see above, how much would you be willing to happily support?

Here and there, you can read in the internet "freeware doesn't mean it is free of each and anything, not paying for a work could mean you pay with your own contribution". As I cannot code, the least I could bring back to this society is bug reporting and trying to help other users out. That's why I also stepped into your case.

Having that said, I need to express, my **expectation to all of us** is, that we **treat** us **with reasonable respect!**

Rationally to your topic, I could imagine the following:
- your TX1 writes exactly TX1 in the EXIF
- those other models write their names in the EXIF
- as long the TX1 hasn't been recognized widely, it wouldn't work, regardless the sensor is exactly the same 
- my D750 also do not write its own name in the same manner into the EXIF. Sometimes it is d750 or Nikon D750 or just D750 and so on.... from time to time that even puzzled my basecurve module

If you want to see your camera supported soon (and soon does not mean in hours or view days), stay with @LebedevRI (as long he can control himself better than me and still want to) and accept his way of doing. Afterwards you may be proud to be part of the team who made the TX1 work.

Sincerely 
 Axel

**Comment by bakubo** [comment]
I have provided everything asked for.  If the developer does not want to add the TX1 then that is his call.  As I said, I appreciate his work on darktable.  Since he doing the work then he can choose what to do and what not to do.  It appears that he has decided not to add the TX1 even though I have given him the files requested.  Oh well.  I wish him well.  I give up at this point though.

**Comment by LebedevRI** [comment]
> I have already uploaded a complete set of 4 photos. 
> I have provided everything asked for.

Hmm, perhaps it needs to be spelled out better on the RPU itself.
Currently it is written as:
![image](https://user-images.githubusercontent.com/88600/56826159-251a2700-6864-11e9-9ddd-a144ce8fa47f.png)

A "set" is a set of the pictures, with the **exact** same content.
Three pictures with same content, and one with another content is not a "set".

This is also written in [Raw Samples Wanted](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) post:
![image](https://user-images.githubusercontent.com/88600/56826241-614d8780-6864-11e9-89ce-ec46b7bb3127.png)

I'm not quite sure how to spell it more directly, without angrying @patdavid :)

> I get the distinct impression you just do not want to add the TX1
> If that is the case then just say you do not want to add the TX1
> It appears that he has decided not to add the TX1 even though I have given him the files requested.

What gave that impression?

I have exactly zero obligation to do any of what i'm doing for the project,
neither do i have any obligation to do anything, including this camera support,
within any kind specific timeframe after the issue has been reported.
The fact that any particular issue is, or isn't, resolved within meaningful timeframe is just luck.

**Comment by LebedevRI** [comment]
I do hope someone will contribute the full sample set for that camera.

**Comment by AxelG-DE** [comment]
@LebedevRI
COOL, appropriate and necessary reaction 
:smile:
