### ISSUE TITLE
Presets: save/apply name of module (renamed modules)

### ISSUE THREAD

**Issue by althio** [darktable-org/darktable#2454]
**Is your feature request related to a problem? Please describe.**
When I apply a preset, the name of the module is undefined (just a number, incremented).
This make it difficult to copy/paste module between images, because module used for the same effect do not have always the same name. This can result in big mistakes for me when pasting settings to several images.
For good operations, I need to rename all the modules (several instances on all images), and it feels a bit time-wasting and error-prone.

**Describe the solution you'd like**
When I save/update a preset, I would like the name of the module to be included.
When I apply a preset, i would like the name of the module to be modified.

**Describe alternatives you've considered**
The name of the module could be:
- free-entry
- same as name of preset
- with numbered increments for several instances with same same

**Comment by pphotography** [comment]
**Applying a preset to a module**
I think it would make the history stack much clearer if the module gets the name of an applied style. For example, I activate the equalizer module, apply the 'clarity' preset and the module's name is 'clarity'.
Now I see in the right side of the UI and in the history what the equalizer does. Currently I  don't name every module I use since this would be too much work, but with an automated naming feature I would get much more information of what I do in a photo.

I see some details to be defined:
- If I enter a name manually and choose a preset after that, should the old name be overwritten or not?
- Same question if I choose a preset and after that another preset?
- Should the automatic name be given automatically when I choose a preset or should there be a button that sets the module's name to the current preset when I click on it?

**Comment by aurelienpierre** [comment]
So I guess the styles should have a data to store a module's name and apply it as any parameter ?

That's a good idea.
