### ISSUE TITLE
Temp File corruption after blackout

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2468]
**Describe the bug**
After a blackout Dt didn't work anymore. Luckily I got an error message informing me that something is wrong with the ``data.db.lock`` file so I deleted both in ``home/.config/``.
Nevertheless the error dialog, it was pretty shocking for a moment. 

**To Reproduce**
1. Unplug your computer  for a moment XD
2. Restart your computer
3. Start Dt
4. See error dialog

**Expected behavior**
Automatic deletion of damaged temporary files like ``data.db.lock``

**Platform (please complete the following information):**
 - OS: Mac 10.11
 - Version Dt 2.6.2

**Comment by Nilvus** [comment]
That's not possible, as .lock files prevent launching accidentally two darktable instances and are probably not damaged. darktable delete these files only when it is closed normally. That's why you have this error dialog, it let you be sure that a process of darktable is not already running to prevent database corruption if two process try to connect on your database (that would be worst). That's a security point as it lets you verify is all is ok.
Blackout you have is something exceptional so darktable (that the same for any software) couldn't do anything. That's same thing as I asking a software to save your last action just before a blackout...

**Comment by johans3** [comment]
Of course I appreciate your detailed comment but not the funny end part. 
So I repeat myself:

A) Darktable didn't start anymore
B) I got a message that something is wrong web the lock files
C) I ignored the message and tried to launch Dt 3 more times. Got always the same error message
D) finally I decided to delete this temp files with suffix "lock"
E)  Dt worked again as expected

If course this is an exceptional case but what if somebody isn't tech-savvy and can't run Dt anymore? 

Add you said, the error dialog of Dt detected a pid running Dt. The fun part is, there wasn't any Dt instance running. False positive! 

How to deal with that?

**Comment by TurboGit** [comment]
As asked by dt checking the lock files. These are there for something. The dB could be corrupted. So better let user look at this issue and possibly doing backup or restoring from backup. There is nothing automatic and safe to do

**Comment by Nilvus** [comment]
> @Nilvus
> Of course I appreciate your detailed comment but not the funny end part.
> So I repeat myself:
> 
> A) Darktable didn't start anymore
> B) I got a message that something is wrong with the `.lock` files
> C) I ignored the message and tried to launch Dt 3 more times. Got always the same error message
> D) finally I decided to delete this temp files with suffix `lock`
> E) Dt worked again as expected
> 
> If course this is an exceptional case but what if somebody isn't tech-savvy and can't run Dt anymore?
> 
> As you said, the error dialog of Dt detected a pid running Dt. The fun part is, there wasn't any Dt instance running. False positive!
> 
> How to deal with that?

The error dialog is here to alert you that you just have to check if a darktable instance is running. If yes, close it or if necessary kill the process. After that, or if there's no instance running, just check the files and if there are always here, delete them. That's all, after that you are sure that you don't have two instances running.

That's just a safe behavior for protecting database, as I said. This how to deal with that so that all but really not an issue.
