### ISSUE TITLE
Optimize loading of thumbnails in lightroom

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2469]
**Describe the bug**
If my filmroll contains 500+ images dt tries to load them as quick as possible, consequently causing an overload for my machine, the noise going up as if I'm on the accelerator of a damn Ferrari. 

**To Reproduce**
1. Choose a film roll with 500+ photos
2. Listen how much noise the creation of  thumbnails in lighttable causes

**Expected behavior**
Loading thumbnails in lightroom shouldn't take all this computing power, optimization is needed. Sometimes Dt crashes and after restarting Dt loads again the whole filmroll (which should be in cache but isn't).
I don't like not the noise nor the overload on my machine- just for some thumbnails. Why not loading thumbnails in background? 

**Screenshots**
I'll take a screenshot about the overload graph when it happens again

**Platform (please complete the following information):**
 - OS: Mac 10.11
 - Version Dt 2.6.2

**Comment by parafin** [comment]
What exactly do you mean by optimization? Throttling the thumbnail creation? I think most users would want them to be generated as fast as possible. If your system has some cooling problems, that's problem of your hardware, I'm not sure why or how it should be solved by darktable.

**Comment by Nilvus** [comment]
And launching depends on your hardware but also on some options of darktable, that you already could use, liking choosing to display reduce RAW and not integrated jpg on the RAW, if after activating the option, you close darktable and launching "darktable-generate-cache" on Terminal. Just launching it and wait that he generate thumbnails on background of all your images. It's generally faster after doing that. Of course, you have to regularly launch it after importing new images.

**Comment by TurboGit** [comment]
For lightroom issues please contact Adobe.

**Comment by TurboGit** [comment]
Anyway nothing to do here, I agree the best is to load as-fast-as-possible.

**Comment by johans3** [comment]
Anyway there's a problem with thumbnails creation as Dt builds them up even when they are updated. I saw another report which described this behaviour. 

Instead to put my report down consider that not all have the newest Os installed on their computers just because it's THE way to go.

Anyway the creation of thumbnails sucks as if I do some heavy 3d rendering. This needs optimization and isn't working  smoothly at all on Mac. I've other software who loads the same amount of thumbnails but doesn't cause any overload or noise
So it's a porting problem
No I've no problems with my hardware.

**Comment by johans3** [comment]
Porting is always a problem. I use regularly Krita (another app from Linux) which caused some overload after each brush stroke and this issue was solved after some versions. 
If you're on Linux you can't experience this errors as they are platform related. 
So laughing about other's people bug reports isn't correct just snob.

**Comment by parafin** [comment]
Describe the problem in more detail then, because here you just complaining that generating thumbnails consumes system resources and it's to be expected. There's no bug. When thumbnails are generated from RAW files it can't be lightning fast. Your hardware is too loud for you, that's basically your bug report here.

**Comment by Nilvus** [comment]
> Porting is always a problem. I use regularly Krita (another app from Linux) which caused some overload after each brush stroke and this issue was solved after some versions.
> If you're on Linux you can't experience this errors as they are platform related.
> So laughing about other's people bug reports isn't correct just snob.

So consider also these things :

- If you don't precise which hardware you use, that's not help if you talk about performances/optimization.
- As you said, "not all have the newest Os installed on their computers just because it's THE way to go.". And not all who have an oldest OS or even a not really powerful hardware have your issues. Performances and optimizations depend on lot of things (for each software that need more performances than a simple navigator for example) like hardware, OS, some tweaks sometimes or even good use (or not) of the software. And since, we could find an infinite of configurations with that, that something difficult.
- darktable is free and open source software and there's no company behind, just developers who spend their free time.
- darktable is a Linux software so yes, it's better on Linux as it is at first develop for this OS. And for MacOS port, as I know, there's only one or two developers...
- I've used darktable on MacOS with same hardware (Macbook pro 13" fin 2013 with just an Intel graphics card, so no OpenCL) and yes it was a little slower on Mac than now on Linux, but it was usable.
- As I know, I'm quite sure that better performance on Linux is also because Linux is a more faster and optimized OS. For example, for same using, Linux use 8 Go of space disk for OS and apps like MacOS was using 24Go. And memory usage without just my environment desktop on Linux use just a little more than 1Gb, like MacOS was approximately 2 to 3 times more...

So maybe porting could be improved but that's not so easy, except if some new developers help on it. That's also the matter of porting...

One truth I could say : most of the time, using the OS for which a software is at first made is one of the better solution.
