### ISSUE TITLE
no histogram in tone curve until reset

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#2506]
**Describe the bug**
When editing the tone curve, the histogram that was usi=ually visible as a backdrop is missing.

![screenshot TQdpozyZxZ](https://user-images.githubusercontent.com/16781735/57092244-3d2df280-6d0b-11e9-8637-48a26ff18b27.png)

The histogram will show up when resetting the tone curve by clicking on it's ⏼, but not when resetting it with a double click on the curve.  Changing the color space, or choosing a preset has no such effect.

After going to lighttable and back to darkroom, the histogram is missing again.

**To Reproduce**
1. open image in darkroom
2. open "tone curve" module

**Expected behavior**
Always show histogram in tone curve module, or at least while it is switched on.

**Platform (please complete the following information):**

  * current ArchLinux
  * no desktop environment (plain X11 and FVWM)
  * darktable 2.7.0+1087~g7fe35d67d

**Comment by Nilvus** [comment]
It also show up if you select one option on drop-down just below the graph.

**Comment by Nilvus** [comment]
Have you tested new rgb curve tone module ? Maybe it will be better and doesn't have this behavior.

**Comment by s5k6** [comment]
Nilvus (2019-May-19, excerpt):
> Have you tested new rgb curve tone module ? Maybe it will be better
> and doesn't have this behavior.

Yes, "rgb curve" does not show this problem.  What's the difference
between the two?  I could not find docs for "rgb curve", I did not
even know it existed.


-- 
http://stefan-klinger.de                                        o/X
I prefer receiving plain text messages, not exceeding 32kB.     /\/
                                                                  \

**Comment by Nilvus** [comment]
> Nilvus (2019-May-19, excerpt):
> Have you tested new rgb curve tone module ? Maybe it will be better and doesn't have this behavior.
> Yes, "rgb curve" does not show this problem. What's the difference between the two? I could not find docs for "rgb curve", I did not even know it existed.

rgb curve was merged on the second part of march and it's a tone curve in rgb mode. So maybe use it instead of tone curve. On the PR was discussed the fact to have a rgb curve with actual tone curve or having an improving tone curve (on Lab mode) with a rgb mode added. Merging new rgb curve was done but I don't know if tone curve will be update to also have a rgb mode (it doesn't seems necessary now). The PR to add this is always on but not updated since a time (see on bottom page of pull requests).

So I think you could :
1) ask pweyland on his pull request if he will continue his PR (and in that case if he could resolve this issue by the way)
2) close this issue and use rgb curve

**Comment by s5k6** [comment]
Nilvus (2019-May-19, excerpt):
> > Nilvus (2019-May-19, excerpt):
> > Have you tested new rgb curve tone module ? Maybe it will be better and doesn't have this behavior.
> > Yes, "rgb curve" does not show this problem. What's the difference between the two? I could not find docs for "rgb curve", I did not even know it existed.

> rgb curve was merged on the second part of march and it's a tone
> curve in rgb mode. So maybe use it instead of tone curve.

I'm very happy with tone curve.

> On the PR was discussed the fact to have a rgb curve with actual
> tone curve or having an improving tone curve (on Lab mode) with a
> rgb mode added. Merging new rgb curve was done but I don't know if
> tone curve will be update to also have a rgb mode (it doesn't seems
> necessary now). The PR to add this is always on but not updated
> since a time (see on bottom page of pull requests).

My tone curve (darktable 2.7.0+1154~g1ea1ab272) does have RGB
channels.

> So I think you could :
> 1) ask pweyland on his pull request if he will continue his PR (and
> in that case if he could resolve this issue by the way)

Whom to ask?  I could not find a `pweyland`.  Which PR?  A URL would
be awesome.

> 2) close this issue and use rgb curve

I won't close the issue while tone curve shows this behavior.

If tone curve is to be replaced by rgb curve, then there should be a
transition to convert the history stacks of images containing tone
curve to equivalent settings in rgb curve.  Otherwise, there's a buggy
module.


-- 
http://stefan-klinger.de                                        o/X
I prefer receiving plain text messages, not exceeding 32kB.     /\/
                                                                  \

**Comment by Nilvus** [comment]
> My tone curve (darktable 2.7.0+1154~g1ea1ab272) does have RGB channels.
I forget that, I now prefer rgb curve so I don't use tone curve since more than a month.

> Whom to ask? I could not find a `pweyland`. Which PR? A URL would be awesome.
Heu, ok I forgot a letter (it's phweyland) but that's difficult to read the title of 17 lines (actual number of PR on a tab in the beginning of this page and find which one talk about tone curve and where the autor is near the name I write ?
Anyway, as I've just answer on this PR, I have referenced your issue...

> 2) close this issue and use rgb curve
> I won't close the issue while tone curve shows this behavior. If tone curve is to be replaced by rgb curve, then there should be a transition to convert the history stacks of images containing tone curve to equivalent settings in rgb curve. Otherwise, there's a buggy module.

That was only suggestions and tone curve will not be replaced so removed, that's not how darktable works. A module could become deprecated if another added is better but it will remain available on the module list.. By now, compatibility to avoid having converting stacks of images as you say remains a principle of darktable.

**Comment by Nilvus** [comment]
See #2636

**Comment by Nilvus** [comment]
@TurboGit : this issue was solved by last PR. So to be closed. Thanks !

**Comment by TurboGit** [comment]
Closing, thanks.
