### ISSUE TITLE
Please add high DPI support (e.g. for 4K monitors)

### ISSUE THREAD

**Issue by mikeweilgart** [darktable-org/darktable#2578]
I've just installed darktable 2.6.2 on my MacBook Pro running 10.11.6.  I have a 4K monitor plugged in with the "scaled" option selected in the "Display" preferences.  Everything in darktable is unreadably tiny.

It would be very nice to have hi-dpi support for darktable.  For now, it can only be used on a non-hi-res monitor.

**Comment by TurboGit** [comment]
This should be supported in next major release.

**Comment by parafin** [comment]
Why next? It already works.

**Comment by homer3018** [comment]
How tiny ? I also have it running on my mac on a 5k display, and it's very readable, as in it's uite big as if it's just the 1920x1080 resolution that has been scaled up. So quite the opposite of what you describe...
Could you please share a screenshot ? What resolution are you using precisely ?
@TurboGit Or maybe it's because 2.6.2 does not have the complete CSS interface ?

**Comment by leclercj** [comment]
With darktable 2.6.x the trick is to tweak the screen_dpi_overwrite parameter in .config/darktable/darktablerc file
For 4K display, try to replace `screen_dpi_overwrite=-1.0` (default value)
by `screen_dpi_overwrite=180` or `screen_dpi_overwrite=200`,
then restart darktable
