### ISSUE TITLE
tagging causes image to export corrupted

### ISSUE THREAD

**Issue by insidebitrunner** [darktable-org/darktable#2651]
![20190503_0001_bw](https://user-images.githubusercontent.com/43019029/58751703-0c5aed80-8470-11e9-92ef-95e68ed03024.jpg)
When adding tags to an image in lighttable and then exporting the image causes the image to go completely dark when the image is black and white

**Comment by Nilvus** [comment]
Which version of darktable ?
Which OS and version you use ?
Add an image who have this problem and the xmp will also help.

Quite difficult for the developers to help with so less informations...

**Comment by insidebitrunner** [comment]
OS is ubuntu 18.04
darktable version is 2.4.2-1

**Comment by insidebitrunner** [comment]
ubuntu 18.04
version 2.4.2-1
github won't let me upload xmp fille

**Comment by Nilvus** [comment]
No more necessary (and not possible with github, that needs to you use a cloud drive and share link) if you use such an older release. darktable is now on 2.6.2 so please update before sending an issue. Maybe this issue is now solved.

To update to 2.6.2, you have two w,ay (by adding ppa) that's explained here : https://www.darktable.org/install/#3rdparty

Test with an updated release and see if it's solved or not. If not, feel free to post a new issue with the most precisions possible.

By now, please close this one (or @TurboGit)
