### ISSUE TITLE
New slider for growing and shrinking drawn masks, in the mask manager

### ISSUE THREAD

**Issue by lolluslollus** [darktable-org/darktable#2669]
Darkroom: every module with masks: apply a path mask (or any type of drawn mask), then try to grow it or shrink it. It can be kludgy at times.
Why not add an option for growing and shrinking a drawn mask, with two sliders?

This happens in the windows and the ubuntu version, 2.6.2 and 2.7.

**Comment by eGax** [comment]
How many sliders are too many because there are a LOT already taking up space? I find it far from _"kludgy"_ to hold the alt or shift keys and scroll the mouse wheel to grow/shrink the mask or feather size. It's actually very quick, smooth and convenient without adding more on screen control clutter.

As it is now on my 1920x1080 display using the color correction, color zones, or equilizer modules for instance, using a drawn and parametric mask the whole module doesn't even fit in view. You have to scroll up and down to change settings at times. Now **_that_** is _"kludgy"_.

**Comment by lolluslollus** [comment]
Every feature should have its UI controls, the keyboard shortcuts are nice but they should not exist without a visible, touchable counterpart. It's standard good practise in commercial software.
If you don't want to add more sliders where they are now, why don't you move all the mask refinement controls into the mask manager? This way, you'd free up more space in the right pane, which is already cluttered.
Alternatively, you could display instructions to illustrate the shortcuts. They do appear today, but only sporadically, and they don't describe all available shortcuts. As a consequence, the user must resort to the online documentation, just to remember a couple of essential shortcuts: doable, but not really state of the art.
This is no bashing: I really like darktable and I would like it to be perfect.
