### ISSUE TITLE
magnetic lasso

### ISSUE THREAD

**Issue by lolluslollus** [darktable-org/darktable#2670]
Darkroom: every module with masks: apply a path mask, then try to follow a contour. It would be nice to have something like Photoshop's magnetic lasso to make this easier. This could make me miss the magic wand less, too.

This happens in the windows and the ubuntu version, 2.6.2 and 2.7.

**Comment by urcindalo** [comment]
I second the proposal. It would be a quantum leap in mask application :)

**Comment by aurelienpierre** [comment]
So I guess that would use an image segmentation on top of a Sobel filter ? The issue here would be that drawn mask are vectors in darktable (their nodes being stored in the database), while the lasso produces a raster mask, generally not vectorizable and not storable in the database. 

I have never used magnetic lassos, to be honest, I have always found their result to be random and behave poorly with bokeh/background blur. 

Meanwhile, you can use the drawn mask with a large brush (no need to be super accurate) and use the mask edge refinement (guided filter).

**Comment by urcindalo** [comment]
> Meanwhile, you can use the drawn mask with a large brush (no need to be super accurate) and use the mask edge refinement (guided filter).

Oops! I wasn't even aware of that option :( Thanks for the suggestion.
You mean this, right? https://github.com/darktable-org/darktable/pull/1809

It's actually very similar :D

**Comment by aurelienpierre** [comment]
yes
