### ISSUE TITLE
Support AVIF

### ISSUE THREAD

**Issue by benkuly** [darktable-org/darktable#2682]
**Additional context**
AVIF could be the jpeg successor.
See https://github.com/AOMediaCodec/av1-avif

**Comment by 1div0** [comment]
We have two options.

1. there will soon be AVIF support in [libheif](https://github.com/strukturag/libheif), LGPL3 licensed library.
2. [libavif](https://github.com/joedrago/avif), BSD licensed library.

**Comment by Entropy512** [comment]
Of those two, my preference based solely on technical aspects (it *appears* that there are no licensing issues with either?) would be libheif - since that fundamentally supports other compression algorithms in HEIF.

I long for the day where smart TVs support HEIF files with the HLG transfer curve instead of having to encode stills into 10-bit HEVC video to get my TV to enter HDR mode...

**Comment by GLLM** [comment]
Bumping this one up, as it seems Canon will soon support HEIF in their high-end models (https://petapixel.com/2019/10/31/canon-has-moved-on-to-heif-but-wont-ditch-jpeg-completely-yet/)

**Comment by aurelienpierre** [comment]
Heif support is WIP with @darix and @cryptomilk

**Comment by cryptomilk** [comment]
It would be nice to have avif in libheif, but it seems the project isn't really moving.

**Comment by darix** [comment]
heif uses HEVC/x256 as code. which has patent problems for distributions.

**Comment by cryptomilk** [comment]
I've implemented AVIF support as the developer is very helpful and fixes bugs quickly. However it doesn't fully work yet. It displays the image but it looks not correct.

My WIP tree is:

https://github.com/cryptomilk/darktable/tree/master-avif

**Comment by cryptomilk** [comment]
@TurboGit this can be closed :-)

**Comment by TurboGit** [comment]
Closing !
