### ISSUE TITLE
Color picker samples are not square

### ISSUE THREAD

**Issue by Benja1972** [darktable-org/darktable#2687]
**Describe the bug**
Color picker samples are not square

**To Reproduce**
Select several color and Add to samples

**Expected behavior**
Color picker samples are squares

**Screenshots**
![ColorPicker](https://user-images.githubusercontent.com/11920879/59068330-294e5100-88b4-11e9-90ac-790f17b3604b.png)

**Comment by Nilvus** [comment]
That's fixed since this commit by @TurboGit : https://github.com/darktable-org/darktable/commit/8120c7a6850fe63c4d61f94185bf561ba2266861 and some adjustments following by me on CSS with that PR : #2586 (see #live-sample-data tag on the end of darktable.css). So since about 20 days.

So two options here :

1) You don't update recently your master, so please update master
2) You have a problem on CSS you use (so not default css)

Please see that and be sure to use last master update and default css.

**Comment by Nilvus** [comment]
I just see your feature request about color picker and see that you use a quite recent update so that's just a css issue (not about default one which works great).

So you that clearly means here that you don't have the css as it is delivered on actual master. The CSS you use should use these tags :

`#live-sample
{
    padding: 1pt;
    min-height: 1em;
    min-width: 3em;
}

#live-sample-data
{
   font-family: courier;
   font-weight: bold;
}`

First tag is about making samples as squares and not lines, second part to have more readable text. So be sure to update or modify your css. By default, all works great. I made a test some few minutes ago with all default CSS (with last master revision).

![Capture-20190607192407-309x397](https://user-images.githubusercontent.com/45535283/59122002-daf38d80-8959-11e9-8e42-79a7e4fcc9dc.png)

**Comment by Benja1972** [comment]
Thank you I will try and check. I have master brunch with theme 'darktable-elegant' with was shipped with darktable but which is not default

**Comment by Benja1972** [comment]
With default it works fine. So the issue is with darktable-elegant theme and probably others alternative themes shipped with darktable

**Comment by Nilvus** [comment]
So you probably have a mistake on alternatives css as with default ones I've updated with previous PR, I don't have your issue. Could you share your css folder (default one and if you have user one) ?

**Comment by Benja1972** [comment]
OK, thank you. I remove all user defined themes and now even with darktable-elegant it works fine. We can close issue

**Comment by Nilvus** [comment]
> OK, thank you. I remove all user defined themes and now even with darktable-elegant it works fine. We can close issue

Great. so please close it (you have the possibility). I dont have rights for that.
