### ISSUE TITLE
[Feature request] Color picker enhancement 

### ISSUE THREAD

**Issue by Benja1972** [darktable-org/darktable#2688]
I have come to one idea to make Color picker (left hand module) more practical and interactive. 
Look what we have up to now.
![ColorPicker2](https://user-images.githubusercontent.com/11920879/59069935-2efa6580-88b9-11e9-8de1-acb59082190d.png)

We can select areas, save them and show on picture. But we cannot reuse them.  Fro example in parametric mask we have color-picker and plus-color-picker. Both of them can be used to select area. So I would propose to make possible use this areas for color picking of ranges. 

Why it is important. Before dive to retouching of image it is convenient to analyze it and pre-select areas of interest, by color or by lightness ranges etc. After then all predefined ranges can be easily used for parametric masking.

PS This is one of improvement and modification that I have for color picker. I try to present them slowly, following discussion.

**Comment by aurelienpierre** [comment]
The problem is the global color picker works at the end of the pipeline, while the parametric blending needs the intermediate values, in-between the modules, which can be quite different from the final ones.

Notice that parametric blending already has such color pickers embedded, but they are not dynamic (their values depend on the output of the lower modules and will not be updated if lower modules parameters are changed).

I don't think the current pixel pipeline design allows for this easily with reasonable performance. That would be something to change in the future.

**Comment by Benja1972** [comment]
Can we reuse same areas? Not settings. What I mean, when I use plus-color-picker in parametric mask it will take latest rectangular area in use automatically. So If we can just click on predefined areas to pick values (min,max) from them? Do we need every time re-draw rectangles?
