### ISSUE TITLE
Snapshots: naming, identify and zooming

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2694]
**Is your feature request related to a problem? Please describe.**
I have some difficulties identifying snapshots. Actually, I forgot often which is the snapshot and which is the picture (especially when I rotate upside-down the middle line).
I'd like the possibility to rename the snapshot as I can rename the iop modules on the right.

**Solution you'd like**

I'd like to have:

- The possibility to assign a name to the snapshot
- The snapshot's name superimposed to the image and something like "original" on the other part.
- The possibility to zoom in and out both part of the image (depending on where the mouse pointer is)

**Alternatives I've considered**
It seems there is not a real alternative so far. The only way seems to switch on/off the snapshot button.

**Comment by GwenaelQ** [comment]
Hi everybody, 

I was about to create a new bug report when I saw that this one was already here. I think that what follows is very near (perhaps exact duplicate) of what is said above. 

**Describe the bug**

Zooming or moving in the darkroom view with the image splitted "before/after" (snapshot feature) will  be ineffective in the snapshot "half" of the image
 
**Expected behavior**

When zooming or moving in the darkroom view with the image splitted  (snapshot feature), the user expects that the two "halves" stay "connected".

Furthermore, +1 for the suggestion of naming snapshots and identifiing the parts of the image.


**Platform (please complete the following information):**

 - Darktable Version: 3.0.1 
 - OS: Windows 8.1



Thank you for listening

**Comment by elstoc** [comment]
I sometimes click to rotate the dividing line on a snapshot and forget which is which

**Comment by GwenaelQ** [comment]
> Perhaps just a visual indicator on the dividing line itself might be enough?

It seems to be a good idea.

> Zooming would be harder because the snapshot is basically just an image taken at the current preview scale. You could maybe zoom but it would be much lower res than the other side.

I didn't imagine that snapshot was to be taken in such a literal sense ! It is really not conceivable to imagine a part of the image calculated in one way and other part calculated in another way when zooming ?
Anyway, that's a minor issue so no need to spend a lot of time on it. Your solution is better than nothing :-)

Thank you for the  reply !

**Comment by chakflying** [comment]
I really want to see at least zooming implemented, since the Before/After in Lightroom is so much better and comfortable to use. But as someone who hasn't written C in years I don't imagine I can tackle this easily. Has there been discussion about how to implement this? Would snapshots need to have the current history stack attached to them? Can the view even support zooming while in split view?

**Comment by elstoc** [comment]
The only way I know to do this is similar to how the duplicate manager works but this method never produces quite the same image as that in the darkroom view. I'm not sure how easy it would be to implement zooming in snapshots without losing the visual fidelity of the snapshot version of the image.

**Comment by shockergit** [comment]
> 
> 
> I really want to see at least zooming implemented, since the Before/After in Lightroom is so much better and comfortable to use. But as someone who hasn't written C in years I don't imagine I can tackle this easily. Has there been discussion about how to implement this? Would snapshots need to have the current history stack attached to them? Can the view even support zooming while in split view?

Its also better in Rawtherape
