### ISSUE TITLE
Temporarily disable all modules after active one in Darkroom

### ISSUE THREAD

**Issue by wilecoyote2015** [darktable-org/darktable#2715]
**Is your feature request related to a problem? Please describe.**
When performing complex image edits, a large amount of modules may be used.
Hence, the preview in Darkroom may become very slow and unresponsive.
Consider the following case:
When retouching a portrait, multiple instances of Equalizers, Liquify and Retouch may be used. 
Those modules exhibit high demands on processing power, so that the whole pipeline may need around 10 seconds to process on an average computer.
If changes to the last of those modules in the processing pipeline are made, editing is still responsive because the module's input from previous modules is cached, so that only the active and  the following modules are reprocessed.
If changes to a module earlier in the stack are made, however, the preview becomes very unresponsive.

Often, I encounter the situation where I need to tune a module that is positioned relatively early in the pipeline. In those situations, there may be no need to see the effect of the modules following in the pipeline, so that I disable all following modules by hand in order to obtain better performance on the preview.

**Describe the solution you'd like**
I believe it would be useful to have a switch in the UI that, only for the darkroom, disables all non-mandatory modules (so except e.g. output profile) in the pipeline after the active module.
At the cost of not seeing the final result, it provides a significant improvement in preview performance for tuning the active module's parameters. 

**Describe alternatives you've considered**
The only currently available option is to disable all modules after the active module by hand and then re-enable them.

**Comment by pphotography** [comment]
I share your thoughts and ideas. Removing 'all' other modules than the current one would lead to some problems:
For example 'White Balance'. You modify the camera's white balance settings. After that you continue with a color module and disable 'all other' modules. What about the value of your color corrections without the final white balance?

Think that the problem is the definition of 'non-mandatory' modules which I did not found so far.

Currently for most of my images I manually disable some modules temporarily. For example, I denoise and sharpen the image and turn off the modules used for that. For final export I reactivate them.

I put images with more complex edits (portraits for example) in a separate folder. I do basic edits like white balance, brightness, colors, sharpen and denoising and export the result as a TIFF in the same folder.
After that I continue work on the TIFF (like retouching) and copy the history stack to the original image in 'append' mode. This keeps the rendering times low and I don't lose my history stack.

Think that there should be a button that lets darktable render the current history stack and use this temporary image as a basis for upcoming edits (similar to the 'snapshot' function).

**Comment by wilecoyote2015** [comment]
Thanks for your input!

> Think that there should be a button that lets darktable render the current history stack and use this temporary image as a basis for upcoming edits (similar to the 'snapshot' function).

In fact, AFAIK Darktable does something like this:
When changing the parameters of the activated module (and, given opencl is used, opencl_synch_cache is set to active module only), the active module's input is buffered, so that insufficient performance in preview depends largely on the modules being processed in the pipeline *after* the active module.
Hence, the idea is to disable those modules.

> I share your thoughts and ideas. Removing 'all' other modules than the current one would lead to some problems:
> For example 'White Balance'. You modify the camera's white balance settings. After that you continue with a color module and disable 'all other' modules. What about the value of your color corrections without the final white balance?

I'd propose to only disable the non-mandatory modules being processed in the pixel pipeline after the active one. Accordingly, it is hard to imagine a realistic use case where the white balance module would be disabled.

>Think that the problem is the definition of 'non-mandatory' modules which I did not found so far.

Hmm yes, I guess that is not trivial.
As an initial guess, I'd propose the following modules:
- raw black/white point
- white balance
- demosaic
- output color profile
- input color profile

**Comment by aurelienpierre** [comment]
Better than disable the last ones, it should be mor clever to run the first ones for full size, cache the result, and interpolate the region of interest instead (one interpolation takes 15 to 50 ms, depending the CPU).
