### ISSUE TITLE
Culling : limited development copy/paste option

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#2718]
**Describe the bug**
On culling mode, copy/paste development on an  image to another is most of the time only limited to first image displayed (first image on the left)

**To Reproduce**
1. Go to 'culling mode on lighttable' and have, for example 2 images displayed side by side
2. Click on 'left image'
3. Press CTRL+C to copy development style
4. Move cursor to have focus on second image
5. Press CTRL+V and see that nothing happen on this second image.
If after step 3 you move to two other images and try CTRL+V, you will see that the pasting is applied to the left image, even if it's the second image have the focus.

**Expected behavior**
Possibility to apply copying and pasting development on the image who have the focus.

**Platform (please complete the following information):**
 - OS: Ubuntu disco (19.10)
 - Version : darktable master ca5f223e558038df0b86bdc1dae8ba98fe236cfe

**Comment by AlicVB** [comment]
just tested, and it seems not limited to culling. In fact pasting (and copying ?) doesn't seems to follow dt selection rule here, even in filemanager...
I will have a look in the code.

**Comment by AlicVB** [comment]
so, reading the code, everything in image development actions (copy, paste, delete, ...) seems to work like that : 
- if there's some images selected => apply on the selection
- else apply on the mouse_over image

This is not consistent with how rating, color labels, ... works : 
- always apply to mouse_over image except
- if mouse_over is inside a selection : apply to the whole selection
- if mouse is outside the view : apply to the selection if any

If you want my opinion,
1. this is an inconsistency in how dt behave, and we should avoid that => change how development action is applied to respect the rest of the ui behavior
2. development actions are here since a long time and users are used to that behavior => don't touch anything...

(I know it can become really hot topic and I hate that)

**Comment by Nilvus** [comment]
So that means some UI inconsistency and that the way darktable goes actually : correct Ui inconsistency. The UI works was a step, pipeline changes made, correct some colors behavior, etc...
Maybe it's an hot one but we prepare the future with changes made on that master so it's probably the best time to correct that inconsistent behavior.
We even had recently some comments saying that some choices means a bad UI (for some shortcuts for example).

I think propose the most consistent UI darktable ever had would also be a great improvement for next release.

Anyway, this behavior could be quite usable on file navigation mode but quite annoying on culling mode as when you scroll down to next images on culling mode, having the possibility to apply a development style on mouse_over image is not possible as the user want.

**Comment by AlicVB** [comment]
I agree with you, and I'll try to come with a PR in the week-end (rainy days ahead)
