### ISSUE TITLE
crop and rotate not activated properly

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#2776]
**Describe the bug**

Crop and rotate does not start in editing mode when switching between
image modes in darkroom.  Clicking ⏻ may not activate it.

**To Reproduce**

In "⚙/shortcuts/views/darkroom", make sure `Page Up` is bound to
"image back", and `Page Down` is bound to "image forward".

Open an image in darktable, which is **not** the first one in the
collection.  Make sure its "crop and rotate" module is disabled.

Hit `Page Up` to go to the previous image.  Open the "crop and rotate"
module, and change the crop by dragging the borders to reduce the
field of view.

Hit `Page Down` to go to the next image.  Good: The "crop and rotate"
module is expanded, but inactive.  Click its ⏻ button to activate it.
Bad: There will be no crop frame on the image in the middle that could
be dragged around.  Expected: A crop frame on the image in the middle
that could be dragged around.

Click its ⏻ button two more times.  The expected crop frame will show
up and allow to change the crop.

Hit `Page Up` to go to the previous image again.  Good: The "crop and
rotate" module is expanded and active.  Bad: The image is shown in
cropped state.  Expected: The full image with a crop frame that could
be dragged around.

Click its ⏻ button two more times.  The expected crop frame will show
up and allow to change the crop.

**Expected behavior**

When switchin images in darkroom with "crop and rotate" active, the next image should present "crop and rotate" in editing mode it it's active, or should activate it by pressing ⏻ if it's not active.

**Additional context**

Maybe this is related to #2618.

**Platform (please complete the following information):**

  * current ArchLinux
  * no desktop environment (plain X11 and FVWM)

    $ git describe
    release-2.7.0-1516-g319ee172c

**Comment by amousset** [comment]
Could not reproduce on current master (even with PageUp/PageDown for switching images).

**Comment by s5k6** [comment]
The problem persists.

**Comment by elstoc** [comment]
Reproduced on current master (ArchLinux). Possibly related issue: if you expand the crop/rotate module with a keyboard shortcut, the grid is enabled and you can crop with the mouse. If you collapse the module with the same shortcut, the grid is still enabled and you can still crop with the mouse. This is not the same behaviour as when you expand/collapse by clicking on the module header.

Crop/rotate is a bit of an odd module in that it's sort-of semi-activated when you expand it so I'm not surprised there are some strange effects. I'll take a look and see what I can see.

**Comment by elstoc** [comment]
To clarify - I tried to fix this issue in the PR above and then decided against it because solutions to the issues with Crop & Rotate aren't simple. I ended up just fixing the 'extra' issue I added in the comment above because that _was_ simple.

The problem is that the Crop & Rotate module activates its guides and crop tools when it is given focus and not when it is activated. The module can be activated and/or expanded without having focus, and this is indeed the state it's left in when you complete a crop and then double-click the image to commit the change. So, when you navigate to the next image in the darkroom it's not entirely clear whether the guides and crop tools _should_ be available or not.

I agree that it doesn't make sense that you have to click twice to reactivate it, though if you can find a bit of the widget without a slider or a drop-down you can click on that to give it focus and re-enable the tool.

The only neat and consistent solution I can think of is to add a show/hide button to all module headers and change so that when you click on the header it instead gives focus to the module. But then 'focus' only makes sense for a few of the modules and only does things in an even smaller subset. A solution specific to the crop&rotate module would be to add a button to re-show the guides, that could be associated with a keyboard shortcut, though that button wouldn't really have to do anything since just clicking on it will give focus to the module.

None of these are particularly nice solutions. Anyone have any other ideas?

**Comment by dreamcat4** [comment]
thanks for explaining these details. it seems this feature still needs more work on it in the future. because one particular thing i noticed today is that the crop module itself cannot actually focus when you click on it's entry after adding into the new quick access panel feature

so i am wondering now (since it's so challenging), why not create a separate button within the crop module controls. which then manually toggles on/off the guides etc. So it could simply be called `edit` or `set` or `guides toggle`. Or whatever you prefer. And then also rename the existing `guides` control --> `guides type`. To make the distinction between those 2 controls a bit clearer.

What do you think? Sorry I know this should be a seperate issue. But I just wanted to check here before raising the new issue. If it was in fact a reasonable suggestion. Because there seems to be different ways for which this feature could be improved. Many thanks for previously looking into this

**Comment by elstoc** [comment]
Could do. Raise a separate feature request and we can discuss.
