### ISSUE TITLE
[Feature request & Issue] Make snapshots adjustable

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#2784]
**Is your feature request related to a problem? Please describe.**
Snapshots are a great feature to compare image but actually this feature have an important lack : snapshot are not adjustable. For example, with the actual master, you have possibility to hide panels around the image. If you select and make snapshot (with left panel visible) and then hide this panel, the actual image is adjusted in the image frame but not the snapshot. See image below to what darktable show when you do that :

![capture](https://user-images.githubusercontent.com/45535283/61172889-af347a80-a58b-11e9-9b89-73954691f234.jpg)

So actually, we can't always compare differents steps of history as it should.

**Describe the solution you'd like**
Having the snapshot following how the "normal" current state of the image is shown in darkroom and especially by adjusting is rendering the same way (size, place, etc.).

**Comment by Nilvus** [comment]
Still wanted

**Comment by johnny-bit** [comment]
Users want it: https://github.com/darktable-org/darktable/issues/9260 :)

**Comment by elstoc** [comment]
How practical is this to do though? 

The snapshot module is currently the only guaranteed way to get a 1:1 comparison between darkroom edits, because it's a direct copy of the darkroom center view. In order to achieve this with resizing / zoom we would need to either generate and save a full resolution copy of the image or find some way to run two darkroom pixelpipes in parallel (I don't think this is possible). Note that the duplicate module tries to do something similar, but it has limitations because it uses a different method to process the image than the darkroom pixelpipe - I still get odd artifacts when using the duplicate module to compare and I wouldn't want to replicate those issues here.

**Comment by johnny-bit** [comment]
I have had several ideas that could benefit both snapshots & duplicates but would require running parallel pipes or delegated pipes or whatever you call it.

eg for snapshots: do "screenshot" of current pipe and then start low-prio backgroud pipe run for snapshot to cache. once done if user does any movement/adjustment follow the adjustment in main img in snapshot one.

similarly for duplicates.

One could then use cached runs (if of good enough quality) as a way of quick export if eg snapshot done IS the current image history.

Obviously all that is super hard.

**Comment by yaitskov** [comment]
Do refactoring and remove global variables ;)
