### ISSUE TITLE
Scrolling to change brush feather size on MacOS not working with non-Apple mouse

### ISSUE THREAD

**Issue by tylerhenthorn** [darktable-org/darktable#2786]
**Describe the bug**
This may be related to https://github.com/darktable-org/darktable/issues/1977. Scrolling the mouse wheel in either direction to change the mask brush feather size will decrease the size of the feather. The issue happens when using a non-Apple USB mouse, but is not present when using the Macbook's trackpad, or when using the Apple Magic Mouse. 

**To Reproduce**
1. Open a CR2 file in darktable
2. Create a new mask and select the brush tool
3. Hold shift and scroll the mouse wheel in either direction

**Expected behavior**
Scrolling the mouse wheel in one direction should increase the brush feather size, and scrolling in the other direction should decrease it. 

**Platform (please complete the following information):**
 - MacOS Sierra 10.12.6 (16G2016)
 - MacOS Mojave 10.14.1 (18B75)
 - darktable 2.6.2
 - non-Apple USB mouse

**Additional context**
[darktable_all.log](https://github.com/darktable-org/darktable/files/3390816/darktable_all.log)

**Comment by dartemisia** [comment]
@tylerhenthorn >>> Are you saying that Shift + scroll only _decreases_ the feather size, regardless of which direction you scroll? I'm just checking because most people seem to report the inverse: that Shift+scroll only _increases_ feather size (as in #1977).

**Comment by tylerhenthorn** [comment]
@dartemisia the inner circle grows to meet the boundary of the outer circle.

**Comment by dartemisia** [comment]
@tylerhenthorn I'm a bit puzzled by your description, so forgive me if I try to say what I see as clearly as I can. Let's say I'm using the exposure module, and I select 'drawn mask' from the blend options. And let's say I then select a circular mask, and click on the picture where I want to apply this, to set the mask position. 

When I then hover the mouse over the mask, I see two concentric circles: one displayed as a thick line, which is the mask itself; the other shown as a dotted line, outside the thick line, which indicates how far the feather region extends beyond the mask. Now, lets just talk about increasing sizes...

If I place the mouse on the mask and just scroll, the diameters of both circles increase in unison, so the distance from the thick line to the dotted line remains constant as both the circles increase in size. In other words, the mask gets bigger, but the distance over which the feathering occurs does not - it stays the same distance from the mask.

But if I hover the mouse over the mask, press the shift key and then scroll, the thick line doesn't move, but the dotted line moves away from it, as the dotted circle gets bigger. In other words, the mask stays the same size, but the feathering distance increases.

However, if I scroll in the opposite direction, both of these procedures should produce a _decrease_ in size: the simple scroll will decrease the size of the mask, and keep the feather the same distance from it as both get smaller together. Shift + scroll will keep the mask's thick-lined circle the same size, while the dotted line moves towards it — and if I keep on scrolling, the dotted circle meets and merges with the thick line of the mask circle, so that there's no feather at all, and the mask has a hard edge.

On my Mac, the problem is that Shift+scroll only makes the dotted line move away from the solid line, regardless of the direction I rotate the scroll wheel. So the feather always just gets bigger.

Apologies if my description comes across as very pedantic, but it's hard to describe time-based motion in writing! I hope I've described clearly what I see happening. Is it what you see?

**Comment by tylerhenthorn** [comment]
@dartemisia the behavior with the circle tool is exactly as you describe. The behavior with the brush tool is as I described above.

**Comment by dartemisia** [comment]
I'm intrigued that you find you can only decrease the size of the feather for the brush tool. On my system, scrolling in either direction only increases it. Strange!

(I'm in discussion over on issue #1977 with @edgardoh about scrolling with and without key modifiers. You might be interested in taking a look, and perhaps contribute your observations. )

**Comment by dartemisia** [comment]
@tylerhenthorn >>> BTW, did you manage to try your Apple USB mouse? I think that information on how that works for scroll, Shift+scroll and Ctrl+scroll with Masks, Brushes, Tone Curve nodes and Zooming would be very enlightening.

If you have the time, please see my observations here:
https://github.com/darktable-org/darktable/issues/1977#issuecomment-511818084

**Comment by tylerhenthorn** [comment]
I do not have an Apple USB mouse. I have tested on these devices: 

non-Apple USB mouse: broken
Apple Magic Mouse (Bluetooth): working
2016 15-inch Macbook Pro integrated trackpad: working

**Comment by dartemisia** [comment]
> I do not have an Apple USB mouse. I have tested on these devices:

Sorry, I don't know how I got the idea that you had. Anyway, no worries, as the devs have been investigating the issue over on https://github.com/darktable-org/darktable/issues/1977. They seem to have worked out what's going on, and how to fix it; and if they can get the fix tested, it may be incorporated into the 2.7 release. :)
