### ISSUE TITLE
Darktable 2.7 → Lighttable buttons

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#2859]
**Describe the bug**
Lighttable buttons width of "tagging" is not consistent with other tabs like "metadata".

**Expected behavior**
Make them of all wide or small

**Screenshots**
![lighttable_size](https://user-images.githubusercontent.com/53873917/63072654-8c500a00-bf2d-11e9-8496-418c78275767.png)

**Comment by Nilvus** [comment]
This depends on GTK widgets used and GTK is not so adjustable. You can see that fields and buttons around are not the same so that's a reason they're not so consistent. Widgets are not the same so how they react are not the same. They also use relative sizes (relative of parent widget) and they can't be on fixed sizes, especially because of translated versions.

For example, french (my native language) have lot of names longer than english version :

![Capture-20190815183048-318x638](https://user-images.githubusercontent.com/45535283/63110121-0367bb80-bf8b-11e9-99b1-57c136c398ae.png)

**Comment by Nilvus** [comment]
I would just add that with a PR waiting to be merge, this problem will be reduced because of new functions added on tags (so new buttons). See here : #2850

**Comment by timur-davletshin** [comment]
Is it not possible to add left-right padding to those small buttons so they have equal distance around text?

**Comment by Nilvus** [comment]
> Is it not possible to add left-right padding to those small buttons so they have equal distance around text?

Without breaking other parts of darktable, unfortunately not on what I have done at this time. I could make a new try though.

**Comment by timur-davletshin** [comment]
Thank you for trying!

**Comment by Nilvus** [comment]
Making few tries and possible to improve a little by using better left padding (left padding is already used). It's possible to add 2 points on left and right buttons (on tag module only). I will propose to @phweyland to add this to his PR and see if it's ok with his new adds (#2850), especially in german language which have the longest texts I find on this module. So by passing padding left and right from 2pt from 4px is better but that doesn't change a lot. More would pose problems because cross and menu buttons on the right of 'new' 'import' 'export' are also considers as buttons so same padding is applied on them.

Above, german rendering with that change :

![gnome-shell-screenshot-YS3E6Z](https://user-images.githubusercontent.com/45535283/63117037-4467cc00-bf9b-11e9-9b4a-4ac4caefb0f3.png)

**Comment by timur-davletshin** [comment]
Looks better than before!

**Comment by timur-davletshin** [comment]
Cannot leave font choice without comment. Line with lots of space and just "Tagging" in it is using narrow font, while lines and buttons with cramped text are written in normall width )))

**Comment by Nilvus** [comment]
I don't understand what you mean on your last comment.

**Comment by timur-davletshin** [comment]
> I don't understand what you mean on your last comment.

Ironic remark on font choice in that theme of your's (last screenshot).

**Comment by Nilvus** [comment]
That's default font by Aurelien yes and I have no problem with them. Font choice, Roboto here, have been discussed a lot by the darktable community during more than 3 months, and this choice have his detractors but also many supports. Compromise was finding by letting the default css with OS font.
And the good thing on darktable is that's the UI is a lot tweakable by CSS (and a lot more than darktable 2.6 was). So you could make a better design for you if you want.
Design is not only consistency, it's also made of choices and compromises. And we are all different so a design will always have people who dislike it. On the new UI, we have seen many users express they like it. And a lot of choices was made about compromise, even when we would like to have a better possibility, for reasons I have already answer to you on your two issues.

I consider your issue solved even if it's not the perfect design here, it's now really difficult to do better with GTK limits and place needed for other buttons and fields around (so without breaking an other part). A more important padding create an inconsistent space between cross and menu buttons on tagging module.

**Comment by timur-davletshin** [comment]
I don't argue about CSS styling — that is a great and easy way to tweak UI. Thank you for your attempts to improve issue.

**Comment by Nilvus** [comment]
I think you can close your issue. See what's @phweyland propose here : https://github.com/darktable-org/darktable/pull/2850#issuecomment-521766937

**Comment by timur-davletshin** [comment]
I'm happy with that fix!
