### ISSUE TITLE
Contrast Brightness Saturation module affects image when all sliders are at 0

### ISSUE THREAD

**Issue by leonixyz** [darktable-org/darktable#2868]
**Describe the bug**
I shot some pictures using my Nikon Z6 under heavy led lights and they look weird when I turn on the Contrast Brightness Saturation module, even though I do not move the sliders.

**To Reproduce**
1. Open RAW and sidecar files from https://www.meran4peace.it/bug.zip
2. Toggle On/Off the Contrast Brightness Saturation module with all sliders at 0
3. See difference in the lights on top of the stage

**Expected behavior**
The manual states:

> The module has sliders for each of the three affected attributes. In their neutral position (zero) the image remains unchanged.

The image should remain unchanged.

**Screenshots**
See RAW and sidecar files from https://www.meran4peace.it/bug.zip

**Platform (please complete the following information):**
 - OS: Arch Linux 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
 - Version: Darktable 2.6.2

**Comment by chrik5** [comment]
This is by design. Depending on the place of the module in the processing pipeline different color spaces are used. Color space conversion may cause artefacts as soon as you turn on a module without touching the sliders. More details can be found in the usermanual like here: https://darktable.gitlab.io/doc/en/color_management.html#possible_color_artifacts

You can turn on gamut clipping in the[ input color profil](https://darktable.gitlab.io/doc/en/color_group.html#input_color_profile)e module to avoid this
