### ISSUE TITLE
Colour/Saturation changes when working in Darkroom

### ISSUE THREAD

**Issue by rhithyn** [darktable-org/darktable#2893]
[darktable 2.6.2, surface book 2 15", Windows 10 1809 - build 17763.615]
When I'm editing my photos, the main picture toggles between an almost sepia version of the image and a more colourful variant, but with no rhyme or reason for changing.  It toggles as I move my mouse around the modifier panel.

For example, I move my mouse over the angle in crop and rotate and it toggles between being desaturated and flat to processed.

**Comment by gemsbond2005** [comment]
[darktable 2.6.0 updated to 2.6.2, Acer Aspire E 15; Windows 10  1803 - build 17134.1006]
Same issue suddenly appeared here too. I thought I might have modified some settings without noticing it, so I uninstalled DT 2.6.0 and installed DT 2.6.2, but problem still present. 


I noticed that for some pictures the preview in the top left corner is covered by a chequered green patern. Also, the histogram gets completely grey when the picture is desaturated, but when it comes back to normal , the histogram shows the blue , green and red channels
Last thing I'd like to add, in the beginning preview and main view are similar, but after a few modifications of crop and rotate they are not coordinated anymore: one is desaturated and the other normal, then they switch between both states. 
The histogram stays coherent with the preview though. 

Since this bug appeared, it's there for every picture and as soon as I open it 

attached : the 4 stadiums of the bug
#1 : I open the image from lighttable by double-clicking it, and it opens desaturated in darkroom. histogram / preview and image are coherent but desaturated
#2 : I open the crop and rotate module, the main image gets its original saturation back
#3 : I modify the crop, the main image loses its saturation, preview and histogram gets saturation back
#4 : Another modification of crop later, main image is saturated again, but preview and histogram aren't anymore


![Capture01](https://user-images.githubusercontent.com/45238106/65078315-0d6f4680-d99d-11e9-926d-2b60bb4b6508.JPG)
![Capture02](https://user-images.githubusercontent.com/45238106/65078325-1233fa80-d99d-11e9-9efb-a212d38db529.JPG)
![Capture03](https://user-images.githubusercontent.com/45238106/65078332-15c78180-d99d-11e9-95bc-4f8642ce80e0.JPG)
![Capture04](https://user-images.githubusercontent.com/45238106/65078340-1a8c3580-d99d-11e9-8dd9-971f204d3aa9.JPG)
