### ISSUE TITLE
Sony a6400 ARW cannot be processed

### ISSUE THREAD

**Issue by mhechthz** [darktable-org/darktable#2899]
Hi,

I just tried to process a Sony a6400 arw. I get a message like "white balance of camera cannot be read from file" and than nothing happens. I can go back to the light table and work with the jpeg but arw doesn't work. I tried to import the arw in Rawtherapee and all is fine.

I'm using version 2.6.2 (German?!) on Windows 10. Camera firmware is 2.00. Objective is SEL18135 with Firmware 01. I also tried Sony RX100 iii with arw and there was no problem! So it's only the a6400.

**Comment by MStraeten** [comment]
according to https://www.darktable.org/resources/camera-support/ the cam is just not supported yet in the productive (2.6.x) software.
You might use a development build of the 2.7 version (see https://discuss.pixls.us/t/darktable-2-7-dev-windows-builds/12579/82) - there the a6400 support should be available - but then you need to backup your darktable databased since the format changes without backward compatibility.

**Comment by mhechthz** [comment]
Perfect, I will try this.

Thank you.

Martin Straeten <notifications@github.com> schrieb am Sa., 31. Aug. 2019,
20:44:

**Comment by MrHalfknight** [comment]
I have built 2.7.0 from GIT today (Oct 10th) but unfortunately arw files from a Sony A6400 still cannot processed (failed to read camera white balance information from xxx.arw)

**Comment by MrHalfknight** [comment]
i have to correct me. with the master branch instead of branch release 2.7.0 arw files from a Sony A6400 can be opened :-)

**Comment by johnny-bit** [comment]
Sony a6400 is supported since darktable 3.0.0
