### ISSUE TITLE
How was libgphoto2 complied for Windows?

### ISSUE THREAD

**Issue by define-private-public** [darktable-org/darktable#2973]
Hi, this is not bug/feature question, but I could use some help.  I'm currently have been working on C#/NuGet package called [SharpCamera](https://www.nuget.org/packages/SharpCamera/). Which right now lets users do some basic tethering of a DSLR camera.  On Linux and OS X, I'm able to build `libgphoto2` all fine and have it work, but Windows has been a bit of a different story.

I was able to do a successful compile of `libgphoto2` from source using the MSYS2/GCC toolchain.  But when I tried hooking up a dummy C program to talk to the library, it would crash horribly.  I recently tried plugging the DLLs that `darktable` is packaged with and it actually worked.  So how are you compiling/packaging libgphoto2?  It would be really helpful to me and others.

**Comment by chhil** [comment]
The msys environment pulls the appropriate versions when you set it up.

From the windows build instructions...

$ pacman -S mingw-w64-x86_64-{exiv2,lcms2,lensfun,dbus-glib,openexr,sqlite3,libxslt,libsoup,libwebp,libsecret,lua,graphicsmagick,openjpeg2,gtk3,pugixml,libexif,osm-gps-map,libgphoto2,flickcurl,drmingw,gettext,python3,iso-codes,python3-jsonschema,python3-setuptools}

I am not a C/C++ dev so this may not be useful.

**Comment by johnny-bit** [comment]
darktable on windows uses libgphoto2 provided by msys2. additionally in build instructions https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.txt there's a note for usb driver & similar is present on homepage. So on windows your libgphoto2 not working might be combination of issues?

(since it's non-darktable related - closing)
