### ISSUE TITLE
What impact will existing styles have with v3.0 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3026]
**Describe the bug/RFI**
I have imported styles and created a couple, with the change in iop order fixes what steps should be taken to get styles in line if any?
Do they get impacted ?

**Platform (please complete the following information):**
 - OS: Any
 - Version v 2.7.xxxx

**Comment by jenshannoschwalm** [comment]
Hi, unfortunately it took a while to understand possible problems related to style & iop_order.
There is indeed a problem here that should be fixed for 3.0

@TurboGit I observed severe dt crashes after applying old styles requiring several restart/crash cycles. When using the -d ioporder option it became obvious that adding that style resulted in **different modules having the same iop_order** and that lead to the crash (in my specific case that was iop=23.0 but i think that doesn't matter).

Unfortunately the darktable_style version="1.0" doesn't give a clue about the iop order version (or is this wrong?). The existing on-the-fly conversion can't be used as-is here, always to default is also **not** ok.

Probably we have to go the hard way and for each entry in style we must ensure a proper iop depending on already existing modules in the history stack.

**Comment by jenshannoschwalm** [comment]
I think this is fixed. Please concide to close issue :-)

**Comment by chhil** [comment]
@jenshannoschwalm 
There is a long trail of comments and separate tickets for this. 
Could you give me a one liner on what one should  keep in mind when I import a style that has modules that are spread across IOP order?

**Comment by jenshannoschwalm** [comment]
Sure, allow me a few more lines :-)

There have been really a number of issues about history, iop_order and styles. Some very technical.

A style basically adds a module with style-defined parameters to the pipeline. This has been the case and still is.

The iop_order of the inserted module is **not** defined by the style but is calculated from default iop_order for the target image respecting multiple instances of modules.

So you can **not** use a style to apply a certain modified iop_order.

Atm we can't do it otherwise.

But be patient, you can use copy & paste (preferably using the selection mode) history to do so.
If the source & target have the same history version the iop_order is respected.

**Comment by chhil** [comment]
@jenshannoschwalm Thank you for the few lines ;)

Really appreciate you taking the time to fix and explain things.
