### ISSUE TITLE
better lut3d placement in the pipeline

### ISSUE THREAD

**Issue by jakubfi** [darktable-org/darktable#3108]
Related to issue #3062

If we consider how the available GMIC LUTs are supposed to be used, default lut3d module placement in dt's pipeline should be different. I'd say it should go right before colorout. Take a look at the following examples prepared using one of GMIC LUTs with various software:

Image processed with rt's film simulation:
![s-example_rt](https://user-images.githubusercontent.com/1270167/66512628-a0515b80-ead9-11e9-9f78-90b5c69fd53d.jpg)
Image processed with dt's lut3d (current placement)
![s-example_dt_lut_basecurve](https://user-images.githubusercontent.com/1270167/66512713-cbd44600-ead9-11e9-83c1-b1060a603836.jpg)
Image processed with dt's lut3d (fixed placement - right before colorout):
![s-example_dt_basecurve_lut](https://user-images.githubusercontent.com/1270167/66512732-d8f13500-ead9-11e9-8230-aa10ddc4a1d4.jpg)
And, for reference, unprocessed image ("clean" edit exported from dt) put through LUT with GMIC:
![s-example_gmic](https://user-images.githubusercontent.com/1270167/66512784-fd4d1180-ead9-11e9-891a-b9cd84c1bb16.jpg)

**Comment by jakubfi** [comment]
P.S. I've checked the module order once more. Before monochrome would be a better placement for lut3d, or maybe even before color reconstruction - I'm not sure about that one.

**Comment by junkyardsparkle** [comment]
Doesn't this depend quite a bit on specific use case? The haldclut is a fixed transform, so I would tend to think it would make more sense early in the pipe, allowing following modules to perform further action on its output. If you only want the effect of the haldclut, it doesn't really matter where it is, because you won't have other stuff enabled. ;-)

(TBH, my insight is limited here, because I don't really see the point of using something so primitive in software with so many other, more flexible color tools... OTOH, I *have* used darktable to *produce* haldcluts for use in ffmpeg, etc; I think of them as more useful in that workflow - using a software which makes adjustment easy to apply a transform in software which doesn't).
