### ISSUE TITLE
Lut3d Random buttom

### ISSUE THREAD

**Issue by dcendal** [darktable-org/darktable#3117]
**Is your feature request related to a problem? Please describe.**
Once you have a big collection of luts, some times is quite difficult to predict which one of them could work with one image.

When I'm lack of ideas or inspiration, I've found my self a lot of times doing : 
- Click on the path button and choose one folder.
- Select the file type
- Choose the path
- Use the arrow keys to try all of the luts of this path.
- Select a different folder.
- Repeat again until I happy with the result.

I know that this is not very professional but with this method I were able to get really good results.

**Describe the solution you'd like**
Add a new button that every time that I click it select and apply random lut.

**Comment by johnny-bit** [comment]
'tis a silly idea... I mean I can't imagine putting "randomize" button in channel mixer, white balance, color calibration, color balance, tone equalizer, color zones or any other module... And I can't imagine putting one in lut3d either.

I might be in minority but I have very small amount of LUTs that I know exactly how they work and can predict what they'll do... My wife has large collection of LUTs but then also knows which one works  (or can tell via organization of them).

So IMO it's more of organizing external resources rather than changing lut3d module.
