### ISSUE TITLE
custom map source

### ISSUE THREAD

**Issue by andrewharvey** [darktable-org/darktable#3124]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use a different map source, allowing the user to enter a new tile URL, or make this configurable somewhere (I searched but couldn't find anywhere in the source code to change this, nor could find a separate plugin repo)

**Describe the solution you'd like**
Custom map source where you can enter a name and URL with {x} {y} {z} being replaced in the same way as the OSM basemap.

**Comment by pphotography** [comment]
Think this is a great idea,

A good list can be found here:
https://wiki.openstreetmap.org/wiki/Tile_servers

Could be implemented with a dropdown menu, its configuration could be stored in a CSV file with 'name' and 'tile URL'

**Comment by andrewharvey** [comment]
To give more context, I want to be able to use a custom aerial imagery layer so I can pinpoint the location with more accuracy. (There is other foss software I can use to do this, but it would be nice for darktable to support this too)

**Comment by junkyardsparkle** [comment]
This is the project for the map widget:

 https://github.com/nzjrs/osm-gps-map

**Comment by johnny-bit** [comment]
I've became interested in this issue because with my recent outdoors shot I find it would be great to be able to use outdoor tiles available on the list shared by @pphotography 
The problem I found especially with open cycle map (and others) - you have to provide it with api key.

a custom map source as a list with URL provided in it with api keys and replacements as proposed by @pphotography would solve all that. Simply say that user wanting to use some maps would have to register for (free in most cases) map plan. then update URL to include api kay and viola - problem solved :)

**Comment by johnny-bit** [comment]
I followed @junkyardsparkle link and found that osm-gps-map has already issue with same problem... from 2011: https://github.com/nzjrs/osm-gps-map/issues/13

So the "fix" for this issue may be either on darktable side or on osm-gps-map... or both really.
