### ISSUE TITLE
Add a font size preference

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#3207]
Too many users have asked for that and it's really too simple to achieve to keep ignoring it…

We need a global preference to setup the UI font size in pt units that will override both OS and theme CSS settings, instead of asking users to find their darktablerc file and edit it manually (assuming they know which line to edit).

You need to set it to `GtkWidget *main_window = dt_ui_main_window(darktable.gui->ui)` and then (I think) propagate it to `pango_layout_set_font_description(layout, darktable.bauhaus->pango_font_desc);`

**Comment by TurboGit** [comment]
Agreed, hope this can be done for 3.0.1.

**Comment by aurelienpierre** [comment]
Well, both ?

**Comment by parafin** [comment]
I would suggest both, yes.

**Comment by jdorigatti** [comment]
Would love to see this.

**Comment by steverydz** [comment]
I would love to see this too. +1 from me.

**Comment by johnny-bit** [comment]
Seems it'd be better way than one mendioned in one of Bruce Williams videos... It should be in GUI options in options screen, right?

**Comment by elstoc** [comment]
I've only ever changed my font size via the DPI setting, which should be very simple to put into the preferences window (since it's already in darktablrc). Is there much to be gained from adding font size as well?

**Comment by parafin** [comment]
DPI scales the whole GUI, font size just text, so they are different things. I would say that scaling font using DPI setting is actually a workaround, it's better to have font size in preferences (and more common).

**Comment by elstoc** [comment]
Ok thanks for clarifying. Scaling the whole UI was my original intention, so that the modules took up less space and I could increase screen real-estate but I can see why people might want to scale the font separately. If the user set the font size, would the idea be to set it in absolute points and no longer scale it with the DPI setting or to have a 'relative' font size that would continue to scale with the DPI setting?

**Comment by elstoc** [comment]
I think changing the font size (certainly if you want to do it in pixels or points) will still scale the UI, because quite a bit of the darktable theming is done in 'ems', which are scaled according to the font size.

**Comment by Nilvus** [comment]
> I think changing the font size (certainly if you want to do it in pixels or points) will still scale the UI, because quite a bit of the darktable theming is done in 'ems', which are scaled according to the font size.

Not all things on the UI use ems so that's a big difference between setting font size and DPI.

**Comment by elstoc** [comment]
You're right of course. I was just experimenting with setting font size in user.css, now that we have it in the preferences dialog. If you remove the font-size setting from line 226 of darktable.css and replace the font-size in line 161 with a pixel- or point-based setting you can alter the font size just by putting the following in user.css

```
* {
font-size: ####;
}
```
but currently it scales other parts of the UI as well. So it might be possible to do it that way, with some other theme tweaks as well.

**Comment by Nilvus** [comment]
@elstoc: you made same mistake I recently made (just a thing I've forgotten). Line 226 is about setting all UI parts except text ones to remain at default size. See comments I've added recently (with the CSS for preferences rework) on those lines. And see this issue (#4769) and PR who fixed that one (#4806) to understand why it's better to not remove or changed line 226. Line 161 is the only one to change/tweak for font size. If line 226 is not changed, only text will be update from line 161 new setting.

**Comment by Nilvus** [comment]
@aurelienpierre and @elstoc: waiting to have a better solution, could we just add some lines on new css edit view in preferences to help user set font size directly?

See how that could it be:

![2020-05-07_23-23](https://user-images.githubusercontent.com/45535283/81346116-04f98680-90ba-11ea-8960-861152000d48.png)

The main remaining problem is that comments there, as I know, couldn't be translated to non english users. So if you have ideas for that?

**Comment by elstoc** [comment]
I don't have an issue with changing font size in the CSS tweaks section (though the CSS you've put in there doesn't currently work for everything - e.g. the preferences window) but I'd rather not start populating that box with default values and suggestions/comments or it will start getting messy quickly. It would be better if we could have guides or 'CSS recipes' set up somewhere separate and refer to that in the default comments instead. A simple bit of text like that _could_ be easily translated as that default text is set in the code and only saved to the user.css file when the user presses the button.

Having said that I can see the argument for being able to set font size independently of CSS and this still might be the better solution.

**Comment by Nilvus** [comment]
@elstoc: I just suggest to add the font size, nothing else, as it's the only thing we often have questions/asking here and on main darktable forums. For anything else, CSS guides/recipes will of course be the best thing (but not for me, I prefer use my time for something else ; I only help sometimes people asking for something to tweak, no more).

If that text could be easily translated and if we add that, that would be a good thing. As you want.
But we will indeed have to wait because of the preferences window issue you point. Indeed, it can't be (by now) changed because preferences settings are on dialog, box, stack, etc. set to 1em in line 224. But changing that would break lot of other things.

I'm working on CSS and will see if there's another way to change only all text with label for example and be sure that doesn't apply to anything else but work for all text. That will be tricky anyway. CSS need now to be optimize will al recent update made on the GUI. But with risk to break something...
