### ISSUE TITLE
Access is denied on libgio~1.DLL on 2.6.2/3

### ISSUE THREAD

**Issue by fabioroldan** [darktable-org/darktable#3243]
When it opens it throws this error:

![dartable-error](https://user-images.githubusercontent.com/9442531/67909442-fb68f200-fb5d-11e9-8f53-d550fccbc607.jpg)

**To Reproduce**
1. open darktable

**Platform**
 - OS: Windows 10 x64

**Comment by TurboGit** [comment]
> to reproduce : open darktable

Of course not ! There is many people on Windows using darktable so it ought to be much more than just starting dt!

**Comment by peterbud** [comment]
How did you install darktable? Which folder you selected to install the software to? The folder name above seems nothing of a standard location.

**Comment by chhil** [comment]
Maybe try installing it as admin. Or run the app with app priviliges if possible.

I know I can't copy stuff into darktable folder in program files without having admin privileges.

**Comment by agusmba** [comment]
Or check your antivirus program... I know I've run into many *access denied* problems due to an overzealous corporate antivirus...

There are many possible causes for this, not only a bug in darktable. As has been pointed out, share how you installed darktable, what kind of user did you use for the installation and for running it, what kind of anti-virus-malware you are using...

**Comment by TurboGit** [comment]
No, no more 32bit versions.

**Comment by fabioroldan** [comment]
i don't use antivirus
