### ISSUE TITLE
Way to enable spot white balance as a default preset for the WB module...a sort of Auto WB feature...

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#3325]
I have been looking back at a lot of older photos I have mostly JPG files. Many have color casts. I find that spot WB does and excellent job correcting many of these but I can not find an automated way to apply it. If you create a preset for WB and have it applied to everything it will apply the last calculated WB from when it was last invoked to all images rather than re running. I am not sure if this would be easy or difficult to implement but it might have merit...for example if you could create a preset that would auto invoke spot white balance you could apply that to a set of files in lighttable with the create duplicate selected to create a set of Spot WB images to quickly compare to the originals...maybe its a niche thing though but I just thought I would ask...a sort of auto WB feature??

**Comment by junkyardsparkle** [comment]
I would propose taking 'spot' out of that (confusingly named) 'preset' list, and instead having something like the auto/manual selection in the exposure module (which works in the way requested here). The 'preset' list could then be named 'camera presets'.

**Comment by todd-prior** [comment]
I think that does make sense or a checkbox in the WB module to enable auto WB which would be spot....some form of this would make sense at least to me...
 
Sent from 
Mail for Windows 10
 

From: junkyardsparkle
Sent: November 8, 2019 12:02 AM
To: darktable-org/darktable
Cc: Prior,Todd; 
Author
Subject: Re: [darktable-org/darktable] Way to enable spot white balance as a default preset for the WB module...a sort of Auto WB feature... (#3325)

 


I would propose taking 'spot' out of that (confusingly named) 'preset' list, and instead having something like the auto/manual selection in the exposure module (which works in the way requested here). The 'preset' list could then be named 'camera presets'.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by dschurholz** [comment]
This feature would be very helpful for me as well. Is it currently available in some form or the other in the current Darktable version?

My issue is that I have maaany (thousands) underwater pictures and I need to white balance them. I have noticed that the spot white balancing in darkroom works very well for this purpose, since I do not need a perfect white balancing on all the pictures. But sometimes the lighting is quite different between the pictures. It would be great to have the option to create a style that, when applied, calculates the white balance for each individual picture using 'spot' on the current picture. Currently (as stated in the original post of this thread), when saving the white balance style with spot, it saves the last values calculated from the last picture used, and applies these same values on subsequent pictures, on which the style is applied.

Thanks for the awesome software and hoping to hear back for this feature.
