### ISSUE TITLE
Zoomable lighttable doesn't refresh properly on mouse over

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#3335]
**Describe the bug**
The selected image in the zoomable lighttable mode doesn't refresh properly.  This makes it very difficult to determine which image is actually selected.

**To Reproduce**
1. Go to zoomable lighttable mode in lighttable
2. Move mouse around
3. Observe that many images appear to be selected.  Moving the mouse off the lighttable view forces a full refresh which clears all the erroneously highlighted images.

**Expected behavior**
I expect only the image that the mouse is hovering over to be highlighted.

**Screenshots**
[![darktable-selection.png](https://i.postimg.cc/wT8H6f9P/darktable-selection.png)](https://postimg.cc/G9Q6Kj8J)

**Platform (please complete the following information):**
 - OS: archlinux
 - Version cc15f8d938c3a7d9742f0a40e2a30428bdda3647

**Additional context**
Also observed on windows 3.0rc

**Comment by groutr** [comment]
In testing this a little more, I've noticed that the issue only happens when moving the mouse to the right or down.

**Comment by Nilvus** [comment]
I don't use this mode but I've just test and can confirm that bug on this mode. I'm using Linux and 3.0rc too.

**Comment by AlicVB** [comment]
I know... zooming mode is a nightmare in the code... (I've tried to fix that at some point, but it would require a lot of change...)
@TurboGit : it's certainly due to your (great) work to limit the amount of redraw. If you want my opinion, we should always force full redraw for zooming. It'll revert back to old behavior... but anyway, at some point we'll have to either drop or completely rewrite this mode :(

**Comment by TurboGit** [comment]
Unconditional full redraw put in place when in zoomable lt. Probably no much we can do indeed. I'm really wondering now about removing this view BTW. It becomes a nightmare to maintain and we have a far better experience with standard view and culling now.
