### ISSUE TITLE
denoise profile: default parameters

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#3352]
In the spirit of giving an immediately accessible, safe, sensible and assisted default setting to beginners, I think the default setting in denoise profile should be "non-local means auto". That way, users can just enable and enjoy, possibly tweak a bit and be done with it.

What do you think @rawfiner and @parafin ?

**Comment by junkyardsparkle** [comment]
Unless I'm misunderstanding, the init values are already auto-adjusted? I thought the "auto" settings are so that users can create presets with manual settings which still are adaptive wrt ISO.

**Comment by rawfiner** [comment]
I am ok with changing to nlmeans auto ;-)
Yes the init values are also already auto-adjusted, but the UI can be intimidating with all the sliders, and the "guessed" values can be inadequate in case of an underexposed image. The auto settings allow user to create presets that are adaptive wrt ISO, but also to adjust quickly the parameters to get a good result (in case of an underexposed image, increasing one slider is enough to get a good result in this mode), so it could be set as default.

**Comment by junkyardsparkle** [comment]
Makes sense, I haven't really used that mode much yet, maybe I should take a closer look. While we're on the subject, and since this "issue" probably won't require much other discussion, I'll hijack just a little... regarding this module being an all-around utility for denoising, I stumbled onto the odd case of trying to use it to denoise some old negatives which were "scanned" with a macro lens. In this case (and possibly others) a way to manualy switch to un-profiled mode would be handy. :-)
