### ISSUE TITLE
Histogram in new 'rgb levels' iop

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#3364]
**Describe the bug**
As a user, I do not understand why the histogram in "rgb levels" iop does not have the same horizontal scale than the overview histogram at top right darkroom corner.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'darkroom'
2. Activate the new 'rgb levels' iop and make it the last one applied in the pipeline. No other iop activated after. Keep the default 'rgb levels' iop parameters. Should not change anything to the image
3. Compare the histogram in 'rgb levels' with histogram on top right corner.
4. As 'rgb levels' is the last iop applied and not not modify the picture, I'm expecting both histograms to be the same. Actually, the 'rgb levels' appears shifted to the left compared to the main one.

**Expected behavior**
I'm expecting consistency between histograms. Same horizontal scale.

**Screenshots**
'rgb level' histogram

![Capture d’écran du 2019-11-10 12-30-44](https://user-images.githubusercontent.com/22872204/68543839-80ed6d00-03bc-11ea-94b1-afa6e9ff1f12.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 19.10 Linux
 - Version 2.7.0+2247~gcc15f8d93

**Additional context**
legacy 'level' histogram for comparison. This one is well aligned on x scale with main histogram

![Capture d’écran du 2019-11-10 12-33-04](https://user-images.githubusercontent.com/22872204/68543843-919de300-03bc-11ea-9b8d-55b61fee2d10.png)

**Comment by aurelienpierre** [comment]
https://discuss.pixls.us/t/why-is-the-global-histogram-in-darktable-different-from-the-ones-in-modules/14794?u=aurelienpierre

**Comment by leclercj** [comment]
Thanks @aurelienpierre for you explanations. It helps, but I still have one question

I do not have problem with the histograms as displayed within "Lab" iops ('levels' and 'tone curve'). 
- 'levels' is showing L channel and this is explained in the tip. OK
- 'tone curve' is showing L, a and b channels and this is clearly written. OK

Also, with these 2 operations working in Lab space, I can easily see the correlation between the histogram in L channel and the RGB top histogram. x-scale appear the same.

'rgb levels' and 'rgb curves' are both working on linear RGB space, right ?
So why are the embedded histogram different ?

- In 'rgb curve', the RGB histogram looks very similar to RGB top histogram. Same x-scale. OK

![Capture d’écran du 2019-11-11 23-18-27](https://user-images.githubusercontent.com/22872204/68625529-a9b75480-04d9-11ea-812f-ee169b99ad71.png)

- Only 'rgb levels' histogram has a different x-scale. Why ?

**Comment by junkyardsparkle** [comment]
If you disable the "compensate middle gray" checkbox in 'rgb curve', it will have similar histogram to 'rgb levels', and if you set histogram profile to linear Rec709, that histogram will match those, too.

**Comment by leclercj** [comment]
Thanks @junkyardsparkle. This "compensate middle gray" checkbox is exactly what I see missing in 'rgb levels'. Don't you think it would also make sense in 'rgb levels' case ?

**Comment by leclercj** [comment]
Then I would also question the definition of 'medium grey point' in 'rgb levels' and this won't be any more just a graphical representation topic. My view is that it would be better to use as 'medium grey point' the mid point from the "grey compensated" scale.

**Comment by aurelienpierre** [comment]
The middle grey compensation is only a non-linear transform to push the 18.45% grey to 50% and then center it on the graph. I have mixed feelings about that, but levels and curves are tools of the past to me.

**Comment by leclercj** [comment]
>The middle grey compensation is only a non-linear transform to push the 18.45% grey to 50% and then center it on the graph

If it make sense for 'rgb curve' to push the 18.45% grey at center of the graph, shouldn't it be the same for 'rgb levels' ? The mid-grey slider in 'rgb levels' could also be attached to this 18.45% grey.

> levels and curves are tools of the past to me.

However, 'rgb levels' and 'rgb curves' are new tools coming with dt3.0.
Don't we have a contradiction here ?
By what do you replace them ? all filmic ?

**Comment by aurelienpierre** [comment]
> If it make sense for 'rgb curve' to push the 18.45% grey at center of the graph, shouldn't it be the same for 'rgb levels' ? The mid-grey slider in 'rgb levels' could also be attached to this 18.45% grey.

It's less important for levels since the controls are sliding in 1D, but setting up nodes in 2D on a linearly-encoded graph can be tricky for low-lights (hence the log scaling in the Lab tonecurve, that wasn't ported to the RGB one).

>  By what do you replace them ? all filmic ?

What rgb levels do is exactly the same as the colour balance (using only the lightness sliders): the grey is a power function, the white is an exposure compensation aka the slope, and the black is an offset. The colour balance having the benefit of not being bounded to [0; 100] % (because the levels ergonomics are grounded into the display-referred workflow) and giving a more precise and reproducible setting.

Same applies (to some extent) to the tone curve (still inheriting its ergonomics from the display-referred workflow), with the difference that the curve could be bent to more specific things that the colour balance slope/offset/power, but is that really useful in practice ? If it is, you have the tone equalizer : once you remove the details preservation mode, it's a simple chroma-preserving tone curve, but with log-scaled controls and 1D sliders than can be set more accurately than 2D nodes on a bounded graph. Same feature, better ergonomics. 

> However, 'rgb levels' and 'rgb curves' are new tools coming with dt3.0.
Don't we have a contradiction here ?

There is what I say, and there is what we decide. My opinion is exposure + colour balance + filmic replace (feature-wise) half the modules in darktable with better results. You only need denoise profiled, local contrast, lens correction and maybe defringe to get your full pipeline, plus tone equalizer for cases where filmic is not enough. But not everyone agrees and people stay attached to their old tools.

**Comment by junkyardsparkle** [comment]
> Same applies (to some extent) to the tone curve (still inheriting its ergonomics from the display-referred workflow), with the difference that the curve could be bent to more specific things that the colour balance slope/offset/power, but is that really useful in practice ?

I understand where you're coming from, and I'm coming to feel the same way *as far as the specific case of straightforward processing of RAW files resulting from "normal" photography*... but I think it's important not to be too dismissive of other use cases, or the tools that might be useful to them. Consider somebody scanning old color negatives, for instance (maybe with a camera rather than a film scanner); independent RGB curves are pretty useful here. :-)

**Comment by vsz1lu** [comment]
@junkyardsparkle 

> Consider somebody scanning old color negatives, for instance (maybe with a camera rather than a film scanner); independent RGB curves are pretty useful here. :-)

Exactly! But not just 'old' negs  ;)

The digital post-processing of chromogenic films is a really hard work - especially with under/overdeveloped or push processed stuffs what have strong colour shifts. The dynamics range of modern analogue materials (expect colour reversal films) is more-more wider and the colours are working in total different way. In the digital world you just try to reach some tonality what you can see on enlarged chemical prints or properly(!) developed slides in projection / ciba print. And don't know what is surrealism while not see badly developed slides :)

The 'rgb leves' and 'rgb curves' is a very-very great feature in DT! I must processing my raw colour scans frame by frame with GIMP in the last years. But now I can rethink and move my colour post-process workflow (except the dirt removal of course) to darktable, what is more effective way with full rolls what I shot of some subject and in some lightning conditions. The 'compensate middle gray' switch is unbelievable useful stuff: I can easily switch between average ranges and highlites while editing the curves. It's simply brilliant. Don't forget: logarithmic scale is perfect for digital images where the low and mid lights area is very important, but the soul of film negatives is living in the highlites! Looks like the midgray checker of 'rgb leves' useless for colour negs - it's push the most part of image over ~Zone IIIV when click a on an area what metered to Zone V, but maybe I use not perfect sample.

So many thanks for the RGB Curves, my life gone to better!
I'll order new stock colour poisons and some roll of Ektar :)
