### ISSUE TITLE
Default denoise (profiled) "chroma" preset makes the image luma-noisier and brighter

### ISSUE THREAD

**Issue by jakubfi** [darktable-org/darktable#3397]
Using the default "chroma" preset for denoise (profiled) adds coarse luma noise and makes shadows brighter overall. When blend mode is changed from "HSV color" to "color", chroma denoising seems to work as expected again.

Test image below is ISO 4000, taken with ILCE-7.

No denoise:
![1_no_denoise](https://user-images.githubusercontent.com/1270167/68695897-2995fb00-057c-11ea-8d0a-e22884036021.jpg)
Default "chroma" preset:
![3_chroma_hsv_color](https://user-images.githubusercontent.com/1270167/68695912-2f8bdc00-057c-11ea-81ce-f821c1ea916d.jpg)
"Chroma" preset with blending changed to "color":
![2_chroma_color](https://user-images.githubusercontent.com/1270167/68695906-2d298200-057c-11ea-9e61-8d4872f0eef4.jpg)

**Comment by jakubfi** [comment]
I see two issues here:

1. Whether such behavior of "HSV color" is expected
1. Whether this blending mode should be the default one for chroma denoising (users get suboptimal results out of the box)

**Comment by aurelienpierre** [comment]
Blending should simply not be used in this module. There is no colour at this place of the pipe.

**Comment by rawfiner** [comment]
I agree with Aurélien.
I don't think it is a bug.
As a side note, the switch to hsv color instead of color was done because the color blending mode clamps the highlights.

**Comment by jakubfi** [comment]
@aurelienpierre @rawfiner so the bug here is that dt has a "chroma denoise" preset where it shouldn't, as I understand? Which raises another issue: where and how provide users with a proper chroma denoise capability?

**Comment by rawfiner** [comment]
@jakubfi The preset is kept for now as people still like it even though it is not perfect. In my opinion, the interesting thing about it is that it shows an example on how to use the wavelets curves.
If you move denoiseprofile after colorin, color blending modes will make sense, but the profile won't be as accurate.

The best solution in my opinion is to use the central pixel weight slider in non local means to choose how much to denoise "luma", without using any blending mode. Increasing this value will basically perserve details as well as "luma noise", and the result will get closer to a "chroma-only" denoising.

**Comment by jakubfi** [comment]
@rawfiner thank you for the explanation and hints, I will definitely try those out. I myself use profiled denoise with "chroma" preset and color blending and find its results the best among all available color denoising methods, even though it is (as I've just learned) technically the wrong approach.

As for the bug report - I honestly don't know how to proceed with this. We have a denoising method (a preset), which is technically wrong, but visualy good and (some) people like it. Moreover, that method uses a blending mode (HSV color), which it shouldn't use at all, but it's technically correct, but gives results noticeably worse than the other one (color) which is technically wrong... :-) And on top of that this method (preset) is not really a proper chroma denoise method, but just an example of how to use a module... I'm at a loss. :-)

**Comment by MStraeten** [comment]
unfortunately a preset can't contain the position in the pipe (before/after colorin)
Considering the many issues while developing the new pixel pipe, this would be a greater challenge.

**Comment by junkyardsparkle** [comment]
> I'm at a loss. :-)

What do you mean? You gave a perfectly good summary. ;-)

FWIW, I've been finding the combination of central pixel weighting and "scattering" adjustment to be very useful for subjectively tuning the denoising for my particular camera. Using more scattering helps with the "blotchy" chroma noise that I find most objectionable (even at fairly small image scales) while the central pixel weighting is similar to what I used to try to do with blending... retain some fine textural detail even if it includes some fine luma "grain" (not really objectionable to me, other than making JPEGs bigger).

> unfortunately a preset can't contain the position in the pipe (before/after colorin)
Considering the many issues while developing the new pixel pipe, this would be a greater challenge.

Yes, pipe position is out of scope for what presets (currently) are: a snapshot of module params. Styles can contain this "meta" parameter, but applying it turned out to cause all kinds of problems given that styles can come from anywhere and any time. We need some way of integrating reordering effectively into a workflow; #3266 is my own crazy idea as to how this could be done.
