### ISSUE TITLE
Tone EQ: showing wrong EV values (RC1)

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#3431]
**Describe the bug**
Tone EQ is showing much to low EV values with initial settings.

**To Reproduce**
Turn on Tone EQ, click on "Reset module".
EV Values of -16 to -14.5 EV are shown for my photo.

**Screenshots**
See below.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version [DT 3.0 RC1]

![Bild1](https://user-images.githubusercontent.com/57685590/68867472-2b83c980-06f6-11ea-915d-5b5096a0a496.jpg)

**Comment by aurelienpierre** [comment]
Display the exposure mask.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
The mask is all black. 
You mean, in order to get some usefull results one has to adjust the mask first?

**Comment by aurelienpierre** [comment]
If the mask is all black then the -16 EV reading is consistent. Either your image is way under-exposed, or the masking options are ill-set. Go to the masking tab, and raise the mask exposure compensation, it should fix your problem.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
I don't think my photo is way underexposed (see global hist) and the mask settings are default.
Please check if the default settings can be improved. 
Anyways I will close the call.

**Comment by aurelienpierre** [comment]
Global histogram is not relevant here since it's the final histogram of the pipeline, we only care about the state of the picture before it enters tone EQ. For example, if you pushed the midtones a lot in filmic, the final histogram would be fine and still, the image would be under-exposed.

Could you send me the raw + XMP ?

The default settings are such that, when applying 2 iterations of guided filter with feathering = 10, you should get 80% of your histogram spread between -7 and -1 EV (from first decile to last decile). But then, there is some variability depending on the original local contrast of your image.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Hi,
here the RAF and XMP:

http://chris-s.bplaced.net/tmp/TMP191115220603.zip

christian


Am 15.11.2019 um 20:00 schrieb Aurélien PIERRE:
> Global histogram is not relevant here since it's the final histogram of
> the pipeline, we only care about the state of the picture before it
> enters tone EQ. For example, if you pushed the midtones a lot in filmic,
> the final histogram would be fine and still, the image would be
> under-exposed.
>
> Could you send me the raw + XMP ?
>
> The default settings are such that, when applying 2 iterations of guided
> filter with feathering = 10, you should get 80% of your histogram spread
> between -7 and -1 EV (from first decile to last decile). But then, there
> is some variability depending on the original local contrast of your image.
>
