### ISSUE TITLE
X-T30 missing in v3.0.0rc1

### ISSUE THREAD

**Issue by dimk1** [darktable-org/darktable#3465]
**Describe the bug**
In the release file of 3.0.0 rc1 it is stated that there is now support for the Fuji X-T30 for compressed RAW files

**To Reproduce**
1. Open a RAF file from X-T30
2. Go to Lens Correction
3. Scroll down to Fuji and search for X-T30
4. Model does not appear

**Expected behavior**
An entry for X-T30 was expected

**Platform (please complete the following information):**
 - OS: [Ubuntu Budgie 18.04]
 - Version [e.g. 3.0.0rc1+22~g55915401e]

**Comment by Nilvus** [comment]
Lens correction and support of RAW are two different things. Lens correction is about Lensfun library. It's not a darktable issue. Please update your lensfun library (lensfun-update-data on a Terminal ; install lensfun-bin package before. Name package could be a little bit different depending of your system. More info by searching on the web for lensfun and how tu update it). X-T30 is supported with last version of lensfun...

Think of closing this issue. Thanks.

**Comment by dimk1** [comment]
Sorry, but why closed? My lensfun library seems updated. under /usr/local/share/lensfun path the mil-fujifilm.xml contains X-T30 but darktable does not list it. I haven't used the packages of Ubuntu but the git ones. Any configuration I'm missing?

**Comment by Nilvus** [comment]
Just read what I write to understand why. That's not because you don't have X-T30 on your system that it's a darktable issue. X-T30 is listed on my system for example. It's not a forum here to help, it's a place to post real issue that developers can correct (or feature request). If you still don't have X-T30, you miss something. So please use forums for that like the one on pixl.us.
