### ISSUE TITLE
User manual: ctrl-h

### ISSUE THREAD

**Issue by bilddateien** [darktable-org/darktable#3508]
I do not find a mention of `<ctrl-h>` in the user manual yet I stumble about this every now and then when I do not remember how to bring the top bar back when it "suddenly" disappears.

As there are no other means in the GUI to control this (like arrows for the other bars) I think it would be worth mention in the user manual.

**Comment by Nilvus** [comment]
User manual is not updated for 3.0. It's the same each year, manual is finish after, just because developers have hard work (on their free time) to finish 3.0 and we don't have people (or too few ones) to help updating the manual. So feel free to propose a chapter (this could be short) with title and text. If you know how to use git and how manual works (wiki on Redmine is a good help for all that), you could propose a PR. Or a text here. Ping @AlicVB then as it is the developer of this function.

**Comment by AlicVB** [comment]
As far as I can tell, I'm not guilty :)
@Nilvus : shortcut preview is just `<h>` `ctrl-h>` is for hiding header bar, iirc
@bilddateien : you're right, it's not documented atm... as many other things, certainly... docs needs more hands !

**Comment by johnny-bit** [comment]
And we have more hands and new docs :) https://github.com/darktable-org/dtdocs + https://darktable-org.github.io/dtdocs/ 
And relevant bit is mentioned here: https://darktable-org.github.io/dtdocs/overview/user-interface/keyboard-shortcuts/
