### ISSUE TITLE
Crashed when using latest windows ver. Using the equalizer module at the time.

### ISSUE THREAD

**Issue by MichaelY** [darktable-org/darktable#3526]
Installed 2.6.3 opened a file from external drive in lighttable from collection. Cropped file, edited using equalizer module. Used Luma element to change file. Error popped up. File attached.

**Expected behavior**
Apply changes from equalizer module and not crash

**Screenshots**

**Platform (please complete the following information):**
 - OS: MS Windows 
 - Version 10 (1903) Build 18362.476
[darktable_bt_T4SQB0.txt](https://github.com/darktable-org/darktable/files/3879818/darktable_bt_T4SQB0.txt)

**Additional context**

**Comment by johnny-bit** [comment]
Since version 2.6.3 we've had couple 3.0.x releases, 3.2.1 and 3.4 releases... Current codebase is very different from 2.6.3 so I'm closing this issue - my wife used 3.0.x and 3.2.1 releases on windows without equalizer ever breaking so I think the issue should be fixed by now.

If you still have problems - please try newest release and if new release produces problems feel free to open up a new issue.
