### ISSUE TITLE
Help setting up debugging on Windows

### ISSUE THREAD

**Issue by DiegoBM** [darktable-org/darktable#3541]
Hi all, I come from the Windows world and I'm more used to things like visual studio and visual studio code with windows-style .sln solutions.

This is my first time setting up an application that comes from the *nix world and I must admit that I'm quite lost with the msys world. I can setup the project to build with no problems by following the thorough instructions from github, but I was trying to setup a windows development environment for darktable using Visual Studio Code, so that I'm able to build, debug with full visual breakpoints, step-through, etc, but I don't know where to start trying to make vscode work with msys and darktable, specially when it comes to visual debugging... Has anyone gone through something similar or could give any advice on how to achieve this?

If nobody has done this in Windows but is working in Linux with vscode and darktable (especially debugging), I presume that I could extrapolate those instructions to Windows with more or less effort, so any help would be welcomed.

Maybe some information in the build documentation about debugging could come handy?

Thank you in advance.

**Comment by chhil** [comment]
With  trial and error I could get it to work with netbeans on windows.

**Comment by MStraeten** [comment]
it‘s time to learn using gdb ;) darktable wasn't supporting windows for a long time so i wonder some of the developer uses microsoft tools in a linux environment.

**Comment by DiegoBM** [comment]
@chhil I might try netbeans although I'd prefer to use something more lightweight if possible

@MStraeten I wouldn't mind lerning gdb, but I reckon that in this time an age it would be more productive to use visual debugging. I know for a fact that VSCode is very popular in Linux and mac as it is in Windows for web development, no idea about C++ but my guess is that it's getting very popular in general. It wouldn't hurt to implement a more modern environment than relying on the terminal only.

**Comment by mbaumgae** [comment]
You can have a look at the "support-visualstudio-build" branch on my darktable repository on GitHub:
[https://github.com/mbaumgae/darktable/tree/support-visualstudio-build](https://github.com/mbaumgae/darktable/tree/support-visualstudio-build)

With the changes/additions on this branch, I'm able to build and debug darktable using Visual Studio Community edition 2017 and 2019. 

The changes in some CMakeLists.txt file have been necessary on my side to be able to use Ninja as generator on Windows, which is used by Visual Studio.
In addition you will find 2 new files:
- CMakeSettings.json:  project settings, You need to adapt the paths to your MSYS resp. MINGW64 installation!
- launch.vs.json: Settings for launching a debug session from VS.

You can find additional info with regards to CMakeFile support of VS and prerequisites:
[https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019)

Currently I see some limitation in the IntelliSense functionality, which is not working completely. I'm still trying to get it running...
Also until now, I haven't been able to attach the debugger to a running darktable instance. I need to start darktable from VS project to debug, which is quite slow due to the many libraries, which are loaded and unloaded during startup.

Other then these limitations the interactive debugging is working, including watches etc. as usual!

Maybe this info can help you to get darktable built and debugged within Visual Studio Code.

**Comment by DiegoBM** [comment]
Thank you @mbaumgae for sharing that. I finally managed to debug by simply binding gdb to the executable, VSCode will catch up. In any case I'll take a look at your repo since for sure will give me some ideas.

**Comment by Macchiato17** [comment]
Hi @DiegoBM , I just saw this post here. Since I'm currently struggling on my Windows 10 system to get VCode working with gdb for debugging darktable I was wondering if perhaps you may help me with setting up my environment? Thanks a lot in advance.

**Comment by Macchiato17** [comment]
...works when using the MINGW64 debugger and not the MSYS2 gdb.exe...
