### ISSUE TITLE
[Additional Camera Support] Images are turning green in high res mode of Panasonic G9.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3602]
**Describe the bug**
darktable-3.0.0rc2+6~gc4c43ae61-win64

When image  imported.
![image](https://user-images.githubusercontent.com/1119439/69810667-6ddaf980-1212-11ea-9ee0-c68f2eab0f70.png)

When double clicked and seen in darkroom, it appears green.
![image](https://user-images.githubusercontent.com/1119439/69810709-821ef680-1212-11ea-9acf-9417585fe3f1.png)

History
![image](https://user-images.githubusercontent.com/1119439/69810806-b4c8ef00-1212-11ea-9be1-a3eafee5dd86.png)

When immediately going back to lightable
![image](https://user-images.githubusercontent.com/1119439/69810757-9c58d480-1212-11ea-891d-1d9a44e2f681.png)

When discarding history it gets restored.
![image](https://user-images.githubusercontent.com/1119439/69810838-c7dbbf00-1212-11ea-8ddf-50c9aed7ffaa.png)

**Comment by timur-davletshin** [comment]
It would help getting feedback if you provide sample files.

**Comment by chhil** [comment]
Here you go, the raw file.
https://www.dropbox.com/s/vagguzp1e14u56u/P1021638.RW2?dl=0

Its a high res Panasonic g9 file.

**Comment by chhil** [comment]
The raw file link...

https://www.dropbox.com/s/1n0l6nz7lrris7s/P1021639.RW2?dl=0
XMP link before discarding history
https://www.dropbox.com/s/r1m8yt8cmvhg6rn/P1021639.RW2.xmp?dl=0

**Comment by vsz1lu** [comment]
Confirmed.

I make a test in Digikam (libraw) where perfectly work, but in dt 3.0.0 rc2 not. (Ubuntu 19.10) Your camera is supported (https://www.darktable.org/resources/camera-support/) but something wrong - maybe in the demosaic. 

You see right colors in the Lighttable panel first, because it's loading just the embedded preview jpg. 

ps: adding the camere type (Panasonic DC-G9) in the title of Your issue maybe more helpful for the developers

**Comment by junkyardsparkle** [comment]
The G9 uses a *large* amount of post-processing boost in-camera compared to other Micro Four Thirds cameras I've seen, I presume as a way of protecting highlights... I had a long discussion about exactly what you're seeing in a forum thread in order to determine that (I don't own the camera). As a fix for that person at that time, I made a basecurve preset so they could have a camera-like starting point, it's available [here](https://github.com/junkyardsparkle/olympus-darktable/blob/master/Panasonic-G9-basecurve.dtstyle), but it's probably far from ideal.

I think you'll have a hard time getting reasonable results from this camera using, for instance, filmic RGB by itself unless you use exposure compensation in the camera (which means your previews will all be overexposed, unless there's some alternate processing mode in the camera).

**Comment by chhil** [comment]
The problem occurs only in the high resolution mode (80 mega pixel) pics. I have not had issues with my G9 raw files. Unfortunately I was helping a friend out with some food photography yesterday and was shooting in this high re mode most of the time.
I went a little back and tested with an older rc1 and the green results were identical, was just making sure a recent green fix did not break things ;).

@junkyardsparkle I will try the base curve but till date I have disabled my base curve for my edits.
@vsz1lu thank you for reproducing it.

For the time being I will edit this set of high res pics in a different editor (luminar).

**Comment by junkyardsparkle** [comment]
> I will try the base curve but till date I have disabled my base curve for my edits.

No need to, it's not really the best way of doing things; mostly it was just an example of how strong of a curve is needed by G9 (normal) RAW files in order to approximate the camera rendering. I wondered if this one was "special" in some way (seemed large), but both darktable and exiftool report the image dimensions as 20MP. I take it this would be the "secondary simulated one shot" file, not the actual 80MP one, then... and the "simulation" is apparently not very good. ;-)

**Comment by chhil** [comment]
I may have to play around with the Simul mode off for the camera.

![image](https://user-images.githubusercontent.com/1119439/69844252-660e6a00-1291-11ea-9d96-d2a7ced824f0.png)

Rawtherapee doe the green thing too. 
My best bet for now is to use a paid software (luminar).

**Comment by chhil** [comment]
Still need to be addressed.

**Comment by MStraeten** [comment]
maybe this is a solution to deal with it: https://pixls.us/articles/profiling-a-camera-with-darktable-chart/

**Comment by junkyardsparkle** [comment]
@LebedevRI: any thoughts on this one?

**Comment by LebedevRI** [comment]
Not really. Looks underexposed by ~3 stops.
I'm guessing there might is some magic tag somewhere (much like the fuji one?),
upon seeing which some automagic exposure compensation might be applied?
No clue what's nowadays darktable stance on such maker-specific crap.

**Comment by junkyardsparkle** [comment]
@LebedevRI There's also a white line along the right side...
