### ISSUE TITLE
[Feature] Refresh a collection

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3632]
Hi all !

[Problem]
I have removed some pictures from a folder which I do use in Darktable.
When I use this folder again in DT, there are plenty of unavailable pictures (noted with the white skull on black background thumbnail).
Those unavailable thumbnails are slow to appear, and mostly do so when I try to open the pic itself.
I'd like to remove all unavailable pictures at once but cannot do so. There is no way to do so, AFAIK.
As a matter of fact, folders/collections/roll management is still quite poor w.r.t features.

[Solution]
When right-clicking on a folder / film roll / collection, a new menu entry "_Refresh collection_" could scan the folder, pick up all unavailable pictures and propose to remove them (from darkroom or/and from the disk).

Thanks.
GLLM

**Comment by ptilopteri** [comment]
use:
  /usr/share/darktable/tools/purge_non_existing_images.sh
provided by darktable

**Comment by GLLM** [comment]
Hi !
Thanks for the tip

From a pure UX/UI standpoint, it'd be reaaaally nice to have this integrated somehow in the UI, and to be able to push a parameter for it (a folder for instance), instead of forcing the whole script to run on my 70k pictures collection :)
Nice to have would be a live user feeback advising _Analyzing xyz / zzz pictures_

But I've ran it, and it seems to find non existing pics, but at the end I don't know how many were found & removed ;-)
PS : got as many "Error: no such table: masks_history" errors as I have file removed

Thanks
GLLM

**Comment by phillies** [comment]
I second that. I recently moved from Lightroom to darktable and the #1 feature I miss is refreshing my collection. I usually have a folder on my disk where my images are. I copy them manually from several sources and in Lightroom I just click "rescan folder" and get a message how many new images were found and how many were removed. A feature like that would be really useful.

**Comment by drbeco** [comment]
Darktable would improve immensely with this feature. A simple button to trigger a "reality check" on database. I can't agree more with @GLLM , fom the UX/UI standpoint. 

The devs are taking their database too seriously. The users (photographers) are much more interested in the files, they are the real thing. If the database can't easily update itself to mirror the real folder, it is just a useless database.

I've read many blogs and help before comming to find this repo, and in all of them experts tells users to "simple don't delete files outside darktable and you will be fine". This is a lazy solution. Of course being able to delete files from other viewers (faster viewers than darktable, to "clean the folder", is an excelent option).

Take a look at "calibre" (open source for collection of books).

Please, kindly reopen this feature/issue.

**Comment by abruenin** [comment]
+1 from me. I try to use Darktable as my primary photo editing software, and I always search for that feature. I think, this is perfectly implemented in Digikam or ACDSee, where I can choose to manually refresh the folder or leave it on Auto. This is not only about removing non-existing images. Also new images should be found.
And to make it even better, subfolders should be added and removed automatically. So I could add my main directory for new photos. When I add new folders with images, they should just appear on manual or automatic refresh.

**Comment by toddmedema** [comment]
Following up here as I'd also love to see this. The shell script execution on WIndows doesn't work. (or if it does, it requires a ton of extra setup - Windows command line won't let you execute shell scripts, and trying to execute it on the Git command line tool requires you install sqlite3 which doesn't seem possible, so the only remaining idea I have would be to install full Windows Linux subsystem, which is too much work)

**Comment by fulldecent** [comment]
A workaround here is to delete your darktable catalog and then reopen the app and reload your (remaining) photos.

If you were using the preference "STORAGE / SIDECAR / SAVE ON EACH EDIT" then all your edits are saved in the sidecar XMP files.

The ratings are NOT saved in the sidecar files and they would be lost with this workaround. (Maybe it would be nice if the ratings were saved in the sidecar, but I digress.)

This workaround doesn't help for lots of people. But it helped for me so I'm sharing it.

**Comment by ptilopteri** [comment]
ratings are most certainly saved in the accompanying xmp files

**Comment by fulldecent** [comment]
My experience is that XMPs do not come from rating files. Here is my walkthrough of that.

(Audio is muted in video by default on GitHub)

https://github.com/darktable-org/darktable/assets/382183/94578c64-3a7d-4a09-9c94-5bfc45a10b0e


But if you happen to edit a file then perhaps the rating will go into the XMP at that time.

**Comment by fulldecent** [comment]
Another workaround here for people is that you can open the darkroom file in DB Browser for SQLite. And you can delete things there. You will VOID your warranty if you do this and don't ask me for any more details about it.

**Comment by ptilopteri** [comment]
recording the editing of images is one of the reasons for xmp files and rating is an editing action.  if you are referring to rating an image in a different application, why would one expect those actions to be recorded by darktable in the xmp file?

**Comment by fulldecent** [comment]
I don't care about using other applications to do things. I am concerned with rating images inside darktable.

Currently it does not (by default) save my ratings into the side car files. For me that's unfortunate.

For example, separately, I was using Lightroom. I used it only for rating photos and moving them across directories. Apparently no other software does that. Today Lightroom stopped running on my computers (because I block network connections, and requires to phone home). Lightroom also did not save all my ratings out to sidecar files. This means all the time I spent on ratings could be lost. When I'm looking at darktable I am hoping that I wont be screwed again, so I was hoping that my ratings in here would all be saved to sidecar files.

**Comment by ptilopteri** [comment]
> I don't care about using other applications to do things. I am concerned with rating images inside darktable.
> 
> Currently it does not (by default) save my ratings into the side car files. For me that's unfortunate.

yes, unfortunate that you do not understand that darktable does save ratings to xmp file when applied within darktable.  DARKTABLE SAVES RATINGS TO XMP SIDECAR FILE.

**Comment by ptilopteri** [comment]
> > DARKTABLE SAVES RATINGS TO XMP SIDECAR FILE.
> 
> @ptilopteri Being calmer and more polite has never hurt anyone. 🙂

he didn't get it the first time :)  
and I am tooo old and cranky to be much more poleit.

**Comment by kmilos** [comment]
> For the avoidance of doubt: once a sidecar file is created (whether ON IMPORT, or ON EDIT then after an edit) any ratings changes will be immediately written to that sidecar file.

Instead of faffing w/ semantics, perhaps there is a new approach to be proposed: write the sidecar on rating (or some other lightroom) change even if it doesn't exist (silently, i.e. treat lightroom changes as ON EDIT, or as a 3rd option)?

**Comment by fulldecent** [comment]
@kmilos I would like that change. Personally I think that changing a rating is an "edit". (Ignoring that others software like Lightroom treats edits and flagging differently.)

However, still, the current wording is incorrect. The file is not written on edit when you select "write... on edit". Instead the file is created on first edit when "on edit" is selected. And the file is written after every edit (unless NEVER) is checked.

In all cases, the choices are still: don't ever make sidecar files / create sidecar files on first change / always create sidecar files. With default as "always".

**Comment by gael-vanderlee** [comment]
Any update on the original issue ? I have my pictures on an external hard drive to edit between multiple computers and the desynchronized libraries make it impossible to use.

**Comment by wpferguson** [comment]
@gael-vanderlee your ESP must be working overtime.  I just merged a lua-script, https://github.com/darktable-org/lua-scripts/pull/468, that scans for missing images and/or missing film rolls and then gives you the option to remove the database entries.

If you're on darktable 4.6.x it will appear in your lua-scripts, provided you have `check for updates` turned on in your preferences.

**Comment by gael-vanderlee** [comment]
Well I was hoping to get to it but none of my lua scripts work, I have spaces in my windows username so I think it's related to this and haven't been able to fix it. When manually updating the lua folder with a git pull, I get an error stating that I need the LUA API version 9.3.0 or later, and I think the current darktable version (4.6.1) only has 9.2.0... Oh well.

**Comment by wpferguson** [comment]
4.8 comes out next week with API-9.3.0

**Comment by gael-vanderlee** [comment]
Oh great, thanks for the help !

**Comment by gael-vanderlee** [comment]
Couldn't get the script to work, had to re import the library. 
But even that isn't enough, since certain things are not synced beyond the deleted images. Duplicated images for instanced are not detected. Darktable is unsuable for me for now as long as I get database sync issues between devices.

**Comment by MatzeG1t** [comment]
> Darktable would improve immensely with this feature. A simple button to trigger a "reality check" on database. I can't agree more with [@GLLM](https://github.com/GLLM) , fom the UX/UI standpoint.
> 
> The devs are taking their database too seriously. The users (photographers) are much more interested in the files, they are the real thing. If the database can't easily update itself to mirror the real folder, it is just a useless database.
> 
> I've read many blogs and help before comming to find this repo, and in all of them experts tells users to "simple don't delete files outside darktable and you will be fine". This is a lazy solution. Of course being able to delete files from other viewers (faster viewers than darktable, to "clean the folder", is an excelent option).
> 
> Take a look at "calibre" (open source for collection of books).
> 
> Please, kindly reopen this feature/issue.

I came to use darktable after skipping Lightroom. The rescanning of a collection is truly the first downside of DDT. All was said already. The user need is there to rescan the collection - why do the product owners/developers ignore this need? I understand the purpose of the library. Its great - but the user needs a simple way to add photos to a collection.
The database for the collection should keep all the past edits and just add new pictures. If the architecture doesnt allow this, thats a pitty.  The DT team should ignore the demands of the user. If the community even starts writing scripts for it, you could consider just offering this functionality. 
Open source tools really rock! But sometimes they lack the User perspective and focus too much on technology perspective.
Lets talk :) Make a survey, pls provide pro/cons of this feature request.
Thanks!

**Comment by wpferguson** [comment]
use --library :memory: if you don't want the database.  Just make sure you have XMP files set to always.

**Comment by MatzeG1t** [comment]
> use --library :memory: if you don't want the database. Just make sure you have XMP files set to always.

thanks for your reply. XMP files should store the changes and metadata of a RAW file. Why would I need XMP files for all images I imported in a first step? 
Would this proposed setting help to have an updated collection? So when I delete RAW files after editing, will the skulls disappear? 

Btw skulls are quite negative metaphor for users. Its like something bad happened and might imply the user did something wrong. Whereas the user just cleaned up files but DT is technically not finding a certain RAW file it it's "outdated" collection image index :(  
After a successful image review/edit workflow my lighttable looks like this 

<img width="406" height="264" alt="Image" src="https://github.com/user-attachments/assets/814f4ac9-067e-462d-bd94-13d2222db349" />

instead of showing me only my photos :) 
Unfortunately not even "re importing" cleans up the skulls🩻. WHich most likely has a good technical reason but from a users perspective DT isn't in a state according to the users expectation nor is it suitable for the task of having a clean lighttable (DIN 9241-110). If you wanna take the perspective of Nielsen&Norman and the 10 Usability heuristics:  these 2 principles aren't met
[2: Match Between the System and the Real World](https://www.nngroup.com/articles/ten-usability-heuristics/#toc-2-match-between-the-system-and-the-real-world-2)
[3: User Control and Freedom](https://www.nngroup.com/articles/ten-usability-heuristics/#toc-3-user-control-and-freedom-3)

It would be awesome if DT UI development could consider testing user facing features against usability standards and more importantly against user needs which are expressed in a variety of forums.
I don't wanna close with "just critizising" :)  I would be happy to get into personal exchange and support, if the DT team wants to explore on issues like this or other user feedback to ensure DT is a great open source alternative to commercial tools what it technically already is 👍

**Comment by TurboGit** [comment]
If you delete the RAW after editing for sure you don't need Darktable at all. You are probably looking for another tool so don't loose your time.

**Comment by MatzeG1t** [comment]
> If you delete the RAW after editing for sure you don't need Darktable at all. You are probably looking for another tool so don't loose your time.

Thanks for your suggestion. I don't loose time - I'm trying to understand the target group of darktable. Why would I keep RAW files "forever"? I mean, darktable has functions in the UI that remember users of Lightroom - thats why a few switch to darktable maybe. 

I will give darktable RAW editing a try at some point in time but right now RawTherapee is fine for me. Only the "mass editing" of tags isnt possible, that's why I checked out darktable actually =)

**Comment by TurboGit** [comment]
> Why would I keep RAW files "forever"?

Do you see any photographers in the analog world throwing away the slide films?

**Comment by wpferguson** [comment]
I have all the RAWs I've ever shot.  As darktable progresses, sometimes I go back and edit those old RAWs and can pull more out of them than I could before.

I also have lots of film and slides

**Comment by drbeco** [comment]
Option/choice is the keyword here. Having the option would be great for those who need it, and would be harmless for those who don't delete their raw files never. (And if somehow you once in a lifetime find yourself in need of deleting a raw , maybe duplicity or any reason, you would also have the option to update the db)

**Comment by wpferguson** [comment]
Instead of continuing to necropost, please open a new issue so that we can look at it again.  This issue is 6 years old and a lot has changed since then.
