### ISSUE TITLE
Resize width not functioning in lightable

### ISSUE THREAD

**Issue by gciccarelli3** [darktable-org/darktable#3707]
Lightable mode of darktable does not allow or automatically resize all three panels to the width of the screen- it's too wide and I can't see the left "import" panel, the center thumbnails, and the right "select" gui.  When in darkroom for a photo, the whole window can be resized, so it's ok.

ubuntu 19.10
dell xps 9570
gnome 3.34.1
darktable 3.0.0-rc2, compiled myself from the release

**Comment by Nilvus** [comment]
Not sure to understand but it's related to Gtk if you talk about resizing the whole window and I don't see why this can be in darkroom or lighttable one. I use same release and Ubuntu 19.10 also, and I don't have any problem about resizing.

Could you check two things :

- Which side panels size you have on preferences options ?
- Close darktable and move your darktablerc file (to keep it at a backup but let darktable create a new one) and restart darktable. See if your problem is always here or not with a new darktablerc file.

**Comment by gciccarelli3** [comment]
Currently 350- which is a setting that takes effect if I close and reopen.
I experimented with smaller sizes.  The whole window does allow resizing
but only up to a minimum width.  The center panel in light table is not
shrinkable below a minimum amount- but that's true in the 2.6 release too-
I just never noticed it.  I think the issue is that the font size of the
side panels is ~18 instead of a smaller font, so to see enough of the text
I have to make the side panels large.  Because the center panel can't be
re-adjusted except by way of resizing the whole three panel display, and
the center panel has a minimum width, the whole gui doesn't fit right on
the screen.
