### ISSUE TITLE
FIXME: message for tone equalizer

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#3714]
playing around with tone equalizer and profiled denoise resulted in following message after zoom in to 100%:
FIXME: module `toneequal' changed the roi from 3342 x 3012 @ 2727 / 2185 to 1624 x 1294 | 3586 / 3044 but doesn't have distort_mask() implemented!

**To Reproduce**
Steps to reproduce the behavior - i'm trying fo find minimum reproducible scenario.

**Screenshots**

**Platform (please complete the following information):**
 - OS: this is darktable 3.0.0rc2+76~gf6026a1fc-dirty
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by aurelienpierre** [comment]
Tone equalizer deals with coordinates mapping internally, since the input needs to be padded with original data if the view is zoomed in (so there is no geometric distorsion). Not many modules have a distort_mask() function (except the obvious perspective corrections), so I did not really understood what I needed it for. I will ask around.
