### ISSUE TITLE
vignette after splittoning

### ISSUE THREAD

**Issue by herbert-50** [darktable-org/darktable#3761]
I often use the modules vignette & splittoning for black&white photos to create an "old" look.

In darktable 2.6  vignetting is done first followed by splittoning in the pixelpipe.
In darktable 3.0 the order has switched.

The disadvantage is that the dark parts of the vignette are not toned and becomes a black color.

I think the order of version 2.6 is the real one. In the "analogous" world the first is the vignette, which is produced from the objectiv and then comes the toning, witch is produced from the photopaper.

**Describe the solution you'd like**
I dont know the reason for the toggle in darktable 3.0, but i think the right way is to change the order to "first vignette and then splittoning".

**Describe alternatives you've considered**
I know, in 3.0 it is possible to change the order of the pixelpipe. But this has to be done for every picture. Creating a style does also not help (see Issue #3703).

**Comment by junkyardsparkle** [comment]
For modules like these, I think different people will probably always have different ideas about what the "real" order should be (for simulating realistic lens vignetting, the module should really be immediately after cropping), so the real solution is to provide a way for users to apply the ordering they want more easily (as you noted).

That said, I agree that the former relationship of these two modules makes more sense, but I don't know if the default ordering is negotiable at this point.

**Comment by aurelienpierre** [comment]
split-toning has not been given a lot of thought because it needs to work after a gamma/EOTF has been applied, therefore after the output colour profile conversion, which is awful since its output becomes then dependent of the output colour space, so it will change if you export for web or for print. 

To split-tone, I suggest you use the colour balance instead, set the input saturation to 0%, define your tones in offset (shadows) and slope (highlights), then set the opacity between 50% and 100%.

As for vignette, it should be but after lens correction to be optically consistent. But vignetting before toning will oversaturates the shadows and push them out of gamut, leading to weird tone and colour transitions, posterization and whatnot. I find more natural to put it just before filmic/base curve.
