### ISSUE TITLE
Histogram → Caching

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3763]
Same as #3575 but for histogram.

Steps to reproduce:

1. Start DT in lightroom mode
2. Open any file in darkroom mode
3. Leave darkroom by pressing 'l'
4. Open any other file in darkroom mode

Notice that histogram of previous image is shown (in top right corner) before current picture is loaded and modules settings applied. Probably it is cached somewhere. Just showing nothing will do fine, showing previous histogram is confusing.

**Comment by Nilvus** [comment]
This is not only the histogram here. When charging an image, waiting it to be charged, you also have some remaining glitch from lighttable.

Anyway, it's good to see which PR are already there as it already exist a PR related to this :  #3683

@AlicVB : I've test you PR and this issue is still there in your PR. Maybe having a blank histogram too when charging an image could be good on your #3683 PR ?

**Comment by AlicVB** [comment]
I've just propose PR #3771 for this one specifically...

**Comment by Nilvus** [comment]
> I've just propose PR #3771 for this one specifically...

I see, you PR was posted just 3 minutes after my reply ;-)

**Comment by Nilvus** [comment]
@aurelienpierre and @TurboGit : this issue has been fixed by #3771 PR merged 3 weeks ago.

**Comment by TurboGit** [comment]
Ok, closing. Thanks.
