### ISSUE TITLE
rolling the mouse wheel inside the histogram used to increase/decrease exposure but now displays individually odd pixel colors

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#3769]
rolling the mouse wheel inside the histogram used to increase/decrease
exposure but now displays individually odd pixel colors

**To Reproduce**
Open an image and display histogram
place mouse pointer in histogram display
roll mouse wheel.

should increase or decrease exposure but instead display odd color pixels

see screen shot:  http://wahoo.no-ip.org/~paka/Screenshot_20191215_112740.png

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. funtoo linux]
 - Version [e.g. 2.6.0]
 - OpenCL activated or no
 - which GFX-card and GFX-driver

**Additional context**
Add any other context about the problem here, for example:
 - Can you reproduce with another dt version?
not available

 - Can you reproduce with a RAW or Jpeg or both?
only tested raw

 - Is dt compiled by yourself? If so which compiler is used? Which options?
using package from darix, openSUSE Tumbleweed
darktable-3.0.0rc2~git102.c09d36df9-2039.1.x86_64

**Comment by timur-davletshin** [comment]
Can't reproduce. Works for me.

**Comment by ptilopteri** [comment]
closing, apparently local issue particular to a single image

**Comment by kanyck** [comment]
No, it's not. The same for me, however it shows up randomly, not every time. Even on the same image it seems to depend upon the modules involved. To my experience it appears more easily if the exposure is the first thing you change. Notably, if you change the exposure not with histogram but with module sliders, it seem to work ok in 100%. 
Please reopen.
https://yadi.sk/d/tJVEtBo9jpEYlg

**Comment by elstoc** [comment]
I've had this too. Happened when I was testing dynamic shortcuts (increasing exposure via 'e' plus scroll). It's intermittent though.

**Comment by elstoc** [comment]
Any way I can reopen this? I've found a way to consistently reproduce it: 

1. Create a duplicate of the exposure module, 
2. click on the previous entry in the history (prior to the module duplication)
3. drag on the histogram. 

The problem is that darktable is trying to update the duplicated module (as can be seen by the fact that the duplicated module name reappears in the history), but that module is no longer present in the UI. I can probably resolve the problems with dynamic shortcuts as part of my PR to resolve https://github.com/darktable-org/darktable/issues/4285 but I don't yet understand how the histogram-dragging does its stuff.
