### ISSUE TITLE
Problem with icc profile generated with displayCal/argyllCMS

### ISSUE THREAD

**Issue by srednax** [darktable-org/darktable#3830]
Hi there, I have recently worked on getting more correct colors, and to achieve that I enabled colord and generated a icc profile using diaplayCal/argyllCMS with my Spyder 4 device.
However, darktable does not work correctly with the profile. Here is a screenshot of darktable with that profile enabled:
![80258475_10157689851128548_3307333295632547840_o](https://user-images.githubusercontent.com/3184467/71321621-7db9c680-24bc-11ea-860c-cf39dea6a6fe.jpg)

My system otherwise works fine with this profile, including browsers, image viewers (gwenview, digikam, okular) etc. And if I switch to the profile while displaying a file in dt, it also looks correct, the problem only appears when a file is rendered in dt with the profile active.

I unfortunately can't attach the profile, but it can be downloaded here: http://nc.alweb.dk/index.php/s/NFdxDym57JywqjG

Darktable version: 2.6.3
System information: Archlinux, fully updated.
Dell Latitude E7440

**Comment by johnny-bit** [comment]
The profile contains LUT, which darktable isn't too keen on using, since it uses matrix math rather than luts for color correction. The switch of profile recognizes that it can't really work and on stderr you should have somm mesage about switching to sRGB profile internally.

PR #7531 should nicely "fix" the problem.

Also - closing since the generated icc file isn't really "valid" from dt standpoint. Generate icc without lut and it should work without problem.

**Comment by srednax** [comment]
Thank you very much for explanation and work on this! :)

onsdag den 30. december 2020 18.34.35 CET skrev Hubert Kowalski:
> Closed #3830.
