### ISSUE TITLE
Levels (Levels RBG): double set of sliders like in Capture One

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#3848]
I believe it could be nice to have a double set of sliders in modules "Levels" and "RBG Levels" as in Capture One

![Cattura7](https://user-images.githubusercontent.com/43290988/71414371-f2286d00-2656-11ea-863c-4e2c89a75283.JPG)

In C1 the sliders below have the same behaviour as in DT. You can increase contrast an change luminosity. 
But with the upper two sliders, you can also reduce contrast, which can't be done in DT.

Marco

**Comment by MStraeten** [comment]
try the new tone equalizer, there you can do this even more detailed

**Comment by todd-prior** [comment]
Better use for double sliders is as in Picture Windows software....top one applies opacity to any masked area and rest to overall image.so you can apply dual opacity of an effect from one module....

**Comment by aurelienpierre** [comment]
What's the purpose of reducing contrast in image ? I mean, what is the final artistic goal ?

Trying to reproduce some feature from some other soft is not good design, there are better ways to achieve the contrast reduction in darktable, that are more consistent with its pipeline/workflow. But first, we need to know what the true need is (tone mapping ? vintage faded look ? softening ? something else ?)

The levels module is quite simple, adding this feature is not very difficult, yet it's not the direction we are taking, since it's grounded into the display-referred workflow, assumes grey = 50%, and is not compatible with HDR scenes.

**Comment by Mark-64** [comment]
From my previous experience with Capture One, a possible use case is the following:
I do often photograph events and I need to develop lot of pictures. Normally I group them per "scene", where in each scene the light condition is similar. Then I develop thoroughly one picture per scene, then copy paste the history stack to the others and adjust each picture using only levels.
If the picture has still some room in the histogram I use the lower sliders, but If I need to recover some over/under exposure, I use the upper sliders. It's equivalent to use exposure / black, but it's quicker.

**Comment by todd-prior** [comment]
Thanks for the tip I will try that so slope 0 or less offset 100 or more and power 0??  Something like that and it will reset I suspect as if you had hit optimize??

Thanks for the tip I will give that a try…

**Comment by todd-prior** [comment]
I must have mis-understood you...I created a style with the parameters out of bounds and then applied it but they stayed there and I got a white image...must be doing something wrong or I did not understand. I took you to mean there was
 a way to set the colorbalance to adjust the parameters when applied to the image from a style application??
 
Thanks for the suggestion...application failure is likely my ignorance...
 
 
 
Sent from 
Mail for Windows 10
 

From: Aurélien PIERRE
Sent: January 11, 2020 9:12 AM
To: darktable-org/darktable
Cc: Prior,Todd; 
Comment
Subject: Re: [darktable-org/darktable] Levels (Levels RBG): double set of sliders like in Capture One (#3848)

 


Notice that the levels are exactly the same as the color balance "factors" settings, in slope/offset/power mode.

slope = exposure = white, offset = black compensation = black power = grey. 
Since the color balance factors are not bound in UI, you can set them past [0;100]%, which exactly falls back in the use case you describe. The only difference is they work on Y luminance so you won't get the extra (de)-saturation that comes with the RGB
 mode, but saturation can be adjusted separately in the same module.
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
