### ISSUE TITLE
Scroll by scroll wheel, change value by Ctrl+Scroll

### ISSUE THREAD

**Issue by crantisz** [darktable-org/darktable#3857]
**Is your feature request related to a problem? Please describe.**
The thing that annoying me most - is that scroll doesn't scroll! 
Only certain areas are scollable - it's not consistent with user experience. Usually scrolling panels scroll over the entire area

**Describe the solution you'd like**
Look how it made in Blender - mouse scrolls panels by default, but if you like to change a value, you can do it by holding ctrl key:

![Peek 2019-12-25 01-04](https://user-images.githubusercontent.com/1749968/71425856-eec2cf00-26b2-11ea-9c09-ab56af0b590a.gif)

**Describe alternatives you've considered**
I think it's can be as option - so users may chose that behavior they prefer

**Additional context**
Of course, it may be better if interface elements highlights on mouse over, but I see this block doesn't work:
```
#bauhaus-popup:hover,
#bauhaus-combobox:hover,
#bauhaus-slider:hover
```

**Comment by todd-prior** [comment]
Use ctrl alt mouse....default action is set in preferences to scroll values or the panel....

**Comment by crantisz** [comment]
> @crantisz Use ctrl alt mouse....default action is set in preferences to scroll values or the panel....

Why I cannot change it?

**Comment by todd-prior** [comment]
If you switch then the default is to scroll sliders and you have to use scroll bars to go up and down the modules ...
 
Sent from 
Mail for Windows 10
 

From: crantisz
Sent: December 29, 2019 4:07 AM
To: darktable-org/darktable
Cc: Prior,Todd; 
Comment
Subject: Re: [darktable-org/darktable] Scroll by scroll wheel, change value by Ctrl+Scroll (#3857)

 



@crantisz Use ctrl alt mouse....default action is set in preferences to scroll values or the panel....

Why I cannot change it?
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by crantisz** [comment]
> If you switch then the default is to scroll sliders and you have to use scroll bars to go up and down the modules ...

I can't understand you. If I can change this behavior, where is this setting in the preferences?

**Comment by todd-prior** [comment]
So you toggle in preferences what the default action is either to scroll the modules or scroll sliders and the alternate action is ctrl alt scroll....eg if set to scroll modules then ctrl alt scroll will do the sliders and the opposite....clear??
 
 
Sent from 
Mail for Windows 10
 

From: crantisz
Sent: January 4, 2020 11:56 AM
To: darktable-org/darktable
Cc: Prior,Todd; 
Comment
Subject: Re: [darktable-org/darktable] Scroll by scroll wheel, change value by Ctrl+Scroll (#3857)

 



If you switch then the default is to scroll sliders and you have to use scroll bars to go up and down the modules ...

I can't understand you. If I can change this behavior, where is this setting in the preferences?
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by crantisz** [comment]
> So you toggle in preferences what the default action is either to scroll the modules or scroll sliders and the alternate action is ctrl alt scroll....eg if set to scroll modules then ctrl alt scroll will do the sliders and the opposite....clear??

Just Ctrl, without alt.

**Comment by nijoakim** [comment]
I think what todd-prior is trying to say is that there is an option in the preferences, "miscellaneous/mouse wheel scrolls modules side panel by default". If you select that one, scrolling won't change values any more. I don't know of any way to map ctrl+scroll wheel to control the values though.

**Comment by todd-prior** [comment]
@crantisz @nijoakim What I was actually trying to say is you can set it either way in preferences. So scroll panels or scroll values. So best to set for your preferred action but whatever you do set then you can invoke the opposite by Ctrl Alt scrolling....so you don't have to live with either or...just set it initially for the most used action.......so if set to scroll panels and you want to scroll a value hold ctrl alt and scroll and the mode will be on the slider....the opposite is true if you have it set in preferences as scroll values then it will scroll panels if you hold down ctrl alt and then scroll......does this now make sense....

**Comment by todd-prior** [comment]
@crantisz @nijoakim As an aside I have it set to scroll values because I like to interact with sliders that way and then if you just mouse off the screen to the right and scroll it will move the panels as if you were using a scroll bar.....so this is my compromise but the ctrl alt toggle is there if you need it....

**Comment by dterrahe** [comment]
Closing as existing functionality to achieve the desired effect has been explained. Thanks!
