### ISSUE TITLE
[Focus Peaking] Some images it doesn't show and shows when you do a ctrl+w

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3901]
darktable-3.1.0+221~ga8695754f-win64
Opencl = On
Take the first image for instance focus peaking does not show.
![image](https://user-images.githubusercontent.com/1119439/71545662-fbe20580-29b3-11ea-8c78-be245216391f.png)

Doing a ctrl+w or ctrl+alt+w does show the peaking, but the focus points shown with ctrl+w don't always match. The peaking draws several times to get to a final peaking display.
![image](https://user-images.githubusercontent.com/1119439/71545685-35b30c00-29b4-11ea-8e50-2ddf2d82f37f.png)
The watermark gets picked up in peaking too.

Next consider the selected image in lightroom and see its peaking.
![image](https://user-images.githubusercontent.com/1119439/71545750-ac500980-29b4-11ea-9667-daf75b943df0.png)
The peaking shown is different in the ctrl+w and the ctrl+w seems to be more accurate for whats in focus.
![image](https://user-images.githubusercontent.com/1119439/71545781-0781fc00-29b5-11ea-8098-0788c37bf831.png)

**Comment by GrahamByrnes** [comment]
I'm yet to see any focus peaking display under Windows...

**Comment by aurelienpierre** [comment]
1. The focus peaking uses another method than the focus points, it's normal that they don't always show the same results (especially in noisy images),
2. The focus peaking computes gradient stats on the image, and shows the outliers of the hyper-laplacian distribution of gradients. If no overlay appears, it means all the gradients in the image are close to the average, so we probably don't have a focused area,
3. The focus peaking depends on the image scale, and, since small scales tend to be smoothened by interpolation, sharpness might not be identified properly. Not much we can doe, except compute it on the full scaled image, which will be crazy slow in lighttable.
4. The sharpness is detected by contrast measurement, with an algorithm that has a low sensitivity to local contrast (like harsh transitions between different luminosity areas). However, it is still a bit sensitive to local contrast and might be fooled by harsh transitions and noise. It's by no mean perfect, but just a fair guess of the focal plane position.

**Comment by aurelienpierre** [comment]
> I'm yet to see any focus peaking display under Windows...

You need to build the master yourself or wait for the package of 3.0.1.

**Comment by chhil** [comment]
If nothing can be done, please feel free to close the issue. I have understood the limitations pointed out by @aurelienpierre.

**Comment by jenshannoschwalm** [comment]
Why don't you close the issue ..

**Comment by chhil** [comment]
Would this be considered as a bug?
> Do note that watermark gets selected in peaking.

**Comment by aurelienpierre** [comment]
> Do note that watermark gets selected in peaking.

If your watermark is sharp, it goes in the peaking. The focus peaking is computed on the final image.
