### ISSUE TITLE
Provide an appimage ?

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#3925]
I don't like Appimage, Snap, Flatpak and such bloatware packages for general use. However, I think providing an Appimage of the master branch (nightly build) could help us get more tests of the dev version by people who don't know how to compile (so, more early feedback) or want a taste of the new release before it appears on their distro repository.

Appimages can be [built from Travis CI](https://docs.appimage.org/packaging-guide/travis.html). We could also consider providing them for PR in order to test bug fixes for bugs that don't reproduce easily on devs computers.

**Comment by TurboGit** [comment]
Would be nice indeed !

**Comment by Dziban-dev** [comment]
this is great, i have not been able to test Darktable 3.0 since i work on Deepin Linux, Debian based however whe i try to install the .deb package for Debian it doesn't start because the package manager detects a "broken dependency: libc6" which is installed. but don't know how safe it is to update to a newer version.

**Comment by ocumo** [comment]
**+1 for an Appimage.**

For Ubuntu 20.04 LTS users, there is no way to use even v3.2.1 because existing 3rd party packages offered for ubuntu 20.04 in the darktable.org/install page just do **not** work - a dependency **hell** pops, be it with the .deb binary package, or with the PPA.

Unfortunately, _no one seems to take ownership of those_.  And yet, darktable.org keeps offering the false "solutions".  Why?  At least could someone remove the section in your web page that offers support for v3.2.1 on Ubuntu 20.04 LTS, because it is not true, it doesn't work. **(Please, can someone tell where is the appropriate place to report the problem of false information in darktable.org webpage?)**

Snap is a very hated method, for a big number of reasons. And by any standards, every single comparison between Snap and Appimages, there is no question about the superiority of Appimages, even considering both "bloatware packages".  At least as bad as Snaps is the horrible Flatpak system.   All in all, one Appimage === one file. Yeah, big, but: No installation, no directories, no dependencies, no bullshit.  Run it from whatever place, even a USB stick.  That's the way to go!!

**Comment by johnny-bit** [comment]
@ocumo - 3rd party means exactly that: a 3rd party makes packages and may or may not be related to the project itself. If you'd like to ask to stop advertising 3rd party, then you can do so in the separate repo: https://github.com/darktable-org/dtorg/issues

**Comment by ocumo** [comment]
Thanks for the link.
For all intents and purposes, darktable's official documentation is pointing to a dead end.

It's not about stop advertising _3rd party_: It's about stop advertising _wrong information_, whatever party it comes from.  That's different!

But hey, deflecting towards a semantics discussion is not my goal. Thanks anyway

**Comment by johnny-bit** [comment]
We could and should do that: AppImage, Flatpak, Windows Package & OSX package are (probably all) buildable via CI.

**Comment by johnny-bit** [comment]
Since I recently fixed windows nightly... the appimage might be next on my list :D

**Comment by w-barath** [comment]
> Since I recently fixed windows nightly... the appimage might be next on my list :D

I would always download the latest appimage, and give quality feedback, if it existed.  But I only use Darktable maybe a dozen days a year, because the UI is so spectacularly painful.  Nearly nothing behaves in an intuitive fashion.  History doesn't show history, adding / exporting files is cryptic, adding/modifying/removing filters has what I can only call random behaviour.  When it works, it's brilliant, but I spent 84% of the time doing things over and over and crossing my fingers that it actually does something akin to what the UI suggests it might, undoing things that didn't go as expected, and the history doesn't revert... instead you hold down CTRL-Z and wait for it to perhaps retreat to where you'd like to be... So yeah I would love to be able to contribute to improving usability.

**Comment by w-barath** [comment]
> Since I recently fixed windows nightly... the appimage might be next on my list :D

I got excited when I saw that, but then I found the master builds, added the apt repo, installed, and got a fast native up-to-date version.  :-)

@ocumo downloading the .deb and installing it with dpkg or apt directly from the filesystem is not the same thing as using the repo.  All the deps you complained about are resolved automatically if you actually follow the directions to add the repo then install with `apt-get install darktable`

[go to the build server: 
](https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable)

Click your distro.

Click "Add repository and install manually"

Example for Ubuntu 21.04:

```
echo 'deb http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_21.04/ /' | sudo tee /etc/apt/sources.list.d/graphics:darktable.list
curl -fsSL https://download.opensuse.org/repositories/graphics:darktable/xUbuntu_21.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/graphics_darktable.gpg > /dev/null
sudo apt update && sudo apt install darktable
```

**Comment by ralfbrown** [comment]
Does #13331 resolve this issue?

**Comment by johnny-bit** [comment]
Not yet. While script is there the issue can be closed once appimage is part of nightly builds for testing

**Comment by yhm3ps1jfp76nkd** [comment]
Since I closed #13776, what do you think about Flatpaks as an alternative?

**Comment by ralfbrown** [comment]
We now have an AppImage in the nightly build.

**Comment by TheAssassin** [comment]
Is there any reason AppImages are not provided from the release builds? They work really well.

... by the way, OBS can build AppImages, too.

**Comment by da-phil** [comment]
> We now have an AppImage in the nightly build.

do they work for you? At least I've tried the [latest nightly](https://github.com/darktable-org/darktable/releases/tag/nightly), but it does not execute (I made it executable before).

**Comment by TheAssassin** [comment]
I can launch the latest nightly AppImage on Ubuntu 22.04 just fine.

**Comment by da-phil** [comment]
Maybe I forgot to mention that I'm (still) using ubuntu 20.04, maybe that's the issue?
Or how to you launch the appImage, maybe I also forgot one step?
I just made it executable (`chmod +x <appImage>`) and then launch it from terminal. It quits w/o any text output in the terminal.

**Comment by TheAssassin** [comment]
I launched it just as you described it.

**Comment by da-phil** [comment]
On my ubuntu 22.04 system it works too, so I'd expect that the appImage contains some specifics which only work on ubuntu 22.04, maybe glibc compatibility? (tbh, I never used appImages before, so I don't know anything about it)
