### ISSUE TITLE
switch back to 2.6.x order of pixelpipe

### ISSUE THREAD

**Issue by herbert-50** [darktable-org/darktable#3971]
**Is your feature request related to a problem? Please describe.**
In  #3761 i have describe the problem with the new (3.0) order of the using vignette and splittoning.
Now I have the next problem:
I use the module monochrome to convert a picture into black and white. If I use a red or green filter the image gets darker. So I use the module levels to compensate the loss of light. In version 2.6.x it was executed **after** the monochrome module. Now with 3.0.0 it is run before, which leads to some problems. 
![darktable_113](https://user-images.githubusercontent.com/57417616/71621750-73d94700-2bd1-11ea-956b-667676185f6f.png)
![darktable_114](https://user-images.githubusercontent.com/57417616/71621751-73d94700-2bd1-11ea-92a2-6921a3e1dec9.png)
![darktable_115](https://user-images.githubusercontent.com/57417616/71621752-7471dd80-2bd1-11ea-97f4-a3cb279da992.png)
![darktable_116](https://user-images.githubusercontent.com/57417616/71621753-7471dd80-2bd1-11ea-992a-bb52d5d8c8b3.png)

All other modules for tonecurve manipulation are also executed before monochrome. The only solution is moving the module in the pixelpipe and this has be done after each usage.

**Describe the solution you'd like**
I have the impression that the arrangement of the pixelpipe in version 2.6.x was very well thought out. I never missed the order change function.
In 3.0.0 more theoretical aspects (monochrome is a creative module) were considered. This is not good.

Is it possible to use the Version 2.6.x order of the pixelpipe in version 3.0.0 by default? Perhaps via an option like 'auto-appy sharpen' .

**Comment by TurboGit** [comment]
This will be possible with #3908.

**Comment by MStraeten** [comment]
you can move the module to the pixelpipe position where you need it - shift+ctrl+drag.

**Comment by junkyardsparkle** [comment]
You may also want to consider trying out the [color LUT module](https://darktable.gitlab.io/doc/en/color_group.html#color_look_up_table) for mapping to monochrome... it's more versatile than the monochrome module, and happens early in the processing order. You can start with the Helmholtz preset and adjust color weighting from there.

**Comment by GrahamByrnes** [comment]
The fact it comes before or after in the pixel-pipe doesn't stop you going back and making compensating changes... the pipe determines the order of computation, it doesn't constrain the order in which you make changes. It does matter if you want the changes to be scene-referred or display-referred.
Try using channel mixer, with a custom blend. In the end, for making B&W it comes down to choosing a linear combination of RGB, either scene-referred (if before the non-linear steps like base-curev/tone curve/filmic rgb etc) or scene referred if it comes after.
Channel mixer now comes before...
However, note that in my arrogant opinion, the proportions you set in channel mixer should add to 1, and there should be no negative values allowed. It's currently a mess, but you can create a few presets and save them.
That said, I'm not sure there is a perfect solution: there are situations where eg the red component or the blue component is much higher than the others, so your exposure settings change dramatically once it is averaged with the other colours. So inevitably, things change when you convert and you will need to adjust for that in Exposure or elsewhere. I have shot theatre where the lighting was almost entirely red... in cases like that, you have to create a special style that takes account of this through colour balance, exposure, channel mixer...

**Comment by herbert-50** [comment]
Yes of course, I can use the channelmixer or the new lut module or I can use the color zones or  the color lookup table. But that is not the point. These modules produce B&W, but they works not in the same way.
The old pixelpipe was well designed and with 3.0.0 it has changed, so that things, that worked in 2.6.x will not work in 3.0.0. See also #3761 .
@MStraeten : Yes, I know shift+ctrl+drag, but I have to do it for every picture! And when I use a style with monochrome & levels, the pixelpipe will be reordered after assigning the style (see #3703).

**Comment by aurelienpierre** [comment]
>  In 3.0.0 more theoretical aspects (monochrome is a creative module) were considered. This is not good.

Yes it is. Messing up the contrast while switching to black and white reeks of bad design. You shouldn't have to correct the lightness because of B&W conversion.

What @GrahamByrnes suggests is good. Notice that, in the linear part of the pipe, changing the contrast before or after the B&W conversion through channel mixer gives exactly the same result, because the white remapping is a simple scaling, and since RGB values are encoded linearly.

Proof:

* B&W conversion (channel mixer) is Grey(RGB) = a * R + b * G + c * B, with a, b, c real constants
* White scaling (RGB levels) is Contrast(RGB) = d * RGB, with d a real constant.

Contrast(Grey(RGB)) = d * (a * R + b * G + c * B) = a * (d * R) + b * (d * G) + c * (d * B) = Grey(Contrast(RGB))

@herbert-50 I think you are trying too hard to hold on to bad tools.

**Comment by herbert-50** [comment]
I have tested a bit further and I may be wrong with my claim that the old sorting is better.
I am not very familiar with mathematics and maybe my idea of ​​the pixel pipe is a bit naive.
My idea is that once details are lost, they cannot be restored.
However, the tests show something different. Here is another example with more structures.

![Auswahl_162](https://user-images.githubusercontent.com/57417616/71763515-113bc000-2edd-11ea-8dd7-eb08d54a2757.png)

Levels is executed BEFORE monochrome and Details are not lost.

But switching of the monochrome module shows, that levels module clips details:

![Auswahl_163](https://user-images.githubusercontent.com/57417616/71763534-4a743000-2edd-11ea-85a9-324cdd343072.png)

The monochrome modules restores details that are clipped from levels. The monochrome-levels combination seems magical. The difference between BEFORE and AFTER in the pixelpipe is not so big.

The situation with other modules in combination with monochrome is different.
![Auswahl_164](https://user-images.githubusercontent.com/57417616/71763709-3d584080-2edf-11ea-858e-8e8e87f12d3c.png)
![Auswahl_165](https://user-images.githubusercontent.com/57417616/71763727-72fd2980-2edf-11ea-94ca-267124586780.png)
![Auswahl_166](https://user-images.githubusercontent.com/57417616/71763741-a93aa900-2edf-11ea-93fb-bf871c06d161.png)
![Auswahl_167](https://user-images.githubusercontent.com/57417616/71763753-cd968580-2edf-11ea-8863-744c1215d563.png)

I am confused. Before 3.0.0, I thought color curve and levels do the same if I only move the upper and lower points in the curve. This is the case in other image processing programs. And if I execute them AFTER monochrome I get comparable results in darktable too. But not so in the case BEFORE.

![Auswahl_168](https://user-images.githubusercontent.com/57417616/71764132-3122b200-2ee4-11ea-97ca-e41aca2a9dd2.png)

What is the "magic" of the levels module?

**Comment by herbert-50** [comment]
> @herbert-50 I think you are trying too hard to hold on to bad tools just because you are used to them.

I'm sorry, but it is difficult for a simple user to distinguish a good tool from a bad one. Channel mixers and monochrome appear equivalent and monochrome is easier to use. And before 3.0.0 it worked for me.
Shouldn't  monchrome not be used anymore?

I suspected that the problem might still occur with other modules.

**Comment by elstoc** [comment]
The comments in the code suggest that monochrome has been moved to the end because it's a 'creative module'. Perhaps there are some other technical reasons but it's not clear.

I preferred to have monochrome earlier in the pixelpipe as well so that I could subsequently modify an already-monochrome image with the tone curve (though I'm not sure I'd go so far as to have it as early as it was - I'd still prefer it in the display-referred part of the workflow). Now monochrome comes after any tool to adjust tones, so I'm basically modifying a colour image with the tone curve that's then converted to mono, which seems less intuitive to me.

Please note that Channel Mixer and monochrome are only equivalent for a single use case (there are lots of tools that will allow conversion to monochrome). Channel Mixer itself is a much more powerful tool and can be put to a number of other uses. The comments in the code suggest that there are good technical reasons for Channel Mixer to sit in the scene-referred part of the pixelpipe.

**Comment by aurelienpierre** [comment]
> The comments in the code suggest that monochrome has been moved to the end because it's a 'creative module'. Perhaps there are some other technical reasons but it's not clear.

"Creative" in this context means the module doesn't retain the relationship with radiometric data and works better after some camera transform (filmic or base curve).

> Now monochrome comes after any tool to adjust tones, so I'm basically modifying a colour image with the tone curve that's then converted to mono, which seems less intuitive to me.

You know that you can still pre-correct the tones earlier in the pipe, and apply monochrome after ? You don't always have to setup the modules in the same order they are applied in the pipe (unless you use parametric blending).

> The comments in the code suggest that there are good technical reasons for Channel Mixer to sit in the scene-referred part of the pixelpipe.

The reason is grounded into the maths proof I have written above. Doing linear operations on linear data, you can reorder the operations as you like, the result will be the same. 

>  My idea is that once details are lost, they cannot be restored.

There is no clipping in darktable, no detail is lost until you cross the output color profile module.

> The monochrome modules restores details that are clipped from levels. The monochrome-levels combination seems magical.

I can't tell in detail how monochrome works, but I know it works in Lab, which can trigger a whole lot of issues and unintuitive behaviours. If you are after a monochrome conversion that works the same way B&W film does, you should use the channel mixer module. I even put B&W film emulsions presets in there, so it is mathematically equivalent to simply shooting film and scanning.

**Comment by elstoc** [comment]
> You know that you can still pre-correct the tones earlier in the pipe, and apply monochrome after ?

I know, but because monochrome processes different colours differently it's often difficult to judge the final monochrome tones from a colour image. Often, for example, I'll have a colour image that has almost blown highlights but when I convert to monochrome they become grey (because it's not processing all of the colours equally). So I'll then do final tweaks to the tone using a (monochrome) tone curve. If I'm using the monochrome module, with the new pixelpipe order, I'll *always* move a tone curve after it to do any final adjustments.

> you should use the channel mixer module

I agree channel mixer is more powerful but sometimes just dragging around a circle until it looks good in the monochrome module produces nice results with a bit less effort. It certainly is easier for less experienced users (unless you want to emulate a specific film).

**Comment by elstoc** [comment]
> "Creative" in this context means the module doesn't retain the relationship with radiometric data and works better after some camera transform (filmic or base curve).

I agree it makes more sense in the display-referred section of the pixelpipe, but could the default order within the 'creative' section be changed?

**Comment by elstoc** [comment]
Looks like requests to change the default pixelpipe order are getting rejected because we now have the ability to move manually on a 'per-image' basis. See #4018

**Comment by TurboGit** [comment]
@elstoc : you are tiresome !!! fFankly, have you looked at the PR I have quoted in #4018.

I said there : See also #3908.

I'm working actively on this PR since some time and this is hard stuff to get right, I have already spent lot of time on this issue. Can you at least take 20 seconds to look at pointers given by the devs???

Why people like us to spend time for nothing :(

**Comment by elstoc** [comment]
> fFankly, have you looked at the PR I have quoted in #4018

Yes, but I'm not a developer and don't understand it all. Please don't assume I've not read the Release Notes or the Pull Request. I have (though I've only read the discussion on the PR - I don't understand the code changes). I'm trying to understand the rules around raising issues so that I don't waste anyone's time with future requests. 

Regarding the PR: I don't want to use the entire 2.6 IOP order (since I agree with the vast majority of the changes in 3.0) and I'm wary about creating my own custom order in case I miss out on useful changes to the defaults in future versions. As the Release Notes say, "It is recommended to move a module only if you know what you are doing and what effect it will have on your image." Getting the defaults right means that people don't have to worry about moving modules about as part of their standard workflow.

> @elstoc : you are tiresome !!!
> Why people like us to spend time for nothing :(

I'm trying to contribute to this project as well so please be polite. I may not be able to write code but I can try to suggest changes and contribute to discussions. I hope that I'm making a positive contribution that will not only help me but other users as well.

**Comment by herbert-50** [comment]
@elstoc: I also didn't understand # 3908.
But I understood that something is under development that could solve the problems.
I hope this also solves the problem of not changing the order when applying a style.

I think waiting and see what is coming is the best at the moment.

**Comment by junkyardsparkle** [comment]
> @elstoc: I also didn't understand # 3908.

Basically, It abstracts the module ordering in such a way that it can be saved (as presets in a new darkroom lib) and applied on a per-image basis, and also includes presets for "legacy" (pre-3.0) and "recommended" (post-3.0) ordering. If eventually these presets can be auto-applied and included in styles, it will be a very nice, comprehensive solution to the different things people want to do with ordering. :-)

**Comment by herbert-50** [comment]
Thank you for the explanation.👍🏻

With these changes, all problems with the sorting of the pixel pipe should then be solved.

**Comment by aurelienpierre** [comment]
Done in master. Will be released in 3.0.2 (not sure if it's ready for 3.0.1).
