### ISSUE TITLE
Re-importing a folder ignores second xmp files created for duplicates

### ISSUE THREAD

**Issue by Bbawt** [darktable-org/darktable#3978]
Using the Duplicate function in lighttable mode creates a second xmp file with _01 in the file name. If the photo or its folder is removed under Collect Images, then re-imported, darktable only recognizes the original xmp file and not the second xmp made from the duplicate.  

Darktable Version: 3.0
Windows 10
OpenCL  not activated

**Based on comments below and on pixls.us this seems to be a problem just on the Windows version**

**Comment by airflow2010** [comment]
This bug is a huge problem for anyone who wants to re-import a collection of images, which have already been processed at an earlier time with darktable. For example, when you re-install your computer with darktable and you want to re-import your photo-collection.

Also, this bug has been around for a while without fixing. It has already been reported and described in detail here: https://redmine.darktable.org/issues/12307

The workaround is very cumbersome and errorprone: You first have to separately save your extra sidecar files at another directory, then you have to manually re-create all duplicates, and then you can re-load the content of your sidecars over those duplicates.

**Comment by TurboGit** [comment]
This works for me on Linux. Maybe a Windows issue only?

**Comment by vsz1lu** [comment]
On Ubuntu 19.10 perfectly work. If U move the files to other node: work. If U rename the files (sidecars too): work.

**Comment by Bbawt** [comment]
> This works for me on Linux. Maybe a Windows issue only?

I believe you are correct.  I tried it on a small laptop running 2.4.2 on Linux Mint, and when importing the folder it shows the duplicate images. I installed darktable on my work Surface Pro Win 10 and importing photos with multiple xmps does not show the duplicates.  Seems to be Win version only.

**Comment by Mark-64** [comment]
I confirm the issue on Windows.
I also noticed that when, re-importing, only the images with duplicates have (NULL) in the name.
![Cattura17](https://user-images.githubusercontent.com/43290988/71711711-825a7500-2e02-11ea-835f-470d9e858b8d.JPG)
I think it could be DT not treating correctly duplicates .xmp filenames under Windows, "/" vs "\", or something like that

**Comment by Mark-64** [comment]
Digging in the source code, my guess it could be the function dt_image_read_duplicates() in image.c,
in particular the part under #ifdef _WIN32.
But how to debug this on Windows / MSYS2 ?

**Comment by Mark-64** [comment]
Well, I found the problem. As I thought it's in the function dt_image_read_duplicates() in image.c, the part under #ifdef _WIN32.
The code builds filename patterns:
- filename.ext.xmp
- filename_[0-9][0-9].ext.xmp
- filename_[0-9][0-9][0-9].ext.xmp
- filename_[0-9][0-9][0-9][0-9].ext.xmp
and then looks in the folder for files matching those patterns. Each file found corresponds to a duplicate.
The problem is that the Win32 functions called to find files (FindFirstFileW and FindNextFileW) do not accept such patterns, unlike Linux. The result is that only the first duplicate, the one without _xx, is found.
By the way, the same error is in the function dt_control_delete_images_job_run() in control_jobs.c, I guess with the effect of leaving orphaned .xmp duplicates behind.
Now I need to find a solution.
Any suggestion ?

**Comment by Bbawt** [comment]
> Well, I found the problem.

Thank you for digging into this issue. Hope a solution can be found.

**Comment by Mark-64** [comment]
Created PR #4013

**Comment by airflow2010** [comment]
> Created PR #4013
> Please test it

It's awesome that you could find and fix the problem so fast - thank you!:-) I would like to test the fix, but I assume I would need the complete dev-environment for building on my system to build the executable (which I don't)? If someone can provide the executable, I can certainly do.
