### ISSUE TITLE
Ubuntu PPA would be nice to have

### ISSUE THREAD

**Issue by magicgoose** [darktable-org/darktable#4009]
**Is your feature request related to a problem? Please describe.**
Having an official Ubuntu PPA with darktable packages was good while it lasted. But it seems it's not updated anymore, dt 3.0 was released 10 days ago and PPA is still at 2.x.  
Also, the official recommended way (from here https://www.darktable.org/install/#3rdparty) (which is to use OBS) also has outdated versions (2.6.2): https://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_19.10/

**Describe the solution you'd like**
Revival of https://launchpad.net/~pmjdebruijn/+archive/ubuntu/darktable-release

**Alternatives**
Installing from source. It works but it's less convenient and doesn't do automatic upgrades.

**Comment by Nilvus** [comment]
darktable never had official Ubuntu PPA and third party are, like each year, updated when their maintainers find time to do that. Having an official Ubuntu PPA, why not but that let, at least, two questions:

- Who will update it, want to do it on each release and could quickly, on each release, find the time to do it ? That's just that.
- And more, why not (with same first question) add a Fedora one, Arch/Manjaro one, OpenSuse one, etc ? And what about the fact that these distribs also need to have a package for a version, and another for another, etc.

That's also the difficulty about Linux: too many distribs and versions to maintain. Not so simple.

**Comment by timur-davletshin** [comment]
@Nilvus well OBS partially worked until recent release but @darix didn't reply to my question on https://discuss.pixls.us so I think there is not other option but to build it youself or wait until someone takes his job.

Aside from that I think dead PPAs and OBS should not be mentioned on darktable's webpage.

**Comment by darix** [comment]
God forbid people have vacation and actually use it for resting. I love your attitude so much. It really keeps people motivated to invest their spare time for you!

**Comment by timur-davletshin** [comment]
@darix I thought it was only in Russia they throw out Christmas trees in early March. Wish you to have good vacations!

**Comment by timur-davletshin** [comment]
@darix some other points related to packaging (sure, when you come back from vacations):

1. Debian builds (maybe other have same issue) have empty directory /usr/lib/darktable/tools which should not be there since no tools packages are distributed from OBS.
2. Creators of darktable specifically insist that no capital letter is in the beginning of program's name. So "Darktable" in /usr/share/applications/darktable.desktop should be changed to "darktable".

**Comment by darix** [comment]
0. the real title of the bug should be "wrong package version number for deb builds from OBS" because ... the stuff built inside is actually 3.0 and not 2.6.2 as the version number makes you believe. After someone accepted @cryptomilk's submit request on the OBS the package is actually 3.0.0.
1. the desktop file is from the DT devs themself. 
2. the deb stuff is probably not copied over correctly by @cryptomilk or needs some more fixing. last time I checked it was fine.

**Comment by timur-davletshin** [comment]
@darix you right about release branch (it's 3.0.0 in fact) but stable release branch is 2.6.3. This way or another these packaging issues should be fixed.

**Comment by Nilvus** [comment]
> @Nilvus well OBS partially worked until recent release but @darix didn't reply to my question on https://discuss.pixls.us so I think there is not other option but to build it youself or wait until someone takes his job.
> 
> Aside from that I think dead PPAs and OBS should not be mentioned on darktable's webpage.

Humm, that's was a sarcastic answer I posted. I compile the master version since a year so I don't care about packages (except for help people have the release and don't know/want to compile). And it was sarcastic just because the "PPA" already exists.

This world needs to learn again to wait and slow down. All the best things took time. So I agree with @darix: too many people forget that's all this is made by on their free time. No one here is employed so no one have obligations. This is made when people have time and want to dot that.

People, like free software, are free !

So it is just made as it is.

**Comment by timur-davletshin** [comment]
> Humm, that's was a sarcastic answer I posted.

I believe it will take another day or two for some to sober up and realize that "sarcastic" is not what they think — that was example of sarcastic and probably a bit rude comment. And a little bit of recursion 😆

**Comment by angryziber** [comment]
IMHO, all the builds should be automated, for every tag in the repo, so that machines would do all the work :-)
Nowadays, even GitHub Actions/Workflows can be used for that

**Comment by darix** [comment]
> IMHO, all the builds should be automated, for every tag in the repo, so that machines would do all the work :-)
> Nowadays, even GitHub Actions/Workflows can be used for that

you have no idea how highly automated we have those things already. but even then occasionally manual work is needed.

**Comment by pmjdebruijn** [comment]
@timur-davletshin: "Darktable" in darktable.desktop should NOT be changed to "darktable".

This argument has been had before like five/six/seven years ago, and I don't know where this nonsense is coming from again...

the darktable.desktop text does not appear within the darktable UI, but in GNOME/XFCE/KDE/whatever, there we should follow normal capitalization rules.

And like all other .desktop files, we should just capitalize each word.

**Comment by gscholz** [comment]
@ magicgoose: Instead of waiting for an updated ppa package, you can easily build your own package based on the debian experimental source package like this, does not take more than five minutes:

# step by step instruction how to build darktable 3.0.0 debian/Ubuntu
# package
#
# create directory for package building
mkdir -p ~/src/debian
cd ~/src/debian

# download debian source packages
wget http://deb.debian.org/debian/pool/main/d/darktable/darktable_3.0.0.orig.tar.xz
wget http://deb.debian.org/debian/pool/main/d/darktable/darktable_3.0.0-1.debian.tar.xz

# extract content
tar -xf darktable_3.0.0.orig.tar.xz
cd darktable-3.0.0
tar -xf ../darktable_3.0.0-1.debian.tar.xz

# install tools for building debian packages
sudo apt install build-essential

# install required packages for darktable (debian/control: build-depends)
# split into several lines for better readability
sudo apt install cmake debhelper intltool libcairo2-dev libcolord-dev libcolord-gtk-dev
sudo apt install libcups2-dev libcurl4-gnutls-dev libexiv2-dev libflickcurl-dev
sudo apt install libglib2.0-dev libgphoto2-dev libgraphicsmagick1-dev libgtk-3-dev
sudo apt install libjpeg-dev libjson-glib-dev liblcms2-dev liblensfun-dev liblua5.3-dev
sudo apt install libopenexr-dev libopenjp2-7-dev libosmgpsmap-1.0-dev libpng-dev
sudo apt install libpugixml-dev librsvg2-dev libsecret-1-dev libsoup2.4-dev
sudo apt install libsqlite3-dev libtiff-dev libwebp-dev xsltproc

# build the darktable package
dpkg-buildpackage -rfakeroot -uc -us
cd ..

#install new package
sudo dpkg -i darktable_3.0.0-1_amd64.deb


Guido
