### ISSUE TITLE
darktable 3.0 crashes with dynamic help (the '?' icon)

### ISSUE THREAD

**Issue by ganouyang** [darktable-org/darktable#4010]
Open an raw file (CR2), enable the '?' icon and click on a module title. dt 3.0 crashed with error: An unhandled exception occured.
Screenshot and backtrace file attached
![DT error message](https://user-images.githubusercontent.com/59418292/71734001-7e355400-2e10-11ea-8123-f7a71ee9f94d.jpg)
[darktable_bt_W08SD0.txt](https://github.com/darktable-org/darktable/files/4019815/darktable_bt_W08SD0.txt)

**Comment by rawfiner** [comment]
Cannot reproduce on linux with darktable master.
The exception seems to be triggered within gtk_show_uri_on_window which is the gtk function we call to open the web browser. So, either we are giving it wrong parameters, either it is a gtk bug? 

@ganouyang could you tell us if darktable crashes whatever the module you are clicking on, or if it is only on some specific modules please?

**Comment by johnny-bit** [comment]
After reading backtrace and digging the code in `global_toolbox.c` i think the problem might be that there was an error during the call (maybe missing handler for uri?), the `gtk_show_uri_on_window` call would want to return `FALSE`, however since GError is not available it cannot pass info to calling app (darktable) and generates crash.
