### ISSUE TITLE
Lighttable: Pressing Alt+1 to zoom should keep currently selected image

### ISSUE THREAD

**Issue by angryziber** [darktable-org/darktable#4033]
Pressing of Alt+1 (single image zoom) currently results in an unexpected jump to some earlier reviewed image (seems to be the first one previously visible on the screen, which is feels like kind of random - changes with scrolling).

Expected behavior would be to jump to currently selected image, so that reviewing can continue uninterrupted.

**Comment by phweyland** [comment]
This is not only with Alt+1, this occurs every time one zooms in: the selected image is not kept inside the visible window.

**Comment by aurelienpierre** [comment]
There are 2 levels of selection : "hard" (click), and "soft" (hover/arrows). Soft selection is used for example to live-update "image information" and tagging modules. But hard selection is used for exports and zooming.

I agree that this behaviour is not good, it's just a matter of anchoring the zooming to the soft selection instead of the hard.

**Comment by phweyland** [comment]
> it's just a matter of anchoring the zooming to the soft selection instead of the hard.

Select an image (click) on the bottom of lighttable with nb of images per line set to 6 or 7.
Then decrease the nb of images per line and the selected image disappears smoothly ...

(First) selected image (hard `and` soft) should stay in the window.

**Comment by AlicVB** [comment]
Well, it's not as easy as it seems... if we want to be consistent, we should keep the hovered/selected image at the same point on screen when zooming in/out, otherwise mouse cursor will hover another image and subsequent zooms will have the same problem... but that would require quite some work and design changes...

Here, Alt-1 is the 'easy' one, but we have to do that for all zoom levels... and anyway, now that you can toggle panels on preview, zoom=1 is not really useful anymore !

I propose to add that on my TODO list for the big filemanager rework I've started, without garanties

**Comment by angryziber** [comment]
Any news? Otherwise GitHub proposes to close the issue...

**Comment by TurboGit** [comment]
Fixed in master.
