### ISSUE TITLE
Deleting duplicate crashed DT

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4061]
I created a virgin duplicate. Did some work on it. 
Moved onto another image.
Went back to this duplicate and decided to delete it and got a backtrace and crash.
 **darktable 3.1.0+320~g218dd5d8c win 10**

00000000679B4006 00000000B0A84FA0 0000000000000000 0000000000000000  libgtk-3-0.dll!gtk_widget_set_sensitive
000000006BA02112 0047004E0041004C 0045004700410055 000000000000CCCC  libduplicate.dll!_lib_duplicate_init_callback  [F:/msys64/home/chill/darktable/src/libs/duplicate.c @ 443]
   441:   if(count==1)
   442:   {
>  443:     gtk_widget_set_sensitive(bt, FALSE);
   444:     gtk_widget_set_visible(bt, FALSE);
   445:   }

[darktable_bt_RUOAE0.txt](https://github.com/darktable-org/darktable/files/4035873/darktable_bt_RUOAE0.txt)

**Comment by chhil** [comment]
Restart resulted in all the folder I had imported were no longer there in the session prior to the crash.

**Comment by Mark-64** [comment]
Confirmed. 
There must be something wrong with my last commit on duplicates in Windows. Let me investigate on this one

**Comment by Mark-64** [comment]
No, nothing to do with my commits. Trashing duplicates always works fine from LT
Also trashing from DR works with imported duplicates, but if you create duplicates (either from LT or DR) then you have strange issues.
In my case, trashing the third last duplicate gives "failed to read WB" message and trashing the second last crashes DT. It happens even if between creation and trashing you restart DT.
Must be something corrupted in the creation of duplicates !?

**Comment by Mark-64** [comment]
running debugger, it seems a GUI issue as there is a access violation even before reaching dt_control_delete_images_job_run(), will have to invetigate further

**Comment by Mark-64** [comment]
Update: (this bug drove me crazy...)
The problem seems to be the fact that the call back _lib_duplicate_init_callback() in duplicate.c is triggered multiple times by different signals. In fact, it can be triggered by   
```
   DT_SIGNAL_DEVELOP_IMAGE_CHANGED 
   DT_SIGNAL_DEVELOP_INITIALIZE 
   DT_SIGNAL_COLLECTION_CHANGED
```
The calls are asynchronous (maybe also different threads, not sure) so eventually there is an access violation at the end of the funtion, in the instructions:
```
   gtk_widget_set_sensitive(bt, FALSE);
   gtk_widget_set_visible(bt, FALSE);
```
In Ubunty, there is an error 

`   Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed`

while in Windows DT crashes completely.

I found an ugly solution like:

```
static int ignore_signals = false;

static void _lib_duplicate_init_callback(gpointer instance, dt_lib_module_t *self)
{
  if (ignore_signals) return;
  ignore_signals = true;
...
...
  ignore_signals = false;
}

```
It works, but maybe there is a more elegant Gtk solution which cancels the multiple signals when entering the function.
Also, I possibly found other cases of multiple callback triggering, which are dangerous and slow down the GUI. Will investigate later.
Please let me know your opinion

**Comment by Mark-64** [comment]
OK, found. I can use 
```
dt_control_signal_block_by_func()
dt_control_signal_unblock_by_func();
```
I will make a PR.
