### ISSUE TITLE
Couple errors when I'm starting program 

### ISSUE THREAD

**Issue by Hohot** [darktable-org/darktable#4070]
Hello. Something wrong. When i'm start the program there is a couple tablets with "Error!"  
Attached the files.
[darktable_bt_6L4UD0.txt](https://github.com/darktable-org/darktable/files/4039762/darktable_bt_6L4UD0.txt)
[darktable_bt_HRXDE0.txt](https://github.com/darktable-org/darktable/files/4039763/darktable_bt_HRXDE0.txt)
[darktable_bt_PWBZD0.txt](https://github.com/darktable-org/darktable/files/4039764/darktable_bt_PWBZD0.txt)
[darktable_bt_VQKEE0.txt](https://github.com/darktable-org/darktable/files/4039765/darktable_bt_VQKEE0.txt)

**Comment by aurelienpierre** [comment]
https://github.com/darktable-org/darktable/wiki/Reporting-bugs-and-issues

**Comment by johnny-bit** [comment]
This issue is missing necessary info + targets dt 3.0.0 which is an "old release". dt 3.0.1 & 2 fixed several issues that might've caused problems experienced and even more was fixed in 3.2.1. We're days away from 3.4 now.

If you still have problems with newest release, don't hesitate to open new issue, but do provide all the necessary information and try steps mentioned at the bottom of https://github.com/darktable-org/darktable/wiki/Reporting-bugs-and-issues
