### ISSUE TITLE
unable to draw masks on macos

### ISSUE THREAD

**Issue by faemir** [darktable-org/darktable#4084]
**Describe the bug**

Completely unable to draw any shape mask on macos

**To Reproduce**

1. Use colour correction
2. Select 'drawn mask'
3. select brush / circle / path / etc.
4. try to draw a mask
4. nothing happens

**Expected behavior**

I should be able to draw out a mask

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: macos 10.14.6
 - no opencl
 - intel iris 6100

**Additional context**

**Comment by parafin** [comment]
works for me on same macOS version - I can draw a mask fine

**Comment by faemir** [comment]
I should have tried this sooner, but a full wipe of ~/.config/darktable cleared this up and it's working fine now.

**Comment by gempain** [comment]
@faemir there's no way 😛  your solution worked for me ! I was having issues with the mouse... I could not place the mask, everywhere I clicked the mask would follow, and when I tried to change the mask, the zoom would conflict with it. I think instead of deleting the entire folder, you could probably just delete `~/.config/darktable/darktablerc`. I'm wondering whether the problem was coming from me having mistakenly enabled something with a shortcut.

**Comment by AlexisBogroff** [comment]
@gempain well done for the way: indeed, I had the same issue after mistakenly pressing "s" (slideshow) and "a".
Solved by pressing "h" then "a". Don't ask me why. Cheers!
