### ISSUE TITLE
DT 3.1: Image goes black, looks like filmic rgb is involved.

### ISSUE THREAD

**Issue by maf** [darktable-org/darktable#4153]
During processing: white balance, highlight reconstruction, lens correction, exposure, tone equalizer, color balance, filmic rgb and in the end local contrast image goes black. Export goes black too. Zooming restores image visibility (or at least part of it).
I don't recall the condition (probably zoom in and out) sometimes black square appear here and there 

Turning off filmic rgb or local contrast helps immediately but turning modules one by one at some point also helps. This happens on 2 systems:
Ubuntu 18.04.3 with DT 3.1 compiled from git (opencl)
Ubuntu 18.04.3 with DT 3.1 from ppa ubuntuhandbook1 (no opencl here)

Nothing particular is in the logs except that if image is black then NaNs appears in the logs (not a number?):
> [dev_pixelpipe] module `filmic rgb' outputs NaNs! [full]

and then
> [dev_pixelpipe] module `local contrast' outputs NaNs! [full]

The number in the output color profile are quite strange:
> [dev_pixelpipe] module `output color profile' min: (-9999999778196308361216,000000; -9999999778196308361216,000000; -9999999778196308361216,000000) max: (0,000000; 0,000000; 0,000000) [full]

Excerpt below:
>[dev_pixelpipe] module `input color profile' min: (-15,706071; -35,378376; -40,351452) max: (80,725571; 33,076302; 32,700928) [full]
>879,111177 [dev_pixelpipe] took 0,417 secs (1,220 CPU) processed `contrast equalizer' on CPU, blended on CPU [full]
>[dev_pixelpipe] module `contrast equalizer' min: (-21,414795; -41,103779; -42,050827) max: (83,442757; 35,731350; 35,746754) [full]
>879,165274 [dev_pixelpipe] took 0,028 secs (0,081 CPU) processed `color balance' on CPU, blended on CPU [full]
>[dev_pixelpipe] module `color balance' min: (0,000000; -32,508270; -47,840672) max: (83,442558; 42,536171; 54,406147) [full]
>image colorspace transform Lab-->RGB took 0,007 secs (0,013 CPU) [filmicrgb ]
>879,243148 [dev_pixelpipe] took 0,053 secs (0,165 CPU) processed `filmic rgb' on CPU, blended on CPU [full]
>[dev_pixelpipe] module `filmic rgb' outputs NaNs! [full]
>[dev_pixelpipe] module `filmic rgb' min: (0,000000; 0,000000; 0,000000) max: (0,702808; 0,699667; 0,742269) [full]
>image colorspace transform RGB-->Lab took 0,012 secs (0,023 CPU) [bilat ]
>879,983328 [dev_pixelpipe] took 0,714 secs (1,379 CPU) processed `local contrast' on CPU, blended on CPU [full]
>879,984456 [dev_pixelpipe] took 1,503 secs (3,482 CPU) processed `local contrast' on CPU, blended on CPU [preview]
>[dev_pixelpipe] module `local contrast' outputs NaNs! [full]
>[dev_pixelpipe] module `local contrast' min: (340282346638528859811704183484516925440,000000; -28,738245; -48,038494) max: (0,000000; 42,913227; 52,831818) [full]
>[dev_pixelpipe] module `local contrast' min: (-5,378101; -29,576660; -59,971619) max: (90,508255; 41,894241; 43,258541) [preview]
>880,072362 [dev_pixelpipe] took 0,076 secs (0,291 CPU) processed `output color profile' on CPU, blended on CPU [full]
>[dev_pixelpipe] module `output color profile' min: (-9999999778196308361216,000000; -9999999778196308361216,000000; -9999999778196308361216,000000) max: (0,000000; 0,000000; 0,000000) [full]

**Comment by aurelienpierre** [comment]
Please give the settings used in filmic.

**Comment by hannonq** [comment]
@aurelienpierre I have a similar issue with Darktable 3.0. (Let me know if I should open a new bug report instead of using this one, since it's a different Darktable version).

Sometimes, when combining some modules, the image goes partially or completely black. 

Now I've just come across what seems to be a variation of this problem. Both my Darktable and my Lighttable view are normal. But when I export the photo, I get a black square in a part of the image.

I've created [this Google Drive folder](https://drive.google.com/open?id=1PP7GKzlOB3m25BYAIJc6lbrMFZRd42Oh) with the original raw photo, the jpg, the .xmp file and also the log files created during the export.

Also, when I enable the Lens Correction module on top of all the others in that photo and select camera Nikon 3400 and lens Tokina AF 11-20mm F2.8 AT-X Pro DX, with the default values, half of the screen goes black

I hope it helps finding out where the problem is.

**Comment by phil20099** [comment]
I have a similar issue with 3.0 on Ubuntu 18.04 and have narrowed it down to the following:

1. Start with an unedited Fujifilm XT-1 raw file (I used discard history)
2. Switch on Filmic RGB, local contrast and channel mixer, all with default values and the image goes black
3. Zooming in several times shows the image but not at every zoom level and sometimes only part of the image shows
4. Zoom out and the image goes black
5. The image shows if you switch off any 1 of the 3 modules mentioned above
6. The image shows if you keep all 3 modules on and change local contrast from _local laclapian_ to _bilateral grid_
 
I've repeated the above with a Nikon D700 raw file and experience the exact same issue.

**Comment by aurelienpierre** [comment]
For darktable 3.0, the problem is supposed to have been fixed. See #3128 

Please test the master branch if you can. 

Now, I need more details from the original poster about the settings used in filmic RGB for the issue on darktable 3.1 (master). There are 4 different modes in filmic, with different calculations, I need to narrow down the causes.

**Comment by maf** [comment]
I will test the latest master then.
For one picture the issue occurred just by enabling modules without touching anything.

**Comment by hannonq** [comment]
Thanks @aurelienpierre . I'll build from the master branch soon and try to reproduce the problem.

**Comment by Nilvus** [comment]
@TurboGit or @aurelienpierre: just seen this issue. Black images are fixed so should be closed I think.
