### ISSUE TITLE
Maybe a sign error in Filmic RGB

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#4169]
As asked on the user mailing list [2] there may be a sign error in
“Filmic RGB”:

From my understanding of a video [1] by Aurélien, “white relative
exposure” (wre) and “black relative exposure” (bre) set how far the
the black and white points in my input's dynamic range are away from
the point I've chosen as “middle grey luminance” (mgl).  If they were
set to, e.g.,

    wre = 4.33 EV
    bre = -8.47 EV

then the dynamic range into which my input is embedded would span

    wre - bre= 12.8 EV

because black is 8.47 EV *below* grey (hence negative), and white is
4.33 EV above, spanning 12.8 EV.

Now when I move mgl slider, the total dynamic range should stay the
same (he said something about the relative values being adopted).

But they don't!

I've got, only by changing mgl,

    wre = 2.89 EV
    bre = -7.03 EV

which give a reduced total dynamic range of

    wre - bre = 9.92 EV

However, the alert reader may have noticed that the *sum* of wre and
bre is of course the same

    4.33 EV - 8.47 EV  =  -4.14 EV  =  2.89 EV - 7.03 EV

To me, this suggested that the Δmgl is added or subtracted on the
wrong side of the dynamic range.  Changing

    p->black_point_source = p->black_point_source - grey_var;

to

    p->black_point_source = p->black_point_source + grey_var;

in `src/iop/filmicrgb.c` leaves the dynamic range constant when moving
mgl.

In case that is not correct, please explain why, because I really
don't understand why

    p->black_point_source = p->black_point_source - grey_var;

would be correct.

Cheers
Stefan

____________________
[1]: https://www.youtube.com/watch?v=zbPj_TqTF88
[2]: https://www.mail-archive.com/darktable-user@lists.darktable.org/msg08541.html

**Comment by aurelienpierre** [comment]
That has been discussed already, there is nothing in there saying that the DR is preserved constant. It is **adaptated**.

The general use case of decreasing the grey reference is when working on high dynamic range pictures, so the DR needs to be increased as well. grey = 18% comes with the assumption that we are working on a 6.5 EV DR. Decreasing grey reference comes with the fact that your DR is larger. If the black exposure wasn't updated like that (DR preserved and only slided), you would need to constantly rework the black afterwards, that would be very annoying.

**Comment by s5k6** [comment]
Ok, I bow to your confidence (honestly, no sarcasm).

> Decreasing grey reference comes with the fact that your DR is
> larger.

I'm sure you're right, but I don't get it.  What does it mean, when
the sum of the endpoints of an interval stays constant, which is what
happens to the white and black relative exposure values?  It feels
like making sense of the 10° which I've calculated by adding the
temperature at night (-5°) and day (+15°).  What is this constant?

In other words, if I moved grey far enough, why should the
trajectories of black and white intersect?

I do buy your argument about the need to update the black exposure as
it's done, but then why does the white exposure have to move the other
way?  I.e., while I've suggested

    p->black_point_source = p->black_point_source + grey_var;
    p->white_point_source = p->white_point_source + grey_var;

of course, I would also find

    p->black_point_source = p->black_point_source - grey_var;
    p->white_point_source = p->white_point_source - grey_var;

plausible.

Of course, you could just say

> If the black exposure wasn't updated like that (DR preserved
> and only slided), you would need to constantly rework the black
> afterwards, that would be very annoying.

about white now, but could I talk you into, just for the experiment,
changing the two lines 828, 829 in `filmicrgb.c` to bear the same sign
(either way), and check out how using that feels?

Cheers
Stefan

**Comment by aurelienpierre** [comment]
> about white now, but could I talk you into, just for the experiment,
changing the two lines 828, 829 in filmicrgb.c to bear the same sign
(either way), and check out how using that feels?

That was the default in filmic v1.

> I do buy your argument about the need to update the black exposure as
it's done, but then why does the white exposure have to move the other
way? 

Because otherwise white will clip. The white end of the DR is far more crucial than the black end. Black is actually where you decide "this is where data stops and noise begins", it's not an hard threshold.

Here is a chart shot properly (the grey patch, highlighted, is exposed at 18%) with filmic set to max/min RGB (clipping alert on, in blue):

![Capture d’écran de 2020-01-22 22-48-54](https://user-images.githubusercontent.com/2779157/72937616-bc67c880-3d69-11ea-9f21-0168be6f4ce6.png)

Let's decrease the grey point by 1 EV (from 18.45% to 9.23 %)

Here is the behaviour you propose (slide DR, keep it as large):
![Capture d’écran de 2020-01-22 22-50-02](https://user-images.githubusercontent.com/2779157/72937704-ef11c100-3d69-11ea-9925-189dde4e83d7.png)

Here is the current default (slide DR, enlarge it by 1 EV):
![Capture d’écran de 2020-01-22 22-50-19](https://user-images.githubusercontent.com/2779157/72937737-fb961980-3d69-11ea-8132-d0bcb4b568a8.png)

From an image-processing perspective, decreasing the grey point from 18% (which is correct for the color checker exposure) to 9% means redoing the global exposure for the background (black cloth) while preserving the checker white from clipping. If your grey reference in the background is lower by 1 EV, it means you have 2 overlapping DR in your image (target and background), shifted by 1 EV relatively to each other. So the sum of both is spanning over the original DR + 1EV.

**Comment by s5k6** [comment]
Hmmm, I need to digest this.  Would you mind sharing the raw image of your example?
Thanks for your patience and for explaining!

**Comment by aurelienpierre** [comment]
The raw is from @phweyland (is that ok ?). Meanwhile, here is the full explanation : https://www.youtube.com/watch?v=zbPj_TqTF88&t=2093s

**Comment by phweyland** [comment]
> The raw is from @phweyland (is that ok ?).

Yes. :-)
