### ISSUE TITLE
[Feature request] : add option in lens correction module to update lensfun on demand

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4180]
**Is your feature request related to a problem? Please describe.**
On forums, we often see people to ask why they don't see their lens(es) on darktable. Most of the times, this is easily solved by launching lensfun-update-data on a Terminal.
Here, I don't talk about Exiv2 problems but only when the lens is not found on "lens correction" module.

**Describe the solution you'd like**
I suggest to add an option on darktable to launch on background "lensfun-update-data" (as this doesn't need root privileges and could be launched as a simple user).
This has to be on demand, on the module himself. I suggest to add a button with a way for the user to easily understand that he has to click if he don't find his lens and see that to update lensfun library to last version.

This need of course, at least, two things:
- a way to be sure "lensfun-update-data" is installed (if not, having a text explained to install it)
- an alert to inform user that if after updating lensfun, he didn't find anymore his lens, that could be an Exiv2 issue or simply the fact that his lens is not supported by now. For this last thing, add a link to Wilson calibration page to encourage user to help add more lenses.

**Additional context**
Of course, this idea need probably to be improved, like precise if this could be easily adapted for all OS (or not). So feel free to suggest, criticize, etc.

**Comment by parafin** [comment]
It's a good idea. But I wonder how lensfun-update-data works on Windows (what is involved in installing it and with which command to call it)?..

**Comment by junkyardsparkle** [comment]
`lensfun-update-data` is a python script, so the best thing for portability would be to re-implement it either as part of darktable itself, maybe as part of a general rewrite of the lens correction module as discussed in #1990... or possibly even as a Lua script (but I've never tried to do anything network-related with Lua, and don't know if that's even feasible). Anyway, I agree that this would serve many users better than the script does.

**Comment by parafin** [comment]
lua might be a good idea

**Comment by GrahamByrnes** [comment]
> But I wonder how lensfun-update-data works on Windows (what is involved in installing it and with which command to call it)?

The current Windows build instructions include:
"NOTE: at the moment, the lensfun version provided by MSYS2 (0.3.95-1) is broken. If you get errors in the build process, manually downgrade lensfun to version 0.3.2-4:"
It seems to still be broken.

In my naivety, this would seem to make direct updating of lensfun tricky under Windows.

**Comment by junkyardsparkle** [comment]
> In my naivety, this would seem to make direct updating of lensfun tricky under Windows.

To clarify, it's not the actual lensfun library which needs frequent updating, but rather the lens database, which is simply a collection of XML files containing the profiles. The script mentioned above simply fetches a zip file containing a database snapshot and extracts it to either a system or user directory. Doing this in a cross-platform way is less simple, but it appears that some aspects of that are handled in some of the existing Lua extensions.

**Comment by Nilvus** [comment]
Not sure if this will help about adding that feature request for Windows but in case : https://github.com/darktable-org/darktable/commit/2d24ca5160e0a4fb2a1c179983a420c378df6dd3

**Comment by junkyardsparkle** [comment]
It would be sane to use the non-system lensfun data locations for this (~/.local/share/lensfun on *nix, not sure on Windows... <darktable_conf>/share/lensfun?). Encouraging users to let Lua scripts do things as root is a bad idea.

**Comment by parafin** [comment]
that's how lensfun-update-data works, I see no reason why lua script would be implemented differently

**Comment by junkyardsparkle** [comment]
`lensfun-update-data` will use the system locations if it has the required rights; just saying that doesn't need to be part of this implementation.

**Comment by johnny-bit** [comment]
In my system there's no possibility of use lua due to obscure version conflict so if this functionality was lua-based it would be problem for me. I would think that best way to deal with it would be to just detect presence of `lensfun-update-data` in `PATH` and execute it on click... That or re-implement that python script in c (:nauseated_face:)

**Comment by Nilvus** [comment]
> In my system there's no possibility of use lua due to obscure version conflict so if this functionality was lua-based it would be problem for me. I would think that best way to deal with it would be to just detect presence of `lensfun-update-data` in `PATH` and execute it on click... That or re-implement that python script in c (nauseated_face)

I agree with that proposal. Just need someone to implement that. I can't do that : I don't have coding skills.

**Comment by johnny-bit** [comment]
Well, that can be learned :P And I actually seen code that does just that! I just need 2h alone with it :)

**Comment by Nilvus** [comment]
> Well, that can be learned :P And I actually seen code that does just that! I just need 2h alone with it :)

Oh yes, but I prefer to use my time for lot of other things I prefer to do.

**Comment by martinber** [comment]
I spent several months waiting for support for my camera and now I realize that this does not depend on Darktable but on lensfun instead.

Temporarily it would be nice to add a message in the module. There is already one when the camera/lens is not found, it should say something like "camera/lens combination not found, select manually. consider updating lensfun library data"

**Comment by johnny-bit** [comment]
I still want to do that...

**Comment by Nilvus** [comment]
> @johnny-bit That was my original idea too, I might want to look into implementing this. I'm not sure how that would be done in a portable way though. Easy enough to add a button to run the `lensfun-update-data` script and re-run the camera/lens detection afterwards on linux/macos, not sure about windows.

This is a start. Windows would come. Of course, in the PR, this would need to be taken in account before merging. The help of a Windows developer could maybe come.

**Comment by pengowray** [comment]
So I had to update lensfun data on Windows recently, so this topic is fresh on my mind. I hope you can implement a better way than the current lack of way, especially on Windows where there's no `lensfun-update-data` python script.

Although updating the lens data was just a matter of downloading https://lensfun.sourceforge.net/db/version_1.tar.bz2 [or https://wilson.bronger.org/lensfun-db/version_1.tar.bz2] and copying the new xml files into `C:\Program Files\darktable\share\lensfun\version_1`, I only worked that out after a bunch of trial and error (attempting to use and then modify an xml file from [lenfun's github](https://github.com/lensfun/lensfun/tree/master/data/db), which is subtly incompatible with the version of lensfun used by darktable, in particular ways I never fully worked out). To find the backported lensfun db I read through and pieced together the url from the [lensfun-update-data](https://github.com/lensfun/lensfun/blob/master/apps/lensfun-update-data) python script.

So the problem that seems to be plaguing this discussion, is how to implement something that on one hand seems so simple, just updating some files, but also requires root privileges. Unfortunately, that makes it not so simple. I've got three possible solutions, which I'm sure no one will like:

1. Keep the updated lensfun db download in the user's folders. On Windows that might be in a directory like `C:\Users\USER\AppData\Local\darktable\lensfun\version_1`. This way there's no privilege escalation just to correct some barrel distortion on a new lens. If the files don't extract correctly or there's some other issue, the user can wipe this directory (manually or through darktable) and fallback to the known good files that came with darktable's installation. These user's lens files should also be ignored if they predate the version that comes with darktable so that the old files stop getting used after the user installs a darktable update. This all adds complexity (two locations for lensfun files with a fallback) but creates simplicity for the end user, who doesn't have to run scripts as root, or update anything manually.

2. Alternatively, have an option within darktable's installer to download and use the latest lensfun files, so the files are updated as part of the installation itself. Reinstalling darktable to update the lensfun files might seem excessive, but it's very rare that the user would need to do this, but at least the option would be there. Also requires no weird scripts with elevated privileges running from inside darktable. This option probably only makes sense on Windows (and maybe mac?), and is kinda clumsy.

3. Another option would be to automatically trigger a minor darktable update every time lensfun is updated.  Very clumsy, but at least those updates would be available.

Cheers. Thanks for the great software.

**Comment by kmilos** [comment]
FYI, there already seems to be some code around for Windows (C++ though): https://discuss.pixls.us/t/how-to-keep-lensfun-current-on-windows-10/22382/2

**Comment by pengowray** [comment]
Would it make sense to bundle this with the Windows version?
