### ISSUE TITLE
Culling Screen Proportions

### ISSUE THREAD

**Issue by JStoddard21** [darktable-org/darktable#4328]
**Describe the bug**
When opening a filmroll or folder and viewing in culling mode, the right panel (with Select through Export Selected) is not fully visible and cannot be fully viewed unless the left panel (Import through Image Information) is minimized to the left.

**To Reproduce**
1. Launch, and import
2. Switch to culling mode from zoomable light table or file manager
3. See issue on right

**Expected behavior**
Usually (in the other view modes; Zoomable Light Table and File Manager) the right panel is visible

**Screenshots**
![Screenshot (17)](https://user-images.githubusercontent.com/53049803/74884231-aa654f80-5340-11ea-95d3-33cf45794998.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Windows 10

**Additional context**
 - I never noticed this before, but it was consistent after quitting and reopening the program.
 - This isn't super important, just a small bug

**Comment by AlicVB** [comment]
Seeing your screenshot, I think it's due to the controls in the bottom toolbar.
In culling, there's more controls here than in other modes, so it take more space and prevent the main area to more smaller width. Hence it force your window to be larger than screen (and crop the right end)

Nothing we can really do here... You can hide the bottom toolbar with ctrl-b, but you'll loose useful controls... or reduce left or right panel sizes (panels sizes are recorded by view/layout, so you can have different size for culling, filemanager, ...)
