### ISSUE TITLE
Cannot collapse the top brand/menu panel

### ISSUE THREAD

**Issue by KristijanZic** [darktable-org/darktable#4339]
**Describe the bug**
The top brand/menu panel cannot be collapsed, not with the border button nor with using `CTRL+SHIFT+T`.

To illustrate on what panel I mean here's the ss with the panel overlayed in red:
![Screenshot from 2020-02-21 00-08-30_001](https://user-images.githubusercontent.com/10299892/74988899-5a20e700-543f-11ea-8fe6-d0bd4f64af74.png)

**To Reproduce**
1. Go to Darktable > Darkroom
2. Click on top border arrow button 2 times, or press `CTRL+SHIFT+T` 2 times.
Observe how the top brand/menu panel doesn't go away.

**Expected behavior**
Top brand/menu panel should collapse when pressing the top border 2 times or using the above mentioned shortcut 2 times. On third click both top panels should expand.

**Platform (please complete the following information):**
Darktable Version: 3.0.0, 3.0.1 master
OS: Ubuntu 19.10 x86_64
Host: Inspiron 13-7359
Kernel: 5.3.0-40-generic
Uptime: 1 day, 17 hours, 32 mins
Packages: 1697 (dpkg), 36 (flatpak), 28 (snap)
Shell: bash 5.0.3
Resolution: 1920x1080
DE: GNOME 3.34.1
Theme: Adwaita-dark [GTK2/3]
Icons: Yaru [GTK2/3]
Terminal: gnome-terminal
CPU: Intel i7-6500U (4) @ 3.100GHz
GPU: Intel Skylake GT2 [HD Graphics 520]
Memory: 6843MiB / 7818MiB

**Additional context**

**Comment by Nilvus** [comment]
I have used darktable 3.0 since the beginning of its development and same for actual master. I never had this behavior. Shortcuts works correctly. Just be careful that master have different behaviour regardless which commit you use (you don't precise that). On darktable 3.0 and master in the beginning of this year, the top panel (what you have on red color) could be collapsed or displayed with 'Ctrl+h'.

Since about a month only (approximatively), 'Ctrl+h' and 'Shift+Ctrl+T' pressing two or three times (depending on collapse/display of top menu, with group, preferences, help... icons) is possible.

But during some days, Ctrl+h were no more avalaible. Be sure to check your preferences dialog windows and how your shortcuts are set. Remember that you could see the available shortcuts of the current view by just pressing 'h' shortcut.

**Comment by KristijanZic** [comment]
Niether `CTRL+SHIFT+H` nor `CTRL+SHIFT+H` nor `CTRL+SHIFT+T` work on the latest Flatpak, Snap or master for hiding the top panel higlited in red. `CTRL+SHIFT+T` used to work. This is an issue.
 
Here are my shortcuts:
![Screenshot from 2020-02-22 22-20-17](https://user-images.githubusercontent.com/10299892/75122781-918ece00-56a1-11ea-857c-cc87b3be7373.png)

**Comment by KristijanZic** [comment]
Alright, new observatins: 

1. I tried spamming `CTRL+H`, `CTRL+SHIFT+H`, `CTRL+SHIFT+T` in lighttable and nothing was happening
2. I click an image to get into darkroom and to my surprise all the panels are gone.
3. I bring back all the panels again with shortcuts except top header. red highlighted top header still doesn't work nor with CTRL+H nor by clicking the border.
4. I restart Darktable
5. CTRL+H works just fine now for hiding and displaying header.

This is very weird and inconsistent behavior, let's keep this bug open

**Comment by Nilvus** [comment]
Of course, you have an issue, that doesn't seems that darktable have an issue in source code. As I said, I regularly use these shortcuts and master development release (I compile really often and follow development since more than a year). I also help users on french darktable forums and I never see or heard someone with your issues. I have just seen some similar ones (one shortcut or two only with some behavior you describe). Each time, that were a corrupted darktablerc file (I have seen one time as I remember where the corrupted file were the keyboard one on config folder). So, I suggest you to test darktable by removing (save it of course before) your darktablerc file in your config folder. Do that with darktable closed and launch darktable after removing it (darktable will create a new default one ; you will lose some settings). If that doesn't solve your issue, do the same with keyboard ones in same folders. And if issue remains, test by removing all these files at once. If issue is solved, you will have to set back other lost settings manually in darktable or by selecting some lines between saved files and defaults new ones (test theme by some lines at each time to be sure the issue doesn't came back).

If you solve your issue, think about closing this one.

Take care that flatpak and snap ones doesn't use by default same config folders. So what you describe seems to confirm that's related to config folder used by one or the other. And having borders is a default behavior of darktable. Removing them by **b** shortcut is then saved in darktablerc file view by view.

**Comment by KristijanZic** [comment]
Idk, what the issue was, 3.0.0 still has the issue, but I just tested the master 3.1.0 from OBS in a vm and everything worked perfectly so I'm closing this issue.
