### ISSUE TITLE
Style is not applied on export

### ISSUE THREAD

**Issue by dmitryash** [darktable-org/darktable#4368]
**Describe the bug**

I needed to export some already edited images w/o applied changes. I decided to create a new style which only contains basic pipeline suggested by darktable (auto rotation + sharpeness). After that I tried to export images with this style (+ option replace style on export). However dartable exported images w/o new style, instead all images were exported as they were edited.

**To Reproduce**

  1. Edit some image
  2. Switch to lightable
  3. Export the image, but select some style and enable option to replace the changed with this style (instead of merging changes).
  4. See that the style wasn't applied. 

**Expected behavior**

I expect that my completely different style will be applied on export and it will replace any changes made to an image.

**Platform (please complete the following information):**
 - Darktable Version: 2.6.3
 - OS: openSUSE leap 15.1

**Comment by johnny-bit** [comment]
Weird...

Does style on export work for you in append mode (eg add watermark etc)? Have you tried replicating issue using darktable 3.0.0 (if you wish to try, please backup your files and prefferably work on fresh copy + non-modified file, so you won't lose/alter changes done in 2.6.3)

**Comment by jade-nl** [comment]
While trying to replicate this issue I see a different behaviour as described:

Using both dt 2.6.3 and dt 3.0.0: Style is **appended** to edits done instead of replacing them when selecting *replace history*

I do believe that the title of this issue isn't correct: The style is applied it is just that it isn't seen in OP's case ("neutral style") due to the edits already done.

I checked both *append history* and *replace history*, both have the same appended end result.

* darktable version:
&nbsp;&nbsp;&nbsp;&nbsp;Old Stable 2.6.3
&nbsp;&nbsp;&nbsp;&nbsp;Stable 3.0.0
* OS     : Linux - kernel 4.19.0-8-amd64
* Distro : Debian Buster (rel. 10.3)
* Extra : Clean/empty config dir to start with

**Comment by dmitryash** [comment]
Could you suggest a better way to do what I needed please? My use case was: I edited several images but then I was asked to convert them w/o modifications (my friend would like to use a simple image editor). 

My idea was to replace all modifications on export with a basic style.

**Comment by johnny-bit** [comment]
as a workaround - create virgin duplicate and export that.

**Comment by jade-nl** [comment]
> Could you suggest a better way to do what I needed please?

Until this issue is fixed you could do the following:

From lightroom view select all the images that you need to export and press ctrl-d. This will create duplicates.

Because all the modifications are also duplicated you need to remove those:  Select all the duplicates, open the *history stack* module and select *discard history*

All the dupes are now unmodified (just the basics) and you can now export the images. After you are done: use _remove_ in the *selected images* module (or the DEL key) to get rid of the duplicates.

Cumbersome, but this will work.

**Comment by dmitryash** [comment]
Thank you, I tried to build from 8887c1b055108e5d6e644d3843a84a2f19ca4513 and did simple experiment. I took one photo and applied one change on the left half and then created a style that applies a change on the right side. Both settings "replace' and "append" gave the same result. Is it what is supposed to be?

**Comment by johnny-bit** [comment]
Nope. replace should replace whole history with your style.
