### ISSUE TITLE
Bigger Handlers - Point handlers hard to pick up

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#4387]
**Is your feature request related to a problem? Please describe.**

Handlers (for modules and to hide/unhide dockers) were always too small; this did not change with Darktable 3.0.0  

**Describe the solution you'd like**

in brief, DT's handlers shall be replaced. Really. Point handlers are hard to pick up.

An example of useful handlers are found in Gimp - let me illustrate what i mean.
For this purpose, lets open the brush settings, to change size, hardness, rotation, spacing, etc. of a brush in Gimp.

Each one of the handlers defines one aspect of a brush, (size, hardness, rotation, spacing, etc.) The handler itself looks like a progress bars and you can move the bar back and forth to set the desired value. There is nothing like a triangle, but the whole bar is clickable and easy to pick up 
To avoid cluttering the UI of Darktable, i suggest to change the width of the handler bar to 1/3 in comparison to the handlers seen in Gimp. Give it a try.
 
**Alternatives**

I appreciate the option to right-click and scroll or input values with the number keys, but prefer handlers over alternatives. Handlers are definitely _quicker_ .

**Comment by Nilvus** [comment]
What do you mean here ? I really don't understand what you mean by handlers and dockers about darktable UI ? And could you please post a screen capture (or two) to point exactly what you have. I really don't see nothing that could be related to what you describe that could be so small.

**Comment by johans3** [comment]
with handlers i mean the point-sized control elements (triangles) to adjust values in the modules and the triangles to hide/unhide the modules. Also gradient masks use point-handlers rotate the mask in the desired direction. 

lets see the module "Sharpen" under the module group "Correction" (in Germany: Korrekturgruppe)
we have Radius, Amount and threshold.
each one of this labels has its ruler.
Why not unify the label and the ruler in one bar, like in Gimp? if you are on Linux you will use Gimp, because Linux has no Photoshop. 

[Gimp-Handler(Imgur)](https://i.imgur.com/2bgIFwX.jpg)

**Comment by Nilvus** [comment]
Ok, I find them just the good size but as they font related, maybe you don't have the wanted behavior. So, as I said, please post a screen capture of your UI.

**Comment by johans3** [comment]
Please click the link in my last post

**Comment by Nilvus** [comment]
Link in your last post was not a darktable screen capture... darktable use CSS and font size related. Your UI is way too small and not the default UI we made. You could see normal size on screen capture I made on the darktable 3.0 article posted in darktable.org blog : https://www.darktable.org/2019/12/darktable-30/. It's not only "handlers" that are too small on your UI but also text so it's really font related on your OS. So it's not something we can change on darktable because not all users don't have that behavior. It depends on some specific configurations.

You could see different solved issues about UI on Mac (some things have been tweaked since) here:
https://github.com/darktable-org/darktable/issues/2615
https://github.com/darktable-org/darktable/issues/3295

To have more help, you could after that use pixl.us forums which is more suitable for specific users issues and helps.

@parafin: if you have something to add about specific Mac things here...

**Comment by parafin** [comment]
There's nothing Mac-specific, it's just a question of screen DPI. On Mac for some reason it is fixed and doesn't depend on screen size at all.
One can adjust darktable's DPI setting which will scale the whole UI.

**Comment by parafin** [comment]
I can only suggest to check how darktable looks if you move away ~/.config/darktable directory. Maybe some old wrong settings are in the config file (like mentioned DPI).

**Comment by johans3** [comment]
The theme looks different indeed…
i also noticed that it is possible to click on the label to move the handler / rulers or how you call the elements to control values of the modules. Still, what do you think to unify label and ruler in one bar, like in Gimp?
see like abowe.

**Comment by Nilvus** [comment]
Thanks @parafin for your help. I have suggested lot of time to move away config folder. I don't know why I don't simply think about that this time.

@johans3: about your last proposal, I personnaly prefer the way darktable render that. I find the the way Gimp render that just awful. I'm quite sure lot of users like the darktable way as others like you prefer the Gimp way. Nothing could be appreciate by all people.

Think about closing this issue now you see that's your config folder (so probably an old DPI setting remains on your darktablerc file : screen_dpi line, by default on -1.0 setting).

**Comment by johnny-bit** [comment]
@johans3 - you can also right-click on slider and it'll show great input-box where you can input value + you have very fine to very coarse way of setting values, which is absolutelly awesome and better than any other UI (including gimp) :P

**Comment by johans3** [comment]
@johnny-bit thank you, yeah it is a way, to have more control over sliders. Still, my point was to be quick foremost and have no point-sliders to click. Luckily also the label is clickable. As a long time user of Gimp, the next idea coming to my mind was some adaption of the sliders in Gimp. I am pretty unsure why several people call gimps functional sliders "ugly". I have seen much worse

**Comment by johnny-bit** [comment]
You can actually click anywhere on slider to move to that value-point. Also your "too small X" problem stems from fontsize/DPI and not any fault of UI, since UI in darktable is very scallable and works great in various screen sizes.

as for gimp way - it has it's ups and downs but it's clearly different than one in darktable.
btw: have you seen sliders in Lightroom? those are freakishly tiny and way uglier than darktable or Gimp ones ;)

**Comment by johans3** [comment]
Luckily darktable allows us to click also on the label, not only the point sliders. The theme / dpi setting didn't matter.
