### ISSUE TITLE
[FEATURE] Enable double-click related action customization in Lighttable

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#4417]
Hi !

This feature request is purely user-comfort related :

As a matter of fact, I double-click on thumbnails in Lighttable to see them bigger and it opens them in darkroom.

But the loading time is too long when you just want to quickly preview the picture.

I'd be great if the double-click could be customized to either open the picture in darkroom  (which will slower) or open the preview  (which will faster).
In case the preview is open, the keyboard shortcut could then be used to open the picture in darkroom.

Would this be useful for anyone, or am I the only one doing this (and I'll close the issue) ?

Thanks
GLLM

**Comment by johnny-bit** [comment]
Nope. That's bad flow. In other apps doubleclicking opens default action and default action in darktable is to process RAWs therefore it should open darkroom. Preview key binding is perfect, because it doesn't obstruct main process.

There is a case to be made for shortcut to be shown in topbar like it is for some tools in darkroom (by @TurboGit ). And again @AlicVB is doing great lighttable rewrite so it may connect with your general issue, but I'd be against changing default doubleclick binding.

**Comment by AlicVB** [comment]
on the coding, it would be far from easy to change that. Double-click perform switch between lighttable and darkroom, but is coded deep in the code. It's not handled directly in views.

That said, I follow @johnny-bit here : I don't think letting user change such basic workflow is great. We need to keep some invariant...

**Comment by johnny-bit** [comment]
@GLLM - currently we have default "w" shortcut which is waay faster (for me and probably those who do keyboard shortcuts a lot) to simply use it and have dedicated variant. Since dbl click is as @AlicVB said "coded deep in the code" I'd suggest simply closing the issue and getting more familiar with very quick "W" shortcut ;)

**Comment by GLLM** [comment]
Hi @johnny-bit, @AlicVB !
Thanks for your replies.
I asked, cos' I'm currently using such a shotcut ("w") but mouse still is my primary HMI :)
I'll close this feature request ...
But as I type this final comment, I realize that this very issus is actually a workaround to my actual issue : the loading of pictures in DR mode (from LT) is slow :)
(though I'm on core i7 7700K + 32GB RAM + Nvidia GFX 1070 8GB, OS on SSD ... I may try to put pics on another SSD, b/c they're on a HDD at the moment)
