### ISSUE TITLE
[FR] Minimum area for color picker

### ISSUE THREAD

**Issue by johnny-bit** [darktable-org/darktable#4466]
**Is your feature request related to a problem? Please describe.**

In #3631 it's clear that issue was caused in some instances by problems fixed by #4431. However it is still possible for users to select area that makes little to no sense in terms of spot picking.

**Describe the solution you'd like**

In #4431 @jenshannoschwalm fixed the ability to pick area outside of the image. It would be great if we could introduce (or let color-picker clients decide) minumum area for color picker to work on. 

My proposition: introduce a configureable minimum sensible area dimmension to work on, eg "10x10" px makes sense because it contains a bit better info than "100x1" px area.

**Alternatives**

Alternatively a color picker consumers could just ignore spot/picked parts that are too small for them to work on or show error (eg "area too small to get meaningful data")
**Additional context**

The best example is a screenshot by @jade-nl:
![3 1 0 spot outside](https://user-images.githubusercontent.com/56407344/76611933-9665d580-651b-11ea-9eb7-cd5004e6c399.png)

as you can see this area makes very little sense to be used by white balance module.

**Comment by GrahamByrnes** [comment]
Hmmm, if you can zoom in and clearly place the box on a bit of grey... at the theoretical level, that shouldn't be a problem.

Otoh, there may be a practical problem, which is the precision of the box boundary.

Once upen a time I launched an issue related to adding a frame line (ie a very thin black border), which implies setting the black border to the same width as the frame (the IT version of Henri C-B filing out his negative holders). On screen, you see that sometimes the black doesn't cover the white, but it varies with zoom. 

It turned out that when exported/printed, everything is fine, it's just a display issue.

So it may be a matter of warning the client that the box s/he sees on screen may not be the actual box when mapped back to the original image for sampling.

**Comment by johnny-bit** [comment]
This isn't about zoom (well, it mostly isn't). But it could help as it would force users to zoom in order to place weird/unexpected color picker areas.

Could you look also into #4471 and say what do you think about it?

**Comment by johnny-bit** [comment]
Fixed by #4495
