### ISSUE TITLE
Window width can't be changed in lighttable mode

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [darktable-org/darktable#4521]
**Describe the bug**

I accidentally made the window larger in lighttable mode longer than my screen so I wanted to resize it to fit again. Turns out the controls do not allow me to make it smaller. I tried maximizing instead to fit the screen, but that option is also unavailable, see screenshot. Oddly enough when I switch to darktable mode the option returns and the window allows me to resize.

**To Reproduce**

1. Open lighttable mode
2. Try to maximize (e.g. by clicking the title bar) or making the window narrow. Can't.

**Expected behavior**

The window would scale to a size where it fits on my screen.

**Screenshots**

![Right click on toolbar](https://user-images.githubusercontent.com/121531/77235193-0f1c0000-6bb4-11ea-90de-6e0f5909839c.png)

**Platform (please complete the following information):**
 - Darktable Version:  3.0.1
 - OS:  Arch Linux, GNOME 3.36
 -  No OpenCL
 -  Intel(R) HD Graphics 3000 running `intel` driver at 1366x768.

**Additional context**

Seems like #3707 is a very similar bug, it seems like lighttable mode has a pretty wide minimum width.

**Comment by froooze** [comment]
Looks like the full screen resize does not work and the minimum window width is around 1500px, which is too much for older systems.

**Comment by bmhorn** [comment]
I have the same problem with my 2 year old Thinkpad [WQHD resolution (2560x1440)], but not exclusively in the light table mode.

Platform (please complete the following information):
* Darktable Version: 3.0.2
* OS: Arch Linux, GNOME 3.36
* Intel(R) HD Graphics 620

**Comment by supsoc** [comment]
Same here. Running Darktable 3.0.1 on Ubuntu 20.04, gnome 3.36.

**Comment by jwiesel** [comment]
Hi there, I have exactly the same issue since the upgrade to Ubuntu 20.04 and Darktable 3.0.
Collapsing the side panels helps temporarily to enable maximizing the window. When I expand the side panels again. the issue reoccurs: The window size is changed and maximizing is not possible any longer
System setup:
* Ubuntu Desktopp 20.04 (default flavour running on Gnome)
* Darktable 3.0.2
* Screen resolution: 1366x768

**Comment by mshigue** [comment]
I solved this problem using 'font size in points' = 8.0. In settings -> general

**Comment by Nilvus** [comment]
This issue is related to Gtk, not darktable. Or to be precise, is related to minimum size of the window needed regardless of screen resolution. If window width is the same or bigger than screen resolution width, maximize button is disabled. That's why reducing font size or reducing panels size fix the issue. We have been working last year on allowing to reduce more panels size and easily change font size in preferences, as explains by @mshigue. So with that, it's possible to adjust window size to small screen resolution. But don't forget too that in 2020 or 2021, 1366x768 is a small resolution.

**Comment by SGSkoblia** [comment]
> I solved this problem using 'font size in points' = 8.0. In settings -> general
I was need to set "max_panel_width=300" in config file "darktablerc" also.
