### ISSUE TITLE
[Liquify] Every operation using the dot,line, curve takes very very long with spinning cursor

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4563]
**Describe the bug**
I don't use liquify at all but one of my lens [panasonic leica 10-25] is not int lensfun db and wanted to remove some curved lines.
Every click takes very long and any operation to move arrows takes very long.
Apart from taking too long and freezing the module works.

**Expected behavior**
Optimized behavior and not have the user to wait.

**Platform (please complete the following information):**
 - Darktable Version: darktable-3.1.0+1048~gac8a95087-win64
 - OS: Win 10
 - OpenCL activated or no?  Yes

**Comment by TurboGit** [comment]
Try deactivating the OpenCL. Maybe your card is too slow? Liquify is certainly one of the most CPU intensive module in darktable.

**Comment by chhil** [comment]
I dont have a very capable graphics card. 
Turning off opencl, restart and tried the liquify module, no change in behavior.

Also noticed resetting the module and enabling it again brings back the line that was drawn prior to reset. 
Sometimes reset will keep the previously selected line tool still active and no way to change it. Something appears to be very off with the module.

**Comment by johnny-bit** [comment]
> Also noticed resetting the module and enabling it again brings back the line that was drawn prior to reset.
Sometimes reset will keep the previously selected line tool still active and no way to change it. Something appears to be very off with the module.

This is fixed in #5723

> Every click takes very long and any operation to move arrows takes very long.

While Liquify is HEAVY module recent speedups (starting with #5421) and more piling up, I'd say that the module is way snappier than what it was back in March.

Closing this with high hopes for @ralfbrown & others continuing putting their time into optimizing darktable :)
