### ISSUE TITLE
[Lens correction] Scale to less than 1 removes cropping and retouch

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4564]
When I scale to less than 1 the cropping and retouching already done is lost.
Lens correction comes earlier in the pipeline but is the behavior intentional?

I was expecting the lens correction use the already cropped and retouched  image. I am aware I can change the pipeline should that be the case.

darktable-3.1.0+1048~gac8a95087-win64

**Comment by johnny-bit** [comment]
while it might be a bug in croping and retouching module, don't move lens correction after those modules. especially crop, as lens correction needs to operate on full image to make sense.

**Comment by jenshannoschwalm** [comment]
@chhil i looked again into this. There is **no** problem as you described. As @johnny-bit already hinted out, the lens module is not for scaling but for correcting data based on sensor and lens. Any other data provided to the module simply don't make sense. (Or you do it and see strange things happen) So please, this is no bug, no issue and thus this should be closed :-)

**Comment by junkyardsparkle** [comment]
> the lens module is not for scaling

Well, to be fair, scaling is almost *always* one of the things it does, and there *are* some valid reasons for manually adjusting from the calculated one (which is just to crop all margins at sensor aspect ratio). This is actually quite useful when, for example, remapping a fisheye to stereographic or rectilinear; you can recover quite a bit of image area by reducing the scale factor, giving you more cropping options later. You just need to do this before doing other processing in order to avoid issues like this. :-)

**Comment by jenshannoschwalm** [comment]
Right, I confess i use this too sometimes :-)
