### ISSUE TITLE
image id - group id issue on import of images when xmp

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#4568]
When I import images without xmp file image id = group id: correct

![image](https://user-images.githubusercontent.com/23012047/77859038-81589a00-71dd-11ea-92c4-936fe328b183.png)

**Describe the bug**

When I import the same images with an xmp file image id = group id + 1 (and image id is pulling the value of group id): incorrect

![image](https://user-images.githubusercontent.com/23012047/77859066-a947fd80-71dd-11ea-9fcf-4f2ec9c20d27.png)

EDIT: same behavior for both single images and folder

**Expected behavior**
group id must be equal to image id at this stage

**Context**
 - Darktable Version: 3.1.0+1049~gd1f0f0e14
 - OS:  Debian 10

**Comment by elstoc** [comment]
This is caused by https://github.com/darktable-org/darktable/pull/4393. In the case of multiple images would you expect it to be the id of the lowest version number?

**Comment by phweyland** [comment]
>  In the case of multiple versions would you expect it to be the id of the lowest version number?

Yes, but that's more than that. I don't have several version. So group id must equal image id.

So for a single image I expect to get the first screenshot, with or without xmp.
I haven't made any test when there are several xmp files ... but the code seems to consider that every xmp is a duplicate, which is not correct.

I think we should not delete the first created image line 1302 image.c. This sounds weird.
dt_image_read_duplicates() should not create an image for the xmp associated with the image (without version).

**Comment by phweyland** [comment]
I'm afraid that #4393 should be reverted and duplicate issues analyzed again.
This fix is breaking the grouping management and the basic workflow (without duplicate).

**Comment by elstoc** [comment]
I don't have a problem with finding a better solution to the original issue but what you've suggested in Edit 2 will not resolve that issue, since I've already deleted the v0 edits and the only sidecars I have are at v1 or higher. If I have to reimport my images at a later date (which I've already had to do a couple of times) I have to go through them all and manually delete all the v0 'edits' again. Note also that if you change the delete function as you suggest that function would have to delete and recreate sidecars as well (to avoid orphan sidecar files).

The only alternative way to manage the import that I could think of was to change it so that it reads the xmp files first and only creates a v0 if there aren't any. However, the way it currently works means that dt_image_read_duplicates won't work without an image to duplicate from, hence the 'dummy' record.

**Comment by elstoc** [comment]
How about if we go back to the first image being inserted at v0 then, for the first xmp that dt_image_read_duplicates() finds, it updates the version number of the passed in id before calling dt_image_duplicate_with_version().

**Comment by phweyland** [comment]
> for the first xmp that dt_image_read_duplicates() finds, it updates the version number of the passed in id instead of calling dt_image_duplicate_with_version()

If I understand properly your idea, it should work (after reverting PR #4393).

This should also stay compatible with the second call to dt_image_read_duplicates() when the imported image already exists. 

A detail: as dt_image_read_duplicates() is used only in image.c it's candidate to be set as static and renamed to _image_read_duplicates().
