### ISSUE TITLE
Tags are applied to wrong images in darkroom

### ISSUE THREAD

**Issue by rabauke** [darktable-org/darktable#4576]
**Describe the bug**

When tags are added to an image in darkroom view, the tags may be applied to the wrong image.

**To Reproduce**

- Open a collection with several images in lighttable view.
- Select an image (image A) in lighttable view.
- Switch to darkroom view.
- Select another image (image B) from the film strip.
- Press Ctrl+T and enter a tag.

**Expected behavior**
The tag should be applied to image B, it is, however, applied to image A.

**Platform (please complete the following information):**
 - Darktable Version: git master
 - OS: Ubuntu 19.10, Intel x64

**Additional context**
The following issue might be related to this bug: Above the image in darkroom view, a text is shown: "1 image of  X (#Y) in current collection is selected". The number Y does _not_ change when switching from image A to image B.

**Comment by phweyland** [comment]
Hi Heiko,
This is related to new behavior filmstrip. Pinging @AlicVB .
Ctrl-T works with selected images if any, otherwise it uses dt_control_get_mouse_over_id().
1. Selected image doesn't change when you click on filmstrip or moves with space/backspace.
2. if you have no selected image, and your mouse is "somewhere" on filmstrip the tag goes there ...

Aldric, what do you think ? Should I change the way to identify the current dev image when in darkroom ? But in that case we cannot apply the tag on selection in darkroom (which may not be stupid)....

**Comment by rabauke** [comment]
@phweyland Thanks for your explanation. I think the current behavior is very unintuitive and inconvenient. In particular, when one switches from lighttable view to darkroom view via double click on an image, which also selects the image one clicks on. In my view it would be very reasonable to apply tags in darkroom view always and only to the image which is currently edited.

**Comment by phweyland** [comment]
>  In my view it would be very reasonable to apply tags in darkroom view always and only to the image which is currently edited.

Agreed.

**Comment by phweyland** [comment]
@Turbogit @AlicVB 
If I'm not mistaken with the previous darkroom behavior selected image = edited image. 
The tag module (not only ctrl-T feature) works on this assumption (and probably some other modules (export ?) which apply on different views).
I don't think this is good idea to check everywhere is we are in darkroom before using selected image.
And I agree with Heiko the current behavior of filmstrip under darkroom is not convenient.

Is there any discussion about this I can refer to understand the basics ?
What is the plan ?  Any help needed ?

**Comment by AlicVB** [comment]
@phweyland : sorry, I'm missed that issue...
I've added some new functions to get the images to act on. it's located here https://github.com/darktable-org/darktable/blob/5d2601b12400e12f3685ba02bf38a088f28a8af4/src/views/view.c#L791
(you have a summary of what it does at the beginning)
The idea is to move all relevant action to use this routine instead of using their own algorithm.
I've started to use that for actions specifically related to thumbtable (rating, etc...) and plan to do that also for other actions, it shouldn't be too hard, but sadly I'm quite busy atm with culling rewrite and lot of personal things...

Note that I know that some people dislike the "hover-first" behavior of dt... but once all the actions use the same routine to get images to act on, it shouldn't be hard to propose alternate (and optional) algorithms

**Comment by phweyland** [comment]
>  but once all the actions use the same routine to get images to act on, it shouldn't be hard to propose alternate (and optional) algorithms

I agree on this. My concern is `which actions` are involved. Every action has a specific target of images.
On the other hand we recently have also made changes to include grouped images for some actions.
BTW (off topic) Reading the code, the notion of 'active image' is new for me (I knew the over mouse one and selected ones) . What is an active image ?

So I'm fine to have global routine to return standardized set of images, but I don't think it can be unique. 

More specifically for this issue, the flag DT_THUMBNAIL_SEL_MODE_MOD_ONLY (which prevents the simple click to select an image) is set specifically to filmstrip mode. Is there a particular reason for that ?

**Comment by AlicVB** [comment]
> Every action has a specific target of images.

hmm... do you have in mind some actions that should apply on a set of images different from the set of rating (for example) ? I've forgot to say that there's `dt_view_get_image_to_act_on2` if you want to get single image (the 2 suffix is to be removed once we get ride of actual `dt_view_get_image_to_act_on`)
> On the other hand we recently have also made changes to include grouped images for some actions

yes, `dt_view_get_images_to_act_on` should have a parameter to define if we want just shown images or hidden grouped ones too. This need to be part of the mentioned rework.

> What is an active image ?

it's the images show in the center view (can be multiple for culling) The idea is that when you are in culling mode (for example) and you apply some action with libs in right panel (no image hovered), you apply these action to the images shown in the center view

> More related to this issue, the flag DT_THUMBNAIL_SEL_MODE_MOD_ONLY (which prevents the simple click to select an image) is set specifically to filmstrip mode. Is there a particular reason for that ?

yes, there's a reason ;)
the idea is to avoid user to loose it's selection when using a mode with filmstrip (culling, darkroom if you don't enter via double-click, ...) You still can do all the selections change in filmstrip. the only difference is that you need to alt-click instead of simple click if you want to select another image. ctrl-click and shift-click are unchanged.

**Comment by phweyland** [comment]
> > What is an active image ?
> 
> it's the images show in the center view (can be multiple for culling) The idea is that when you are in culling mode (for example) and you apply some action with libs in right panel (no image hovered), you apply these action to the images shown in the center view

I understand, but the user can still select different images (independently of those visible in culling mode) in filmstrip. (before the visible images were limited by selected ones in filmstrip).
If I tag, add some metadata, export selected what is target ? Different one from the other modes ?

> do you have in mind some actions that should apply on a set of images different from the set of rating (for example) ?

Sorry I didn't mean that actions are applied on different set of images, just that any action must have a clear target. But in darkroom there is an example. Most of the actions are to be done on the developed image, including tagging, exporting, ... But copy / paste history apply to hovered / selected images.

> the idea is to avoid user to loose it's selection when using a mode with filmstrip

That may be a good idea. But selections on filmstrip have a different role depending on the view. Selection in map has not the same role as in darkroom. So why not to save / restore it when needed ?

Not sure I've progressed toward a solution for this issue.
Hovered and selected images is widely used mechanism to retrieved the targeted images.
What do you suggest ?

**Comment by AlicVB** [comment]
> I understand, but the user can still select different images (independently of those visible in culling mode) in filmstrip. (before the visible images were limited by selected ones in filmstrip).
> If I tag, add some metadata, export selected what is target ? Different one from the other modes ?

The idea is that when you use tagging, exporting, whatever in culling mode (same apply for preview or darkroom) targeted images are the one(s) display in main view (what I've called active images). As you point just after, that's coherent with what you expect from darkroom.
Now if one absolutely want to apply some action to a bunch of images (which can be considered as advanced usage imho) he "just" need to show and use filmstrip and shortcuts for that. (we have to keep in mind that filmstrip will be hidden in lot of cases, esp. in darkroom)



> Most of the actions are to be done on the developed image, including tagging, exporting, ... But copy / paste history apply to hovered / selected images.

to reformulate what I've said earlier : 
- mouse outside filmstrip => action on active image
- mouse inside filmstrip => act like if you were in filemanager (action on hovered/selection/...)



> That may be a good idea. But selections on filmstrip have a different role depending on the view. Selection in map has not the same role as in darkroom. So why not to save / restore it when needed ?

you'll have the reverse effect, why should we loose the selection done in filmstrip ;)
That said, is there some interaction problem with map and filmstrip selection ?



> What do you suggest ?

if you use `dt_view_get_images_to_act_on` you'll have this behavior : 
- mouse outside filmstrip : tag applied to active image (image B here)
- mouse inside filmstrip : tag applied to image hovered

That should solves @rabauke issue...

**Comment by phweyland** [comment]
> > What do you suggest ?
> 
> if you use `dt_view_get_images_to_act_on` you'll have this behavior :
> 
>     * mouse outside filmstrip : tag applied to active image (image B here)
> 
>     * mouse inside filmstrip : tag applied to image hovered
> 
> 
> That should solves @rabauke issue...

I was not sure that dt_view_get_images_to_act_on() would work in darkroom. OK, so I make the necessary changes in tagging. 
Thank you.

> the only difference is that you need to alt-click instead of simple click if you want to select another image.

I've tried this but that doesn't work for me (debian 10). Sounds like event is not triggered with alt key...

**Comment by AlicVB** [comment]
> I've tried this but that doesn't work for me (debian 10). Sounds like event is not triggered with alt key...

This give me headhaches too... In fact it was xfce which intercept alt-click for I don't remember what. Once I've change this behavior everything was ok (if that can help you)

**Comment by phweyland** [comment]
> In fact it was xfce which intercept alt-click for I don't remember what. Once I've change this behavior everything was ok (if that can help you)

That did it indeed ! Thanks

**Comment by Nilvus** [comment]
To be closed since merging of #4602
