### ISSUE TITLE
[Lens correction] Darktable not find the good lens

### ISSUE THREAD

**Issue by beudbeud** [darktable-org/darktable#4623]
Hi, 
**Describe the bug**
I have two Sigma lens with a Canon 80D and Darktable don't find the good lens in Lens correction.

For my Sigma 17-50mm f2.8 EX DC OS HSM, Darktable choose always the Canon 18-55 f2.8 IS USM

And For my Sigma 50mm f1.4 Art, Darktable, don't find the lens. I have the number 368 in lens correction module and i need to choose manually.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1
 - OS: Ubuntu 20.04
 - OpenCL: yes 
 - Nvidia: 440.64
- Lensfun: use the last version (i do lensfun-update-data)

Thanks for your work

**Comment by Nilvus** [comment]
It's not a darktable issue but more Exiv2 one. Exiv2 is the library used by darktable to identify camera and lens used by their number id and some characteristics. Then Lensfun use what Exiv2 identify to apply the related lens correction found.

Check lens line and what displayed on image infos. More suitable for that than correction module.

Then check which Exiv2 version you have and see on Exiv2 site and Github one for help or what's possible to resolve your issue (think of closing this one to help developers see which one could be fixed by them. Thanks).

Sites :
https://www.exiv2.org/index.html
https://github.com/exiv2/exiv2 (in issues page there, think of searching if related issues exist, opne and closed ones, with sigma keyword on start).

**Comment by beudbeud** [comment]
Ok thanks i fix it by add some information in exvi2 config file.
