### ISSUE TITLE
Feature: Make CSS Tweaking Simpler

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#4662]
This feature request stems from discussions in #4660 and #4643.

Essentially the idea is that a user can use a standard darktable theme (for example, darktable-elegant-grey) but add their own tweaks to it, by creating a file with the same name as the theme (e.g. themes/darktable-elegant-grey) in their own config directory. That file would only contain the altered css.

When darktable loads the user's chosen theme, in this scenario, it would load the base theme first and then incorporate the user's changes. It would be equivalent to using ``@import`` to load the base theme at the start of the user's own css.

**Comment by jenshannoschwalm** [comment]
I followed the technical part in the other discussions about "tweaking" options related to style. Just my personal opinions
1. i absolutely don't care about such an option at all personally
2. In general i **much** prefer **not** to open such a playground, it's nothing more than that.
3. I fear we would be floated by "Issues" rising like "I absolutely hate the color of icon xxx, i tried to tweak and now it look so greenish"  How would this hell of issues could be kept in limits? I read upcoming issues to find out about bugs. **Those** issues might get out of focus.
4. I think dt should focus on being a productive tool for the user, best algos, good and solid gui, bugfree, fast user interface. I think gui tweaking simply goes in the wrong direction.

**Comment by parafin** [comment]
I support this idea. It’s already possible for user to adjust CSS theme, discussed changes only make it easier and more consistent. Moreover it will actually prevent some bugs when user copies main theme to homedir, updates DT and then have broken GUI due to missing lines in CSS theme. As for the bug types @jenshannoschwalm mentions - as I said they are already possible, so nothing changes IMHO. And finally I don’t think artificially limiting user possibilities is what DT is about. What @elstoc proposes is good design idea and therefore should be implemented.
