### ISSUE TITLE
LUT file moved... Darktable keeps throwing errors about the old location

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#4667]
I have a RAW image with a 3d-LUT Cube file applied.
I reorganized the LUT files.
When I open the image Darktable says 'invalid cube file <the old location>'.

I have cleared the database, the settings and everything. The original location of the LUT is not in the XMP file. 
I have reset the 3dLUT module and applied the Cube file from its new location.

Somehow Darktable keeps throwing the error 'invalid cube file <the old location>'. 
I don't know where the old location is stored but it is somehow fixed and I can not find it nor overwrite it.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1 on Linux Mint.

**Comment by phweyland** [comment]
> I have reset the 3dLUT module and applied the Cube file from its new location.

Is that the only cube file to be invalid ? Do you get this issue with whatever cube file ?
Has a the image an xmp companion ? What does happen if you rename the xmp ?
Is there only one image affected by the issue ?

Probably not related but just to be sure:
Have you set the LUT #D folder in configuration ?
Do haldclut files (png) work better ?

**Comment by phweyland** [comment]
Another potential reason if you have a gmic compatible system:
Try to find in .cache/gmic the name of the failing lut and delete the corresponding file... If this file is corrupted that may explain the issue.

**Comment by rekcodocker** [comment]
**Found it!!**

Comment bt pheyland about the XMP file set me on the right track.
I decided to try to detach the XMP file from the image. First I opened the image to confirm the error was still there... it was. 
Then I noticed it had a large number of Lut-module actions in the history, so I compressed the history.  
**Error gone.**  
So that is where the reference to the renamed file had been hiding: In the history of the Lut module operations.

I still think it's a bug but even though I am a developer myself I am uncertain how I would fix it.  
The software is clearly capable of detecting that the Cube file is missing. You could remove the history-action but then only in the case it is followed up by another LUT3d action which would overwrite it. 
Thanks, my problem is solved (although it is still a subtle inconsistency!).

**Comment by phweyland** [comment]
I'm glad you have found a solution for your problem.
The accumulation of history steps has always been a bit of headache for me.
Even if the step is not active the error is thrown if I remember well. 
I'll definitively look at your idea of removing the step if it is failing. Thanks.

**Comment by user583953** [comment]
Happens on version `dc04d3b` (built from master this week).

Compressing history stack in lighttable fixes the issue.

**Steps to reproduce:**
1. Open an image in Darktable.
2. Add LUT 3D and select a lut file (`$OLD_PATH`).
3. Remove/rename/move etc. the lut file.
4. Go to lighttable and open that image again.
5. Notification appears "invalid png file `$OLD_PATH`" (expected).
6. Update the path to the lut.
7. Go to lighttable and open that image again.
8. Notification appears "invalid png file `$OLD_PATH`" (even though I have updated the path).
9. Enable or disable another module (e.g. exposure).
10. Notification appears "invalid png file `$OLD_PATH`" (even though I have updated the path).

**Expected behavior:** darktable should not notify about old invalid paths in the history stack.
