### ISSUE TITLE
Tagging module request : simplified UX in "dictionary view"

### ISSUE THREAD

**Issue by GwenaelQ** [darktable-org/darktable#4814]
Hello, 

**Issue**
- It is annoying to rise an error when using pipe with "edit tag" command of "dictionary view", 

meanwhile  :

- "rename path dialog" allows the use of pipe, although it has a very similar dialog box,
- creating tag within entry zone allows the use of pipe 
 
**Request**

Since in some places of the  tagging module a path is "just" a "tag with pipe inside" why not simplify the interface, and improve consistency, by combining the possibilities of both "edit tag" and "rename path dialog" under an "edit tag".

The single command only dedicated to path would then be "delete branch".

Thank you for listening

**Comment by phweyland** [comment]
I understand the request, however, even if they are similar, they are not really consistent.

"rename path" allows the user to split or combine different levels on the path of a given tag. It is not applicable in list view because a change on the path may impact a lot of other tags in the list, while in the tree view it affects only the selected tag.

The list view is for people who don't care about hierarchical tags and for consistency with previous versions.

"edit tag" allows the user to change the tags attribute. It works in both list and tree view.

Of course, that would be possible to do what you request but I'm not sure this desirable. If we removed the list view and had only the tree view that would be easier.
