### ISSUE TITLE
Tagging module request - dictionary view :  same commands in list view than tree view

### ISSUE THREAD

**Issue by GwenaelQ** [darktable-org/darktable#4815]
Hello,

When in "tree view" mode , the "dictionary view" shows many commands within contextual menu (right click) that doesn't appear in "list view" mode. 

These commands should be available in that mode too.

Thank you again for the very good work

DT 3.0.2 in windows 8.1

**Comment by phweyland** [comment]
Here some explanation about why it is not (yet) as you request.

Between list and tree view there is only one difference, "rename path". See my comments [here](https://github.com/darktable-org/darktable/issues/4814#issuecomment-619437434) about "rename path".

The third view, suggestion view, tries to sort out the most relevant tags depending on selected images. It's an helper for tagging and is not related to tag maintenance. Making tags change here could have unexpected results as the user doesn't see all the tags. Then it interacts  a lot with database and is slower than the other ones.
That's why we have few commands here. 

My concern about suggestion view is that it is not very relevant in reality. We would need a bit of AI, or at least some statistics about usage depending on subject, location, recent usage, ... to be more accurate. But that's another story.

I hope this helps a bit.
Thanks for your interest about tagging
