### ISSUE TITLE
Fujifilm X-T200 support

### ISSUE THREAD

**Issue by manithree** [darktable-org/darktable#4853]
I've submitted a raw sample from my X-T200 at raw.pixls.us

I don't think there are any other raw options supported by the camera, but I just got it yesterday, so if more are needed, I'll try to do it.

**Comment by digitalillusions** [comment]
Hi, I'm wondering what the status of the camera support of the X-T200 is at the moment? I see there are commits to a fork with basic camera support and a custom color matrix to a fork, but was never propagated. However, I also see the same commits in the darktable master when I do a search and the commits were before the most recent stable release. Do I need to build darktable from source to get access to the custom color matrix or is this a different color matrix somehow? Sorry if this question is a bit ignorant, I'm just getting into the workings of all of this.

**Comment by manithree** [comment]
I'm pretty sure there have been a couple of releases with full X-T200 support. You shouldn't have to build from source unless your distro's package is pretty old, or something like that.

**Comment by BonziBuddy21** [comment]
Is there going to be a Support for the XT-200 in the next 1 or 2 Updates? I honestly dont know what it all means here (im sry)
Im just using it on my chromebook and its a miracle for me i got it working on there. But i didnt saw a Support for it, because it would be easier for me to use the denoise (profiled) with it. And is it somehow possible to get that Code on my Chromebook working?
