### ISSUE TITLE
Culling mode: use all screen space available when zooming

### ISSUE THREAD

**Issue by moy** [darktable-org/darktable#4885]
**Is your feature request related to a problem? Please describe.**

In culling mode, each image is assigned a rectangle corresponding to the aspect ratio of the image. This obviously makes sense when the images are displayed completely (zoom fit), but when zooming in, it's frustrating to show only a rather small portion of the image with a lot of screen real estate lost:

![current](https://user-images.githubusercontent.com/14709/80807078-7f0ea480-8bbc-11ea-89ee-caf0ce7c07cb.jpg)

**Describe the solution you'd like**

The portion of screen assigned to the image shouldn't depend on the aspect ratio. It should be computed based on the number of images, and then, if the image doesn't fill the portion of the screen assigned to the image, the uncovered portions should be greyed out. This is what's done in darkroom, but darkroom does it for a single image (when zoomed out, there is a lot of grey padding, but when zoomed in, the image covers the whole area).

A mock of what it could look like (even with landscape images):

![full](https://user-images.githubusercontent.com/14709/80807177-c4cb6d00-8bbc-11ea-88bd-7a2d0f71d384.jpg)

**Comment by AlicVB** [comment]
completely agree ! Sadly the problem is that I didn't manage to understand the code that place and size the image in culling mode... and the original author isn't here anymore :(
Each changes I've done here so far end with weird corner cases...

If someone want to have a look, it's located in `views/lighttable.c` `_culling_compute_slots` in current master, and in `dtgtk/culling.c` `_thumbs_compute_positions` in my culling rewrite which should soon (PR #4864 )...
