### ISSUE TITLE
LUA: erratic behaviour of sliders after commit 36d459f

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4909]
After commit 36d459f2698695b9245e55cbc516698ab1eb3074, the behaviour of slua slider has become unpredictable, with soft_min and soft_max limits do not respect values set in the code, but are erratically set.
To try to reproduce, take the following script, which defines a simple LT module with one test slider.
[slider.lua.txt](https://github.com/darktable-org/darktable/files/4574804/slider.lua.txt)

Run the script several times, playing with the slider.

Before the mentioned commit, at DT start the result is consistently the following, as expected
![Cattura2](https://user-images.githubusercontent.com/43290988/80969282-a6ae7880-8e19-11ea-8ddc-7e746f256a83.JPG)

after the commit, sometimes I get this
![Cattura](https://user-images.githubusercontent.com/43290988/80969357-be85fc80-8e19-11ea-86d6-d8306b326bb2.JPG)

DT git master on Windows 10.

**Comment by Mark-64** [comment]
I did some investigation and it's pretty weird. I might be wrong, need some help here, but it could be a sort of race condition.
In lua/widget/slider.c, the code
```
int dt_lua_init_widget_slider(lua_State* L)
{
  dt_lua_init_widget_type(L,&slider_type,lua_slider,DT_BAUHAUS_WIDGET_TYPE);

  lua_pushcfunction(L, tostring_member);
  dt_lua_gtk_wrap(L);
  dt_lua_type_setmetafield(L, lua_slider, "__tostring");
  lua_pushcfunction(L,digits_member);
  dt_lua_gtk_wrap(L);
  dt_lua_type_register(L, lua_slider, "digits");
  lua_pushcfunction(L,step_member);
  dt_lua_gtk_wrap(L);
  dt_lua_type_register(L, lua_slider, "step");
  lua_pushcfunction(L,hard_min_member);
  dt_lua_gtk_wrap(L);
  dt_lua_type_register(L, lua_slider, "hard_min");
  lua_pushcfunction(L,hard_max_member);
  dt_lua_gtk_wrap(L);
  dt_lua_type_register(L, lua_slider, "hard_max");
  lua_pushcfunction(L,soft_min_member);
  dt_lua_gtk_wrap(L);
  dt_lua_type_register(L, lua_slider, "soft_min");
  lua_pushcfunction(L,soft_max_member);
  dt_lua_gtk_wrap(L);
  dt_lua_type_register(L, lua_slider, "soft_max");
  lua_pushcfunction(L,value_member);
  dt_lua_gtk_wrap(L);
  dt_lua_type_register(L, lua_slider, "value");
  lua_pushcfunction(L,label_member);
  dt_lua_gtk_wrap(L);
  dt_lua_type_register(L, lua_slider, "label");
  return 0;
}
```
seems to put the following functions (among others), defined in the same source file, in a sort of execution queue:
```
hard_min_member()
hard_max_member()
soft_min_member()
soft_max_member()
```
In turn, those functions call respectively the following ones:
```
dt_bauhaus_slider_set_hard_min
dt_bauhaus_slider_set_hard_max
dt_bauhaus_slider_set_soft_min
dt_bauhaus_slider_set_soft_max
```
in bauhaus/bauhaus.c, which are the ones affected by the commit in question.

With gdb in Eclipse, in both Windows and Ubuntu, I've verified those functions are not called in the same order they appear in `dt_lua_init_widget_slider()`, but with a random order, which can change at every DT run.
I guess that instead the order of those calls is important, as the result depend on it, at least with the new code after the commit (but maybe the problem was there even before, only hidden)

To verify my hypothesis, I would need to force the order of execution of the functions.
Is there anyone that knows how to do it ?

**Comment by TurboGit** [comment]
Looks like a regression from 36d459f2698695b9245e55cbc516698ab1eb3074.

@dterrahe : Any idea ?

**Comment by dterrahe** [comment]
Interesting.

I haven't worked with lua, so I don't even know where the magic happens and I'm just guessing here; please tell me if I get this wrong. 

It looks to me like the lua api allows to create a bauhaus object without going through one of the "_new" calls (for example dt_bauhaus_slider_new or dt_bauhaus_slider_new_with_range_and_feedback). In the example code, after an uninitialised widget is created, the following calls (is that an initialisation block?) set its fields one by one, but seemingly going through the several "set" functions.

In #4846 a change in behavior is mentioned (but maybe cryptically, I admit). Previously setting a soft limit outside of the hard limits would stretch the hard limit in order to let the new soft limit fall within range. But since we are working on initialising sliders from the hard limits specified in introspection and making them guard/enforce those limits, this looked like undesirably behavior to me. So instead the new code clips new soft limits to the existing hard limits and doesn't change the hard limits except by explicitly calling set_hard_min/max.

Of course if the hard limits haven't been initialised yet and probably contain random rubbish, setting the soft limits first could lead to them getting randomly clipped.

So hard limits should be set first and then soft. If lua doesn't guarantee an order within an initialisation block, maybe the soft limits can be explicitly set _after_ the object has been fully initialised?

But to be honest, I had not expected this kind of problem cropping up and if there is no guaranteed way at the lua interface level to avoid it, the change should probably be backed out to not cause a lot of pain and confusion going forward. My apologies for the amount you have suffered so far and thanks for bringing this to my attention.

**Comment by Mark-64** [comment]
@dterrahe No need to apologize, this is the beauty of SW development :-)
I don't think reverting the commit is the solution, I have the feeling the problem was already there. Now that I think about it, I noticed some rare misbehaviour of the lua sliders in the past that I didn't pay too much attention to.
I will try to change the lua code instead, any suggestion is welcome

**Comment by dterrahe** [comment]
Maybe, but the old code was very forgiving; basically not enforcing the hard limits so they didn't cause any trouble. There may be more out-of-tree code out there that has started misbehaving. Maybe the right thing to do would be to at least print a debug message whenever input that was previously allowed is now being clipped, so that people can at least be aware that their code violates some new assumption.

I'd be happy to put that in. And if you have any suggestions for a mechanism to pass debug info back to lua, that would be welcome too.

**Comment by wpferguson** [comment]
@Mark-64 perhaps you could do a check from dt_bauhaus_slider_set_soft_min() and dt_bauhaus_slider_set_soft_max() to see what the hard limits are and set them if necessary.

**Comment by Mark-64** [comment]
This has proven to be too hard for me.
The lua calls use a Glib asynchronous queue, so there is absolutely no guarantee of the execution order of the four setting functions:

```
dt_bauhaus_slider_set_hard_min()
dt_bauhaus_slider_set_hard_max()
dt_bauhaus_slider_set_soft_min()
dt_bauhaus_slider_set_soft_max()
 ```
This is a problem in the initialization, because if for example `dt_bauhaus_slider_set_soft_max() ` in order to set `soft_max` needs to know `hard_max`, that value could be not initialized yet.
There is no problem instead if for example `dt_bauhaus_slider_set_soft_max() ` sets `soft_max` and also `hard_max`. Which is the way the old code worked.
At this point I see only two alternatives to revert the commit:
1) Modify the lua calls async queue so that the initialization is single threaded
2) Write a duplicate of the aforementioned functions (maybe not all are needed) for usage with lua only

I have absolutely no idea how to do option 1), but I can do option 2).
Opinions?

**Comment by dterrahe** [comment]
Again, I have no idea how the lua glue works, but I'm a bit surprised that the newly allocated slider object doesn't somehow get initialised before any of the set functions get called. My preference would be for it to be initialised with hard limits at -INF and +INF, but given that this is probably not possible, I'll submit a change to revert just that change (not the main part of the PR which was to add a new set_soft_range function.)

Last question though; is it possible to set the soft_min and soft_max __after__ the call to new_widget() is completed? That should no longer be queued asynchronously, I would think? Like the "test_slider.value = 50" at the end of your example.

**Comment by Mark-64** [comment]
There is an initialization call
```
static void slider_init(lua_State*L)
{
  lua_slider slider;
  luaA_to(L,lua_slider,&slider,-1);
  dt_bauhaus_slider_from_widget(DT_BAUHAUS_WIDGET(slider->widget),NULL, 0.0, 1.0, 0.1, 0.5, 3,0);
}
```
which uses some default values, maybe we can use that one ?

**Comment by Mark-64** [comment]
@dterrahe as you suggested, changing to
`dt_bauhaus_slider_from_widget(DT_BAUHAUS_WIDGET(slider->widget),NULL, -1.0E9, 1.0E9, 1.0, 0.0, 3,0);`
seems to work. I'll do more tests

**Comment by Mark-64** [comment]
It works, @dterrahe  thanks for helping me !
PR created

**Comment by dterrahe** [comment]
You are welcome.

If anything depended on the old default values and breaks, at least this time the cause should be easy to find and to correct for.

**Comment by Mark-64** [comment]
Fixed
