### ISSUE TITLE
Last picture opened is not saved in lighttable when exiting on darkroom

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#4911]
The lighttable saves in `darktablerc` the ID of the last selected image and last selected collection, so the next time darktable starts, the lighttable opens centered on that same image again, inside that same collection.

However, this requires to close darktable with the lighttable view active. If you close dt when you are in darkroom (or if dartable crashes in darkroom…), the current image ID is not saved and darktable re-opens with lighttable view centered on a random picture.

The feature request is to save the current image ID to `darktablerc` in every view, when exiting the software.

**Comment by TurboGit** [comment]
This is not saved in darktablerc but in selected_images in library.db. And indeed, the last selected images stored is the one when entering the darkroom (so not really a random image but still).

I'll have a look at this issue.

**Comment by TurboGit** [comment]
See #4914 , can you test ?

**Comment by AlicVB** [comment]
@aurelienpierre : I don't reproduce except on dt crash.
To be sure we are speaking of the same thing : 
usually, when you go back to lighttable from darkroom, the last edited image is the first image shown in filemanager (top left). And this is not the case when you close dt directly from darkroom. I'm right ?

If effectively, it's only in case of crash of dt, I know where the problem is coming from : dt doesn't seems to write rc file on the fly, but on exiting (correctly ;)) only. I'm not sure if it's worth the pain to force the write in this case, as all of us know that dt is NEVER crashing :) and because imho it's not a really crucial data loss in this specific case

**Comment by aurelienpierre** [comment]
> To be sure we are speaking of the same thing :
usually, when you go back to lighttable from darkroom, the last edited image is the first image shown in filemanager (top left). And this is not the case when you close dt directly from darkroom. I'm right ?

Yes. Also if you open an image directly from the file manager. I need to test this solution, I'm in the middle of something.

**Comment by TurboGit** [comment]
Is this issue still present ?

**Comment by aurelienpierre** [comment]
Seems gone.
