### ISSUE TITLE
DT3 Retouch module regression (high contrast artifacts on skin)

### ISSUE THREAD

**Issue by choller** [darktable-org/darktable#4938]
**Describe the bug**

When using the retouch module in DT3 to eliminate skin irregularities, I get weird artifacts that look like a contrast problem of some sort.

**To Reproduce**
1. Load the attached ARW: [DSC01932.ARW.zip](https://github.com/darktable-org/darktable/files/4594262/DSC01932.ARW.zip)

2. Perform a retouch as shown in the attached screenshot.
3. Observe the problem.

I can only reproduce this on RAWs (Sony), not on the respective JPEGs.

**Expected behavior**

Retouch should work seamlessly.

**Screenshots**

![dt3-retouch-bug](https://user-images.githubusercontent.com/1140686/81318882-3446ce00-908f-11ea-9205-98e0d2f58b4b.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Linux (Ubuntu 18.04)
 - OpenCL support active
 - Intel Corporation UHD Graphics 620, i915 driver

**Additional context**
 - Does not reproduce in DT 2.6, this is a very likely a DT3 regression
 - Only reproduces on RAW
 - The screenshot is with a base curve applied, but base curve is not necessary to see the issue.
 - I already observed this in DT3 beta, but did not have a testcase. We made the attached picture specifically for this bug report.
- Image was shot on a Sony Alpha 7Riii in Super35 mode to reduce RAW size

**Comment by aurelienpierre** [comment]
Retouch copies the texture from source to target. I don't see any issue here. It does not eliminate irregularities, it is not a healing brush.

**Comment by choller** [comment]
> Retouch copies the texture from source to target. I don't see any issue here. It does not eliminate irregularities, it is not a healing brush.

With this response, I really have to wonder if you actually took the time to read the bug report, which is somewhat disappointing, given that I spent quite some time on properly reporting this.

1. This is a *regression*. The same thing works nicely in DT 2.x.

2. This is a *RAW-only* problem. The exact same thing on JPEG works as expected.

3. If you take a close look at the sample image I provided, you should clearly see, that there is serious over-contrasted/saturated in the retouched area. I have no issue with the texture being copied, in fact, that's how I expect Retouch to work (and how I always used it), but it doesn't simply do that with this example.

**Comment by paperdigits** [comment]
Are you sure you don't just need some feathering around that heal spot?

**Comment by choller** [comment]
> Are you sure you don't just need some feathering around that heal spot?

This is actually with feathering, and I noticed that feathering sometimes seems to make this even worse. And as I mentioned before, I've been using this tool regularly on DT2, this behavior is purely in DT3.

**Comment by johnny-bit** [comment]
I've re-checked and discussed the problem further.

The problem is visible on dt 2.6.3, albeit not as pronounced. That might be because of various changes, but the core issue remains: You've chosen a particular patch with high detail that is not as visible in bright area and used it to retouch darker patch in darker area. This increases contrast. If you'd chose a patch of skin a bit below and to the left instead then the contrast would be lower and would work very nice.

This "works" with jpegs probably because of ingrained smoothing, lower DR and loss of details in jpegs as whole. I managed to extract jpeg (previewimage) using exiftool and i could see similar problem visible but not as pronounced (mainly i believe due to lower dr of jpeg and lower resolution)

I do think this works as intended and maybe considered an improvement over dt2 exactly for better taking contrast into account.
