### ISSUE TITLE
Could the Library be optionally disabled altogether?

### ISSUE THREAD

**Issue by progo** [darktable-org/darktable#4942]
**Is your feature request related to a problem? Please describe.**

The library (.config/darktable/library.db) that compiles metadata about files is acting like a giant cache, and like a cache, when the data goes stale it's usually a pain to correct.

For example, I import a directory of photos of two cameras. I immediately notice that the timeline doesn't align -- one of the cameras had bad time. I fixed that thing quickly with a small exiftool invocation but the timeline remains unaligned, (or aligned to the old timestamps).

**Describe the solution you'd like**

It is largely an unnecessary thing for me (and many others, I gather?). Deleting the library.db every once in a while is a complete no-op for me; I don't see much of  a difference what data I am seeing.

**Alternatives**

```
darktable
rm ~/.config/darktable/library.db
```

Suppose this sort of a thing would work to a degree (although would like to hear about dev's about this, something I may miss). 

Still need to restart Darktable sometime in the midst of a focused editing session, if I go this way.

**Additional context**

**Comment by Nilvus** [comment]
Did you read the manual (https://darktable.gitlab.io/doc/en/overview_chapter.html#program_invocation)? This file stores all image information, so also history work on darkroom (XMP are only last saved state) and so allow also to use cancel/redo shortcuts, etc.

I don't see a "big giant cache". If you have one, it's probable because you have thousands and thousands images. This file is important to keep all features darktable allow on image.

So it's far to be an "unnecessary thing" (except probably for you).

**Comment by parafin** [comment]
library can be set :memory: in config file I think

**Comment by progo** [comment]
Okay got it thanks. I was under a false impression that the library only contains cached analysis of imported files.

**Comment by wpferguson** [comment]
@progo as far as fixing the timestamps in your images, there's a new lua script, image_time.lua, waiting to be merged into the [lua script repository](https://github.com/darktable-org/lua-scripts) that can fix timestamp issues in the database.
