### ISSUE TITLE
Selection broken (?) in culling

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#4965]
**Describe the bug**

Viewing images in culling does not seem to allow a way to select an image.

Clicking on the image does not select it... hovering the mouse seems to, but if I try to go to darkroom, that is lost and I get "no image selected". same applies for the thumbnails: hovering selects, but clicking does not.

I can double-click to go to dr, but there are also issues with eg deleting or removing: if an image is selected in file mode, then I go to culling and the selected image is off screen, it is still that image that is selected even if I click on one on screen. Particularly dangerous when the tool-tip says "1 image selected."

There is also the issue of returning from dr and finding that a different image is selected (possibly related to #4911 & #4957), and also the return of an old issue: deleting the last image on a film strip when viewing 1 image / screen leaves no way to get back to images.

**Expected behavior**

Clicking on an image in culling view should select that image. Deleting an image should not leave the screen blank while there are still images in the fim strip.

dt3.1.0+1481 Win 10 release 190318-1202

**Comment by Nilvus** [comment]
If I count correctly, you don't have CSS tweaks needed to finish these modes, so some selected/hover issues you have could be broken on your release. That's probably don't explain all you describe. I use last master (+1495) and culling/preview works great on my side.

**Comment by GrahamByrnes** [comment]
Ok, will update :-)

**Comment by GrahamByrnes** [comment]
Well, some things are better: it doesn't seem to crash after importing new images now :-)

However the failure to select in culling remains. 

I wasn't able to get stranded with a blank screen after removing an image, but I did manage to get this:
![image](https://user-images.githubusercontent.com/58031430/81480489-722c2980-922a-11ea-8d6a-2fac41579306.png)

**Comment by AlicVB** [comment]
@GrahamByrnes : as you may have noticed, I've very recently rewritten all the culling and preview part, like what I've done for filemanager weeks ago. The amount of change was huge, so that's expected that there's some glitches and issues on this part.

Now for your question about selection in culling : there's 2 culling mode dynamic and fixed
- in dynamic mode, the image you see are the selected ones. If you change the selection via filmstrip, the shown shown change too.
- if you start fixed mode with selection exactly equals to the images that will be shown, then we consider that the selection is not a "real" selection but just a indication for which image to show. In this case, the selection will follow the images shown in culling mode if you scroll.
- if you start fixed mode with selection different to the images that will be shown, we don't change the selection, except if the user do it with filmstrip and a modifier key.
- Note that preview can be considered as fixed mode with zoom = 1

For the return from darkroom, I'm not sure to understand the issue, but this works like culling in fixed mode too : don't touch the selection in the back of the user.

Now for the confirmation dialogs, the term selected can clearly be confused, and that's not the only problem. I'm currently working of uniformazing all this part (on which image to act on)

**Comment by GrahamByrnes** [comment]
No question, bravo for the work! As you say, some of the issues above may be legitimate choices. I expect thay will be debated as more people try them, which must be a good thing.

However, I think having the module "selected image" delete an image which is selected "off screen" is dangerous...

**Comment by Mark-64** [comment]
I noticed this behaviour: if you are in fixed zoom mode with N images and then you move to dynamic zoom, you start with N images, which is expected.
Then you can decrease/increase the number of images shown by CTRL+click in/out of the selection in filmstrip.
This works until there are two images in the selection, but if you reduce to one, then suddenly the number of image shown jups back to N, where you started from.
This is pretty strange.

**Comment by GrahamByrnes** [comment]
Mea culpa, I hadn't read the manual for the raison d'être of culling mode.

I still think there could be some discussion about the choices, but I should have been calmer about this. I can say that now I've gotten away from +1481 and I can change to file manager without a crash, that view seems to be working impeccably.

**Comment by Nilvus** [comment]
@GrahamByrnes and @Mark-64: I think this PR by @AlicVB could help and be tested for that:  #4980

**Comment by Mark-64** [comment]
Testing #4980, but it shows the same behavior described two posts ahead

**Comment by AlicVB** [comment]
@Mark-64 : I admit I've add difficulties to understand your post. But now I think I got it :) In fact, there's a problem when switching from fixed to dynamic that is more than what you see... I'll try to fix that asap
