### ISSUE TITLE
[FR] Static and ordered collections

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#5018]
**Is your feature request related to a problem? Please describe.**

Today it's possible to move around images in a given collection (custom order). But the images order is global. Then if you to shuffle another collection with the same images you loose the first order.

Furthermore the stack of recent collection is limited and one is going to loose the collections quickly.

Tagging covers a part of the need (static collection) but is not image position aware.

So in fact there is no way to keep in darktable a collection of images properly ordered (wedding, ...). This is an issue which has been discussed for a long time. See [here](https://discuss.pixls.us/t/virtual-album-collection-in-darktable/18139), [here](https://discuss.pixls.us/t/the-obvious-darktable-how-to-drag-and-drop-move-an-image-within-a-folder/6358), ...

**Describe the solution you'd like**

I would like to solve this and I open this FR to get comments, directions, suggestions ...

The solution I can see would be more or less this one.

A new module is called "collection", or "album", or anything more appropriate. This module  exposes the following actions:
- create collection
- delete collection
- add selected images to one of the collections
- remove selected images from current collection.

The collections are visible from collect module. As such, the user can select one of them and order the images as needed. 
The image (and the xmp) is not aware of collections (each image can belongs to several collections).

Challenge.
Modify the current global image order to turn it specific to each collection. 
From the image order standpoint the current collection, and potentially the 10 recent ones (?), are seen as collections and have each its own order.

Some doubts.
Outside the new static collections, do we need to keep a custom order ?
Does it exists any necessity to have a global order for all images of the database ? Which use case ?

What do you think ?

**Comment by GrahamByrnes** [comment]
I think it's an excellent idea. I have some tag-collections which are already getting a bit too big, and I'm (very) far from a commercial photographer in volume. Of course I could go back and start adding secondary tags, but that is potentially a lot of retrospective work with no immediate pay-off... and life is short. 
Being able to pull the images that I'm excited about _now_ into a new structure would seem to fix this.

**Comment by spaceChRiS** [comment]
Oh, wow, dreams becoming true ... Some random thoughts:
* Calling it album seams appropriate as collection is already used.
* Shall the albums are represented in a tree structure as well or only in a flat hierarchy, wedding-x-y-2020|album ..|presentation etc. vs wedding-x-y-2020-album and ..-presentation? Tree would be more compatible with tagging.
* Interaction with collect module: My idea would be that albums are on top of the collect module, such that collect module works on the images of the album. Default state would therefore be no album selected. On the other hand, albums could be part of the darktable tag tree such that I can e.g. check which images are overlapping between albums etc.
* Order is always given by the selected album of course, if not specified otherwise (means an additional entry "album" and "album-reverse" in the sort order drop-down).
* Why not add the collection as part of the darktable namespace to the tags in xmp? The order is not in the xmp, but one could at least reconstruct the albums from the xmp.
* Export module could get a custom $() replacement in the file name such that an album can be exported with ordered filenames. The album name itself maybe as well? "Album_name-001-original_filename.jpg".
* All images could automatically be part of the default album such that the global order would be no issue. In the UI, no album automatically translates to default album internally.

**Comment by phweyland** [comment]
>  Shall the albums are represented in a tree structure as well or only in a flat hierarchy, wedding-x-y-2020|album ..|presentation etc. vs wedding-x-y-2020-album and ..-presentation? Tree would be more compatible with tagging

> Why not add the collection as part of the darktable namespace to the tags in xmp? The order is not in the xmp, but one could at least reconstruct the albums from the xmp.

Agreed. My current collections are based on tags. Except they cannot keep the order. That also answers the second point.
My concern here is that I find the collect tags a bit slow...

>  My idea would be that albums are on top of the collect module, such that collect module works on the images of the album.

I may be wrong but it seems difficult to put something on top of collect module, which is the root of lighttable structure. On the other hand it should not be too much difficult to check if the first level of collect filters is `album` related or not.

>  Export module could get a custom $() replacement in the file name such that an album can be exported with ordered filenames. The album name itself maybe as well? "Album_name-001-original_filename.jpg".

Good point, this missing today as well. Export selected doesn't consider the display order of selected images. But if it did, $(SEQUENCE) should cover the need, including combining it with any other name elements.

**Comment by spaceChRiS** [comment]
> it seems difficult to put something on top of collect module

I did not mean it literally. It could as well be part of the collect module. I meant it means "album AND (collect module selection)". Your idea sounds good as well, but it is maybe not so easy to explain to the user than having e.g. a separate drop down.

**Comment by lhietal** [comment]
In my workflow I see two distinct ways in which I use tags. That for me suggests how the proposed feature would fit in to my way of organizing images.

- what the images contain or what they represent, all images (tags proper)
- how the images are used or published, most important images (albums)

I would mostly work with only one _album_ at a time. Using "collect images" module and tags to search images and add them to the album. So I think albums are in some way similar to presets in "collect images". Ordering is important for coming up with the final set of images. And then work with the album in darkroom and exporting.

For this use case it would be good to be able to easisly switch between an album and filtered collection. Having a tree structure is good for managing large dbs but 1–2 easily accessible albums could speed up working. Maybe keyboard shortcut for adding images to the album and for displaying the images. Or dedicated are for some albums in a tree view (favorites).
