### ISSUE TITLE
[FR] New keep original filename : improve it in import section

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5040]
**Is your feature request related to a problem? Please describe.**
Not really a problem but a suggestion. #5007 PR from @jenshannoschwalm adds a new feature on import section in preferences window and this line is related to the following line where a pattern could be set if keep original filename is not checked.

**Describe the solution you'd like**
I suggest to simply deactivate and put in grey entry pattern when the keep original filename checkbox is checked and reactivate that entry field when keep original filename is uncheck.
Exactly the same way as the new lines to set font on general tab.

**Comment by jenshannoschwalm** [comment]
Yeah -- for a better UI :-)

**Comment by jenshannoschwalm** [comment]
But -- this seems to be very tricky, at least for me. The import tab is automatically generated via the xml and there seems to be no option to make an entry switchable "hidden". Any idea? (doing the widgets manually would add code to be maintained ... )

**Comment by johnny-bit** [comment]
gui preferences were generated from xml... @elstoc can you look at this? It's really interesting!

**Comment by elstoc** [comment]
Hmm. Easy enough on the hard-coded sections of preferences but sounds like it might be a tricky to do in the auto-generated ones.

**Comment by jenshannoschwalm** [comment]
The auto-generating is the point 🤔 I guess the xml2code is not aware of such stuff.

**Comment by Nilvus** [comment]
Thanks for trying but If it's too tricky, we can forget that. Not so important. It's as want.

**Comment by elstoc** [comment]
You'd probably have to build some preference that combined the boolean and the string in one and built both at the same time, since afaik the widgets are each assigned names containing an integer and the boolean widget won't know the name of the string widget and vice versa. If we thought it would get a lot of use it might be worth it but for one pair of prefs, maybe not.

**Comment by Nilvus** [comment]
It's actually for just one setting so indeed not needed to add to much new lines of code and lost time for that. Just say me and I close this issue.

**Comment by elstoc** [comment]
An alternative that might have more general use would be a combined GtkComboBox and GtkEntry input, where you could define a list of common options but still let the user type their own value. This shouldn't be too difficult since we can likely just duplicate the existing enum type and use ``gtk_combo_box_with_model_and_entry``. Might that work for this input?

**Comment by jenshannoschwalm** [comment]
> Might that work for this input?

I don't know. We also must be able to take defaults somehow.

I really good solution would be able to switch between show/hide of 'items' depending on a given bool.

**Comment by elstoc** [comment]
enums can already take defaults. I'd have thought it should be possible to duplicate that enum type in ``generate_prefs.xsl`` but using the combobox_with_entry instead. Then you could put the existing default plus whatever the variable string needs to be for original filename as enumerated values, while still allowing the user to overtype with their own.
