### ISSUE TITLE
Crop and Rotate Aspect Ratio Problem

### ISSUE THREAD

**Issue by InchoateImages** [darktable-org/darktable#5057]
**Describe the bug**
The Crop and Rotate module does not handle image aspect ratio properly.

I’m running 3.1.0~git1382.cb99cf52f.

When I edit a new photo, it doesn’t default to the camera image aspect ratio. It always defaults to ‘freehand’. Once I select the ratio that I want and save the photo, when I open it again and look at the crop aspect ratio, it shows ‘freehand’ again.
I’m pretty sure this used to work in some earlier version. -->

**To Reproduce**
1. Open an image and select Crop and Rotate
2. Look at 'Aspect'.  It defaults to Freehand
3. Select any desired aspect and edit the photo.
4. Leave the module.
5. Open the module again and Aspect is back at Freehand.

**Expected behavior**
It should detect the natural aspect of the image when opened.
It should remember the aspect ratio of a modified image.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0~git1382.cb99cf52f
 - OS: KDE 19.10
 - OpenCL activated: yes
 -Which graphics card and driver version: Nvidia  GTX960M

(Sorry if I've done anything wrong, I'm a newbie to Github)

**Comment by ptilopteri** [comment]
It is a bug recently introduced.  I see the same.  Crop ration always remained the last selected raio, but now now.
darktable-3.1.0~git1604.1f74b4108

**Comment by sboukortt** [comment]
> **Expected behavior**
> It should detect the natural aspect of the image when opened.

For what it’s worth, I disagree with the idea that the original aspect ratio is intrinsically “natural”. If I am cropping, that in itself is a signal that I want to deviate from the original framing. In such a situation, it makes no sense to me to reduce the vertical FOV just because I want to exclude (say) something on the right. If I want to restrict myself to a certain aspect ratio, it will be because of the *output* (e.g. 4:5 for Instagram, 16:9 for a TV…), not because of the input (my cameras don’t even all have the same ratio).

I definitely agree that the choice should be remembered across sessions, but “freehand” as the default seems good to me. It’s much less arbitrary than being restricted to 4:3 on some of my cameras and 3:2 on another.

**Comment by InchoateImages** [comment]
Different people have different requirements. While I do crop creatively for some of my photos, a large number of my images I simply level the horizon and crop slightly, keeping the original aspect ratio. As I had just returned from a trip with 1000's of images to process, having to repeatedly re-select the aspect ratio each time has been frustrating. 

I will point out that this was a recent change. The original behavior was to default to the image aspect ratio.

**Comment by sboukortt** [comment]
Was it? That’s not what I remember in ~2 years of darktable usage.

**Comment by ptilopteri** [comment]
I have been using dt for 8 or 9 years now and to my aged memory, the crop ratio alway returned as the last time it was used.  If I close dt and had cropped at 3:4, when I open dt it returned with crop set to 3:4.  If I edit an image and use 16:9, the next image I edit defaulted to 16:9, and on ...

**Comment by TurboGit** [comment]
A bug, I'll try to have a look. This is probably due to latest change on this module from Aurélien.

**Comment by TurboGit** [comment]
As I thought this is due to 504b0abdfa52bc9c576ffd94dd74742e1c13e94a.

@aurelienpierre : can you have a look ?

**Comment by TurboGit** [comment]
Was easy, this is now fixed.

**Comment by aurelienpierre** [comment]
Sorry about that.
