### ISSUE TITLE
Support for animated gifs in lighttable

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#5122]
Many people are looking for a program that helps them managing all their personal photos. The image format may differ and might also contain animated gifs. Darktable is able to display the start of the gif (first frame) but does not show the animation. 

It would be very nice if darktable was able to playback the animated gif.

**Comment by parafin** [comment]
dt is a raw editor, not image viewer. dt won't be able to edit animated gifs, so no reason to display them.

**Comment by codingdave** [comment]
I agree partially. But the gifs are displayed already and you can also open
the darkroom and edit them, it's just that the animation does not work. I
did not see what happens when you export these with our without prior edit.

parafin <notifications@github.com> schrieb am Di., 19. Mai 2020, 10:41:

**Comment by parafin** [comment]
formats like gif are supported thanks to graphicsmagick/imagemagick integration, which can read a lot of different formats, some of which, I'm sure, have other non-standard features, e.g. multiple layers. dt won't support these.

**Comment by Drakonas** [comment]
@parafin The neverending search for a program that can handle large libraries of images with animated gif thumbnail support continues....

I've tried tons of image library management software, and nothing supports it.

If this is a case of "the performance required would be too substantial because of the design of lighttable", then I understand, but there literally is no software that does this that I've been able to find, yet Google Photos can do it online just fine.

I don't mean to beg here, but it's sad that even the bigname image library software (ACDSee, Adobe) don't even support animated gif thumbnails. I've even complained to ACDSee about the feature and they've said they've added it to the notes for a future update, and it's been 3 years and it never happened.

Color me frustrated, but I'm asking any developer of such software that if they consider putting in the effort for this kind of capability, as long as it is realistically possible with their software design, then they would be met with a lot of open arms from the community that is looking for such a software.

Google Picasa left a lot of people hanging for an image library software that could handle any number of photos they threw at it, but even that doesn't have animated gif thumbnails.

I'd appreciate at least giving it some thought before people assume it's just a case of you not wanting to put the effort in.

I wish you well regardless. Thank you for your time.
