### ISSUE TITLE
Regression in WB module after Commit 62670ed 

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5125]
**Describe the bug**

In the past (at least the recent weeks) WB spot was like this:
- pick a spot, WB will be adjusted
- for what ever reason, one would like to check "camera" or others again, so click something else and get adjustments
- subsequently wanna go **back to spot**
-- the former frame is displayed and the value is set, as in the first spot picking = perfect

What has changed?
- pick up spot, works as normal
- click "camera" for instance and get the related WB values
- chose spot again
-- -> the former spot is framed = correct
-- -> the **WB setting** remains **unchanged** = **incorrect**
-- (reframing and it reacts again)

**To Reproduce**

see above

**Expected behavior**
as it was before: when going back to spot and the frame is shown, WB should be adjusted to that frame.

**Bisect**

I bescted this and got:
```
62670ed9ca4b24f6ad0f42adc49231a739e0b6e1 is the first bad commit
commit 62670ed9ca4b24f6ad0f42adc49231a739e0b6e1
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Thu May 14 11:43:08 2020 +0100

    reduce complexity of color_picker_proxy by not special casing blender pickers

 src/develop/blend_gui.c      |  24 ++--
 src/develop/imageop.c        |   2 -
 src/develop/imageop.h        |   8 +-
 src/gui/color_picker_proxy.c | 314 +++++++++++++------------------------------
 src/gui/color_picker_proxy.h |  68 +---------
 src/iop/basicadj.c           |   3 -
 src/iop/colorzones.c         |  41 +++---
 src/iop/rgbcurve.c           |  25 ++--
 src/iop/toneequal.c          |   2 +-
 9 files changed, 142 insertions(+), 345 deletions(-)
```
@dterrahe could you pls. have a look into it, even I cannot understand, how this could be responsible for it.

**Platform (please complete the following information):**
 - Darktable Version:  3.1.0+1700~g3c3ea3119
 - OS:  Gentoo

**Additional context**
 - Can you reproduce with another Darktable version? **see bisect**
 - Are the steps above reproduce with a fresh edit (removing history)? **yes**
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
-- gcc 9.0.3 (during bisecting, by chance 8.0.3 was set, but cross checked after switching back to 9.0.3)
-- CMAKE_BUILD_TYPE="Release" 
-- CFLAGS="-march=native -O2 -mtune=native -pipe"
 - Is the issue still present using an empty/new config-dir > **Yes**

**Comment by dterrahe** [comment]
I will look at this tomorrow and try to figure out what previously triggered the recalc on reselection of the spot option. Have you (or anyone else) noticed a similar change with other spot pickers?

**Comment by AxelG-DE** [comment]
> Have you (or anyone else) noticed a similar change with other spot pickers?

- not noticed.
- currently cannot imagine, where similar situation could occur (framing and set something w/o frame and back)
- something for IRC to discuss?

**Comment by dterrahe** [comment]
Too long for IRC, so I'll explain here :-)

Whenever a color picker selection changes and as a result some sliders get moved, the pipeline will get redrawn. As a result of this redrawing, the color picker code sends out another update. Since nothing else is changed, this probably doesn't lead to new slider changes, so usually this doesn't lead to an endless loop, but it can cause unnecessary calculations and slow response.

So previously, some modules would set a flag to ignore the next update coming in. I saw two issues with this:
- each module would have to do this themselves and most didn't (so most would indeed respond twice to the same update coming in)
- If no sliders were moved as a result of the colorpicker selection, it would still ignore the next update coming through, which could be from a completely different spot. So sometimes you would have to click twice for it to register.

So I changed this to actually check if the selection had changed and only respond if it had. But you now found a case where that approach works really badly! Thank you! I feel bad that I caused you to spend all that time on bisecting.

So now I'm surprised that this change wasn't noticeable, or at least not inconvenient, for other color pickers. Try for example in color balance the color picker for factor. Turn on the color picker -> the slider moves. Turn off color picker. Move slider manually. Turn on color picker again. Previously, the slider would move to the same spot it was before; after my change it doesn't anymore.

I'll fix this tomorrow. Shouldn't be difficult, but I want to keep it simple without getting hacky.

**Comment by AxelG-DE** [comment]
> I feel bad that I caused you to spend all that time on bisecting.

don't say like this. No need!

I am a user, I get this wonderful software from you guys, the devs. The least I can do, if I see something, is trying my best to file a reasonable bug report. With this we all make it better and better every day :-)

BTW I did like you proposed for colour balance and confirm, is the same.

Thank you for your fast reaction and commitment!
