### ISSUE TITLE
NEF's that were desecrated by Nikon Transfer fail to load

### ISSUE THREAD

**Issue by Thanatomanic** [darktable-org/darktable#5149]
The Nikon D3100 raw file provided [here](https://discuss.pixls.us/t/nefs-has-unknown-format/18318/13) loads fine in e.g. RawTherapee, but not in darktable, which gives the message `failed to read camera white balance information from '2013-02-16@17-15-0802.nef'` as reported [here](https://discuss.pixls.us/t/nefs-has-unknown-format/18318/30) for darktable 2.6.2 on Ubuntu 18.04 LTS. The file also does not load on my current development build with an up to date rawspeed.

**Comment by LebedevRI** [comment]
Thanks for the report.
The problem is:
https://github.com/darktable-org/rawspeed/blob/708f3cdc7bf1e1a7cbe52c479a625bda6d08455c/src/librawspeed/decoders/NefDecoder.cpp#L113
That looks for TIFF IFD that contains an entry with tag `0x8c` (`ContrastCurve`?)
Clearly, it is not present in **that** raw, so we fail.

**Comment by kmilos** [comment]
Just out of curiosity, why is this specific tag a hard requirement? There's maybe a more elegant way to fall back, like getting the IFD of the Nikon MakerNote via some other (more realiable tag) and then checking for 0x96 or 0x8c, and eventually fail?

**Comment by LebedevRI** [comment]
We pick TIFF IFD with `0x8c` because that is the tag we'd look for later:
https://github.com/darktable-org/rawspeed/blob/708f3cdc7bf1e1a7cbe52c479a625bda6d08455c/src/librawspeed/decoders/NefDecoder.cpp#L119
The other obvious alternative is [`0x96`](https://github.com/darktable-org/rawspeed/blob/708f3cdc7bf1e1a7cbe52c479a625bda6d08455c/src/librawspeed/decoders/NefDecoder.cpp#L117), and i tried that,
but apparently it isn't present in all of the NEF's, (i think D1x decoding broke),
so we'd need to look for one and if we fail then the other one (try-catch).
To support the explicitly-unsupported case of broken files. Seems wrong.

It also doesn't immediately make sense to me that it would be meaningful to look for other tags that we won't ever query later.

So i'm conflicted here. (That is why i didn't close the issue.)

**Comment by aurelienpierre** [comment]
I closed it only because there is a tag "won't fix".

**Comment by kmilos** [comment]
Yes, I saw that line, but I'm also not convinced the  initial logic of getting the IFD via this tag is a surefire way. I wouldn't call this file necessarily broken as it does have 0x96, and decided just fine in other SW.

In a catch 22 situation like this, all I'm saying is one should probably try to get the IFD via both (or a third robust alternative) before giving up, not give priority to 0x8c only.

**Comment by LebedevRI** [comment]
> I'm also not convinced the initial logic of getting the IFD via this tag is a surefire way.
> And I would rather say the older implementations using 0x8c for compression LUT are "broken", I fail to see the connection...


Can you point me at the fresh out-of-camera NEF raw that does not have `0x8c`?
Or has it in wrong IFD so the decoding fails?

> I wouldn't call this file necessarily broken as it does have 0x96, and decodes just fine in other SW.

Note that all bets are off here, precisely because that file *isn't* fresh out-of-camera NEF raw,
because it was crippled during transfer.

**Comment by kmilos** [comment]
One could say all bets are off regardless because we're dealing with a proprietary format to begin with.

What guarantees do you have 0x8c will be present in out-of-camera NEF raws for tomorrow's Nikon cameras / firmware?

To me it seems like an arbitrary choice, and just a workaround to support older cameras like D1x as you said. Indeed, it has worked out in general so far, and it certainly is your prerogative to declate it done and dusted.

It just feels there perhaps a better way to get to the Nikon MakerNote IFD, e.g. exiftool and exiv2 have no problem identifying these files. Unfortunately given my limited experience and skills, it'll take some time to figure out what heurtistics they use...

**Comment by LebedevRI** [comment]
That's actually true.
There are zero guarantees whatsoever because we are guessing everything
because we are reverse-engineering a black box, not operating off of a written spec.

**Comment by kmilos** [comment]
So instead of "give me the IFD that constains the magical 0x8c" is it not just as simple as "give me the IFD which is a MakerNote" since we know it'll be a Nikon MakerNote anyway (the file is already identifed as a Nikon raw)?
