### ISSUE TITLE
Thumbnail pre-rendering

### ISSUE THREAD

**Issue by nilsholle** [darktable-org/darktable#5171]
Currently, darktable only renders thumbnails of newly imported RAWs if needed (i.e. if the thumbnail is visible). This can be very annoying as one always has to wait for the thumbnails to be created before it is possible to have a quick look through the collection.
Do you think that it could be possible to change this behaviour? I think this might improve the user-experience a lot, especially for first-time users.

**Comment by parafin** [comment]
Run darktable-generate-cache.

**Comment by nilsholle** [comment]
I'm sorry, but I don't think this is an acceptable solution. Darktable does not just aim at photographers that know how to use a command line (in fact, most people don't and don't know how to and I think this is ok).
I don't see why the default behaviour should be as described above. I guess some kind of smart pre-generation of the thumbnail cache would be the best solution. It could be based on
- the number of images in the current collection that need a cache update
- the number of visible images (which directly relates to the scroll rate and thus the time that will pass until an update of the cache is needed)
- the amount of free resources (if there are enough CPU cores available, at least one thread could be used for this task such that the UI stays responsive)

**Comment by nilsholle** [comment]
@parafin Would you be so kind to re-open this issue? I don't consider it resolved. Thank you!

**Comment by parafin** [comment]
Not sure anyone will code it anytime soon, so I don't think having an open issue will help anyone. But whatever.

**Comment by wpferguson** [comment]
I'll take a look at this and see if we can do it with a lua script to at least get an idea of what's involved

**Comment by wpferguson** [comment]
Thank you bot, this one got lost in the shuffle :)

**Comment by wpferguson** [comment]
Decided to see if darktable-generate-cache would run while darktable was running.  It actually does, seemingly without problems.  So, I created a little script that catches the `post-film-import` event and then runs darktable-generate-cache on the the set of images just imported.  Running on an SSD, it generates the cache in a second or two for ~350 image import.  Going to do some more testing

**Comment by wpferguson** [comment]
Scratch the above thought (I deleted it so no one got false hope).  I tried spinning off darktable-generate-cache from a script. Once I got all the arguments right, it doesn't run because it can't get a lock on the database.  It looks like the `generate_thumbnail_cache` routine from darktable-generate-cache could be lifted and spun off as a job once an import is finished, though depending on your system and what settings you use, it could be painful.

I'll play a little more, as I just got another idea

**Comment by wpferguson** [comment]
So, I had an idea...

I added a generate_cache function to the lua image data type so that you can call <image>:generate_cache(min-map, max-map) and it will generate cache images for the specified scales and write them to the mipmap cache on disk, for the specified image.  Generating sizes 0-4 for 732 20MB cr2 files took 393 seconds on a reasonable system (i7-6850K w/nvidia 970M) with an SSD,

Now that I have it working, I'll try to see if I can find ways to speed it up without bringing darktable to it's knees.  My thought process in generating the cache as part of lua is that lua is single threaded, so darktable should still have the rest of the threads and remain responsive.  The tradeoff is speed generating the cache.

**Comment by wpferguson** [comment]
Played some and this is what I found.  On my system generating a size 8 cache image (100%) takes 1.5 secs/image.  However, if I have my darktable full screen, with lighttable in file manager mode with 5 images per line, these images are cache size 2.  If I use culling, these images are cache size 5.  I can make 2 runs, 1 generating cache size 2 and the other cache size 5 in 94 seconds for 732 20mb images.  This might be useful.

**Comment by wpferguson** [comment]
Another speed test.  I imported a 3089 image shoot.  The size 2 cache images got generated at 9 images/sec.  The size 5 cache images got generated at 6/sec.  Depending on your workflow (scroll through the lighttable first, or cull first) this should be fast enough to stay ahead of the users ability to evaluate images.

If you are processing off of a NAS, or even a hard drive, then disk I/O is going to slow things down.

**Comment by wpferguson** [comment]
Tried a 2770 image shoot from my NAS.  Processing slowed down from 9 and 6 images per second to 6 and 4 for an average of 5 images processed per second.  I scrolled through and culled with no lag, so darktable remains responsive.

**Comment by wpferguson** [comment]
Next test is Windows 7 running in a VM, so no opencl, emulated everything.  I imported a 491 image play raw directory and generated size 2 and size 5 cache images. Size 2 images seemed to generate at ~4/sec and size 5 and ~2/sec.  To generate the whole 982 cache images took 304 seconds, for an average of 3.2 images/sec.
