### ISSUE TITLE
Infinite loop when clicking on cancel button in copy/paste development dialog window

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5207]
**Describe the bug**

Can't cancel a copy or paste dialog window with cancel button. @johnny-bit: maybe not related but as you recently work on dialog windows.

**To Reproduce**
1. Select an image in lighttable
2. Open the copy... dialog window with Maj+ctrl+c shortcut (the issue appear only when launching dialog window with shortcut)
3. Click on cancel
4. See that dialog window "react" (try to close) but remains open

Same on paste dialog window. Close dialog button on header bar works.

**Expected behavior**
Click on cancel button close the dialog window.

Commit git1749 so a quite recent master release (last compile about 2 days ago).

**Comment by johnny-bit** [comment]
Just to be clear: I worked only on yes/no dialogs ;)

Since I was called I tried to replicate and it's complicated as it's weird. I can't replicate problematic behaviour when clicking copy/paste buttons in history stack module. dialogs normally pop up and can be closed when clicking on `cancel`.
The "problem" however becomes apparent when using keyboard shortcut - that opens copy/paste dialog, but upon clicking cancel it doesn't go away immediatelly, only on 2nd cancel.

My version tested is: 3.1.0+1793~gda7cecccf
I'll try to bisect the issue.

**Comment by elstoc** [comment]
Maybe related to the duplicate shortcuts mentioned in #5188.

**Comment by johnny-bit** [comment]
this is exactly related to #5188 - I'm bisecting and all things point to @AlicVB  lighttable rewrite :)

**Comment by Nilvus** [comment]
> Just to be clear: I worked only on yes/no dialogs ;)

Clear now ;-)

> Since I was called I tried to replicate and it's complicated as it's weird. I can't replicate problematic behaviour when clicking copy/paste buttons in history stack module. dialogs normally pop up and can be closed when clicking on `cancel`.

Oups, my mistake. Indeed this issue is only when using shortcut (that I use most of the time). First post corrected... It works when using buttons.

**Comment by Nilvus** [comment]
> Maybe related to the duplicate shortcuts mentioned in #5188.

I had this idea and forgot to mention it. Thanks.
