### ISSUE TITLE
Can't zoom to 100% when Tone Equalizer is on - Mac OS X

### ISSUE THREAD

**Issue by jrguerreiro** [darktable-org/darktable#5216]
When Tone Equalizer is on, I can't zoom to 100%, darktable just keeps trying to load the image. Sometimes it works, but only after an abnormally long time. I'm using Mac OS X, with darktable 3.1.0+1266˜g737735db9.

**Comment by johnny-bit** [comment]
Tone Equalizer is CPU-bound (no opencl acceleration for it) and it's quite early in the pipeline, so any changes to it require recomputation of whole pipe. Also in order to work properly Tone Equalizer fetches whole image in order to do masing etc.

Anyway - I checked your issue and I can zoom just fine, not only to 100% but actually waaay down to 1600% and while performance is degraded when using tone equalizer it still is in "acceptable" range.

**Comment by jrguerreiro** [comment]
Maybe that's something specific to how it's running on my Mac then (Intel
i5, 2.6ghz). Is there a way I could register the issue with more precision
(some option to document processing time?)? Here, even with few modules on,
it may take several minutes to zoom in 100%, if/when it works.

**Comment by johnny-bit** [comment]
run darktable from console with `-d perf` option.

**Comment by MStraeten** [comment]
try to disable denoise and retouch while editing, since they need several processing time.
My experience: after a basic exposure setting do the retouch stuff and disable the module afterwards. Same for denoise. Then do your tone- and colourcorrection. And enable denoise and retouch just before leaving darkroom. So you’re waiting only once ;)
Because you’re using a development build you also can make use of the new Preview downsampling #4931 since the image is processed three times: full - for your edit area, preview for the upper left area and a thumbnail for the filmstrip. While thumbnail calculations are made in the background the preview is needed for masks, color picker etc. and so you also have to wait for it ...

**Comment by MStraeten** [comment]
further idea: i checked some of the images causing a few minutes to process full and preview and found them having duplicate masks. One xmp was about 1 MB filesize ;) 
to explore (you need a sqllite client to explore .config/darktable/library.db): 
```
select film_rolls.folder, images.filename, images.id from film_rolls, images where images.id in
( select distinct(imgid) from masks_history where rowid not in (select min(rowid)from masks_history group by imgid,formid,num))
and film_rolls.id = images.film_id
```
these images are having more than one duplicated mask (duplicated definition not usage) - and this also seems to slow down the processing.
You can remove duplicate mask definition with (it reduced the processing time from 400 sec to 24 secs for a image with a couple of masks to deal with):
```
delete from masks_history where rowid not in (select min(rowid)from masks_history group by imgid,formid,num)
```
but backup your library first ...
Maybe copying edits via ctrl+c ctrl+v from different development stages is a bit ridiculous if masks are affected - and there were some commits dealing with masks ...
