### ISSUE TITLE
automatic cropping in perspective correction not ok when preview downsampling is enabled

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#5226]
If preview downsampling (#4702) is enabled, the cropping frame for automatic cropping is also scaled - so a manual tweaking is not possible

**To Reproduce**
process a mage that really needs perspective correction (for minimal perspective distortion it's not that noticeable)
1. set downsampling to '1/4'
2. apply automatic perspective correction (eg.vertical correction)
3. activate automatic cropping "original format" or "largest area"
--> 
![perspective-correction](https://user-images.githubusercontent.com/39386816/83257975-bcfbea00-a1b5-11ea-8070-d0d5c0dd47b3.jpg)

**Platform (please complete the following information):**
- Darktable Version: darktable 3.1.0+1806~g70e3a7a78 (plain current master)
- OS: OSX
- OpenCL no dependency

**Comment by GrahamByrnes** [comment]
I'm a couple of versions behind atm, I'll need to do some cloning.

However, with +1796 it works for me, provided I follow the slightly strange logic of crop & rotate:
-do automatic correction
-do automatic cropping (and so I then saw the frame shrunken onto the maximum-area crop, with the cropped off mess still visible;
-click on the module name (not the button) to remove focus.

The third step expands the crop-frame to full-frame. This doesn't work for you?

**Comment by MStraeten** [comment]
the cropping itself is done indeed, but i'm not able to adjust the cropping because the frame doesnt cover the area to be cropped

**Comment by GrahamByrnes** [comment]
It works for me, but there is a reason I created 4 options: try a less severe reduction, or turn it off.

**Comment by MStraeten** [comment]
it should work for any user and platform ... if not then this behaviour needs to be documented as a feature ;)

**Comment by TurboGit** [comment]
@GrahamByrnes : I can reproduce. The identified edges are ok but the cropped area and grids are completely off.

**Comment by GrahamByrnes** [comment]
I'll have a look, but I suspect this is more an issue of how the "automatic" part works... I did write at one stage that reducing the resolution may not be ideal when edges were being traced.
So it may take some time, since I have no idea how auto-perspective works.

For testing, I fed in a completely normal photo and the proposed "correction" was extreme... the algorithm was picking up the lines in a woman's hair, and trying the straigthen it. It did this differently at 1/1 and 1/4, but both were absurd. In @MStraeten 's case, it seems the guess about which part of the image is the more interesting is wrong...

In fact it does seem to capture the same edges in both cases, but there is a bit of a "ping pong ball on the top of the Andes" effect.... it attempts to straighten in either one way or another, both wrong.  (Don't have the model's authorisation, sorry...)

**Comment by GrahamByrnes** [comment]
Well, it's documented:

// We use a pseudo-RANSAC algorithm to elminiate ouliers from our set of lines. The
// original RANSAC works on linear optimization problems. Our model is nonlinear. We
// take advantage of the fact that lines interesting for our model are vantage lines
// that meet in one vantage point for each subset of lines (vertical/horizontal).
// Strategy: we construct a model by (random) sampling within the subset of lines and
// calculate the vantage point. Then we check the "distance" of all other lines to the
// vantage point. The model that gives highest number of lines combined with the highest
// total weight and lowest overall "distance" wins.
// Disadvantage: compared to the original RANSAC we don't get any model parameters that
// we could use for the following NMS fit.
// Self-tuning: we optimize "epsilon", the hurdle rate to reject a line as an outlier,
// by a number of dry runs first. The target average percentage value of lines to eliminate as
// outliers (without judging on the quality of the model) is given by RANSAC_ELIMINATION_RATIO,
// note: the actual percentage of outliers removed in the final run will be lower because we
// will finally look for the best quality model with the optimized epsilon and that quality value also
// encloses the number of good lines

Holy Flying Spaghetti Monster...

**Comment by GrahamByrnes** [comment]
And:

"A disadvantage of RANSAC is that there is **no upper bound on the time it takes** to compute these parameters (except exhaustion). When the number of iterations computed is limited the **solution obtained may not be optimal**, and it **may not even be one that fits the data in a good way**. In this way RANSAC offers a trade-off; by computing a greater number of iterations the probability of a reasonable model being produced is increased. Moreover, RANSAC is not always able to find the optimal set even for moderately contaminated sets and it usually performs badly when the number of inliers is less than 50%. Optimal RANSAC [3] was proposed to handle both these problems and is capable of finding the optimal set for heavily contaminated sets, even for an inlier ratio under 5%. **Another disadvantage of RANSAC is that it requires the setting of problem-specific thresholds.**

**Comment by GrahamByrnes** [comment]
I'm starting to get my head around this. It looks like what is happening is that at some stage, only the upper-left 1/4 x 1/4 (or etc) of the image is passed to the optimisation algorithm.
The cropping is then done considering only that part, and if you look in the cropped piece, you can see there are only two lines: the cropping locks on one or the other depending on what transformations are allowed.

The mysterious part is that the line-detection algorithm is apparently working on the full image. That the whole image is distorted is not a clue, since the optimisation parameters are hed to the homograph, which combines them and applies them to the whole image, blind to the content of the image.

**Comment by MStraeten** [comment]
pr #5249 fixes it, so i will close here after it is merged ...

**Comment by MStraeten** [comment]
fix confirmed, thanks for the solution
