### ISSUE TITLE
Color Balance module: soft range for offset sliders

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#5227]
In color balance all factor and saturation sliders have the same soft range (0 to 25% for saturation and -50% to 50% for factor).
However the offset part (shadows adjustment) is way too sensitive.
In most practical cases an adjustment of +/- 1% of factor has already a dramatic affect on the image.
You are forced to fiddle with fine right click adjustment all the time, which slows down the workflow.
Shadows naturally require low touch (that's why log scale is often used in audio / video manipulation.
Fact is that soft range can be increased on the gui, but it cannot be decreased.

My proposal is to set by default a narrower soft range for offset sliders. It doesn't make sense to have a range which is almost never used for 99% of its span.

By the way I could make a PR just to test the idea

**Comment by aurelienpierre** [comment]
The problem is the behaviour changes if you are in slope/offset/power or lift/gamma/gain mode. The second behaves well, only the first one is super sensitive. I agree that current state is not ok for slope/offset/power, but managing the UI consistency between both modet is a problem for each I haven't found an elegant solution.

**Comment by Mark-64** [comment]
this is solved in #5533
