### ISSUE TITLE
[Basecureve] Bug : new preset created cannot be deleted.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#5275]
darktable-3.1.0+1862~g0d825a4ce-win64.exe

Enabled basecurve and applied the "panasonic like preset"
Use the same one to create a preset XYZ and checked the boxes to auto apply and show preset for matching images.

Now I applied the XYZ preset to another image for some reason it did not auto apply.

Now I am trying to delete the preset XYZ.
When I look at the presets I see both "panasonic like" and "XYZ" bold.
![image](https://user-images.githubusercontent.com/1119439/83414007-6226f480-a43a-11ea-88ed-a8f519adbead.png)

When I try to delete the preset (note 2 of them were active) I get the dialog to delete panasonic one but I want to delete xyz.
![image](https://user-images.githubusercontent.com/1119439/83414133-98647400-a43a-11ea-9213-00190ea16c99.png)

I select yest for deleting but it doesn't delete the panasonic one either. I am stuck with the 2 enabled presets.

**Comment by johnny-bit** [comment]
Workaround:

Go to settings -> presets
open up base curve presets.
at the bottom there should be your "xyz" preset. select it and press [delete] key

**Comment by chhil** [comment]
@johnny-bit , thank you. It removed the preset and the new import no longer enables the base curve.

That applying to similar images in the base curve is tricky and is overriding the preferences, maybe someone can look at that and indicate the precedence order for base curve applying when its configured to apply in one place and not to apply in another.

**Comment by chhil** [comment]
I have kept this open as the delete functionality of the newly created preset from the preset itself still doesn't work.

**Comment by johnny-bit** [comment]
Not realy a constraint, but a way of how this works. The "active" preset is based on preset op params, since the preset is cloned from an internal preset it has exact same params as internal one. Problem is: system when looking for active presets prioritizes internal presets. Additionally delete prohibits deletion of internal presets, so there's a deadlock created and only way to remove preset is with presets settings.

Possible way to handle this would be to absolutely constrain creating copy of preset in presets menu (so you wouldn't be able to create unremovable preset in the first place).

**Comment by chhil** [comment]
Thanks for the explanation.
Do I leave this open or close it?

**Comment by johnny-bit** [comment]
keep it open please.
