### ISSUE TITLE
Auto applied WB preset is not used for thumbnail

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#5295]
**Describe the bug**
I use WB preset with "Auto apply" checkbox "on".  It successfully applied to the image, but ignored in thumbnails of DR and LT.

**To Reproduce**
1. Create WB preset with "Auto apply" checkbox "on".
2. Open test image in DR. WB automatically apply to it.
3. Switch back on LT.
4. See thumbnail of test image w/o WB applied.
5. Open another image in DR. See thumbnail of test image w/o WB applied.

**Platform:**
Darktable Version: master
OS: Debian 10

**Additional context**
To bypass issue it is necessary to manually turn off/on WB module.

**Comment by TurboGit** [comment]
@phweyland : could this be a hash computing issue ?

**Comment by phweyland** [comment]
If the config "doesn't use embedded thumbnail" is off, this is a possible failing scenario.
in that case the auto apply is effective only in darkroom (as described) and the altered flag is not set because that's the first run. So when you leave darkroom the embedded thumbnail is kept.
this was not visible before hash computing, because of another bug, when image was always recalculated (and xmp written) leaving darkroom even without change.
I cannot look at this by the next 2 or 3 days, but then I'll try to find a solution.
