### ISSUE TITLE
Darktable opens "wrong" instance of module

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#5308]
This might be a bug or might be intended behaviour?
Suppose you have two instances of a module e.g. exposure and exposure1, and the latter is open/expanded.  Now go to lighttable and double-click back to darktable.  Exposure1 is now closed and exposure is open instead.

Master build  3.1.0+1837~gee49c4778-dirty  from 30 May 2020
Ubuntu 18.04

**Comment by elstoc** [comment]
darktable just stores the active/expanded modules (take a look at the darktablerc file and you can see what configurations it saves when you exit). It doesn't record what image a module was active in or what instance of the module was active. 

I wouldn't go as far as to say it was by design (the code probably predates multi-instances) but it's difficult to see how we could consistently make it work like you suggest.  

We could store the full instance name possibly but then what if you open another image that doesn't have 'exposure 1'?

**Comment by RawConvert** [comment]
It sounds like it's not a bug, more an area of fuzziness.  Obviously it's not a big problem.
Perhaps there's a project someone might want to take on to define the ideal behaviour re. "workspace" i.e. what modules are visible and whether expanded or closed up; and what should happen when you import new raws; and re-open existing ones.  But that might be making a mountain out of a molehill.
