### ISSUE TITLE
Pixel size on output can be disturbed by mouse wheel

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#5366]
I noticed my max size on outputting in lighttable (the max pixel dimensions) had got altered.  The mouse wheel lets me move up and down the lighttable sections, as expected, and it doesn't allow values to be changed, as expected, EXCEPT for these two pixel values. So it's quite easy to accidentally change them as you flick around the right hand side of the screen.  I suppose someone will say you can use the scroll bar, but that's rather fiddly compared to just mouse wheeling  anywhere on the right.

dt master 3.1.0+2017~ga6c18e1b7-dirty    built today.

**Comment by RawConvert** [comment]
everybody dance, do-do-dodo, clap your hands, clap your hands

**Comment by elstoc** [comment]
If you're trying to get a response you succeeded. I recommend you just use the scroll bar ;-)

Really though the best thing to do is to change the preference so that it doesn't scroll the panels by default and just scroll by hovering over the scroll bar and scrolling your mouse - you don't have to grab and drag it. Using scroll to change values is much more useful anyway because then you can use the CTRL and SHIFT modifiers.

**Comment by RawConvert** [comment]
I'm not really looking for a workaround, and hovering over the scroll bar is fiddly compared with being anywhere in the righthand panel.
I think it's clearly a bug or anomaly that the pixel dimensions are the only items that are exposed, and so this issue should be logged as a candidate for a future fix.

**Comment by RawConvert** [comment]
Just tested in dt 3.2.1 release.  This remains a bug.

**Comment by elstoc** [comment]
One option would be to change those fields to being straight GtkEntry boxes rather than spin buttons. I'm not sure whether the buttons and scroll functionality are really needed for those settings. Also the +/- buttons take up a lot of screen width and mean that the right hand panel can't be shrunk very small without affecting the rest of the gui.

**Comment by RawConvert** [comment]
I think you are saying make them so the only way to change value is by typing in the boxes.  That seems fine to me, it's only once per output, and it's not as if continuous change is needed whilst you look at the image.

**Comment by elstoc** [comment]
Indeed. Does anyone really use scroll or the buttons to adjust these?

**Comment by TurboGit** [comment]
I have never used the button nor scroll. I always enter values.

**Comment by elstoc** [comment]
Only downside is we'd probably have to add some validation to a standard GtkEntry box (that's automatically incorporated into spin buttons)

**Comment by elstoc** [comment]
I'll look into this and submit a PR.

**Comment by RawConvert** [comment]
#5833 is similar but different!

**Comment by RawConvert** [comment]
I see this is now fixed in master 3.3.0 23Aug20. ** Thank You **
