### ISSUE TITLE
Add a warning banner to old versions of the manual

### ISSUE THREAD

**Issue by mikaelmoutakis** [darktable-org/darktable#5374]
**Is your feature request related to a problem? Please describe.**

If I duck-duck-go or google "darktable manual", a top hit is the 2.4 version. This can confuse the unobservant user. 

**Describe the solution you'd like**

Add a big, fat red banner warning people that the 2.4 manual is stale, and point them to the newer version. Python does that very nicely: https://docs.python.org/2/howto/argparse.html

**Alternatives**

Automatic redirection?

**Comment by rgo** [comment]
Personally, I'd prefer an automatic redirection.

Why? Because if google/duck duck go/bing/whatever sends you to an old manual, it could be that you don't realise about the info/warning banner that says it's an older version of the manual. Furthermore, it forces you to make another jump to the current manual.

In fact, I'd send a 301 redirect to inform the crawlers where is hosted the new documentation.

Darktable 3.0 can have a section linking old manuals, and them could be stored in a subdirectory of the current manual. But of all them hosted in the same place.

**Comment by mikaelmoutakis** [comment]
I don't have any strong opinions here. Either case works.  But there might be people using the old versions of Darktable.

**Comment by TurboGit** [comment]
Fact is that previous maintainer of the documentation has lost the password for the server where the doc is stored. So I have moved the documentation into a more open location (GitLab IO). At this stage there is nothing we can do for the old doc.
