### ISSUE TITLE
Lua scripts installer remains (partially) open on darktable start. should not be

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5401]
**Describe the bug**
Just open darktable and see that new lua scripts installer is partially open. module header bar is on hide/close state but not the content that is shown. Clicking on header bar hide the content. After that, close darktable and open it and see that this module remains partially open (header bar on close state but content shown).

![2020-06-11_08-33](https://user-images.githubusercontent.com/45535283/84354070-8b751c80-abc0-11ea-9d45-d39c3c97eb7f.jpg)

**Expected behavior**

Just have the content hide on darktable start and when the collapse button is in hide/close state (as all other modules) and be sure darktable start again with last state not this default not wanted one.

@wpferguson: this one probably for you.

**Comment by wpferguson** [comment]
This was actually by design.  My thought process was this:

If you already had the scripts installed, you would never see this.

If you didn't want to install the scripts and didn't want to see this, you would select dont show again and never see it again.

If you weren't sure, then you could select remind me later and this would reappear every 5th time you started darktable.

If you wanted to install the scripts, then install them and this wouldn't show up again.

I didn't anticipate the do nothing at this time response.  I'll change it to be open the first time it runs, then respect what the user decides after that.

I'll also write something for the mailing lists and pixls.us explaining what this is and how I envisioned it being used.

**Comment by Nilvus** [comment]
@wpferguson: I never use lua and so don't install any scripts. If I understand you, I should not see it. Or do I show this because of some library installed when compile darktable?

I understand the idea of you purpose (I didn't follow that PR as I don't use lua) but I see 2 issues:

- the collapse arrow should be on open stale it the content is shown. On start, the arrow is on close stale so not consistent. This should be fixed for good UI.
- before your answer, I never thought of opening the menu so I don't see that the menu allow to hide this. So not intuitive for user. It would be good to have a better way to know what the menu allow to do. Maybe, something like a message shown directly (one time only) to inform the user that he could hide that for 5th time or for ever.

**Comment by Nilvus** [comment]
Last thing I just see:
When selecting action (here don't show again) and then execute, the content disappear but the collapse arrow remains on open stale. Should be in closed one. For consistent UI also regardless of other modules behavior.

**Comment by Nilvus** [comment]
Oh, another thing (should be the real last one): is this "module" could be translated? Actually it's in english and added the path file on POTFILES.in doesn't seems to update po files with intltool-update after. Or I miss something?

**Comment by wpferguson** [comment]
The collaspe arrow not reflecting the change in state is a bug.  I'm tracing it...

I can make it translatable.  It requires a small lua api change to make it work.

I can do a one time message.
