### ISSUE TITLE
Impossible to unselect images in filmstrip

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5495]
**Describe the bug**
It's impossible to cancel selected images in filmstrip (same in all views with filmstrip) to select for example another set. Selection could only begin from image(s) already selected in lighttable. Un-select them is possible only in lighttable, not in filmstrip.

@AlicVB: another one for you I suppose (no, I'm not laughing :joy:)

**To reproduce**
Start on lighttable and select one or more images and go on map view and select other images you want on filmstrip. All that possible. Try to unselect them to select another set, it's not possible. Go to lighttable and see that all previously selected images are still there. Unselect them and go back to map view. You could now select a new set.

**Expected behavior**
Be possible, as before, to select/unselect set of images we want directly in filmstrip.

**Platform (please complete the following information):**
 - Darktable Version: last master

**Comment by AlicVB** [comment]
yes, that's "by design" : to avoid user to "loose" their selection by switching to another image for example. In filmstrip, selection change is only possible with modifier keys = only possible if user really want it.

You can use Alt-click to have the same behavior on selection as normal click in filemanager.

**Comment by Nilvus** [comment]
Ok, not really intuitive but I understand the goal. Thanks for your reply.
