### ISSUE TITLE
doc/README.md: Invalid description of libsoup dependency

### ISSUE THREAD

**Issue by mkszuba** [darktable-org/darktable#5541]
**Describe the bug**

_doc/README.md_ says Darktable needs libsoup in order to provide geotagging support. However, comments in _src/CMakeFiles.txt_ suggest libsoup is only required by the Facebook exporter - and geotagging seems to work just fine without it.

**To Reproduce**

1. Compare the contents of _doc/README.md_ with those of _src/CMakeFiles.txt_, and/or
2. Build Darktable with osm-gps-map but without libsoup and try using geotagging.

**Comment by johnny-bit** [comment]
osm-gps-map depends on libsoup internally https://github.com/nzjrs/osm-gps-map/blob/9df1353a3970cd21a73527967e9f3d75f9bf7537/configure.ac#L24 it's impossible (i think) to build/use osm-gps-map without it, since it uses libsoup to download map tiles.

another use is that mentioned facebook, however facebook export is removed in favour of lua scripts... i need to browse code because this became interesting!

**Comment by mkszuba** [comment]
> osm-gps-map depends on libsoup internally

True - but if you e.g. link it to osm-gps-map statically then geotagging in darktable will work fine without an extra copy of libsoup installed :-) Anyway, thank you for having cleared that up!
