### ISSUE TITLE
always on button size, again

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#5543]
I thought that after #5445 and cc0bc1d the alignment of icons/labels in module headers was solved, but apparently it's not

![icons](https://user-images.githubusercontent.com/43290988/85027533-521d4d80-b17a-11ea-93d8-bc90660ffd1f.JPG)

![no_icons](https://user-images.githubusercontent.com/43290988/85027541-547fa780-b17a-11ea-8533-33cc025f3ffa.JPG)
 
current master, Windows 10

**Comment by Nilvus** [comment]
They are aligned. I just made the test: going in Gimp with your image (and same for what I see on my side) and just make a square selection and you will see that they are aligned. The main difference is icon module is more "brilliant" and have not totally same circle (sort of more plain) and they are SVG as always on is cairo painted.

So that's just an optical illusion, physically they are aligned. So, I would see nothing to do or to reduce this optical illusion, maybe just increase to 2 pixels the diameter of the always on icon (so 1 pixel more on top and 1 more on bottom). No more.

**Comment by TurboGit** [comment]
> So that's just an optical illusion, physically they are aligned.

Optical illusion ? I see them aligned on my side... Maybe my brain is damaged and don't see the illusion :)

**Comment by TurboGit** [comment]
> Or more seriously, we don't all have same eyes (and brain).

Ah ok, so I have a perfect brain with an auto alignment algorithm included :)

**Comment by Mark-64** [comment]
?
![immagine](https://user-images.githubusercontent.com/43290988/85053103-548f9f80-b19a-11ea-97d8-26d69685ee9d.png)

**Comment by TurboGit** [comment]
Ah indeed! I was concentrated on the horizontal alignment and so I did not even notice this vertical shift :)

**Comment by Nilvus** [comment]
> Ah indeed! I was concentrated on the horizontal alignment and so I did not even notice this vertical shift :)

Me too. So it's not icon size as your title says but vertical shift.

**Comment by Nilvus** [comment]
Seems that CSS padding and margins are not the same for always-on icon. Will check more this evening if this could be solved by CSS. So let me that @Mark-64. If something else, I will say you there.

**Comment by Nilvus** [comment]
Was finally an easy one to fix. See #5548 PR.
