### ISSUE TITLE
channel mixer causes highlights to clip

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5578]
Using the default scene-referred workflow I adjust exposure to get the middle-grey values looking reasonable while keeping the highlights well exposed (note the histogram), with filmic auto-enabled.

![Screenshot_2020-06-20_09-43-34](https://user-images.githubusercontent.com/9555491/85197687-8a3ba200-b2da-11ea-962d-fd21ae116762.png)

I switch on the channel mixer module _without changing any parameters_ and it appears that my 'white' is no longer at the far right of the histogram and is bunched up into a 'light grey' peak. I assume by the peak on the right of the histogram, that I have lost some detail here.

![Screenshot_2020-06-20_09-47-23](https://user-images.githubusercontent.com/9555491/85197758-11891580-b2db-11ea-9120-27cff2cf6ad3.png)

I can persuade it back to white again using the 'white relative exposure' slider in filmic but I've definitely lost some highlight detail:

![Screenshot_2020-06-20_09-48-40](https://user-images.githubusercontent.com/9555491/85197779-3da49680-b2db-11ea-9933-999c71f47daa.png)

This (loss of highlight detail) is something I've noticed mosly when using channel mixer to make my image monochrome but the above is the minimal way to reproduce the issue and it seems to me that without any parameter changes, the channel mixer module really should just pass the RGB signal unadjusted. It appears that the module is instead clipping the values and then passing those clipped values to the filmic module. 

I know there are alternative ways to get a monochrome image but channel mixer really is the most powerful.

I can work around this by switching off filmic and making sure that the histogram is not clipped before engaging the filmic and channel mixer modules but I find it much harder to recover shadow detail when working like this.

**Comment by elstoc** [comment]
Perhaps this is a use case for retaining the 'middle grey luminance' slider in filmic as the standard advised workflow (of using exposure to set middle grey) doesn't work when channel mixer is enabled.

**Comment by johnny-bit** [comment]
Unfortunatelly current channelmixer clips. There were some PRs started to unclip the image, but that would break some edits. Further changes were done etc but as far as I see, nothing got merged for "obsolete channelmixer". it seems that only non-clipping channelmixer is Aurelien's Channel Mixer Reboot.

**Comment by elstoc** [comment]
:-(

**Comment by GrahamByrnes** [comment]
I think that decision was a mistake. When you look at the code, it was an obvious bug: there were commands
`CLIP(red_stuff)+green_stuff+blue_stuff;`
but with lots of extra parantheses... the CLIP should have included all colours... or it should be omitted, since applying a CLIP inside channelmixer is just another form of clipping, so you'd be better off dealing with it upstream or downstream.

Ironically, I just came in here to ask a question about hsl2rgb... lol

**Comment by johnny-bit** [comment]
Color science... HSL is evil ;) HSV is "a bit better".

How much unfunking we want in channel mixer is dependent on whether somebody would like to hack away at it while keeping in mind that reboot channelmixer is *better* :)

**Comment by GrahamByrnes** [comment]
Funny you should mention that :-)

To my mind, the biggest issue of channelmixer is that it confounds slider settings output: ie to escape grey mode, you have to reset the CHANNEL_GRAY sliders to zero. You can't just hop between your favourite rgb version and your favourite mono version to see where the love is.

It's actually fairly easy to fix with just a couple of internal variables to track the output_channel.
Some of them were already there but commented out, possibly because they were placed at complicated positions relative to presets.

Also `process` is a bit of a shambles, but anyway...

So I'm in the final stages of fixing all that, but then there is the political decision of what to do with it. My concern is that channelmixer reboot is going to do a bunch of highlight reconstruction that isn't necessary for a correctly exposed photo: the reson I have, for now, abandoned filmicIV.

**Comment by elstoc** [comment]
So I have two possible workarounds so far. The first is to place a new instance of the exposure module after channel mixer (using the first to stop channelmixer clipping and the second to adjust for the middle grey) and the other is to re-introduce the 'custom middle grey values' slider into filmic. 

What might be nice as a compromise would be if the last set value of the 'use custom middle grey values' tick box was stored as a configuration setting and used as a default for the next image. Then those people who like to keep it switched on could do so permanently.

**Comment by GrahamByrnes** [comment]
1. Expand using exposure so you clip only what must be clipped (extreme highlights);
2.  Mix happily without pushing the sum of contributions to any channel above 1:
3.  Use something (base curve, filmicrgb) to move the content around.

Putting a second instance of exposure.c after channelmixer doesn't do anything, since it's a linear scaler: x -> lambda x, so it commutes with channelmixer, so long as you don't clip.

I don't see a problem, except that channelmixer encourages you to mix high: my evil scheme is to set the sliders to [-0.5,1.0] with, in some cases, a constraint function so they can't exceed 1. 

You can get an idea of what was originally thought of by looking at the presents (they all add to 1) and the comments suggesting the sliders be limited to [-1,1] (I'd have been happy with [0,1]).
Then it would be necessary to include a "go wide" option if you really want the range [-2,2]

**Comment by elstoc** [comment]
> Putting a second instance of exposure.c after channelmixer doesn't do anything

The second exposure instance is basically (as I understand it) equivalent to setting the custom middle grey in filmic. Once you're past the channel mixer module in the pixelpipe you're no longer limited by its clipping and you can use the second exposure module to push the overall exposure in the knowledge that the filmic module will bring the highlights back again. This isn't possible with the first exposure instance because channel mixer will clip its output. Or am I missing something?

**Comment by TurboGit** [comment]
@GrahamByrnes : Fact is that if we do change this it will really break edits and could cause some big differences. Now we could have a new version and only use the unclipping version in new edits and use the clipping one for old edits. Of course a reset of the module will switch to new version and would allow to use the unclipping version in previous edits.

That being said, is that really a good way to use our time ? The new channel mixer will have unclipping version right at the start and we may well hide the previous module (as done for previous filmic) and so we will be back to the exact same situation I described above.

**Comment by GrahamByrnes** [comment]
@TurboGit Interesting questions :-)

I'm still a beginner around here, so doing things off line is part of my way of learning. It's just a coincidence that I fell into this conversation as I was in the middle of editing channelmix... because I wanted to see if I could make it work better in the space of a few days.

For the clipping, I think we can agree to disagree, and you're the boss here. Although, "that being said", it would be a peculiar edit that depends on this. It would mean someone pushed red so that it alone clipped... so that the edit actually stopped doing anything. Hence my proposal would be to drop the CLIP commands entirely.

For the other colour (or BW) modules, the same is true à fortiori: the only edits affected would be those that pushed against clipping.

Or that is so far as I understand, which in the case of HSL is not very much. Now that @ralfbrown reminds me, I can remember from Lightroom that there was one slider for saturation and one for hue. I shall go look. For the waste of time... well, I'm not really a button-tamer (dresseur de boutons ?), but if I can be useful in the next month or so, I shall do my bit.

**Comment by GrahamByrnes** [comment]
> Or am I missing something?

No, as it's currently written. I wasn't thinking through the filmicIII -> filmicIV change

**Comment by GrahamByrnes** [comment]
I think I get it now. learning, as I said :-)

HSL has to clip... it's the bicubic representation, where does it go if L>100% ?

But I never use HSL.... and for grey-mode (which I use almost always) there is no need for clipping. Same for the RGB matrix multiplier.

The issue really is that channelmixer brings together something that needs to be in the non-linear flow (HSL) with things that belong in the linear flow (Grey, RGB). And so @elstoc's solution is what it has to be. In the utopian world, it would exist in two versions: `linear-channelmixer` and `nonlinear-channelmixer`, for use before & after basecurve/tonecurve/filmicrgb. The first can be made faster by getting rid of the conditionals in `process` (which I've done for fun, although I doubt it makes much difference).

**Comment by elstoc** [comment]
> for grey-mode (which I use almost always) there is no need for clipping

Grey mode is really where I have the issue too (I'm not sure I've ever used anything other than grey mode except to swap channels for infrared). I only used 'non-grey' mode in the issue because I was trying to find the minimal steps to reproduce the issue.

**Comment by RawConvert** [comment]
@GrahamByrnes , re. your comment doing "highlight reconstruction that isn't necessary for a correctly exposed photo".
I'm interested, could you maybe expand on this please?  Is there something you don't like about the filmic4 highlight rec?  I was just checking and you can increase the threshold to take areas out of scope for rec. if I understand correctly, looking at the mask.

**Comment by GrahamByrnes** [comment]
If your photo doesn't have blown highlights, there's nothing to reconstruct.

That's an oversimplification, of course: quite often there are small specular highlights... and in colour, they may well take a cast because of limiting occuring in a single channel. However, not always... and for someone who works mostly in B&W, they matter much less. Sometimes it just doesn't matter: if you have a lot of blown-out highlight, you are in the realm of creating a psychological reconstruction: see photo below that I took yesterday. None of that yellow is really there, it's result of the blue blowing out and leaving the red & green channels. See the second photo, which was exposed for the wall.

![_IMG5307](https://user-images.githubusercontent.com/58031430/86542466-48377080-bf16-11ea-9029-3cdb346836c1.jpg)
![_IMG5330](https://user-images.githubusercontent.com/58031430/86542576-065afa00-bf17-11ea-9ea7-862d070f367d.jpg)

@aurelienpierre and I had this discussion with filmic V3... I eventually started using it because its parametric nature made it easier to edit a batch of photos. That overlaps the function of basecurve.c, so fair competition. 

Otoh, for v4 I remain unconvinced, *for my photography*. As you say, you can push all the reconstruction sliders fully left or fully right.... and I found I was doing that with *every* photo. When I didn't, the results looked slightly soft, a little like autochromes (note, I didn't print them out, this may have been an issue with my screen). For me, it pushes the boat out a little far and spends a lot of resources trying to correct things that aren't an issue for me. I've gone back to basecurve + tonecurve, because they offer immediate feedback when I push a bit here or pull a bit there. They are good enough for me, and the price of something that might be better for some people is not something I want to pay.

For a professional wedding photographer, or any number of other special interests, what I'm saying might be complete nonsense... which is fine.

**Comment by elstoc** [comment]
https://github.com/darktable-org/darktable/commit/f5d07393094d5cd2567c73fb0b949a03537648c2

**Comment by TurboGit** [comment]
Thanks, no much explanation from this commit. Ok, boken... But we know that now :)

**Comment by johnny-bit** [comment]
If I'm not mistaken there are currently 3 competing PRs fixing channel mixer :)

**Comment by matt-maguire** [comment]
GraharmByrnes wrote:
> 3. The linearity in monochrome mixing and colour matrix multiplication is spoiled only by a choice to clamp values to [0,1] on some scale. I'd suggest that for most people using this facility, removing the bounding would cause no legacy issue.
I disagree here, if you remove the clamping, this can cause out-of-range values to be passed to modules further along the pixel pipe that are not designed to handle them. I think we should set the default to no clamping (maybe the default option in a drop-down box?), but if the module is used in a legacy xmp pixel pipe, then the clamping should probably remain in place.

> 4. For HSL, there is the necessary clamping, but also a bug which applies this differently for R. I'd consider this a bug, but others (eg @TurboGit) are concerned about changing it corrupting previous edits. That's certainly a reasonable point of view.

Really, this should be a separate module. It could be left in place for existing edits, but for new edits this should probably be covered by a separate module. Any thoughts on that? We should probably look at what those other PRs are proposing :-)

**Comment by GrahamByrnes** [comment]
Yes.

Le lun. 24 août 2020 01:47, Matt Maguire <notifications@github.com> a
écrit :

**Comment by johnny-bit** [comment]
Now that #4687 is merged I wonder how much of an issue for new edits will this problem bee.

**Comment by elstoc** [comment]
I think this probably was resolved in #4687 but either way is now superseded by color calibration which doesn't exhibit this issue. So closing.
