### ISSUE TITLE
filmic vs base curve preferences → both modules enabled/disabled

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#5596]
Linux, 64 bit, latest master snapshot

1. Make sure that display-referred is enabled in dt preferences → processing
2. Discard history of sample image
3. Open that image, make sure that base curve module is enabled
4. Leave to lighttable mode and change preferences to scene-referred
5. Open same image for editing
6. Click "original" in history tab and press "compress history stack"
7. See both "base curve" and "filmic rgb" enabled in new history.
8. In opposite situation (changing scene referred to display referred) no modules are enabled after clicking "original" and "compress history stack".

Expected behavior: enable modules according selected preferences.

**Comment by elstoc** [comment]
Did you restart after changing the preference (as advised in the tooltip)?

**Comment by timur-davletshin** [comment]
If restart is really required, old logic should be applied before that. But we have "all enabled" or "all disabled".

**Comment by aurelienpierre** [comment]
> If restart is really required, old logic should be applied before that. But we have "all enabled" or "all disabled".

If C was really a programming language, we would discover these kind of errors at compilation time. But here we are…

Question is: what happens if you follow the guidelines ? I don't care how the soft should fail if user doesn't comply with guidelines, at that point the daktable's pipeline is 10 years old and has been hot-plugged with masks, multi-instances and pipe reordering in ways it was not designed for, so, yeah, brittle stuff is going on and nobody understands the pipeline anymore.

**Comment by timur-davletshin** [comment]
> If C was really a programming language, we would discover these kind of errors at compilation time. But here we are…

Brian Kernighan is still alive...

**Comment by ralfbrown** [comment]
That reminds me of something which is surprising behavior more than a bug (it's actually doing exactly what it's been told): if you choose scene-referred workflow and leave "auto-apply per-camera basecurve" set, you get both filmic and basecurve enabled on initial open if dt has a basecurve for the specific camera model that took the picture.

**Comment by matt-maguire** [comment]
Fixed in #6304

**Comment by TurboGit** [comment]
Closing as fixed.
