### ISSUE TITLE
rgb curve - color picker not desiabled when selecting any blending mode

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5607]
**Describe the bug**
In rgb curve - color picker not desiabled when selecting any blending mode

**To Reproduce**
1. Go to darkroom
2. Open rgb curve module
3. Select color picker standard or the +/- on top
4. Click on any blending mode, say drawn mask
5. Picker is not disabled
6. Select pencil
7. Click on image and it still change the color picker location

**Expected behavior**
The color picker must be disabled when a blending mode is selected.

**Platform (please complete the following information):**
 - Darktable Version master
 - OS: GNU/Debian

**Additional context**

Most probably due to the recent introspection changes. We probably want to double check other modules. "rgb levels" seems to work properly.

**Comment by TurboGit** [comment]
@dterrahe : Could you have a look ?

**Comment by dterrahe** [comment]
Color zones has the same issue and I believe it only applies to the left (normal) picker). This is caused by the earlier color picker refactoring, not introspection. There used to be some code that specifically only turned off the +picker. I refactored that to leave the normal (left) picker enabled whenever any widgets change within the module, but I hadn't considered blending I'm afraid, so that was a logic error. I was already planning to do some more cleanup in the blending module, which might be the best place to address this, but I postponed that because of the impending freeze.

In the meantime, the quick solution to this current problem is to comment out
`    if(strcmp(gtk_widget_get_name(module->picker->colorpick), "keep-active") != 0)
` in `dt_iop_color_picker_reset`

That also means that the normal color picker in rgb curve and color zones gets disabled each time a combobox setting is changed and would need to be reenabled to see the effect. I suppose that is a regression versus 3.0.2 but I can't judge whether that was an important feature. Please let me know if you would be ok with that solution for now or if you want me to deliver a more comprehensive fix (which might take a few days).

**Comment by dterrahe** [comment]
Created and tested a minimalist patch, as proposed above.
