### ISSUE TITLE
Filmic v4: "middle tones saturation" pushes colors out of gamut ?

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#5639]
Currently testing DT git master. Please use this image:
[DSC00635.ARW](https://drive.google.com/file/d/1hkv6EKXlo8q-1vt2rZixUWZBpYTMCYAA/view?usp=sharing)
[DSC00635_05.ARW.xmp](https://drive.google.com/file/d/1hkv6EKXlo8q-1vt2rZixUWZBpYTMCYAA/view?usp=sharing)
This file is licensed [Creative Commons, By-Attribution, Share-Alike](https://creativecommons.org/licenses/by-sa/4.0/).

Now enable gamut warning and increase "middle tones saturation" in filmic module. See the blue tones in the sky and the mountains going out of gamut, even at low values of saturation. Colors becomes blue-led like.
By comparison, this doesn't happen if you increase saturation in color balance instead, even at much higher values.

![Cattura](https://user-images.githubusercontent.com/43290988/85824601-7e3f5c80-b780-11ea-9c7b-1629818de676.JPG)

**Comment by pitbuster** [comment]
Color balance goes before filmic, so filmic own's desaturation helps avoid out of gamut colors. Maybe filmic resaturation could use finer steps, but at that point of the pipeline, there is little more to be done that be careful IMO.

**Comment by paolodepetrillo** [comment]
I had noticed the same thing with another image. The different "Preserve Chrominance" options seem to have a significant effect on how much out of gamut color occurs when increasing the saturation.

With my image tweaking the white balance seemed to help.. [this post](https://eng.aurelienpierre.com/2018/11/filmic-darktable-and-the-quest-of-the-hdr-tone-mapping/) on filmic says that:

> Notice that the chroma preservation is especially not forgiving with inaccurate color profiles and color-checker LUTs, ill-set white balances, and lens chromatic aberrations.

**Comment by Mark-64** [comment]
The point here is that v3 let you choose how to desaturate extreme luminance values while saturation of mid-tones is handled saparately, normally with the color balance module.
Instead, v4 puts to 0% the saturation of black and white no matter what and let the user choose resaturation of midtones inside filmic. 
One could think the two approaches are equivalent and v4 should actually be better, but it seems it has a weird effect on blue tones.
@pitbuster Using v4, I can put midtones saturation to 0%, use a color balance module, putting it manually after filmic. doing so I don't get the out of gamut blues even with much higher saturation values. That's why I believe it could be a bug. 
I guess only @aurelienpierre can shed some light here.

**Comment by aurelienpierre** [comment]
Everything normal here. Whatever the saturation algo you use, it increases the probability of pusing color outside of gamut. Also, "out of gamut" is only relative to the color space you use as a reference. We already know that sRGB is much much smaller than your camera gamut, so it's no surprise that color will shrink at the end of the pipe. You should use Rec2020 as a gamut check reference, and see if colors originally in gamut are pushed out of gamut by filmic. But keep in mind that adding saturation is likely to push them away.

Also, you can slide the latitude to black or white (using shadows-highlights balance), that will slide the resaturated range accordingly and let you favour saturated shadows or highlights.

> The point here is that v3 let you choose how to desaturate extreme luminance values while saturation of mid-tones is handled saparately, normally with the color balance module.

No, colorbalance affects the saturation of the whole range and makes no differences if it's midtones or extremes.

Keep in mind that filmic gamut mapping is a basic safety jacket, not a full-fledged pipe -> RGB output mapping because that could only happen in output color profile.

**Comment by Mark-64** [comment]
Ok. I close then
