### ISSUE TITLE
parametric mask: "set range" color picker doesn't keep gradient slider area markers

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5656]
If I use the "set range" color picker in a parametric mask, it also shows the applicable range of the selected area on the input/output gradient sliders, which is very useful.

![Screenshot_2020-06-28_19-15-00](https://user-images.githubusercontent.com/9555491/85955023-bfe42900-b973-11ea-8364-7201fed601a7.png)

However, if I then manually move one of the sliders, this range is no longer shown

![Screenshot_2020-06-28_19-15-25](https://user-images.githubusercontent.com/9555491/85955039-d1c5cc00-b973-11ea-8b51-eb0e67bd7f5f.png)

The only way to get it back is to re-select the same area with the second color picker. But it's very useful to still keep a visual representation of the selected area in order to assist with any adjustments.

I suspect this is probably more of a feature request since I see the same behaviour on 3.0.2

**Comment by dterrahe** [comment]
@elstoc I'd been thinking that it would be useful to switch from the right color picker, which _sets_ the mask, to the left, which just shows the results for the selected range. Or to have the ranges connected. This would be a bit fiddly and probably lead to confusion, unless done really well. Implementation wise also not that trivial, but there must be a way to do it once we've decided on what the best behavior would be. Currently obviously the right picker just switches off when a further manual change is made in order to avoid overwriting it.

**Comment by elstoc** [comment]
> I'd been thinking that it would be useful to switch from the right color picker, which sets the mask, to the left, which just shows the results for the selected range. Or to have the ranges connected.

Exactly what I was going to suggest.

**Comment by dterrahe** [comment]
Something to look at for 3.4...

**Comment by dterrahe** [comment]
#5634 provides the simple fix of just not disabling the color picker for the specific case that either one of the multi-value sliders gets adjusted. Please test if there are any corner cases that lead to unwanted behavior.
