### ISSUE TITLE
Unify formatting of similar strings across modules

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#5660]
In order to create more logical UI and ease understanding of editing process I believe we need to unify formatting of similar strings.

__filmic rgb:__
- structure/texture
- bloom/reconstruct
- grey/colorful details
- shadow/highlights details
- middle tones

__color contrast:__
- green vs magenta
- blue vs yellow

__color balance:__
- lift / offset
- gamma / power
- gain / slope
- mid-tones

__color lookup table:__
-  green/red (BTW, why red, not magenta?)
- blue/yellow

**Comment by timur-davletshin** [comment]
Probably it is better to avoid using of "/" in strings like "green/red", it creates potential problem in preferences → shortcuts ("/" is treated as separator). See how color lookup tries to overcome this problem in shortcuts (compare with same idea in color contrast).

**Comment by hatsunearu** [comment]
As a dual-lingual person, I must add that vs. is not a common term in some languages, and that there might not be a good replacement for that. Whereas a symbolic separator like `/` is quite common.

**Comment by elstoc** [comment]
Might "|" be a reasonable alternative? e.g. "structure | texture"

**Comment by johnny-bit** [comment]
I think it could be like this:

1. Normalize `midtones`. Currently filmic uses `middle tones saturation`, color balance uses `mid-tones` and color balance rgb uses `midtones`
2. while it might be problematic on some non-unicode fonts I'd love to see `<->` character were it makes sense: U+2194 `↔` or U+27F7 `⟷` or U+27FA `⟺` or U+2B04  `⬄` or U+2B0C `⬌`. eg in filmic:
    - `structure ⟷ texture`
    - `bloom ⟷ reconstruct`
    - `gray ⟷ colorful details`
3. in color contrast the term used got changed to more sensible `green-magenta contrast` so that's a bit better
4. color balance make sense, because the terms in that case are pretty much interchangeable, so it's ease of recognition
5. Color look up table coud use arrows instad of `/` ;) and indeed the shift is rather towards magenta.

**Comment by johnny-bit** [comment]
Please see #9814 and check if alleviates your problems :)
