### ISSUE TITLE
For selected history copy&paste the Ctrl-Shft-V is broken 

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#5687]
**Describe the bug**
Copy selected history from one image and paste parts of it (Ctrl-Shift-V). Darktable hangs now.

**To Reproduce**
If you do this on the console it shows
```[image_cache_allocate] failed to open image 65408928 from database: no more rows available```

**Expected behavior**
Should just work :-)

**Platform:**
 - Darktable Version: todays master git
 - OS: Fedora 32

**Additional context**
Has been working not long ago, don't know the key accels code at all yet so -- up to someone else :-)

When analysing data presented to `dt_history_paste_parts_on_list` at least the firstdest is always wrong, the length of the list seems to be right. Somehow the `dt_view_get_images_to_act_on` does not work correctly in this context, is it `_accel_paste_parts`? If so, are other shortcuts possibly also affected?

**Comment by elstoc** [comment]
What view is this in? The lighttable view shortcuts aren't necessarily the same as the darkroom ones.

**Comment by jenshannoschwalm** [comment]
Lighttable

**Comment by elstoc** [comment]
Ok then not related to bea8af4 - lighttable should use the shortcuts defined in ``libs/copy_history.c`` which should do exactly the same thing as when you click the button (the keyboard shortcut just connects directly to the button).

I get the same issue on current master. The only difference between initiating it via a shortcut and via the button is that your mouse is likely hovering over an image when you initiate the shortcut (and never when you use the button). Try repeating the test while your mouse is hovering over one of the side panels and it works fine.

So probably it is something about the ``dt_view_get_images_to_act_on`` function since that does work differently if you're hovering an image.

**Comment by jenshannoschwalm** [comment]
Hmmm, further test show

Pasting works **fine** if the mouse has **not** been over any thumbnail while pressing Ctld-Shift-V

**Comment by TurboGit** [comment]
I have a fix, will PR in a moment. A quite tricky one to investigate !!!
