### ISSUE TITLE
Darktable Importing Hyperlapse dng files from Mavic 2 Pro

### ISSUE THREAD

**Issue by iBainesy** [darktable-org/darktable#5706]
**Describe the bug**
Importing Raw DNG files from the Hyperlapse function on Mavic 2 Pro results in an error, regular DNG files shot on normal mode are fine.

**To Reproduce**
1: Import Image from Hyperlapse folder from Mavic 2 Pro (Has to be raw files created from Hyperlapse mode, regular raw files work fine)
2: Error message (I'll paste links to 2 different pictures, 1 is from a regular shot, the other is from a hyperlapse shot.)

**Expected behavior**
I expect a Hyperlapse raw file to be treated the same as a regular shot Raw file.

**Screenshots**
None.

**Platform (please complete the following information):**
 - Darktable Version:  3.0.2 (But a user on reddit attempted with the latest development version as at 06/07/2020 and said that it doesn't work there either.)
 - OS: Windows 7 Pro (I know, I know, I should get with the times)
 -  Unsure.
 - Graphics card: GTX 760 - 445.75

**Additional context**

**Comment by jade-nl** [comment]
Helping out a first-time bug poster, here's some additional info:

This issue was initially posted on [reddit](https://old.reddit.com/r/DarkTable/comments/hhtsdq/importing_hyperlapse_raw_files_into_darktable_302/) and I'm the one that pointed out filing a bug report. Here's some info from the reddit thread that isn't mentioned/available in the above post.

* [The DNG in question \[google drive\]](https://drive.google.com/file/d/1KZX_tLqyR7Y9zBhABLa41AnV9oA2iTdb/view?usp=sharing)
* The DNG does not load (skull) and the following error is thrown:

> RawSpeed:WARNING: RawImageData::subFrame - Negative crop offset. Crop skipped. [rawspeed] (HYPERLAPSE_0001.DNG) void rawspeed::DngDecoder::handleMetadata(const rawspeed::TiffIFD*), line 483: No positive crop area

This happens in both darktable 3.0.2 as the latest development version.

**Platform**
* darktable        : 3.1.0+2426~gd4fe89ee2
* OpenCL installed : Yes (nvidia-opencl-common 440.82-1~bpo10+1)
* OpenCL activated : Yes
* OS               : Linux (kernel 5.4.0-0.bpo.4-amd64)
* Distro           : Debian Buster (rel. 10.4)

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0 - clang 10.0.1 - LLVM 10.0.1
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by iBainesy** [comment]
Thank you for that.
I've just noticed, my post is cut off after "Additional context", where I linked files and wrote extra stuff...
Copied from me "Editing" my original post (it appears in the edit, but not on the post?)

**Additional context**
 - Can reproduce with an older version, can't remember which
 - Only shoots RAW in hyperlapse mode (It might save a JPEG but I have that option turned off, not sure)
 - Not sure about removing history, it doesn't even import to get to that stage.
 - Added a XMP file, not sure if it's for the same picture, but it is from a failed import.
 - Downloaded it for Windows 7, so no compiling
 - Is the issue still present using an empty/new config-dir - Unsure sorry.

**Files share:**
https://drive.google.com/file/d/1KZX_tLqyR7Y9zBhABLa41AnV9oA2iTdb/view?usp=sharing, https://drive.google.com/file/d/1nMVwBDZbpRz9pvBFLMK8bcXStyIZ5C6p/view?usp=sharing, https://drive.google.com/file/d/1pLEdjvq_DXdjLTCngdG3CTmL_GkWyQn2/view?usp=sharing

**Comment by jenshannoschwalm** [comment]
No idea what "hyperlapse" I took a look at the shared "DNG-in-question" and as you descibed it does not work in dt.

The reason is pretty simple i think, have a look at exiv2 output
```
Exif.SubImage1.ActiveArea                    Long        4  0 0 0 0
Exif.SubImage1.DefaultCropOrigin             Rational    2  0/0 0/0
Exif.SubImage1.DefaultCropSize               Rational    2  0/0 0/0
```

These are just wrong. rawspeed is quite strict about correct tags and relaxing that rule might lead to more problems. Don't know what  @LebedevRI thinks about this though.

RawTherapee uses a different decoder ...

**Comment by LebedevRI** [comment]
Yep, `ActiveArea` and `DefaultCropSize` look bogus. 
I don't see in https://www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.4.0.0.pdf anything that would imply that if those are zero they are to be ignored.

**Comment by iBainesy** [comment]
@jenshannoschwalm 
https://youtu.be/CZLeu-vUVV4
That's a hyperlapse I took, conveniently enough, the same as the pictures I've uploaded to google drive for looking at.
It's like a timelapse, but the camera isn't stationary, The Drone takes 25 pictures per 1 second of footage. so for 6 seconds it would take 150 pictures. In the video I set it to start at one point, and finish at another point, and it flew from point A to point B taking 150 pictures (Or how ever many it actually was) and the app produced a clip from those images.
BUT
It also saves the original pictures as Raw files so one could import them into a editing app, like Darktable, edit pictures, then bring it indo a video editing software to create a video from it.

Does Rawspeed have anything to do with the interval or shutter speed from the Camera/Drone? Would it be worth trying out different settings and seeing if the results are different? (Or am I completely missing the mark with what Rawspeeed is/does?

**Comment by LebedevRI** [comment]
@iBainesy please contact customer support for the manufacturer of whatever produced those raw files.
I believe, those raw files are incorrect. In metadata, it is incorrect to specify DNG tags `ActiveArea`/`DefaultCropSize` with all-zeros - that says that the image has no pixels. I guess they meant to specify that all pixels of the image are good instead.

**Comment by jenshannoschwalm** [comment]
> Does Rawspeed have anything to do with the interval or shutter speed from the Camera/Drone? Would it be worth trying out different settings and seeing if the results are different? (Or am I completely missing the mark with what Rawspeeed is/does?

The rawfile tags are **not correct**, the mentioned tags are about the sensor size and what parts of the sensor data are valid for development in darktable. ActiveArea describes the size to be used but here we have zero for width and height :-)

I also think it would not good to allow dt/rawspeed to proceed with such data. @LebedevRI assumption is correct, the zero tags in this **specific** case mean, "don't worry" but we can't take that for granted.

For your camera/software there are two ways to go
1. As suggested, report this as a firmware error at the cam/soft manufacturer
2. You could write a script that removes the buggy tags and replaces them with correct ones. exiv2 would be one candidate ... could be done by lua

**Comment by johnny-bit** [comment]
Unfortunately out-of-spec files are not a target to be used. Mavic needs to fix their file generator engine, not other way around.

If you have contacted mavic and the report is public - can you link it here please for future reference? Had Mavic fixed their engine already?

Either way marking this as "won't fix" and closing sice really there's hardly anything darktable CAN do. The tags are interpretted according to spec and so with the ones here the file literally says "the active area is 0x0 px"
