### ISSUE TITLE
Fine-tuning hue selection in masks

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#5741]
When selecting based on colour, e.g. "h", a colour bar is shown and the hue selected is defined by two pairs of arrowheads, which can be dragged to adjust the selection.  This works ok until the hue range is at one of the ends of the bar and you want to extend it. It's not possible to make the arrowheads "wrap around" so that the range starts towards the right side, and finishes towards the left side.  At least I can't make it wrap around!  (I suppose for hue, ideally, it would be a circle rather than a bar)

So the request is to be able to move the arrowheads more flexibly and have them wrap around.

**Comment by johnny-bit** [comment]
Hue is (i think) the only circular setting and I really wonder how to express that in ui so that the controll has the same ux as expected by others yet allow for what you describe...

Anyway - there MIGHT be a workaround, eg - select hues that are available and then invert mask (dunno if it would work tho ;) )

As for the controll - my first (and currently only) idea would be to allow to drag (eg move 0° from start of controll to middle by drag and move rainbow to match it) and then have triangles nicelly map to dragged value.

**Comment by RawConvert** [comment]
Re. your last point, I also thought about that, it seems like a good pragmatic solution.  Of course sliding the zero degrees position has to be particular to each instance of each module.  I suppose dt could automatically put the selected range in the middle of the bar at the point you take the sample.

**Comment by johnny-bit** [comment]
well i tried it recently - invert polarity of slider works for getting 0-20 and 340-360 in range :)

**Comment by RawConvert** [comment]
Nice one, yes, seems to work.  You could put this as a tip in the main forum?

**Comment by johnny-bit** [comment]
https://github.com/darktable-org/darktable/wiki/User's-portal#selecting-red-hues-in-hls-blend-mode :package: 

actually you can share this tip yourself!

**Comment by RawConvert** [comment]
Ok, I might do that.
I'll leave this Issue open in case someone decides to centralise the sampled range, that would seem a nice improvement.

**Comment by RawConvert** [comment]
Anyone interested in centralising the sampled range so that you don't get constrained by the widget boundaries?
