### ISSUE TITLE
FR: Better visual indication and control when changing module order

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5772]
Usually a user will only have a small subset of available modules displayed in the right hand panel.

If a user chooses to reorder the modules by dragging and dropping, it is not clear how that module will be placed in relation to the modules that are **not** displayed, either during or after the drag-and-drop operation.

For example, take the following random subset of modules (where all modules are shown in the right hand panel)

![Screenshot_2020-07-19_20-11-14](https://user-images.githubusercontent.com/9555491/87882997-0ae5df00-c9fc-11ea-95a7-22bb9ef9e59d.png)

I amend my favourites group to show alternate modules from this list

![Screenshot_2020-07-19_20-12-52](https://user-images.githubusercontent.com/9555491/87883025-3cf74100-c9fc-11ea-86a5-caefe7f7249d.png)

Now, say I want to move fill light so that it sits between color zones and velvia, there are two choices - I can either place it immediately before color zones (after vibrance) or immediately after velvia (before vibrance) in the pipe. Currently darktable makes that choice for me. However, it should be possible for the user to choose between these options and for darktable to visually indicate which one will be done when the module is dropped.

The best suggestion I can think of is that, while dragging, the user is presented with two empty 'placeholder' slots into which they may drop the module. The placeholders appear when the user drags over a module header (they appear before that header). They move if the user drags over another module header and they disappear if the user drops the module or drags over the body of another module or outside of the right hand panel. The module can only be dropped into one of these placeholders.

**Comment by dterrahe** [comment]
My gut feeling is that any way that adds choices here is likely to lead to confusion. A useful, predictable, default and a way to be more specific if needed might be better than a very advanced/flexible approach that is not immediately obvious and either doesn't get used or needs to be double checked anyway. So my preference would be:
- when not all modules are visible, if you drop a module just above another module, it will be in the pipe _immediately after_ that lower module, even when there are other modules sitting between that lower module and the one that is shown immediately above it.
- if I want to place more specifically, I can either temporarily switch to the first group with all active modules (which is maybe where you should be doing all your module reordering?) or show all modules.

But I haven't really been annoyed by this issue myself. If it is really problematic for you, I understand you'd want to implement a solution that solves your workflow.

In your suggestion, you you say "two empty 'placeholder' slots" because in your example there is always one module in between that wasn't shown? Generally, it could be any number of invisible modules between two successive visible modules. You could temporarily show all those intermediate modules, whether invisible or not. But it would make the list jump up and down, so you'd have to be careful to keep the module the dragged module is currently hovering above stationary and move modules above and below to make space for all the intermediate modules. This would be quite complex to implement and, though maybe nice (but confusing), for me the benefit would be limited. The added complexity could also cause bugs or more time spent on maintenance/implementing other features that become more complex. As a first time user of module reordering I would be taken aback by everything jumping about. And module reordering is already confusing enough (with the pipeline consequences not obvious)...

**Comment by elstoc** [comment]
> In your suggestion, you you say "two empty 'placeholder' slots" because in your example there is always one module in between that wasn't shown?

No. I mean so that the two options would be either "immediately before the upper module" or "immediately after the lower module" in the pipe. The user would still be limited to placing modules immediately adjacent to the modules that are currently visible.

**Comment by parafin** [comment]
> the two options would be either "immediately before the upper module" or "immediately after the lower module" in the pipe

In case there are no modules in-between upper and lower modules these 2 options are one and the same.

How often do you re-order modules? I would say it should be done very rarely, so maybe it makes sense to limit the reorder feature to all modules view only.

**Comment by elstoc** [comment]
> In case there are no modules in-between upper and lower modules these 2 options are one and the same.

Agreed

> How often do you re-order modules?

There are a couple of situations where I reorder quite often. For example when using channel mixer in a monochrome workflow I always move exposure to after channel mixer to avoid clipping. Or if I want to spot/retouch with the source outside of the cropped area I'll move the crop/rotate module.

> maybe it makes sense to limit the reorder feature to all modules view only

That makes sense as a way to work around the issue I'm discussing here but maybe a bit too far for most users. TBH given the issues raised with my proposal I'm probably just as happy with having a visual indication of what darktable is doing by default. Then if I disagree with it I can go into the 'all modules' view and correct manually.

**Comment by parafin** [comment]
> There are a couple of situations where I reorder quite often. For example when using channel mixer in a monochrome workflow I always move exposure to after channel mixer to avoid clipping. Or if I want to spot/retouch with the source outside of the cropped area I'll move the crop/rotate module.

But isn't it possible to create a preset/style of module order? And apply it when these situations arise instead of re-ordering manually each time.

**Comment by elstoc** [comment]
Yes it is. Not something I've explored but a good idea.

**Comment by dterrahe** [comment]
> There are a couple of situations where I reorder quite often. For example when using channel mixer in a monochrome workflow I always move exposure to after channel mixer to avoid clipping. Or if I want to spot/retouch with the source outside of the cropped area I'll move the crop/rotate module.

Not knowing much about this feature, I would have thought this should be possible with module order presets?

> No. I mean so that the two options would be either "immediately before the upper module" or "immediately after the lower module" in the pipe. The user would still be limited to placing modules immediately adjacent to the modules that are currently visible.

Ah, so a partial solution that hopefully covers 90% of the cases. Currently there is no visual feedback while dragging/hovering over a module. Usually in dragging UIs, you see a bold line drawn between the items where the dragged item would land. You could extend this visual feedback maybe to show that it is clinging to the upper module (if you are hovering over the bottom half of the upper module) or that is is clinging to the lower module (if you are hovering over the top half of the lower module). Without otherwise dynamically popping up "landing zones".

**Comment by elstoc** [comment]
> You could extend this visual feedback maybe to show that it is clinging to the upper module (if you are hovering over the bottom half of the upper module) or that is is clinging to the lower module (if you are hovering over the top half of the lower module). Without otherwise dynamically popping up "landing zones".

I considered that. The only issue is that one or both of the upper/lower modules might currently be expanded (or not), so it might be hard to consistently determine where the upper and lower bounds are.

> Usually in dragging UIs, you see a bold line drawn between the items where the dragged item would land.

Yes. Perhaps if we just kept the current default positioning and extended this implementation by also slightly altering the background color of the module to which it would cling. Then after dropping we could pop up a toast saying "module <name> placed <before|after> module <name>".

**Comment by elstoc** [comment]
I've submitted a (perhaps slightly crude) suggestion of how this could work in #5775

**Comment by aurelienpierre** [comment]
empty placeholders are a better UX and a one that is pretty common among other apps. I often drag the modules above instead of below the target, because the threshold is quite sensible. But then I guess you are on for some Gtk madening time.

**Comment by elstoc** [comment]
Yes this is what I've gone for in #5775.
