### ISSUE TITLE
Clamp negative L values after unsharp mask and local contrast modules

### ISSUE THREAD

**Issue by age1988** [darktable-org/darktable#5783]
Avoid negative L channel values generated from um and local contrast

**Comment by hatsunearu** [comment]
Does #5668 potentially fix what you're talking about?

**Comment by jenshannoschwalm** [comment]
I guess the underlying problem is in `dt_bilateral_slice` and it's cl friend **not** clipping for below zero in L channel.

I am not sure how to proceed here .. technically negatives are undefined here. So do some clamping here. But would that break old edits .. possibly yes if done wrong in the using modules.

1. Define a new version for every using module?
2. leave it as is 
3. do clamping here and declare possibly changed old edits as "broken developed"
