### ISSUE TITLE
Contrast Equalizer: Visualise wavelet frequencies

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5855]
When using the retouch module it is possible to visualise each wavelet scale that can be acted on. It would be really useful to have something similar in the contrast equalizer so that you can visualise either

- The areas of the image that will be impacted based on the current module settings; and/or
- The areas of the image that each node impacts

For the latter, it could use the 'graph' that gets drawn in the background when you hover over the nodes. So hovering here:

![Screenshot_2020-08-02_14-51-42](https://user-images.githubusercontent.com/9555491/89124537-c8c69e00-d4cf-11ea-8d8d-0f0100d60688.png)

Might show something like this on the image:

![Screenshot_2020-08-02_14-53-33](https://user-images.githubusercontent.com/9555491/89124568-f7dd0f80-d4cf-11ea-974c-ed9f81205ac4.png)

The above example was produced by drawing the same shape and enabling 'difference' blend mode, i.e.

![Screenshot_2020-08-02_15-02-27](https://user-images.githubusercontent.com/9555491/89124744-40e19380-d4d1-11ea-9cf6-bb663b9cad70.png)

However, I would hope that such a visualisation would be a bit brighter than this example.

**Comment by aurelienpierre** [comment]
This is almost impossible to achieve within reasonable runtimes with current pipeline design. Basically, the GUI and the pipeline live in fully separated threads, and synchronizing them is difficult and unreliable. Also, when working on OpenCL, it means that image buffers need to be copied on-the-fly from vRAM to RAM because the painting is done by Cairo on CPU only. 

So far, the retouch module gets away with that by outputing the requested wavelets scale instead of the module output. But it's not interactive, and awfully slow.

**Comment by elstoc** [comment]
Boo. Even just some hack that temporarily enables difference blend mode (and maybe brightens it - by increasing mix) would be nice. I can get a semi-ok result by doing that and pushing mix to 2 (it won't go any higher) but that's a few clicks every time.
