### ISSUE TITLE
Comboboxes in prefs do not work when DT is in fullscreen mode on macOS

### ISSUE THREAD

**Issue by virtualritz** [darktable-org/darktable#5903]
**Describe the bug**
Comboboxes in prefs do not work when DT is in fullscreen mode on macOS unless focus is switched to another app once before using them.

**To Reproduce**

1. Make sure DT is in fullscreen mode.
2. Open the darkroom.
3. Open the preferences. Try to use/change any menu/combobox item – it does not open.
4. Keep the prefs open & switch to another app (CMD-Tab) and back to Darktable -- menu/comboboxes in prefs work now.

Everything works fine if DT is *not* in fullscreen mode.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: macOS 10.15.6
 
**Additional context**
I'm using the official binary from the DMG from GitHub.

**Comment by parafin** [comment]
I confirm this bug - when clicking on combobox the list that appears is rendered below the dialog window (not the main window, so preferences or for example edit preset window). It's the same for both bauhaus and native comboboxes. I will take a look, but it's unlikely that I can do anything about native comboboxes. It's just that GTK quartz backend works poorly...
BTW, scrolling over combobox works fine, since no additional window appears.

**Comment by parafin** [comment]
Fix will be in next release, as a workaround you can add the following text into CSS theme tweaks field in general tab of preferences (and press save theme tweaks after that):
```
button:checked cellview
{
  color: shade(@button_hover_fg, 0.99);
}
```

**Comment by elstoc** [comment]
> Fix will be in next release, as a workaround you can add the following text into CSS theme tweaks field in general tab of preferences (and press save theme tweaks after that):

Don't forget to also tick the 'modify selected theme with CSS tweaks below' box
