### ISSUE TITLE
[Feature request] Server/client mode

### ISSUE THREAD

**Issue by Eideen** [darktable-org/darktable#5904]
I like there to be a option to have some parts of the work be done by a server, especially storage.

There is a tread on the maillist:
https://www.mail-archive.com/darktable-user@lists.darktable.org/msg09331.html

# Server:

- Provides an API to the Client.
- Is the only direct user of the database, so SQLite will still work,
but Mysql/MariaDB is much faster.
- Have a web interface for management.
- User upload images via API or web interface-
- Server is responsible for generating thumbnails.
- Server is responsible for handling storage of images.

# Client:

- Access the server via API.
- Downloads thumbnails for faster browsing.
- Download to local cache any images for editing.
- Client adds new files to local cache first, then uploads in the
background to the server. Alla OwnCloud.

Since I don't know all the inner workings of darktable there is
probably internal service I have skipt.

**Comment by johnny-bit** [comment]
Why would you want that at all? You CAN have images on external storage. you CAN take images away and do processing "on the go". You can then store images back. You can have owncloud providing you networked fs for storage...

The only thing I could see benefit of client/server would be to have thin-client for processing images and having server provide computational power, but that's really weird - you'd have to have server with opencl compute card(s) to see any real performance benefit over network latencies, which at that point could be better realized with things like RDP to server and have darktable working on remote graphical env.

**Comment by Eideen** [comment]
I have multiple servers and multiple client. For my desktop with wire connection, it work okay. but for my laptop it doesn't work that well. For media I have 200GB, of raw files. And my clients don't need to download 200GB of raw files to generate thumbnails, everytime i replace my clients.  

External storage is a lot of hazel, it doesn't backup it self, it isn't always accessible.  

In my experience Darktable doesn't likes SMB shares, it extra bad on VPN. and Darktable doesn't handle multiple folder location. or like you say the network latency is higher than local connection.

With file hosting service you still need to have the entire folder download to added to Darktable, to be able search it.

A other problem i like to solve is to have a backup of Darktable things. Currently you need to manage everything per client base, and can't be shared between clients. 

So the best solution i see is to be able to server/client solutions that handles the files, and database. For my needs it only need to handle the database and files. And the client download and edits the file and exports the file. and the changes get send back to the server database for backup.

**Comment by bigntallmike** [comment]
> The only thing I could see benefit of client/server would be to have thin-client for processing images and having server provide computational power, but that's really weird - you'd have to have server with opencl compute card(s) to see any real performance benefit over network latencies, which at that point could be better realized with things like RDP to server and have darktable working on remote graphical env.

I have a very fast PC with OpenCL running Darktable and a laptop I want to work from sometimes in the kitchen.  Being able to run Darktable 'remotely' by having the processing take place on the PC would certainly speed up that workflow.  As it is, I have to live with the much slower laptop processing when working that way.

I don't see it as a 'must have' but I can certainly understand the rationale -- this type of code reorganization can be hard though, although it also offers a good distinction between back and front end code that helps keep things more clean.

**Comment by aurelienpierre** [comment]
This feature is unlikely to come to reality. Not that it's a bad idea, but at this point in the software history, it's too big of a change.

A nasty way would be to call darktable-cli on the server and have a lite monitor on the client that refreshes the preview by getting the resulting JPEG. Problem is the pipeline caching will not be supported, so the preview pipeline will need to be recomputed entirely each time.

Then, the server will not be aware of the client monitor color profile, so the colors for the preview will be off, unless we use a connection color space like sRGB, which may trigger a load of bad side-effects and color inconsistencies for someone who needs a color-proofing setup.

**Comment by thequux** [comment]
I'm seconding the request for support for storing the library on a server. My use case is that I'll often take photos, transfer them via my laptop, and then do most of my editing on my workstation, which has much more processing power and enough GPU power to drive nice 4k monitors. Also, while my laptop hovers around a few GiB of free disk space, my server has 16TiB of storage. Further, I have never had good experiences running SQLite on a network filesystem, even with only one client at a time.

Based on my analysis of the problem, I think that the best approach would be to make it so that users have a choice between either using a local sqlite database (in which case, the user experience would be nearly identical to what we have now) or storing the database on a server that exposes either a REST-style interface or GraphQL (or a combination of the two, depending on what turns out to be necessary) for metadata and history stacks, and that uses a simple subset of the S3 API for storing bulk image data (to make it easy to provide hosted database storage if we decide to do that in the future). 

My plan of attack for this would be as follows:

1. Start by cleanly separating library access from the rest of the program logic using an internal API. Ideally, this API would be flexible enough to support all of the previous schemas for the sqlite database that I can find; as soon as you have separate client and server components, version skew becomes an issue, and being able survive a reasonable amount of version mismatch is important for the user experience to not suck. Importantly, the final form of this interface wouldn't expose any sort of information about file paths or raw access to the sqlite database, though while this step is in progress, such fallbacks would exist to ease porting.
2. Generalize this API into a WIP spec for the HTTP API; ideally, as the access patterns in Darktable change and features are added, we want older servers to be able to support as many features from newer releases of darktable as possible.
3. Implement a client and server for this API in tandem. The client would, of course, be written in C and be part of darktable itself, and it would just be another implementation of the interface that darktable uses to access the SQLite library. The server would be maintained in its own repository and might be written in Python, Rust, or Go, because these are currently the best languages for writing web services.

In the initial release, each individual photo will only be editable by one client at a time; merging is a hard problem. Making a copy of a locked photo will be possible, so I don't expect this to be that onerous of a restriction.

Over time, I would like to add features like simultaneous editing of a single file (i.e., merging), a web UI for browsing film rolls (which I'd imagine would be useful for both professional photographers who want to deliver proofs and final results to clients and for home users who want an easy way to put up web galleries of their photos), and similar features. 

If I were to work on this alone, it would probably be a year or two of implementation effort; I only have so many hours outside of my day job. Still, I'd be happy to do so, because it would solve a very real problem for me. All that I'd expect from the darktable developers is that my patches and/or pull requests (whichever you prefer) would be merged without too much fuss, and ideally some help providing integration into the user interface (because every single one of my attempts to create a user interface has been dreadful)

Does this sound like a good plan, and if I were to start writing code, would my patches be accepted?

**Comment by qosch** [comment]
Just came across this by chance and wanted to name a (relatively) simple  way to achieve at least export of final images on a server (I think this is called "off site rendering" when talking about videos instead of images). I started working on the server side script a few years back but lost interest at some point. Here is what I tried/had in mind:
- the server has darktable-cli installed and uses something like inotify to monitor the directory that RAWs are in
- the local darktable needs a lua script or a module that has the usual export setting, but instead of running the export itself, it writes a txt file to the server directory that only writes the command line arguments that darktable-cli would need to run to export the images
- the server gets notified that the txt file was modified (or created), starts exporting the images and removes every line from the txt that was already processed.

There is no information on the progress of the export visible in the local darktable instance but the remaining lines in the txt file could be checked to monitor progress. This solution would require only very little development work inside darktable (maybe it could even be done by an external lua script) but I am not sure how many people would really use this feature. It's understandable to me that this is not high up on the list of priorities.
