### ISSUE TITLE
Make image fill the whole (or the most of the) screen in file manager

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#5926]
**Is your feature request related to a problem? Please describe.**
When I Shift-scroll in the FileManager to only see one image, the image does not fill the whole screen. @aurelienpierre told me its because the requirement was to always have square items in the file manager. However, here it is really annoying because the image has the same size as each of the 2 images that I can see when I Shift-Scroll in the other direction by one go. 

**Describe the solution you'd like**
Be able to make the image much larger, whatever still works fine.

**Comment by elstoc** [comment]
Alternative would be to use the preview mode but I agree: keeping it square doesn't really make sense when it's no longer a grid.

**Comment by michalfapso** [comment]
In lighttable, I was used to hide all panels (Tab key) and zoom to a single image filling the whole screen for reviewing photos. In the new version 3.2.1 it is possible only by using the "Preview" mode (holding the "W" key), as @elstoc pointed out.

Could you please consider zooming photos to fit the whole window area in Litghttable also in the new version?

**Comment by esm7** [comment]
Even if there's solid logic behind this change and we now need Preview Mode to review images full-screen before grading/rejecting/labeling them, beyond the visual annoyance there's an important flow that was broken here.
It now became impossible to review a series of image by selecting the first one and navigating with the right arrow.
I now need to select the first image, review images (and label/reject/grade), press right on the keyboard, and then when I get to the end of the row... What do I do? Press left-arrow all the way and the down...? This makes no sense to me.
At least to me, the "light table" analogy on which the images are sorted on a big virtual rectangle always felt a reasonable choice to quickly zoom in and out within a collection, but the real central flow was always about reviewing images one by one and doing actions on them. Not sure if intentionally or not, but the support for this flow is completely gone now.

**Comment by helloworld1** [comment]
It is fast and very intuitive to scroll mouse wheel to zoom in to single image full screen in light table in darktable 3.0. But on 3.2.1, I feel the experience of zoomable light table much much worse. Needing to press W is not smooth and unintuitive.

**Comment by AlicVB** [comment]
As pointed by many, lighttable, zoomable or not is not designed to do one-by-one image culling. For that, you have either the sticky preview mode (alt-w) or the culling mode. In tis modes, you'll even gain the possibility to use filmstrip when you need it, to zoom inside the image, etc...



> It now became impossible to review a series of image by selecting the first one and navigating with the right arrow.
> I now need to select the first image, review images (and label/reject/grade), press right on the keyboard, and then when I get to the end of the row... What do I do? Press left-arrow all the way and the down...? This makes no sense to me.

can you elaborate, are you speaking with the use of preview mode ? sticky or not ? in filemanager with zoom == 1, in zoomable lightable ?



> It is fast and very intuitive to scroll mouse wheel to zoom in to single image full screen in zoomable light table in darktable 3.0. But on 3.2.1, I feel the experience of zoomable light table much much worse

Considering the full rewrite and the fact that zoomable lightable is not used intensively but any dev around, there's more glitch in this area. I'll try to take care of them !

**Comment by michalfapso** [comment]
Thanks, @AlicVB, for the insight. I didn't know about the "sticky preview mode" when I tried lighttable for the first time. It was most natural to me just to Ctrl+mouse scroll to zoom in the filmstrip, which worked well for the "one-by-one image culling".

Is the sticky preview mode visible anywhere in the lighttable window? Or just in the list of keyborad shortcuts? It would be great to show it to users, so they know it exists at the first sight. For me, this one-by-one culling is about 95% of my lighttable usage.

**Comment by johnny-bit** [comment]
sticky preview - just use [Alt]+W. press `H` to get help about available keys and modes. There's aslo focus detection preview and many more. Exposing them in GUI as buttons would cram up the interface.

**Comment by michalfapso** [comment]
I see your point, @johnny-bit. I didn't know about the `H` key either. Of course there can't be a GUI button for every action, but it would be really nice to find a way to communicate it somehow to users who just want to give darktable a try, they run it for the first time and just look at the GUI for what the possibilities it provides.

Maybe this preview mode would even deserve its own button as it is quite an important mode in lighttable. Maybe in the top toolbar on the right side next to the "collapse grouped images", ..., "settings" buttons. Then it would be needed to add another button to switch from the sticky preview mode back to the filmstrip mode. Maybe in the preview mode, there could be a "exit preview mode" button above / under the rating buttons in the top left corner.

**Comment by maboleth** [comment]
But can we have similar functionality like in 3.02 for zoomable mode?

There we used scroll mouse button, hovered above the image and just zoomed it straight to the center. In and out. Selected image was always perfectly aligned to the screen.
Now it's off and zooms wherever you're pointing it at. Sometimes it's the edge of the image or worse. You have to be careful to point your mouse exactly in the center to zoom it that way.

**Comment by Nilvus** [comment]
@michalfapso: Isuggest you to read 3.0 and 3.2 articles on darktable.org/blog. These articles will learn you some good features about darktable. And will save you time.

**Comment by michalfapso** [comment]
Thanks, @Nilvus. Now I know most of the stuff I needed. Keyboard shortcuts are perfect for me, I don't need buttons. I just thought, that the user experience of new users could be enhanced by showing the preview mode more visibly (e.g. as a button).

**Comment by Nilvus** [comment]
Preview feature is here since few years. It's not a recent feature. And it's hard to choose which button to add or not. Some others could be added but would overload the UI, as @johnny-bit said.

Anyway, as preview mode is near culling one in some ways, maybe could it be add on dropdown menu like culling, filemanager, etc. Just an idea. @AlicVB (and others), what do you think about that?

**Comment by michalfapso** [comment]
Yes, @Nilvus, such a dropdown menu would be really helpful. I've been using darktable for about 3 years, but didn't know about the preview mode at all. I always just zoomed in to a single image till it covered whole window and used `Tab` to hide other panels and went through my photos using arrow keys. But in 3.2.1, I can't zoom so close anymore, so I started looking at the issues list here and found out the preview mode :)

**Comment by AlicVB** [comment]
@Nilvus : you're perfectly right : preview and culling share almost all same code.
Now about your proposition, the tricky part is that preview (sticky or not) is a mode on top of other modes : you can enter preview from filemanager, zoomable and culling, and return to that mode once you exit preview...

**Comment by Nilvus** [comment]
> @Nilvus : you're perfectly right : preview and culling share almost all same code.
> Now about your proposition, the tricky part is that preview (sticky or not) is a mode on top of other modes : you can enter preview from filemanager, zoomable and culling, and return to that mode once you exit preview...

Culling mode is also on top of filemanager and zoomable view, so the tricky part is quite the same for culling and preview ones, regardless of filemanager and zoomable modes. Having preview on dropdown menu is so the same as having culling one, except that preview could also be on top of culling. So, if adding preview on dropdown menu, it would be at the end (on top of all others).

**Comment by esm7** [comment]
Sorry for the late reply, I was away for a few days.

> As pointed by many, lighttable, zoomable or not is not designed to do one-by-one image culling. For that, you have either the sticky preview mode (alt-w) or the culling mode. In tis modes, you'll even gain the possibility to use filmstrip when you need it, to zoom inside the image, etc...

I think that's essentially the key here. I was using zoomable mode the way that it was seemingly not designed to. The flow I was using the past years is now broken, but perhaps it was never meant to work in the first place.

> 
> > It now became impossible to review a series of image by selecting the first one and navigating with the right arrow.
> > I now need to select the first image, review images (and label/reject/grade), press right on the keyboard, and then when I get to the end of the row... What do I do? Press left-arrow all the way and the down...? This makes no sense to me.
> 
> can you elaborate, are you speaking with the use of preview mode ? sticky or not ? in filemanager with zoom == 1, in zoomable lightable ?

I was referring to how I (and seemingly also some other users) was using the zoomable mode. I was actually never aware of the other modes till this broke in 3.2.1 and I started digging the forums and bug reports. I always zoomed where I wanted to start reviewing (to zoom == 1 image), the image filled the screen, and from there I started rating images, rejecting, editing and coming back to lighttable etc., pressing Right on the keyboard until I was done with all the images.
This flow is now broken in two ways: 1) images don't fill the screen anymore and preview mode or culling is needed for that, and 2) even if I insist on zoomable and keep pressing right, it won't wrap past the end of a row in the light table.

**Suggestion:** since there was an overlap between the old behavior of zoomable and the relatively new culling mode, maybe there can be some continuity between them? e.g. maybe if a user zooms all the way into an image, Darktable will switch to culling mode with this image, and if she zooms out in culling mode, it will switch to zoomable?
The way I see it, the advantages of this behavior are:
1. It's consistent with what most users probably expect to happen when zooming all the way into an image (they probably want to review a series of images, and don't care about the arbitrary division to rows).
2. It makes culling mode much more discoverable.
3. It's consistent with the old behavior.

**Comment by Nilvus** [comment]
> Sorry for the late reply, I was away for a few days.
> 
> > As pointed by many, lighttable, zoomable or not is not designed to do one-by-one image culling. For that, you have either the sticky preview mode (alt-w) or the culling mode. In tis modes, you'll even gain the possibility to use filmstrip when you need it, to zoom inside the image, etc...
> 
> I think that's essentially the key here. I was using zoomable mode the way that it was seemingly not designed to. The flow I was using the past years is now broken, but perhaps it was never meant to work in the first place.

That's the key: zoomable mode was indeed never designed for that. 

> I was referring to how I (and seemingly also some other users) was using the zoomable mode. I was actually never aware of the other modes till this broke in 3.2.1 and I started digging the forums and bug reports. I always zoomed where I wanted to start reviewing (to zoom == 1 image), the image filled the screen, and from there I started rating images, rejecting, editing and coming back to lighttable etc., pressing Right on the keyboard until I was done with all the images.

The way you do doesn't mean the way it was design for nor the way most users use it. Other modes exist since few versions now, especially something like preview that is quite old. Culling and preview modes, design for what you want allow to navigate with left/right arrows (as well as mouse wheel)..

> This flow is now broken in two ways: 1) images don't fill the screen anymore and preview mode or culling is needed for that, and 2) even if I insist on zoomable and keep pressing right, it won't wrap past the end of a row in the light table.

So it's not a darktable issue as it was never design for your flow. And you have better tools for that. 

> **Suggestion:** since there was an overlap between the old behavior of zoomable and the relatively new culling mode, maybe there can be some continuity between them? e.g. maybe if a user zooms all the way into an image, Darktable will switch to culling mode with this image, and if she zooms out in culling mode, it will switch to zoomable?

Culling mode is not new (not on darktable 3.2.1. It was a new feature in darktable 3.0, asked by most users (like me) to have a better possibility to compare images. You can even compare not following images in your film roll.

> The way I see it, the advantages of this behavior are:
> 
>     1. It's consistent with what most users probably expect to happen when zooming all the way into an image (they probably want to review a series of images, and don't care about the arbitrary division to rows).
> 
>     2. It makes culling mode much more discoverable.
> 
>     3. It's consistent with the old behavior.

What you describe is culling mode. Nothing has to be consistent has it was not designed for.

**Comment by quovadit** [comment]
I would also suggest to have a gui element for the great 'sticky-preview' feature.
Extending the drop-down list seems quite logical for me.
(by the way: does anyone use the zoomable light table, or can this option be removed instead?)

**Comment by quovadit** [comment]
To sum up: lighttable is not designed to do one-by-one image culling, but the alternatives (sticky preview mode or culling mode) are not accessible intuitively (weird shortcut Alt-W or non visible option in drop-down).

So here is a suggestion how to 'fix' that:

- Replace the drop-down with meaningful icons including fullscreen+focus:
![sticky-preview](https://user-images.githubusercontent.com/5677563/103565048-e608f980-4ebf-11eb-83fc-cc4263118a97.png)
- Show description and current shortcut in tooltip:
  - Grid-View (adjustable number of images per row)
  - Zoomable lighttable (fix number of images per row)
  - Navigate through selected images side-by-side ('X')
  - Show all selected images side-by-side (Ctrl-X)
  - Fullscreen Preview of selected image ('F')
  - Focus Peaking mode (Ctrl-Shift-F)
- Change shortcut from Alt-X to F (meaning Fullscreen - as in lightroom)
- Limit Ctrl-Scroll in grid-view to minimum 2 images
- Show toast-message if user Ctrl-scrolls even further: 'Use Fullscreen Preview ('F') to show only one image'

**Comment by johnny-bit** [comment]
Here's my take:
> Replace the drop-down with meaningful icons including fullscreen+focus

IMO - Icons aren't too obvious, but then people don't read manual and we HAVE to encourage them now

> Limit Ctrl-Scroll in grid-view to minimum 2 images

That's a good idea!

> Show toast-message if user Ctrl-scrolls even further: 'Use Fullscreen Preview ('F') to show only one image'

even better...

But then there MIGHT be a use case for single image in non full view.

**Comment by Nilvus** [comment]
> lighttable is not designed to do one-by-one image culling, but the alternatives (sticky preview mode or culling mode) are not accessible intuitively (weird shortcut Alt-W or non visible option in drop-down).

This is designed, with preview and sticky preview. But yes, shortcut could be improved. I like the 'F' ('Alt'+'F' for sticky one) shortcut. More intuitive than actual one.

>     * Replace the drop-down with meaningful icons including fullscreen+focus:

I agree with @johnny-bit here. Absolutely not obvious, except fullscreen one image, and so not really more intuitive than actual drop-down.

>     * Limit Ctrl-Scroll in grid-view to minimum 2 images

Like that too.

> * Show toast-message if user Ctrl-scrolls even further: 'Use Fullscreen Preview ('F') to show only one image'

Really great idea.

**Comment by Nilvus** [comment]
@AlicVB: as you work a lot on those part, what do you think of all that?

**Comment by quovadit** [comment]
I totally agree, that it's important to push people to read the (great!) documentation.
But even this is much easier if there is an icon for each mode, so that you can use the context-sensitive help leading to the doc.

Secondly the drop down is very unusable for me (probably depending on the screen resolution?):
![drop-down](https://user-images.githubusercontent.com/5677563/103576841-1064b200-4ed4-11eb-8f4e-5739a532d56f.png)

To go to dynamic culling (without remembering Ctrl-X) I have to:
- open drop-down
- scroll down
- select culling
- open second drop-down
- select fixed zoom

Compared to: click on one icon

**Comment by Nilvus** [comment]
> Compared to: click on one icon

But icons are really not obvious. And here, scroll down is more a Gtk issue than darktable one and depends on which Gtk release you have on your system. And more, menu you show seems strange. Could you precise which theme, OS and darktable version you use and post a screenshot with more outside the menu (not too much but just a better view with what's around). I would suggest you use dark theme, so her a screenshot of same menu (with more around) with dark theme, on Linux (Ubuntu 20.10 and Gtk 3.24.23):

![2021-01-04_18-51](https://user-images.githubusercontent.com/45535283/103577868-d5fc1480-4ed5-11eb-8fb3-1f935926e439.png)

**Comment by AlicVB** [comment]
So...
1. shortcuts : in fact, my "production" version (always little behind master) as F mapped to sticky preview... So I fully agree here. The tricky part is that "non-sticky" preview should ideally be mapped to a single key (keep 'W' ?)
2. limit filemanager to 2 : not sure, I know that some people heavily use filemanager with zoom == 1 and after all, that would mean artificially limiting a feature just because some user may be frustrated because they don't use it right...
3. icons : I quite like the idea (but we certainly can find better icons) even if icons are not self explanatory there's tooltips. Another advantage of icons is that we can use ctrl-click on them (for example to enter fullscreen with focus) that would limit the number of icons...

**Comment by AlicVB** [comment]
@Nilvus : about icon vs combobox : as @quovadit says, icons are really quicker imo. In fact I've never used the combobox, just the shortcuts because of that (well not only, I like shortcuts ;)  but sometimes when you only use mouse you don't want to search keys on keybors and in this cases an icon should be handy)
Not sure what I've said is understandable...

**Comment by johnny-bit** [comment]
regarding my "icons" criticism: I just say that those need consideration and design, but icons are good. I like toolbars :+1: 

after thining about it - i agree with @AlicVB  - no reason to limit images to 2 - can go to 1, but could be fine to point to user that "hey, you can get larger view with full view"

**Comment by TurboGit** [comment]
The icons idea is good to me. Please do not limit at 2 pictures, this would be gratuitous. For the rest I agree that discoverability would be probably better, on my side I do use the accels only for this s so I may not be the best guy to comment on the usability.

**Comment by TurboGit** [comment]
Already said, but I suppose the hard part would be to come up with 5 readable icons.

**Comment by quovadit** [comment]
Of course we shouldn't limit the grid to 2+ if there is the need for using it with only 1 image.

For non-sticky preview I would also keep W.

I like the idea of ctrl-click on the icons for focus-peak, but what about darkroom, there's also the focus-peak icon but no icons to ctrl-click on...

If we want to reduce the number of icons I would remove the 'display profile' icon and move that function to the preferences.

Here are some more ideas for the 5 icons:
![more-icons](https://user-images.githubusercontent.com/5677563/103637857-6412e200-4f4c-11eb-99b3-3237464f1cf1.png)
(a is the same as above, b is just reduced, d is 90% stolen from lightroom and c is something in between)

Maybe the icons should get highlighted on mouse-over so that they are more visible...

**Comment by johnny-bit** [comment]
> Here are some more ideas for the 5 icons:

Me likey the c and d option...

i strongly suggest to use `show_icons_in_paint_c.pl` to extract currently drawn icons and match the style :)

**Comment by TurboGit** [comment]
Option **d** for me looks the best. I don't like the icon on column 1 for others as it is too bright (white).

**Comment by TurboGit** [comment]
I see **d** stolen from lightroom... Probably a bad idea then. So maybe **c** with some more refinement. The arrows on icon 3 are not visible. And A, B and arrows on 5 not visible either. I would use a darker tone for those and for 1 a more greyish tone for the grid.

**Comment by AlicVB** [comment]
I like c too.

for preview + focus, this is different from the focus peaking with the actual icon : this show big rectangle on focused areas

Now some comments about the 'c' icons themselves (note that I'm very bad in icons drawing) : 
- c2 can eventually show "cropped" rectangle on the left edge too to emphasis on the difference with filemanager
- If I understand well the first icon is "selected", hence the brighter color (maybe too bright), I'm right ?
- more contrast on c2->c5 would be better
- bigger arrows on c3

If you want, I can do the code implementation with "temp" icons, so you can insert them afterward... (or I can help you on the code if you want to do it)

**Comment by quovadit** [comment]
@AlicVB : it would be great, if you could code it with temp-icons - thanks very much!
I will try to improve the c-icons as suggested.
But... I failed running show_icons_in_paint_c.pl and I don't know how to create the cairo image-code
Does it help if I create svg, or should I start learning cairo? (is there a tool?)

**Comment by johnny-bit** [comment]
arght... `dtgtk_cairo_paint_label_flower` causes problems for show_icons_in_paint_c

**Comment by johnny-bit** [comment]
@TurboGit - your change in 6b58bc0 for `paint.c` broke `show_icons_in_paint_c.pl` tool due to referencing `darktable.bauhaus->colorlabels` in `paint.c` code. better way (imo) would be to pass colorlabels as data and fallback to old ones in case data is null. I can try my hand in making a pr...

**Comment by Nilvus** [comment]
Last icons proposal are much better and indeed could be great and better than menu dropdown with those. Based on your answers, I am definitely for something between c and d.

I would see icons as flat as they are on c line but with the more visible border we have on d line. For example, for full screen (so icon 5), icon on line C is better (with the arrows) but would be better I think with black border and black arrows.
And for 1st icon in c line, yes it's too white and I would just put a flat grid but with black borders like on d line.

Last I prefer X Y letters than A B.

**Comment by Nilvus** [comment]
> @TurboGit - your change in [6b58bc0](https://github.com/darktable-org/darktable/commit/6b58bc079e9474291ecaaffdeb974a210a4de3e7) for `paint.c` broke `show_icons_in_paint_c.pl` tool due to referencing `darktable.bauhaus->colorlabels` in `paint.c` code. better way (imo) would be to pass colorlabels as data and fallback to old ones in case data is null. I can try my hand in making a pr...

Is this will keep defined colorlabels with CSS? Commit you point was to set colorlabels with CSS and especially yellow to be more visible on some thumbnails state.

**Comment by johnny-bit** [comment]
@Nilvus - yeah, that's the point ;) just provide some defaults so showiconsinpaint can work without referensing darktable.bauhaus->colorlabels

**Comment by quovadit** [comment]
I tried to consider all comments:
![icons-v2](https://user-images.githubusercontent.com/5677563/103709359-abcc5480-4fb2-11eb-8043-4ec3cd9b3570.png)

First line is inactive, second one is active/mousover

**Comment by TurboGit** [comment]
The first looks fine, but hard to say, it is readable for sure but bigger than what it will be on the UI. So if first not readable enough we can use the second. Great work, this looks really good to me.

**Comment by quovadit** [comment]
here's a 1:1 UI-mockup:
![icons-screen](https://user-images.githubusercontent.com/5677563/103744133-8a448a80-4ffd-11eb-89db-aa5124b3517c.png)

**Comment by johnny-bit** [comment]
@quovadit - as you can see on UI-mockup the icons are ok, but they do stand out too much from other darktable icons.

Below are all icons exported from `paint.c` using `show_icons_in_paint_c.pl` fixed with #7711 :) Please note that all 5 icons would have to be written as paint.c functions 
![show_icons_in_paint_c](https://user-images.githubusercontent.com/10687765/103769016-d86c8480-5023-11eb-837c-773fdda6c577.png)

**Comment by quovadit** [comment]
@johnny-bit : thanks a lot for the icons!

Here are the 5 new icons in darktable-style (compared with 5 original icons I copied from):

![icons-dt-style](https://user-images.githubusercontent.com/5677563/103786185-6eaca480-503c-11eb-9c6a-ce749230c976.png)

As soon as the mockup is agreed on I will do my best do write them as paint.c functions

**Comment by Nilvus** [comment]
> Here are the 5 new icons in darktable-style (compared with 5 original icons I copied from):
> 
> ![icons-dt-style](https://user-images.githubusercontent.com/5677563/103786185-6eaca480-503c-11eb-9c6a-ce749230c976.png)
> 
> As soon as the mockup is agreed on I will do my best do write them as paint.c functions

Style is better but I find some icons less obvious than you're previous mockup. Something between last mockup and that one could be better, except for 1st and last icons that are great for me on that last mockup. Simple and efficient. That's especially the second one that is not clear. Could you do something like the second icon in first line of following screendshot but with thin borders around represented thumbnails? And for icons 3 and four about culling modes, 

> I tried to consider all comments:
> ![icons-v2](https://user-images.githubusercontent.com/5677563/103709359-abcc5480-4fb2-11eb-8043-4ec3cd9b3570.png)
> 
> First line is inactive, second one is active/mousover, on your last mockup, I would use not square icons and try with a letter inside instead of full/not full square. That's more obvious for me like in above screenshot. So, again something above screenshot and last mockup. Hope I'm clear here!

**Comment by quovadit** [comment]
here's the fusion of old+new (first is selected):
![icons-v3](https://user-images.githubusercontent.com/5677563/103948652-6dfa3800-513a-11eb-8cc6-ac934c0fa278.png)

**Comment by TurboGit** [comment]
@quovadit : latest are fine by me.

**Comment by quovadit** [comment]
@AlicVB : I created the icons - see #7762
