### ISSUE TITLE
Can't copy history/history buttons grayed out

### ISSUE THREAD

**Issue by virtualritz** [darktable-org/darktable#5931]
**Describe the bug**
In the attached file I can't copy the history. I.e. the whole panel of `copy...`, `copy all...` `paste...` & `paste all...` are grayed out. Only `compress history` & `discard history` are available. All I did was browse the folder, do the edits, export and close DT.
When I opened it today, I have this issue. Curiously `copy` buttons are available for all other images in that folder which do *not* have any edits (but the default history, ofc.).
[history_stack_issue.zip](https://github.com/darktable-org/darktable/files/5059998/history_stack_issue.zip)

**To Reproduce**
I did not do much editing with 3.2.1. This is the first image I worked on so I dunno how to reproduce this.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: macOS 10.15.6

**Comment by Nilvus** [comment]
Greyed buttons is a new feature, not an issue. Buttons are now displayed contextually. I suggest you, first, to read the 3.2 article that describe that: https://www.darktable.org/2020/08/darktable-3-2/ (see "Dynamic buttons: personalize your actions" part)

**Comment by virtualritz** [comment]
This is not a feature. It makes no sense that the button is disabled here. There is history to copy and an image is selected.

**Comment by Nilvus** [comment]
I said that greyed buttons is a feature. What you describe is not really clear. So if you think it's an issue, please be more precise on steps you made, step by step.

**Comment by Nilvus** [comment]
Just open your image and xmp on darktable and if selected or even when hovering it, I have copy/copy all buttons correctly activated, so I can use them.

**Comment by virtualritz** [comment]
Ok, I found the reason.

I have PNG with same base name in the folder.
So I have
```
foo.png
foo.png.xmp
foo.exr
foo.exr.xmp
```
As shown above: DT *does* create an `XMP` for the `PNG` but *does not* show the PNG in the Lighttable.
For every image that has `EXR` + `PNG` this bug triggers. For every EXR that is alone `Copy` are not grayed out/work as expected.

**Comment by TurboGit** [comment]
@virtualritz : Thanks for finding out what's going wrong, it will help a lot!

@johnny-bit : I suppose there is an issue in the code to check about current selection to activate or not the buttons. Can you have a look at this? TIA.

**Comment by johnny-bit** [comment]
GUI button state reflect the logic that would be checked anyway, so in your case if buttons weren't disabled, clicking on them would do absolutely nothing and you'd be frustrated not knowing why it doesn't work. Instead GUI now shows it won't work ;)

the reason might be in @AlicVB grouping code - basically the logic behind enabling `copy` button is "if selected images count is exactly 1" which is represented by this bit of code:

```c
  const GList *imgs = dt_view_get_images_to_act_on(TRUE, FALSE);
  const guint act_on_cnt = g_list_length((GList *)imgs);
// couple lines later
  gtk_widget_set_sensitive(GTK_WIDGET(d->copy_button), act_on_cnt == 1);
  gtk_widget_set_sensitive(GTK_WIDGET(d->copy_parts_button), act_on_cnt == 1);
```

and in this case the only reason why that would be a problem is if `dt_view_get_images_to_act_on` would return list with more than 1 image on it.

I tried to reproduce it with CR2&JPEG files but I can't, those are simply grouped. I think the EXR + PNG might be some special case here :/ I don't really know what might be the root cause.

**Comment by virtualritz** [comment]
Curiously deleting the `png` and the `png.xmp` does not solve this. somehow DT seems to remember and the buttons stay grayed out.
The only way is really to copy the `exr` and `exr.xmp` to a new folder and open that. Only then can I copy the `exr`'s history.

**Comment by TurboGit** [comment]
I cannot reproduce, tried hard, on my side the buttons are always active when an image is selected.

**Comment by ianhattendorf** [comment]
@johnny-bit I'm running into this issue and noticed it's due to grouping as well. Is there anything that can be done about this? Should this be re-opened as a feature request? Definitely a pain to have to disable grouping and re-find the images you want to copy/paste history for, especially if there are many similar images and you only want to edit the RAW file.

Grouping enabled:
![image](https://user-images.githubusercontent.com/2917725/145111582-79bf3bea-06ec-4462-86e6-00ac3efa7976.png)

Grouping disabled, both images selected:
![image](https://user-images.githubusercontent.com/2917725/145111613-8edeb922-4f17-4794-8057-c38fe858af46.png)

Grouping disabled, one image selected:
![image](https://user-images.githubusercontent.com/2917725/145111637-3206f741-90bf-487f-aa53-564b41dffb39.png)

**Comment by Nilvus** [comment]
> @johnny-bit @TurboGit I'm running into this issue and noticed it's due to grouping as well. Is there anything that can be done about this? Should this be re-opened as a feature request? Definitely a pain to have to disable grouping and re-find the images you want to copy/paste history for, especially if there are many similar images and you only want to edit the RAW file.
> 
> Grouping enabled: ![image](https://user-images.githubusercontent.com/2917725/145111582-79bf3bea-06ec-4462-86e6-00ac3efa7976.png)
> 
> Grouping disabled, both images selected: ![image](https://user-images.githubusercontent.com/2917725/145111613-8edeb922-4f17-4794-8057-c38fe858af46.png)
> 
> Grouping disabled, one image selected: ![image](https://user-images.githubusercontent.com/2917725/145111637-3206f741-90bf-487f-aa53-564b41dffb39.png)

This issue is old and closed, and could also be a different one (even if it's related to same buttons.And you don't precise release you use. This issue is about 3.2.1. We are now in 3.6.1 and 3.8 will be released on Christmas.

Thus, on what you describe, you just don't have buttons enabled to copy when multiple images are selected. It's not an issue. It's not possible for a software to understand from which image to copy history. So it's normal that for copy part, only one image selected is needed to be sure from which one to copy history. Then after a copy, you should have paste enabled even on multiple images selected. If your issue is not that, you need so to precise a detailed step by step. For that, it would be easier, if needed, to post a new issue with a more detailed issue. Thanks.

**Comment by Nilvus** [comment]
Just a thing, when grouping is enabled, and so only one image is displayed, on actual master (future 3.8), buttons are enabled (that not the case in your first screenshot), so maybe issue is fixed. If possible, it would be good before posting a new issue if you can test actual master (or wait for 3.8 to test again if it is fixed or not).

**Comment by ianhattendorf** [comment]
I'm just posting my findings on an existing issue which appears to be relevant, if not it can be moved to a new issue. To me just because an issue is old doesn't mean it isn't relevant anymore.

> And you don't precise release you use

Sorry about that, this was 3.6.1 on Fedora 35

> It's not an issue

Respectfully, I disagree. Seems like the UX could be improved here. Trying to copy history from one RAW file to multiple (think 10+) similar photos is a pain, as you have to (unless I'm missing something):
1. disable image grouping
2. mouse over the two selected images to determine which is the RAW
3. select the raw -> copy
4. individually ctrl + click every RAW image you want to paste, as shift + click will select JPEGs as well
5. re-enable image grouping

when you could just
1. select image to copy -> copy
2. select first image to paste -> shift + click last -> paste

> It's not possible for a software to understand from which image to copy history

Mousing over a grouped image shows the RAW filename in the tooltip, and double-clicking the grouped image opens the RAW image. Seems to me like defaulting to copying history for RAWs in this case makes sense if we're already defaulting to opening RAWs. It doesn't make sense to me to treat grouped images as RAWs for one action but then for another action throw our hands up in failure.

It does appear that copying (from a single selected image) and then pasting on the grouped image correctly handles pasting the history onto the RAW image, while leaving the (selected) JPEG image alone. So at least a work-around would be to disable grouping, copy history from raw, enable grouping, then shift + click to select and paste history. But ideally the two extra steps of disabling and then re-enabling grouping wouldn't be needed at all.

> on actual master (future 3.8), buttons are enabled

master (010cdcdf089fbcab03630b35506d2c95265f74ed):
![image](https://user-images.githubusercontent.com/2917725/145286824-65012dff-1eac-44bb-8da7-5ad573799eaf.png)
