### ISSUE TITLE
db maintenance not working when leaving dt

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#6011]
**Describe the bug**
database maintenance not done...

```
sqlite3 error: /home/obry/dev/builds/darktable/build/src/src/common/database.c:2919, function _dt_database_maintenance(), query "VACUUM data": cannot VACUUM - SQL statements in progress
sqlite3 error: /home/obry/dev/builds/darktable/build/src/src/common/database.c:2921, function _dt_database_maintenance(), query "VACUUM main": cannot VACUUM - SQL statements in progress
sqlite3 error: /home/obry/dev/builds/darktable/build/src/src/common/database.c:2930, function _dt_database_maintenance(), query "VACUUM": cannot VACUUM - SQL statements in progress
```

**To Reproduce**
1. After using dt I got a message when leaving dt to clean the db
2. I accpeted the clean-up
3.  And got the error above

**Expected behavior**
No SQL error expected 

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: Debian

**Comment by johnny-bit** [comment]
This is bad side-effect of tittle-to-none transactions in dt and the existence of error is sole reason for `ERRCHECK` macro. Seems like some query is open and it prevents vacuum from happening. the starting vacuum is "safe" from that since it's basically first op on db, however closing vacuum is prone to problems stemming from open queries :/

Possible workarounds:
- switch to maintenance on start
- start dt and close it without doing anything ;) maintenance will then be able to run (or should be)

possible fixes:
- super easy: remove maintenance on close options 
- sorta easy: for on close maintenance - close db, re-open, vaccuum, continue with closing dt
- super complex: introduce transactions in sql commands across whole dt

:)

**Comment by TurboGit** [comment]
The vacumm did past the second run, so this issue is not that terrible anyway. Note sure what is the better solution... doing nothing at this stage is ok as there is some more pressing issues.

**Comment by TurboGit** [comment]
No big deal here, let's drop this for now.

**Comment by johnny-bit** [comment]
TBH it's good that you pinged this issue. Turns out I was a bit mistaken. Apparently the bug in maintenance can manifest itself when there's a prepared statement or result set dangling. The issue might be caused when there are missing calls to `sqlite3_finalize()` or when statements aren't `sqlite3_step`ped till getting the `SQLITE_DONE` response.

I need to learn more about dangling statements and what can be done about them.

**Comment by johnny-bit** [comment]
Hey @TurboGit - almost exactly 24h later and I have working PR that fixes the issue and helps debug SQL usage in dt even better :) Please check #6220 :)
