### ISSUE TITLE
Lens correction module leaves changed scale when 'only vignetting' selected

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#6033]
This is more enchantment than a bug.

By default, this module changes both distortion and vignetting. However, when "only vignetting" is selected, it leaves the changed scale that needs to be manually reset to 1,000 in order for image to not have changed distortion.

Expected: "only vignetting" should automatically reset scale to 1,000.

**Comment by elstoc** [comment]
Similarly for TCA I suppose (and any of the options that don't include distortion). Seems like a reasonable idea. However we need to be careful as any of the parameters on this module are user-adjustable. So for example, the user could have manually changed the scale, TCA parameters etc. I wonder if we could predictably determine which things to alter automatically taking into account that user interaction.

Note that there is an auto-scale button that will reset the scale back to 1.0 if you click on it after selecting vignetting only. Applying TCA correction seems to set the scale a little higher (1.01 in the images I checked).

**Comment by junkyardsparkle** [comment]
> Applying TCA correction seems to set the scale a little higher (1.01 in the images I checked).

Yes, TCA correction will often induce a small scale adjustment due to the fact that the scale factors applied to the the R or B channel may be <1 and therefore could leave empty edge pixels otherwise. Of course, applying global scaling rather than cropping to prevent this means that the G channel is subject to interpolation when it might not really need to be... but that's another can of worms altogether. :-)

This "enchantment" (actually a very appropriate term for adding more automagic!) might make the most sense as part of a general rethinking of the lens correction module, as discussed in #1990...

**Comment by maboleth** [comment]
Fair enough, I never thought about user changing certain parameters before applying corrections.

But just thinking, if someone chooses 'corrections: only vignetting' (or any other parameter in the list) isn't he or she predetermined to change 'just vignette' rather than previously change all other parameters and then choose which corrections to make?

My logic was:
- The module changes everything automatically based on the lens, by default (as now)
- Then user can choose which correction to use specifically. Picking any on the list would reset all other, non-relevant changes. 
- THEN user can tweak other settings how s/he likes.

**Comment by maboleth** [comment]
Should this be looked on/assigned for the future release or to close it?

**Comment by jenshannoschwalm** [comment]
Just leave it on :-) There is another thing i am working on and this would me having a look into this anyway ...
