### ISSUE TITLE
Add checkboxes to the "store new preset" dialog in the "module order" section

### ISSUE THREAD

**Issue by mrleemon** [darktable-org/darktable#6083]
Unlike modules, the "store new preset" dialog in the "module order" section doesn't have the "auto apply this preset to matching images" and "only show this preset for matching images" checkboxes. Although you can check those checkboxes in the presets tab in the DT preferences dialog, I think it would be very useful to have these two options in the "store new preset" dialog, too.

**dialog for module order:**

![new_preset_module_order](https://user-images.githubusercontent.com/2060659/91060884-cae1cf80-e62b-11ea-8ac7-2e1c55cdbfcd.jpg)

**dialog for color zones:**

![new_preset_color_zones](https://user-images.githubusercontent.com/2060659/91060889-ccab9300-e62b-11ea-8b84-c9ed14f91c62.jpg)

**Comment by matt-maguire** [comment]
So the reason you don't see the auto apply / only show options when creating the "module order" presets is because it has been implemented as a lighttable plugin rather than a darkroom plugin. In general, lightroom plugins are not used in the context of editing a specific image, so they don't have "auto apply", and "only show this preset for a matching image".

I would say that it is more appropriate for the "module order" plugin to be classified under the darkroom plugins, and set it up to use the edit_preset dialogues in iop/presets.c rather than the similarly named one in libs/lib.c.

The preferences plugin allows one to set the "auto apply" and "only show this preset for matching images" for lighttable plugins as well as darkroom plugins. If we talk about darkroom plugins, they are obviously matching the image being edited in darkroom, but for a lighttable plugin, which image would you match it against? There may be zero, one or more images selected in lighttable. So, I'm a bit doubtfull whether setting the auto_apply on a preset for "module order" plugin will have the intended effect.

So, my thoughts:
- we should make the "module order" plugin a darkroom plugin.
- for lighttable plugins, it may make sense to set "only show this preset for a matching image" for some plugins, such as the export plugin, and in this case I guess all the images selected on lighttable should meet the match criteria.
- for lighttable plugins, I think "auto_apply preset" would only make sense for something like the metadata editor, and the auto apply would be dome at time of import. But the import plugin already provides that functionality, so I don't see any use case for auto_apply for lightroom plugins.
- The preferences pane doesn't distinguish between lighttable and darkroom plugins when editing presets, which I think is a mistake based on the above remarks. This could cause confusion for users, and so the preferences pane should probably not present, or present in greyed out format, the buttons for image matching when editing a lighttable plugin preset.

**Comment by johnny-bit** [comment]
@AlicVB - I'm looking at issue #6083 and in the context of your PR #8502 - would it make sense to show if lib is capable of respecting autoapply and only show autoapply fields for those that are?

**Comment by AlicVB** [comment]
yes, I agree, that would be useful here.
with #8502 that should be very easy to implement :)

We even can think about a different default module order for some type of image. jpeg for example...

**Comment by johnny-bit** [comment]
I think that just not showing the "auto apply" checkbox for those libs that don't support auto apply would be enough to "fix" this FR :)

but i leave the decision to you. I took just a brief look at the code and thought that for me it's not "very easy" (maybe not yet).
