### ISSUE TITLE
[Dev 3.3.0-xxx Vignette] The vignette default mask/circles persist across modules and images

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6090]
Vignette masks present when a preset from a another module is applied.

Edit an image, select and enable vignette module.
The vignette circle masks get displayed.
The vignette module is still in the expanded state.

Now scroll to a different module and apply the preset from the 3 horizontal lines. The preset gets applied but the vignette modules circular mask is still present. It's as if the active module did not change.

This gets worse, now go to lightable and select a different image collection and double click an image from it. This image opens in darkroom with the vignette circle mask on it.

I have, expand single module at a time enabled for darkroom preferences.

this is darktable 3.3.0+337~g53e333a11 (windows)
compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by chhil** [comment]
Tested it and it works.

**Comment by AlicVB** [comment]
I've found this bug via git blame when trying to solve #9296 and #9264 
In fact I think that what the @chhil describe here is the correct behavior : applying a preset to a module via the menu or via shortcuts, without unfolding the module, doesn't have to put the focus on the module itself.
Otherwise, it make workflow harder, esp. when applying preset with a shortcut...

So it's quite normal imo : 
1. you have the focus into the vignetting module => you see the round overlay
2. you apply a preset to whatever other module without expanding it => the focus stay on vignetting => you see the round overlay
3. you go to lighttable and back to darkroom with another image. darkroom put the focus on the last focused module == vignetting => you see the round overlay

I've proposed a PR to revert the fix merged here and fix the other issues
