### ISSUE TITLE
Module UI elements stay activated when not enabled (v3.2.1)

### ISSUE THREAD

**Issue by Martin2112** [darktable-org/darktable#6169]
**Describe the bug**
I've been using crop and rotate and gradient density modules and I've been seeing their UI elements appearing on images where they're not activated. This has led to some strange behaviour with crop & rotate where the boundary I drew for one image appears on others and is hard to remove. I don't remember seeing it in previous versions.

**To Reproduce**
1. Turn on gradient density for an image, drag the line to the correct place
2. Restart darktable
3. Select an image where gradient density is not enabled

**Expected behavior**
Not seeing the gradient density line as the module is off but it sometimes appears

**Screenshots**

![dtgradoff](https://user-images.githubusercontent.com/13366863/91831338-db053a80-ec3b-11ea-97f7-2b751a974ab4.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10
 - OpenCL on
 - NVidia 1070, latest driver as of today

**Additional context**

**Comment by elstoc** [comment]
This is because the module has focus (the slightly brighter header text and the slight fill behind the module on/off button indicate this). If you notice when you expand either crop&rotate or graduated density modules, they don't become enabled but the on-image guides appear nonetheless - only when you actually modify one of these guides does the module become enabled. When you switch between modules I believe darktable tries to keep the same module in focus and this means that the on-image guides appear again. This _can_ be useful if you're cropping images in bulk.

So I guess it's probably working as designed. If you want to remove focus without expanding the module you can Ctrl+click on the on/off button.

**Comment by Martin2112** [comment]
OK, thanks. It possibly is WAI but I don't remember seeing this before. It's quite fiddly with crop & rotate. At least I know how to hide it now.

I can see why this is useful in the case you described but it's also a bit counter intuitive to me that a module I haven't interacted with during a session is showing its controls

**Comment by johnny-bit** [comment]
working as desinged - optimize workflow, leave most recently used module in focus, remember focus across sessions... Kinda cool ;)

the icon is big indicator that module despite being "off" is indeed having focus. similarly to unchecked checkbox having focus - it isn't checked but you can operate on it :)

**Comment by Martin2112** [comment]
Right, seems to not be a bug then. Not sure if the persistence across sessions is a new thing.

I'll close it as WAI.
