### ISSUE TITLE
Nikon Z5

### ISSUE THREAD

**Issue by Kaens** [darktable-org/darktable#6173]
Dropped a bunch of varied raws to https://raw.pixls.us/ ; can't see them in the repo but I guess it's moderated, I'm new here.
Ready to provide further info if needed.

**Comment by LebedevRI** [comment]
Thank you for the contribution!

**Comment by LebedevRI** [comment]
So i wanted to finally do this (sorry, got really side-tracked, sorry!),
and while it works, i'm unable to produce the most high-quality support.
As it is stated on RPU, the samples really really need to be well-lit (thus low ISO),
of something like daylight landscape. This is is really important, because i need
to manually fine-tune the crop size, and for that the pixels need to be discernable,
and not a jumbled noisy mess..

So i'm ready to push the support as soon as good samples are re-apploaded to RPU.

**Comment by ponceto** [comment]
Hi.

Sadly, I'm not a owner of a Z5, but I'm waiting the Z5 support in darktable to buy one.

But you can find some samples on some sites/blogs like this one : 

- https://www.photographyblog.com/previews/nikon_z5_photos

Are these samples ok for your validation process ?

**Comment by LebedevRI** [comment]
RPU exists specifically to avoid the need of having to find samples
from various cameras on different sites, with questionable legality.

**Comment by CiroZorro** [comment]
I have uploaded some pictures I took last weekend with a Z5 we rented, I unfortunately don't have the camera anymore or I would have tried to get some nice bright landscapes. I am in ABQ and it is sunny so I chose a few of the better ones without people(or minimal people) and ISO 100. I notice no support or work in dark table so I am hopeful this will assist in getting these images to work.

**Comment by matt-maguire** [comment]
I extracted the black and white points and standard color matrix from your samples using DNG converter 12.4.0.555 on macOS. I create darktable PR #6529 and rawspeed PR #243, so with any luck basic support may find its way into the next release of darktable.
