### ISSUE TITLE
new shortcut requests

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#6175]
I'm requesting more default shortcut, I find them essential for my work.

All of them are about `image operations - _some module_ - show module`

- shift-C (or shift-R) -> crop and rotate
- shift-P -> perspective correction
- shift-W -> white balance
- shift-E -> exposure

**Comment by TurboGit** [comment]
Well, I'm not sure it is wise because people may have another set of modules, some people may have already set those presets for other means and the translated modules may need to use another letter. In French "white balance" is "balance des blancs" I don't think using Shift-W is good then.

Better letting people define their own shorcuts.
