### ISSUE TITLE
Parrot Anafi (Drone) lens correction

### ISSUE THREAD

**Issue by OUARZA** [darktable-org/darktable#6182]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by johnny-bit** [comment]
Your issue has issues ;) have you uploaded samples to raw.pixls.us?

**Comment by LebedevRI** [comment]
The raws seem to load fine.
What is the problem?

**Comment by OUARZA** [comment]
> Your issue has issues ;) have you uploaded samples to raw.pixls.us?
Yes, about 3 hours ago.

> The raws seem to load fine.
> What is the problem?
I would like an image correction for this lens for Darktable.

**Comment by johnny-bit** [comment]
>>Your issue has issues ;) have you uploaded samples to raw.pixls.us?
> Yes, about 3 hours ago.

I meant that you haven't filled it properly ;) it looks like default template with nothing added.

> I would like an image correction for this lens for Darktable.

You mean lens correction? it's different ting!

check https://github.com/darktable-org/darktable/wiki/Camera-support#lens-correction (a part of https://github.com/darktable-org/darktable/wiki/Camera-support)

some people already made correction profiles for some drones, see:
https://mavicpilots.com/threads/mavic-2-zoom-lensfun-calibration-for-darktable-3-etc.88875/

If you could send the data to lensfun guys too it would be great because it would be used not only by darktable but also by all other projects using lensfun.

**Comment by OUARZA** [comment]
I'm sorry, I'm not very good at English. 
In Darktable, my drone lens is not referenced to correct for distortion. 
My drone is not a Mavic but an Anafi from Parrot (lens from Sony).
I will look at the different links. Thanks for your help.

**Comment by OUARZA** [comment]
hello,
what should I do to have my request taken into account?
 thanks in advance.

**Comment by johnny-bit** [comment]
Look for your calibration request here: https://github.com/lensfun/lensfun/issues

**Comment by johnny-bit** [comment]
As lens correction depends on lensfun (therefore upstream) and will be picked automagically once such correction is available in lensfun db there is nothing more we need to do here.

The raws themselves open just fine.
