### ISSUE TITLE
Default modules applied on top of copied history stack

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#6186]
**Describe the bug**
In dt 3.3.0+199~gc8474d8f9, when I copy a history stack on an untouched image I get my default modules applied on top of the copied stack. If I touch the image before, so that the default modules are applied and I paste (append mode) the history stack on the image I get the correct behavior. Also in the official release (3.2.1) the default modules are not applied on top.

**To Reproduce**
1. Create a setting for a module (e.g. Exposure EV = +1.0) and auto-apply to your images
2. Edit an image and change the exposure to EV = 0.0
3. Copy-paste your history stack to another image that is untouched
4. Open the image and see that the current EV = +1.0

**Expected behavior**
I expect that the default modules would be applied first and the history stack copied on top and not the other way round and how 3.2.1 works.

**Screenshots**
Can provide if needed.

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+199~gc8474d8f9
 - OS: Win10-64

**Additional context**
 - Cannot be reproduced with another version 3.2.1
 - Problem exists only with fresh edits (no history stack)
 - dt 3.3 was compiled on Mingw-64 with gcc10.2 with standard build file

[Corrected typo in step 4]

**Comment by TurboGit** [comment]
Your step 4 above looks correct but seems to contradict the description of the bug. Can you clarify ?

**Comment by juhavlintula** [comment]
Sorry, typo. Should have been EV = +1.0

**Comment by elstoc** [comment]
Easy way to reproduce with scene-referred workflow enabled.

1. Import an image (or discard its history stack)
2. Go into the darkroom and increase the exposure
3. Exit back to the lighttable
4. Duplicate the image and discard the stack on the duplicate
5. Copy the history from the edited image to the duplicate

They should be identical and they are not (because the exposure default is applied after the increased exposure and therefore overrides it back to its default setting).

Anyway the above PR should resolve it.
