### ISSUE TITLE
Open recent images.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#6194]
This is a feature request.
A search engine for images that have been recently worked and don't have to browse the catalog, something like a history of recent worked images, which of course is customizable with a certain quantity of images was opened, like other software do. This parameter could be placed into the darktable preferences window, lighttable configuration as "quantity of images to show".

![open_recent_images](https://user-images.githubusercontent.com/67672868/92205342-791f1d80-ee53-11ea-866a-837404f7e55d.jpg)

**Comment by Nilvus** [comment]
And what about if we import hundreds (or thousands) images at once? We had, since 3.2.1, a new filter in collect images called import timestamp, that allow same things by selecting date (so more powerful as we can select last import date but also quite older ones).

**Comment by pitbuster** [comment]
@Nilvus that would work in the case of recently imported images, but I think the request is for recently worked images, which could be older that the latest imported ones.

**Comment by Nilvus** [comment]
@pitbuster: so change timestamp is the filter to use. I suggest to read 3.2 article in darktable.org/blog, all new filters are described.

**Comment by difrkaguilar** [comment]
I create this because as many people I work some images from different sources, cameras, dates and so on, and I'll like to have at hand a place to select and open the images I had been working last day for instance. Software like Gimp even have a history of recently open (worked) images.

**Comment by ptilopteri** [comment]
a directory sort by date on xml files will provide you what you desire

**Comment by sergei18500** [comment]
Hello,
By using the following procedure you have a method that meets your needs:
- Collect images
(select) change timestamp
(enter for example ) >= 2020:08
you have all your images modified since the beginning of August.
You can refine by choosing the day, >2020:08:15
This search will be found afterwards in 'Recently used collections'.

**Comment by Nilvus** [comment]
> I create this because as many people I work some images from different sources, cameras, dates and so on, and I'll like to have at hand a place to select and open the images I had been working last day for instance. Software like Gimp even have a history of recently open (worked) images.

As I said and @sergei18500 too, check change timestamp filter in collect images. It suits your needs.

**Comment by difrkaguilar** [comment]
Sorry if I don't be agree with your opinions. The request is about something so easy that almost every software have. A simple thing as a history of last open files.
This software is indeed brained by Photographers for photographers, not for people with advanced skills in computer, or geeks.
The best way to reach more public is to make more affordable the app to users.
As I talk sa Gimp do, for instance the last 15 images recently worked. And not to browse the catalog by search criteria, timestamps and so on.

**Comment by TurboGit** [comment]
Well recent images by name is certainly not something that will help people. Look at your proposed GUI... The names are not meaningful I really don't see the point.

Maybe some other software have this (like Gimp) because they don't have a lightttable! Here you can see your last collection visually and sorting by changed stamps you have a visual of last image that have been touched. To me darktable does a better job already.
