### ISSUE TITLE
Preserve luminance option for color balance module

### ISSUE THREAD

**Issue by age1988** [darktable-org/darktable#6209]
A simple button to toggle on/off luminance preservation in the color balance module

**Comment by matt-maguire** [comment]
Not quite sure what you are aiming at here. In the default HSL mode, you can leave the factor sliders at zero while you adjust the hue and saturation sliders separately. Is this about normalising the RGB coefficients when in RGB mode? Perhaps you can explain a bit about what is the problem you are trying to solve here?

**Comment by age1988** [comment]
Using the rgb mode should be really in rgb, for example moving all the r+g+b offset slider to the right is a no-op with the actual behaviour, there's a luminance preservation under the hood

**Comment by matt-maguire** [comment]
Looking at the Primaries Wheels in Davinci Resolve, it looks like by default they behave in a similar way to the current color balance module in darktable, where the adjustments to the RGB sliders tries to keep the luminance effect of the sliders neutral, and it is left to the "factor" slider to control the overall intensity of the effect.

It sounds like what this feature requiest is asking is similar to what happens in Da Vinci resolve if you set the "Lum Mix" to zero. Then, adjusting the RGB sliders will implicitly affect the factor slider as well, since the RGB sliders are no longer nomalised in the luma dimension.

So far it doesn't doesn't look like any of the dev team have picked this up.

**Comment by Nilvus** [comment]
As this module will be replaced by a whole new color balance rgb module which will allow to have better settings and way way better results, color balance module should not have any new option. The new color balance rgb module will be the new to use instead (highly recommended). It will be in the new 3.6 release, which will be out in about 2 weeks. I so close this one.
