### ISSUE TITLE
Clamp values module RGB and LAB

### ISSUE THREAD

**Issue by age1988** [darktable-org/darktable#6210]
It could be useful, related to #4843

**Comment by matt-maguire** [comment]
Could you please elaborate what are the specific use cases where this is required?

**Comment by johnny-bit** [comment]
It's essentially useless to do that and goes against philosophy on unbounded color operations. If any module expects bound data, then algorithm isn't resilient enough or is oldschool with loads of assumptions baked in which is no good at all. This also could lead to invalid data with large dynamic range sensors and adjusting it. 

The only technically correct assumption might be regarding negative values since "there's no negative light", but then negative numbers are still a valid mathematical concept and dealing with them is part of algo life.

**Comment by johnny-bit** [comment]
I'm going to close this now - If you believe such module is required, feel free to ping me and I'll reopen.

darktable is moving toward unbounded pipeline, meaning that anything between input and output is never clipped and at last stages everything is maped to output medium. This has downside of not working great for algos with assumptions about values being bounded, but then we'd rather have more robust algos than loose values :)
