### ISSUE TITLE
History stack just disappears

### ISSUE THREAD

**Issue by 8606DesignStudio** [darktable-org/darktable#6248]
**Describe the bug**
Program discards my history stack anytime I click out of Darkroom to Lighttable making the program pretty much useless. 

**To Reproduce**
Edit in Darkroom, click out to lighttable. Click back into darkroom. 
-->

**Expected behavior**
Image reverts to original. 

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: windows 10 64 bit
 -  Idk
 -  None. Stock 2012 Ideapad Yoga

**Additional context**

**Comment by TurboGit** [comment]
You are the first to report such issue so probably a problem on your side.

I would check the permissions on the databases library.db and data.db. On Windows everything can happen... If you have an antivirus disable it or remove it, it serves nothing except doing stupid things.

**Comment by 8606DesignStudio** [comment]
ok I'll try that

**Comment by johnny-bit** [comment]
Since @8606DesignStudio - since you haven't replied it seems that issue didn't reappear, right? If darktable dropped history every time you got back and forth between lighttable and darkroom it would be quite useless... I'm closing this for now - please ping me if you stll have problems and I'll reopen the issue.
