### ISSUE TITLE
Olympus E-M5 Mark 3: lens correction scale not working correctly

### ISSUE THREAD

**Issue by DD8372812** [darktable-org/darktable#6279]
**Describe the bug**
This bug is related to the Olympus E-M5 Mark 3 and the Darktable module lens correction. The scale option is not set correctly.

**To Reproduce**
Import new photos and turn on lens correction module. Camera and lens are identified correctly, also mm and f, d and distance. But scale is still set wrongly to 1,000. It should be accordingly to the values e.g. 1,09. A click on auto scale will set this value to 1,09 correctly.

**Expected behavior**
With Olympus E-M5 Mark 1 and same lens (Olympus M.Zuiko Digital ED 12-40mm f/2.8 Pro) this value is set correctly to 1,09 without clicking on auto scale.

If I am not wrong I need to click in every photo on auto scale for workaround. Or is there some better automatic workaround?

**Tested on**
 - Darktable Version: 3.2.1
 - OS: Windows 10 and Linux Mint 20 Cinnamon with up to date lensfun lib

**Comment by johnny-bit** [comment]
You can create preset with that params and auto apply it to matching  camera/lens. As for root cause: does lensfun know about both your camera and lens? seems like if it knows it should work....

**Comment by ptilopteri** [comment]
open an image in darkroom view
right panel below histogram, see search module and enter scale
"scale pixels" will appear
select the right side three horizontal lines and
"store new preset"
fill in your choice for the top, "Label"
and second "description"
select "auto apply ..."
and enter the parameters that will distinguish the body which doesn't present
the correct scale and what scale you want.

now when you open an image the scale you prefer will be automagically applied.

**Comment by DD8372812** [comment]
> You can create preset with that params and auto apply it to matching camera/lens. As for root cause: does lensfun know about both your camera and lens? seems like if it knows it should work....

Preset does not work because of the scale problem. It will Lthen also not touch the scale value and leave it to 1,000 .
Yes, camera and lens are identified correctly.

**Comment by DD8372812** [comment]
> open an image in darkroom view
> right panel below histogram, see search module and enter scale
> "scale pixels" will appear
> select the right side three horizontal lines and
> "store new preset"
> fill in your choice for the top, "Label"
> and second "description"
> select "auto apply ..."
> and enter the parameters that will distinguish the body which doesn't present
> the correct scale and what scale you want.
> 
> now when you open an image the scale you prefer will be automagically applied.

I can't turn on this module because "automatic pixel scaling only works for the sensors that need it"

**Comment by junkyardsparkle** [comment]
> I can't turn on this module because "automatic pixel scaling only works for the sensors that need it"

You don't need to touch that module, I promise. :-)

First thing to point out is that the scale factor isn't a property of the camera or lens profiles, it's something that darktable calculates in the process of applying correction, with the intention of showing the largest possible rectangle at the original aspect ratio without any "empty" black pixels appearing at the edges or corners. This means that you don't want to hard code it into a preset, because it will be different for different focal lengths on a zoom lens (corrections can be very different, even opposite, at each end of the zoom range).

That said, I can reproduce the behavior you describe with the normal RAW downloaded [here](https://www.imaging-resource.com/PRODS/olympus-e-m5-iii/EM5M3hSLI00200NR0.ORF.HTM) (had to make a "dummy" profile for that lens). The scale factor gets adjusted when making a manual lens selection, or when clicking the autoscale, but not upon module init for some reason. Seems to be a legitimate bug, but I have no guesses about why it's happening...

**Comment by DD8372812** [comment]
Hello junkyardsparkle,

thanks for your answer.

For now I do not know what I can do for the bug fixing. Maybe someone else is able to understand what's happening.

**Comment by DD8372812** [comment]
Are there any other E-M5 Mark 3 user having this issue, too?

**Comment by junkyardsparkle** [comment]
Sorry, I meant to get back to this sooner. After some head scratching, it turns out that this camera was added to the lensfun database with an incorrect (probably copy/pasted) maker name ("Olympus Imaging Corp". vs "Olympus Corporation"). I have no idea why this would cause this particular issue, but it does. Updating lensfun database should fix it for you. Thanks for reporting, please close this issue when you get a chance.

**Comment by DD8372812** [comment]
Great, thanks a lot for the fix. After the lensfun update everything's fine again!
