### ISSUE TITLE
color picker module automatically changes to "area" mode

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#6282]
Open and expand the color picker module. Defaults to my last selected option "point":

![Screenshot_2020-09-12_22-43-10](https://user-images.githubusercontent.com/9555491/93005541-d862e900-f549-11ea-9feb-525b5b74f52b.png)

Click on the color picker icon. Option changes to "area":

![Screenshot_2020-09-12_22-44-24](https://user-images.githubusercontent.com/9555491/93005551-e9135f00-f549-11ea-9af6-ee629d72dfbe.png)

Same thing happens if I disable the picker, change it back to "point" and then re-enable the picker.

The only way to get to point mode is to enable the picker and then change it in the drop-down while the picker is enabled.

Also (possibly unrelated) it used to be possible to change the active color picker in an IOP module from point to area mode using this module (and the documentation states that it should) but this seems to no longer be possible.

**Comment by elstoc** [comment]
@dterrahe?

**Comment by dterrahe** [comment]
I'll have a look at both of these today; thanks for flagging!

**Comment by dterrahe** [comment]
If I revert part of #5072 then the first part works again (i.e. selecting point/area and then clicking picker button enables the selected size). This must have been broken since May, but I haven't seen any bugreports. Alternatively, the selection of point/area could be based on whether CTRL was pressed when the button was clicked, as it is elsewhere. Of course that wouldn't give the second feature you (and the manual) mention.

Changing the size of a currently active colorpicker doesn't work even if I revert #5072. It may have been broken by my earlier color picker work, but the debugger tells me that changing that combobox eventually results in temperature.c/gui_update switching off all colorpickers and _that_ change went back to 2 years ago. If anybody still has a (running; mine broke from library changes) 3.0 or something, maybe they can confirm if it still worked then.

All of this tells me this module might not be very actively used. It may not be the most intuitive. And certainly the code isn't the easiest to grasp. So while I'm happy to submit a PR that partially reverts #5072 (the main goal it had was to make this color picker switch off when any other color picker, in one of the iop modules, was used; I don't know another easy way to achieve that) I'm thinking that maybe this module could use some redesign.

So what I'd prefer to do, is to change the color picker type from DT_COLOR_PICKER_AREA to DT_COLOR_PICKER_POINT_AREA. This would allow the CTRL key to be used to decide between the two. That would leave the size combobox doing nothing useful so it could be removed (a nice spot needs to be found for the picker button...). The size of colorpickers elsewhere can similarly be detemined by the CTRL key. This is already possible with some separate color picker buttons that have DT_COLOR_PICKER_POINT_AREA, but the quad based picker only have supported this flag since recently. They used to not be able to determine if CTRL was held because they didn't receive an _event_ to read that information from, but there's now a separate utility function. Maybe this could be generalised so that _AREA or _POINT are only the defaults but can _always_ be overridden by holding CTRL. Clearly, that shouldn't break anything because the colorpicker library module could always do this behind the IOP module's back anyway.

If you _are_ interested in a significant redesign of the library module, then maybe the need for a separate mean/min/max and rgb/lab combo just for the _add_ functionality could be reevaluated.  I'd say having the add button use the current setting is sufficient+efficient+intuitive. And moving the picked color numbers _below_ the color box would allow the module to be narrower.

**Comment by elstoc** [comment]
Honestly I don't use this lib module very much. I was just curious, having read the manual again, whether it still worked, knowing that it had been redesigned. Now that most color pickers use _Ctrl+click_ to set area mode I don't think there's any need to be able to alter the mode of an IOP color picker with this module.

I think the first bug (the fact that point/area mode isn't selected consistently) is the more important and I'm not bothered whether you keep the point/area combobox or just have the colorpicker use the same standard as the rest of the application (click to select point, ctrl+click to select area).

**Comment by GrahamByrnes** [comment]
I use it occasionally to check for sanity vs weirdness. The thing is, failing to preserve point vs area mode is one of those things where I'd just shrug, wonder what happened, and carry on, so lack of notification there might not mean it's not used. It probably does mean it's not used every day.
The proposed changes seem sensible to me, however.

**Comment by TurboGit** [comment]
> So what I'd prefer to do, is to change the color picker type from DT_COLOR_PICKER_AREA to DT_COLOR_PICKER_POINT_AREA. This would allow the CTRL key to be used to decide between the two.

I suppose this is a good option indeed. We can remove the point vs combo indeed and place the min/max/mean instead gaining one line in this module.

**Comment by dterrahe** [comment]
So I was thinking of simplifying it somewhat further. Very rough mock-up done in a few minutes (spacing etc would need a lot of polish):
![image](https://user-images.githubusercontent.com/1549490/93110362-1e848d80-f6ad-11ea-86cb-f40ea2e80f90.png)

In that case I'd like to take a little more time to clean up the module, remove dead/redundant code, make the max height adjustable with ctrl-scroll like other modules etc.

If this looks like a good idea, I'll add it to my list of mini projects.

**Comment by TurboGit** [comment]
Whaou!!! Looks really nice now.

**Comment by johnny-bit** [comment]
> So I was thinking of simplifying it somewhat further. Very rough mock-up done in a few minutes (spacing etc would need a lot of polish)

Yes, please!
