### ISSUE TITLE
Parametric mask color picker doesn't stay visible when changing the parametric slider

### ISSUE THREAD

**Issue by paperdigits** [darktable-org/darktable#6285]
**Describe the bug**
When using the color picker in the parametric mask portion of the gui, if a color is picked, then the parametric slider is adjusted, the color picker marker disappears.

This happens with all modules, but I'll use the Tone Curve in the example below.

**To Reproduce**
1. In darkroom mode, enable the Tone Curve.
2. Enable the parametric mask.
3. Use the parametric mask color picker to pick a color in the image. An indicator is shown on the slider
![image](https://user-images.githubusercontent.com/71795/93008909-3b935200-f52f-11ea-9dbe-49eac6fc4c41.png)
4. Move the parametric mask slider. The indicator disappears.

**Expected behavior**
The indicator should remain visible as the parametric mask slider moves.

**Screenshots**

The arrow points to the visible marker:
![image](https://user-images.githubusercontent.com/71795/93008909-3b935200-f52f-11ea-9dbe-49eac6fc4c41.png)

The indicator disappears:
![image](https://user-images.githubusercontent.com/71795/93008959-fb809f00-f52f-11ea-8a18-742bb7c03bc3.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Flatpak and NixOS 20.03
 - OpenCL not activated

**Additional context**
Was not present in 2.6.2, did not notice if worked in 3.0.2 or not.

**Comment by matt-maguire** [comment]
This issue seems specific to 3.2.x, I don't see it happening in 3.0.2 or in the latest master (3.3.0+650~g428b3f35c)

**Comment by elstoc** [comment]
Agreed. This seems fine in current master. The only thing that may be useful is: when you use the right-hand picker to set the sliders and then subsequently alter a slider manually, the picker on the left should be highlighted instead (since the slider range no longer represents the selected area but the rectangles range is still shown on the sliders).

**Comment by dterrahe** [comment]
On the other hand, since the selection picker is still active, you can now select the range for the other slider (by holding CTRL while selecting a range) without having to reselect the right picker. I think there are pros and cons for each approach (keeping the selection picker active does make it easier to accidentally lose your adjustments. not that big a deal imo and you'll learn quickly enough), so not really worth the hassle of trying to make the switchover work between two, at the moment fully independent, pickers.

**Comment by elstoc** [comment]
Makes sense. You've persuaded me.

**Comment by paperdigits** [comment]
Yes that's fair. Closing, thanks folks.
