### ISSUE TITLE
Basecurve and Sharpen applied although "scene referred" workflow is activated

### ISSUE THREAD

**Issue by Macchiato17** [darktable-org/darktable#6287]
**Describe the bug**
The modules "basecurve" and "sharpen" are applied to a freshly imported RAW file (here Nikon), even though "scene-referred" workflow is activated (see screenshot "settings") and auto-apply basecurve and auto-apply sharpen is set inactive. No presets exist that would auto-apply these modules.
It seems as if this issue depends on a sidecar being available when importing the RAW first time into digikam. 

**To Reproduce**
I narrowed this down to the "conclusion" that the issue seems to occur as soon as a sidecar was written by Digikam for the RAW file we want to import into digikam, e.g. by applying a rating, adding tags or similar.

- if the RAW file was **not** e.g. rated in Digikam prior to import in darktable (and thus the RAW file has **no side-car file** written by Digikam at the time of import), everything works fine: only the expected modules are auto-applied in darktable. See screenshot "notRatedInDigikamBeforeImportToDarktable.png"
- if the RAW file was e.g. rated in Digikam (and thus **has a side-car file** written by Digikam at the time of import), then besides filmic, also basecurve and sharpen are applied, exposure is missing in this case. See screenshot "ratedInDigikamBeforeImportToDarktable.png"

**Expected behavior**
The desired modules should be applied during import independent from a side-car file being there or not.

**Screenshots**
notRatedInDigikamBeforeImportToDarktable.png
![grafik](https://user-images.githubusercontent.com/58610057/93021823-490b1380-f5e5-11ea-8193-e026a95d8922.png)
ratedInDigikamBeforeImportToDarktable.png
![grafik](https://user-images.githubusercontent.com/58610057/93021829-52947b80-f5e5-11ea-88b2-4f70da3f4545.png)
settings.png
![grafik](https://user-images.githubusercontent.com/58610057/93021854-7fe12980-f5e5-11ea-9881-49f7b11df3a5.png)

**Additional information**
When choosing "discard history" in lighttable for the incorrect processed image, and then changing back to darktable again, the settings are applied correctly. 

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1 (current, official installer)
 - Digikam Version: 7.0.0 (current, official installer)
 - Windows 10 x64 pro (1909)

**Comment by matt-maguire** [comment]
Some remarks:
- when you change the setting to "scene-referred workflow" and/or change the auto-apply basecurve/sharpening options just below it, you need to restart darktable for those new settings to take effect.
- You make mention of Digikam -- is this just a typing mistake? Do you really mean to type "darktable"?

It is true that once an XMP file is created, the workflow is set inside that XMP file, and any subsequent attempts to open the image in darkroom will keep using that original workflow. As you remark, if you reset the history, either my doing "discard history" in lighttable, or is darkroom by selecting the bottom "original image" item in the history stack and hitting the "compress history stack" button, this will then set up the image to use the new workflow specified in the darkroom preferences.

If you are using Digikam to create an XMP file before importing the image into darktable, then it is up to digikam what it decides to write to that XMP file, and darktable will merely follow what Digikam already populated in that XMP file. in that case, you should raise a feature request on Digikam so that the user can specify whether Digikam should create an XMP file using the scene-referred or display-referred workflow. Otherwise, the easiest thing it to use the "comress history stack" trick in darkroom to  tell darktable to set up the new scene-referred workflow for that image. This will not destroy any ratings or tags that may have been set up in Digikam or lighttable.

Does this help at all?

**Comment by Macchiato17** [comment]
Hi Matt,

thanks for your quick reply. First of all, sorry there was indeed a typo from my side: 
> It seems as if this issue depends on a sidecar being available when importing the RAW first time into **digikam**.

should read 

> It seems as if this issue depends on a sidecar being available when importing the RAW first time into **darktable**.

But I think this was the obvious part ;-). Since I changed those settings directly after installation of the latest darktable version some weeks ago, this should be safe.

My RAW workflow is as follows:
 - I completely manage my pictures with Digikam 
 - RAW file processing is done only in darktable. This includes exporting to JPG.
 - After the JPG export, I remove the imported pictures from darktable.
 - The album folder then is refreshed in Digikam 
 - Now the "round trip" finished.
Following this workflow, I first open the RAW files in Digikam, rate and tag the picture for the further processing in darktable. Digikam writes the sidecar file in this step. There is no darktable related information at all included in the sidecar files at this point-in-time. I think it won't be much of help to ask the Digikam developers to include darktable specific XML in their export.

From darktable's point of view, there will be neither a display- nor a scene-referred workflow available in the sidecar, when the picture is imported. Therefore I would expect darktable to take over the information available (like the rating and tags) and set up the workflow as defined in the application settings and add this to the sidecar. 

Would you agree to my expectation?

Cheers & greetings to down-under :-),
Lars.

**Comment by matt-maguire** [comment]
Ok, I think I understand what you are trying to do. I don't have any experience with digikam, so I'll need to check out what it is doing with the XMP files and how it interects with darktable's XMP logic, in order to work out what may be the best way to proceed. Thanks for the clarification.

**Comment by matt-maguire** [comment]
So, I managed to download and build digikam 7.0.0 on my linux system, and I was able to reproduce the behaviour you report in this ticket with darktable 3.2.1. I tried using the latest dev version of darktable (3.3.0+749~gfb177d9c5) and now for the images with XMP generated by digikam, we get filmic instead of basecurve, but we incorrectly get sharpen still being applied, and we are missing the exposure module. The images that didn't have an XMP from digikam were set up correctly with filmic+exposure and no sharpen. This does seem to be an error in the darktable import logic, so I'll dig around a little further.

**Comment by jenshannoschwalm** [comment]
I think the xmp tags might not be correctly interpreted, dt xmp tags include a blob defining the modules parameters and digikam very likely doesn't know how to do that. Some tags are somewhat correctly read for lightroom. That might be the place/way to find out.

**Comment by matt-maguire** [comment]
@jenshannoschwalm it's not that, the problem is that if darktable sees an XMP file that doesn't contain any darktable tags at all, it wrongly assumes it is a legacy XMP and so it auto-applies the display-referred presets (ie. sharpen) instead of properly checking whether scene-referred presets (ie. exposure) should be applied. If an XMP has never been imported into darktable before, it should be treated as a fresh image with no legacy history, not assumed to be an image with a legacy workflow.

I raised a PR to check for this and set the "legacy" flag appropriately.

**Comment by Macchiato17** [comment]
Thank you all for your effort to improve this workflow. I'm really looking forward to the next release of this fine piece of software :-)
