### ISSUE TITLE
Geotagging: wrong number of images with grouped images

### ISSUE THREAD

**Issue by jonas-ott** [darktable-org/darktable#6306]
If you geotag some images Darktable reports how many images were tagged. But if you have grouped some images and those are collapsed, the collapsed Images are geotagged but not counted. So you think not all images were geotagged, but actually, they are. 

**Steps to Reproduce** 
1. Group some images
2. collapse grouped images
4. Select all
3. Apply GPX File
4. Compare the number of actually geotagged images and the number Darktable reports

**Comment by Nilvus** [comment]
This is updated when you quit map and change filter collections. @phweyland: is this could be linked to your last #6303 PR?

**Comment by jonas-ott** [comment]
> This is updated when you quit map and change filter collections.

To clarify, this is about the message at the bottom after you tag the images in lighttable view, not in map view.

**Comment by Nilvus** [comment]
Oups, my bad.

**Comment by johnny-bit** [comment]
Hmmm... I don't have test gpx file for testing but I think since 3.4 release this works correctly since it follows `images_to_act_on` scheme.

@phweyland - If you have time can you check this issue and see whether this count of files is fixed when applying gpx to selected when images are grouped?

@jonas-ott - since you posted this issue the darktable 3.4 got released and there's new release (3.6) comming in just ~7 days. Can you check and confirm whether either 3.4 or 3.6 fixed this issue? we'd appreciate your feedback.

**Comment by phweyland** [comment]
>  If you have time can you check this issue

I'll do.
