### ISSUE TITLE
color zone - color picker tool broken

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#6321]
**Describe the bug**
On the Color Zone there is two different picker. One is the standard picker to get samples from point or area and get corresponding zone on the histogram. This works fine.

The second color picker with a little + on top of it is a tool that should change the curve (raise or lower it) if using Ctrl or Shift when clicking on it.

**To Reproduce**
1. Go to darkroom
2. Open color zone module
3. Ctrl+Click on color picker on the right of the module
4. Draw an area
5. The curve is not changed

**Expected behavior**
The curve should be adjusted (raised or lowered).

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Linux Debian/sid

**Additional context**
Most probably a side effect of the introspection work.

**Comment by TurboGit** [comment]
@dterrahe : can you have a look ? I bet this is due to the introspection work. I just find this will working on the documentation for color zone. TIA.

**Comment by dterrahe** [comment]
The behavior here changed. Previously, the ctrl (or shift) modifier had to be held when the button was pressed to create a positive or negative curve. Now, it needs to be held while _dragging_ (which means, if you held the wrong, or no, modifier while pressing the button you can still change (or switch later, without having to go to the button again).

This is correctly indicated in the tooltip, but yes, the manual needs to be adjusted too.

See #5443 (which turned out to also be a Windows modifier bug)

**Comment by TurboGit** [comment]
Indeed, and we even discussed that IIRC. That good to see people with better memory than me :) Sorry for the noise. Closing.
