### ISSUE TITLE
[masks] maximum size of shapes, before they are created

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#6362]
**Describe the bug**

e.g. in exposure module, try to place a circular mask and with mouse wheel try tomake it very large. Unlike with an ellipse shape, you will be limited to something similar to a vignette size. After placing the circular shape, you can further enlarge it. That feels a bit odd to me.

**To Reproduce**
1. Go to exposure module
2. Click on drawn mask --> cirucular shape
3. Scroll mouse wheel to enlarge it
4. Do the same with ellipse

**Expected behavior**

Same than ellipse.

**Additional context**
* darktable version : 3.3.0+820~g5586a71a0
* OS                : Linux - kernel 5.7.15-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.100-r2
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by johnny-bit** [comment]
Indeed there's some interesting clamping going on during creation... But for both circle and elipse :) And there's some funzies in there too.

So during creation circle shape is limited to max diameter of shortest picture size. Similarly ellipse radius a is limited to it (but radius b isn't since it's scalled via factor). After placing the shape, circle diameter is limted too, but i'm not really sure to how much exactly, looks as if radius of circle is still the smaller of 2 sides of image.

Now the problem is in placing the ellipse. You can indeed try to edit ellipse size pre-placing, but you can't place huge ass-ellipse. It's radius a and b will be clamped to half the size of smallest picture side, so placing huge ass-ellipse allows you to maximally place only same big circle. But of course you can edit it's size after placing.

The max radius is not affected by cropping.

I find this behaviour indeed quite bizarre. One part of it is a bit overzealous clamping done in mask placing introduced in #2049 however I'm not quite sure why it doesn't allow huge ass-circle and ellipse pre-placing but allows to make them big after placing...

I'll try to work on this.

**Comment by johnny-bit** [comment]
Done in #6364 :grinning: Plz test and report back!

**Comment by AxelG-DE** [comment]
tested on exposure module
- circular can be enlarged as it is outside the visible area
- ellipse is large enough but smaller than circle (still bigger than the picture, though)

so, definitely works for me :-)
TNX
