### ISSUE TITLE
Light Table - "Retained" shortcut / button

### ISSUE THREAD

**Issue by sbeuhatsxb** [darktable-org/darktable#6370]
Simple request :

Wouldn't it be nice to have a "Retained" button/shortcut plus the arleady existing "Rejected" (ctrl-r) button/shortcut ?

Didn't find any issue brought anywhere in the "Issues".

Thanks in advance, and keep on the great work you're doing !

(working on 3.2.1)

**Comment by Nilvus** [comment]
Why added that button? All images not rejected are "retained". That's just a basic and to select the best ones, you have stars. Really not useful. If you want a specific button, color labels are there for what you want to assign to them. For example, you could assign the green color to images you want to retain (and there's also shortcuts for color label ; see "h" window info for available shortcuts in current view).

So you already have what you want.

**Comment by sbeuhatsxb** [comment]
Well, in my workflow, i'm used to select images i like instead of the rejected the one that i don't like. Then I'm staring after the first edition in order to refine my selection. I was considering that having a "Retained" button was the same logic that having the "Rejected" one - and, by the way, more gratifying psychologically talking and more economical.

And, to my knowledge, it's not possible to filter by color.

I agree that it doesn't seem to be the top first priority, but it would have be nice to have it !

**Comment by ptilopteri** [comment]
most definitely able to filter by color
you need to look further

**Comment by dterrahe** [comment]
All workflows are valid, but no program can support all of them cleanly. There are ways to achieve what you want using the existing functionality in darktable (either by using colors or by using rating 1 to mean "retained"). Because it is unlikely that this suggestion will be implemented or accepted in the codebase, I'm closing this issue, but please report any problems you have when using the suggested alternative approaches. Thank you.
