### ISSUE TITLE
Color contrast module grading colors (cosmetic).

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#6376]
**Feature request**
The sliders of green vs magenta and blue vs yellow are without their respective colors.
It is just a cosmetic thing. I don't know how the scales are projected, because now the marker is more at the left and the scale goes from 0 to 5.

**Solution**
Would be great a solution cretae a grading colors between them.

**Alternatives**
See the attached image.

**Additional context**
<img width="254" alt="Cosmetic01" src="https://user-images.githubusercontent.com/67672868/94228685-81ef9600-fecb-11ea-8ef8-4204f38255ed.png">

**Comment by johnny-bit** [comment]
Well, to be completely honest it's IMO impossible to convey what's module doing using slider gradient as an example.

First of all - it doesn't boost greens when going one way on `green vs magenta` slider and boost magenta when going the other way ;) what it does is boosting BOTH when on 5x place and when it's on 0 it desaturates them. same with `blue vs yellow`.

so - green vs magenta would have to be represented by 2 stacked linear gradients going from gray to super-saturated green and super-saturated magenta. and similarly blue vs yellow would have to do the same. 

Second - the scale. The scale is designed to be a bit to the left since you can get it up from 1 to 5, but you can only go from 1 to 0.

I can badly aproximate that via following image:
![lab](https://user-images.githubusercontent.com/10687765/94333470-a2a51200-ffd7-11ea-8ae5-f4c1bfd46ce6.png)

Warning - this image is not correct in any measure but it's "sorta there"

I've checked current manual for color contrast and TBH if I haven't checked source nor tried the module, I wouldn't get what it does and would like to have colored sliders in it... but after checking it - I really think that what you are asking here is simply... impossible.

What is possible though is changing labels :) so I understand that when the label says "green vs magenta" one could understand "this is a battle between green and magenta! which side do you boost?" instead of "this is boost of green&magenta colors draging them away from each other for greater contrast between those 2"

I'm very open to suggestions on how to improve manual and labels (and maybe show some hidden features the module has ;) ) so - @difrkaguilar what are your suggestions?

Also - I'd love suggestions from @elstoc here too :)

**Comment by elstoc** [comment]
The labels could be misunderstood, I agree. Perhaps changing them is the best. Colouring the sliders would probably be equally confusing unless you had two colours - e.g. green on top and magenta on the bottom. It probably still wouldn't be very clear though.

Changing to something like "green/magenta contrast" and "blue/yellow contrast" might be better.
