### ISSUE TITLE
White balance module: sliders too imprecise

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#6395]
I use the master branch on Xubuntu 18.04 and noticed a change in the channel coefficient sliders which makes it very hard to adjust white balance in my photos.

My procedure to fine-tune white balance: With the color picker I select one or a few areas I consider to be neutral and add them to the samples.
After that I adjust white balance with the channel coefficient sliders using the mouse wheel until I am satisfied with the results.

One step with the mouse wheel changed the value by 0,001. Since a few weeks this has changed to 0,1. Now one step with the mousewheel changes R,G or B values by 10 on higher values which is way too much to finetune white balance.
When I use the right mouse button on a slider I change the initial value by moving the mouse to the slider. Even on the lower areas the slider is not precise enough and it is very hard to change details because I have to be very precise with my mouse movements.

Is this change in the slider behaviour intended?

**To Reproduce**
1. take a sample with the color picker and save it
1. open white balance module
1. change a channel coefficient for R, G or B with the mousewheel
1. value changes by 0,1 

**Expected behavior**
value changes by 0,001 

**Platform (please complete the following information):**
darktable 3.3.0~git868.7631e70a8
Xubuntu 18.04

**Comment by johnny-bit** [comment]
@dterrahe can you check it?

**Comment by dterrahe** [comment]
The scroll wheel step size can now be made more precise by holding the CTRL key _even if "mouse wheel scrolls modules" is enabled._ This reduces the step size to 0.01, so 1000 steps overall. Are you sure you really need 10,000? If so, you can modify the specific multiplier used by the CTRL modifier in darktablerc with 
`darkroom/ui/scale_precise_step_multiplier=0.01
`
For the last micro adjustments, the right-click finetune is most precise exactly around the current value and at the bottom. If you really can't hit a specific value, you can type it in.

I would be reluctant to reduce all the step sizes to the smallest possible moves again, because it makes the scrollwheel less useful for everybody else, even with the shift and ctrl modifiers. But of course if this bug report receives significant support, anybody could submit a PR; the "fix" itself is trivial; it would just require
```
  dt_bauhaus_slider_set_step(g->scale_r, 0.01);
  dt_bauhaus_slider_set_step(g->scale_g, 0.01);
  dt_bauhaus_slider_set_step(g->scale_b, 0.01);
  dt_bauhaus_slider_set_sep(g->scale_g2, 0.01);
```

**Comment by junkyardsparkle** [comment]
I would agree that the "smal" step size of 0.01 is sufficiently granular for any sane purpose, but the "normal" step of 0.1 does seem a little bit heavy handed for general unmodified scrolling action.... maybe 0.05 would be a good compromise? For me that's close to a "just visible" change. Also, the "large" Shift + scroll increment of 1 really isn't useful at all... 0.25 would probably be better. My two cents.
