### ISSUE TITLE
global color picker: tiny font

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#6407]
When reducing the width of the left panel the R/G/B labels become very small, even though the gap between them remains large -- so there's plenty of space for larger numbers.

![Screenshot_2020-09-29_20-13-06](https://user-images.githubusercontent.com/9555491/94604895-37399980-0290-11eb-875b-81aa51e4a920.png)

Please make the numbers bigger.

**Comment by elstoc** [comment]
@dterrahe? 

I can that space might be needed for Lab mode but for RGB presumably it could be increased?

**Comment by dterrahe** [comment]
I'm working on a PR that uses the NK57 Monospace font to condense (only horizontally, not vertically as well) the text when space gets tight. Very few monospaced fonts have variants with different "stretch" factors, so this would only work (well) with this specific font.

To discuss giving RGB a different treatment from Lab and the others, you'll have to talk to @TurboGit, because he was very insistent they should all be the same width so there would be no jumping when stepping through the options combobox (https://github.com/darktable-org/darktable/pull/6355#issuecomment-697906130). I regret a little giving in to him, because for narrow panels "narrow" RGB would be a nice choice to have, but of course I would never suggest he might not be right about this one!

**Comment by elstoc** [comment]
@dterrahe I'll leave it to you and @TurboGit to decide what's best (I don't really use this module much) but these become unreadable quite quickly when resizing and, strangely, get smaller when you set larger font sizes. The situation could be mitigated a little by making the live sample square smaller (or subject to a smaller minimum width) but really, with Lab samples (four digits with a decimal and possibly minus sign) the problem is that there is too much information in a small space.

With the previous version the font size was constant and the module increased in width when you went to Lab mode (which wasn't ideal either) so I'm not sure there's a good solution that will satisfy everyone.

**Comment by dterrahe** [comment]
![image](https://user-images.githubusercontent.com/1549490/94611179-45d87e80-0299-11eb-86fc-2adc00091943.png)

This would be the narrowest using condensed fonts (before it starts ellipsing). Of course at that point, the two strategies could be combined; reducing font _size_ a little as well. But yes, removing some spaces from RGB would also help. There's the "bullseye" option and using the tooltip, too.

**Comment by elstoc** [comment]
ellipsizing would be more consistent with the rest of darktable

**Comment by dterrahe** [comment]
That's true, but in most cases what is ellipsized is text. Even if they are for example combobox options (i.e. non-static) a few letters often still provide all the information. With numbers this is not the case, hence why I'm trying to find a better way of dealing with insufficient space for them. You are of course absolutely right that the color picker numbers get too small. I have to admit that this was a bit of an experiment to see what the feedback would be; I think you are the first to pick up on it.
The other place that really needs attention though is the blending sliders. The complication there is that _all_ numbers need to change condensation at the same time. The other thing there is that adding ellipses for each number ends up wasting a lot of space, that could have given still some partial information. And the numbers are jumping all over the place (partially because they are not monospaced). So I'm going to rewrite that as a drawingarea/direct pango and see if it can be smoothed a bit, either with "tab stops"/"fixed" positions or with a monospace style. Those fonts tend to be wider though, so condensed fonts could be sugar on top for those who choose to install them.

**Comment by elstoc** [comment]
You're right, numbers aren't ellipsized anywhere.

**Comment by dterrahe** [comment]
For the blender gradient slider numbers I'm experimenting with different layouting solutions to avoid having to shrink the font (too much) or making the numbers unreadable by ellipsizing them. Because simply "wrapping" the numbers (using a flowbox) would confusingly change the order (i.e. the rightmost number could end up on the next line on the left) I'm thinking of alternating them on different lines so they can overlap. Hope these screenshots make the idea clear.
![image](https://user-images.githubusercontent.com/1549490/94838868-1e56f280-040e-11eb-90fd-152856780548.png)
![image](https://user-images.githubusercontent.com/1549490/94838679-d506a300-040d-11eb-8f92-cfee112f82fb.png)
This would dynamically happen when the panel becomes narrower (so a wide panel still has one line). But it won't depend on the exact width of each of the labels (or whether the colorpicker number is visible) because that would cause annoying jumping around.

Alternatively, the line-height could be kept constant, but the numbers font reduced, to achieve a similar effect.
![image](https://user-images.githubusercontent.com/1549490/94839711-47c44e00-040f-11eb-9541-a2ff9a20c191.png)

What do you think?

**Comment by elstoc** [comment]
I don't usually have my panels _that_  narrow (not the right hand one anyway) so I don't normally have issues with numbers colliding, but generally I'm not the biggest fan of auto-scaling fonts - font size is supposed to be user specified and adjustable via CSS. Though you could maybe make the default font a little smaller.

If you want to split the numbers onto two lines you could try to make the numbers better match the layout of the sliders if possible

So for the output slider on your last example you might have
```
    9.0  43
2.0          46
=============== (slider)
```
or (imo better)
```
9.0         43
=============== (slider)
2.0         46
```
which might make it clearer what each of the numbers mean.

**Comment by dterrahe** [comment]
I did consider that (the top suggestion), but would have to change inner and outer when polarity is switched. And that makes it necessary to change the position of the color picker number as well. This is all quite finicky. The bottom one would be easy when always using two rows, but I'd want to use them "only when necessary". Also wondering if the bottom numbers from the top slider being next to the top numbers for the bottom slider might cause a little confusion/distraction again.

The implementation I'm currently playing with uses a GtkOverlay, which allows "fixed" relative positioning (so numbers don't move when a different number changes). Drawback is that it doesn't prevent overlap, so putting two numbers close together is hazardous.
