### ISSUE TITLE
filmic v4: a couple of odd slider behaviors

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#6508]
**Describe the bug**
In the "look" section of filmic v4, when sliding the "middle tones saturation" control fully to the left (-50%), the preview suddenly goes completely black, true for OpenCL on or off.

Also, it's possible to enter a value higher than 2 via right-click in the "contrast" slider, which accepts the value and changes the soft upper bound of the control to match... however, values >2 do not actually produce any change, but give the same result as a value of 2.

**To Reproduce**
See above.

**Expected behavior**
First issue: preview should obviously not go black.

Second issue: If values >2 don't make sense for "contrast", the upper bound of the control should be hard.

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1057~g7079a88ac
 - OS: Linux
 - OpenCL makes no difference

**Comment by junkyardsparkle** [comment]
I changed the contrast clamping to 5 to match the control bounds and tried some extreme settings... nothing exploded. So... @aurelienpierre, is the clamping to 2 intentional? I didn't see any explanatory comments.

**Comment by aurelienpierre** [comment]
If you set contrast > 2, there is 95% chance that it makes the curve over and undershoot at the same time. Real color film should have an equivalent contrast of 1.628 (I computed that a while ago), so that's our "real life" ground truth. There is some sanity checks happening behind the GUI that remove bad nodes, so that might explain why, once you go to unreasonable settings, little unreasonable or very unreasonable produce the same results.

I guess the saturation issue comes from a division by zero. I thought I prevented that in the code, but I have to check, don't remember.

**Comment by junkyardsparkle** [comment]
@aurelienpierre Thanks for the explanation, that's kind of what I guessed. But the value of contrast is clamped to 2 in the code, so it's not that the change when setting above 2 is small... there is no change. So basically what I'm getting at is that the clamping value and upper input bound should be the same, right? Or am I missing something?

I made a feeble attempt to find the saturation glitch, but I struggle at a fairly low threshold of complexity. :-)

**Comment by johnny-bit** [comment]
While I was checking this issue again with `3.5.0+2526` i've noticed that contrast works from 1 to 5 regardless whether it's filmic v4 or v5. the saturation also doesn't cause black screen (however there's interesting effect on module graph when completely desaturating the image).

So... The issue can be marked as fixed?

I did notice that the contrast below 1 doesn't change the result but that might've been intentional.
