### ISSUE TITLE
Watermark module only handles one space character

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#6513]
3.3.0+584~g5424fa2e3-dirty    Ubuntu 18.04

Using the simple text option within Watermark, you can't space words out freely because two or more spaces are treated as just one space in what is applied to the image.

**Comment by RawConvert** [comment]
Nice juicy little bug for someone surely?

**Comment by RawConvert** [comment]
Still happening in 3.4.0 release.

**Comment by ralfbrown** [comment]
I was looking at the SVG spec because I wanted to embed a newline in the text for the simple-text stamp.  No luck on that front, but it's straightforward to allow multiple embedded blanks: add attribute `xml:space="preserve"` to the `text` tag in simple-text.svg.  Leading/trailing blanks will still be stripped, and tab/newline converted to space.

**Comment by TurboGit** [comment]
> to allow multiple embedded blanks: add attribute `xml:space="preserve"` to the `text` tag in simple-text.svg.

I suppose we want this to be the default in dt.
