### ISSUE TITLE
keyboard shortcut for the RGB Level module is inactive

### ISSUE THREAD

**Issue by LViatour** [darktable-org/darktable#6561]
**Describe the bug**
creating a keyboard shortcut to display the "RGB level" module does not work. it works for the other modules.

**To Reproduce**
1. create a racourcci "ctrl + M" to display the module or other combination
2. activate keyboard combination
3. the RGB Level module is not displayed

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0~git1128.bb9b701fe
 - OS: Linux Ubuntu 20.04
 - OpenCL activated
 - graphiccard Nvidia drive 450.80.02

**Additional context**
tested on other installations and problem confirmed on two other PCs
-->

**Comment by elstoc** [comment]
Works fine for me on the same version

**Comment by LViatour** [comment]
the problem is in the darktablerc file which contains my preferences.
I edited the file and changed the line:
plugins / darkroom / rgblevels / visible = False to True

now it works

**Comment by dterrahe** [comment]
> Works fine for me on the same version

Does it work for you on a clean install (no darktablerc)? I find that many (most?) modules don't seem to get their accelerators connected. For example the default mappings of "[" and "]" to rotate do not work. Even though flip::connect_key_accels _does_ get called.

I used to have frequent issues with accelerators not working, but could usually resolve them by selecting the all modules subset  and reentering darkroom. That doesn't work anymore (maybe sense the new module group work?).

Maybe for all of us old timers this works fine, because we still have old darktablerc files that have all modules activated, but newcomers may just decide that shortcuts don't work at all. This is not the first such bugreport I've seen but many won't take that trouble.

**Comment by LViatour** [comment]
I have a very old darktablerc. But there is no problem with a clean installation.
There are at least three other users who have the same problem.
Probably an old setting which is not well saved in darktablerc.

**Comment by dterrahe** [comment]
I'm starting _without_ any darktablerc, so i'm not sure what you mean with an old setting possibly being the problem?

Are you saying that "[" works for you out of the box with a newly compiled master and --configdir ~/.config/emptydarktablesettings ?

**Comment by LViatour** [comment]
My darktablerc contains preferences from several years of preferences.
If I delete the darktablerc I lose my settings but then the keyboard is working.

**Comment by dterrahe** [comment]
To be absolutely clear, you are saying that after deleting darktablerc (or using a clean settings directory via --configdir) keyboard shortcuts _are_ working in the darkroom. Specifically, the standard shortcut '[' rotates the image?

**Comment by LViatour** [comment]
with a clean darktablerc the standard keyboards shortcut works even for rgb level
With my old darktablerc the shortcut standard keyboards work but impossible to give a keypad to the rgb level display.

Sorry for my english....

**Comment by elstoc** [comment]
> For example the default mappings of "[" and "]" to rotate do not work. Even though flip::connect_key_accels does get called.

Just an aside here but these shortcuts are _local_ so the orientation module has to have gui focus for them to work. This is set by the second input parameter to dt_accel_register_iop (TRUE).

**Comment by dterrahe** [comment]
Ah, that'll be it! I always forget about that flag.

But also, here I don't think local shortcuts make sense; the whole point of the rotation shortcut is to not have to go to the module first (otherwise you might as well press the button there). I guess this was done because otherwise the local shortcuts in masks don't work; they get overruled. But it makes the rotate shortcuts useless imho.

What about the sliders in bloom? Do they work for you in a clean install?

**Comment by elstoc** [comment]
@LViatour: There have been quite a few code changes around keyboard shortcuts recently so this should be retested on latest master. Alternatively, if you're happy with deleting config files as a solution you could consider closing the issue.
