### ISSUE TITLE
Olympus OM-D E-M10 Mark IV

### ISSUE THREAD

**Issue by wombalton** [darktable-org/darktable#6569]
Just submitted a raw sample at raw.pixls.us. Log Message by Darktable is:

`RawSpeed:Unable to find camera in database: 'OLYMPUS CORPORATION' 'E-M10MarkIV' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (PA170030.ORF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 174: Camera 'OLYMPUS CORPORATION' 'E-M10MarkIV', mode '' not supported, and not allowed to guess. Sorry.
`
EDIT: I'm running darktable version 3.2.1 as a flatpak from flathub.

On the other hand RawTherapee 5.8 also a flatpak from flathub is able to open that file.

**Comment by wombalton** [comment]
I'm able to open the E-M10 Mark IV ORF when I copy the entry for the Mark III in `cameras.xls`:

```xml	
    <Camera make="OLYMPUS CORPORATION" model="E-M10 Mark IV">
		<ID make="Olympus" model="E-M10 Mark IV">Olympus E-M10 Mark IV</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="254" white="4000"/>
		<Aliases>
			<Alias>E-M10MarkIV</Alias>
		</Aliases>
     </Camera> 
```

For me `cameras.xml` is located in `/var/lib/flatpak/app/org.darktable.Darktable/current/active/files/share/darktable/rawspeed/`; I guess for a native installs that would be somewhat like `/usr/share/darktable/rawspeed/cameras.xml`

But I dot get errors about some missing color matrix:
``` 
[temperature] 'Olympus E-M10 Mark IV' color matrix not found for image
[colorin] 'Olympus E-M10 Mark IV' color matrix not found!
```

Can anyone point me to where I can fix this?

**Comment by junkyardsparkle** [comment]
> Can anyone point me to where I can fix this?

https://github.com/darktable-org/darktable/blob/master/src/external/adobe_coeff.c

As you can see, the matrices for the I, II, and III models are identical, and AFAIK nothing about the sensor in the mk IV has changed, so you'd probably be fine with duplicating it again.

**Comment by wombalton** [comment]
Thx @junkyardsparkle, that works.
What would be the correct way of adding support for the Mark IV? Simply adding that alias or duplicating the entries in both files?

**Comment by junkyardsparkle** [comment]
It will be an new unique entry when it's properly added to the rawspeed library; normally an alias would just be for the same model by a different name (Panasonic is notorious for doing this for different market regions).

**Comment by wombalton** [comment]
Very well. But before I do that pull request, is there a way to verify that these are indeed the right values? I mean just because it works, does it work correctly? How do I know?
Sry, if these are dump questions, I'm new to that topic.

**Comment by junkyardsparkle** [comment]
Probably no need for a PR, I think @LebedevRI has this on his TODO list (?)... the matrices are derived from what ends up in converted DNG files (and in my experience as a 16MP Olympus user, they're ok but have a tendency towards gamut-busting dark blue shades and dull oranges). 

You could submit a set of white balance values for the different in-camera settings, but tbh even if you end up with different ones than the previous models, it doesn't mean that they're more correct. Olympus cameras actually use different RGB coefficients for these settings depending on the lens mounted at the time (this seems to be a little-known fact), so differences from previously submitted ones could simply be due to that. If you want to produce these, the best way would probably be without a lens mounted at all.
