### ISSUE TITLE
feature enhancement:  shortcuts display

### ISSUE THREAD

**Issue by sergei18500** [darktable-org/darktable#6609]
Hello,
In the master version, when a global preference is changed, it is displayed in bold italics.

You will be able to do the same for shortcuts that you modify or create.

This would be very visual when using the 'Help' key to view darktable shortcuts and your own customizations.

- Thanks

**Comment by Nilvus** [comment]
Why not but actually, bold/italic has to be changed. Having a visual sign to see what is changed is the idea but bold/italic is not the best. But we do not have better idea by now. I am on trying ASAP to think about a better one (but no time by now to search/look for), as discussed with @johnny-bit there: https://github.com/darktable-org/darktable/pull/6433#issuecomment-703141111

If you have an idea, you're welcome!

**Comment by sergei18500** [comment]
It might be possible, for example, to leave the bold and italic and change the background color of the modified line?
Personally, the most important thing is to visualize quikly on the 'H' page one shortcut  modified or created .

**Comment by Nilvus** [comment]
As I said, bold/italic has to be changed, not kept with a color. The goal is to see what has been changed but in a less distracting way. So adding color would be worse. I think a sign should be better, not how text is rendered. But I need to think more about it and find ideas.

**Comment by TurboGit** [comment]
> So adding color would be worse.

Agreed.

> I think a sign should be better, not how text is rendered. But I need to think more about it and find ideas.

I had created a PR or talked about it... Let me recreate it to let you test this.

**Comment by sergei18500** [comment]
Do the best you can, but personally the italic bold would have satisfied me.
(I don't know anything about development so I can't offer code or test your versions).
I'm sorry

**Comment by johnny-bit** [comment]
Essentially - bring the "dot" character from preferences into shortcuts view :)

**Comment by difrkaguilar** [comment]
#

> Essentially - bring the "dot" character from preferences into shortcuts view :)

I think this is the best way to show users a difference between defaults shortcuts and the changed ones. One more thing will be great if in the shortcuts configuration tab this little dot be to with an indication of the previous (default) shortcut, before change. In that way if users like to go back to the default shortcuts don't have to reset all of them to the initial state with the default button.

**Comment by dterrahe** [comment]
Internally, the default shortcuts are no longer stored when they are overwritten by the user configuration, so it wouldn't be that easy to figure out what has changed. It may not be efficient to spend that time now because...

In #8078 a completely new implementation of the shortcut system is proposed, which allows much more flexibility. For example, multiple shortcuts can be linked to the same action. This is necessary because several new devices are supported (midi, gamepad, possibly others in future). But this also blurs the concept of "changed from default". I think I'll dump the default keyboard shortcuts to a file before reading the user configuration. This could then be reimported (possibly after editing/pruning) to revert (some of) the keys to their default meaning, but you could then end up with duplicates. The whole concept of the help screen also should be rethought, because it could get very crowded with all the additional shortcuts that can be set up (double/triple presses etc). Also, because the configuration dialog will follow a different logic (key -> action, vs currently all actions -> some mapped keys) and because there will be many more tooltips showing shortcut keys, there may not be as much of a separate help screen.
