### ISSUE TITLE
Handle existing styles import/export conflicts.

### ISSUE THREAD

**Issue by darkelectron** [darktable-org/darktable#6627]
**Is your feature request related to a problem? Please describe.**

Currently, darktable will reply with a message such as "style 'name' already exists", while importing, which means the user has to remove/rename the existing style inside darktable or the one in a file manager.

The same is also true for exports, darktable won't overwrite an existing style, but will reply with a notification of "style saved successfully saved", even though nothing was saved. (fixed in my build)

**Describe the solution you'd like**

darktable should have an option on how existing styles are to be handled, e.g a drop down menu that will be in the styles module in lighttable.

**Alternatives**

Before choosing a folder where styles will be imported from, darktable may produce a dialog on how users would like to handle existing styles. And the same applies for exporting. 

Depending on how often users would import/export styles, it may be annoying to always having to select an option before every operation. That's why I prefer the above solution(drop down.)

**Additional context**

An idea of what I was thinking:

![2020-10-24-17-17-15](https://user-images.githubusercontent.com/51426724/97088192-d434eb80-161e-11eb-8454-20006c5b7686.png)
![2020-10-24-17-18-40](https://user-images.githubusercontent.com/51426724/97088194-d5feaf00-161e-11eb-97bb-3842eed4d2ee.png)

**Comment by junkyardsparkle** [comment]
Since there's already a dialog for choosing location, what about just adding some (sticky?) options there, similar to the image import dialog? As for the options themselves, I don't think of "skip" as being very useful (is this ever what somebody is trying to do when initiating an import/export action?). Otherwise, I think my preference would be for an additional dialog only in the case of collisions, which would hopefully not be very common (I usually encounter it with exports only on odd occasions when making changes shortly after a first export).

Imports are kind of a weird case, because AFAIK previously imported style files remain as files even when the styles have been "removed" from the module. This situation might need some thinking about (it's not clear to me that those files really need to exist in the first place, but maybe I'm missing something). Anyway, thanks for working on this!

**Comment by darkelectron** [comment]
> I don't think of "skip" as being very useful (is this ever what somebody is trying to do when initiating an import/export action?).

This would be on a case of multiple styles.

> Imports are kind of a weird case, because AFAIK previously imported style files remain as files even when the styles have been "removed" from the module. This situation might need some thinking about (it's not clear to me that those files really need to exist in the first place, but maybe I'm missing something).

I think dt tries to be non-destructive even on styles, so remove, will delete a style in its database.

> Otherwise, I think my preference would be for an additional dialog only in the case of collisions, which would hopefully not be very common (I usually encounter it with exports only on odd occasions when making changes shortly after a first export).

One reason  I didn't go for this one was cause of the multiple styles export. Just thought of something that might work in both cases: 

when dealing with one, just have a dialog of "overwrite or not", and on multiple have a similar dialog appearing on the first collision it encounters on whether to overwrite the remaining styles or not.

**Comment by junkyardsparkle** [comment]
> This would be on a case of multiple styles.

I admit I wasn't really thinking about that, but I suppose it's something that people do.

> I think dt tries to be non-destructive even on styles, so remove, will delete a style in its database.

It's just that it's possible for a user to not even be aware of the dtstyle files that have accumulated in the config directory, so there's the possibility that an import will be a collision there even if there's no indication of that in the GUI... which could be confusing. The current behavior of silently skipping the file write is kind of weird, because that means you can have stale versions in that directory which don't correspond to the same-named styles in the db. I would say that silently overwriting makes more sense in that case (renaming old versions seems like overkill).

> when dealing with one, just have a dialog of "overwrite or not", and on multiple have a similar dialog appearing on the first collision it encounters on whether to overwrite the remaining styles or not.

Good old "[Yes] [No] [All] [None]" works for me. :-)

**Comment by parafin** [comment]
styles files in config directory is just a backup in convenient form, so indeed it makes sense to overwrite those files
