### ISSUE TITLE
Print Module : Icc profile could be taken twice

### ISSUE THREAD

**Issue by japamax** [darktable-org/darktable#6635]
System : Archlinux
Desktop : Kde 5.20.1
Printer : Epson R2000
Driver : epson-inkjet-printer 1.0.0-1lsb3.2
Kde Color Corrections : Epson R2000 : profile1.icc by default (not default RGB)
Darktable profile : profile1.icc

The print occurs with the profile profile1.icc applied twice. 
You need to put default RGB profile by default on Kde Color Corrections for the printer to have a correct printing.

**Comment by Nilvus** [comment]
Your issue is now old and you don't precise darktable version. It's not even sure on what I understand (sorry but your issue is not clear) if it's really darktable related. As now, KDE has newer release and darktable will have a newer huge release in about 2 weeks (3.6 one), I suggest you to test again with future 3.6 and if possible latest KDE one. Then if you still have the issue, please open a new one with all infos asked in issue template and more information as possible to be sure someone can reproduce your issue. Thanks.
