### ISSUE TITLE
Improved zoom in culling mode

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#6676]
**Problem**
It is very difficult to zoom to a specific area in culling mode:
Even if the mouse cursor is positioned in the bottom-right corner of the image, the centre gets zoomed.
So I have to pan to the area I want to inspect.

**Solution**
Use the existing zoom functionality of darkroom also for culling mode:
The area where the mouse cursor is positioned gets zoomed.

**Alternative**
Draw a rectangle over the area to be zoomed in darkroom + culling mode
(similar to the new zooming functionality in Adobe Lightroom 10)

**Comment by maboleth** [comment]
Interesting idea! Would like to know if that's possible (easy) to implement?

**Comment by AlicVB** [comment]
I think I need more time :) 
At some point, we'll implement the zoom around cursor for culling too, but as @Nilvus said, it's not so simple because we have to take lot of corner cases into account. iirc, it was not there in previous version either.
Sadly, I'm really short in time now because my real job is becoming crazy... So except if someone stand up and want to code it, I fear this won't be for 3.4 :(

**Comment by maboleth** [comment]
> I think I need more time :)
> At some point, we'll implement the zoom around cursor for culling too, but as @Nilvus said, it's not so simple because we have to take lot of corner cases into account. iirc, it was not there in previous version either.
> Sadly, I'm really short in time now because my real job is becoming crazy... So except if someone stand up and want to code it, I fear this won't be for 3.4 :(
> 
> For your other proposition, at first sight, this will be even more difficult...

@AlicVB All good, take your time Alic. :) I'm all for improved stuff, BUT having robust, rock stable and working module is the top priority. Considering we squished so many bugs in git release, better take your time than rush into some features that could introduce more pests. :)
