### ISSUE TITLE
Basecurve is applied to JPEG files

### ISSUE THREAD

**Issue by angryziber** [darktable-org/darktable#6705]
**Describe the bug**
JPEG files get basecurve applied in both darkroom and zoomed-preview in lighttable resulting in over-brightened shots.

**To Reproduce**
1. Import a JPEG file from DSLR camera (Canon 6D mark II in my case).
2. Press W in lighttable view to see it over-brightened (thumbnail is fine)
3. Doule-click to get to Darkroom and see it overbrightened again. Disabling basecurve module fixes the issue.

**Expected behavior**
JPEGs are already non-linear, so don't need basecurve applied at all.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Ubuntu 20.10

**Comment by johnny-bit** [comment]
Does not replicate on current master (and therefore release 3.4 won't have this problem) Since release 3.4 is super near - closing

To be clear: I followed replication steps using all combinations of processing settings using current master build. JPEGs do not get basecurve nor filmic applied and it's all fine :)
