### ISSUE TITLE
channel mixer rgb not neutral

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#6803]
**Describe the bug**

activate the channel mixer rgb changes the image

**To Reproduce**
1. Go to darkroom
2. Active channel mixer rgb
3. See image changes

**Expected behavior**

The module should be a not by default.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Linux debian

**Additional context**

Maybe setting CAT adaptation to "none" by default could be a solution ?

**Comment by elstoc** [comment]
The problem is not necessarily that it's not neutral but that there is a dependency between the white balance module and the CAT. If you were to set channel mixer to be no-op by default then the problem would come back when you change that default without setting the WB module to D65. 

It's a similar problem to the scene referred workflow defaults, in that it requires two modules to be changed but in this case the dependency remains even if either module is subsequently altered.

We've been discussing on IRC and the only solution I can see is to force one behaviour or the other via a preference, i.e. either

1. Use the white balance module to do white balancing. Force the CAT adaptation to "none (bypass)" and don't allow it to be changed; or
2. Use the channel mixer rgb module to do the white balancing. Force the white balance module to D65 and don't allow it to be changed

Old edits would have to be forced to option 1.

**Comment by rabauke** [comment]
I think setting source to "same as pipeline (D50)" as default should fix this. See also discussion on pull request  #6793.

**Comment by matt-maguire** [comment]
The problem with defaultiing to "same as pipeline (D50)" is that is you then want to set the module to do white balancing based on the camera settings, this is no longer possible -- there is no menu item to specify this.

**Comment by rabauke** [comment]
@elstoc Taking a broader perspective: We have two modules dedicated to white balancing (although the channel mixer rgb is not solely about while balancing). Is it correct that these two can not be used independently/exclusively? (The "white balance" module must be set to specific parameters for white balancing via "channel mixer rgb". I.e., "white balance" must be turned on when setting the white balance via channel mixer.)

I think, heaving two modules for white balancing is not intuitive, in particular because these modules depend on each other in a non-trivial way. Users will wonder which module should be used in which context.

**Comment by matt-maguire** [comment]
@aurelienpierre already described why there are two WB modules in his post on pixls (see section under the heading “Why duplicate the WB setting?” ):
https://discuss.pixls.us/t/introducing-color-calibration-module-formerly-known-as-channel-mixer-rgb/21227

**Comment by rabauke** [comment]
@matt-maguire Thanks for drawing my attention to this article. It helps a lot to understand the new module.
