### ISSUE TITLE
Mouse wheel turn on new image causes it to pixelate

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6806]
3.3.0+1440~g44fe67e70 Windows.
Opencl off.

Coppied history then realized I want to edit this fresh. Copy had multiple exposure modules. Compressed history.

Turning mouse wheel on histogram for exposure immediately pixelated.
Notice history has exposure 1, but there is no exposure 1 in modules.

This has happened on a few images now. 

![image](https://user-images.githubusercontent.com/1119439/98520057-929b7600-2297-11eb-96a8-70ef08784990.png)

**Comment by elstoc** [comment]
This could be a regression from a refactor. This was a bug that used to happen before I rewrote the multi-instance shortcut stuff. Probably @dterrahe.

**Comment by dterrahe** [comment]
That test in imageop.c is still there
`      if(mod->so == module && mod->iop_order != INT_MAX)
`
Does the manipulation of exposure via scrolling of histogram go via accelerators?

**Comment by elstoc** [comment]
The exposure module proxy used by the histogram is set in connect_key_accels() within exposure.c

**Comment by dterrahe** [comment]
You are correct; connect_key_accels is only called once now, and the connections are stored in a list and restored from there. It is not called for every change of active module.

Looking at it closer, what happens with the proxy.exposure needed to be fixed for multi-instance ordering, because every time connect_key_accels was called another proxy entry was added to the list. So if one kept switching back and forth between two exposure modules, the list would keep growing. Only the first element is ever used. The list is eventually cleaned in gui_cleanup or when the darkroom is left. This made sense when the last added instance of exposure always was the active one, and connect_key_accels was called only once to set it up, but now that they can switch back and forth, maybe we should just set the instance->module of dt_dev_proxy_exposure_t to the currently active exposure module.

@TurboGit I can fix just this regression or clean up the whole proxy list structure, which I don't think works (or can be made to work) correctly with the current setup of multi-instance accelerator priorities.

**Comment by TurboGit** [comment]
I would go for clean up the proxy if possible to get this right in 3.4. TIA.

**Comment by chhil** [comment]
I believe this should be reopened.
3.3.0+1520~g26b4e09d4 on Ubuntu 20 run on windows using WSL (windows subsystem for linux).

Compressed edited history stack of image1.
Cleared history of edited image2 by compressing to original.
Copied history (ctrl+c) of image1 from filmstrip.
Pasted history on image2.

![image](https://user-images.githubusercontent.com/1119439/98903193-1b572380-24dd-11eb-8c50-f965df347394.png)

**Comment by elstoc** [comment]
Maybe worth raising a new one as this doesn't appear to be directly related to histogram adjustment. Also worth asking if either of these images are ones that were affected by the previous issue?

**Comment by chhil** [comment]
This image was not affected previously, its a brand new edit. 
Created https://github.com/darktable-org/darktable/issues/6868
