### ISSUE TITLE
Color Calibration Preset for B/W luminance based just uses the green channel

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6865]
B/W luminance based preset in channel mixer
![image](https://user-images.githubusercontent.com/1119439/98900509-ec8a7e80-24d7-11eb-9cd3-c2f7c40657ee.png)

B/W luminance based preset in color calibration
![image](https://user-images.githubusercontent.com/1119439/98900583-1479e200-24d8-11eb-993e-277ed463ed97.png)

Also, inconsistent naming of grey/gray between the 2 modules. This has been brought up in https://github.com/darktable-org/darktable/issues/6791

**Comment by matt-maguire** [comment]
- the old channel mixer works in the working profile color space, and those coefficients are a typical perceptual luminance estimator got sRGB and REC.709 colorspaces, based on CIE color matching functions. So, they make sense.
- the new channel mixer works in a special CAT color space. If you look at which CAT space is selected by that preset, it is XYZ, and of course in XYZ space the "Y" represents luminance. That's why the second slider ("G") is 1.0 and the others X ("R") and Z ("B") are zero.

- "gray" is an American spelling, whereas the English spelling is "grey". In my personal view, the language is called "English" for a reason :-)

**Comment by parafin** [comment]
Shouldn’t labels change then not to say red, green and blue?

**Comment by chhil** [comment]
I need to get hold of documentation for this module to use it correctly.

Made me look up the difference between brightness and luminance, technically I can understand it but visually I don't.

> "gray" is an American spelling, whereas the English spelling is "grey". In my personal view, the language is called "English" for a reason :-)

I need my custom dictionary plugged in ;)

**Comment by aurelienpierre** [comment]
XYZ is a special RGB space for all we care when pushing buttons. As any CAT space is. And as Matt explained, Y = luminance, so if RGB = XYZ, G = luminance.

**Comment by matt-maguire** [comment]
@chhil a first cut of the documentation is here:
https://elstoc.github.io/dtdocs/module-reference/processing-modules/color-calibration/

**Comment by chhil** [comment]
Thanks @matt-maguire, appreciate the pointer.

**Comment by parafin** [comment]
> XYZ is a special RGB space for all we care when pushing buttons. As any CAT space is. And as Matt explained, Y = luminance, so if RGB = XYZ, G = luminance.

RGB means red, green and blue, clearly XYZ is not RGB. And you don't even see the selected color space in this tab, adding to the confusion. IMHO this should be re-worked somehow.

**Comment by aurelienpierre** [comment]
These are the opponent gradients on the XYZ primaries projected to sRGB:
![Screenshot_20201114_003406](https://user-images.githubusercontent.com/2779157/99130664-3a56d200-2611-11eb-8857-a8d123e89fa6.png)
![Screenshot_20201114_003416](https://user-images.githubusercontent.com/2779157/99130661-3a56d200-2611-11eb-882a-4538658794ed.png)
![Screenshot_20201114_003438](https://user-images.githubusercontent.com/2779157/99130659-388d0e80-2611-11eb-89e5-90d90c2c83eb.png)
it is very much an RGB space.

RGB is a proxy to split a continuous light spectrum into a tri-stimulus that enables a discrete vector representation. It's a method which doesn't presume of the actual space, not the particular space. Spaces are sRGB, Adobe RGB, Rec2020, etc. XYZ is just a special RGB space connected to retina cone response. 

RGB could be called ABC or three spectral slices or trichromatic bullshit, it wouldn't change anything.

**Comment by parafin** [comment]
I understand that XYZ fits the definition of RGB colorspace, but if you notice it doesn’t have RGB in its name as opposed to others. I’m pretty sure nobody calls X channel “red”, because it’s not red. Especially in photographic software I think users expect “red” to mean red color, not abstract red channel, they are not programming some OpenGL code here… Even just using R instead of “red” would already be better, because it’s much more ambiguous. So I don’t agree that naming doesn’t change anything - it changes user expectations.

**Comment by aurelienpierre** [comment]
Most RGB R channels are not red either. The white balance modules shows the actual color of the camera RGB primaries projected to sRGB, none of them look as their name suggest. Red doesn't exist as an absolute color outside of lasers.

**Comment by parafin** [comment]
OK, but green channel in XYZ is luminance, it's like an antonym of color.

Anyway, I think I've explained what I mean, do with it whatever you may want.
