### ISSUE TITLE
Fatal crash in Darkroom 3.2.1

### ISSUE THREAD

**Issue by Vity01** [darktable-org/darktable#6896]
**Describe the bug**
Opening specific picture in Darkroom leads to the fatal crash. 
Crash info attached in files.

**To Reproduce**
Just opening the Darkroom causes the crash

**Expected behavior**
No crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/2512959/99118355-aaf0f500-25f7-11eb-8eb3-17cac2d892e5.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10
[bug_report.zip](https://github.com/darktable-org/darktable/files/5539195/bug_report.zip)

**Additional context**
Editing same picture - PNG.
<!-- Add any other context about the problem here, for example:
 - Can you reproduce with another Darktable version?
 - Can you reproduce with a RAW or Jpeg or both?
 - Are the steps above reproduce with a fresh edit (removing history)?
I cannot remove history - it crashes immediately
 - Attach an XMP if this is necessary
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
No.
 - Is the issue still present using an empty/new config-dir
Discarding image history resolved the crash.

**Comment by johnny-bit** [comment]
Cannot replicate on neither current master nor 3.2.1 on Linux using provided xmp file :/ 

does it happen with this particular XMP for all PNG files or does it happen in combination of this XMP with this particular PNG (which we don't have)? Have you tried with empty config directory?

**Comment by johnny-bit** [comment]
I've re-checked with my-refound knowledge about spots module and 2 things I can advise:

1. use retouch module instead of spots. That might be better suited for every occasion
2. there might be problem with memory management. I "fixed" a bit of allocation problems in spots, but otherwise I don't see how it could fail...

Either way - should be fixed on master. Closing.

If you still manage to replicate the problem we do need that specific png file to see what's going on + way more information about your system, such as: opencl status, graphics card, amount of ram etc.

**Comment by Vity01** [comment]
@johnny-bit  when I deleted the xmp file and reimported the image, the problem was gone. Since that I was not able to reproduce it again (source image is correct). I am not sure what caused it. I hoped the stack trace might be helpful as well. Thank you for checking it.
