### ISSUE TITLE
Softer module deprecation

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#6907]
A number of modules have recently been deprecated. While I agree with the goal and I don't use any of these modules (or will now use their better replacement), a number of people in the poll stated that they do still use them.

The normal process in most software is to issue a release that warns of pending deprecation before finally removing them in a later release. This gives people a chance to explore alternatives while still using the modules they are used to in the meantime.

As we now have the ability to flag warning messages in module headers I propose that, for 3.4, we use this mechanism to warn users of pending deprecation and then fully remove them in a future release.

**Comment by aurelienpierre** [comment]
1. Warnings in modules should be used only for self-checks and settings issues. Popping warnings for design choices will do the opposite of what is intended : people will get used to false positive and disregard the warnings entirely.
2. Delaying deprecation is only going to let people harm themselves for longer. The deprecated modules have internal design mistakes that can't be solved AND alternatives that solves them. Said alternatives have been available since 3.0.
3. New users will see loads of bad modules with deprecation warnings, that's even more confusing.
4. If people absolutely need broken color science, just hide a boolean in preferences that will bypass the deprecation checks in `src/libs/modulegroups.c`

**Comment by TurboGit** [comment]
I would propose a compromise here, have a deprecated "module group" which will list soft deprecated modules. Still accessible but not as easy and clearly when switch to a specific module group.

**Comment by TurboGit** [comment]
For what is worth see #6912
