### ISSUE TITLE
Channel Mixer Deprecation and workflow impact

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6921]
With modules deprecated here is something that I miss...

I do 2 edits per pic, one for color and one for b/w.

Previously I would turn channel mixer on/off to get to my color v b/w edits.

With color calibration, the channel mixer is tied into it and turning color calibration on/off is no longer an option as it impacts white balance. I have t specifically go in and turn the grey sliders to 0.

I **don't** consider this a bug but it's just unnecessary slider changes which got introduced with deprecating channel mixer. I am aware that I can create a duplicate and work on it.

**Comment by chhil** [comment]
To work around this, I thought I can get multiple color calibration modules and touch the grey in the second one.

The second instance shows a warning symbol.

![image](https://user-images.githubusercontent.com/1119439/99178486-8ef56c80-2739-11eb-8e02-6c65f881e022.png)

**Comment by matt-maguire** [comment]
So if you are going to use a second instance of Color calibration, and use luminance preset to work in XYZ space to make the image monochrome, then you need to set the illumination to “Same as pipeline (D50)” in order to avoid doubling up on white balance correction. This is what the warning is trying to tell you.

**Comment by chhil** [comment]
Makes sense.

I pity the user who has to find all this out the hard way :)
