### ISSUE TITLE
DT group modules to turn on / off as a group - several modules would activate / deactivate together.

### ISSUE THREAD

**Issue by vancouverbluesea** [darktable-org/darktable#6953]
**Is your feature request related to a problem? Please describe.**

I am curious if it would be considered beneficial to have the modules organized in groups (per image). 
My issue is - when I process an image completely - I copy paste the history in a few other images. However - some modules are slower (for example denoise). The new images that I copy the history to - may need more intensive operation - like retouching or liquefy. It would be beneficial if I can turn off slower modules, then finish the retouching part then re enable the modules that were temporary off. I expect this would speed up the processing.

**Describe the solution you'd like**

Not sure how this would be best implemented if ever but few approaches below
- show only active modules area - if there is a way to show all modules that are in the history stack for the particular image. Currently - if I am to turn off a module - it disappears from the active modules (expected) but when I am to turn it on - I have to search for it.
- another approach would be to have something similar to snapshots but relevant to set of modules that are on or off
- another approach would be to turn on / off modules directly in the history stack.
- another approach would be to have local styles (relevant for the image only). I was considering using the styles but since they are global - it would be quite confusing on a long term.

**Alternatives**

I considered the existing styles but I am avoiding cluttering the global menu.
Currently I would disable a module from active modules tab but I have no clear fast way to go back to the module and enable it. Especially if several modules have been changed - for example temporary off for denoise, temporary change demosaic from amaze to PPG etc. 
I considered duplicates (duplicate manager) but again - at the end I would like to re enable several modules together and if I don't have an easy way to see all that are "temporary off" I will most likely miss some of them.
My machine is fast but there are still operations that when bundled together can create unnecessary slow down.

**Additional context**

**Comment by Nilvus** [comment]
You already have different ways to do what you want (at least the most important ones). I suggest you to check darktable manual to better learn how to use it.

> **Is your feature request related to a problem? Please describe.**
> 
> I am curious if it would be considered beneficial to have the modules organized in groups (per image).
> My issue is - when I process an image completely - I copy paste the history in a few other images. However - some modules are slower (for example denoise). The new images that I copy the history to - may need more intensive operation - like retouching or liquefy. It would be beneficial if I can turn off slower modules, then finish the retouching part then re enable the modules that were temporary off. I expect this would speed up the processing.
> 
> **Describe the solution you'd like**
> 
> Not sure how this would be best implemented if ever but few approaches below
> 
>     * show only active modules area - if there is a way to show all modules that are in the history stack for the particular image. Currently - if I am to turn off a module - it disappears from the active modules (expected) but when I am to turn it on - I have to search for it.

This is already possible: on the right, active modules show you all actives modules. Of course, if you quit it after disabling one, it's normal that it disappear from actives modules as it's no more an active module. To quickly find a module, you have a search field on top of modules list on the right in darkroom. If you don't have that checkbox, you could find a setting in preferences to enable it.

>     * another approach would be to have something similar to snapshots but relevant to set of modules that are on or off

On modules are shown on active modules tab on the right, so by comparing them to the history and disabled ones, it's quick.

>     * another approach would be to turn on / off modules directly in the history stack.

That has been discussed but many drawbacks and mistakes possibles there. For example, if a user click on a line to just show image at that process or begin the creation of a snapshot and by mistake click on the button to turn on/off...

>     * another approach would be to have local styles (relevant for the image only). I was considering using the styles but since they are global - it would be quite confusing on a long term.

I don't understand the goal to have that per image. But maybe it's just me. For an image, if you copy/paste as you describe above, you can copy/paste modules you want by buttons in development module in lighttable or with Shift+Ctrl+c and/or Shift+Ctrl+v that display you a popup window to select modules you want to copy/paste.

Other thing, in darkroom for next 3.4 coming in Christmas, a new way to manage modules on darkroom will be released, allowing you to display modules used by tabs the way you want in the right panel of darkroom. You will also have the possibility to create different presets with so different configurations of displayed modules and groups/tabs on that panel. See #5683 (note that this was the first pull request to create that new feature ; others have been posted since to improve the feature and 2 are coming for that and a better display is already available).

With all that, I think you could find a way to do what you want, especially with the future 3.4.

**Comment by vancouverbluesea** [comment]
Thank you,
> I don't understand the goal to have that per image. But maybe it's just me. For an image, if you copy/paste as you describe above, you can copy/paste modules you want by buttons in development module in lighttable or with Shift+Ctrl+c and/or Shift+Ctrl+v that display you a popup window to select modules you want to copy/paste.

I do use Shift+Ctrl+c and/or Shift+Ctrl+v - local styles would be simply to select / deselect a group of modules for the image and enabling the user to go fast back and forth. Not sure how to express it - almost like turning a layer in GIMP on / off.... 

> With all that, I think you could find a way to do what you want, especially with the future 3.4.

Looking forward it - I believe indeed it is going to be an exciting feature.

Thank you!

**Comment by Nilvus** [comment]
> Thank you,
> 
> > I don't understand the goal to have that per image. But maybe it's just me. For an image, if you copy/paste as you describe above, you can copy/paste modules you want by buttons in development module in lighttable or with Shift+Ctrl+c and/or Shift+Ctrl+v that display you a popup window to select modules you want to copy/paste.
> 
> I do use Shift+Ctrl+c and/or Shift+Ctrl+v - local styles would be simply to select / deselect a group of modules for the image and enabling the user to go fast back and forth. Not sure how to express it - almost like turning a layer in GIMP on / off....
> 
> > With all that, I think you could find a way to do what you want, especially with the future 3.4.
> 
> Looking forward it - I believe indeed it is going to be an exciting feature.
> 
> Thank you!

So, organizing tabs in right panel for modules you use will help you to do that. I had used favorites tab in darktable before to do that. I add all main modules I use on favorites tab and so switch to active/favorites tab to do that. But now, with that new feature I use in development version, that new feature allow a more configurable way to do that.
