### ISSUE TITLE
Parametric mask: (yellow) mask don't include the value get from picker

### ISSUE THREAD

**Issue by gverduci** [darktable-org/darktable#7004]
**Describe the bug**
After enabling parametric mask in a module (es. vibrance or color balance), picking a value from photo and then setting the slider of hue (for example ) near the selected value, if I enable the yellow mask this not include the selected value.

**To Reproduce**
1. Go to 'Vibrance' module
2. Click on 'Parametric mask'
3. Enable 'Picker'
4. Select a point
5. Enable mask

**Expected behavior**
The mask include the value picked

**Screenshots**
![image](https://user-images.githubusercontent.com/6370005/99879822-98864500-2c0f-11eb-9279-cd27123eeba2.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0~git1688.cd70c5754
 - OS: Ubuntu Linux 20.04
 - OpenCL activated
 - Nvidia GeForce GTX 1050 Ti - driver version 450.80.02

**Additional context**
License for the attached raw file: CC0 1.0 Universal (CC0 1.0)

[DSCF4283.zip](https://github.com/darktable-org/darktable/files/5577807/DSCF4283.zip)

**Comment by TurboGit** [comment]
I see nothing obviously wrong. A frog is mostly green so with some yellow, so selecting yellow seems to do the job asked. If you think there is something really wrong please explain.

**Comment by gverduci** [comment]
My idea is to "modify" the yellow / brown areas of the frog. I select a point in this area with the picker, I change the sliders to select only hues close to the chosen point, but the mask does not include the selected point at all. This point is within the range delimited by the sliders, I expect it to be part of the mask.

**Comment by hlecleme** [comment]
This behavior is due to the fact that the color picker takes samples from a scaled down image (the preview pipe) → the information shown in the slider represents the average of a small region: individual pixels may be different than that averaged value.

It may perhaps be improved by using the full image for picking colors, but this would mean:
- heavier computation (more samples to be read by the color picker)
- as the values are not averaged, this means that the color picker for an area will be more sensitive to outliers (noise)

@TurboGit is it worth to investigate using the full image for the color picker?
