### ISSUE TITLE
documentation: export to e-mail requires clarification

### ISSUE THREAD

**Issue by dtteufel** [darktable-org/darktable#7093]
**Which new feature or section need to be documented/updated**

Export Module 
Target storage = Send as email

Whilst at export an email is created, the image file is NOT attached to the mail.
The image file will be found in ~/tmp and should be manually attached/added to the mail before sending.

Note this is expected behaviour as xdg-email removed the option to attach a file on security grounds.

**Comment by parafin** [comment]
I guess this function should be removed then.

**Comment by johnny-bit** [comment]
I've checked `xdg-email` and I haven't found any mention of removing support for `--attach`. I've browsed https://github.com/freedesktop/xdg-utils and looking at `xdg-email` it looks like attachment is part of generated `mailto:` sent to email command, but there might be diferences in how each mail app attaches them.

So the clarification might be more in vein of "if the attachment hadn't been attached, the generated file is in `/tmp` and you can browse for it in mail app itself" or something like that.

**Comment by dtteufel** [comment]
@parafin Possibly - but probably sufficient to note the limitations in documentation.
@johnny-bit 
In practice I don't think this worked with Thunderbird for quite a while anyway.
Quite happy with your suggested clarification.  

* SECURITY UPDATE: local file inclusion vulnerability
    - debian/patches/CVE-2020-27748.patch: remove attachment handling from
      mailto in scripts/xdg-email.in.
    - CVE-2020-27748
See link below for full detail.
https://launchpad.net/ubuntu/+source/xdg-utils/1.1.3-2ubuntu1.20.04.1

**Comment by ptilopteri** [comment]
you must have a configuration problem.  I just emailed myself an image
from master 05949edcf on openSUSE Tumbleweed plasma5/kde5, and 
successfully received it.

ie: works for me.

**Comment by johnny-bit** [comment]
@dtteufel - OK, thanks for mentioning CVE number. That's very useful when researching for related bugs/problems.

So the thunderbird issue is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1613425

The point from thunderbird devs is this:

> If you can trick the user to run command lines supplied by the attacker, it's basically game over from there. The command line must be considered a safe environment.

So technically attachment way WORKS for thunderbird since thunderbird considers attachment command to be safe.

Problem is that mailto: address handling is handled by xdg-open, which calls xdg-email which is calling thunderbird over commandline which can be considered "game over".

This is the relevant issue: https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/177

The associated merge request only removes attachment parsing from thunderbird-specific code, but leaves `--attach` code unchanged, so the attachment might as well still be there (or not)

In any case - the mention in documentation sure would be welcome change, maybe even go as far as having a warning in the module? Or since the process might not be reliable at all, just remove email export since it's just 1 step less in "export -> open any mail -> attach file" workflow :)

**Comment by ptilopteri** [comment]
why remove a working function because a particular application
refuses or fails to use the provided path to attach an image?

I have no problem with mutt or kmail and do use the export to email
function.

and it is: export -> target storage -> send as email

Thunderbird mail has a problem, not darktable.

**Comment by dtteufel** [comment]
@johnny-bit
Thanks for exploring further.
It looks as if the issue is specific to Thunderbird at present.
Dredging back in my memory about 5 years, I think we may have visited this issue before.
I support you observations on the documentation - at present the topic is not really covered at all.
  
@parafin
I see no reason to remove the export -> target storage -> send as email option.
Clearly it is working for other mailers. 


I'm happy to close this issue now.
