### ISSUE TITLE
[FR] Improve slideshow

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#7118]
**Problem**
The slideshow does not match the expected behavior described in the manual since at least dt 2.7

**Describe the solution you'd like**
- When entering the slideshow, the auto-advance mode should be started automatically
  - at the moment you have to press Space to start it
- Leaving slideshow should only be possible with Esc
  - all other shortcuts should work as always (so B will toggle the borders, L will switch to lightroom, ...)
- the border-controls should be hidden automatically when entering the slideshow

**Alternatives**
- replace the slideshow-module with the sticky-preview feature
  - see discussion at #5926

**Comment by AlicVB** [comment]
if you want my opinion we should rewrite slideshow from scratch and use sticky full preview as a base.
After all, slideshow is "only" sticky full preview with an auto advance feature... So that would mean adding the auto-advance to actual full preview code (not hard) and use that in slideshow view.

fyi, I've had a look at the code when I've rewritten lighttable, to use slideshow code as a base for full preview, but imo the code was way too complex for what it does...

**Comment by TurboGit** [comment]
Note that it is complex because it cashes the next and previous value to be use moving forward backward is instantaneous. This is very important to have a smooth experience especially when HQ preview is used.

**Comment by quovadit** [comment]
Esc and borders are solved meanwhile, and by now I like it that there is no auto-start
