### ISSUE TITLE
Segmentation fault with color picker and switching to lighttable

### ISSUE THREAD

**Issue by hlecleme** [darktable-org/darktable#7153]
When testing #7152, it seems that there is a possibility to have a segmentation fault when performing a color pick and switching to lighttable at the same time. This is not 100% reproducible as it could take several tries to make it happen.

**To Reproduce**
1. Select an image and go to darkroom
2. Use the white balance "spot"
3. Change the region one or more times
4. After changing a region, but before the picker color has been applied, press `L` to switch to lighttable
5. darktable can crash (sometimes)

**Expected behavior**
darktable shouldn't crash :wink: 

**Platform:**
 - darktable version: could reproduce with darktable master 3eb2253b956aadfaad885919138174c28b4af3d0 (with and without #7152)
 - OS: Ubuntu 18.04
 - Could reproduce it both with OpenCL code path and CPU code path

**Additional context**
- Crash log with a tiff file [crash-1.log](https://github.com/darktable-org/darktable/files/5625772/color-picker-crash-1.log)
- Crash log with a raw file [crash-2.log](https://github.com/darktable-org/darktable/files/5625773/color-picker-crash-2.log)
- Crash log with CPU code path [crash-3-cpu.log](https://github.com/darktable-org/darktable/files/5625776/color-picker-crash-3-cpu.log)

**First analysis**
It looks like there is a race condition between the clean up performed when exiting darkroom and the color picker callback. The error happens either in `_iop_color_picker_signal_callback` (`src/gui/color_picker_proxy.c:245`) when dereferencing `dev` or later `_iop_color_picker_signal_callback` → `_iop_color_picker_apply` (`src/gui/color_picker_proxy.c:97`) → `_iop_record_point_area` (`src/gui/color_picker_proxy.c:46`) when dereferencing the module picker (which has probably been cleaned up).

`dt_iop_color_picker_init` seems to be currently called in `dt_gui_gtk_init` so when darktable is initialized, and `dt_iop_color_picker_cleanup` seems not to be called. Perhaps those methods should be called when entering and leaving darkroom?

**Comment by dterrahe** [comment]
> Perhaps those methods should be called when entering and leaving darkroom?

That does make sense (I'm not aware of any cases where color pickers can be used outside darkroom; but maybe there are?).

When I move the dt_iop_color_picker_init call to the end of darkroom.c::enter and put a call to dt_iop_color_picker_cleanup as first thing in darkroom.c::leave, I no longer see this crash.

However, I get a crash in _gtk_widget_queue_draw. I suspect https://github.com/darktable-org/darktable/blob/31540ec18c134bf5d7e83aa62bd1052829b6d26e/src/develop/pixelpipe_hb.c#L1057
because without that line so far I haven't seen a crash.

How does one correctly fix a race like that? Is a signal required or are there simpler solutions?

**Comment by hlecleme** [comment]
@dterrahe Thanks a lot and well done!
