### ISSUE TITLE
ESC does not quit slideshow anymore

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#7197]
**Describe the bug**
Since #7139 it's not possible to quit the slideshow by pressing ESC anymore

**To Reproduce**
1. Start slideshow
2. Press 'ESC'
3. Nothing happens

**Expected behavior**
- ESC does not (only) quit fullscreen but (also) quits the slideshow
- this behavior is intuitive and necessary because the top-menu is not shown in the slideshow
- even the old user manual says 'ESC :  leave slideshow mode and return to lighttable view'

**Comment by AlicVB** [comment]
well, as said earlier, the previous situation was weird and would have give serious issues sooner or later : having one shortcuts that do multiple things in the middle of a view change...

the best solution I can give for now is to remove the ESC shortcut from "exit fullscreen". This shortcut is even not really useful, as F11 already switch between normal and fullscreen.

I'll try to come with a PR, but I fear that this would only "solve" this for new users, otherwise we'll break too many workflows for old users...

**Comment by quovadit** [comment]
@AlicVB : I also think this is the best solution. F11 always toggles fullscreen (as in most other tools) and esc quits slideshow (as in other slideshow-tools)
My pull request should do exactly this
