### ISSUE TITLE
Segfault on image export

### ISSUE THREAD

**Issue by zinger565** [darktable-org/darktable#7218]
**Describe the bug**

Darktable crashes while attempting to export an image. Logfile attached:
[darktable_bt_341YU0.txt](https://github.com/darktable-org/darktable/files/5648835/darktable_bt_341YU0.txt)

Last known good export occurred Nov. 1st.
Filetype to export is .ARW (Sony RAW), have tried various source and export filepaths.

**To Reproduce**
Open .ARW
Make edits (Local Contrast module seems to be the culprit)
Attempt to export

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1 release 50
 - OS: Solus x86_64
 - DE: Budgie 10.5.2
 - CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
 - GPU: AMD ATI Radeon RX 5700 XT

**Additional context**

 - I can reproduce with Jpeg file. Making an edit with the Local Contrast module causes segfault. Any other module used exports a 1x2 pixel image.
 - Darktable installed from Solus Repo
 - Happens with fresh edit

I have also opened a ticked within the Solus bugtracker: https://dev.getsol.us/T9418

**Comment by Nilvus** [comment]
Some issues have been fixed in local contrast for next release, 3.4. I use on each image that module in master (future 3.4) and doesn't have that issue. And if you used same release (3.2.1) with local contrast before nov 1st, your issue is probably not related to darktable but something on your system. Anyway, as some things and crash related to local contrast, I suggest you to close your issue and wait just less than 3 weeks to install darktable 3.4. You could reopen the issue with more infos after if you still see same issue with 3.4 release.

**Comment by zinger565** [comment]
This answer: https://github.com/darktable-org/darktable/issues/7214#issuecomment-739506115

seems to resolve the segfault. So may stem from a broken config file?

**Comment by johnny-bit** [comment]
Probably a broken config. Integrity check for db is now part of the startup process (at least in master) so it should detect errors faster.
