### ISSUE TITLE
Module grouping settings → Language change

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#7235]
1. Start dt, lets say, in English locale via LANG=en_US.UTF-8 darktable and choose module grouping settings to "modules: all" (hamburger button to the right side below histogram).
2. Start dt in any other locale, lets say French, LANG=fr_FR.UTF-8 darktable

Problem: module grouping settings is reset back to "modules: default". Do not store settings in language dependent format.

**Comment by elstoc** [comment]
Problem is that this potentially leaves darktablerc non-human-readable for non-English speakers (because we'd presumably leave the settings in English).

**Comment by timur-davletshin** [comment]
elstoc, why would anyone bother? Asign views with integers and don't bother with parsing Unicode strings.

**Comment by elstoc** [comment]
Well ok but, apart from translators, I wouldn't expect changing language to be all that common an activity. I take your point but I'm not sure it's worth the effort because there wouldn't be much point doing it only for the module grouping settings.

**Comment by dterrahe** [comment]
> Problem is that this potentially leaves darktablerc non-human-readable for non-English speakers (because we'd presumably leave the settings in English).

This is what we do everywhere. The setting names themselves are in english. Obviously any custom names will be whatever language the user types in, but the built-in options...

There's a similar issue with presets that end up translated in keyboardrc (even the built-in ones). @johnny-bit is going to solve this for 3.4+ ;-) imho it should be possible to exchange darktablerc files (for example to help someone fix an issue) even if not using same language.

Devs should be the ones that change languages regularly to check they didn't break anything. If it is broken by design each time (or if you have to redo all your settings after each switch to get back to the same behavior), this will further complicate/discourage testing.

**Comment by AlicVB** [comment]
well, this "issue" is for all presets, not only modulegroups. It's just more evident there...

If we want to change it, one solution is to add a "unique_id" field to presets. That field will be untranslated, in contrary to the name field. That's doable, but will require quite some work, esp. to ensure backward compatibility... That will also possibly solve problems with duplicate names...

Note that this problem only occurs for built-in presets, not for for user defined ones

**Comment by johnny-bit** [comment]
And making sure that preset names are not translated in choicer but in ui would make this problem go away - unique_id is name in english and everybody's happy :wink:

**Comment by TurboGit** [comment]
Fully agree with last message from @johnny-bit .

**Comment by dterrahe** [comment]
For bauhaus_set_label some changes were required to keep untranslated labels at least long enough to use them for (autogenerated) shortcuts. They are still translated before setting the actual label in the widget.

Question is; would it be too slow to do the translation each time we actually write to the screen (i.e. basically in the pango code). This would solve one issue with #6875. It could also enable on-the-fly language switches, but I don't think that should be a goal in itself. Alternatively, bauhaus could keep both untranslated and (buffered) translated labels. And this pattern could then be used anywhere else where relevant.

**Comment by johnny-bit** [comment]
#6651 and this one share the same underlying issue - translated names
