### ISSUE TITLE
Lighttable styles selection and removal behaviora issues

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7247]
Current master

1.Selecting all styles can only be done by selecting a style and then doing a shift+down arrow, no ctrl+a available to select all. 
2.On selecting all and then clicking the remove button does not remove styles that have a pipe "|" character in them to display its tree structure. The subtree needs to be deleted for them to be removed

**Comment by johnny-bit** [comment]
OK as I read your issue I figured out the issue you have is not the issue you think you have, but your approach to the issue is wrong.

First of all - you can't select ALL styles because that's a tree view and we really rather not apply ALL styles (unless you've got like 2 of them). <kbd>Shift</kbd>+click work too to select multiple styles to apply etc. And tree view does not like to select all elements...

So judging from description it looks like you want to remove all styles and currently you are unable to do so easily... So I made #7607 so you can use reset button that clears all styles :D hope that one fixes the root issue.
