### ISSUE TITLE
[FR] Improve actions (trash / rate) in culling mode

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#7254]
**Problem**
Currently it's not predictable, which image is 'active' in culling mode, if the mouse cursor is not hovered over an image.

Two scenarios where this is problematic:
- I want to trash one image in culling-mode
  - procedure: I click on the desired image, move mouse to the sidepanel to click the button 'trash'
  - expected: click selects one image --> this image is sent to trash
  - current: click has no effect, when leaving center-area no image is highlighted --> all visible images are sent to trash
- I want to rate my images with keyboard only in culling-mode
  - procedure: I start culling with the mouse in a corner (so that the cursor is not in the way)
  - expected: the first visible image is selected when starting culling mode (not only after pressing arrow-right)
  - current: depending on the position of the mouse (?) one of the images is highlighted, but does not always have a white border

The problem is, that you can't just 'select' images in culling-mode, because the selection of images is done on the file-manager view or in the filmstrip to define the set of images used for culling.

So the only way to define images, on which actions should be applied on is the highlighting, which is done by mouse-over.

If mouse has not moved or is not hovered over an image anymore, it's unpredictable which image is 'active' (and therefor gets trashed / rated).

.

**Solution**
In culling-mode there should always be one (1) image highlighted (= it has a white border + all actions are applied on this image)

This is one way to achieve this:
- when starting culling mode, the first visible image gets highlighted and saved as highlighted
- when moving (!) the mouse over an image (in center-area or filmstrip) this image gets highlighted but not saved as highlighted
- when clicking on an image (only in center-area), this image gets highlighted and saved as highlighted
- as soon as the mouse leaves an image (in center-area or filmstrip), the image which is saved as highlighted gets highlighted
- when changing the visible images (by scrolling, pressing an arrow-key or clicking on the filmstrip) the first visible image gets highlighted and saved as highlighted

.

**Alternative**
Only images which were selected in file-manager-view are shown in filmstrip of culling view
- plus: 
  - you can 'select' images in culling view as in file-manager view
  - no need for a new logic 'saved as highlighted'
- minus: 
  - you can't add / remove images via filmstrip anymore
  - the selections in file-manager view and culling view are not the same

**Additional context**
This feature request was created as a result of the discussion in  #6625

**Comment by pahl34** [comment]
To further support this idea:
I noticed that 'copy/paste history stack' is offered in culling and the buttons are active as long as the mouse hovers over an image - 
however, when moving the mouse in oder to klick e. g. the copy button, the button gets deactivated once the mouse leaves the picture. This means, copy/paste history effectively cannot be used while in culling mode (although seemingly offered to the user). I had use cases where I would have liked to use it, but had to switch to file manager first. (Now that I write this, it comes to my mind that there may be a keyboard shortcut for it, which would serve as a workaround. I'll have to check. However, even then this would still be a minor usability flaw in my eyes as it cannot be done with the mouse.)

If I understand correctly,  the feature requested here would also resolve this issue, which would be nice.

**Comment by dbrgn** [comment]
I'd like this to be kept open. I agree that the current behavior is a bit non-intuitive (see #7805).

I primarily use culling mode (with 1 visible image) for my initial selection, not the file manager, because I can switch to an A-vs-B comparison mode by simply changing culling mode to 2 visible images with the mouse wheel, instead of needing to switch the whole viewing mode. I then directly delete the image I don't want. It seems like a very efficient workflow to me, but the selection behavior seems weird at first when expecting selection to work similarly as in file manager mode, especially when deleting images.

**Comment by dbrgn** [comment]
@github-actions, please keep this open 🙂

**Comment by Nilvus** [comment]
> @github-actions, please keep this open slightly_smiling_face

@github-actions is just a bot ;-)

**Comment by gentlecolts** [comment]
To further add onto this: rating images in culling view is also very unpredictable.  Typically I expect that when i star/reject an image, it will affect the current image under my mouse.  This is usually the case, however sometimes all images in the culling view will be affected, even when my mouse is definitely over one specific image.  Not sure if that falls under this issue specifically or if I should open a new bug for it, but it's very frustrating.

**Comment by airflow2010** [comment]
I found this FR as I searched the internet out of desperation about the user-experience of rating images in culling mode.

I assume: Culling mode is for culling (= rating) pictures. Throwing lot's of pictures away (rejecting), keeping and rating the others. Culling mode does many things right, but it strangely fails at one delicate task - to deliver confidence and fidelity about the question what image you're actually rejecting/rating!

When I use culling mode, I typically set the filter to "not rated only" and select a subset of pictures which are similar, then switch to culling mode. I then enjoy the good overview of the images, compare them, if needed zoom to details and compare those. When I decided what image to reject/keep, I execute the decision by pressing r/1/2/etc. Rated and rejected images disappear until I finished the set.

The problem is: While it works in many cases as expected, inevitably when working through larger sets of images, in between you notice you didn't just rate the one image you intended to. But instead the complete set of pictures that were displayed at the same time.

When this happens (and you notice it), you have to switch back to lightroom mode and adjust the filter to "all pictures", re-rate the pictures, switch back to culling mode, reset the filter, until it happens again. After a while I'm frustrated and stop doing this tedious work...

My questions: Has this been identified as a problem which is going to be fixed? As this FR (in my mind, it's a bug) has been open for quite a while, it seems to be not an issue for many. What is your workflow? How can I prevent this from happening?

**Comment by airflow2010** [comment]
This thread describes problems with darktable which have been already present for years, up to the latest stable version 4.0.1 and which frustrates users while doing simple mundane tasks like rating and culling images.

The problem I mean is when the mouse is clearly and definitely over a specific image in culling mode (when multiple images are shown besides each other) and want to act on it. In this case, it often (not always) happens that all displayed images are affected, instead of just the one where the mouse was over.

To bring this issue to the needed attention, I try to illustrate it with two short videos showing the problem in action. Here you have two examples of the same problem. In the [first example](https://youtu.be/KSKJKnIDKG0), I use the zoom-feature. In the [second example](https://youtu.be/rkHYabxZb2I), I don't. But the principle is the same. I used an additional software ("Screenkey") to display the keys I pressed during recording, so you can see exactly what I'm doing. In the comments of the video you see a more detailed explanation with the info of exact moment of problem.

**Comment by Nilvus** [comment]
Keep cool @airflow2010. Even if frustrating, it's possible to deal with by being careful with behavior. I do not say it's the best way but it's what you have control on. Yes it's been there since a time but you just need to remember that darktable is done by people freely in their free time. You can't ask that as it were a software made by a company with paid developers. It's not the case here.

The only way to see things changed is be patient, try to convince people on opened FR/issue (not opened new ones and post repeated comments of a known thing) to change that. And more, as @Solarer tries, propose a PR to change that. Remains to convince other developers to change behavior. And remember that habits do not change easily. It's just how humans works.
