### ISSUE TITLE
Filmstrip: marking two or more pictures in map view

### ISSUE THREAD

**Issue by Messie1** [darktable-org/darktable#7264]
In map view you can move pictures one by one onto the map to geo-tag them. But to tag two or more pictures, taken on the same place, you have to change the view to lighttable, mark them, return to map, adjust map again, and move them onto the map to tag them all. To be able to mark multiple pictures in filmstrip could avoid much work / time. This was possible in older versions.

**Comment by Nilvus** [comment]
Hmmm, as always, please precise which release you use?
Since 3.2.1, in filmstrip, you have to use Alt+click to change selection. Please avoid to answer that it's not a good thing. This has been discussed (and still is) a lot. See #7000. And to learn how darktable use and changes, it's very recommended to read articles in darktable.org/blog. You will certainly learn some things and save your time! For that one, read 3.2.1 article.

If your issue is no more than what I describe here and that answer to your issue, please think about closing it to help darktable team. Thanks.

**Comment by Messie1** [comment]
Sorry, I'm using 3.2.1. And I searched the web, several blogs and discussion groups before. But I couldn't find the solution.

Your answer gave me the inspiration to find the solution: Ctrl-click made the job.

**Comment by Nilvus** [comment]
> Sorry, I'm using 3.2.1. And I searched the web, several blogs and discussion groups before. But I couldn't find the solution.
> 
> Your answer gave me the inspiration to find the solution: Ctrl-click made the job.

Indeed, you correct my mistake!
