### ISSUE TITLE
shrink blending/module group icons in narrow panel

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#7270]
The number if icons in the blending and module group headers have been steadily growing. When reducing the width of the right-hand panel in darkroom, at some point the toggle button icons do not fit anymore, causing the module group settings (hamburger) icon to move out-of-sight (and become unreachable). The blending settings icon is still reachable, but one now needs to use the scrollbar that appears at the bottom of the panel.

This situation cannot simply be avoided by increasing the minimum panel width, because with a larger font size the problem would still occur.

The best/correct solution to this problem would be to make the minimum width of the panel depend on the number of icons that need to be shown and the font size. This would be complicated, because the scrolled window doesn't allow the minimum size to be dictated by the sum of contained items. So this would need to be done with a series of call-backs from panel width, (font) settings, opened modules, module group definitions, which is overly complex.

As a fall-back, rather than menu items becoming unreachable or scrollbars appearing, I think it is preferable for the icon size to shrink. I'm not advocating that this makes such a narrow panel usable. The user will quickly conclude that this is not the case because all text will get ellipsized (but they can then adjust font size if they want). But the behavior when experimenting with the panel width will be nicer, with less scroll bar jumping.

In personal CSS tweaks the desired outcome can be achieved by adding
```
#modules-tabs #dt-toggle-button,
#blending-tabs #dt-toggle-button
{
  min-width: 0em;
  padding-left: 0.1em;
  padding-right: 0.1em;
}
```

@Nilvus I've tried to achieve the same directly in darktable.css (so I could submit a PR) but somehow I cannot get it to work when just adding to or editing the existing #blending-tabs and #modules-tabs settings, of which there are a few. They seem to conflict with each other. Would you be able to make this work? I think the narrower horizontal padding is not a problem, because it will only impact the very narrow situation (otherwise the icons just get evenly spaced and have additional left/right space anyway). When really squeezed I'd rather have slightly larger icons than more space between them.

**Comment by Nilvus** [comment]
I really think we take care too much about narrow panels. The icons has not increased, as they are exactly the same since a long time for module headers and just raster icon had been added last year. The user need to take care about panel size regardless what is displayed. And more, we have now since few months different settings in preferences to change how module headers icons are displayed. A minimal panel width would have been better, even for some higher font sizes.

Anyway, of course, if a CSS tweak could help, I will check that and test your proposal and what I can do to improve that.
I'm not sure make icons shrink would be a good solution but that need to be tested. From what you write, scrollbars should already let the user conclude that reduce panel size too much is a bad idea. And more, we also have shortcuts to quickly hide/show panels.

**Comment by Nilvus** [comment]
@dterrahe: your tweak is just great and indeed it's better with it. To integrate it to darktable.css, this need to be set separately after existing lines (and by removing redundant lines). A PR is coming.

**Comment by dterrahe** [comment]
> I really think we take care too much about narrow panels.

You are right about that, but the reason I do spend time on it is that often translations have longer strings than English, so something that looks fine to me could start looking messed up for somebody else. The UI should "degenerate" in a predictable manner, rather than going ugly, unusable or jumpy, even if the user has (temporarily or accidentally) chosen wrong settings.

> The icons has not increased

Blending has had a settings/hamburger icon added on the right side and module groups are now configurable, so the user can add an unlimited number.

It would be good if we could automatically expand the (minimum size of the) panel to fit all the icons, but that's really hard, so I'm glad you agree this is a worthwhile "fix" to make things look better in extreme cases.

**Comment by Nilvus** [comment]
@dterrahe: my bad, I read "module header" instead of "module GROUP header". Indeed, that had steadily increased.

And yes I totally agree, the fix you propose, and so my PR to correctly integrate that in darktable.css is the best way to do that, as it is simple and will use no CPU at all. Having an automatic way to adjust panel could use a little CPU (for some slower computers, all CPU that we could keep for processing images is good to save!) and if also quite complex to implement, no need to lost time on that. Time would be better spent to improve other things in darktable.

To conclude, I really think your fix is the best compromise.
