### ISSUE TITLE
Problems opening darktable 

### ISSUE THREAD

**Issue by cerlienkus** [darktable-org/darktable#7272]
**Describe the bug**
Darktable doesn't open or, if it does, every characher on the screen is substituted by a square and, in this case, if I open a single picture in darkroom, it crashes.

**To Reproduce**
I've tried to open the application

**Expected behavior**
A normal behaviour

**Screenshots**
Can't provide a screenshot at this time.

**Platform (please complete the following information):**
 - Darktable Version:  3.2.1
 - OS: Ubuntu 20.04 Virtualized with virtualbox on a windows 10 host.

Thanks in advance for your support.

Maurizio Cerlienco

**Comment by Nilvus** [comment]
I use Ubuntu and never had that. If we can't reproduce, it will be hard to help. And as you use darktable in Ubuntu integrated in vitrutalbox, it could be something related to your install and virtualization.

About square character, it's probably font setting issue, so not directly related to darktable. For elegant themes in darktable, you need to have installed Roboto fonts package.

And as darktable support Windows 10, why you don't use directly darktable in Windows 10? You could download Windows package in install page on darktable.org website.

**Comment by johnny-bit** [comment]
We need more data from you in order to be able to asses the problem.

1. have you tried native windows package?
2. have you tried with empty config directory?
3. can you provide output from console of darktable (and backtrace of error)?

for font issues - there should be a fallback anyway so.. is your virtualized ubuntu actually working properly at all for other linux apps?
side question: what advantage does virtualized ubuntu in windows have over native windows package?

**Comment by cerlienkus** [comment]
I think it was a problem of the Ubuntu installation. Probably one of the last update messed things up, including darktable.
I've tried the windows installation and I'm happy with it.
Thanks all of you for the support.
Maurizio
