### ISSUE TITLE
User-created module groups

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#7296]
Devs,
I LOVE the new module groups window! Awesome stuff.
The only thing I'd like to see added is the ability, for any USER-CREATED group, to sort the modules alphabetically.
I quite often know exactly which module I'm looking for, but having them appear in what seems to be a fairly random order (I'm guessing they are sorted by where they appear in the pixelpipe?) makes it difficult to quickly SEE the module I want. But if I could sort them alphabetically, it would be much quicker to find what I'm after.

**Comment by Nilvus** [comment]
The order is and has always been pipeline order. Modules are like layers in Gimp, so first one in bottom on last applied one in top. It's not possible to manage both ways: pipeline order and alphabetical one. And it's needed to see/show pipeline order to correctly process modules.

As you can see, on module groups manager, when you click on + button, modules are there ordered by recommended ones at first, then alphabetically, because here, it's just the list to add them. After, it's pipeline order.

And notice also that you have search field to quickly find a module.

The best way is to use groups to not have a long list in each group and, if possible, in a logical way, like for example what is proposed: technical, color, effects groups, etc.

**Comment by Nilvus** [comment]
Oh last thing: remember that the order could be changed by Shift+ctrl+ drag&drop module but that change is order in pixelpipe, so that's also why it's not possible to sort them alphabetically.

**Comment by brucewilliamsphotography** [comment]
Yeah, I'm aware of all of that. :)
And I didn't want it to affect the pixelpipe order... only the order in which the modules, in their groups, are displayed. The active modules group would still reflect the pixelpipe order.
I was merely asking if it could be implemented within USER-CREATED groups (in the new module management window).
If not, so be it.

**Comment by AlicVB** [comment]
As @Nilvus said this won't happen. All dt interface and functionalities rely on pipe order. If you don't expose it, you don't have anything stable to rely on anymore...
Even if you don't use them, module (re)ordering is a key feature (not to speak about multi-instances)...
Imagine also what would happen in Gimp if you order layers alphabetically...

**Comment by Nilvus** [comment]
> And I didn't want it to affect the pixelpipe order... only the order in which the modules, in their groups, are displayed. The active modules group would still reflect the pixelpipe order.
> I was merely asking if it could be implemented within USER-CREATED groups (in the new module management window).
> If not, so be it.

But, how? The order you see and set in module group manager is the pixelpipe. It can't be the other way as we need to see and have pixelpipe order. What you set in USER CREATED groups is just what module you use and so show. The order remains the pixelpipe order and can't be another way.

**Comment by parafin** [comment]
Having different order of the modules will break consistency and create confusion about the meaning of the order. As @Nilvus said, just create small user-created groups and sort them instead (so horizontally instead of vertically).
