### ISSUE TITLE
3.5 - exiv dependency

### ISSUE THREAD

**Issue by lterlecki** [darktable-org/darktable#7343]
**Describe the bug**
Dependencies in 3.5 releases require: 
  - libexiv2-27 (>= 0.27.3), 
  - libilmbase25 (>= 2.5.3),
  - libjson-glib-1.0-0 (>= 1.5.2),
  - libopenexr25 (>= 2.5.3)
  
  but these version are available since *buntu 20.10, not before.

**To Reproduce**
Get one of this version: https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable and try to install

**Expected behavior**
Installed package

**Screenshots**
`libexiv2-27 is already the newest version (0.27.2-8ubuntu2).`
`Package libilmbase25 has no candidate to install`
`libjson-glib-1.0-0 is already the newest version (1.4.4-2ubuntu2).`

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0~git3.e3efd26b0
 - OS: Mint 20/Ubuntu 20.04

**Additional context**
No additional context

**Comment by parafin** [comment]
This not the right place to report problems with distribution packages.

**Comment by lterlecki** [comment]
You maintain the package, so you are responsible for correctly selecting the required packages for the given distribution and version. And these are wrong.

**Comment by parafin** [comment]
No, we (this project) do not maintain these packages.

**Comment by lterlecki** [comment]
So please give ma a information where I can to complain it.

**Comment by parafin** [comment]
https://bugzilla.opensuse.org/ would be a good bet

**Comment by ptilopteri** [comment]
since is is running Mint rather than a version of openSUSE, better
report to the packagers of Mint which appears in and/or about
http://packages.linuxmint.com/
but I do not know a contact for the particular packager of exiv2

**Comment by KristijanZic** [comment]
I've filed a request for the Ubuntu 20.04 openexr package here:
https://bugs.launchpad.net/ubuntu/+source/openexr/+bug/1908725

I've also filed for Focal fossa exiv2 package here:
https://bugs.launchpad.net/ubuntu/+source/exiv2/+bug/1908726

I don't know where is the libilmbase and libjson-glib ubuntu repo

Anyway when I go to upgrade the darktable form the Ubuntu repo I get:
```
$ sudo apt upgrade darktable
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 darktable : Depends: libexiv2-27 (>= 0.27.3) but 0.27.2-8ubuntu2 is to be installed
             Depends: libilmbase25 (>= 2.5.3) but it is not installable
             Depends: libjson-glib-1.0-0 (>= 1.5.2) but 1.4.4-2ubuntu2 is to be installed
             Depends: libopenexr25 (>= 2.5.3) but it is not installable
E: Broken packages
```

**Comment by ocumo** [comment]
> No, we (this project) do not maintain these packages.

Yeah. But you **do** [**endorse and advertise them**](https://www.darktable.org/install/#3rdparty).

Ergo: it is _your responsibility_ until you stop doing so in your official documentation.

So please do not just fingerpoint somewhere else without first removing those bad references from your **official documentation**, because they do make people waste a lot of time.  It took me several hours of pain googling and troubleshooting, to discover that it's not just "me", and that no one takes owership of this, until I reached to this issue, which is not even directly specific to the problem, although it is absolutely clear about what I am complaining about.   If there is no valid PPA nor working binaries for Ubuntu 20.04, then do not document the opposite.

I was not even trying to install v3.5. Just the v3.2.1.  It is really bad that no one seems to take ownership for a PPA that does not work or of .deb binaries that don't work, and to make it worst, not even the project that advertise them seem to recognize that they are implicitly bound to those - else why putting them in the official install page?

[Officially recommended](https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable) 3rd party PPA for 3.2.1 latest release for Ubuntu 20.04 LTS:

`darktable : Depends: libexiv2-27 (>= 0.27.3) but 0.27.2-8ubuntu2 is to be installed Depends: libilmbase25 (>= 2.5.3) but it is not installable Depends: libjson-glib-1.0-0 (>= 1.5.2) but 1.4.4-2ubuntu2 is to be installed Depends: libopenexr25 (>= 2.5.3) but it is not installable`

and the officially recommended 3rd party binaries for 3.2.1 latest release for Ubuntu 20.04 LTS:

`sudo dpkg -i darktable_3.2.1-1.1_amd64.deb ... dpkg: dependency problems prevent configuration of darktable: darktable depends on libexiv2-27 (>= 0.27.3); however: Version of libexiv2-27:amd64 on system is 0.27.2-8ubuntu2. darktable depends on libilmbase25 (>= 2.5.3); however: Package libilmbase25 is not installed. darktable depends on libjson-glib-1.0-0 (>= 1.5.2); however: Version of libjson-glib-1.0-0:amd64 on system is 1.4.4-2ubuntu2. darktable depends on libopenexr25 (>= 2.5.3); however: Package libopenexr25 is not installed.`

**Comment by parafin** [comment]
No need to go on the rant, you can just ask to amend the documentation on the website in one sentence.
