### ISSUE TITLE
Drawn mask corruption with large feathering

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#7362]
**Describe the bug**
When feathering size of a drawn mask is increased using Shift+Scroll, the mask shape becomes distorted. Reproduced using elliptic mask as well as drawn path.

**To Reproduce**
1. Import the raw + XMP from https://tech.kovacs-telekes.org/files/2020-12-19-edit-elliptic-mask/
2. Display the mask of 'exposure 1'
3. Set image size to 'small'
4. Use Shift+Scroll to adjust feathering size

**Expected behavior**
Feathering region is not distorted

**Screenshots**
![](https://tech.kovacs-telekes.org/files/2020-12-19-edit-elliptic-mask/1.png)
![](https://tech.kovacs-telekes.org/files/2020-12-19-edit-elliptic-mask/2.png)
![](https://tech.kovacs-telekes.org/files/2020-12-19-edit-elliptic-mask/3.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0+2~g610cbd971
 - OS: Ubuntu 20.10
 - OpenCL on/off does not influence the behaviour

**Comment by ralfbrown** [comment]
Confirmed.  It's an interaction between the lens correction and crop&rotate modules and the later drawn shape.  When a shape is drawn, its coordinates get mapped to locations in the original sensor array so that the shape stays in the same place relative to the image even as you crop/rotate/shear/distort it.  You can see this in action by dialing in some rotation in crop&rotate and then going back to `exposure 1` -- you'll see that the ellipse is now tilted.

The mapping is clearly going wonky as the feathering zone passes the side edges of the uncropped (but lens-corrected) image.  Turning off lens correction eliminates the issue (note that you'll have to toggle shape display off and back on to see the difference), so the problem is most likely in one of the distort_* functions in lens.cc.

**Comment by kofa73** [comment]
Reproducible with 3.5.0+719~gc1a75a6ac

**Comment by ralfbrown** [comment]
This appears to have been fixed in master as of about two weeks ago (the lens correction distortion computation was updated).  @kofa73 please check and close this issue if that is the case.

**Comment by kofa73** [comment]
No longer reproducible (the ellipse becomes a circle at very large feathering radius, but I think that's OK or a different issue). Thanks for the fix!
