### ISSUE TITLE
discrepancy in definition of DT_IOP_COLOR_ICC_LEN

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#7368]
**Describe the bug**
The source contains multiple definitions of the symbol DT_IOP_COLOR_ICC_LEN, but they do not all have the same value.
colorin.c, colorout.c, and rgbcurve.c use a value of 512, while lightroom.c uses 100.  The latter matches the value used by legacy parameters in colorin and colorout, so it is likely that lightroom.c was never updated.

**To Reproduce**
See src/iop/colorin.c at line 60, src/iop/colorout.c at line 46, src/iop/rgbcurve.c at line 41, and src/develop/lightroom.c at line 196 (line numbers current as of Dec 19th).

**Comment by johnny-bit** [comment]
it seems that copy in lightroom.c is used to create input params for colorin in dt_lightroom_import because that's the only place that uses dt_iop_colorin_params_t (that match version 1 of colorin params).

So it seems that lightroom.c would need to have rewrite of dt_lightroom_import to newest version of dt_iop_colorin_params_t (and generally have deduplication of that structure via header file?)

**Comment by ralfbrown** [comment]
That would be the proper way to address things.  Less duplication means fewer chances for discrepancies to creep in.

**Comment by johnny-bit** [comment]
Please check if #9691 handles the issue to your liking :)

**Comment by ralfbrown** [comment]
Looks good!
