### ISSUE TITLE
crash de l'app après un export, puis fermeture à chaque lancement

### ISSUE THREAD

**Issue by MarcAureleMork** [darktable-org/darktable#7371]
**Describe the bug**
Lors de l'exportation d'un photo, l'app a crashé, puis après cela, impossible pour moi d'utiliser l'app. J'ai réinstallé sans que l'erreur ne disparaisse.

![2020-12-19_23h54_33](https://user-images.githubusercontent.com/61016486/102701263-88d13f00-4255-11eb-9f53-ee5260810bd6.png)

**Expected behavior**
pouvoir utiliser l'app sans crash ni fermeture

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: windows 10

[darktable_bt_ZM3SV0.txt](https://github.com/darktable-org/darktable/files/5720245/darktable_bt_ZM3SV0.txt)

**Comment by MarcAureleMork** [comment]
[darktable_bt_6SSRV0.txt](https://github.com/darktable-org/darktable/files/5720255/darktable_bt_6SSRV0.txt)

**Comment by johnny-bit** [comment]
Hi,

Reinstalling the app won't fix the problem if problem is present in config/db. Make a backup of `C:\Users\[username]\AppData\Local\darktable` and then remove that dir. Next try again - if you have problem with particular file, we'll need XMP file to investigate the issue.

On another note: dt 3.4 is coming in couple days sowhatever the fix is it's most likelly included in 3.4 :)

**Comment by Nilvus** [comment]
No feedback since more than a month and an issue on an old darktable release. And as darktable 3.4.1 will be out in probably 2 or 3 weeks, I suggest to reopen a more precise issue if this issue is still there with 3.4.1.
