### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by dcendal** [darktable-org/darktable#7414]
**Describe the bug**
In current master the startup of darktable is now much slower than the last time that I compiled it (about 4 months ago).

Lightable is opened almost instantaneous, but then the system freezes for about 25 seconds, during this time I'm not able to interact with the application or see any thumbnail. After that, everything works again.

running with /opt/darktable/bin/darktable -d all  , I get this relevant part of the log (if you need the complete log, please, let me know). The non responsiviness is between 2.621803 and 27.212969
 
_1.931485 [lighttable] expose took 0.0761 sec
2.621803 [run_job-] 03 318115069.886254 2.621824 detect connected printers | queue: 4 | priority: 02.621832 
4.137919 [camera_control] loaded 41 port drivers.
4.162226 [camera_control] 0 cameras connected
8.184205 [camera_control] loaded 41 port drivers.
8.207415 [camera_control] 0 cameras connected
12.228747 [camera_control] loaded 41 port drivers.
12.248481 [camera_control] 0 cameras connected
16.266548 [camera_control] loaded 41 port drivers.
16.288432 [camera_control] 0 cameras connected
20.306431 [camera_control] loaded 41 port drivers.
20.330434 [camera_control] 0 cameras connected
24.352368 [camera_control] loaded 41 port drivers.
24.374980 [camera_control] 0 cameras connected
27.212969 [lighttable] expose took 0.0000 sec
27.213317 [add_job] 0 | 27.213327 load image 7456 mip 1 | queue: 1 | priority: 027.213340 
27.213391 [run_job+] 03 318115094.477844 27.213446 load image 7456 mip 1 | queue: 1 | priority: 427.213482 
27.214429 [mipmap_cache] grab mip 1 for image 7456 from disk cache
27.214548 [run_job-] 03 318115094.479000 27.214585 load image 7456 mip 1 | queue: 1 | priority: 427.214616 
27.222184 [add_job] 0 | 27.222210 load image 7447 mip 1 | queue: 1 | priority: 027.222215_
 
I tried with  option(USE_CAMERA_SUPPORT "Detect and use camera support if available." OFF), but without success, this is the new log.

_2.230200 done in 0.0704 sec 21 thumbs reloaded
[mipmap_cache] thumbs fill 0.00/1027.00 MB (0.00%)
[mipmap_cache] float fill 0/2 slots (0.00%)
[mipmap_cache] full  fill 0/2 slots (0.00%)
[mipmap_cache] level | near match | miss | stand-in | fetches | total rq
[mipmap_cache] thumb |   -nan% |   -nan% |   -nan%  |   -nan% |   -nan%
[mipmap_cache] float |   -nan% |   -nan% |   -nan%  |   -nan% |   -nan%
[mipmap_cache] full  |   -nan% |   -nan% |   -nan%  |   -nan% |   -nan%
2.247259 [lighttable] expose took 0.0876 sec
2.852171 [run_job-] 03 318117034.852633 2.852227 detect connected printers | queue: 4 | priority: 02.852239 
27.533964 [dt_get_system_gui_ppd] system ppd is 1.000000
27.534038 [screen resolution] setting the screen resolution to 96.000000 dpi
27.562583 [lighttable] expose took 0.0000 sec_

**Expected behavior**

 
**Screenshots**
![Screenshot from 2020-12-23 13-12-07](https://user-images.githubusercontent.com/48381321/102995149-b6054200-4520-11eb-8173-a1f0ed5f7ffe.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+127~g54fc5b4dd-dirty
 - OS: Ubuntu 20.04.1 LTS
 - OpenCL yes

**Additional context**
- It's a clean installation
- libgphoto2      2.5.25
- GCC 9.3.0
- build with ./build.sh

**Comment by johnny-bit** [comment]
can you try either current master or build from couple days ago (roughly +80 from 3.5.0 tag?)

also - can you try to generate backtrace during when darktable is hanged by sending sigsegv to it?

**Comment by dcendal** [comment]
Here is the backtrace.

I was doing some bisection with old builds without success.
[darktable_bt_J8FIW0.txt](https://github.com/darktable-org/darktable/files/5735815/darktable_bt_J8FIW0.txt)

I found something in the log and one process is related with Lua, so I deleted luarc from my configuration path and everything is working again.

I put again luarc and disabled all the addons using script manager and same issue.
darktable -d lua give me

1.502464 LUA LUA_DIR is /home/david/.config/darktable/lua
1.506679 LUA found lua scripts directory
1.506714 LUA scripts managed by git
_1.517144 LUA git found at '/usr/bin/git'
27.133478 LUA processing contrib/AutoGrouper_
27.133507 LUA category is contrib
27.133518 LUA name is AutoGrouper
27.133527 LUA category is contrib
27.133530 LUA name is AutoGrouper

Do you think that this issue should go here or i need to open a diffent one in lua-scripts project?
By the way some one give me any direction, I could try to debug it by my self.

**Comment by johnny-bit** [comment]
OK... I don't use lua at all (yet) but it's a bit weird... How about this: remove lua from config and then using built-in script manager install fresh versions of extensions used by you, one by one. That should tell you which is causing problems. Myabe lua-scripts? but i'd ask @wpferguson to take a look :)

**Comment by wpferguson** [comment]
My first thought is that nothing has changed with lua, in the last 4 months, except small bug fixes in the lua-scripts and the horiontal box packing in darktable.  None of those should have caused a performance hit.

My startup has slowed also, but it's before the gui launches.  I figure mine is database checking and backup up since my database is large (~500,000 images).

The only way I can think it would be a lua problem is this: when script_manager starts it does a find on the lua scripts directory, looking for the scripts.  If the disk was really busy because the database was backing up or something else was using it, then possibly the scan could get slowed down, but even then I'm not sure the call is blocking.

I tried disabling lua-scripts and didn't detect any change in startup time.  But, I'm using an SSD... :)

As a test you could try starting darktable like so: 
`darktable -d lua --cachedir $HOME/.cache/dttest --configdir $HOME/.config/dttest`
which would give you a completely clean setup.  Stop darktable and copy the lua scripts and your luarc to $HOME/.config/dttest and then start darktable and see if the startup hang persists.

Another thought.  Looking at your toolbar it looks like you have a lot of programs running.  It could just be swapping to disk because your system is low on memory.

**Comment by dcendal** [comment]
Hello.
Some feedback, with the new version of scripter_manager, is working again.

But first, @wpferguson really good present for chritsmas, thanks a lot for this, it's a pleasure to take a look to the code and use the application!!

By the way, I was doing some additional research, just in case that this could be useful in the future or for other users in the same situation.

The culprint was the next line of the previous version in script_manager.lua, (well, not the line, for sure it's my computer) 
` sm.git_location = df.executable_path_widget({"git"})`
becouse, it ends calling in file.lue something like
 `dt.new_widget("file_chooser_button")`

The line was removed in the new version, and I think that's the reason why it's now working for me now.

If I try to enable some script that contains something with `dt.new_widget("file_chooser_button")`, then I have again the freeze of 2x seconds during the starup (enfused and open in explorer are the ones that I tried), but only the first time in the first script, then everything is OK.

The same occurs if I disable all the scripts restart DT and then try to enable them using the UI, the first time I get this freeze, next times with other scripts is instantaneous..

Thanks a lot for the support

**Comment by dcendal** [comment]
But first, @wpferguson really good present for chritsmas, thanks a lot for this, it's a pleasure to take a look to the code and use the application!!

By the way, I was doing some additional research, just in case that this could be useful in the future or for other users in the same situation.

The culprint was the next line of the previous version in script_manager.lua, (well, not the line, for sure it's my computer) 
` sm.git_location = df.executable_path_widget({"git"})`
becouse, it ends calling in file.lue something like
 `dt.new_widget("file_chooser_button")`

The line was removed in the new version, and I think that's the reason why it's now working for me now.

If I try to enable some script that contains something with `dt.new_widget("file_chooser_button")`, then I have again the freeze of 2x seconds during the starup (enfused and open in explorer are the ones that I tried), but only the first time in the first script, then everything is OK.

The same occurs if I disable all the scripts restart DT and then try to enable them using the UI, the first time I get this freeze, next times with other scripts is instantaneous..

Thanks a lot for the support

**Comment by wpferguson** [comment]
The use of the file chooser button is a side effect of how windows installs packages.  Along with the new script_manager there is also a new check_if_bin_exists that actually searches the likely file system places for executables and caches the result with the  ultimate goal of getting rid of the file_chooser widget except in tools/executable_manager.  The only problem with this is GIMP which I still can't find by searching on windows.  Maybe I'll just add a find_gimp() function sometime in the future.  contrib/gimp also uses the file_chooser widget because of this.

Thanks for the thanks :smile:

I'll look at the file_chooser widget and see if I can figure out what the slowdown is...
