### ISSUE TITLE
Shortcut in double

### ISSUE THREAD

**Issue by hgmarty** [darktable-org/darktable#7436]
Hello,

in a new install from the git version, after I delete the config directory, there is two actions (*2) what have the same shortcut : 
* the module orientation to turn to left and right with [ and ]
* and the shortcut for the brush size with too the same [ et ]

Debian 10 darktable 3.4 from the git
OpenCL with nvidia

Have a good Christmas day

**Comment by johnny-bit** [comment]
Huh... Actually there might be 3:

(introduced 6 years ago by @TurboGit)
https://github.com/darktable-org/darktable/blob/545b7e804166094b28b81308455e2e4f1baca76e/src/views/darkroom.c#L3868-L3869

(introduced 9 years ago by houz)
https://github.com/darktable-org/darktable/blob/545b7e804166094b28b81308455e2e4f1baca76e/src/iop/flip.c#L508-L514

(introduced 2 years ago by AlicVB)
https://github.com/darktable-org/darktable/blob/545b7e804166094b28b81308455e2e4f1baca76e/src/libs/tools/timeline.c#L1437-L1441

The timeline one doesn't clash with darkroom ones since it's limited to lighttable view.

The flip/brush do clash against each other and in my case flip gets preference over brush (even if brush is active and paining). TBH I only adjust brush size with scroll so I've never noticed this before :slightly_smiling_face:

Pinging @elstoc and @dterrahe here :)

**Comment by hgmarty** [comment]
With 3.2 and 3.3, I had the brush size over the orientation but in 3.4 it switched and this shortcuts make orientation. I like use this shortcuts for brush because I can change the size during the brush

**Comment by dterrahe** [comment]
For some reason sometimes brush size _does_ get preference. Not sure exactly which steps lead to this behavior and it is a little confusing because I'd think the order would be predetermined since the shortcuts are set up once during startup. This initialisation code changed significantly for 3.4 and this change in order seems to be an unintended side effect. In any case, not sure what the correct order would be.

I would either use the scroll wheel to change brush size (it works even while keeping left button pressed) or delete the shortcuts for rotate.

**Comment by hgmarty** [comment]
I have deleted the shortcut for the module orientation. I knew with the scroll but i find it's more easy with the shortcuts ;)
For the rest, I leave it for the pros, i don't know about code.

Thanks for darktable

**Comment by johnny-bit** [comment]
@dterrahe , @AlicVB and @elstoc - what dou you think the default shortcuts should be then? :)

**Comment by dterrahe** [comment]
@hgmarty seems to have been able to get the configuration he wants by changing his individual settings. For new users, having a shortcut for orientation is probably more useful than having two ways of adjusting brush size, so I would suggest removing the increase/decrease brush bindings.

**Comment by hgmarty** [comment]
i have changed all the shortcuts and I can change in few weeks for my workflow...
So keep the shortcut for beginners, @dterrahe has right, it's orientation the most important. Few people use the shortcut for brush.
Good evening
