### ISSUE TITLE
Mousewheel doesn't change brush size if CapsLock on

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#7466]
dt 3.4.0    Ubuntu 18.04

When creating a mask with a brush, the mouse wheel normally controls the overall size, but it has no effect if capslock is on.  (Using ctrl or shift with mousewheel continues to work even if capslock is on)

**Comment by johnny-bit** [comment]
LOL... well, i can replicate. Interesting to note is that scroll works normally to adjust sliders when capslock is on, but not for brush size 0.o

looking at `xev` output i can see that event mask is different for scroll with and without capslock on so dunno...

pinging @dterrahe becaus this seems interesting ;)

**Comment by dterrahe** [comment]
Similar to #7288 (merged) and #7289 (not yet merged).

Ralfbrown has started fixing these cases. There are probably many more cases where it is almost-but-not-quite-right.

**Comment by johnny-bit** [comment]
so #7289 didn't help... darn... but then with 3.7 i'm certain that @dterrahe's huge input ng PR will clear all those kinds of issues once and for all :)

**Comment by dterrahe** [comment]
> i'm certain that @dterrahe's huge input ng PR will clear all those kinds of issues once and for all :)

I know you are joking, but just to be clear; in first instance #8078 won't touch these center view handlers at all.

In second (or third) instance the same framework could be extended to also make per-view (or per-mode really) editing controls fully configurable. But to be honest, since these are so heavily mouse based, I expect the benefit to be relatively small. So it would have to lead to considerable code simplification to be worth it imho. Making it all configurable also means needing dynamically adjusting help texts (and a dynamic manual? What's @mica's handle here again?)

What _would_ definitely be useful is to be able to configure midi (or other device) buttons to act as modifiers (alt/ctrl/shift), so the keyboard might almost not be needed at all (and the loupedeck(+) could be more fully supported). Haven't given to much thought to it yet, but with all the work @ralfbrown did in #7289 and before to make all the checks consistent, it should not be too difficult to support widely.

Similarly, allowing Mac users to use CMD instead of CTRL everywhere is probably easy, as soon as one of them provides useful feedback on whether it works in #8078...
