### ISSUE TITLE
3.4.0 - white balance unselected by default in copy / paste

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#7504]
When try copy and paste history an image, the "white balance" modul missing in the list. When use shit+ctr+c all moduls from the history is selected  by default - except "white balance".

It's very annoying when "color calibration" adaption is used, because in this case the white balance must set to "camera reference".

(Otherwise all similar problem maybe goes away, if "color calibration" is automatic set the wb preset to camera reference ;) )

-------------
Ubuntu 20.04 - darktable 3.4.0

**Comment by MStraeten** [comment]
copying whitebalance often can cause a mess, so it's better to have this disabled by default - if you're selecting it, you can't blame darktable for the mess ;)

Since you can use color calibration just as a channel mixer, it's not always helpful if this changes whitebalance settings (you even may have better custom camera whitebalance parameters you want instead of a generic preset)

**Comment by johnny-bit** [comment]
This is in release announcement:

> The history copy has been changed to include only safe modules. Modules like “raw white/black point” and “scale pixels” are no longer copied, for example. To copy such modules, use the “copy parts…” button. Note that the unsafe modules are not selected by default in the resulting dialog.

and blog post says:

> By default the copy button now exclude some modules that can cause issues when pasted between images. You can still include these modules by using the “copy parts” button

in https://darktable-org.github.io/dtdocs/module-reference/utility-modules/lighttable/history-stack/ you can see that:

>     The following modules will be excluded from the copy operation:
>    orientation
    lens correction
    raw black/white point
    rotate pixels
    scale pixels
    white balance

So... "working as intended" :)

Reason: white balance can and will cause mess if copied to different camera model or file type

**Comment by vsz1lu** [comment]
OK, I understand. And retouch is "safe"? And any modul what have mask? ;)

**Comment by johnny-bit** [comment]
Depending on your workflow... But then the disabled modules could shoot user in the foot. Theoretically... Depending on circumstances...

Personally I'd Only disable 
- raw black/white point
- rotate pixels
- scale pixels

due to their limitations.

white balance is problematic since it's very dependent on camera model. with new workflow ad modern color science based on color calibration module it's not a problem and it alsho should be in unsafe modules since modern color science simply expects white balance to be set to d65.
