### ISSUE TITLE
Centralized select & bulk import/export mode

### ISSUE THREAD

**Issue by Lorenzoeffe** [darktable-org/darktable#7506]
It would be very convenient to have a centralized select & bulk import/export mode.
That is a single section in which you can decide to perform a backup:
Settings
database
preset
style
watermark
and more.
This is to export and import quickly in case of formatting or backup

**Comment by MStraeten** [comment]
simply backup your ~/.config/darktable directory.
bulk export of presets is in current master: https://github.com/darktable-org/darktable/pull/7405
imported styles are also as files in your config directory

**Comment by johnny-bit** [comment]
Everything is in your config dir and there's no point in specialized places for "exports" of such things imo.

- Setttings - just copy your darktablerc
- database - the backups are autogenerated now, copying db "somewhere elso" is imo not a job of darktable
- presets are exported either one by one via "save" button in preset configuration dialog or by export functionality introduced in #7405
- styles are exported in styles module
- watermarks are placed in your config dir (afaik) and backuping them will be enough...

> This is to export and import quickly in case of formatting or backup

assuming that you want to re-use database and all paths are the same - backuping whole darktable config dir is the way to go :)

Closing since imo this isn't actionable.
