### ISSUE TITLE
in darkroom, if 2 images have the same timestamp: assigning a rating can change order

### ISSUE THREAD

**Issue by steple** [darktable-org/darktable#7573]
**Describe the bug**
I would call this an inconvenience, not a bug.  This probably works as designed.
In darkroom, if 2 images have the same timestamp and no rating:  If I assign "rejected" to the first image then the order of the two images is swapped.  Hitting space will skip the next other image.  So if I keep hitting space - rating key then I will skip images if the rating is rejected.

**To Reproduce**
Collect 3 images.  2 with the same timestamp (I think same second) and 1 that was taken afterwards.
Set the rating to none for all images.
Go to darkroom for the first images.
Hit R on the keyboard to reject the image.
In the strip at the bottom (not sure what the strip is called), see that what was the first image is now the second image.
Hit space.
Now we are at the 3rd image.
What used to be the second image is now the first.

**Expected behavior**
If I enter darkroom with "View = all" and sort by time and I just advance through the images and rate them, then I would like for the order of the images to not change.
If I had to guess, the images are sorted by timestamp, then rating?

**Screenshots**
Let me know if a screen capture helps.

**Platform (please complete the following information):**
Linux, current master.

**Additional context**
I don't think it's needed.

**Comment by Solarer** [comment]
I also experienced this and figured out what is going on by looking into the code.
Basically, Darktable uses a primary and a secondary ordering function. So in case you order by timestamp and there is a tie, the secondary ordering function will decide the final order.

The default values are configured in `~/.config/darktable/darktablerc` 

> plugins/collection/sort=1
> plugins/collection/sort_second_order=8

Where 1 equals timestamp and 8 equals color rating. (See enum dt_collection_sort_t in [collection.h](https://github.com/darktable-org/darktable/blob/master/src/common/collection.h#L61)

Since I found this annoying myself, I changed it to 7 which is an internal picture id within darktable. This seems to be unique even if you create multiple versions of one file within darktable. Another option would be 10 (filepath) but that collides in case of multiple versions of one picture. 

**Important**:
It looks like the second sort order will be temporally overwritten by whatever you chose as previous sort order. So if you first sort by rating and then sort by color label, all images with the same color label will be sorted by rating next. This will be reset if you close darktable. This is not explained in the darktable [sort order documentation](https://darktable.gitlab.io/doc/en/filtering_and_sort_order.html) and should be added in my opinion.

**Comment by Solarer** [comment]
Can we change the default value for the sort_second_order to 7 and explain in the documentation that darktable can sort by 2 functions at once?

**Comment by steple** [comment]
Thanks @Solarer , your analysis is very helpful to me.

**Comment by rrd1** [comment]
Thanks @Solarer for clarification. The second order sorting was introduced by me some time ago by #2391. I noticed you shared a patch for the documentation for that via mailing list. Thanks again, very appreciated!

**Comment by Solarer** [comment]
@steple can you close this? :)

**Comment by steple** [comment]
Closing.  Works as designed and documentation will be updated.  Thanks @Solarer and @rrd1 .
