### ISSUE TITLE
Error opening darktable.

### ISSUE THREAD

**Issue by Raza786000** [darktable-org/darktable#7592]
Hi,
The program opens but then closes showing the following error.
![image](https://user-images.githubusercontent.com/60373100/103433672-25cb9a80-4bbb-11eb-9e5d-56f9ad172536.png)

I am also attaching the back trace:
[darktable_bt_IHOAW0.txt](https://github.com/darktable-org/darktable/files/5758645/darktable_bt_IHOAW0.txt)

Not sure what is wrong. This happened after I updated from my previous version to v(3.4). Now, none of the versions are working, I tried removing and redownloading but the same error appears.

I would really appreciate any help with this issue.

Thank you in advance.

**Comment by aurelienpierre** [comment]
The function 
```C
void dtgtk_button_override_background_color(GtkDarktableButton *button, GdkRGBA *color)
{
  if(color)
  {
    button->bg = *color;
    button->icon_flags |= CPF_CUSTOM_BG;
  }
  else
    button->icon_flags &= ~CPF_CUSTOM_BG;
}
```
from `src/dtgtk/button.c` is called with a non-inited `*button` from `dt_control_progress_cancellable()`

**Comment by johnny-bit** [comment]
While I don't know how it could reach that state I see that there are very little protections against nulls... I'll try to work on this :)

**Comment by johnny-bit** [comment]
Similar problem reported in #7627 with couple nice backtraces

**Comment by aantonin** [comment]
Hi,
I do have the exact same problem. Since the 3.4, it doesn't work anymore. 
I can open the software but one I try to click on anything, it crash all the time with the same error message of @Raza786000 

[darktable_bt_JD4HW0.txt](https://github.com/darktable-org/darktable/files/5761420/darktable_bt_JD4HW0.txt)
[darktable_bt_NB66V0.txt](https://github.com/darktable-org/darktable/files/5761421/darktable_bt_NB66V0.txt)
[darktable_bt_NSPCW0.txt](https://github.com/darktable-org/darktable/files/5761422/darktable_bt_NSPCW0.txt)
[darktable_bt_Q0M4V0.txt](https://github.com/darktable-org/darktable/files/5761423/darktable_bt_Q0M4V0.txt)
[darktable_bt_Z1X1V0.txt](https://github.com/darktable-org/darktable/files/5761424/darktable_bt_Z1X1V0.txt)

Thanks for the help!
