### ISSUE TITLE
UI glitch with automatic hide of module header buttons 

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#7622]
DT 3.4 on Windows 10, the automatic hide of module header buttons in darkroom does non always work

here are my settings in preferences
![Cattura4](https://user-images.githubusercontent.com/43290988/103454292-d2546c00-4ce2-11eb-94c2-4e9fda3ce8cf.JPG)

To reproduce:
- enter darkroom
- hover one module header
- interact with the header, for example click the preset button
- now click some other module header
- see the first module buttons, they do not disappear

![Cattura5](https://user-images.githubusercontent.com/43290988/103454297-e39d7880-4ce2-11eb-9259-f4a0d941cf2d.JPG)

EDIT: it happens on Linux and current master as well

**Comment by johnny-bit** [comment]
@dterrahe: possible problems with signals?

**Comment by dterrahe** [comment]
It is caused by the fun gtk behavior of `gtk_container_get_focus_child` that is being used to check if the Entry widget for the instance name editing currently exists. This is normally the only widget in the header that can receive focus _except_, apparently, when a buton has been pressed. Then suddenly that button becomes focusable.

So immediately after pressing, say, the reset parameters button, ctrl-pressing the header to edit the name doesn't work either :-(

I'll need to implement an alternative way to detect if the Entry widget is present.
