### ISSUE TITLE
History corruption when pasting, garbled image with 2 contrast EQs

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#7655]
**Describe the bug**
Copying and pasting the history stack, containing multiple contrast equalizer instances, from one image to another results in a rendering that looks like random noise.

**To Reproduce**
1. Download the raws and XMP from https://tech.kovacs-telekes.org/files/2021-01-03-darktable-history-copy-paste-issue/
2. Import into darktable. Lighttable thumbnails: 
![image](https://user-images.githubusercontent.com/3177739/103480059-533e6100-4dd2-11eb-904e-c896bb91fafa.png)
3. Copy history of `2020-05-21_18-32-03_P1020944.RW2`
4. Paste onto `2020-05-21_18-32-12_P1020945.RW2` in append mode
5. Lighttable shows garbage thumbnail: 
![image](https://user-images.githubusercontent.com/3177739/103480088-7a952e00-4dd2-11eb-993f-1e9fadfa07c8.png)
6. darkroom shows garbage image; history shows two instances of contrast equalizer, but processing stack shows only 1 active instance: 
![image](https://user-images.githubusercontent.com/3177739/103480284-cb595680-4dd3-11eb-96a5-f98ef638d845.png)
7. Turning off the single instance does not fix the image:
![image](https://user-images.githubusercontent.com/3177739/103480218-5259ff00-4dd3-11eb-8e86-8a790dd8ad54.png)
8. Compressing the history does not change anything. Selecting to the 'invisible' instance in the history shows a different garbled version:
![image](https://user-images.githubusercontent.com/3177739/103480267-ab299780-4dd3-11eb-9627-352262559a83.png)

**Expected behavior**
History stack is copied. Image is not garbage. Both contrast EQ instances are present in target image's history stack.

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0+40~g1263b3f3a 1263b3f3a
 - OS: Kubuntu 20.10
 - OpenCL activated or no?: not relevant

** Screenshots **
See above. Also, history of source image (contrast EQ at positions 18, 19, 20, 21 and 23):
![image](https://user-images.githubusercontent.com/3177739/103480035-238f5900-4dd2-11eb-9ff3-cbcd17b0b792.png)

**Comment by hancaleil** [comment]
I have the same problem on Windows 10 (Darktable 3.4.0)

**Comment by Nilvus** [comment]
@kofa73 and @hancaleil: this issue is well known and have been fixed since 3.2.1 (it's not related on darktable 3.4 and no more on darktable but about corrupted XMP created before).

To be more precise: it was an issue related to new pipe order introduced in 3.0 and completely fixed in 3.2.1 by @TurboGit. Anyway, already affected XMP with multiple instances (so all possibly before 3.2.1) can't be fixed by darktable work on code. The only way is to ask darktable to create a whole new XMP. The best way is to just clone the image, remove the first one (to remove corrupted XMP/database entry) with the issue and work on the clone.

Indeed, the issue was in generating the XMP before 3.2.1. I'll close this issue as we can't do more here. And I agree that was a very annoying issue that had cause some headaches to @TurboGit.
