### ISSUE TITLE
Culling: Selection cannot be changed

### ISSUE THREAD

**Issue by dbrgn** [darktable-org/darktable#7805]
**Describe the bug**

In light table mode and in file manager mode, I can change the currently selected image by clicking on it.

However, in culling mode, the selection is not updated.

**To Reproduce**

- Go to culling mode
- Set mode to single image with fixed zoom (not sure if relevant)
- Select a different image
- Observe that the selection did not change

I made a video to show this:

https://user-images.githubusercontent.com/105168/104249868-918bee00-546c-11eb-8ef6-eba99dab532f.mp4

**Expected behavior**

I expected that the selection can be changed and was confused by the fact that it didn't. Only after a while I realized that this behavior only happens in culling mode.

Maybe this is intended behavior? I'm not sure. My main issue is that when deleting a file or doing another action, it's not clear which image(s) this action is being applied to. Is it the previewed image? Is it the selected image? Is it the image I'm hovering over with the mouse?

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+557~g713fac470 (current master right now)
 - OS: Arch Linux
 - OpenCL: Yes
 - Nvidia, proprietary driver 460.27.04

**Comment by dbrgn** [comment]
Ah, this issue might actually be closely related to #7254. (Sorry, I did not find that one at first.)

**Comment by Nilvus** [comment]
> Ah, this issue might actually be closely related to #7254. (Sorry, I did not find that one at first.)

You could close yourself an issue you created. Just click below comment editor for that.

**Comment by Nilvus** [comment]
That is the intended behavior, as culling is a compare mode (so not intended to one image only ; for that you have preview mode and preview mode will change selection if you change image). And for culling, keeping first selection could be useful (even if behavior you want also, of course).

In culling mode, the "selected" image for actions (like remove, set stars, etc.) has a light border. You just have to move mouse cursor on the image (or few pixels around) to show that light white border appear. And you know that the image is selected and so actions will be applied on that image.

And as your issue is not an issue and #7254 is a related feature request, I close your issue.
