### ISSUE TITLE
affordable calibration target, alternatives to xrite & datacolor

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#7815]
@aurelienpierre 

The xrite & datacolor calibration targets are great but not really affordable.

I suggest also the IT 8.7 scanner & camera calibration targets from Wolf Faust. (http://www.targets.coloraid.de/)

It would be also a color calibration solution to scanned film pictures.

**Comment by johnny-bit** [comment]
Those are not good targets for color calibration module as they are run-dependent and colors are not constant across runs. They have LOTS of patches and are glossy, which means shooting them properly is super hard (and badly shot targets create even more problems than no targets). With color calibration module it's more about optimizing colors for given shot rather than creating comprehensive profile for camera. Given that one can shoot the target perfectly (the target isn't in hard material, like xrtie & datacolor ones, so using them on location would be a freaking challenge) there's a problem of given run colors: currently all the patches data is hardcoded in module (and for good reason). Having to maintain the list could be super problematic... But if you're willing to got to the lenghts required, you can get all the patches info for your target and it's run, add them to the module and recompile dt for yourself! 

Ultimately - IT 8.7 camera target (C1) is 30€+delivery. Spyder checkr 24 is 45€... 15 eur difference is not so much if one will use the target often ;) And both xrite & datacolor ones can be used on location shooting but i can't imagine using C1 target on location...
