### ISSUE TITLE
Perspective correction

### ISSUE THREAD

**Issue by Lorenzoeffe** [darktable-org/darktable#7818]
Good morning,
I am writing to report that I am having difficulty using the "perspective correction" tool.
I usually select the following:
Guides - deactivated
Auto crop - original size
Lens model - specific

click on Analyze ...
click on Correct ...

Initially the module works correctly, identifies corrects and cuts in the manner indicated.
As soon as I select a new image from the previews below, the newly corrected image loses the "auto crop to original size" and the black side portions are highlighted.
This happened to me with all 3.x.x versions
With the 2.x.x versions of DarkTable this never happened to me.
The method I use is always the same.

I add the following based on a test.
On the other hand, it would seem that if you activate the module searching and correcting, and then later select the automatic cropping in the original format, the module behaves correctly and does not create problems, have you tried?

**Comment by johnny-bit** [comment]
Huh... Indeed there's something wrong with cropping in perspective module... It's "wonky" a bit if you first select that you want to crop to original size and then do analyze & correct.

@AlicVB - since you are already handling #9214 and #6888 - this seems like a same class of problems in perspective correction module. What do you think?
