### ISSUE TITLE
Crop manual (not mouse) size control

### ISSUE THREAD

**Issue by nk8020** [darktable-org/darktable#7847]
Problem:
When cropping, using the mouse, I have to tweak the mouse endlessly to get the right measurements I want (even when using the locked aspect ratio).

Solution:
It would help to have the ability to stretch the initial frame, and get the numbers in the side, and be able to overwrite one (at least) to get a precise dimension.

**Comment by dterrahe** [comment]
This is probably not exactly what you are looking for, but in the crop&rotate module itself, on the second tab, you can right-click on any slider and enter a % border crop width. I realise that you are probably looking for the ability to enter pixel sizes when cropping rather than specifying percentages, but the philosophy of crop& rotate is to chose a visually correct crop for your image, rather than have it be dictated by a technicality, and if your output needs to have exact dimensions in pixels, you enter those in the export module. But if your output is always the same factor reduced compared to you image sensor, you could just calculate the percentage once. Internally the module always works with percentages anyway...

**Comment by nk8020** [comment]
Thanks dterrahe
Already using what you suggested. Noticed that there is marked advantage for me to Crop up to certain sizes (pixel counts) before exporting to a pre-formatted pixel count. I use a 2:'3 or 3:2 rigid aspect ratio. After adjustments I crop artistically (this is where I have a problem with DT), which leaves enough pixels to be further reduced to the final export (Habitually more than 8.3MP which is 4K, preferably twice as many). 
It is nit picking on my side, but really bothering for me, that I cannot draw the crop area roughly, then adjust the measurements for the width & height, then drag it to its final cropping place. I have this option in Capture one express, GIMP and even Paint.net.

**Comment by dterrahe** [comment]
Generally dt developers try to give everybody the options that they want. Which is how we end up with very complex modules that internally need to consider and deal with many different usage patterns. Crop & Rotate is a particularly notorious case, where the experience is that every little change breaks something else that the fly-by-night developer (I've been guilty of this) didn't consider or wasn't even aware of. Hence the hesitancy to add anything on top. Whenever the module gets mentioned, the calls for a complete rewrite start, but that's a daunting task because all existing features will need to be reimplemented (and inventorised first!) or a chorus of complaints will be heard. Complaints, especially future ones, are not typically what motivates volunteer developers. So realistically, it is unlikely that your wish will be granted in the short term. But do feel free to submit it again after that elusive rewrite lands without this feature or when you pick up chatter in the developer channels that someone has actually started the task, to make sure they take it into consideration. For now, I'll leave this bug open in case somebody brave notices it, or you might consider closing it. Thanks!

**Comment by TurboGit** [comment]
@dterrahe : Fully agree !

**Comment by Nilvus** [comment]
@nk8020: a rewrite of crop & rotate is a WIP by @AlicVB. See #8834. Maybe this can be closed and continue in #8834?

**Comment by johnny-bit** [comment]
This should be IMO continued in the scope of #8834. @nk8020 - please add your input there and if you can - test the ongoing work in the current master.
