### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by Rene-RVB** [darktable-org/darktable#7866]
**Is your feature request related to a problem? Please describe.**

I'm frustrated about the IPTC/metada in the light table and very important for archiving historical photos.

**Describe the solution you'd like**

would it be possible to make IPTC/metada evolve by adding some very useful lines?

**Alternatives**

Add in the Metadata Editor panel the few missing lines as shown in the attached visual below, as was the addition of notes.

**Additional context**

![iptc - futur dt eng](https://user-images.githubusercontent.com/45768233/104750515-824ebe00-5754-11eb-9faf-85d29696b550.jpg)

**Comment by phweyland** [comment]
I'll make here a 'personal' answer.

metadata feature is well designed for image specific information, like title, description, notes, ...
It is not appropriate for repetitive information like creator, copy rights, because the information (the same) is duplicated as many time as you have images.
Moreover I think that including all standard (but messy) metadata on the earth in dt does not make sense.

Instead, categories (which are tags) are designed for the repetitive information and your are not constrained by standard metadata at the definition stage.
Then they can be exported in the dedicated standard metadata of your choice. Example:

![image](https://user-images.githubusercontent.com/23012047/104760047-950ac800-573f-11eb-9030-5731e53196ab.png)

Note the usage of $(CATEGORYn(xxx)) which allows you to create virtually an infinity of personal or standard metadata, including hierarchical information.
Note also you can combine different information to build certain metadata (rights for example).

They are also displayed in metadata info if you want them.

Hoping this covers the main of your needs.

**Comment by Nilvus** [comment]
Here we go
