### ISSUE TITLE
Darkroom: jagged, coarse lines, sharp transitions in zoomed-out preview (and also rotation, lens correction?)

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#8016]
**Describe the bug**
While editing an image at less than 100% size, the scaling algorithm creates artefacts. Zooming to 100% or exporting the image proves that the artefacts are the results of scaling.
According to preference tooltip, `plugins/lighttable/export/pixel_interpolator` influences **rotations and lens correction** (darkroom preview is not mentioned, but Paolo suggested at https://discuss.pixls.us/t/darktable-coarse-picture-in-editor/22978/5 that it may be used for the preview, and I was able to confirm that); in that case, these **artefacts could show up in exported images** as well.

**To Reproduce**
1. Set plugins/lighttable/export/pixel_interpolator=lanczos3
2. Get the raw and sidecar files from https://tech.kovacs-telekes.org/files/2021-01-27-darkroom-scaling/, import to darktable
3. Open in darkroom. 

**Expected behavior**
Zoomed-out preview should be displayed without artefacts.

**Screenshots**
Zoomed out image in darkroom vs exported image scaled to same size in Geeqie (in the red frames)
![](https://tech.kovacs-telekes.org/files/2021-01-27-darkroom-scaling/1-zoomed-out-comparison.jpg)

Image at 100% (darkroom vs. exported JPG) shows no/minimal difference:
![](https://tech.kovacs-telekes.org/files/2021-01-27-darkroom-scaling/2-100percent.jpeg)
![](https://tech.kovacs-telekes.org/files/2021-01-27-darkroom-scaling/3-100percent.jpg)

Images scaled using ImageMagick `convert -filter Lanczos *tif -resize 50% 50.png` (using `convert -filter Lanczos *.tif -gamma 0.45454 -resize 50% -gamma 2.2 50.png` made no visible difference):
![](https://tech.kovacs-telekes.org/files/2021-01-27-darkroom-scaling/4-imagemagick-50percent.png)
![](https://tech.kovacs-telekes.org/files/2021-01-27-darkroom-scaling/5-imagemagick-50percent.png)

Switching the interpolation to lanczos2 in darktable reduced the artefacts, but gave worse results than ImageMagick:
![](https://tech.kovacs-telekes.org/files/2021-01-27-darkroom-scaling/6-darkroom-lanczos2.png)
![](https://tech.kovacs-telekes.org/files/2021-01-27-darkroom-scaling/7-darkroom-lanczos2.jpeg)

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+816~g6ecf808b9
 - OS: 64-bit Linux (Ubuntu 20.10)
 - OpenCL on/off makes no difference.
 - Setting `plugins/darkroom/demosaic/quality=full (possibly slow)` makes no difference
 - `preview_downsampling=original`
 - `ui/performance=FALSE`

**Comment by paolodepetrillo** [comment]
The issue of overshoot / undershoot artifacts when interpolating on scene-linear data is mentioned on page 35 of the [Cinematic Color](https://raw.githubusercontent.com/jeremyselan/cinematiccolor/master/ves/Cinematic_Color_VES.pdf) white paper.

If the module color pickers operate on a downscaled preview, then this issue may also be one reason that min / max pickers often pick an outlier value that isn't representative of the actual highest or lowest value in the image.

**Comment by jenshannoschwalm** [comment]
@kofa73, are you sure this is not the same issue as reported in #7756 just presenting in a different setting?

**Comment by paolodepetrillo** [comment]
@jenshannoschwalm I don't think this is related to demosaicing, it looks the same with any demosaic setting. The dark lines are visible when the lanczos3 interpolator is selected, but disappear when the interpolator is changed to bilinear. It looks like it's because of overshoot that occurs at a bright / dark boundary with some interpolators.

**Comment by jenshannoschwalm** [comment]
> I don't think this is related to demosaicing

I don't think so either :-) The issue reported here seems to be subtle differences beacuse of the visual representation (interpolator). So could **this** be the same problem as was understood as subtle differences between smoothing in demosaicers?

**Comment by kofa73** [comment]
I don't think so.
For #7756, I did not switch between the interpolation methods, and the results are random: changing the smoothing either takes effect or it does not. Here I did not switch between the demosaic algos, and the results are consistent: lanczos3 has more artefacts, lanczos2 less.

**Comment by paolodepetrillo** [comment]
A possible problem with this preference is that it does a few different things that maybe shouldn't all be set the same way.

- It sets the interpolation to be used for previews, which affects the way the previews look and could affect performance when zooming, but has no effect on the exported image.
- It effectively acts like a module parameter for lens correction, crop and rotate, and maybe a few others. Even though it's set as a global preference instead of a param within the module, it does affect the module output and exported image.
- When an image is exported with a scale other than 1:1 the selected interpolator is used.

[This issue came up in RawTherapee](https://github.com/Beep6581/RawTherapee/issues/5588) and in that case an option was added specifically to the lens correction module to try to reduce the artifacts. It only uses bicubic interpolation, but it provides the option to do the interpolation in linear (like Darktable) or log space. 

From the [Cinematic Color](https://raw.githubusercontent.com/jeremyselan/cinematiccolor/master/ves/Cinematic_Color_VES.pdf) paper:

> Though log-space processing results in a gross distortion of energy, for conversions which are approximately 1:1 (such as lens distortion effects for plates) this works well.

These artifacts seem to compound on top of each other and look worse when the interpolation that creates the artifacts occurs more than once. For example, I took the image from the original post, with all default settings, and exported it a few different ways:

![bilinear_straight](https://user-images.githubusercontent.com/3238173/106338816-c2d52e00-6262-11eb-929e-0e84e963f481.png)
Bilinear interpolation, scaled down by 0.3. Doesn't introduce the artifacts.

![lanczos3_straight](https://user-images.githubusercontent.com/3238173/106338848-d84a5800-6262-11eb-953b-c7e80a90d184.png)
Lanczos3 interpolation, scaled down by 0.3. Has the artifacts.

![bilinear_rot](https://user-images.githubusercontent.com/3238173/106338890-f3b56300-6262-11eb-8a1a-550c0b2854c4.png)
Bilinear interpolation, scaled down by 0.3 and rotated by 0.5deg, so two interpolations. No artifacts.

![lanczos3_rot](https://user-images.githubusercontent.com/3238173/106338936-12b3f500-6263-11eb-89f0-082fef1b21ff.png)
Lanczos3 interpolation, scaled down by 0.3 and rotated by 0.5deg, so two interpolations. Slightly worse artifacts?

For an image that's rotated, has lens correction for distortion on, and is viewed zoomed out in preview or exported scaled down, there could be three of these interpolations.

**Comment by jenshannoschwalm** [comment]
Yes, looking through the source shows the interpolater chosen by the preference is used at other places like zooming. **Plus** there is cairo_scaling involved at other places...

**Comment by kofa73** [comment]
For the 'bot: still reproducible 815887.

**Comment by jenshannoschwalm** [comment]
Hi @kofa73 and @paolodepetrillo i now found time to come back this after weeks of work and demosaicers, i guess i was a bit blind/deaf about your former messages, you are totally right and the code analysis shows the interpolater defined by the preset is in fact used by many modules.

Was is your opinion about "What should be done?" I would not like to add a bunch of options ... Just document the behaviour?

**Comment by kofa73** [comment]
No problem, Hano. I only update the issue so it does not get closed automatically.
Given how different Gimp and Image/GraphicsMagick scaling look, compared to darktable, I've been wondering if something is wrong with the algorithm implementations (in darktable).

How does darktable do the scaling of the zoomed-out preview? In linear (gamma = 1) encoding, or with gamma (e.g. screen gamma)? I'll try to check that with the following images. :)

![gamma_dalai_lama_gray](https://user-images.githubusercontent.com/3177739/110175355-e6f7d200-7e01-11eb-8b52-02eaf8b21179.jpg)

![gamma-1 0-or-2 2](https://user-images.githubusercontent.com/3177739/110175387-f414c100-7e01-11eb-8f3b-0a605a14c382.png)

**Comment by kofa73** [comment]
It seems gamma is not taken into account either on the screen or during export, if scaling is applied there. Import this into darktable, and export at a size of 128x64 pixel (e.g. to PNG).
http://www.ericbrasseur.org/gamma_2.2.jpg

Also, in darkable, rotate it by 45 degrees, export without rescaling. This is what I got:
Gimp, Cubic interpolation, image in linear light:
![gamma_2 2-45degrees-gimp-cubic](https://user-images.githubusercontent.com/3177739/110177998-1ad4f680-7e06-11eb-983e-c07760185cba.png)

Darktable, bilinear:
![gamma_2 2-45degrees-darktable-bilinear](https://user-images.githubusercontent.com/3177739/110178032-26c0b880-7e06-11eb-8156-33fdfe4ce436.png)

Darktable, bicubic:
![gamma_2 2-45degrees-darktable-bicubic](https://user-images.githubusercontent.com/3177739/110178078-38a25b80-7e06-11eb-86ae-5a674e035551.png)

Darktable, lanczos2:
![gamma_2 2-45degrees-darktable-lanczos2](https://user-images.githubusercontent.com/3177739/110178112-4526b400-7e06-11eb-86bf-9a4794898df2.png)

Darktable, lanczos3:
![gamma_2 2-45degrees-darktable-lanczos3](https://user-images.githubusercontent.com/3177739/110178130-4ce65880-7e06-11eb-885b-bc3b2fac3b47.png)

**Comment by kofa73** [comment]
Sorry for spamming, but it is my understanding that this image, when viewed at a distance, should produce mid-grey. For example, if viewed at 100%, from a distance, it should look uniform grey (and it does, when loaded into darktable). However, it's not only the rotations that break this property: low-pass produces this:
![image](https://user-images.githubusercontent.com/3177739/110179352-36410100-7e08-11eb-80f3-c035e8c850fa.png)

And contrast EQ, with luma & edges dropped all the way down:
![image](https://user-images.githubusercontent.com/3177739/110179452-625c8200-7e08-11eb-806d-8a99104aad03.png)

The input profile was left as sRGB.

**Comment by paolodepetrillo** [comment]
@kofa73 For the issue with your image that is rotated 45 degrees, I was able to make it look correct (all patches roughly the same color) by moving the crop and rotate module after input color profile in the pipeline.
I also opened the jpeg in gimp, converted to 16 bit linear light, saved as a tiff, and opened in darktable. In that case it looks correct rotated, even when crop and rotate is in its default location before input color profile.

I'm not totally sure what's going on here, I think that maybe in the case of the jpeg the image has not yet been converted to linear light when it's being rotated before it has gone through input color profile.

Also, when zooming the preview in and out to an arbitrary zoom level like 50%, the jpeg and the tiff look different. Maybe the raw image is being resized before it goes into the pipeline and gets converted to linear light. If that is really what's happening then any gamma encoded image like a jpeg is going to look incorrect in the preview when zoomed?

**Comment by kofa73** [comment]
Sorry, it has just never occurred to me to check the module order. I always assumed that most operations would be done after the input colour profile is applied, in linear space.

I guess the blurs also have nothing to do with the scaling; but any idea why they (low-pass and contrast EQ) don't blur all segments the same way?

**Comment by jenshannoschwalm** [comment]
The order of the module processing is shown in the left-most module group showing all active modules ...

Anyway we are discussing completely different topics here if i understand your issues correctly, i think we started with possibly a "wrong" pixel interpolator applied and
1. why is this so
2. what would be a better solution, or "Do we need another preference or can we assume another interpolator should be used for modules x,y,z. This is were i am unsure and try to understand your issue so we can agree on something good i would do as an pr. So far i simply dont know. I always leave it at bicubic btw.

**Comment by kofa73** [comment]
Yes, correct, the rotation issues are not related to the interpolation algorithm; and the blurs, neither.
So, let's get back to interpolations. What I see is that the darktable preview produces artefacts, while other software, even when using nominally identical methods, do not (see the ImageMagick `convert` reference in the initial post).
I'm wondering if those artefacts could be eliminated, because:
- since the same algorithms are also used in other places, which directly influence the output, the final image quality may suffer;
- always needing to zoom to 100% to check whether the artefact is the result of an image processing module or just that of the preview scaling is a bother.

**Comment by jenshannoschwalm** [comment]
Ok, for the preview i think there is also cairo scaling involved, could you send your darktablerc please? It will take some days for me to check and test though ...

**Comment by paolodepetrillo** [comment]
I filed #8410 for the issue that was seen with rotation assuming it was unrelated to this issue, but now I think something similar also explains the difference between the images scaled in darktable vs imagemagick in the first post.

As far as I can tell, when an image is exported from darktable at a scale other than 100% or the preview is zoomed to a scale other than 100%, that scaling is performed on the input image pixels at the very beginning of the pipeline, before any other processing occurs (section 3a of dt_dev_pixelpipe_process_rec in pixelpipe_hb.c). So this would look different from the image exported through the entire pipeline at 100% and then scaled down in imagemagick. After having gone through filmic and all the other usual modules the dynamic range is reduced and the artifacts are less severe.

I tried exporting the original image at 100% scale as a linear tiff, then importing it back into darktable and exporting it back out at 50% scale, and it does look similar to the one scaled down through imagemagick. So I don't think there is any difference between the lanczos scaling algorithm in darktable vs imagemagick.


There is a lot of discussion of this issue with scaling artifacts in the imagemagick documentation, and a lot of very long forum threads about it. [This page](https://legacy.imagemagick.org/Usage/filter/nicolas/) shows some examples of the artifacts from various techniques. It sounds like there's not one ideal algorithm that works well on every image or for every upscale / downscale ratio, and there has been a lot of research on ways to improve the scaling. The problem is that a lot of these more complicated algorithms are nonlinear. I'm not sure if it would be worthwhile to try any of these or if bicubic is good enough.

Assuming that this issue will always continue to exist in some cases, it may be worthwhile to make the min / max color picker robust to it - for any image where this artifact exists the min picker is always going to pick a pixel affected by the artifact. I had been experimenting with blurring the image seen by the picker to avoid this (with a 3x3 median filter). It seems to work well enough but I haven't gotten around to testing more or submitting a PR yet.

**Comment by jenshannoschwalm** [comment]
@paolodepetrillo i think your summary is just right.

We might want to have two interpolators, one for lens correction (there we should default to bicubic i think) and another for the rest though where we have lancsos3 as default (here the tooltip should tell that lanc3 might be a bit sharper but might produce halos)

Do you agree on this? For this scenario i have a pr mostly ready ...

**Comment by kofa73** [comment]
@jenshannoschwalm , my darktablerc in case you still need it: https://cp.s701.sureserver.com/fileman/editfile.php?editfile=%2Fwww%2Ftech%2Ffiles%2F2021-03-06-darktable-issue-8016/darktablerc

**Comment by jenshannoschwalm** [comment]
No log in possible :-)

**Comment by kofa73** [comment]
Oops... that was the admin link :)
https://tech.kovacs-telekes.org/files/2021-03-06-darktable-issue-8016/darktablerc

**Comment by ralfbrown** [comment]
Lowpass and Contrast Equalizer both operate in Lab space, which has a nonlinear luma channel....

**Comment by kofa73** [comment]
Thanks

**Comment by jenshannoschwalm** [comment]
Hi maybe you could close this issue, in dt master i think we have a proper config switch for this :-)

**Comment by kofa73** [comment]
The quality is still inferior to post-export resizing, but has certainly improved. Thanks!
