### ISSUE TITLE
Darktable crashses after first click with mouse

### ISSUE THREAD

**Issue by mppronk0462** [darktable-org/darktable#8021]
After installing 3.4.0 I worked with the new version without problems. From one day to the other after some edits Darktable crashes. And now every time I start darktable, I can do something with te mouse, but shortly after that it crashes. It is impossible to work further with my projects.

I work with Darktable 3.4.0 on OS/X version 10.15.7.

**Comment by ralfbrown** [comment]
Looks like something got corrupted (either just before that first crash or as a result of it).  Four main possibilities, with different ways of checking/fixing:

1. Some part of dt's code on the drive got corrupted, either by a hardware fault or an erroneous write from somewhere.  This can be fixed by uninstalling and re-installing.
2. One of dt's main data files: darktablerc (configuration), data.db (presets and the like), library.db (image metadata).  To check whether it's one of these three, you can either temporarily rename dt's configuration directory (~/.config/darktable) or invoke dt from the commandline with an alternate location, import a few images, and see whether the crash persists:
     `darktable --configdir /path/to/alternate/empty/directory`

If the problem goes away with an empty config directory, you can then try narrowing down which of the three files is the culprit.
If neither of the above two suggestions results in a solution, we'll need more information, starting with a log of the output when run with `-d all` on the commandline and a backtrace from the crash.

**Comment by mppronk0462** [comment]
I have renamed the directory in .config where darktable have its files like darktabelc,, data.db an libarry.db. Then I started Darktable and Darktable stays alive. I have imported photo's and can edit is as usual. 
I have decided to import all my photo's and that was succesfull. I can do the things now without delay.

Next week I wil test something to see which file was corrupted.
Many thanks to RalfBrown for the information given.
