### ISSUE TITLE
Lens correction introduces chromatic aberration, resetting to the already set defaults removes them

### ISSUE THREAD

**Issue by fvollmer** [darktable-org/darktable#8039]
**Describe the bug**
If I enable lens correction it adds chromatic abberations to the image. This obviously could be the fault of the profile, but it gets a little bit weirder: If I reset the TCA sliders with a double click the abbereations are gone. The sliders don't change from their default (1.00000), but the image changes.

**To Reproduce**
1. Open darktable, load image into darkroom
![image](https://user-images.githubusercontent.com/16699443/106364303-4ad43a00-632e-11eb-8aa7-6754ec686d7c.png)
2. Enable lens correction (chromatic abberations appear)
![image](https://user-images.githubusercontent.com/16699443/106364321-6dfee980-632e-11eb-9401-eb5f8c9ed684.png)
3. Double click on the TCA red slider (chromatic abberations disappear, but the settings are still the same)
![image](https://user-images.githubusercontent.com/16699443/106365493-4ad83800-6336-11eb-8e88-872b2eb1970b.png)

**Expected behavior**
No changes of of the image if the TCA red slider is reset to the already set default.

**Screenshots**
see above

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10
 - OpenCL enabled
 - NVidia 660Ti

**Additional context**
Example image to reproduce:
[image.zip](https://github.com/darktable-org/darktable/files/5898470/image.zip)

**Comment by paolodepetrillo** [comment]
I'm not sure if it's a bug or intended behavior, but [this line](https://github.com/darktable-org/darktable/blob/04da339e4b8dbf239ee3ef7301bfaffadb0145c3/src/iop/lens.cc#L2102) might be the issue.

When you first enable the module with the default settings, the tca_override flag is false, and it should use the CA settings from the lens' profile. As soon as you touch one of the sliders and set it to a nonzero value, the tca_override flag is set true and now it uses the settings from the slider instead of the lens profile.

The problem is that when you set the sliders back to 1.0 and 1.0, it never sets the tca_override flag back to false and now it uses 1.0 and 1.0, not doing any TCA correction, instead of using the lens profile.

**Comment by fvollmer** [comment]
Thanks for investigating!

Wouldn't it be better to show this in the user interface? I mean there is currently no way to know if the flag is set. Maybe the corrections setting could change?
![image](https://user-images.githubusercontent.com/16699443/106382842-77d22c80-63c2-11eb-8938-9ec9f4087394.png)

**Comment by paolodepetrillo** [comment]
Probably the most straightforward change would be to add a "TCA override" checkbox above the sliders. When the checkbox is unchecked, the sliders would be hidden and the settings from the lens profile would be used. When the checkbox is checked, the sliders would be shown and their settings would be used.

Since the tca_override flag is already present in the module parameters it wouldn't require a new version of the module parameters, it would only be a GUI change.

**Comment by fvollmer** [comment]
@paolodepetrillo I gave it a try and added a checkbox
