### ISSUE TITLE
Pressing "C" to view mask channel data causes flashing stuff on screen

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#8084]
dt 3.4 release   Ubuntu 18.04

The manual says "Press the letter C while hovering over a channel’s input/output slider to view the input/output image data for that color channel..."
I'm finding this causes part of the screen to flash and display weird stuff.  If I move the mouse away whilst holding C the weird stuff becomes still -
![Screenshot from 2021-02-03 13-50-28](https://user-images.githubusercontent.com/16868433/106758063-fd571600-6628-11eb-8d90-c3938931ea7a.png)
Obviously the flashing and the bands are wrong.  Behind though are 4 thumbnails.  I'm not sure what these could be telling me.  Are there not 7 channels going from g to hz?  Please could you explain.

Pressing "M" has a similar effect.

**Comment by da-phil** [comment]
This looks as it could be related to https://github.com/darktable-org/darktable/issues/8076

**Comment by elstoc** [comment]
Just press "c". Don't hold it. It's a toggle.

**Comment by RawConvert** [comment]
I pressed c momentarily and nothing changed.  So held it down a bit longer and got the screen corruption.  Now it won't go! I can reset the module, go back to lighttable, the thumb looks ok, but going back to darktable, the weird bands are back!

**Comment by RawConvert** [comment]
![Screenshot from 2021-05-10 20-41-06](https://user-images.githubusercontent.com/16868433/117715433-27901500-b1d0-11eb-96fd-6a3641803da3.png)

The para mask was in Exposure.

**Comment by elstoc** [comment]
Dunno then. I can't reproduce.

**Comment by johnny-bit** [comment]
This is proooobably too much of a key shortcut application and not cancelling event properly

in order to reproduce you have to keep `c` pressed and after some time due to processing speed shenenigans or something you might start seeing corruption.

I also managed to get
```
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
```

when testing this.

it does not impact image processing afaik.

**Comment by johnny-bit** [comment]
this is still a bit of a problem in `3.7.0+681`

I wonder if this could be a bit alleviated with input ng or simply instead of key press react on key release.

@dterrahe - what would be your suggestion here?

**Comment by dterrahe** [comment]
Input ng doesn't deal with per-widget keys (yet). It is not an easy topic and the payoff may not be that large, unless I get the feeling that bauhaus configurability makes it really worth it.

Correctly swallowing repeating keys means you need to keep track of currently pressed keys (by monitoring key_releases which is a bit of a nuisance, since you might not receive them if the application loses focus or some other situations). But quick and dirty, you could just store the last key received and clear it in key_release and only act on new key_press if it is different from stored key. You may lose a key press now and then (if you're switching between applications a lot) but letting go and pressing it again should resolve that.
