### ISSUE TITLE
Flip Sides in darkroom [Feature Request]

### ISSUE THREAD

**Issue by ohms-law** [darktable-org/darktable#8094]
Hi there,

would it be possible to implement an option to swap the sidebars in the darkroom. I would love to have the modules and histogram on the left side and what is now left on the right side.

I know it is a very personal preference but maybe the devs might give it a thought!?

Best regards everyone

**Comment by dterrahe** [comment]
There kind-of/sort-of is already a way to do this. If you start GtkInspector (pressing CTRL-ALT-D; you may need to be in a text entry field for the shortcut to work) you can then, in the Visual tab, select Text Direction Right-to-Left. It doesn't just swap the panels, but also reverses all button positions and text outlining. Clearly this is not something that is used much, because there are specific bugs (if you want to make a panel narrower, you have to drag the border in the opposite direction) that probably bite everybody that tries to use the application in an RTL language.

@Nilvus is there a way to set this RTL mode in CSS tweaks so that it persists over restarts?

**Comment by Nilvus** [comment]
> @Nilvus is there a way to set this RTL mode in CSS tweaks so that it persists over restarts?

No. For me, this would need a Gtk work to have an option to switch them. And we want to switch only panels, no more.
