### ISSUE TITLE
Blurry images detection tool in lighttable.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#8097]
**Is your feature request related to a problem? Please describe.**
Sometimes when shoot a lot of photos, users have to preview each photo in lighttable to define the focused one, even if the focus-peaking icon is activated. Blurry images is a common thing in a photo shoot. 

**Describe the solution you'd like**
Some script with a kind of visual alert to show the blurry images to reject in a selected film roll of the collect images.

**Alternatives**
Something like the icon of focus-peaking mode, but other to detect blurry images to reject. When the icon is on the boxes showing blurry images got an specific color.

**Additional context**
Web references:
https://www.analyticsvidhya.com/blog/2020/09/how-to-perform-blur-detection-using-opencv-in-python/
https://www.pyimagesearch.com/2015/09/07/blur-detection-with-opencv/
https://www.reginout.com/help-center/how-to-identify-blurry-photos-in-your-photo-library-in-pc-mac/

**Comment by aurelienpierre** [comment]
Automatic blur detection is going to fail in a lot of cases. It's easy to compute the norm of the laplacian in a picture. But then what ? At what threshold do you decide "this is sharp enough" ? Also, the laplacian is unable to differentiate between noise and details, because they are all high frequencies. And then, the picture having the highest laplacian norm may well have a wrong focus, for example if you shoot a subject in front of a background, and the camera makes a back focus, then the more wrong focus will yield the higher norm, and there is no easy numerical way to detect that. 

What you ask is feasible only for pictures shot at f/8 and less and at relatively low ISO, and even then it might not be reliable enough to dispense you from a visual double-check. Focus peaking is much better in that regard, because it lets you see where the focus is, so if you see it in the background, then it's a closed matter.
