### ISSUE TITLE
Segfault selecting any existing filmroll

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#8100]
Hi,
Whenever I select a filmroll darktable crashes. This behavior was introduced with Debians package version 3.4.0-2:
dpkg -s darktable
Package: darktable
Status: install ok installed
Priority: optional
Section: graphics
Installed-Size: 22826
Maintainer: Debian PhotoTools Maintainers <pkg-phototools-devel@lists.alioth.debian.org>
Architecture: amd64
Version: 3.4.0-2

I have attached the core dump file.
[darktable_bt_2G7UX0.txt](https://github.com/darktable-org/darktable/files/5928541/darktable_bt_2G7UX0.txt)

**Comment by mir07** [comment]
Just to mention. I moved the current ~/.config/darktable away and copied the ~/.config/darktable-3.2.1 back to ~/.config/darktable. Under upgrade I instructed darktable to overwrite any xmp files with changes to the state of 3.2.1 and now darktable works again.

**Comment by Nilvus** [comment]
So, I close this issue as you fixed it. Seems that your issue was about your own personal config. And as filmroll is used by many users and never had issues like that, It was probably a corrupted file on your side, and not something darktable team can fix on darktable code. Thanks for posting how you fix it.
