### ISSUE TITLE
Mask visual indication in modules.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#8102]
**Is your feature request related to a problem? Please describe.**
Sometimes working with many masks and modules tend to be confusing. A visual indication like an icon in modules will be a help to locate which modules have masks applied to them.

**Describe the solution you'd like**
An icon with an M (mask) beside the others to show which modules have a mask applied.

![mask indicator](https://user-images.githubusercontent.com/67672868/107002828-d1877d80-6759-11eb-8314-58d648550752.png)

**Comment by johnny-bit** [comment]
Since I use style that doesn't have icons for modules, I'd put `M` indicator where the module icon is... and still I'd put the indicator next to status icon.

Generally I think this is a good idea. I too sometimes have bunch of masks (with multiple instances) and finding which one has and which hasn't would be good. And maybe instead of "just" `M` as an indicator, have mask type icon to distingush type of mask?

**Comment by elstoc** [comment]
The only problem with putting the `M` indicator on the left is that the module names will become mis-aligned (because only some modules will have the indicator), which might look ugly. I'm all for the idea of using the mask icon (assuming they're still legible when rendered that small) but I prefer the icon on the right.

**Comment by Mark-64** [comment]
Shall this be just an indicator or rather a toogle button switching mask on and off ?
and maybe with an icon, rather than a "M", for example
![immagine](https://user-images.githubusercontent.com/43290988/107037414-5656b380-67bb-11eb-9bdb-dac62a1f9f0d.png)
or similar

**Comment by todd-prior** [comment]
This indicator would be more useful I think if say you double clicked or ctrl click on a history line it would take you to that module. Also sometimes you revisit a module and if you enable or disable the mask you would entries for the same module with and without the mask in the stack which depending on the order of events might be weird to look at???  Just thinking out loud. I would vote more for an indication on the module so when you look in the active modules you see if there is an active mask for that module. THis is also a more standard approach used when layers are in play and I always think about the modules a bit like layers .....just my thoughts. Maybe both places would be a good idea it the coding is not crazy.....

**Comment by da-phil** [comment]
>  And maybe instead of "just" `M` as an indicator, have mask type icon to distingush type of mask?

I like that! Then you'd be even able to see whether it's just a drawn mask, parametric or drawn+parametric mask. Using letters in the UI for that would be difficult, I could imagine just using the already used icons for masks, such as:
![Screenshot from 2021-02-05 19-02-45](https://user-images.githubusercontent.com/810285/107072188-12c56f00-67e6-11eb-893f-ad39455a0694.png)

**Comment by todd-prior** [comment]
Nice…..

**Comment by difrkaguilar** [comment]
> > And maybe instead of "just" `M` as an indicator, have mask type icon to distingush type of mask?
> 
> I like that! Then you'd be even able to see whether it's just a drawn mask, parametric or drawn+parametric mask. Using letters in the UI for that would be difficult, I could imagine just using the already used icons for masks, such as:
> ![Screenshot from 2021-02-05 19-02-45](https://user-images.githubusercontent.com/810285/107072188-12c56f00-67e6-11eb-893f-ad39455a0694.png)

I had this idea in mind, but I changed from the diferents mask icons to an M first because I don't know if icons of masks are in .svg and allow scalability, and as each one is different from the other is a little mess.
I put the M into an square because have more integration with the actual icons and even when I know isn't recommended use letters in icons, the M is the first letter for mask in many languages.
Anyway, using icons or a M will be a nice addition to know when a mask is active in modules.

**Comment by RawConvert** [comment]
Here's what I do, which helps with the question of which modules have masks.
Firstly, have a rule that if you're using a mask, then it must be on a new instance of the module.  Hence you know if there's no number after the name then there's no mask.
Secondly, use the rename facility and give the instance a meaningful handle that will prevent confusion, especially if you come back to it in a month's time.  E.g. "exposure lighten eyes"
Saves a development? :)

**Comment by elstoc** [comment]
Icon needs to be a bit smaller than the example though, to match the other icons on the header.

If it was clickable, to toggle mask view on/off, that would be cool too :)

**Comment by TurboGit** [comment]
Yes, smaller like the initial proposal. And I think a single icon just for masks (drawn or parametric) would be ok. Having a small icon with pencil or symbols for parametric will be hard to read. Again the initial proposal seems good enough to me. We can eventually add a tooltip over this icon to list the actual masks kind used.

**Comment by elstoc** [comment]
It could just use the same icon as the show/hide masks button.

**Comment by aurelienpierre** [comment]
I think this raises a more general question about whom/what hardware we target. This will obviously penalize users with small screens and laptops by taking more display real-estate.

**Comment by difrkaguilar** [comment]
> I think this raises a more general question about whom/what hardware we target. This will obviously penalize users with small screens and laptops by taking more display real-estate.

In that case this will be a solution for it.
![Screenshot_20210207_233628-1](https://user-images.githubusercontent.com/67672868/107177390-bf971c00-699f-11eb-8155-b56242a3162d.png)

**Comment by elstoc** [comment]
New preference. Controversial.

**Comment by dterrahe** [comment]
> This will obviously penalize users with small screens and laptops by taking more display real-estate.

There might also be an intentional/unintentional interaction of this with the "show right-side buttons" functionality that tries to address that issue. I.e. if that is set to "active" should the mask icon be hidden most of the time as well? If not (mask icon always visible) it will jump left and right as the other three icons are (un)hidden).

A (controversial?) solution to this could be to have the mask icon left aligned, immediately at the _end_ of the module name. Possibly _only_ if the visibility of the three right-side buttons is variable? (i.e. if the buttons are always visible (dimmed or not) then have the mask icon in that group as per the mock ups above, but if any if the variable "show right-side" options are selected, then have the mask button at the end of the module name.

**Comment by RawConvert** [comment]
It all sounds quite complicated for what is largely a cosmetic change.  I wonder how many people use masks AND have difficulty seeing what they've done AND couldn't sort it out by using the naming facility.
Why was naming introduced? - probably to make the pipeline/edits clearer to the user!
If you adopt a discipline it's easy.  The base instance applies to whole image. Other instances have a mask, or can apply to the whole image, and you can name them to make clear what the instance is doing.

**Comment by TurboGit** [comment]
Yes, I tend to agree with @RawConvert, this is becoming overly complex.

**Comment by johnny-bit** [comment]
I think  #8352 introduced it and so this issue can be closed :)
