### ISSUE TITLE
Relative RPATH is set incorrectly

### ISSUE THREAD

**Issue by mikhailnov** [darktable-org/darktable#8122]
Currently RPATH is set incorrectly.           
/usr/bin/darktable has RPATH '$ORIGIN/..//usr/lib64/darktable'. 
So, rtld will try to look for libraries in /usr/bin/../usr/lib64/darktable -> /usr/usr/lib64/darktable,
but this path is incorrect. 
RPATH is also set in other files, for example, /usr/lib64/darktable/plugins/imageio/format/libcopy.so
has RPATH '$ORIGIN/..//usr/lib64/darktable', which is also incorrect.

**Comment by mikhailnov** [comment]
A workaround is:

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -71,7 +71,7 @@ if (APPLE)
     set(CMAKE_MACOSX_RPATH ON)
     set(CMAKE_INSTALL_LIBDIR_RPATH @loader_path/../${CMAKE_INSTALL_LIBDIR}/darktable)
 else()
-    set(CMAKE_INSTALL_LIBDIR_RPATH $ORIGIN/../${CMAKE_INSTALL_LIBDIR}/darktable)
+    set(CMAKE_INSTALL_LIBDIR_RPATH ${CMAKE_INSTALL_LIBDIR}/darktable)
 endif()
 
 if (USE_OPENMP)
```

**Comment by johnny-bit** [comment]
@codingdave - how would proposed workaround interfere with your PR that made it easy to run from build dir?

**Comment by mikhailnov** [comment]
I called this a workaround, but not a fix, because it will break running from the build directory.

**Comment by johnny-bit** [comment]
Ayyy... Can we have the cake and eat it too?

**Comment by mikhailnov** [comment]
What is the structure of files onside the build dir?

**Comment by mikhailnov** [comment]
Actually I would not care about running from the build directory, those who need it may set LD_LIBRARY_PATH I think.

**Comment by johnny-bit** [comment]
Actually running from build directory makes it very nice to run and debug from within IDEs such as vs code ;)

**Comment by parafin** [comment]
How exactly do you build darktable? Because /usr is usually part of prefix, not libdir. Anyway correct fix is to use REL_BIN_TO_LIBDIR instead of ../${CMAKE_INSTALL_LIBDIR}/darktable

**Comment by parafin** [comment]
As for files other than main executable - RPATH on Linux is indeed incorrect, but I guess it basically isn't needed, since libdarktable.so is already loaded at that point. The fact that it works I think proves it, so we should just remove RPATH from those files altogether (after testing it of course).

**Comment by codingdave** [comment]
@parafin you have a good overview. I guess this will be it.

**Comment by mikhailnov** [comment]
6 февраля 2021 г. 22:55:53 GMT+03:00, parafin <notifications@github.com> пишет:
>How exactly do you build darktable? Because /usr is usually part of
>prefix, not libdir. Anyway correct fix is to use REL_BIN_TO_LIBDIR
>instead of ../${CMAKE_INSTALL_LIBDIR}/darktable
%build %cmake \ 	-DCMAKE_BUILD_TYPE:STRING=Release \ 	-DBINARY_PACKAGE_BUILD:BOOLEAN=ON \ 	-DUSE_OPENCL=ON \ 	-DRAWSPEED_ENABLE_LTO=%{_use_rawspeed_lto} \ 	-DPROJECT_VERSION:STRING="%{version}" \ 	-DCMAKE_LIBRARY_PATH:PATH=%{_libdir} 

%_libdir == /usr/lib64

I thought about changing CMAKE_LIBRARY_PATH no be /lib64 instead of /usr/lib64, but that is probably not a good solution.

**Comment by mikhailnov** [comment]
6 февраля 2021 г. 23:03:31 GMT+03:00, parafin <notifications@github.com> пишет:
>As for files other than main executable - RPATH on Linux is indeed
>incorrect, but I guess it basically isn't needed, since libdarktable.so
>is already loaded at that point. The fact that it works I think proves
>it, so we should just remove RPATH from those files altogether (after
>testing it of course).

If those files use symbols from libdarktable.so, I would better avoid unresolvable symbols from the point of view of different methods of analyzing ELFs.

**Comment by parafin** [comment]
> %build %cmake \ -DCMAKE_BUILD_TYPE:STRING=Release \ -DBINARY_PACKAGE_BUILD:BOOLEAN=ON \ -DUSE_OPENCL=ON \ -DRAWSPEED_ENABLE_LTO=%{_use_rawspeed_lto} \ -DPROJECT_VERSION:STRING="%{version}" \ -DCMAKE_LIBRARY_PATH:PATH=%{_libdir} %_libdir == /usr/lib64 I thought about changing CMAKE_LIBRARY_PATH no be /lib64 instead of /usr/lib64, but that is probably not a good solution.

I'm guessing the interesting cmake variables are set somewhere else. Because if you just run cmake from console it will install files into /usr/local. CMAKE_LIBRARY_PATH is unrelated to install libdir.

Anywany, your setup is IMHO strange, but still valid, so it's a real bug with solution already proposed.

**Comment by parafin** [comment]
> If those files use symbols from libdarktable.so, I would better avoid unresolvable symbols from the point of view of different methods of analyzing ELFs.

I tend to agree, so someone needs to fix cmake files to use correct relative RPATH for all those shared modules. Just using CMAKE_INSTALL_LIBDIR_RPATH is incorrect (except for executables installed into bindir). BTW I now realized that it's also wrong on macOS too.

**Comment by mikhailnov** [comment]
> I'm guessing the interesting cmake variables are set somewhere else. Because if you just run cmake from console it will install files into /usr/local. CMAKE_LIBRARY_PATH is unrelated to install libdir.

Yes. Prefix is set inside the `%cmake` RPM macro. In expanded form it is this:
```
$ rpmspec --parse darktable.spec
<...>
    mkdir -p build 
    cd build 
    /usr/bin/cmake .. \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
        -DLIB_SUFFIX=64 \
         \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DBUILD_SHARED_LIBS:BOOL=ON \
        -DBUILD_STATIC_LIBS:BOOL=OFF \
        -DCMAKE_MODULE_LINKER_FLAGS="-O2 -fomit-frame-pointer -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -fstack-protector-strong --param=ssp-buffer-size=4 -m64 -mtune=generic -Wl,-O2  -Wl,--no-undefined   -Wl,--unresolved-symbols=ignore-all" \
        -DCMAKE_BUILD_TYPE:STRING=Release \
        -DBINARY_PACKAGE_BUILD:BOOLEAN=ON \
        -DUSE_OPENCL=ON \
        -DRAWSPEED_ENABLE_LTO="ON" \
        -DPROJECT_VERSION:STRING="3.4.0" \
        -DCMAKE_LIBRARY_PATH:PATH=/usr/lib64
```

spec is here: https://abf.io/import/darktable

> I tend to agree, so someone needs to fix cmake files to use correct relative RPATH for all those shared modules.

Yes. Unfortunately I am not an expert in cmake and tend to deal with it not well.

**Comment by parafin** [comment]
These settings look like quite a mess to me to be honest:

1. INCLUDE_INSTALL_DIR, LIB_INSTALL_DIR, SYSCONF_INSTALL_DIR, and SHARE_INSTALL_PREFIX aren't used for anything - all cmake variables start with CMAKE_ prefix (so e.g. CMAKE_INSTALL_INCLUDEDIR), and darktable doesn't install include files or system configs anyway.
2. CMAKE_LIBRARY_PATH is most likely not needed, and anyway is incorrect way to set this search path. Instead of it and LIB_SUFFIX you should use variables like CMAKE_SYSTEM_LIBRARY_PATH, CMAKE_SYSTEM_PREFIX_PATH and CMAKE_FIND_LIBRARY_CUSTOM_LIB_SUFFIX. But I strongly suspect that cmake does the right thing by default anyway.
3. CMAKE_INSTALL_LIBDIR can be relative to CMAKE_INSTALL_PREFIX, so just lib64 instead of /usr/lib64, it will fix this particular issue. Or maybe it can be skipped altogether, again cmake might do the right thing anyway here, not sure.

I have no idea how settings mentioned in 1 came to be, I suspect it's for some very old backwards compatibility reasons for other packages. Point 2 isn't a big deal, so you can investigate it in your own time. Point 3 is what triggers this darktable bug, it's an allowed configuration, but maybe it can be amended on your side too?

**Comment by parafin** [comment]
This is an old bug, and I've fixed some rpath problems not long ago, so I suppose this is already fixed or not really a bug. I gonna close, please create a new bug if there's still problems.
