### ISSUE TITLE
Possible bug in masks

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#8216]
Hi one and all.
I may have found a bug in the masking operations (or this may already be something you're aware of... not sure).
After much trial and error, these are the steps I've found to reproduce it:

Pick any module (I was using Colorize for my testing)
Enable drawn+parametric mask
Add a circle mask to the image
Add a brush stroke mask to the image
Toggle all channels polarity
(Combine masks dropdown has now automatically changed to 'inclusive')
Change back to 'exclusive' mode, and the circle and brush stroke are ignored. Their paths are shown, but they no longer mask the image.

From my testing, it seems to be the existence of the brush stroke mask which causes the failure.
Do it with just the circle mask, and upon switching from 'inclusive' back to 'exclusive', the shape is respected and the mask works as expected.
But the introduction of the brush seems to break it.

Again, Linux mint 20, cinnamon DE.

**Comment by todd-prior** [comment]
@brucewilliamsphotography 
Likely part of this stuff ....https://github.com/darktable-org/darktable/issues/8172#issue-805429633
Up until now i had only notice a difference if you made the changes manually. If you used toggle all it had seemed okay but I hadn't tried a brush mask.....

**Comment by jenshannoschwalm** [comment]
@brucewilliamsphotography is this still valid with ccurrent master?

**Comment by todd-prior** [comment]
It seems to be working for me on 3.5.0+2399~g0bb81f9cb using Windows.

One thing I still don’t understand. So maybe it’s the way I rationalize the math. But for example the default condition of exclusive should produce a combined mask where the drawn and the parametric mask overlap and nothing else. This means in my head where both masks are 1 (positive??). In non selected areas ie where either mask is 0 or not selected there is no masking. In these conditions we start with  + polarity for the parametric mask so + is 1. Then  why is that not the same for the drawn mask??   It starts with a negative polarity??  In all mask combinations if I use the rule exclusive where both masks are 1 and inclusive where the either mask is one so that only where the masks are both zero the image is unmasked I see the expected area masked. If you toggle the channels manually it follows that rule but only if you assume the drawn mask with negative polarity indicates 1 for the drawn selection and a positive polarity for the parametric selection. I would think the starting channel polarities should all be +…. I have asked before a couple of times and nobody seemed to provide an answer??

Perhaps you can clarify it?

**Comment by johnny-bit** [comment]
Not reproducible in 3.7.0+681 using provide reproduction steps.

Please check newest master or 3.6 release if it still has the problem you're experiencing.
