### ISSUE TITLE
Don't rely on user to delete lock files when darktable crashed

### ISSUE THREAD

**Issue by qosch** [darktable-org/darktable#8239]
**Is your feature request related to a problem? Please describe.**
I recently worked on large (~2GB per image) panoramas and darktable crashed a few times (nothing I could reproduce and report, yet) and showed the "database locked" error message when restarting. To me it was only annoying to navigate through the series of hidden directories to delete the lock files by hand, but to the average lightroom user this could very well be a show stopper (leading to forum posts and suggestions to reinstall darktable).

**Describe the solution you'd like**
I can't really say how this would be handled best, but maybe we can get rid of this error message somehow?

**Comment by Nilvus** [comment]
This error message was added because some users don't understand what to do. Lock files are here to avoid having 2 instances of darktable. Having 2 instances of darktable would just increase a lot worst errors and especially bad writings in darktable database.

So we can't get rid of this error as we have had many more complaints before adding this message. Removing 2 lock files with the path and explanation is not something hard. And sometimes, the first thing is to be sure there's not another process not completely closed. So that's why we let that to the user. It can be safely done totally automatically. I will let this a little more open if someone else in darktable team want to complete (or anything else) but this will probably won't change by now.

**Comment by qosch** [comment]
And there is no other ways to check whether another instance is running? How do other programs solve this (I guess it's easier for non cross platform Software?)

**Comment by Nilvus** [comment]
> And there is no other ways to check whether another instance is running? How do other programs solve this (I guess it's easier for non cross platform Software?)

Some don't even check that. And as you correctly said, it's easier for non cross platform software. Each system has it's own way. If it was easy, that would have been done already, instead of adding this error message. And even if it's done, not sure it's safer. Sometimes, letting the user check (with a todo like actually) is safer and so better. Even if it's seems annoying.

**Comment by quovadit** [comment]
it would help, if the path shown in the message could be selected or even clicked

And I would shorten the text, for example:

```
Sorry, darktable could not be started (database is locked)

How to solve:
- check if darktable is already running (might be process id 1234)
- if you can't find it -> restart your computer
- if you still get this error after the restart: 
  + open your config folder (click here: /home/xxx/.config/darktable)
  + manually delete the file[s] xxx.db.lock [and yyy.db.lock]
 
```

**Comment by phweyland** [comment]
In case lock files are present it could possible to show a popup inviting the user to one of these choices:
- exit
- delete lock files.

The user can then check if there is another running instance and give the right answer.
