### ISSUE TITLE
Database Portability

### ISSUE THREAD

**Issue by WillyKirsch** [darktable-org/darktable#8285]
It will be nice if there is a possibility of targeting in the settings where is the database , this will give the possibility to work on external drives and with different databases/catalogs too.

**Comment by johnny-bit** [comment]
This is already possible via either `--library` or `--configdir` options and possibly `--conf` options on commandline.

There is no possibility of switching library or data dbs during program run, that's why there's no GUI config option for that.

See https://www.darktable.org/usermanual/en/special-topics/program-invocation/darktable/

**Comment by WillyKirsch** [comment]
Thank You! I understand that addressing a new DB on the flight its not an option, but making a restart?

anyway there is a way!!

**Comment by johnny-bit** [comment]
We'd have to rebuild a shitton of stuff in order to be able to support swithcing db don the fly and it's not something worthwhile if we can get around it with commandline ;) For example i have 3 dbs that i use and 3 dt shortcuts :)

**Comment by WillyKirsch** [comment]
I got it! Thank You!
