### ISSUE TITLE
When culling a selected set, ratings are applied to all

### ISSUE THREAD

**Issue by greymont** [darktable-org/darktable#8302]
**Describe the bug**
From the lighttable File Manager mode, I select a set of images that I want to cull. With them selected I enter culling mode. The filmstrip shows all images and the selected set is highlighted, so they are still selected. Culling mode allows me to scroll back and forth only within the selected set, which is fine, but it shows the to-be-culled set is known. If I now set the rating on an image, that rating gets applied to ALL the images in the selected set instead of the one I am currently looking at. **Surely this is not the intended behavior while culling!?**

**To Reproduce**
Just follow the steps in the description. This happens whether or not you use the number keys to set the star rating or click on the stars superimposed on an image being culled.

**Expected behavior**
I expect only the current image to have its rating changed while in culling mode. That is what happens when I enter culling mode without a set of images selected.

**Screenshots**
n/a

**Platform (please complete the following information):**
 - Darktable Version: 3.4.1.1
 - OS: Windows 10
 - OpenCL activated
 - Which graphics card:  NVIDIA Quadro K1200

**Additional context**
If this is intended behavior, what is the proper method of culling a subset of images? That is, how to get the subset into culling mode without selecting them in file manager mode first? I cannot de-select the selected set in culling mode using the filmstrip. Clicking on one image just makes it current and does not de-select the others.

**Comment by Nilvus** [comment]
It's the intended behavior. Or to be more precise, it depends on how you use culling mode. Culling mode is made to compare images and you then have 2 possible ways:

- Applied only in one image rating or color labels for example. For that, you need to be sure the wanted image is highlighted (move cursor on the image and see white border to show that). Then, if you rate stars, you will see that only that image have new rating applied.
- If no image is highlighted, so no white border on any image of selection, then that means you want to apply rating on all selected images.

So could you check all that and if image is highlighted or not? I've just tried in master and it work as described (and wanted) here.So should be too in 3.4.1.1 as I don't remember any update on culling mode since 3.4.1.1.

**Comment by greymont** [comment]
What you have described is exactly what is not working, hence my bug report. But I just went back and tried it again and it now works as you described. So I will keep watching and try to see what circumstances caused it to fail.

**Comment by Nilvus** [comment]
> What you have described is exactly what is not working, hence my bug report. But I just went back and tried it again and it now works as you described. So I will keep watching and try to see what circumstances caused it to fail.

So for now, as you have it finally as described, I close your issue. Feel free to reopen if you have more information and find a way to always reproduce the issue you report here. If you can't reopen, just add a comment with the precise way to reproduce and ping me to reopen.

**Comment by quovadit** [comment]
looks like a duplicate of #7254

**Comment by Nilvus** [comment]
> looks like a duplicate of #7254

Not a duplicate but related. This is posted as bug and it's not. #7254 is a discussion of the actual behavior and the question of changing it. So not same thing, even if it's related.
