### ISSUE TITLE
2nd instance of module always remaining expanded

### ISSUE THREAD

**Issue by phil20099** [darktable-org/darktable#8306]
**Describe the bug**
When I have a second instance of a module that module is always expanding when I go into the image even if I collapsed it the previous time.

The issue only occurs when using a second instance and it’s not limited to the same module.

**To Reproduce**
- collapse all modules, move from one image to the next, all modules remain collapsed as expected
- move back to the previous image, all modules remain collapsed as expected
- create a new instance of any module then collapse it
- move to the next image then back to the previous image and the new instance will be expanded even though you collapsed it last time

**Expected behavior**
Where there is no second instance the modules behave as I would expect :
- if I close all modules they remain closed when I move to the next image or back to the previous image.
- if I open a module (e.g. filmic) it remains open when I move to the next image or back to the previous image.

I expect the same behaviour for any additional instances.

**Platform (please complete the following information):**
 - Darktable Version: v3.4.1 and v3.5 built from source today
 - OS: Ubuntu 20.04
 - opencl is activated
 - Nvidia GeForce GTX670

**Additional context**
This might seem trivial but it’s really frustrating when you want to check the settings in a module across images.

**Comment by elstoc** [comment]
I suppose in fixing this there's a more general question about how we would _like_ this to work. One of the issues is that darktable stores which module(s) were last expanded but is currently only able to do this by the module name. So, for example, darktable might store that "exposure" is currently expanded (or not) - this cannot handle multiple instances right now. 

Where there are multiple instances of exposure on an image, which one should be expanded? You can't determine it using instance name, because exposure could be named differently on any one of your images. Do you only expand the first one in the pipe? Only the last in the pipe? All of them?

**Comment by phil20099** [comment]
I can definitely appreciate the challenges.

_All of them ?_
This may work against the "expand a single module at a time" preference.

_None?_
From my point of view this is better than always expanding it but others may think differently.

Perhaps it's based on the "expand a single module at a time" preference :
- ticked : never expand 2nd and subsequent instances
- blank : always expand 2nd and subsequent instances

Not ideal I know but it at least gives the user some sort of choice.

**Comment by elstoc** [comment]
> ticked : never expand 2nd and subsequent instances

Problem is it's not always possible to identify which is the "second" instance unless you do so by pipe order
