### ISSUE TITLE
Copy-paste modern chromatic adaptation history stack when the default is legacy

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#8309]
**Describe the bug**
Copy-pasting a history stack from an image with a modern chromatic adaption to another image when the default  is set to legacy produces an error.

**To Reproduce**
1. Set auto-apply chromatic adaptation defaults to _modern_
2. Edit an image
3. Create a duplicate
4. Remove history stack from the duplicate
5. Set auto-apply chromatic adaptation defaults to _legacy_
6. Copy-paste the history stack from the original to the duplicate
7. See the difference

**Screenshots**
orginal on the left, copy-paste on the right
![image](https://user-images.githubusercontent.com/18402158/108896903-27936680-761e-11eb-82fb-85d6a1978e93.png)
history stack of the duplicate
![image](https://user-images.githubusercontent.com/18402158/108897141-73461000-761e-11eb-9e40-f8cc4d571021.png)

When running from command line I can see
```
[color calibration] white balance error
[color calibration] white balance error
[white balance] double application of white balance
[white balance] double application of white balance
[color calibration] white balance error
[color calibration] white balance error
```

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+1175
 - OS:  Win10 and Ubuntu 20.10
 - OpenCL: yes on Win, no on Ubuntu

**Comment by pitbuster** [comment]
I think this is produced because some time ago some modules were marked as _unsafe_ for copy (white balance being one of them). As a workaround you can set the WB to Camera Reference after pasting the history.

**Comment by Nilvus** [comment]
I don't see issue here and to complete @pitbuster (I was on writing an answer same time), default copy/paste don't integrate some modules (like he said) and white balance is one of them). So this will produce what you have. Instead of simple copy/paste, you could use the other copy/paste way that allow you to select which modules you want to copy. Use related buttons in development module in lighttable, or Shift+ctrl+c instead of ctrl+c to display a popup with modules to select/unselect.

If you select white balance in that popup window, you will have no error. Actual error is just shown to let you know that using CAT mode in color calibration module is not good if white balance module is not set to D65 (the lamp icon).

Think about closing this issue if that answer to your issue.

**Comment by juhavlintula** [comment]
I understand the issue. I was confused as on the white balance module there is the message it's applied twice even though there is only one instance and same applies to the error messages on the console.

I will close the issue as a user error, but maybe the error messages could be improved so that it would be easier to identify the issue.

**Comment by Nilvus** [comment]
> I will close the issue as a user error, but maybe the error messages could be improved so that it would be easier to identify the issue.

If you want to see that, you could so create a feature request to suggest that and add a link to that issue.
