### ISSUE TITLE
[idea] make blend GUI more compact

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#8350]
The mention of extraneous vertical space in #8346 reminded me that I haven't yet posted this....

The panel for drawn+parametric masks is tall enough that on a 1080p screen, you can't see all of it at once without collapsing the filmstrip.  It should be possible to save height equivalent to two lines of text by rearranging things a bit.

The first line can be saved by moving the "hide shapes" and "show mask" buttons from the very bottom to the header line of the "mask refinement" section, just like the reset button for parametric masks is on the right end of the header line for that section.

The second is from removing on of the two instances of the string "drawn mask".  Two possibilities here:
1. just remove the header line.  Easier, but won't look as nice.
2. eliminate the copy in the text box for the pull-down  menu, then move the shape icons onto the same line.

Implementing the latter case would require being able to set a minimum width for the expanded pulldown which is greater than the current width of the collapsed text box.   It will also constrain just how narrow the entire side panel can be made (more than the first alternative).  If the second alternative is used, I would suggest putting the pulldown between the shape-creation and show/invert buttons to have a clear visual separation between the two groups with different functionalities.

**Comment by Nilvus** [comment]
I can also reduced it a little with CSS. I'm not on to remove header line, that would make the UI won't look nice as you said and less consistent.

**Comment by dterrahe** [comment]
> moving the "hide shapes" and "show mask" buttons from the very bottom to the header line of the "mask refinement" section

Agreed.

> 1. just remove the header line.  Easier, but won't look as nice.

True; not as nice

> 2. eliminate the copy in the text box for the pull-down  menu, then move the shape icons onto the same line.

That won't really work because of the reason you mention

maybe 3. underline the pull-down so it is also a header, _almost_ consistent with the other groups, at the same time. Make it full width (so move the two icons to the next line). Or maybe keep the polarity icon on this line (that would be sort-of consistent with the other underlined header lines having one or two icons.

I would encourage including even the crappiest mock-ups, for example:
![image](https://user-images.githubusercontent.com/1549490/109396462-a1329980-7929-11eb-9376-3b6f2c313b91.png)![image](https://user-images.githubusercontent.com/1549490/109396641-7268f300-792a-11eb-9043-101c85c1fc2d.png)

**Comment by Nilvus** [comment]
I like your mockup @dterrahe, except 2 things (of course, it's just a mockup):
- too less space on top of mask refinement title
- icons on the right of those titles, like it's already the case in parametric mask line is not good. This should be on same line and size as the title, and so the border continue below them (would be more consistent as it's something near modules header, like a sub-header.

Of course, if this is done, this should be done too in other blending modes, for consistency.

**Comment by ralfbrown** [comment]
Thanks for the mockup, @dterrahe .  I like the idea of having the pulldown in the title line.  It hadn't occurred to me, but having the pulldown arrow fits nicely with having active icons on the right of the other section headers.

@Nilvus, I imagine the changes would automatically happen in the other blend modes.  My impression (without looking at the code) is that there are four pieces that get switched on as needed: drawn and/or parametric as appropriate, "combine masks" if both are active, and "mask refinement" if either.  As the tallest mode, it makes sense to do the design with drawn+parametric.

The insufficient space above "mask refinement" is the current state.  "combine masks" should probably get less space above and more below.

**Comment by dterrahe** [comment]
> * his should be on same line and size as the title, and so the border continue below them

This may not be easy, because the underline is part of the label. I'll try tomorrow to see if I can resolve all of these.

**Comment by TurboGit** [comment]
A needed rework indeed as this is very long. I would put all the shape tools on the left and keep the edit and invert button on the right. This will be similar to what is done for parametric channels (channels on the left) and controls on the right.

**Comment by dterrahe** [comment]
> . I would put all the shape tools on the left and keep the edit and invert button on the right.

That would be inconsistent with retouch/spots/liquify tough, where they can't be moved to the left because there's an item count there.

**Comment by dterrahe** [comment]
> This may not be easy, because the underline is part of the label.

It actually _was_ very easy :-)

#8359 now has too much vertical spacing between the "label" (the box, really) and the underline (at least in master; haven't looked with #8346). @Nilvus hopefully you can fix that.

**Comment by Nilvus** [comment]
> > This may not be easy, because the underline is part of the label.
> 
> It actually _was_ very easy :-)
> 
> #8359 now has too much vertical spacing between the "label" (the box, really) and the underline (at least in master; haven't looked with #8346). @Nilvus hopefully you can fix that.

#8346 is now updated with better spacing. It's still remains a bad bottom margin in section label "drawn max" because of combobox added in the line by your PR #8359, @dterrahe. I try to improve it a little but can't do more. There's no margin/padding that add that. Is there a better alignment possible with GTK? You could see that combobox and invert icon on the right are not correctly aligned (test with my PR #8346 which is a little better than #8359). If you see section label parameter mask (in so parameter+drawn mask tab), you could see that spacing between label and bottom border is good in comparison of drawn bad one.
