### ISSUE TITLE
local contrast GPU code should be checked

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#8382]
**Describe the bug/issue**
The CPU vs GPU output for local contrast are very different. 

**To Reproduce**

Run test 0002 from integration test. There is 1.75e6 pixels different which is around 50% of the whole image.

```
$ ./run.sh 0002-local-contrast
Test 0002-local-contrast
      Image mire1.cr2
      CPU & GPU version differ by 1.7502e+06 pixels
      ----------------------------------
      Max dE                   : 0.00000
      Avg dE                   : 0.00000
      Std dE                   : 0.00000
      ----------------------------------
      Pixels below avg + 0 std : 100.00 %
      Pixels below avg + 1 std : 100.00 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
  OK

Total test 1
Errors     0
see test-20210302-201555.log
```

**Expected behavior**

Far less different pixels.

**Screenshots**

![diff-cl](https://user-images.githubusercontent.com/467069/109702273-4fda1280-7b94-11eb-97d8-e754affa103a.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : master
* OS                : Linux
* Linux - Distro    : Debian
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  :  Yes (obviously)
* OpenCL activated  :  Yes
* Xorg              : 
* Desktop           :  GNOME
* GTK+              : 
* gcc               :  10.2
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**

The OpenCL code for local contrast is old so probably a bug since a very long time.

**Comment by jenshannoschwalm** [comment]
We might want a diff image with every color channel having abs of diff for every pixel in integration. This might help to identify vectoring issues also in sse2

**Comment by TurboGit** [comment]
I did another tests on 0002. I have disabled all OpenCL for all modules using in this test:

```
$ ./run.sh 0002-local-contrast
Test 0002-local-contrast
      Image mire1.cr2
      CPU & GPU version differ by 8137 pixels
      ----------------------------------
      Max dE                   : 0.00000
      Avg dE                   : 0.00000
      Std dE                   : 0.00000
      ----------------------------------
      Pixels below avg + 0 std : 100.00 %
      Pixels below avg + 1 std : 100.00 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
  OK

Total test 1
Errors     0
see test-20210303-095806.log
```

And enabling just OpenCL for local contrast:

```
$ ./run.sh 0002-local-contrast
Test 0002-local-contrast
      Image mire1.cr2
      CPU & GPU version differ by 1.74225e+06 pixels
      ----------------------------------
      Max dE                   : 0.00000
      Avg dE                   : 0.00000
      Std dE                   : 0.00000
      ----------------------------------
      Pixels below avg + 0 std : 100.00 %
      Pixels below avg + 1 std : 100.00 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
  OK

Total test 1
Errors     0
see test-20210303-100016.log
```

So this rules out a possibly common module used in the pipe having issue handling the borders.

**Comment by Eneen** [comment]
I think this may be related. This is the result of subtracting the gpu and cpu images of the dt benchmark (https://math.dartmouth.edu/~sarunas/darktable_bench.html):
![test_subtract](https://user-images.githubusercontent.com/25537418/111871552-158db500-898b-11eb-94ef-cd08e3a477d0.jpg)

**Comment by jenshannoschwalm** [comment]
I had a first look and can confirm there is a problem in laplacian part. Will look deeper into this.

**Comment by jenshannoschwalm** [comment]
Ok got it.

There are these code sections making the difference
https://github.com/darktable-org/darktable/blob/549a51880a2ac228f54f41190285f73145a8d89b/data/kernels/locallaplacian.cl#L275-L276

and

https://github.com/darktable-org/darktable/blob/549a51880a2ac228f54f41190285f73145a8d89b/src/common/locallaplacian.c#L426-L427

If `dt_fast_expf` is changed to `expf` for the cpu code the images differ only in the border regions due to the demosaicer border interpolation. (BTW if we do regression tests we should likely use rcd as the border is calculated more likely between code paths)

Result here:
```
Test 0002-local-contrast
      Image mire1.cr2

      CPU & GPU version differ by 26012 pixels
      ----------------------------------
      Max dE                   : 2.13545
      Avg dE                   : 0.29550
      Std dE                   : 0.27302
      ----------------------------------
      Pixels below avg + 0 std : 46.11 %
      Pixels below avg + 1 std : 84.46 %
      Pixels below avg + 3 std : 99.95 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
  OK
```

We have have higher dE but this is due to the image we gave for comparison while introducing that test.

I also tested using `exp` instead of `native_exp` for the gpu path and that was slower but without much output difference. I am not sure how to deal with this though, the khronos docs says
```
native_exp computes the base- e exponential of x over an implementation-defined range. The maximum error is implementation-defined.
```
and i am using a nividia quadro card here, this card/driver might be better suited than others so it would mean more testing on other hardware i don't have. No idea about other hardware also. 

I think we have these options:

1. We understand the issue - maybe add some comments in the code - but leave it unchanged for performance reasons.
2. only change the cpu code for precision but that would mean a performance drop as that inline function is called a lot
3. change both code paths for precision.

pinging you @TurboGit

**Comment by TurboGit** [comment]
No strong preference between 2 and 3 but 1 is not an option. The case at hand is that an output should be equivalent between CPU and GPU as much as possible. The scenario is if I use local contrast today on a CPU, if tomorrow I get a better card supporting GPU my edits should stay the same (as much as possible).

What is the performance penalty between dt_fast_expf and expf ?

**Comment by jenshannoschwalm** [comment]
> What is the performance penalty between dt_fast_expf and expf ?

When using -d perf (instead of micro benches) the overall performance penalty for the module is less than 10% so i would say neglectable.

The scenario you describes is not the whole story as we also don't want to "break edits". If we change `dt_fast_expf' to 'expf' there is a very small difference - probably below the visable margin, but it is.

Anyway, i would also opt for option 2 and would do the pr if you wish

**Comment by TurboGit** [comment]
> The scenario you describes is not the whole story as we also don't want to "break edits". If we change `dt_fast_expf' to 'expf' there is a very small difference - probably below the visable margin, but it is.

If we feel that this is a problem we can increment the module version and have a boolean to control the algorithm used. I would say probably not needed here, because probably barely visible and anyway already broken between the CPU & GPU version.

> Anyway, i would also opt for option 2 and would do the pr if you wish

Perfect ! Go ahead, and good detective work on this one.

BTW, maybe we want to double check that this _dt_fast_exp_ vs _expf_ does not exists on other iop.

**Comment by jenshannoschwalm** [comment]
Other module having the `dt_fast` variant are `monochrome` and `base-curve`. For both the integration tests give no visible change so i kept them as they are.
