### ISSUE TITLE
frustrating behavior font size spin box in preferences

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#8447]
When trying to use the mouse to change the font size in the first tab of the preferences window, the spin buttons keep moving about as the font size changes, because the text to the left of the spinbox (and the tab names) are resized live. This makes it hard to click twice on the same button. Similar effect when using the scroll wheel over the box; the target keeps moving away from the mouse. Small video demonstration:
https://user-images.githubusercontent.com/1549490/110438773-9f49a280-80ae-11eb-984f-876be97470bd.mp4

My solution in #8437 got rejected, but maybe someone has a better looking approach that does not involve rewriting the spinbox to a normal Entry widget and thereby losing the ability to manipulate it with the mouse completely. Consider giving me the benefit of the doubt that I may have thought of, and maybe even tried, the simple, pretty, suggestions that don't actually fix the problem.

Please also keep in mind that it is more important that the widget _looks_ good to the 99% of people that _don't_ use it than that it _works_ for the 1% who _do_.
https://github.com/darktable-org/darktable/pull/8437#issuecomment-792997542

**Comment by elstoc** [comment]
One of the issues I've always had with preferences is that the length of the labels dictates the position of the widgets: those panels with long labels have the widgets positioned much further to the left than those with shorter labels. Two possible solutions:

- Make the grid fixed-width, shorten the labels (as much as possible) and make the labels wrap if the font size is too big. Perhaps devote 50% to the labels and 50% to the controls, and then the widgets could reasonably span the entire 50% width.
- Remove the grid entirely and place the labels above the widgets. Not sure this would look better, but you could perhaps split the  widgets across two equal-sized columns.

Not sure either of those are really workable but just other possibilities

**Comment by dterrahe** [comment]
I would not consider these suggestions improvements, to say the least, but I'm not the one you'd have to convince if you decided to implement this.

**Comment by quovadit** [comment]
I like the slider bar of google chrome to change font size, because you can continue dragging although it moves around

chrome://settings/fonts

![image](https://user-images.githubusercontent.com/5677563/110534540-7b727500-811f-11eb-978f-ab105ab1a326.png)

**Comment by parafin** [comment]
I don't think UI should be adapted for such corner case (changing one specific setting out of many). Instead some hidden way to easily change font size can be added - e.g. keyboard shortcut (either local to preferences or even global if it's going to work).

**Comment by quovadit** [comment]
maybe Ctrl +/-
this could also be shown in the tooltip
you could even remove the +/- buttons

**Comment by dterrahe** [comment]
> you could even remove the +/- buttons

I'm afraid that would "involve rewriting the spinbox to a normal Entry widget and thereby losing the ability to manipulate it with the mouse completely" but of course that's a small price to pay in the name of progress.

**Comment by Nilvus** [comment]
@quovadit proposal is a good one and will solve that.

Anyway, I agree with you with the issue, just not the full width solution. I have thought more about your @8437 PR @dterrahe and I think that some other things could be improved in preferences window: spinbox (with @quovadit proposal for example) and combobox need to be improved. I already add a CSS min-width to let combobox have minimum same width (align them most of the time, but depend on language).

I've checked some other apps and see 2 main behavior about spinbox and combobox :
- having them just following text setting, without space like we have actually (that doesn't solve this issue)
- having all combobox and spinbox aligned to the right of the window (so without margin right, except main page one).

This last one could be an improvement but would need some minor adjustments to be really good (actually this would add too much space between text setting and combobox or spinbox), by reducing a little the width of preferences window with such things to improve:
- 3D root lut folder have a really too big combobox and seems to have a fixed with.
![2021-03-12_21-10](https://user-images.githubusercontent.com/45535283/110993711-8ae7fd00-836f-11eb-8538-e5deff1ed030.png)

- text fields in many tabs (like import one) width could also be reduced, if needed for some by ellipsizing and/or put some infos in 2 lines instead of one (this is already done in some parts of preferences). Another example of text view width to reduce:
![2021-03-12_21-11](https://user-images.githubusercontent.com/45535283/110993768-a3581780-836f-11eb-82b7-03d400cf0293.png)

Just some ideas. Align to right would need to be test to be sure it will be good but at least, last 2 points would be good to to be fixed.

**Comment by Nilvus** [comment]
@dterrahe: just thinking more about that and @quovadit proposal. I really think more and more that would be the best one, so using bauhaus slider we have in modules to set font size (and why not some other options in preferences. With a slider, we no more have issue you pointed and with right-click why not also have the possibility to enter with keyboard a font size value like we already do in darkroom modules.
