### ISSUE TITLE
Redesigning the UI for Darktable

### ISSUE THREAD

**Issue by Zlitchufdux** [darktable-org/darktable#8497]
01/30/22 Updates and tweaks to the UI! See image below.

I've been working on this for a while because I get OCD about UX and UI and especially on Linux because it has so much potential to shine.

To continue, I've been wanting to send this to whoever does the UI and even collaborate or whatever may be to see the idea come to life for the next big release of Darktable. But, I do not even know where to start. I've been given links leading here and there, so I am just posting. 

Here is my redesign, I do have documentation on why I did what I did and placed certain objects and ideas where they are. To say the least, I cannot code this into Darktable, only do UX and UI designs. So I am looking to reach out to an admin of this who would give me a chance on this redesign. 

Here is what I have been working on. The main idea is to reduce clutter, create some spacing and be able to tell what is what. It is all kind of jumbled up to me which is why I started this UI concept.

![DarkTable 2](https://user-images.githubusercontent.com/76977280/151710201-4fba81a9-1285-48eb-a1de-c4d60cb40556.jpg)

**Comment by paperdigits** [comment]
Hi @Zlitchufdux and thank you for taking the time to submit such an ambitious change to the project. The redesign does look quite nice and clean. I appreciate the attention to detail with the typography and the spacing on the widgets.

However, this would be a lot of work for one or even many developers to undertake. It would probably take several years, as this is a complete rewrite of the GUI. Generally we like our changes, especially UI, to be quite small, so that someone can tackle it and get the improvement merged rather quickly. 

There are a few others UI enhancement issues open already. Have you taken a look at them? 

Perhaps to start, instead of redesigning the whole UI, you take one little bit of the UI, like the widget sliders, and redesign those.

**Comment by Zlitchufdux** [comment]
Hey @paperdigits I appreciate the response! I have to say I am proud of the redesign, but I had no idea (I know nothing of code) that it could take so long to rewrite the gui. That makes me sad to know that. 

I did the redesign as I believe in this program and I really like what it is capable of and I believe a redesign would bring in so many more users and this program would gain a lot of attention. So while I look into some redesigns on a smaller level, I do hope one day someone can undertake the task of rewriting the GUI and see this come to life while still keep core concepts of allowing users to tackle it and move quickly.

**Comment by GLLM** [comment]
OMG, this looks like a 2021 UI .... what a shocker ! :) ... Sliders look really nice :)

A mix between this and @difrkaguilar suggestion would indeed be nice ! But, as @paperdigits said, that will probably take a looong time !

On another note, black UI is maybe not the best for photo retouching, as it tricks the brain when looking at exposure/contrast/colors)

Thanks for the work/time taken to suggest all this ...
GLLM

**Comment by alenaksu** [comment]
Hi all, this is a quite old issue but as I can see the "redesign" is a recurring topic in this repo.

I really like the work @Zlitchufdux have proposed and at the same time I agree with @paperdigits that redefining the whole UI would be a huge amount of work. 
So, if there still is the will to redesign the app, would it make sense to start by creating a design system? 
In this way there will be a clear set of guidelines (spacing, sizing, behaviour, components, and so on..) that could be discussed among the community and that the developers can follow to eventually build or redesign each component individually.

To give you an example, Adobe has a design system called [Spectrum](https://spectrum.adobe.com/page/principles/). For instance, these are the [guidelines for building sliders](https://spectrum.adobe.com/page/slider/).

What do you think, does it make sense?

**Comment by MStraeten** [comment]
darktable developers implements what they are convinced of, not because thats written in community discussed styleguides ;)
styleguides are defined by those who does the job…

**Comment by alenaksu** [comment]
@MStraeten of course `styleguides are defined by those who does the job` and of course it's not mandatory to involve the community in decisions (even though darktable developers are a community per sé :)). Just my opinion, asking for a  feedback, also to whom that have a different area of expertise, it's always a good thing, especially when you are building something that is meant to be used by everyday users.

Also, I just wanted to highlight the benefit to have something written and `standardized` somewhere that can be useful to anyone, starting from the new contributor to the most experienced one. It could help to declutter code and keep the UI consistent over the time. 

That said, I'm far from saying that Darktable has a bad UX, I actually think it is amazing, but I also think that it is a topic that should not be underestimated.

**Comment by Zlitchufdux** [comment]
Update on the ui

**Comment by Nilvus** [comment]
> Also, I just wanted to highlight the benefit to have something written and `standardized` somewhere that can be useful to anyone, starting from the new contributor to the most experienced one. It could help to declutter code and keep the UI consistent over the time.
> 
> That said, I'm far from saying that Darktable has a bad UX, I actually think it is amazing, but I also think that it is a topic that should not be underestimated.

I completely agree with you. Set a design system need work outside of coding. The only limit here is that few people work on the UI. About CSS part (and some coding), I'm (nearly) the only one to work on that part. Some developers put really useful feedback and work on some part but to finish and fine-tune UI, nobody else. And I'm sure it's not a good idea to set such design system with only one people. I've proved propose some good design guidelines but also, on some parts, have limits. And thanks to some great feedback where my limits come, I improved and fix them.

Of course, non-developers could help set that but the limit would that they have absolute no idea on what issues/limits some proposal could have when coding work is done. I've sometimes ideas that I can't add just because when setting them, other issues appears. And changing thing is often all about compromises. For example, those past days, I change/improve a lot hover effects on all the UI (that was starting about some bauhaus widgets, sliders and combobox that needs to be improved). And I have had some hard time to find a good balanced way on all the UI. When improving a part, that often broke another part. I've finally succeed to do that here, thanks to great elstoc feedback mainly.

Theory and ideas are often great, like @Zlitchufdux proposal here. But it's nearly always harder to do that it seems, even when you know how to do it.

Anyway, said that, I have in mind to propose some first guidelines here but this will take time, needs to be simple. And I hope having same some help and others ideas than just mine (by taking care of limits I said just above of course). That's also why I started this year a complete CSS (and some Gtk parts for what I've learned to do) rework. I already changed about 33% of CSS code and reduce CSS files by removing more than 100 lines. Hover effects are since yesterday now more consistent in all parts of the UI and, I think, better design now. I will now start a new huge work to simplify more other parts by making CSS more conform with W3C standards (It's actually not on some parts). This work should simplify work by setting not only CSS for items in the UI but by setting some standards settings (for example, all items with same effect) and then applied them on all related items. This should help then to set such design system.

**Comment by Nilvus** [comment]
@Zlitchufdux: thanks again for your mockup. I think now that we can close that one. Such a UI update would be huge but this help me finding new icons for darktable UI. If you have ideas for thumbnails in lighttable, I'm all on. Just think about mockups that could easily deal with actual thumbnails (mainly keeping actual square around images). For more, this will also need someone able to rework Gtk code (so not me).
