### ISSUE TITLE
enhance export shortcut

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#8519]
For most usual work, I have 3 different export presets : web ; tiff hq ; jpeg hq + 2 lua export presets : hugin(slighty modified) ; backup (relies to some bash scripts)
Each time I want to export an image, I need to -at least- do 2 actions : the shortcut of the preset + ctrl-E. and, especially for "delicate" presets like backup, don't forget to reset the export module to something less dangerous in case of a erroneous ctrl-e

Currently, I use a workaround by redefining everything in a lua script and assign it a special shortcut, but that's not ideal...

What I want to achieve is to have a way to export with a specific preset in one shortcut, without changing all the export module values. That's not so hard, but there's multiple internal ways to do it cleanly and I don't know which one is the best...

1. the less intrusive : add specific "export to preset ..." accels to export lib, one for each preset (need t to be synchronized with presets)
2. add a fct to the lib api to allow to "execute" a preset (not only to "apply" it) That would have the advantage to allow that to be reused by other libs (tags ? geotags ? metadata ? import ?) Then we have 2 solutions if this optional fct is present : 
2a. add a parameter to presets "execute directly" at the same place we have "autoapply" and "filter" checkboxes
2b. for each preset, allow 2 shortcuts : with or without autoexecute (this has my preference)
3. do nothing and continue with the actual state :)

All solutions seems doable without to much efforts, so if some devs can give their opinion, esp. @dterrahe as you plan to do big changes in this area

**Comment by dterrahe** [comment]
This will fit very neatly in phase ii of #8078, which will have a concept of the "effect" of a shortcut. This will for example be used for sliders to "reset" or "move to min"/"move to max". For (shapes) buttons to "add single"/"add multiple".

So in this case, a shortcut for a preset could either "apply" or "execute". You could have different shortcuts for the same preset do different things (you wouldn't have to create two presets, and keep them in sync, which you would have to do if you implemented 2a).

You could even create a shortcut "fallback" (another phase ii or possibly phase iii aspect of #8078) so that for any shortcut for a preset you created, if you press it while holding ctrl (or if you double pressed the key, or if you pressed the key and then right-clicked the mouse; whatever your personal preference is), it would then execute rather than apply the preset. So by creating, say, three shortcuts for different presets and one fallback (which might come as default) you'd have 6 different shortcut options.

Rather than adding a new fct to a lib to "execute" presets, we could possibly mark a button with gtk_dialog_set_default_response or something similar (a widget name) and "press" that after applying the preset. This could then maybe also work with pressing Enter while editing any parameters/Entries in the lib. There were some recent discussion with @elstoc and @phweyland if I remember correctly about this kind of topic.

Also, I'm not just "planning" to do big changes in the area; there is a PR (#8078) that is ready for testing and feedback! (hint hint)

**Comment by AlicVB** [comment]
great ! So I'll wait for all your hard work to land and then rethink all this.


> Rather than adding a new fct to a lib to "execute" presets, we could possibly mark a button with gtk_dialog_set_default_response or something similar (a widget name) and "press" that after applying the preset. This could then maybe also work with pressing Enter while editing any parameters/Entries in the lib. There were some recent discussion with @elstoc and @phweyland if I remember correctly about this kind of topic.

no sure it's exactly the same, as I think that "executing" a preset shouldn't change the values inside the module (or set them back once the "execute" is done). That said, I agree that having a default button would be great for usual use.

...and I don't forget you for #8078 testing :)

**Comment by dterrahe** [comment]
> I think that "executing" a preset shouldn't change the values inside the module

OK, now in theory that would be possible, of course. In practice, I think (may be wrong) that most modules use the same values that are put in the widgets by the presets when you press the "go" button. So they'd all need some rewriting if you want to separate that. My understanding from your description was that if you do "preset"+"execute" in one step, rather than having to press two separate shortcuts, you wouldn't need a preset for "execute" and therefore the risk of accidentally pressing it is also small. You'd only have a problem when you press the button in the lib itself, but then you can _see_ what you are doing.

So I'd hope that "apply" and "apply and execute" would be sufficient. It also means people can _see_ afterwards what the settings were that were executed.

**Comment by AlicVB** [comment]
good point ! Let's go with that at least for now... That'll will simpler !
And in any case we can always add some "save current" + "apply preset" + "execute" + "restore previous" if really needed once everything is in place !

**Comment by Nilvus** [comment]
@AlicVB: as #8078 is merged, this issue is probably fixed. I don't know if you have tested this PR. I let you close this issue if ok for you.
