### ISSUE TITLE
Update collection folder (to remove/add files in darktable)

### ISSUE THREAD

**Issue by jcarsanfoto** [darktable-org/darktable#8642]
I read a similar issue here and I want to say the same thing.
Hi, I tried the option you say Nilvus, and it doesn't work as you say. I deleted a photo inside the closed light table the program. Once rebooted, I made the option to search for the folder to re-import, and it didn't.
On the contrary, it did work for me when I switched from distro and had to locate the images in the database. Year after year I have been locating them and everything has been restored correctly. But it doesn't work for re-importing images from a folder

**Platform**
* darktable version : 3.4.1 version estable
* OS                : e.g. Linux - kernel 5.10.2 / 
* Linux - Distro    : Manjaro 21 Ornara
* Memory            : 16 GB
* Graphics card     : Nvidia 1650 Ti
* Graphics driver   : Nvidia 460
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : Yes
* Desktop           : Gnome
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by Nilvus** [comment]
Hi,
You certainly not understand correctly what I suggest. I not only suggest the right-click and then research a filmroll but also to manage files only in darktable. And never outside. I always manage my files inside darktable without any problems (and since more than 3 years that I use intensively darktable. And I'm not the only one to use it that way without any problem.

darktable link files from your filesystem, so of course if you break links, you will have issues. If you add/remove files directly from darktable (by using import options to add and remove/delete from related module in right panel), you will never had issues. If you change them outside darktable, you will always have issues.

As for each tool, just use it the good way and all will be good. If necessary, the manual is here to help.

**Comment by jcarsanfoto** [comment]
I may not have been able to express myself correctly in English.  I 
know that Nilvus commented that if we used the right button to search 
for the folders, we would get the folder and all the files that were 
inside.
I understand that in order to do this, images must always be imported 
beforehand.  That was my doubt.
Thanks

En dg., 11 d’abr. 2021 a les 10:36 A. M., Nicolas Auffray 
***@***.***> ha escrit:

**Comment by Nilvus** [comment]
> I may not have been able to express myself correctly in English. I know that Nilvus commented that if we used the right button to search for the folders, we would get the folder and all the files that were inside. I understand that in order to do this, images must always be imported beforehand. That was my doubt. Thanks

So, is this issue could be closed and you have your way? Remember that issue is intended as something than eventually could be changed/fixed in darktable code. About help on how to use darktable, pixl.us is better for that (in english). I don't know your native language, if it's french (it's my native language), darktable.fr forums is here.
