### ISSUE TITLE
Difficulty getting to "compress history stack" in history module

### ISSUE THREAD

**Issue by SWSRN** [darktable-org/darktable#8665]
If I make a lot of edits, the history stack gets so long that it is difficult to get to the "compress history stack" button. I've had to decrease the font size temporarily to make it show. Could a scroll bar be added to history to avoid this problem?

I am running 3.4.0.

**Comment by Nilvus** [comment]
Hi, a scrollbar exist. But maybe it was not in 3.4.0, even if I'm quite sure it exist since a long time. But can't remember precisely. And last darktable release is 3.4.1. At least, I had one on actual master. So, the worst you could have is to wait for 3.6 which should be released on first days of july.

See a long history (and scrollbars) I have on actual master:
![2021-04-12_17-48](https://user-images.githubusercontent.com/45535283/114423385-ab8db780-9ba6-11eb-9ba3-627c4c153d42.png)

At least, a scrollbar is there since few years, on the left of the UI, as you can see in picture above and in this old issue: #2912

As you can see, since (and that what I can't remember when it was implementing), we now have a scrollbar for history (right scrollbar in screenshot above).

I close as this is fixed but feel free to answer if you need it. Help to use darktable is also possible in pixl.us forums. Here it's about all things that could be fixed by working on darktable code.

**Comment by SWSRN** [comment]
"At least, a scrollbar is there since few years, on the left of the UI, as you can see in picture above and in this old issue: #2912"
The left scroll bar (which does the trick) is there on my darktable 3.4.0 just like in issue #2912. I don't see the right scrollbar that you show but it was not seen either in issue #2912. Maybe the right scroll bar has been added recently? Thanks for the help.
