### ISSUE TITLE
dont understand the binary "darktable:params="

### ISSUE THREAD

**Issue by UsefGeorge** [darktable-org/darktable#8793]
Trying to figure out why this xmp file causes darktable to go core. It would be nice for a detailed description of what the "darktable:params=" equates to But just not there to see.

[20100801-IMG_5050.JPG.xmp_13.txt](https://github.com/darktable-org/darktable/files/6379193/20100801-IMG_5050.JPG.xmp_13.txt)

this xmp file causes an imported .JPG file to crash when it is appended to the current history. I have no idea as to what "CROP" features its trying to attempt.

fedora 32, darktable 3.4.1

**Comment by johnny-bit** [comment]
Well, fortunately this XMP no longer crashes darktable ;)

To answer your question: the xmp contains pretty radical rotation + very aggressive (100%) right+bottom margins (making image size =0x0 px)

The crash most likely got fixed by https://github.com/darktable-org/darktable/pull/9153
Fuller fix would be in https://github.com/darktable-org/darktable/pull/9133

and readability of params is part of https://github.com/darktable-org/darktable/issues/4250

Since it no longer crashes I'd consider the issue fixed... You've opened couple more bug reports for dt crashes connected to crop&rotate - let's investigate them there.
