### ISSUE TITLE
"Smart Presets": More flexible presets: only set some parameters of a module

### ISSUE THREAD

**Issue by misttsim** [darktable-org/darktable#8861]
**Is your feature request related to a problem? Please describe.**
When creating a preset, for example for lens correction, all parameters of the module are part of the preset, and will be applied if the preset is used (by an automatic match or manually). For some parameters, this does not make sense. E.g. for Lens correction, I would want to remember the lens model and all fixed lens correction parameters, but not the e.g. the used focal length (of zoom lenses, of course). The focal length should be taken from the current picture, not the preset.

**Describe the solution you'd like**
Maybe presets would allow to select the set of parameters that are part of the preset, and leave other parameters untouched and in the responsibility of the module. Let's call it "smart presets". Maybe each module could pre-define a sensible set or parameters that are part of the preset.

**Alternatives**
Easier: Do not implement a selectable set of parameters, but just pre-define that some parameters of some modules are not changed by the preset.

**Additional context**

N/A

**Comment by fidergo-stephane-gourichon** [comment]
This looks related to #8365, where:
* "white balance" was used as example instead of "lens correction" here.
* "applying preset" is the action here, while #8365 is about copy-paste.

Here:

> The focal length should be taken from the current picture, not the preset.

On #8365:

> * reset "crop and rotate" to whatever different dimensions and orientation each photograph is
> * reset "perspective"
> * reset "lens correction" to apply using whatever different processing (distorsion, chromatic aberration, etc) is actually best for each photograph
> * reset "profiled denoise" to whatever different sensor and iso each photograph was shot.
> * reset "exposure", obeying whatever different per-photograph bias the camera may have set
> * more are probably applicable

If I understand correctly, this bug is about applying some parameters and not others, while #8365 focuses on copy-pasting a "reset module". Could a fix to this bug be considered like an extension of a fix to #8365?

**Comment by misttsim** [comment]
Hi
I checked #8365, and I agree, this refers to the same kind of behaviour. Presets should not always set all parameters in the module, be it white-balance, or lens correction. But I'm afraid it's not always clear which parameters should be set by the preset, and which not. So a flexible solution would be appreciated, but on the other hand might be more effort that this not-so-big problem deserves.

**Comment by Yardlongbean** [comment]
+1 from me
Present behaviour is confusing
If you set a preset for lens correction with corrections set to 'All' and everything left alone, it will correctly apply the focal length relevant to that image.
If you select, for example 'Distortion and vignetting', as a preset, it pastes a constant value for focal length and doesn't read it from the image.
As the CA corrections from 'Raw CA corrections' are much better than from lensfun, it would be useful to apply just distortion and vignetting as a preset that reads the focal length settings correctly. I am sure you are aware of this, and it is a matter of having time to fix it, but it would be great if this issue was fixed for 3.6. Thanks!
