### ISSUE TITLE
Multi-threaded thumbnail creation

### ISSUE THREAD

**Issue by MWP** [darktable-org/darktable#8912]
Hi all,

I've been surprised to find that thumbnail creation is not multi-threaded.
Is it in the to-do list?

I'm asking as im only seeing a single core of my 20 core Xeon CPU being used.
(official DT 3.4.1.1 windows build under Win10)

Other DT functions are multi-threaded as expected (ie, image export). 

Thankyou.

**Comment by ralfbrown** [comment]
dt does multi-thread during thumbnail generation, but you may not be seeing it because reading an image off disk is single-threaded since disk I/O would be the limiting factor anyway,  and
- processing the loaded image at thumbnail size probably takes much less time than loading it
- or you've configured dt to use the embedded thumbnails from the image file

**Comment by MWP** [comment]
Okay, ive tweaked the lighttable settings, and now thumbnail generation in DT is multi-threaded.
Much much quicker.

Using darktable-generate-cache.exe however is still single threaded.
Is there a way to fix this?

Thanks again.

**Comment by Nilvus** [comment]
> Okay, ive tweaked the lighttable settings, and now thumbnail generation in DT is multi-threaded.
> Much much quicker.
> 
> Using darktable-generate-cache.exe however is still single threaded.
> Is there a way to fix this?

It's not really the same issue and with processor you have, using darktable-generate-cache is not really useful. I had used this script when I was using an old macbook pro (7 years old) but now that I have a powerful processor (less powerful than yours) and an Nvidia Geforce 1650 GTX Super card, thumbnail generation is really fast in live. By default, darktable generate thumbnail (same thing as darktable-generate-cache does, when you show a thumbnail.

About darktable-generate-cache still single threaded, I let you read again @ralfbrown answer, it's the same. This is only a script and the limited factor remains that disk I/O is single-threaded. This script is about generating (so writing on disk) thumbnails for each image (one-by-one, because the disk can't write 2 images at the same time)!

**Comment by MWP** [comment]
> using darktable-generate-cache is not really useful

I wouldn't be asking if it wasnt useful.
I just imported 10,000 new photos... not having to scroll wait, scroll wait, etc would be VERY useful and time-saving.

**Comment by MWP** [comment]
@jenshannoschwalm okay, thankyou.
I don't understand the technicalities/difference between multithreading and OpenMP.

Either way, my feature request is that darktable-generate-cache.exe is updated/optimised so that it will use maximum cpu resources to generate the cache as quickly as possible, as it currently does not.

**Comment by jenshannoschwalm** [comment]
You suggested, to use multiple threads to do the thumbnail generation as you have 20cores on your cpu, fine.

But - it's much more relevant, that for each thumbnail generated - (and most of the "power users" have it defined in preferences to generate the thumbs from raw data and not from preview image) to have **all** available cores to render on that single image. Thats much more efficient, thats what OpenMP is about, to distribute code as "one code on different sections of data also allowing the compile to generate vectorized code (meaning to us sse or other vector instructions). And that is definitely activated. So a design decision and probably a very good one.

On your machine, if you render 20 thumbs at the same time in 20 threads, every thread would fight for resources, cpu & ram wise.

**Comment by MWP** [comment]
Okay, I understand, thanks for the explanation.

That leads me back to the original problem then... why am I only seeing one CPU core in use when using darktable-generate-cache.exe?
I understand darktable-generate-cache not working on more than one thumbnail at a time, but if OpenMP is working as intended, shouldn't I see activity on more cores?
darktable-generate-cache takes just under a second to process each thumb.

**Comment by jenshannoschwalm** [comment]
I don't know how windows is showing the cpu load so i can't tell you - linux only here. Try to do it after setting the above-mentioned preference, also give the cpu a lot of work via the option `-m 6`

Or the build of the windows binary does not include OpenMP
