### ISSUE TITLE
Drag and drop into lighttable fails if it's empty

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#8914]
Ubuntu 18.04    dt 3.5.0+1966~g12d7a9967-dirty
If I already have one image in lighttable, I can drag some other raw file, or a folder of raws, into lighttable, and it works ok.  This is using the desktop's own file manager, "Files".
But if lighttable is empty, it doesn't work, lighttable remains empty.

**Comment by RawConvert** [comment]
As per above - still happening on 3.7.0+324~g17d82bb19.

**Comment by domosbg** [comment]
I tried to take a look at it, but I'm stuck. Lack of skills. Maybe someone can give me a hint.

What I understand is the following:
The drag and drop works if the lightable is not empty, because then it is handled in thumbtable.c by the function "static void _event_dnd_received") line 1699ff.
This function is connected as a signal in line 1804 "g_signal_connect(table->widget, "drag-data-received", G_CALLBACK(_event_dnd_received), table);"

It doesn't work if the lighttable is empty, because then the thumbtable is not shown. The text hints in the empty view are drawn in lighttable.c function static int _lighttable_expose_empty.

So in my theory it should work if I connect the "drag receive" event with the UI element which represents the rectangle of the empty lighttable view (or draw a new rectangle in _lighttable_expose_empty if this can be connected to a signal).
Can anyone give me a hint where I can find this object? Or is there any additional documentation of the UI (e.g. name and position of the containers and in which source files it is coded)?
