### ISSUE TITLE
When importing, can the folder be auto-selected?

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#8916]
Ubuntu 18.04  dt 3.5.0+1966~g12d7a9967-dirty

Suppose you click "import in-place", navigate to a folder, and click "open".  You now get the "import in-place" panel with your folder on the left.  But it is not selected, so you have to click it, and now you can see your files.
Could it not be automatically be selected?  This would make the process more seamless.

**Comment by elstoc** [comment]
I think this does reveal though (not for the first time) that we've not yet found a way to make the optimal process clear in the UI. @TurboGit I think we need to work out how to make this better before this finds its way into a release, because the new import process has already generated a lot of discussion and confusion (even after the single-dialog enhancements). I fear a flood of this sort of thing once it's released.

**Comment by elstoc** [comment]
The import dialog in current master now has much more obvious workflow.

**Comment by elstoc** [comment]
With the most recent revisions to the import dialogs, I think this can be closed, and the correct process is now much better signposted. @RawConvert do you agree?

**Comment by RawConvert** [comment]
Yes thanks, closing.
