### ISSUE TITLE
Font face defined only by font-family attribute

### ISSUE THREAD

**Issue by lhietal** [darktable-org/darktable#8985]
**Describe the bug/issue**
The specific Roboto font face used in _darktable-elegant-*_ themes is currently defined only by `font-family` property. This assumes that _Roboto Light_ and _Roboto Condensed_ are recognized as separate font families. If this is not the case both fallback to _Roboto_ (implemented in https://github.com/darktable-org/darktable/commit/8ecbf59202bf39acc885db9c8054bf6208d73eb8) which is regular weight and stretch.

CSS spec suggests that `font-family` property is only used to specify the family and `font-weight`, `font-stretch` and `font-style` are used to specify an individual face. ([css](https://www.w3.org/TR/css-fonts-3/#font-family-prop))

**Expected behavior**
Adding properties for weight and stretch to https://github.com/darktable-org/darktable/blob/1f105ca20ecdbeb6c023401ee6ee412943bd3fed/data/themes/darktable-elegant-darker.css#L73-L80 and https://github.com/darktable-org/darktable/blob/1f105ca20ecdbeb6c023401ee6ee412943bd3fed/data/themes/darktable-elegant-darker.css#L96-L103 would keep proper font faces even if only _Roboto_ is recognized as a font family. I assume this wouldn't change the font face if _Roboto Light_ and _Roboto Condensed_  are recognized on other systems.

**Platform**
* darktable version : 3.5.0+2228~gabfd8d42e
* OS                : macOS 10.14.6

**Comment by Nilvus** [comment]
This file is just used to set font (family) for elegant themes. All other settings inherit from main darktable.css file. So font-weight is defined in darktable.css file. No need to duplicate it here. And that's why font-weight had been removed here: to avoid duplicates.

Applied font-stretch setting here would force font-stretch on all fonts here and so could break for some. And probably more if there's no Roboto fonts installed. Not wanted!

**Comment by lhietal** [comment]
I couldn't find `font-weight` set to light anywhere in the darktable.css. Because _Roboto Light_ is requested as `font-family` I assumed that light font face is preferred. Preventing strech from being applied to font families that don't have a face for that is very important. Thank you for mentioning that. CSS way to prevent that ([font-synthesis](https://www.w3.org/TR/css-fonts-3/#propdef-font-synthesis)) cannot be found in gtk documentation and seems to not be working.

If this issue is not present on most other systems it is not crucial to have explicit font face specified by default. The UI is usable without any changes and user.css is very easy to modify.

**Comment by Nilvus** [comment]
> I couldn't find `font-weight` set to light anywhere in the darktable.css. Because _Roboto Light_ is requested as `font-family` I assumed that light font face is preferred.

I just said font-weight is set in darktable.css by default but you're right, light setting is the one not set anywhere. Maybe the only thing to add (or not, I need to test before).

> If this issue is not present on most other systems it is not crucial to have explicit font face specified by default. The UI is usable without any changes and user.css is very easy to modify.

I agree, not real issue as it is not present on most systems. This is as it is since about 2 years and we had no complaint about that. So, at worst, it is just a minor CSS improvement (anyway, all improvements are welcomed) but no hurry. I have few time to test by now but will try ASAP. Maybe for 3.6 (or not).

**Comment by lhietal** [comment]
I'll let you work on this when you have time. I can also test if needed. 

Thanks for helping me understand this issue.
