### ISSUE TITLE
[FR] white balance sliders range are too big

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9039]
**Is your feature request related to a problem? Please describe.**
The 'white balance' module has a slider to dial in a temperature between 1901 K and 25.000 K.
Because of that long range it is really hard to use. Moving the slider only a tiny bit leads to massive changes in the temperature values. (I know that you can fine tune your selection via a right-click on the slider but the slider should be somewhat usable without that.)
I propose to change the limit on that slider to values between 3000 K and 10.000K similarly to the exposure module which is limited between +/- 3 EV. Higher values can always achieved by dialing in the number directly.

**Comment by johnny-bit** [comment]
Scrolling with <kbd>ctrl</kbd> gives fine enough adjustment without blocking access to full might of channel coeff aproximation algorithtm. Color calibration even has for blackbody/daylight a range from 1667 to 25000 which is IMO as good as it gets (and also can be adjusted delicately enough with <kbd>ctrl</kbd>)

A better way in case of big temp/tint shifts is to use color calibration in "custom" mode and adjust light source hue & chroma so it's even more powerfull.

Since white balance isn't really a creative module, but rather corrective one I do think having access to full slider is for the better. Then there are channel coeff sliders (hidden by default) which go from 0 to 6 and putting 0 in any of them WILL result in black image.
So ultimately the sliders in white balance are following "I PAID FOR WHOLE SLIDER, I'M GONNA USE WHOLE SLIDER" kind of mentality :) And since we have scene refered mode that's going to be default with 3.6 release the color balance is ultimately a better thing to have and focus on. White balance should be set to D65 and illuminant adaptation should be done in color calibration.

And in custom case where white balance adjustment is needed then you paid for whole slider and can use whole slider.


(also your example with exposure is a bit incorrect since it was now broadened to -3/+4 EV actually expanding allowed range) :)

So no - not necessary change IMO.

**Comment by Solarer** [comment]
I don't agree with the full slider mentality if anything below a certain threshold turns the picture into a mess of colors, but if we are moving away from this module anyway it does not really matter. 
But after all, there is a reason why the exposure slider does not go to -10/+10 by default :P
