### ISSUE TITLE
tint slider in 'white balance' module overflows color values below 0.6

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9040]
**Describe the bug/issue**

The description of the slider states that values smaller than 1.00 tint the picture magenta. But as you get smaller than 0.6 the magenta color jumpes to blue!? Below 0.165 the picture suddenly gets colored green... For values >1 the slider behaves correctly.

On a side note: the tint slider is very sensitive. Is it possible to restrict the slider to more reasonable values? I would never use anything outside 0.8 - 1.2 for color correction and you can always deal in higher numbers manually if you really need to.

Manjaro Linux 
3.5.0+1967~g4024d7d73

**Comment by johnny-bit** [comment]
No. It works as intended.

If you enable slider color in white balance in emulation mode it shows how it'll shift the image colours. The hint is correct for most part, because magenta->blue shift is dependent on scene illuminant temperature. And blue->green shift also depends on temperature that may or may not happen depending on specifics of scene because ultimately it calculates coefficients which then apply adjustment to data.

The sensitivity and spread of it is also good thing because it covers basically whole range permissible by algorithm used to aproximate coefficients and ultimately it is coefficents that are applied and not temp/tint.

This module is now superseded by color calibration which has way better mechanism for adjusting scene light imbalances and should only be used to apply D65 coefficients for color calibration to have neutralised data.

scene refered is the way to go.

**Comment by Solarer** [comment]
Thank you for your explanation
