### ISSUE TITLE
Raw Files not being processed

### ISSUE THREAD

**Issue by seanfletcher** [darktable-org/darktable#9086]
RAW Files from the following cameras not being read
Canon PowerShot Elph 180
Canon PowerShot A590 IS
but can be read by rawtherapee (both teams should get together and share the work of raw processing just a thought)
i will add sample files for study

http://super.narfoo.com/files/rawtests.zip

Thanks

**Comment by MStraeten** [comment]
See https://github.com/darktable-org/darktable/wiki/Camera-support

**Comment by seanfletcher** [comment]
Thanks

**Comment by johnny-bit** [comment]
@seanfletcher - please send samples to raw.pixls.us according to https://github.com/darktable-org/darktable/wiki/Camera-support and create a new [Camera Support issue](]https://github.com/darktable-org/darktable/issues/new?assignees=LebedevRI&labels=scope%3A+camera+support&template=new_camera_support.md&title=%3CEnter+your+camera+name+here%3E)

Otherwise this is is not actionable as of now.

**Comment by johnny-bit** [comment]
Over a month open in incomplete state. Please upload raw samples and ceate new camera support tickets per https://github.com/darktable-org/darktable/wiki/Camera-support
