### ISSUE TITLE
Searching shortcuts: case-insensitive search & "no results" display

### ISSUE THREAD

**Issue by Konzertheld** [darktable-org/darktable#9126]
**Is your feature request related to a problem? Please describe.**
I was wondering if the search function in the shortcuts settings did not work. It did, but I "misspelled" the setting I was searching for, using lower case letters only. I would expect this search field to be case-insensitive, there is no point in being case-sensitive here. Also, when no results are found, nothing happens. I would like to see a little message in that case. And third, searching for something that does not lead to any results closes all expanded sections. I was noticing the last point when I thought maybe I need to select a section first to search inside.

**Describe the solution you'd like**
- Search is case-insensitive
- Search gives message when no results are found

**Alternatives**
- Document that search is case-sensitive

**Comment by dterrahe** [comment]
With #8078 you will have case insensitive incremental search in the shortcuts and actions lists. This search is build using standard gtk functionality, which means you can go to the next/previous match using down/up keys. Since it is incremental, it becomes obvious if the last character you typed causes there to be no matches, so there won't be a need for a "no results" message.

**Comment by johnny-bit** [comment]
I've re-checked the shortcuts and actions search in #8078. It's AWESOME, incremental, case-insensitive and VERY "intuitive" to use :)

since #8078 is slated for very early merging into master during 3.8 dev cycle to increase the testing area I'd recommend testinc #8078 untill it's merged into master.

Otherwise I'd consider this FR to be "fixed" by 8078 and no need to do anything more about it.

I'll close this pre-emptively if you don't mind :)
