### ISSUE TITLE
Use Segoe UI as the UI font on Windows

### ISSUE THREAD

**Issue by matteoscopel** [darktable-org/darktable#9168]
**Problem**
By default, UI fonts on Windows look a bit bad. There is some kind of subpixel distortion around the fonts, which creates a sort of pinkish aura around fonts.

![image](https://user-images.githubusercontent.com/18525423/120907025-6fcf1580-c65e-11eb-98b3-3a0c7d2474f2.png)

Moreover, the default font is very thin and difficult to read. It looks completely different from any other application, GTK or not. This problem does not appear on Linux, where it seems that the default system font is picked up.

**Solution**
The workaround for this is pretty easy. I've added the following code to the CSS tweaks section:

```
#iop-panel-label,
#lib-panel-label,
*,
#lib-plugin-ui,
#iop-plugin-ui,
#bauhaus-popup,
#modules-tabs,
#left,
#right,
combobox,
combobox *,
togglebutton,
togglebutton *,
notebook,
notebook *,
notebook tab,
notebook tab *,
table,
table *,
row,
row *,
frame,
frame *,
alignment,
entry,
entry *,
dialog,
dialog *,
colorswatch,
colorswatch *,
stack,
stack *,
scrollbar,
scrollbar *,
eventbox,
eventbox *,
scale,
scale *,
button,
button *,
treeview,
treeview *,
menu,
menu *,
separator,
eventbox,
eventbox *,
box,
box *
{
    font-family: "Segoe UI";
}
```

So, using Windows' standard font, Segoe UI, solves every problem. The font is very readable, it renders properly, and it is consistent with every other app. It also properly supports the special symbols that Darktable uses (the stars, the dot).
Here is a screenshot of the font rendering with Segoe:

![image](https://user-images.githubusercontent.com/18525423/120907080-04397800-c65f-11eb-9968-7c4c078416ff.png)

While the solution for the problem was easy, I'd suggest using Segoe UI by default. It's a tiny thing, but it improves the usability and the impression the software makes a lot.

**Comment by MStraeten** [comment]
the used font depends on your system since darktable defines several alternatives gtk can choose by default 
```
{
    font-family: "Roboto Light", "Roboto",                  /* best case scenario */
                 "Segoe UI Light", "Segoe UI",              /* Windows 10 default */
                 "SF Pro Display Light", "SF Pro Display",  /* Mac OS X default */
                 "Ubuntu Light", "Ubuntu",                  /* Ubuntu default */
                 "Cantarell",                               /* Gnome default */
                 sans-serif;                                /* default default */
}
```
it doesn’t make sense to set a windows specific font as a default for a tool that is run mostly on linux systems. Solving a windows problem the windows way doesn’t solve "every problem" but might generate problems on other platforms ;) 
So if yo prefer Segoe UI over Roboto even Roboto is available on your system, then it's a case the user specific css tweaking is made for.

**Comment by matteoscopel** [comment]
Thank you for your answer, @MStraeten! Just for a test, I've set Segoe UI Light as a font, and it displayed the red fringing as well, so I think this is due to how the light variants of fonts is rendered. Perhaps the effect is just less visible with a non-light font.

And I perfectly understand what you say, of course it makes sense, given that the solution is a change of CSS.

**Comment by Nilvus** [comment]
I would add that how Gtk handles font in Windows is not always best. And as a reminder, to have a correct rendering of elegant themes, Roboto fonts needs to be installed. This has been discussed a lot and it's not possible to do better, without breaking CSS (so UI) in other systems. WIth Roboto fonts installed, rendering should be ok in Windows (on what I know, I don't use WIndows). We made a lot of try with especially 2 developers that use Windows.

So sorry but unfortunately, this can't be fixed in darktable code. It's good that your workaround make the job for you.

**Comment by Nilvus** [comment]
Oh, and did you check antialiasing options in Windows?

**Comment by matteoscopel** [comment]
Thank you! In the meantime I've also found similar discussions that respectively the Gimp and Inkscape teams had on the same issue. It seems that GTK+ 3, in particular, introduced the issue on Windows. So, it is definitely a bigger upstream matter. Setting a bolder font somehow conceals it, but that's all it does. However, it is clearly out of Darktable's domain.

And I might give it a try, but on Windows, from what I see, setting the hinting or the subpixel method is not as intuitive as on Linux desktops and it requires going through a silly and very imprecise Cleartype wizard. I think for now I'll just stick with using regular Segoe as a font.

Thanks again for your answers, I hope at least that, if another Windows users stumbles into this minor inconvenient, this report helps them mitigate it.
