### ISSUE TITLE
Repeatedly opening and closing c&r module changes crop

### ISSUE THREAD

**Issue by Thanatomanic** [darktable-org/darktable#9171]
**Describe the bug/issue**
Repeatedly opening and closing the c&r module with an active crop can sometimes shrink the crop, as if the crop is applied a second time relative to the original crop.

**To Reproduce**
1. Open any image with only the basic scene-referred defaults.
2. Set a crop in the c&r module (the effect is most visible when you crop a good portion of the image)
3. Repeatedly, and quickly, switch between the c&r module and another module. N.B. Not activate/deactivate, but switch active module so that the crop guidelines need to be redrawn.
The crop will sometimes shrink.

The effect can be reproduced much more easily when a processing-heavy module is active before c&r, such as profiled denoise and surface blur.

**Expected behavior**
The crop should stay the same.

**Screenshots**
Initial crop:
![image](https://user-images.githubusercontent.com/6567747/120913297-5ba70a80-c696-11eb-890e-c6846dae5878.png)

After some repeated switching (see history):
![image](https://user-images.githubusercontent.com/6567747/120913327-9c068880-c696-11eb-8a6f-6cf448b4ee0f.png)

**Screencast**
See below. To demonstrate more easily, I will activate profiled denoise, but it can be reproduced without.
https://user-images.githubusercontent.com/6567747/120913545-11268d80-c698-11eb-9dfc-ee9629dddeeb.mp4

**Which commit introduced the error**
Unclear, I have not found a recent commit that does not show this behavior.

**Platform**
* darktable version : e.g. 3.5.0+2470~gefc30a4d1-dirty
* OS                : Win10 (20H2)
* CPU : Ryzen 7 3700X
* Memory            : 32 GB
* Graphics card     : GeForce RTX 2070 SUPER
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* GTK+              : 3.24.3
* gcc               : 10.3.0
* cflags            : n/a
* CMAKE_BUILD_TYPE  : Release

**Additional context**
Configuration log: [cmake.log.txt](https://github.com/darktable-org/darktable/files/6603674/cmake.log.txt)
No errors or warnings during compilation.

**Comment by Thanatomanic** [comment]
In addition: I just tested this in `3.4.1.1` and I could reproduce as well.

**Comment by AlicVB** [comment]
@Thanatomanic : I've manage to reproduce. I'll have a look, but apart if the fix is trivial, I'm not sure to want to take the risk of breaking something else in crop & rotate... Esp. considering that we eventually plan to do lot of in this area for 3.8... (and the issue is not really critical or easily reproducible)

Can you also try if you manage to reproduce with the new "crop" module ? (I've not manage to get the issue)
Thanks !

**Comment by xfh** [comment]
I just came across this as well, with 3.5.0+2475~gf6a211e96-dirty (compiled minutes ago).

All I need to do to reproduce is to set some area inside the image (away from borders/edges) and click several times on the crop and rotate module header (the module name). It usually happens before 10 attempts, but I am guessing it is some timing issue with module de- and reactivation.

At some point that also made me see a crop of 0x0, hence related to #9133.

I haven't been able to reproduce with the new crop module.

**Comment by jenshannoschwalm** [comment]
> At some point that also made me see a crop of 0x0, hence related to #9133.

Can reproduce here! So at least we know what might trigger. It's difficult to catch with a fast system on an image with a small history. Use a compute-heavy module in the pipeline after C&R or use cpu-path with just one core makes it easier to reproduce.

**Comment by Thanatomanic** [comment]
I have also been able to reproduce the same effect with the newer Crop module.

**Comment by AlicVB** [comment]
So I have a "almost-fix", see PR #9188 

That's a race condition, where the previous preview pipe can be used instead of the updated one if it was not finished and restart... The issue itself comes from the fact that in this cases, the max-size is computed based on the "cropped" image but isn't updated when the preview is updated...

I've still managed to reproduce the bug, though, but it's way more difficult now : for that I need to double-click multiple-time on "crop&rotate" header, with a very very heavy pipe and opencl deactivated... But that's a way more uncommon case ;)
