### ISSUE TITLE
export with style: "replace history" adds history and "append history" does nothing

### ISSUE THREAD

**Issue by paul-pw** [darktable-org/darktable#9191]
**Introduction**
I have a style to export in scene liner space from dt. 
When selecting "append history" for the style in the export panel the style is not appended. the export is the same as exporting without a style.  
when selecting "replace history" the history gets appended (the expected behavior for "append history")

**Describe the bug/issue**
with a style selected
"append history" in the export panel does nothing
"replace history" in the export panel appends the history

[the style i used](https://drive.google.com/file/d/1JgYQ1Ag6nzNB-mLybrfkvLcszNYJbeuz/view?usp=sharing)

**To Reproduce**
1. import the style
2. select an image with filmic enabled
3. go to the export panel
3. select my style as the export style to use
4. select mode "append history"
4. observe that the exported image does not look like it has filmic disabled.

**Expected behavior**
"append history" actually appends the history
"replace history" replaces history

also another minor issue: 
the naming between the export panel and the styles panel isn't consistent
overwrite in styles panel is replace history in export panel

**Comment by paul-pw** [comment]
a few testimages:
## Style1:

when I append in styles panel:
![DSC_4556_app_truth](https://user-images.githubusercontent.com/58135819/121475308-87433100-c9c5-11eb-937f-a8071eaca8db.jpg)

when I append on export:
![DSC_4556_app](https://user-images.githubusercontent.com/58135819/121475344-91fdc600-c9c5-11eb-83bc-be78fcafef53.jpg)

---

when I overwrite history in styles panel:
![DSC_4556_rep_truth](https://user-images.githubusercontent.com/58135819/121475443-b35eb200-c9c5-11eb-979c-a477f133c33e.jpg)

when I replace history on export
![DSC_4556_rep](https://user-images.githubusercontent.com/58135819/121475536-d38e7100-c9c5-11eb-949d-62d513ba7c25.jpg)

to summarize: the overwrite history on export has the same behavior as append history on export (which it shouldn't have)

## Style2:

when I append in styles panel:
![DSC_4556_kapp_truth](https://user-images.githubusercontent.com/58135819/121475751-1cdec080-c9c6-11eb-8b50-21b734119766.jpg)

when I append on export:
![DSC_4556_kapp](https://user-images.githubusercontent.com/58135819/121475846-3bdd5280-c9c6-11eb-8f16-d929af745559.jpg)

---

when I overwrite history in styles panel:
![DSC_4556_krep_truth](https://user-images.githubusercontent.com/58135819/121475823-33851780-c9c6-11eb-99b1-579200b7af02.jpg)

when I replace history on export:
![DSC_4556_krep](https://user-images.githubusercontent.com/58135819/121475926-557e9a00-c9c6-11eb-90c1-dab84020b13a.jpg)

to sumarize: 
this style behaves even weirder:
* append on export is the same as with no style applied.
* replace history on export is the same as append with the styles panel.
---
---

the base Image for reference (no style applied or appended.):
![DSC_4556_base](https://user-images.githubusercontent.com/58135819/121476014-70e9a500-c9c6-11eb-836b-a7514c1f9cc5.jpg)

**Comment by hqhoang** [comment]
I'm sorry for re-opening this ticket, but is this fixed? As of today (3.7.0+46~g89923b49b), "append history" doesn't add the preset on export, whereas "replace history" delete the whole history of the image before applying the preset. Confirmed with both "-d perf" and "-d imageio".

What I'm understanding from the user manual is, "append history" and "replace history" only matter if the preset has modules that are already in the image' stack. For those matching modules, "append history" would add a new instance, whereas "replace history" would replace the existing instance in the image's history. 

"Replace history" should not clear the image' stack before applying the preset, I can't even think of a use case for that (why would anyone edit an image just to have all editing get cleared on export.

Maybe the terms are confusing, since the mode doesn't affect the whole history, just the duplicating/matching modules in the history. Maybe renaming them to "append/replace matchings" or "append/replace instances"? At least that would force the users to read the manual for clarification instead of making a wild guess.

**Comment by paul-pw** [comment]
as I understand append should and does just append the preset module stack to the history stack. and replace should and does just replace everything from the history stack.
as for the usefulness I don't know. 
Maybe you want to use a preset to export without your previous edit effecting the result. Idk there is probably a valid Usecase for replace history on export.

As for append history: I use it to dissable filmic and everything that comes after (with a preset) for the export and then edit in scene linear in krita and then do the final adjustments in dt.

**Comment by hqhoang** [comment]
> as I understand append should and does just append the preset module stack to the history stack. and replace should and does just replace everything from the history stack.

That was the original behavior before 3.0 (or 3.1), but it has changed since then, and yes, I was confused by the change at that time, too. Not sure the reasoning behind that change back then, though.
