### ISSUE TITLE
while zooming fast the zoom position will reset to center of image 

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9207]
**Describe the bug/issue**
While investigating #9206 I noticed that something else is wrong with the zoom function. When I zoom in culling fixed mode using `Crtl-mousewheel` into a corner of an image, sometimes the zoom location will jump back to the center of the image as I am turning the mouse wheel.

It only happens when I zoom in quite fast. If I turn the wheel slowly, it works fine.
The jump will happen at around 65-75% zoom.

**To Reproduce**
1. Go to culling mode fixed
2. Move the mouse into a corner of the image
3. `Ctrl-wheel` zoom into the corner quite fast
4. You will first zoom into the corner and then jump to the center of the image.

**Expected behavior**
No jumping

* darktable version : 3.5.0+2493~g4097c761f1
* OS                : Manjaro Linux
* OpenCL installed  : yes
* OpenCL activated  :  yes

**Comment by xfh** [comment]
I can reproduce I think. For me, it also happens with previously zoomed images. It might be a different effect tough. I am not ending up at the exact center but somewhere close.

While you are zooming, you are actually also changing the size of the image widget. While you are zooming, the size of this widget changes, to give you more pixel data - after all you want to see es much of your image as possible. This is especially noticeable with a portrait image on a landscape darktable window.

Initially, the image is shown, such that it fills the screen (in my example setup, the portrait is limited by the height of your window). You should have some grey background around the image. As you zoom, the background area is reduced.

Now, while you are zooming really fast, the mouse pointer position is used as a reference for the zoom & shift. The problem is, that each event zooms, shifts the image increases the widget size. Thus, the reference point under your pointer moves and succeeding events are triggered for a new reference position. The same effect can also be observed in darkroom.

That's why it works when zooming slowly and why it fails when you are fast.

I am not sure how to fix tough. Conceptually, it's a very similar problem as observed in #9171.
There is some initial state, followed by event processing, but all of these events should use
reference data from the initial state - instead of some newly calculated outcome of each intermediate step.

It's complicated :-)

In case you were not aware: you can simply move your mouse to the desired location and then press the mouse wheel to get to that exact position at 100%.

**Comment by Solarer** [comment]
You are correct, this happens every time in contrast to #9206 which only happens once. Those are two different effects.

**Comment by Solarer** [comment]
Can you not get the mouse pointer (pixel) position on the picture rather than the mouse pointer position on the image widget? That should stay constant.

**Comment by AlicVB** [comment]
> Can you not get the mouse pointer (pixel) position on the picture rather than the mouse pointer position on the image widget? That should stay constant.

As the picture is inside the widget, that would be difficult : we need a reference !
Maybe we can try something like caching the relative pointer position on the first scroll movement ?

**Comment by xfh** [comment]
Actually, what we get is the mouse pointer position of X-Server, so there is a fixed reference.

I think the problem is, that the zooming code AND the image drawing code both update the zoomx,zoomy coordinates, making this a race condition issue.
