### ISSUE TITLE
[FR] make "search module" more comfortable

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9253]
Hello, I have 2 feature requests here:
1) Sometimes I want to edit some pictures in a row with a module that I do not use a lot. I use the "search module" field to find the module.
When I apply the module to my picture and select the next picture, the search field is cleared automatically. This forces me to type in the name of the module again and again. 
2) In my opinion the search module field is missing a small [x] button to clear the field via mouse button. Currently, the fastest way is to place the cursor in the field and then press ESC which requires me to use mouse+keyboard instead of only a single mouse click.

**Describe the solution you'd like**
* When selecting a new picture in darkroom, the search query should not reset automatically.
* The text field should have a [x] to clear the text just like the tagging module.

**Additional context**
I know that I can Ctrl-Shift-C copy edits from one picture to another but I don't want to apply the exact same value to all pictures. Some might need a +20 shadows and some need a -10. So I need to edit them one by one and every time I have to retype the query field.

**Comment by Nilvus** [comment]
Hi @Solarer,
About point 2, could you share a screenshot of your search module because what you ask for is there since quite some times (can't remember precisely when). See what I have in actual master:

![2021-06-16_00-05](https://user-images.githubusercontent.com/45535283/122129615-e4a40b80-ce25-11eb-88bd-4749ab293444.png)

About point 1, I understand your goal but not having search field  resetting could also be annoying. Module manager and its presets seems a better way.

**Comment by Nilvus** [comment]
@Solarer: just forget something about point 2. Could you precise following elements:

- your OS?
- which darktable theme do you use?
- If elegant ones, do you have all Roboto fonts installed? If darktable default theme, what font is used?

**Comment by Solarer** [comment]
@Nilvus here is a screenshot. As you can see I don't have that button:
![image](https://user-images.githubusercontent.com/2805109/122285015-7e36f000-ceee-11eb-8622-b824a6c97af2.png)

My OS is manjaro linux and I just pulled the latest master from source and deleted my build dir to check if it was implemented in the meantime - it is still not there.

How can I check what font darktable is using?

Is this console output helpful?
```
build/bin/darktable --configdir /tmp/darktable-test                                                                                                  

(darktable:18994): Gtk-WARNING **: 21:57:53.632: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(darktable:18994): Gtk-WARNING **: 21:57:53.782: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(darktable:18994): Gtk-WARNING **: 21:57:53.782: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(darktable:18994): Gtk-WARNING **: 21:57:53.782: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(darktable:18994): Gtk-WARNING **: 21:57:53.782: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(darktable:18994): Gtk-WARNING **: 21:57:53.782: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(darktable:18994): Gtk-CRITICAL **: 22:05:44.951: _gtk_accel_group_attach: assertion 'g_slist_find (accel_group->priv->acceleratables, object) == NULL' failed
```
 

Regarding point 1: 
Sometimes it is worse to automate something too much because having to undo it is more troublesome than having to do the step by hand (here: clicking the [x] button vs having to retype everything). The search field already clears automatically when I leave darkroom or when I select another module group (buttons above search field) and makes total sense. I think automation should stop there and the field should not reset when I select another picture for edits.

**Comment by Nilvus** [comment]
@Solarer: ok, so that's what I was suspected for cross button. It's font related, not darktable one. As you use default theme, darktable so use your default OS font. Or here, to be more precise your default desktop environment font. You could check (and change) in your desktop environment settings (I use Gnome and so I can see that with gnome-tweaks, with KDE, just go to KDE settings...). And you probably use a font that don't enable to display the "x" button. If you have Roboto fonts installed (or installed them), I suggest you to use (and so test) elegant themes, darker one if you still want darker theme. But I strongly recommend grey one (it's all about optic illusions and having some near a middle grey is better).

I don't know if this "x" button could be easily replaced by a cairo icon that would avoid having it not displayed with some fonts (it's only for darktable default theme) as I don't know anything on the UI except CSS! Maybe @elstoc or @johnny-bit could have other feedback?

About point 2, I can't help you more. I just disagree with you. I prefer actual behavior but I understand you purpose and use.

**Comment by johnny-bit** [comment]
I don't know why ping me ;)

anyway to answer icon in entry question: it should "simply work". The icon is standard gtk `edit-clear` icon, that should just work. uses `gtk_entry_set_icon_from_icon_name` to specify icon wanted (that corresponds with system style, it's not unicode emoji!)

if you don't see that icon in darktable, most likely you don't see that icon anywhere in gtk edit fields that use it. and those errors in console look like it's your gtk theme that might be borked and not darktable css..

as for the icon itself -sure we could play with gdkpixbuf stuff which would need us to write another drawing function in pain.c but hey, that's the fun :)

For the search module you COULD ping @AlicVB as the search module is part of modulegroups :)

**Comment by Solarer** [comment]
ok, funny discovery. The button was there all along - but it has the same black color as the background in standard theme on my distro... lol
![image](https://user-images.githubusercontent.com/2805109/122306633-1641d300-cf09-11eb-99a7-b0036c580484.png)
![image](https://user-images.githubusercontent.com/2805109/122306757-56a15100-cf09-11eb-92d9-89c3556b463e.png)

This happens in themes: "icons-darker", "standard", "icons" and "elegant-darker". 
Is there anything that can be done globally or do I need to chose another font on my end? Guess other people using manjaro/kde might be impacted by this as well.

The only thing I could think of is using the same button as in the tagging module. That is visible in every theme:
![image](https://user-images.githubusercontent.com/2805109/122307438-a6cce300-cf0a-11eb-82f2-4020b00ab72d.png)

**Comment by Nilvus** [comment]
> I don't know why ping me ;)

Just because I remember you answered another issue recently about cairo icons.

**Comment by Nilvus** [comment]
@Solarer: I made a mistake and @johnny-bit correct it. It's not font issue but an issue in general Gtk theme set in your system, outside darktable.

**Comment by johnny-bit** [comment]
I think the best way forward and to sum up would be:

1. instead of named icon from theme use X symbol from paint.c (`dtgtk_cairo_paint_multiply_small`)
2. create entry completion based on history and/or module names/aliases

I think pt1 is desireable - in my theme the "edit-clear" icon looks very much in place in darktable, but on Nilvus' screenshot it's big red dot that I wouldn't like... and is wholly dependent on ghtk theme. Plus if we could replace the button in the tagging module with clickabe icon it'd make interface of tagging module a tiiiiny bit clearer ;)

**Comment by darkelectron** [comment]
May be related to: #8592

**Comment by johnny-bit** [comment]
Thanks darkelectron! indeed #8592 asks for "create entry completion based on history of searches"  :)

**Comment by dterrahe** [comment]
#8078 changes the GtkEntry widget that was used for the search box to a GtkSearchEntry, which is a standard Gtk widget that provides the delete button automatically, without needing additional code, among some other refinements. Maybe @johnny-bit could provide feedback if this change has caused any issues for him.

Additionally, pressing enter moves the focus away from the search box, so that normal shortcuts start to work again.

**Comment by johnny-bit** [comment]
no problem at all with gtksearchentry while testing #8078 :)

**Comment by dterrahe** [comment]
Thank you!

For those who haven't tested 8078, this is what it looks like without anything entered:
![image](https://user-images.githubusercontent.com/1549490/122930351-d42eec00-d363-11eb-97ad-bd47470499d7.png)
and this once you've started typing:
![image](https://user-images.githubusercontent.com/1549490/122930455-ea3cac80-d363-11eb-9ebc-3349d0117944.png)

**Comment by johnny-bit** [comment]
@Solarer - since 8078 is in master... does it cover your usecase or are future enhancements needed?

**Comment by Solarer** [comment]
@johnny-bit looks good to me, thank you!
