### ISSUE TITLE
DT 3.4.1.1 crash Filmic

### ISSUE THREAD

**Issue by 35mm-foto** [darktable-org/darktable#9280]
Application crashed when I try to save preset for RGB filmic.

I am not able to reproduce, but generated report is attached.
Used versiom3.4.1.1 on W10 - 64bit

[darktable_bt_21WP40.txt](https://github.com/darktable-org/darktable/files/6680345/darktable_bt_21WP40.txt)

**Comment by johnny-bit** [comment]
The attached report does not mention anything about presets or filmic rgb, but rather a "possible problem" in searching shortcuts in preferences window. 

The "possible problem" is in quotes because the problem mentioned by report is "DEP violation" which means "data execution policy violation". The code in question is pure code and does not exectute data. I've came to regard "DEP violations" as more of indication of problem in the system than in the app itself.

For example - see this stack overflow answer: https://stackoverflow.com/a/19506360 and "solution 2" in this post: https://silicophilic.com/exception-access-violation-in-windows-10-how-to-fix/

@35mm-foto - since backtrace suggest "problem" is in different part of the application, can you reliably reproduce the problem? If yes then we'd need reproduction steps. If no... Consider closing the issue :) Also - next time PLEASE use issue template and fill all the relevant info.

@elstoc - while the backtrace suggest problems stem from your part of the code, I honestly doubt it's the case here. The crash with dep violation could be random and have no basis in reality of the code itself.

**Comment by elstoc** [comment]
Yeah, no idea I'm afraid.

**Comment by johnny-bit** [comment]
Yeah, Every DEP Violation we had so far was false positive.

I'm gonna close the issue and let's see if there's reliable reproduce way for it.

@35mm-foto - if you can: keep using darktable normally and see whether there's pattern to any breackages. If there isn't, eg when you create a module preset and other time same module preset creation works and the report says "DEP Violation" try the solution posted about DEPs as a workaround.

If you manage to crash it repeatedly in same conditions - then comment back and comment so we'll reopen the issue (or open new issue if you'd like)

**Comment by 35mm-foto** [comment]
I am, not possible to reproduce, as I wrote to my initial comment and able to work with program. Just hoped, that you will be able to read something from generated log. THX
