### ISSUE TITLE
crop preset does not activate module

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#9296]
**Describe the bug/issue**

The crop module does not activate the module when a preset is applied.

**To Reproduce**

1. Go to 'darkroom'
2. Create a preset for 'crop' module
3. Select another image (without crop being applied)
4. Select crop preset
5. See error, the module is not activated, the preset is not properly applied and the guides are visible

**Expected behavior**

The crop should be done, module activated and guide remain non visible.

This is what is done for other module, apply a preset on `monochrome` or `color zones` for example.

**Platform**

* darktable version : current master
* OS                : Linux
* Linux - Distro    : Debian/sid

**Comment by TurboGit** [comment]
@AlicVB I have assigned this to you as you've been working on crop recently.

**Comment by TurboGit** [comment]
Note that the `crop & rotate` module does exhibit also this behavior.

**Comment by AlicVB** [comment]
this seems quite the same as #9264 
I'll have a look !

**Comment by AlicVB** [comment]
@TurboGit : I have a problem here, the bug comes from : https://github.com/darktable-org/darktable/blob/5aa0f20fb1686937c7957d8618671e8390ea1250/src/gui/presets.c#L920 which is an addition made by you to fix #6090

if I understand correctly the 2 issues, we have issues because we are in the middle of the bridge now, so we have to choose between : 
1. applying a preset on a fold module doesn't change the module in focus
2. applying a preset on a fold module first expand the module and focus it, then apply the preset to it

I would vote for the first solution as it's more predicable, and the contrary can be unwanted in some workflow, esp. when using accels... (not to speak that it's the simplest to implement) What do you think ?

**Comment by TurboGit** [comment]
I would vote for 1 too. But then we need also to fix all issues in #6090 which had some very strange and unexpected behavior.

**Comment by AlicVB** [comment]
hmmm... do you remember the "strange and unexpected" behaviors ? because, if I can reproduce what is in the issue, I think that it's the correct behavior as soon as applying a preset doesn't change the focus module...

**Comment by TurboGit** [comment]
The "strange and unexpected" is this part on OP issue:

> This gets worse, now go to lightable and select a different image collection and double click an image from it. This image
> opens in darkroom with the vignette circle mask on it.

Of course, this happens even if the vignette is not selected and/or expanded.

**Comment by AlicVB** [comment]
I'm confuse now...
I don't see how your last sentence can be related to preset applied to another module... (and I can't reproduce)
Here is what I've done to test : 
1. click 2 time on modulegroup button to show all available modules
2. Open a new image, expand the vignetting module and set some values
3. without expanding the module, apply a preset in exposure module
4. the vignetting module keep the focus and so show the round overlay
5. go back to lighttable and back to darkroom with another image
6. the expanded module is vignetting as expected as it's the last one expanded... and the round overlays are visible as expected too...

If between 4 and 5 I expand another module, then the overlay disappear (normal) and on point 6, this is this module that get expanded, so the overlays are not visible as expected...

**Comment by TurboGit** [comment]
Maybe something has changed since my fix was done. I'll test your PR and will report my findings. Probably tomorrow now.
