### ISSUE TITLE
OSX: Input System NG: some issues with keyboard shortcuts (rating, preview)

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9376]
**Describe the bug/issue**
rating an image by typing 0..5 or r in lighttable is not recognised 
pressing h indicates 0..5 is defined for rating and r to reject rating

**To Reproduce**
1. select image in lighttable
2. type 0 
3. type 3
4. type r
--> rating isn't changed after each step

**Describe the bug/issue**
pressing w to open preview switches to preview mode but never returns after releasing

**To Reproduce**
1. select image in lighttable
2. press w --> preview is displayed
3. release w --> preview keeps being displayed

**Platform**

darktable version : darktable-3.7.0+178~gfb034c530
OS : OSx

**Comment by dterrahe** [comment]
Did you perhaps have a shortcutsrc hanging around from a few months ago?

ratings and color labels were restructured recently, but an old shortcutsrc would overwrite those new default mappings with mappings to now non-functional actions.

All of 0..5 and r should be mapped to "thumbtable/rating" with different Elements.

Advantages are that the shortcuts are now shown when hovering over the star icons and that you can increase/decrease rating with scroll (or other moves).

Would you mind splitting the preview problem into a separate issue; I need to investigate since I may have introduced that problem recently.

**Comment by MStraeten** [comment]
ok, after deleting keybordrc and shortcutrc everything is fine with rating. 
the "w" shortcut is now like clicking on the full size preview icon below the grid. I'll split the issue and close this.
