### ISSUE TITLE
NG Input: wrong group expanded in shortcut preferences

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9377]
3.7.0+106~ga1c0a6732

Go into preferences and select the shortcut tab. Click on (for example) the expand arrow beside "utility modules". "global" section is expanded instead.

Once I collapse the global section, it works normally (the correct group is expanded) when clicked.

**Comment by elstoc** [comment]
Actually the global section seems to expand wherever I click in the bottom pane.

**Comment by dterrahe** [comment]
Gtk treeview widgets have a lot of quirks that sometimes take a lot of effort to work around.

I find that if I click on "utility modules", rather than the arrow next to it, it works even the first time.

Other than that, this seems to be a focus gaining issue for the widget. I agree this is very annoying, but since from experience I know that experimenting to find workarounds for these kinds of issues is a tedious, long process (and then the next gtk release can break it) I'm not going to give this the highest priority right now.

Myself I don't run into this issue often, because I usually open the shortcut dialog via the shortcut button+clicking a screen region. Then it doesn't seem to occur? Myself, I would be in support of removing shortcuts from the preferences dialog completely (so that preferences also opens more quickly).

**Comment by elstoc** [comment]
> I find that if I click on "utility modules", rather than the arrow next to it

Click to expand is not the way most (all?) of the other treeview widgets work in darktable, so it's what most people will do by default.

> Myself, I would be in support of removing shortcuts from the preferences dialog completely

Into its own dialog? Most people will start exploring this from preferences since it's where they're used to finding shortcuts.

**Comment by dterrahe** [comment]
> clicking on the arrow is what most people will do by default.

Absolutely. And like I said, I agree it is an annoying bug and I'd really like to fix it. But at the moment I have no idea how and I know from experience these kind of bugs can take days.

> Most people will start exploring this from preferences

My worry is exactly that; that people will not realise there is a new and better way and keep using the old cumbersome one.

**Comment by johnny-bit** [comment]
> My worry is exactly that; that people will not realise there is a new and better way and keep using the old cumbersome one.

How about a note atop shortcuts setting tab (i know - wasting space...) that "you can set shortcuts directly using shortcut assign mode accessible by pressing [keys] buton" or something like this?

**Comment by dterrahe** [comment]
I'm glad we have loads of time during the 3.8 cycle for lots of polishing like this. My priority now is to get everything stable and I guess to end up with a list of FRs based on the experience people have in getting up to speed with the new framework. I don't think we immediately need to _implement_ all those new ideas without giving a bit more thought to what we want to end up with.

The input of documenters is very important; if it is very hard/impossible to explain certain features and they continue to cause confusion and loss of productivity, then removing them or putting them behind a config option has to be considered.

But if people eventually tend to like the flexibility, then we need to focus on how to get everybody to that point, starting with making them aware of the changes. There could be a huge "New In This Version" pop-up, just to let people know their keyboardrc doesn't work anymore and there's a new mapping button.

Or someone could work on a script to translate (inefficiently, but OK) keyboardrcs into shortcutsrcs on first run.

#8078 was always ment to be the basis, not the finished polished product. You don't start polishing until there is agreement the direction is sound. And we are only now starting to see some _real_ testing...
