### ISSUE TITLE
[3.6] add widget and add module in "manage module layouts" don't do anything

### ISSUE THREAD

**Issue by rafalkrupinski** [darktable-org/darktable#9400]
**Describe the bug/issue**

"add widget" and "add module" in "manage module layouts" don't do anything.
tested on macos.
both new and existing module layout is affected

edit:
| Macos 11.4
| only in fullscreen mode

**To Reproduce**
enter fullscreen mode
go to layout manager
click [+] button above quick access widgets or any module group

**Expected behavior**
module/widget selection modal appears

**Comment by AlicVB** [comment]
of course I can't reproduce (I've just tested again) otherwise that feature would be useless...
So there should be something specific on your side... maybe OSX... or some config...

On a side note we have a template with lot of infos for filling issues. This is not to annoy people, but because we need this infos to find the problem and try to solve it. In this case, the last part about systems, config files, etc... would be useful ! Thanks !

**Comment by rafalkrupinski** [comment]
Sorry for an incomplete report, I'm just not sure what else could I include.
Using the release from the website.
Macos 11.4
8GB RAM
Intel Iris Plus Graphics 650 1536 MB
using openCL
[darktablerc.txt](https://github.com/darktable-org/darktable/files/6759660/darktablerc.txt)

it worked before with 3.4.1
I don't use any scripts
The bug DOESN'T APPEAR when I run darktable with empty config dir

**Comment by AlicVB** [comment]
Thanks for the infos. That help !

> The bug DOESN'T APPEAR when I run darktable with empty config dir

ahah... so the issue seems to come from here. Let's try to narrow down the problem !
1. Can I ask you to try to remove/rename each file from you config dir one by one and see which file is causing problem ? (I would say it's data.db or darktablerc, but try the other too to be sure)
2. do this also happen if you create a new preset in the "manage" dialog ?

Thanks for your help !

**Comment by AlicVB** [comment]
also, if I read your rc file correctly, you seems to have userdefined css. Can you try to desctivate them ?

**Comment by rafalkrupinski** [comment]
- working on a new preset doesn't affect it - buggy with old configdir, not buggy with the new configdir
- removing the rc file - helped
- removing data.db - didn't help

thanks for _your_ help

**Comment by rafalkrupinski** [comment]
> also, if I read your rc file correctly, you seems to have userdefined css. Can you try to desctivate them ?

css "usertweak" was enabled but the contents was empty (just the default comment). Disabled it and restarted DT, didn't help.

Also the buttons kinda work (change their state), just the modal windows doesn't appear, see the attachment.

https://user-images.githubusercontent.com/3732079/124380967-45559400-dcc0-11eb-9a0a-dd8659839516.mov

**Comment by AlicVB** [comment]
Sadly, I've absolutely no idea of what can happen... I've not spotted anything obviously wrong in your draktablerc, and I've tried it for real with no issue...

if you have some time, you can try to narrow down which darktablerc line is cause the cause of the issue by doing a sort of bisecting : 
1. be sure to always keep a backup of darktablerc file
2. remove lines 1-600
3. test if you reproduce the issue
4. if yes, then the problem comes from somewhere in part 2 (lines 601-1136) otherwise it comes from part 1 (lines 1-600)
5. restart from your backup, remove the half of the problematic part, and test again...
6. and so on until you narrow down to the problematic line

Thanks !

**Comment by rafalkrupinski** [comment]
So I narrowed it down to lines 600-899 but removing any subset of that doesn't fix it.
That part doesn't seem to have many critical settings, so I'll just remove it and restore it through the UI.

Thanks for your help!

**Comment by rafalkrupinski** [comment]
@AlicVB does it work in fullscreen mode for you? that's what I've missed

**Comment by dterrahe** [comment]
Sounds like this issue was resolved for the OP. Please reopen if not. Thanks!

**Comment by rafalkrupinski** [comment]
Seems DT performs much better on my Linux machine, so

**Comment by abulka** [comment]
I'm getting this issue with version 4.2 on my Mac.
Clicking on the + to add widgets doesn't work.  The button highlights when I hover over it, but nothing happens when I click.

I deleted my `/Users/USERNAME/.config/darktable/darktablerc` file and restarted Darktable, and now it works.

What is the proper solution to this?  Perhaps by upgrading from earler versions of Darktable some incompatible settings have remained in `darktablerc`?

**Comment by rafalkrupinski** [comment]
Are you using dt in Full screen mode?
If so, try turning to normal mode. For me it was a problem with modal window not showing in Full screen.

**Comment by abulka** [comment]
Ah yes - even with my brand new `darktablerc` it stopped working again soon after. Turns out I was in fullscreen mode like you say! Thanks.
