### ISSUE TITLE
NG input: copy/paste shortcuts doesn't work in culling/preview mode

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#9428]
**Describe the bug/issue**
Since new shortcut manager, ctrl+c/ctrl+v and shift+ctrl+c/shift+ctrl+v doesn't work in culling/preview modes.

@dterrahe: probably for you.

**To Reproduce**

Just try them in culling or preview mode. For culling mode, I tested with 2 images but should be the same with more images.

Shortcuts works well in lighttable file manager default view and in darkroom and were working well with older system.

**Expected behavior**
Having those shortcuts working great in culling/preview modes.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.7.0+200~g76d1a261e
* OS                : Linux Ubuntu 21.04

**Comment by dterrahe** [comment]
Thanks for reporting this! 

This reminds me that there is still some work (and testing) to be done on shortcuts for hidden widgets.

Sometimes we hide a widget because we want to disable it; the shortcut then shouldn't work either. Sometimes we hide widgets because a module gets collapsed or the whole panel is hidden. Sometimes buttons don't get created at all because they have been hidden from the start.

The shortcut code needs to be able to deal with buttons that respond to different kinds of events:
- button press/release (this can include a modifier state; ctrl/shift/alt)
- clicked
- toggled

Gtk seems to ignore events sent to hidden _buttons_, but not _toggle_ buttons.

It also ignores gtk_button_clicked, for buttons (but happily passes the clicked event to toggle buttons). 

I'm now testing if gtk_widget_activate works.
