### ISSUE TITLE
Tool to collect info for issue submission

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#9439]
**Is your feature request related to a problem? Please describe.**
Developers need detailed info for bug reports; the bug report template already contains a section to provide them (from OS version to GTK and hardware). Typing (and gathering) it is time-consuming, and there will be users who won't even understand what info they need to provide.

**Describe the solution you'd like**
I suggest that a small diagnostic tool is provided that users can run, and can paste its output into the bug report. Ideally, the tool would populate the clipboard, so users not familiar with the console could just click an icon and then paste info into the bug report. The bug report template would need to be updated to contain a reference to the tool.
I'm afraid such a tool would need lots of OS-specific code (but maybe MacOS is 'Unix enough', and Windows has more and more Linux compatibility features).

**Alternatives**
- Manual entry, as done now.
- Adding the functionality directly to darktable, e.g. to the _About_ dialogue (will not help if darktable, for some reason, is unable to start)

**Comment by jade-nl** [comment]
@johnny-bit remembered that I made an *info gathering tool* (that creates copy/paste-able markdown output)  and asked me via IRC #darktable to have a look at your feature request.

Turns out that your idea is rather comprehensive and probably not at all easy to realize. Well, at least not as a *small diagnostic tool*.

I do not have a developers background so I'm lost when it comes to the likes of C(++) or other higher languages which might make things somewhat easier; Bash scripting and the command line is what I am reasonably good at. That being said:

There are a lot of issues that need to be tackled to make this successful. I'll limit myself to just  one issue on a Linux system to give you an idea: _Graphics card (Vendor+type)_ and accompanying _driver (+version)_.

Just to give you some context: My 3 machines, all run the latest Debian and all have Nvidia graphics cards. Should be easy to get that info, right?

* lspci (with or without options) tells you which brand your video card is. But depending on the card it does or does not tell you its type. Actually it does tell: 1F06 for example. But you need info from a third party website to figure out what that means and this might not be all that reliable and/or up-to-date (https://devicehunt.com/search/type/pci/vendor/10DE/device/any).
* Using Vendor specific software to get the type and other info only works if it is installed (it isn't by default).
* lshw and hwinfo also aren't able to help (besides they need root access, so not really an option to begin with).
* The Xorg log in /var/log might be of help, but then you are assuming that the provided info is correct to begin with and that Xorg is being used and not Wayland.

OK, lets step away from this and lets get the driver and its version number!

* lspci can give you the general name of the driver, no problem there.
*  The version is a bit more complicated though. On debian you basically have three possibilities: Nouveau (open source), legacy drivers (NVidia, but "free") and proprietary, which would be *alternative*, and you don't have a clue what the actual full driver name is (lspci output is way to general *nvidia* or *nouveau*). Oh, and what is proprietary and has *alternative* in its driver name now can be *legacy* later on.

So you have these you can choose from and sort out atm:

- xserver-xorg-video-nouveau
- nvidia-driver
- nvidia-alternative
- nvidia-legacy-304xx-driver
- nvidia-legacy-390xx-driver
- \<future legacy driver\>

Just remembered: looking in */sys/module/nvidia* and/or */sys/bus/pci/drivers/nvidia* to get version info is also a roll of the dice. Some vendor do and some don't provide that info for a specific type of card.

There are a few more places you can look, none of them work all the time though.

I ended up making (parts of) my *info gathering tool* machine specific and it also uses some (Nvidia specific) software I specifically had to install. I gave my script to someone else running Gentoo and also having Nvidia graphics and he had to do some serious tinkering to get certain parts to generate the correct output.

I'm sure that you will encounter different hurdles when another distro (=package management) is being used and/or one has an AMD or integrated graphics card.

Is what you want impossible: I'm sure it isn't impossible, but it will need some serious programming and needs to be meticulously maintained. Especially if this needs to be done for all 3 OS's that are supported by darktable.

I'm not sure if all that is worth the effort to facilitate a handful of  users to more easily provide some info.....

**Comment by kofa73** [comment]
Thank you very much for looking into this. I understand the complications involved.
Maybe you could use darktable-cltest in your script? It prints stuff like:
```
[opencl_init] device 0: GeForce GTX 1060 6GB 
     CANONICAL_NAME:           geforce
     GLOBAL_MEM_SIZE:          6077MB
     MAX_WORK_GROUP_SIZE:      1024
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 1024 1024 64 ]
     DRIVER_VERSION:           460.80
     DEVICE_VERSION:           OpenCL 1.2 CUDA
```

**Comment by jade-nl** [comment]
> Maybe you could use darktable-cltest in your script? 

Nope, that is not an option. 2 reasons:

1. If a machines does not support opencl, running that command will give you no info whatsoever.
2. A bug is being reported, which means that darktable is possibly broken. In this case you mustn't assume that darktable-cltest will work correctly/at all.

**Comment by kofa73** [comment]
OK, it was just an idea.
