### ISSUE TITLE
Opening in darktable causes wrong module instance to be opened.

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#9460]
dt 3.7.0+245~g05f381e95    Ubuntu

Seems like a minor bug.

Suppose you are in darktable and have a second instance of color balance rgb with a mask opened up and switched on. Also the "original" module is not opened up and is not switched on.  You now go to lighttable, then back to darktable.  Now the original instance is opened up and the second one is closed.  (Their on/off status is correct)

Ideally dt would remember the config, but it's obviously not a big issue.

**Comment by elstoc** [comment]
I think this is "as designed". It just remembers the last module that was open _in the darkroom_ and keeps that module open the next time you open the darkroom (regardless of whether it's the same image being opened again). Since it doesn't remember instance names it just opens the first (base) instance. We could try to be clever with it but ultimately that would only really work if you opened the same image twice, which is a bit of a corner case.

**Comment by RawConvert** [comment]
Going back into the same image is my case really! (although I see you can export from darktable now, so that's one less reason to re-enter)  But agree it's a minor thing. So if that's the design, I'll close.
