### ISSUE TITLE
Settings toggle for 'modern' highlight reconstruction

### ISSUE THREAD

**Issue by Egocentrix** [darktable-org/darktable#9509]
With the modern scene referred pipe I find myself often disabling the highlight reconstruction/clipping module, because the filmic curve and reconstruction seem to give much nicer results, softer white clipping and less unexpected color shift. I would like some way to automate disabling that module.

It can be done with a style or preset that is applied by default to all pictures (and keep it a personal choice on a picture-by-picture basis), but a nicer solution (at least to me) is to add a toggle to settings. There are already toggles for the modern scene-referred pipeline and modern colour calibration instead of white balance. It seems like a logical next step to add a toggle for modern highlight reconstruction, where the highlight reconstruction module is disabled and everything is handled by filmic rgb.

What do you think about this? Or am I missing something technical and *should* I be enabling the highlight reconstruction module anyway?

**Comment by TurboGit** [comment]
Maybe just disable highlight reconstruction when scene-referred is set as indeed Filmic will do the work.

@aurelienpierre : What's your thinking on this?

**Comment by elstoc** [comment]
Filmic will only do the work if its highlight reconstruction is enabled, which by default it is not, due to performance considerations. Without it being enabled (and some adjustment to the gray/colorful details slider), you will get magenta casts in highlights.

IMO we need to either replace the earlier highlight reconstruction module with something better or leave it to user choice (which can be made with a preset).

**Comment by acornsirup** [comment]
I also think that providing another toggle in settings, just like the "sharpen" option, is the best idea. I also disable the highlights reconstruction more often than not.

**Comment by Egocentrix** [comment]
Still think it would be nice to have, PR #10711 may make this request obsolete?
