### ISSUE TITLE
NG Input: darktable is sending midi events continuously

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9621]
having enabled a midi monitor to check side effects from an attached keyboard stack i found that darktable send midi events to the devices   

**To Reproduce**
- attach some midi devices
- enable a midi monitor
- darktable continuously sends Note Off events

**Expected behavior**
- darktable just receives midi events instead of sending some

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : darktable-3.7.0+498~g3ccd1f881
* OS                : OSx

**Comment by dterrahe** [comment]
Some midi devices (at least x-touch mini and beatstep) have lights under their buttons and around their knobs). These are updated based on the positions of their mapped sliders and/or toggle buttons (see video in https://github.com/dterrahe/darktable/wiki/Showcase). There is a timer loop that always keeps them in sync. Once there is more of a configuration framework for midi devices, this could be disabled for devices without lights. Or updates could be sent only when widgets change status (although this would require a lot more notification management and complexity).

However since the x-touch doesn't send anything when switching between Layer A&B and silently ignores updates for the invisible layer, light correctness can't be guaranteed unless synced continuously.

Another reason midi needs to _send_ messages to devices with limitless knobs with lights (like x-touch) is that it simulates unlimited resolution (i.e. variable by holding ctrl or shift or changing shortcut speed) by updating the knob position (which is in 0-127) after each move. But those updates of course only are sent when moving the knob, not continuously.

**Comment by MStraeten** [comment]
Maybe this effect will be mitigated if there’s a way to configure, which Midi devices should be used …

**Comment by dterrahe** [comment]
That's definitely the intention.

**Comment by MStraeten** [comment]
then i close this to avoid noise ...
