### ISSUE TITLE
FR: A new Preference under darkroom/modules

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#9644]
I've been playing around a lot with second instances of some modules, and when I do, I always rename the module to indicate what that instance is doing.
And every time, I have to manually click on the multiple instances icon, and select Rename.
I would love to see a checkbox preference under darkroom/modules that says something like "Prompt for name on addition of new instance".
So, the moment you invoke a new instance of any module, darktable gives you the rename box straight away.
Just a thought.
Cheers.

**Comment by TurboGit** [comment]
Hi Bruce, you can ctrl-click on the instance name to enter the edit mode.

**Comment by brucewilliamsphotography** [comment]
Urgh... I'm sure I KNEW that at some point. I'd just forgotten it.
Yeah, good call.
Close the feature request.
Sorry.

**Comment by johnny-bit** [comment]
I still wonder about implementing double-clicking for that instead of ctrl-click...

**Comment by johnny-bit** [comment]
@dterrahe - do you thing it would be fit for input NG or would it be ok to try and use "normal" gtk way of detecting double click on header to initiate rename?

**Comment by dterrahe** [comment]
It is a trivial change in `_iop_plugin_header_button_press`:
`    else if(dt_modifier_is(e->state, GDK_CONTROL_MASK))
` to
`    else if(dt_modifier_is(e->state, GDK_CONTROL_MASK) || e->type == GDK_2BUTTON_PRESS)
`
(and also remove the first line in the function
`  if(e->type == GDK_2BUTTON_PRESS || e->type == GDK_3BUTTON_PRESS) return TRUE;`
so that double and triple clicks don't get ignored)

But I would still _not_ do this, because reserving many different ways to do the same thing just means that double click can't in future be used for something else. Without somebody complaining at least. But feel free to disagree :-)

Input NG (for now) is only concerned with shortcuts, not with direct manipulation of widgets by mouse.
You can already assign a shortcut to the multi-instance/rename effect, but it would be a module specific shortcut. #9487 lists the idea of generic shortcuts for the _focused_ module. This would/could be part of that. (of course the _blending_ shortcuts fall in that category as well.)
