### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by tobeexplained** [darktable-org/darktable#9647]
I'm not exactly sure how to report this but.  Darktable started crashing when I try to open an image.
[darktable_bt_FZ9L70.txt](https://github.com/darktable-org/darktable/files/6887113/darktable_bt_FZ9L70.txt)

**Comment by wpferguson** [comment]
The template had questions to fill out that would help us to understand what was happening when darktable crashed. Could you at least tell us what you were doing when the crash occurred?

**Comment by tobeexplained** [comment]
I was trying to open an image (I think the xml data was corrupted) .  I
ended up moving the file to a different folder, deleting the XML file,
reopening darktable deleted the now non-existent image from the
lighttable.  Then I moved the file back to the original folder and
reimported it.  I lost all the adjustment I had made but I didn't lose the
file.

**Comment by Nilvus** [comment]
> I was trying to open an image (I think the xml data was corrupted) . I ended up moving the file to a different folder, deleting the XML file, reopening darktable deleted the now non-existent image from the lighttable. Then I moved the file back to the original folder and reimported it. I lost all the adjustment I had made but I didn't lose the file.

It's not clear. Do you still have the issue or not? And you lack a lot of infos asked in issue template (they are useful, like OS, darktable version used, etc.).

On what I understand on your reply is that you have crash with the xmp related to the image present and you don't have it after removing it. If it's right, so the issue was the corrupted xmp, not darktable. And so, please close this issue as we can't do more here. If not, please be really more precise.

**Comment by tobeexplained** [comment]
I've resolved the issue.  I'm running the latest ver. 3.6.0.  I didn't see
a template.
Thank you for all the support.  You guys do an amazing job.



Wes

**Comment by Nilvus** [comment]
The template is written when you open an issue. It can't be seen.

Then, when solving an issue, it's good to close it.
