### ISSUE TITLE
[FR] image navigation by mouse

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#9662]
Hello

Please consider adding image navigation ("image back" and "image forward") by mouse in all modes. 

To do this, I propose to use a combination of RMB + wheel rotation 
(this is how tabs switching was implemented in the Opera browser).

Perhaps this will be appreciated not only by longtime fans of the aforementioned browser.

**Comment by Nilvus** [comment]
@dterrahe: I was thinking that was possible with your big work about NG Input but I didn't succeed to set that for darkroom previous/next image options. Tooltip when pointing on a shortcut to set said that is possible. An issue or a part not implemented by now?

@esq4: did you test the actual master and new way to set shortcuts? If you don't know what I'm talking about here, see #8078

**Comment by dterrahe** [comment]
Input NG at the moment only provides shortcuts, meaning a key press combined with mouse buttons/moves. So you _could_ define a keyboard (or gaming mouse) key to start the shortcut and then set up left and right to move back or forward. Possibly you could configure X to treat RMB as a key press (but that would disable it for anything else so I doubt you'd want to do that).

However the proposed method responds to just a mouse button to trigger the start of an action. These kinds of "gestures" are currently handled at the view level (presumably this would only work on the centre view, since some widgets themselves respond to RMB). Making this fully configurable would require a lot of extra infrastructure and complexity and at the moment I'm not convinced it is worth it. The  feedback from Input NG suggests that very few people like, or are willing to deal with, complexity...

Which would leave, for now, the option of implementing this behavior as a special case. Simultaneous button click and scroll sounds like a recipe for RSI to me, but I would not object if someone wanted to implement it in the darkroom view (taking care to not make it conflict with mask editing etc). Maybe this FR could serve as a survey to find out how much interest there is for this feature.

**Comment by esq4** [comment]
> Which would leave, for now, the option of implementing this behavior as a special case. Simultaneous button click and scroll sounds like a recipe for RSI to me, but I would not object if someone wanted to implement it in the darkroom view (taking care to not make it conflict with mask editing etc). Maybe this FR could serve as a survey to find out how much interest there is for this feature.

I will definitely try to implement it as soon as I understand where it can be done.  If nobody gets ahead of me. :)

**Comment by esq4** [comment]
https://github.com/darktable-org/darktable/pull/9891
It turned out like this.

**Comment by esq4** [comment]
@dterrahe In the course of my research, I discovered that _button_released_ and _button_pressed_ are defined, but not used, in many modules. Could it be trash?

**Comment by dterrahe** [comment]
From the discussions in the several PRs there is little appetite to merge this into core dt. Maybe this functionality can be achieved using external utilities, but I think it is reasonable to close this FR at this point.
