### ISSUE TITLE
Groups joining

### ISSUE THREAD

**Issue by borjeJ** [darktable-org/darktable#9670]
Hello

I use Win10 and darktable 3.7.0 but I have seen this behaviour on Manjaro with darktable 3.6.0 also. 

I use groups frequently and I found that if I make a group and then change the lead picture in this group then will the following grop be attached to the first. If I do not change the lead picture in the first group it works like expected, i.e. two separate groups. 

However it´s quite simple to get around, knowing that you change the leadimage in the last group. When making the second group, first click group, then ungroup and again group.

**Comment by wpferguson** [comment]
Could you please provide a step by step process to make this happen?  I'm not sure I can get enough information from the above to recreate the behavior.  What behavior do you expect to have?  And, what behavior do you want to have?

The bug report template has sections to fill out that give us the necessary information to understand and recreate the problem so that we can determine what to do about it.  It would be best if you closed this, then opened a bug report issue and filled out the sections so that we can help you.

**Comment by borjeJ** [comment]
OK

In darkroom, lighttable Let´s say I have a number of images.
I select some of them, let´s say five and click the group button.
Now I have a group of five and the first image is considered as the lead, the one displayed when groups are collapsed.
But in this case I change the lead image to number three. 

When I continue and make a second group I select four images in a new group making sure that the images in the preceding group are not selected. 
I click the group button and now I should have two groups the first of five images and second of four but in fact I have one group of nine images, the group I just created becomes a part of the last group of five so instead of having two groups of five and four this becomes a group of nine. 

As I mentioned I can correct this by first click on group then ungroup and again group. That will give me two groups of five and four images. 

Hope this will clarify the problem.

**Comment by wpferguson** [comment]
@AlicVB could you look at this please?

Steps to reproduce

* lighttable in file manager mode, 5 images per row, more than 15 images
* select images in row 1 and group.  I'll refer to this as group A
* select images in row 3 and group.  I'll refer to this as group B
* click an image in rows 2 or 4 so that no grouped images are selected
* move mouse over group A and notice group A and group B are surrounded by grouping box
* hover over group icon in first image of group A and notice 10 images in group
* hover over 3rd image in group B and notice it is also the group leader with 10 images in the group.

Selecting group A, ungrouping it, then regrouping it breaks the connection.

Grouping row 3 first then row 1 sometimes worked correctly (2 groups) and sometimes resulted in just 1 group.

On group B why did the 3rd image in the group become the leader instead of the first?

Reproduced on current master, ubuntu 18.04

**Comment by borjeJ** [comment]
Hi

I tried to follow your steps but for me this works as it should. When I hover over the groupicon in all images it states 5 images regardless if it is group A or group B. 

The funny thing happends when I, after creating group A changes the lead image to something else then image one and after that I create group B. Hovering over the the groupicons will then state 10 images both in group A and B. If I do not change the lead image in group A it works like it should.
