### ISSUE TITLE
color balance rgb’s slider naming causes problems with quick access panel

### ISSUE THREAD

**Issue by SWSRN** [darktable-org/darktable#9736]
**Introduction**
I am trying to add certain sliders to the quick access panel (my own preset) from color balance rgb but I can only select the wrong sliders -- the ones I want are not listed.

**Describe the bug/issue**
I want to load into my quick access panel preset the following sliders in color balance rgb:
Master perceptual brilliance grading : global
Master perceptual brilliance grading : shadows
Master perceptual brilliance grading : highlights
Master perceptual brilliance grading : midtones

I get the correct slider for global because the slider names global vibrance, global chroma, and global saturation don’t conflict with it.

The names shadows, highlights and midtones are reused in the module. I can only select the following sliders which have the first instance of those names.
Master perceptual chroma grading : shadows
Master perceptual chroma grading : highlights
Master perceptual chroma grading : midtones
I don’t want these sliders.

I believe that this is a bug and not intentionally planned this way. Please rename the sliders to make them unique.

**Expected behavior**
All sliders in color balance rgb should have unique names. All sliders show up in the add drop down menu when editing the  quick access panel preset. 

**Screenshots**
<img width="383" alt="Screen Shot 2021-08-05 at 11 41 54 AM" src="https://user-images.githubusercontent.com/9578196/128403160-ae188723-0a37-49c8-8476-fd9aa9cece42.png">

<img width="2048" alt="Screen Shot 2021-08-05 at 2 44 09 PM" src="https://user-images.githubusercontent.com/9578196/128404256-5d78a7a2-1d29-4c49-8111-04b0b839056a.png">

**Platform**
* darktable version : 3.6.0+3-g4287791fe
* OS                : Os 11.4 Big Sur

**Comment by aurelienpierre** [comment]
1. "global" got properly renamed "global brilliance" in master, so that one is fixed,
2. labels like "Master perceptual brilliance grading : global" are not possible as they way too much GUI real estate. All the more since English is a quite concise language, but German and French tend to use longer words and that will backfire. I see you use quite large sidebars, but that's rather unusual.
3. Color balance is an advanced module with fine-grained control. This is the opposite mindset of the quick access panel one, which is meant to synthesize the most used and fairly basic features in an unified view. Squeezing the color balance settings in there is a contradiction in that regard. Only the global chroma/vibrance/saturation make sense in there, the rest is not desirable nor really suited.

**Comment by SWSRN** [comment]
Thank you for the feedback. Just some clarifications on what I was intending:
2. I used those long names like "Master perceptual brilliance grading : global" to try to be clear as to which tab, etc., I was indicating. The actual slider names should be something like "highlights brilliance", "shadows brilliance" and "midtones brilliance"--- like "global brilliance". All about the same length. 
3. If the minor sliders shouldn't be included by design, you need to remove chroma's "highlights", "shadows" and "midtones" from the quick select panel's add menu. Or should everything be available and the user should know better than to select too many items (or ill-suited ones) for the quick access panel? I'm not sure who is deciding which sliders are appropriate out of all the possible ones for the quick access panel: the designer or the user?

**Comment by MStraeten** [comment]
the developer decides - because he's the one doing the job ;)
and btw: the developers eats their own dogfood - they implement stuff they need and use and aren't provided otherwise
