### ISSUE TITLE
can't import picture!!! help plz

### ISSUE THREAD

**Issue by newsky017** [darktable-org/darktable#9746]
Download version 3.6 darktable
When I drag a photo to darktable or add to library to import a photo, it says imported images, but there is no change.

Also, when I import photos by clicking the copy & import button, darktable is turned off.

please tell me how to solve it quickly

And please reply to macoto724@naver.com

**Comment by johnny-bit** [comment]
understood: unclear.

You haven't used the recommended issue template and the vital informations are missing. What os are you on? Did the path contain diacritic characters? What files? What errors are shown? There's nothing actionable in your report and nothing that can be done "quickly"

if you want quick solution you can check test release from "insider" program available here: https://discuss.pixls.us/t/darktable-windows-insider-program-8-1/26215?u=johnny-bit it has all the bugs fixed and new bugs introduced so proceed with caution.

**Comment by MStraeten** [comment]
check your rating filter and the default setting for rating import. No rating is handled as 0 rating in some camera exifs.

**Comment by andreilabato** [comment]
I have the same issue on Windows 10, using darktable 3.6.1 when I try to import  pictures from my profile pictures path.
**Please note that I have a special character in this pictures path (my user name contains one). When I try to import the same files located in a path without special characters, it works fine!**

**Comment by andreilabato** [comment]
I add that when I want to move images already loaded successfully in DT3.6.1, into a folder path with special character it does not work=> after the confirmation message "do you really want to physically move 29 images to C:\users\André\Pictures\...? nothng happens!

**Comment by johnny-bit** [comment]
@andreilabato - I think you are using not 3.6.1 but 3.6.0.1... the fix for "special chars in path in windows" will be included in 3.6.1 release which isn't yet released.

@newsky017 - if your issue is same as @andreilabato's then the isue will be fixed with 3.6.1 release (or you could try mentioned insider's program)

I believe that this can be closed

**Comment by johnny-bit** [comment]
@andreilabato - if you can, please test if your "move images" issue with path containing special characters is fixed using "insiders" duild as specified in https://discuss.pixls.us/t/darktable-windows-insider-program-8-1/26215?u=johnny-bit

In case it's not fixed, please open new issue.

Closing this issue since it's incomplete. @newsky017 - if you follow @MStraeten's advice or test insiders build and you still have issue, please comment with all the required detail and I'll reopen the issue for further investigation.
