### ISSUE TITLE
Reimported images are updating all the xmp files 

### ISSUE THREAD

**Issue by risbac** [darktable-org/darktable#9748]
I'm using XMP files to synchronise my editing between various computers. Everything is synchronized with my NAS, from two computers. This way, I can keep editing files on both computers. What I'm doing after editing on one computer is re-importing the folder with the RAWs. I have to do that to let darktable see the new xmps. It's updating the current ones, but it doesn't see the new ones. By reimporting the folder, it sees the new xmps and I see the new versions for my photos. 

Since probably version 3.6, when I reimport the folder, it updates every xmp files to the current date and time. It's not really a problem for my editing (it still sees the new versions), but it's updating a lot of files which didn't change at all, resulting in a heavy synchronization with my NAS, and the last update time for every XMP doesn't mean much now. 

So it's not a major problem, Darktable is working fine for my editing, but it used to import the XMPs without changing their last update time. 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Import a folder with RAWs and xmp files that are already in the photo database
2. Check the update date of the XMP files, they are all updated to the current time

**Expected behavior**
I would expect the update date of the XMP to stay the same, since technically speaking, nothing was changed in the content (but Darktable is now updating the "import timestamp" in the XMP file, and I guess it was not doing it before). 

**Platform**

darktable version : 3.6, on Ubuntu 21.04

**Comment by MStraeten** [comment]
import timestamp is set on import. If you reimport stuff then it’s the date of the reimport.
If you just want to update according to the changed xmp have a look at https://www.darktable.org/usermanual/3.6/en/overview/sidecar-files/sidecar/ and https://www.darktable.org/usermanual/3.6/en/preferences-settings/storage/#xmp

**Comment by risbac** [comment]
Thanks for your answer ! I know about the changed xmps, but it's not working as written in the documentation : 
"Activating this option also causes darktable to check for text sidecar files that have been added after import time"

Let's say that I have one photo synchronized on both computers. I update the photo on computer A (version 1) and I also create a new version 2. I have 2 xmps for this raw on computer A, and they both get synchronized on computer B. But when I open Darktable on computer B, it does NOT create the V2 for that photo. It only offers to update from the XMP it knows already. My first version for this raw is updated, but I simply don't see version 2 on computer B. 

That's why until now, I was re-importing the whole folder each time, that was the only way to see new XMPs. It's still working, but it's updating every single xmp in the folder. Not a major issue, but if I have 500 or 1000 raws in a folder, that's a lot of files to synchronize for no reason. 

And in any case, the documentation sounds misleading, it talks about sidecar files created AFTER the initial import, but it's not seeing them. Or maybe just for the additional versions.

**Comment by phweyland** [comment]
> I know about the changed xmps, but it's not working as written in the documentation :
> "Activating this option also causes darktable to check for text sidecar files that have been added after import time"

This is correct. That works when you open dt, but NOT during subsequent imports.

I don't know which version of dt you come from, but the process you describe as working should not have worked since "import timestamp" has been introduced. 

I think you would like the option "look for updated xmp files on startup" looks also after new xmp(s). Alternatively a new option could be added for that.

**Comment by risbac** [comment]
Yes you could be right Philippe, maybe it never did what I say and I was not noticing it with my previous NAS. i checked the previous big set that I worked on with the 2 computers, and all the XMPs have the same update time. 
Indeed, what would be nice would be a scan for new XMPs and not just updated existing XMPs. That would avoid to reimport many times, making the import timestamp quite wrong.

**Comment by phweyland** [comment]
Could I suggest you close this issue and open a new request to add the new xmp detection (to start a clean thread) ?

**Comment by phweyland** [comment]
pinging @elstoc ,... may have good idea about this.

**Comment by risbac** [comment]
Should I close this ticket and open another request then ? Not too sure when I see your first EDIT :)

**Comment by phweyland** [comment]
Looking at this again... Just some thoughts.

Crawler compares image versions existing in db with corresponding xmp files to check if there is a change (newer timestamp).
But it doesn't check if there is new xmp(version) for that image and ignore missing xmp.

Crawler could look at new xmp for an existing image in db, but doesn't detect new image. This is done by the import function.

On its side, import function ([add to library]) looks at image files whenever it exists in db or not, ignoring xmp files. On import action all xmp are considered even if the version already exists. Combined with "import timestamp" this is the source of your concern (because the xmp is written again with the new "import timestamp").

Remains the case of an existing db version which has no xmp (considering that "write xmp" is on). This is not detected anywhere.
But for your use case you may want to remove the corresponding version from the db (considering that "write xmp" is on).

**Comment by phweyland** [comment]
Since I rely only on
xmp files to synch everything between multiple computers, they are always
written. 

But when you delete a duplicate, the corresponding xmp is also deleted.

**Comment by risbac** [comment]
Ah yes, didn't think about this one. So in fact what I'm doing is tagging
every image I delete with the "rejected grade" (the ❌). And from time to
time, I delete all the photos with this grade. This way they are deleted on
all the computers, just not at the same time. It's not perfect, but since
it's fast and for the whole collection, it's fine.
