### ISSUE TITLE
Incomplete pop-up menu of tag dictionary section in list mode (DT 3.6.0)

### ISSUE THREAD

**Issue by henkux** [darktable-org/darktable#9760]
The right click pop up menu of the tag dictionary section is not complete in case of list view.

In tree view the sub menu shows in the second part options to create, delete, edit and change path.
In case list view is selected, this part of the menu is empty.

The manual does not state that there is different behaviour to be expected between the list and tree view.
So I assume that this is an error somewhere?

I'm running dual boot Linux Mint and Windows 10. Both with Darktable 3.6.0. On Linux as a flatpack.
Both show the same issue.

**Comment by phweyland** [comment]
The only difference is the presence of "change path", between list and tree views.
I guess you are on "suggestions" view instead of "list" view (sign "+" active).
This is normal. The context menu offers actions which makes senses ... in that context ...

This said I agree the double line is a bit misleading:
![image](https://user-images.githubusercontent.com/23012047/128705513-963e7c1e-5868-4dc6-8011-6570602db6de.png)

**Comment by henkux** [comment]
Mmm, there are more menu items 'missing'.  Yes, and I'm aware that it is a context menu. But e.g. I don't see why the edit option should not be available in list mode.
![TagDictionaryMenuDiscrepancy](https://user-images.githubusercontent.com/33800844/128918268-df5711b3-5556-401a-a3a3-8a5a9bc9e54b.png)

**Comment by phweyland** [comment]
The right view corresponds to Suggestions view ("+" is highlighted), not to List view. Just click on "+" to switch to List view.
Suggestions only shows a subset of the tags. That's why most of the operations are not available.

**Comment by johnny-bit** [comment]
I don't want to go and check if the menu was as you say "complete" in previous versions, but i browsed git blame and the logic for not showing create/delete/edit items at least since #2850

the suggestion view is constrained therefore not able to have all items in menu.

if as you mention the manual does not inform you the fact that those view differ in abilities, please fill an issue with https://github.com/darktable-org/dtdocs

Code-wise - I don't see how we can add the functionality you want "easily". Obviously "patches welcome".

That being said - this bug as it stands is invalid. Consider closing.

**Comment by henkux** [comment]
Thanks phweyland! Disabling suggestions made the context menu in list mode complete again.
