### ISSUE TITLE
Unhandled exception occurred

### ISSUE THREAD

**Issue by mohxinn** [darktable-org/darktable#9794]
Unhandled exception occurred when moving to next photo after editing in the same folder. This happens quite frequently. Photos are from Sony A7C

Attaching multiple backtraces. All caused by moving to next photo after editing the current one.

I am using Logitech option and have set mouse wheel click to right/left for moving to next/previous photo. I have been using Logitech Options on Windows 10 with the same darktable version and never experienced this issue before.

Backtraces:

[darktable_bt_0L5370.txt](https://github.com/darktable-org/darktable/files/6967751/darktable_bt_0L5370.txt)
[darktable_bt_6RYZ70.txt](https://github.com/darktable-org/darktable/files/6967752/darktable_bt_6RYZ70.txt)
[darktable_bt_09WX70.txt](https://github.com/darktable-org/darktable/files/6967753/darktable_bt_09WX70.txt)
[darktable_bt_12LX70.txt](https://github.com/darktable-org/darktable/files/6967754/darktable_bt_12LX70.txt)
[darktable_bt_A2B170.txt](https://github.com/darktable-org/darktable/files/6967755/darktable_bt_A2B170.txt)
[darktable_bt_C7D970.txt](https://github.com/darktable-org/darktable/files/6967756/darktable_bt_C7D970.txt)
[darktable_bt_FK1270.txt](https://github.com/darktable-org/darktable/files/6967757/darktable_bt_FK1270.txt)
[darktable_bt_FWEU70.txt](https://github.com/darktable-org/darktable/files/6967758/darktable_bt_FWEU70.txt)
[darktable_bt_GJD370.txt](https://github.com/darktable-org/darktable/files/6967759/darktable_bt_GJD370.txt)
[darktable_bt_HGK270.txt](https://github.com/darktable-org/darktable/files/6967760/darktable_bt_HGK270.txt)
[darktable_bt_IICX70.txt](https://github.com/darktable-org/darktable/files/6967761/darktable_bt_IICX70.txt)
[darktable_bt_LFOT70.txt](https://github.com/darktable-org/darktable/files/6967762/darktable_bt_LFOT70.txt)
[darktable_bt_MYNZ70.txt](https://github.com/darktable-org/darktable/files/6967763/darktable_bt_MYNZ70.txt)
[darktable_bt_NCIF80.txt](https://github.com/darktable-org/darktable/files/6967764/darktable_bt_NCIF80.txt)
[darktable_bt_OGMX70.txt](https://github.com/darktable-org/darktable/files/6967766/darktable_bt_OGMX70.txt)
[darktable_bt_OJ2X70.txt](https://github.com/darktable-org/darktable/files/6967767/darktable_bt_OJ2X70.txt)
[darktable_bt_OZ6W70.txt](https://github.com/darktable-org/darktable/files/6967768/darktable_bt_OZ6W70.txt)
[darktable_bt_QO8V70.txt](https://github.com/darktable-org/darktable/files/6967769/darktable_bt_QO8V70.txt)
[darktable_bt_TXDW70.txt](https://github.com/darktable-org/darktable/files/6967749/darktable_bt_TXDW70.txt)

Darktable version: 3.6.0.1
OS: Windows 11 Version	10.0.22000 Build 22000

System Info:

![image](https://user-images.githubusercontent.com/41345954/129198369-aa1a982b-0e05-4af5-86d7-c204fcfbc85e.png)

**Comment by mohxinn** [comment]
This issue makes darktable very difficult to use :-( I don't see any crash with any other software including Lightroom so that probably means it is not an issue with my system or?

**Comment by johnny-bit** [comment]
There are couple issues with your issue report. First and foremost you haven't used offered issue template, which would guide you to pass certain information about your system, setup etc. Would ask you to try with clean config & db to see whether or not it's some resident issue in config/db...

Obviously switching between images is pretty important and often used functionality. The fact that it's probably 1st report that i've seen about crashes with it points to problem being actually on your system.

Here are the questions, please answer them all:

How **To Reproduce**?
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

In your case how you're swithcing between images is necessary info too.

Can you provide **Screencast**? Eg record your screen + keys while switching between images that would show the error?

Couple additional questions:
 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by mohxinn** [comment]
I recorded an editing session where the crash occurred. The crash occurred after some time so the clip is 6 mins long. Too big to upload here:

OneDrive link:
https://1drv.ms/v/s!Aq87ZQshMd2tjLETn_h5KzbRLV_Ayg?e=ewleHn

**Comment by mohxinn** [comment]
Info from Windows Error Reporting:

```
Source
darktable photo workflow software

Summary
Stopped working

Date
‎2021-‎08-‎10 00:51

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\darktable\bin\darktable.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	darktable.exe
Application Version:	3.6.0.0
Application Timestamp:	00000000
Fault Module Name:	libmodulegroups.dll
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	00000000
Exception Code:	c0000005
Exception Offset:	00000000000013f1
OS Version:	10.0.22000.2.0.0.768.101
Locale ID:	8192
Additional Information 1:	cd6d
Additional Information 2:	cd6d75403418ea5f0e462ed8f7d89388
Additional Information 3:	19fe
Additional Information 4:	19fe148b7ce8f0ca431a66b674f602aa

Extra information about the problem
Bucket ID:	eade0a6d356e15d29626277bb139ee2d (1596006530157243949)

```

**Comment by johnny-bit** [comment]
@mohxinn - that video contains photos of non-public individuals. Please remove it to protect their privacy.

Other than that we have to narrow the problem down.

**Comment by mohxinn** [comment]
I will try to delete darktable folder under %AppData% and try again to see if the issue re-occurs

**Comment by mohxinn** [comment]
Deleting folder doesn't help.

I even tried to compile the latest snapshot of darktable (latest commit: **9362865a2c71daf4aa11d6ce09c888e3a0fbd07d**) myself using MYSYS2 but still I get the exception

One thing is that the issue occurs when I copy part or complete history stack from current photo and move to next photo.

Is there any way I can help with more information that will be useful for troubleshooting?
