### ISSUE TITLE
Harmonization of module handling/workflow

### ISSUE THREAD

**Issue by domosbg** [darktable-org/darktable#9826]
**Is your feature request related to a problem? Please describe.**
Some modules which allow mouse interaction directly on the picture act in different ways. IMO that is a little bit confusing.

**For example:**
_Crop and rotate:_
- Click on module header
- in the picture the rectangle for croping is shown with the last aspect setting and you can immediatly start changing the rectangle
- module is not switched on until you cropped the picture by double click within the rectangle.

_retouch:_
- Click on module header
- nothing happens, no interaction in the picture possible
- you have to choose a least one of the shapes you would like to have. After that you can retouch with the mouse in the picture
- the module is switched on immediately after choosing a shape, not after doing a retouch operation

_tone equalizer:_
- Click on module header
- nothing happens, no interaction in the picture possible
- you have to activate/deactivate "display exposure mask" or switch on the module, after that you can change the tone exposure by scrolling the mouse wheel in the picture

**Describe the solution you'd like**
I would prefer, that all modules act in the same way. That means for the examples above:

_Crop and rotate:_
- ok as described above

_retouch:_
- Click on the module header
- the last setting is restored (mainly preselecting the last used shape) or a useful standard setting is activated
- you can start immediately retouching in the picture with the mouse.
- Module is switch on after you have made your first retouch action not immediately.

_tone equalizer:_
- Click on the module header
- changing the tone values by moving the mouse wheel is immediately possible in the picture.

That means for the general workflow of a module which allows modifications in in the picture by mouse:
- Click on the module header
- Useful standard settings are selected or the last setting is restored
- You can immediately start acting with the mouse in the picture
- Module is switched to "on" after the first modification is done.

**Comment by johnny-bit** [comment]
You are mistaken regarding tone equalizer (and tbh both crop and crop&rotate) - usually those "work". The problem is - the module has to have focus for it to have controll over the main image area. That focus is indicated by faint background of "power" icon. Sometimes the focus isn't correctly grabbed by module, which means that eg for me when I opened tone equalizer to check if you discovered some problem I had it working immediately. Instead I managed to get crop module enabled without having a focus :P 

So in general your idea is already done except for retouch.
And for retouch you are (IMHO) also mistaken regarding flow of operations - retouch has same tools and follows same logic of drawn masks. You don't have ANY tool selected when opening a drawn masks options on any module and it's deliberate action of yours to choose the tool. Not only that, but in retouch you ought to choose algorithm used, wavelets used etc. You can use shift+click to set default algorithm.

If going with same flow as masks - for retouch immediately starting off with tool selected would mean that you effectively disable zooming with scroll... which is not something I would like to have. And since the same functionality would have to be present for consistency in masking - opening masks would also kill zooming and cause problems with how people may use darkable and their flow...

So it's a no from me :)

**Comment by domosbg** [comment]
Thanks a lot for your answer.

I understand your explanation for the retouch module. I compared it with the other two modules because I use retouch only in a very basic way (use add circle, healing and be happy if I be able to fix little dirt from the lens). But for more experienced users which uses more of the module's potential, I agree that it makes no sense to preselect something. Also your argument that it breaks the consisteny with the masks is an strong argument against by suggestion.

For the tone equalizer and crop & rotate: I'm not sure if I understand it correctly. If the module gets focus (which is neccessary to get control over the main image area) the "power" icon of e.g. tone equalizer looks like this:
![grafik](https://user-images.githubusercontent.com/88573684/129943463-78aa44d4-78e2-49c2-841c-92afe7ccb053.png)

In this case the tone equalizer has the focus and it should be possible to change the tone exposure by moving the mouse wheel over the picture. Is that correct?
If yes, then there might be another problem because in my darktable installation on windows it never works this way. The "power" icon looks like the picture above, in the headline the help text "scroll over image to change tone exposure...." is displayed but in the picture mouse wheel operations only zooms the picture.

Thanks a lot for your patience.

**Comment by johnny-bit** [comment]
If the icon's like that it means that it SHOULD work. another indication is the tip sayint to scroll over the image... It's actually in same piece of code that handles scrolling on the image surface! So if it doesn't work for you then it's a bug in gtk! If it's a bug it should be investigated in bug report and this FR closed.

**Comment by domosbg** [comment]
Ok, then I close this issue here and open a new bug report.
