### ISSUE TITLE
add filter to exclude folder for import module

### ISSUE THREAD

**Issue by Syliosha** [darktable-org/darktable#9860]
**Is your feature request related to a problem? Please describe.**
I like to import my old folder structure into darktable. In this folder structure theire are exported images from darktable in folder "darktable" (the default for exporting). But this folder isn't excluded.

This leads to an other problem in lighttable view, viewing folders with subfolders doesn't show the number of pictures in this folder.

**Describe the solution you'd like**
adding option to set an regular expression for excluding import subfolders.

**Alternatives**
include option for discret name for folder witch should be exluded

**Comment by nicorikken** [comment]
I'd like to +1 this request.

I have years worth of jpeg's organized in hierarchical folders. I've already set up the filesystem so I can do bulk Darktable export to a different file hierarchy, so that `/photos/shoots/2021/2021-10-18 shoot/IMG_0001.CR2` would end up in `/photos/exports/2021/2021-10-18 shoot/IMG_0001.jpg`, so mimicking the folder and filename hierarchy, just from the directory 'shoots' to the directory 'exports'. I got to this setup from tips by other Darktable users. But in practice my processing is more ad-hoc and on a per-shoot basis. So some shoots have been edited and exported, some not. I haven't taken the time to render out all images (including the majority which have no editing done), so my 'exports' folder is mostly empty. I'd like to have a folder in which I can find the images of all shoots, either just the imported images or the final renders/exports. The obvious step would be to render out all images, but this suggested feature would allow me to stick to a more shoot-based rendering approach and prevent duplicating hundreds of GB's in photo's by 1:1 exports.

To stick with my example, the new approach could be:
```
/photos/2021/2021-10-18 shoot/shoot/IMG_0001.CR2
/photos/2021/2021-10-18 shoot/darktable_exported/IMG_0001.jpg
```

This would also be more in line with the default export settings.

For any of you wondering why I might re-import existing folders with exported images? I use 3 different computers to manage and edit the files that are stored on my NAS. Also I have switched from the distribution packages to the Flatpak packages, requiring a new setup, and I also re-import after reinstalling one of my computers. I know scripts exist to migrate databases, but re-importing the whole folder structure just seems easier and more logical to me. For now I keep my exports on a separate location to prevent importing exports, but being able to exclude folders would be very welcome.

Git has `.gitignore` files ([docs](https://git-scm.com/docs/gitignore)) to exclude certain files, perhaps that can be inspiration. Rather than writing full-blown regexes, one can use globbing (`*`, `?`) to point to describe certain files or directories. One could even opt for having a `.darktableignore` file that would serve as input for these excludes, but as imports can happen in subdirectories I think it is difficult to determine the 'root' of the project, and thus where Darktable should look for such files. So defining files or directories to ignore would probably best be stored in Darktable itself.
