### ISSUE TITLE
TangentWave Panel Support for Darktable

### ISSUE THREAD

**Issue by nemotyro** [darktable-org/darktable#9882]
**Is your feature request related to a problem? Please describe.**
Colour Correction or Grading photographs is a lot more fun with Control Panels. I use the affordable Tangent Wave panel; to use this panel I’d have to map using keyboard shortcuts or mouse actions. The third way is to make use of OSC. 

I’ve contacted TangentWave, they haven’t heard of Darktable but will look into it. Apparently I’m the first to enquire with them. All they need is help from this community to allocate their resources. The copy of their response is copied, below:

**Describe the solution you'd like**

“Hi,

Thank you for your enquiry.

We’ve not come across Darktable, so we’d have to take a look. Right now you’re the first person to mention it, so I’m not sure we’d be able to commit resources to doing anything.

In general, if the software doesn’t have an OSC interface that we can access, the software manufacturer would have to change their code so that it logs into our Tangent Hub. They then need to pass all the details of the controls they have available in an XML file. This would then allow users and us to create a control map for it.

If it supports OSC then this is something you can do for yourself.

Kind regards,

Support“

I’m not a programmer, I only wish to add my small contribution. Darktable is the first photo-editing software I’ve come across that supports the waveform scopes, perhaps not strictly necessary; but they sure do help me understand what’s going-on.  Control Panel support will bring a little more fun.  

**Alternatives**

**Additional context**

**Comment by nemotyro** [comment]
Hi Jonny-bit & steerage,

Many thanks for your responses. 

Photographers have been jealous of videographer’s access to Waveform Scopes & Control Panels for colour correction & grading; they’re eyeballing the screen picture and Scopes while there hands & fingers operate trackerballs, dials, buttons & knobs. Currently, Control Panels from tangentwave.org.uk have out-of-box firmware support for 50-55+ photo/film-editing programmes like CaptureOne or Davinci Resolve. Darktable could be the 56th!

May I suggest Darktable try entering a collaboration dialogue with TangentWave. TangentWave have expressed an interest to look into Darktable. It could be a win-win situation for Darktable users: photographers get to use what videographers have enjoyed for years, we’re half way there, we now have the full compliment of scopes; we just need a plug-n-play control panel. All I did was go to their website, clicked on Support, raised a support ticket, sent an email & they expressed an interest. They have the resources to help.

**Comment by nemotyro** [comment]
Oops! Sorry dterrahe , this app auto corrected your handle.

**Comment by dterrahe** [comment]
> TangentWave have expressed an interest to look into Darktable.
> They have the resources to help.

I'm not sure where you read that in their reply. I see this:

>  Right now you’re the first person to mention it, so I’m not sure we’d be able to commit resources to doing anything.

Without them, or somebody else, providing a device (on loan) there's not much _I_ could do. But anybody who has one could get involved with the programming, or at least investigation and testing, part. Input NG is very much intended and designed to allow others to extend it for more and different types of devices, so TangentWave support would be very welcome. But in open source, the work is done by those who have an interest...

Alternatively, if you can point me at a really cheap device that sends OSC and that can be used as a test case for simple support, it may be possible to kindle my interest a little more.

**Comment by nemotyro** [comment]
Hi dterrahe,

Maybe I stretched the following: “Hi,

Thank you for your enquiry.

We’ve not come across Darktable, so we’d have to take a look.“

… to mean taking an interest in Darktable, rather than literally taking a look. My apologies. In any case they now know of Darktable. As to:

“Right now you’re the first person to mention it, so I’m not sure we’d be able to commit resources to doing anything”
 
 I took it to mean if more people had enquired they might see the project as worthwhile.  Again, my apologies. 
 
 Further, I was assuming that “software manufacturer” in the following meant the “programmers of Darktable”.

“ In general, if the software doesn’t have an OSC interface that we can access, the software manufacturer would have to change their code so that it logs into our Tangent Hub. They then need to pass all the details of the controls they have available in an XML file. This would then allow users and us to create a control map for it.”

… I downloaded Darktable 3.6, I thought that was called software. Apologies.
 
I’ll have to revise my understanding of a definition of an expression of interest. 

None-the-less, If I were given assurance that a senior Darktable rep was genuinely interested to work on the problem I would donate mine. I did say I wanted to do my bit.

**Comment by dterrahe** [comment]
Hey! No need to apologise so profusely! I didn't mean my reply to sound so negative, sorry. I understand you are hopeful; I just don't expect too much from them, because there's probably not going to be too much money in it.

If you are offering free machines, I'm sure somebody is willing to figure this out and implement something. Be clear what you expect though; you'd want it to work flawlessly (which might not be possible).

If nothing happens, when I have more time I might be interested myself...

**Comment by johnny-bit** [comment]
I browsed a bit and it looks like for it darktable's InputNG would have to expose OpenSoundControl interface according to spec published on http://opensoundcontrol.org/ and that would be a start... Looks like OSC was designed to be "more better midi" but as is usual things ran into xkcd 927.

A brief read told me that it looks like darktable should be OSC Receiver using their terminology... But the website & material are hard to easily follow :confused: I don't even know if there's ready-made osc library that's available in linux/msys/homebrew repos that we could use or would we need to develop socket reader (granted that it looks like it should be either TCP or UDP stuff :confused:) Browsing through https://github.com/topics/opensoundcontrol would take a lot more time ;)

What's cool however is that I see that there's free app from TangentWave that one can install on tablet and have test interface for free... but needs either iPad or 7" android tablet. Browsing around seems like OSC stuff is quite popular, especially in higher-end panels and some manufacturers do provide apps that simulate some of functionalities and communicate via osc.

Overall - this looks complex ;)

**Comment by dterrahe** [comment]
That was my takeaway as well. I suspect, like midi, OSC can be used in complex or simple mode. If the controller knows a lot about your setup, it can do a lot of configuration and send smart, tailored, commands. If not, it hopefully can just send simple "this knob was turned" messages and let dt do what it will. For example the BCR2000 has a whole configuration language built in. But I'm just asking it to send the message "knob one turned" when knob one is turned, rather than having it reconfigure all my keyboards, drumkits and stage lighting. And then when Input NG sees that knob one is turned, it does whatever you have configured it to do.

**Comment by nemotyro** [comment]
Hi guys,

I’m assuming there are many more professional & amateur photographers colour correcting & grading photos than there are videographers grading film for the screen. TangentWave’s reward would be getting units out the door. 

The email I sent them was labelled, by them: “Tangent Support email - ID 2051”. There’s one way to find out if TangentWave would be interested in helping Darktable and that’s for someone with authority from Darktable to email TangentWave; it wouldn’t have taken much for them to “take a look.” ID 2051 is there reference. 

To have something work flawlessly first off is a big ask, that’s why there are bug fixes and updated versions. 

I very much appreciate that capable people had read my original post. If it helps, my machine is still available.

All the best.

**Comment by dterrahe** [comment]
> someone with authority from Darktable

LOL

I'm not sure this is how it works around here. You mean authority to spend money? Authority to make other people do work?

Or just authority from knowing what they are talking about? In that case, in the area of input handling, I may be that person. But at the moment I'm finishing up the last bits of Input NG (see #8078 and #9487) and after that I'm moving house and after _that_ I can't promise anything about my motivation levels in this area...

But _anybody else_ can have a look at midi.c and OSC documentation and see if it is useful to have a conversation with TangentWave.

Out of curiosity; have you looked at the features Input NG offers (it currently supports midi devices and gamepads, besides keyboard) and assessed whether you think this could cover your wishes when linked to OSC? Because implementing the approach TangentWave proposes (writing a bunch of code specifically to tie into their system) seems unlikely to happen. Unless somebody pays somebody to do the work.

**Comment by nemotyro** [comment]
No worries, mate. Mia culpa. It looks like a control panel wont plug-n-play with Darktable any time soon, but I’d just like to say you guys have done a fine job implementing the waveform scopes. All the best in moving house.

**Comment by dterrahe** [comment]
Maybe this would be useful https://github.com/Andymann/ofxOscMidi ?
Not having an actual device I cannot play around with it.
