### ISSUE TITLE
Windows: Use of \ or / or // or \\ in DT inconsistent or incompatible

### ISSUE THREAD

**Issue by 520kaymann** [darktable-org/darktable#9905]
**Is your feature request related to a problem? Please describe.**
The windows standard of \ in directory prefencenes is not fully supported in DT and DT's use of // is also not windows supported 

**Describe the solution you'd like**
Typical Windows users just switching to DT will not even begin to know how to fix this on their own....
Please port over the directory standards common to MS Windows.

**Alternatives**
Make it clear to all Windows users that using the defaults in DT can break film rolls and library locations.

**Additional context**

**Comment by Mark-64** [comment]
Please consider that DT is not Windows native, it's a cross platform app and the Windows port was done not so long ago.
Having said that, I am regular Windows user of DT and I find the support of Windows OS pretty good.  
Moreover, several fixes are being implemented specific for Windows, take a look at [this](https://github.com/darktable-org/darktable/pulls?q=is%3Apr+windows+is%3Aclosed)
When coming to file paths, in Windows both \ and / are accepted as folder separator. 
If you have an issue, can you be more specific on what it is?

**Comment by 520kaymann** [comment]
Mark-64, first you have no idea how thankful I am of DT regardless of whether it is native or not SO do not take this as whining just if improvement can be done great if not I will work through it.

Now to be more specific. Yes windows could care but DT seems to care which I use.  I now use DT 3.6 (and 3.7) and the import 
![Screenshot 2021-08-30 121241](https://user-images.githubusercontent.com/57155093/131392336-0c68fd6c-ddd3-48a4-86a2-90b7119b4423.png)
If my preference are written as above using WIndows \ then DT will import into library.DB but not copy them the listed folder.

If I change all the \'s to /'s then everything imports correctly. The film roll will identify the roll with /'s. However if I want to filter using folders or file names or etc. DT cannot find the photos as I can only assume the folder is now using the wrong /\

![Screenshot 2021-08-30 122343](https://user-images.githubusercontent.com/57155093/131393692-b9f453af-39bf-458b-ad6d-671aa6921886.png)
![Screenshot 2021-08-30 122430](https://user-images.githubusercontent.com/57155093/131393707-092109a3-b6ae-4008-bcbf-28ba61f5f3aa.png)

Now If I want to import already existing folders (folders used pre DT 3.6) the get the windows style slash and If I change to folder view they are all listed including the previously copied and imported folder...
![Screenshot 2021-08-30 122703](https://user-images.githubusercontent.com/57155093/131394617-6408cb71-da53-47ce-844c-b6fd74af932c.png)
![Screenshot 2021-08-30 123146](https://user-images.githubusercontent.com/57155093/131394622-a7abbbda-9912-4674-b372-7def4507bdbd.png)

Now the making rating changes in film roll photo is not reflected in the exact same photo in folder view - even after restart.

This presents a dilemma - if I copy and import I will not be able to go to m photos by folder view basically no folder filter, If I manually copy and then import only I have to do the renaming one by one and I take thousands of photos a month which is back to DT 3.4 ugh.  

Sorry for the lengthy post but those are the details requested.

**Comment by 520kaymann** [comment]
Is DT using a Windows API in the import folder option and a DT Linux API in the Cop and import option...

**Comment by domosbg** [comment]
I also use darktable under windows and until now I had no problems. Because of your issue report I tried a little bit around.

The "\" darktable doesn't like in th file pattern field (maybe it is an escape character). I tried it in the export file pattern. The files are exported but all "\" are ignored. Instead of folders the filename is a concatenation of the folders and your file name. I think the same happened with your path and because of that the path was not valid and no files imported.
"\\" or "/" works for importing and exporting under windows.

Is the "\" needed in the file pattern for the bash like string manipulation? If not and there is no need to use a "\" in the file pattern, it would be possible to replace the "\" with "/" before processing the string further.

Unfortunately that would not fix the problem with the film roles. I think the path which is stored in the database is exactly the path you entered (with "/"). Saving also works because windows uses both "/" and "\" as folder separator. But if you want to read it again windows uses "\" as folder separator, so the database path and the windows path doesn't match.

I have no idea how to fix this with a solution that works under windows and linux usig the same code. I'm not sure if it is possible. If it is possible to make code pieces which are only compiled under windows, then a possible solution could be to replace "/" with "\" shortly before storing the path in the database.

In this case maybe it could also be possible to show a warning message if "\" are used in the file pattern field under windows (something like " "\" is used as a special control character here. Use "\\" as folder separator").

**Comment by 520kaymann** [comment]
I am now on 3.7 and I looks like they got it pretty much under control with the gtk_file_chooser_native instead of gtk_file_chooser. gtk_file_chooser_native will use whatever is the standard for our OS and it seems to work. So I am going to kill my library and start from scratch with 3.7 - thank heaven for xmp's!!

**Comment by Mark-64** [comment]
I believe #9717 and #9774 fixed most of the above issues.
Please test 3.7 and report if you find additional problems.

**Comment by 520kaymann** [comment]
Using darktable 3.7.0+331~g950232e0a for Windows: DT will not copy the files using \ as a folder marker. Using / will copy them and save a film roll that use / .   Tring to see the copied picture using collections folders and they are not listed. remove the film roll and then import the folder and then they there.....

**Comment by Mark-64** [comment]
Tested right now with 3.7.0+930
selecting folder with the native dialog works perfectly, you can even use network shared folder in Windows.
If you use variables for naming pattern or you manually write the folder paths, you have to use double backslash, like this

![immagine](https://user-images.githubusercontent.com/43290988/131904177-4c2f430d-51b8-4ae1-94e4-0cc2e8138855.png)

Single backslash does not work because it is not recognized as a stand alone characted by the string interpreter.
Forward slash is useble by the Windows file system, but at the moment it messes up the film roll name.

That's the way it is now
