### ISSUE TITLE
Global color picker values inconsistent with what's visible - Windows, maybe related to negadoctor

### ISSUE THREAD

**Issue by europlatus** [darktable-org/darktable#9920]
**Describe the bug/issue**
When using the global color picker, sometimes the colour sample is a different colour (perhaps offset) to the area sampled. 

**To Reproduce**
1. In darkroom, use global color picker in point mode or area mode to select a colour
2. Check sample in the module to see if it matches the point/area selected

**Expected behavior**
The colour sample should be the same as what the color picker reticle (point mode) is resting on or area selected (area mode).

**Screenshots**
![image](https://user-images.githubusercontent.com/89879133/131720921-a25e656b-b584-4301-b4ab-01433b5c4f90.png)
![image](https://user-images.githubusercontent.com/89879133/131721125-8f17a2c9-e336-40c2-8808-b2292769e902.png)
![image](https://user-images.githubusercontent.com/89879133/131721280-dc949c3a-32cd-4a9f-bfb8-47537c4bd195.png)
![image](https://user-images.githubusercontent.com/89879133/131721453-e34e067c-2585-4059-9238-8481154a5744.png)

**Platform**

* darktable version : 3.6.0 and 3.7.0+903~g9470965ae
* OS                : Win10 19043.1165
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
I have reproduced this on two RAW files so far. It is perhaps related to negadoctor.
One RAW and XMP in the links below for testing. The red chevrons and signs show the issue.

CR2 file: https://1drv.ms/u/s!Ar5ZQ34XqKqri5dwhxqVXfQeZzcIfQ?e=Qno7Pi
XMP: https://1drv.ms/u/s!Ar5ZQ34XqKqri5gdeX6ynf0HfEX6-A?e=fDXKLS

**Comment by Mark-64** [comment]
From what I see from the sample you provided, it's not begadoctor, but crop.
You have three modules that change gemometry: 

- lens correction
- crop&rotate
- crop

(BTW you apply both crop&rotate and crop, which is asking for trouble.)

It seems to me (by zooming to 1600%) that the shift is produced by crop module. The other two do not produce a substantial shift, considering that color picker sample the preview, not the full image.

**Comment by europlatus** [comment]
> (BTW you apply both crop&rotate and crop, which is asking for trouble)

I thought that was precisely what we are meant to do until the new crop module is implemented in 3.8. I use the crop&rotate module for rotating only, then the crop module for cropping.

As per the manual entry for the crop module: "For best results, you are advised to use the crop & rotate module to perform rotation and keystone correction (if required), and then perform final creative cropping with this module."

It also still seems to be a bit off from the reticle. This is the same picture sampled with crop and crop&rotate turned off:
![image](https://user-images.githubusercontent.com/89879133/131753715-4caabffa-f9f3-46b2-bbad-035fe5b7cd11.png)

**Comment by Mark-64** [comment]
I can't wrap my head around this, the pixel pipe is too difficult for me.
One question to the experts: couldn't we take the samples from the full image instead of the preview?
At least if there is a shift it would be easier to detect

**Comment by johnny-bit** [comment]
Fascinating to add is that we have preview scalling which throws another degree of uncertainty regarding color picker positioning

**Comment by elstoc** [comment]
> I thought that was precisely what we are meant to do until the new crop module is implemented in 3.8.

Indeed. We're still waiting for someone to code keystone correction into the perspective module and I think we still need crop&rotate for rotation atm. Not sure we can even guarantee this will be done in time for 3.8.

**Comment by Mark-64** [comment]
Ok, but about the color picker, how difficult it is to just sample the full image as it appears on the screen at the position of the cursor?

**Comment by dtorop** [comment]
Interesting. The #9835 changes should at least show in the central swatch what the picker is actually seeing (in the preview pixelpipe), which help to emphasize this.

I tested this a bit at the time and it seemed aligned (though sometimes painfully inaccurate due to the lower quality of the preview pipe data). I looked at the math in pixelpipe, which also looked right. But the results in the supplied test image do suggest a problem, at least for "pixel peeping"...

Here's a quick test just to show what may be happening:

Supplied image at 800%, all iops off, live sample set, dragging image so that can see the preview pixelpipe:

![preview pixelpipe](https://user-images.githubusercontent.com/2311860/132025949-37232c4f-f0d3-4bad-9077-d2120b6dee3f.png)

Same live sample, not dragging image so that are seeing full pixelpipe:

![full pixelpipe](https://user-images.githubusercontent.com/2311860/132025970-653255f7-3b2f-4723-82a6-606057b975a0.png)

To me this suggests that the sampling code is taking the sample in the right place, but the preview pipe isn't totally aligned with the full pipe. I wonder if the downscaling code in dt_iop_clip_and_zoom_mosaic_*() functions are shifting the image when they resample and "remosaic" it. I worked on that code a few years ago, and don't think I left it as good as it could be.

This is something like a 2 pixel error (in terms of preview pipe). But it would look worse in the full pixelpipe when zoomed at 1600%, because each of those preview pipe pixels would correspond to something like 4 full pipe pixels.

Other alternatives could be as simple as rounding the pixel location when converting to preview buffer coordinates rather than truncating it (as now). Or it may be a bug in the backtransform code...

So far as sampling from the full pixelpipe: The rationale for sampling from preview pixelpipe may be that the preview pixelpipe always renders the full image, while the full pipe may only render a crop of the image (what's shown in the center view at the current magnification) and may render that at a variety of magnifications. Hence if sampling the full pipe, off-screen live samples wouldn't update, and the sample quality would change depending on the current zoom level (though would almost always be better than the current pixelpipe samples).

There might be some clever way to work around this, e.g. make another "picker" pipe which would use a roi of the current picker area. This would probably bog down for large rectangular samples or a bunch of point samples in different places (unless the pipe was run multiple times for each point sample). Or maybe two passes? A first low-quality pass based on pixelpipe (as now, to produce picker and scope results), then at a low priority a picker/scope pipe would run and fill in higher quality data?

**Comment by Mark-64** [comment]
> There might be some clever way to work around this

What about sampling from full pipe only the on-screen samples? We can't pixel peep what's off screen.

**Comment by dtorop** [comment]
> What about sampling from full pipe only the on-screen samples? We can't pixel peep what's off screen.

It's possible... The trick is that the samples serve two purposes -- as input data to iops and as readouts to the user:

The ones requested by an iop may be used to change parameters to that iop, so it's tricky if they are unstable because they depend on the current "region of interest". If there is a two-pass solution (first off of preview pipe, then off of full pipe) the iop parameters might stutter a bit as the result gets better. If we only use the second pass to change the iop parameters, picker operations may start being sluggish on slow computers or complicated images.

Some iop pickers, the "primary" picker, and the live samples are just there to give a visual readout (vertical line representing sample). For those, it's probably OK if they start out rough then become more reliable. The same goes for scopes, but if we're limited to roi, full pixelpipe would only be useful when the center view shows the whole image.

Another possibility would be to make the point sample actually not be a single pixel, but a few pixels (ideally bigger than the mosaic pattern). Less precise, but it'd smooth out some of the errors in the preview pipe. And do we actually ever _want_ a one pixel sample of a continuous tone image?

Yet another possibility is to make the "remosaiced" preview pixelpipe image better. I tried to do this a few years ago, and made some headway, but it wasn't perfect. To start out the preview pixelpipe, a mosaiced image is downsampled then a new lower-resolution mosaiced image is created from the results. There's no effort to anti-alias, though (e.g. no Gaussian filter applied on downsample), so the results are strange, particular for fine detail. A problem is that blurring the image on downsample smears around overexposed pixels (e.g. specular highlights), which at the time made them look worse. This may be less of a problem with "modern" pipeline, though.

First pass I think would be simply making sure that the downsampled preview image aligns with the full pixelpipe. I'd imagine that other approaches may just require some time spent and trial-and-error to see which gives good results.

**Comment by jenshannoschwalm** [comment]
Some modules have a fast mode, could this be the cause of mis-alignment?

**Comment by dtorop** [comment]
> Some modules have a fast mode, could this be the cause of mis-alignment?

Maybe!

Also, thinking more about using full pixelpipe for iop picker input. In the case of "verb" pickers which change iop parameters. If they only change iop parameters once, when they're newly drawn (and then the picker automatically turns off), then it's fine to use the full pixelpipe data. As by definition (with current code), you can't draw a picker outside of the current roi. So why not use the best available data, which is closest to what the user sees?

In the case of "descriptive" pickers (which draw a line/rectangle to represent picker data, or give a readout on the left panel), it seems OK to use full pipe if possible, then fall back to preview pipe if the picker is offscreen. Perhaps fade out the picker results slightly if it is relying on preview pipe data, to clue the user into the situation.

Seems like a lot of little things which could improve this (the above, plus working on the "remosaicing" code). I'm happy to look into this, but wouldn't get the time until mid/late September at soonest.

**Comment by europlatus** [comment]
I just checked this issue on build 3.8.0 and it's still present. It does not seem to be related to the crop module, rotate and perspective, negadoctor or any other module enabled.
![image](https://user-images.githubusercontent.com/89879133/149224613-f7e6d729-9d69-451c-89cf-d406c3807b89.png)

**Comment by dtorop** [comment]
@europlatus Thank you for the reminder. None of the relevant code should have changed in v3.8, so it makes sense this bug is still present.

My guess (without any further investigation) continues to be that it's innate with sampling from the preview pixelpipe, and no iop is to blame. I'm still too swamped to look into this, but will when there's more time, if no one else does. It's an annoying/embarrassing bug, but not totally critical...?

**Comment by europlatus** [comment]
You're right, it's not critical. Thanks for the response!

**Comment by europlatus** [comment]
>  I'm also curious if this is Bayer-only or shows up on X-Trans sensors as well.
I have Fuji and Canon raw files, so I can check this out. I'll do some tests tomorrow.

**Comment by dtorop** [comment]
It appears that there is a longstanding problem in how the color picker region is calculated which is at least part of the problem. Something like this seems to improve things:

```diff
modified   src/develop/pixelpipe_hb.c
@@ -708,16 +708,22 @@ static int _pixelpipe_picker_box(
 
   dt_boundingbox_t fbox = { 0.0f };
 
-  // get absolute pixel coordinates in final preview image
+  // get absolute pixel coordinates in final preview image, keeping in
+  // mind that a sample at screen 0,0 is actually referencing image
+  // pixels (-0.5,-0.5) to (0.5,0.5)
   if(sample->size == DT_LIB_COLORPICKER_SIZE_BOX)
   {
-    for(int k = 0; k < 4; k += 2) fbox[k] = sample->box[k] * wd;
-    for(int k = 1; k < 4; k += 2) fbox[k] = sample->box[k] * ht;
+    fbox[0] = sample->box[0] * wd - 0.5f;
+    fbox[1] = sample->box[1] * ht - 0.5f;
+    fbox[2] = sample->box[2] * wd + 0.5f;
+    fbox[3] = sample->box[3] * ht + 0.5f;
   }
   else if(sample->size == DT_LIB_COLORPICKER_SIZE_POINT)
   {
-    fbox[0] = fbox[2] = sample->point[0] * wd;
-    fbox[1] = fbox[3] = sample->point[1] * ht;
+    fbox[0] = sample->point[0] * wd - 0.5f;
+    fbox[1] = sample->point[1] * ht - 0.5f;
+    fbox[2] = sample->point[0] * wd + 0.5f;
+    fbox[3] = sample->point[1] * ht + 0.5f;
   }
 
   // transform back to current module coordinates
@@ -735,24 +741,24 @@ static int _pixelpipe_picker_box(
   fbox[2] -= roi->x;
   fbox[3] -= roi->y;
 
-  // re-order edges of bounding box
-  box[0] = fminf(fbox[0], fbox[2]);
-  box[1] = fminf(fbox[1], fbox[3]);
-  box[2] = fmaxf(fbox[0], fbox[2]);
-  box[3] = fmaxf(fbox[1], fbox[3]);
+  // re-order edges of bounding box and center on pixel
+  box[0] = roundf(fminf(fbox[0], fbox[2]));
+  box[1] = roundf(fminf(fbox[1], fbox[3]));
+  box[2] = roundf(fmaxf(fbox[0], fbox[2]));
+  box[3] = roundf(fmaxf(fbox[1], fbox[3]));
 
-  if(sample->size == DT_LIB_COLORPICKER_SIZE_POINT)
-  {
-    // if we are sampling one point, make sure that we actually sample it.
-    for(int k = 2; k < 4; k++) box[k] += 1;
-  }
+  // make sure we sample at least one point
+  box[2] = fmaxf(box[2], box[0] + 1);
+  box[3] = fmaxf(box[3], box[1] + 1);
 
   // do not continue if box is completely outside of roi
   if(box[0] >= width || box[1] >= height || box[2] < 0 || box[3] < 0) return 1;
 
   // clamp bounding box to roi
-  for(int k = 0; k < 4; k += 2) box[k] = MIN(width - 1, MAX(0, box[k]));
-  for(int k = 1; k < 4; k += 2) box[k] = MIN(height - 1, MAX(0, box[k]));
+  box[0] = CLAMP(box[0], 0, width - 1);
+  box[1] = CLAMP(box[1], 0, height - 1);
+  box[2] = CLAMP(box[2], 1, width);
+  box[3] = CLAMP(box[3], 1, height);
 
   // safety check: area needs to have minimum 1 pixel width and height
   if(box[2] - box[0] < 1 || box[3] - box[1] < 1) return 1;
```

There's still at least one more wrinkle. Code like this seems to help:

```diff
modified   src/develop/develop.c
@@ -330,9 +330,11 @@ restart:
   dt_times_t start;
   dt_get_times(&start);
   dt_dev_pixelpipe_change(dev->preview_pipe, dev);
+  const int down_width = ceilf((dev->preview_pipe->processed_width + 1.0f) * dev->preview_downsampling);
+  const int down_height = ceilf((dev->preview_pipe->processed_height + 1.0f) * dev->preview_downsampling);
   if(dt_dev_pixelpipe_process(
-         dev->preview_pipe, dev, 0, 0, dev->preview_pipe->processed_width * dev->preview_downsampling,
-         dev->preview_pipe->processed_height * dev->preview_downsampling, dev->preview_downsampling))
+         dev->preview_pipe, dev, 0, 0, down_width,
+         down_height, dev->preview_downsampling))
   {
     if(dev->preview_loading || dev->preview_input_changed)
     {
``` 

But I can't tell if this is fixing a problem for any good reason, or patching over another problem.
