### ISSUE TITLE
[FR] more precise trouble message removing

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#9921]
Currently, when you want to remove a module trouble message, you do something like `dt_iop_set_module_trouble_message(module, NULL, NULL, NULL);`

The problem is that remove *any* trouble message, even if it's another one.

This is problematic for module which may display multiple trouble messages. One example is clipping (see #9893 comments) : 
- `process(...)` call `dt_iop_have_required_input_format` before anything else
- this routine "blindly" remove any trouble message if the format is correct (most of the time)
- as `process(...)` is called all the time, this prevent you to display any other trouble message ! (I guess this is the same for lot of other modules)

imho, we have 2 solutions here : 
1. consider it's not an issue and limit modules to only 1 trouble message.
2. implement a more powerfull system that don't blindly remove trouble messages.

for point 2, I can imagine : 
1. dt_iop_remove_module_trouble_message(module, msg_title); which would only remove the trouble msg if the title correspond
2. more complex system which would allow to show multiple messages and so on...

What do you think ?

**Comment by domosbg** [comment]
Solution 1 means to leave it as it is? I think that not a good solution as you can see in #9893. Actually there happens stranges things and the modules influences each other (deleting the trouble messages of other modules).

So I would prefer the second solution. In the first step IMO it would be enough to implement something like the first suggestion from AlicVB which should be enough to avoid the modules influencing each other.

Unfortunately I cannot help how to implement it because what happened in imageop.c in dt_iop_set_module_trouble_message looks like rocket science for me.

**Comment by AlicVB** [comment]
> Actually there happens stranges things and the modules influences each other (deleting the trouble messages of other modules).

I'm not aware of that... do you have any example of that ?
As said, the issue in #9893 is strickly internal to the c&r module... and codewise, that would be surprising, as you need to pass the module structure to all trouble routines...

**Comment by domosbg** [comment]
No, sorry. I think I missunderstood the functionality. Forget what I posted.

**Comment by jenshannoschwalm** [comment]
I don't think a 'remove message' function based on comparing is good, the module might simply not know what the last message was. 

Do we need some sort of inter-module communication?

Or use global enum tokens instead of pure text and every module can have a list of trouble tokens that can be set/cleared. The 'set trouble message' function would then have to construct a combined text?

Writing from my phone and memory ....

**Comment by AlicVB** [comment]
> I don't think a 'remove message' function based on comparing is good, the module might simply not know what the last message was.

in every part of the code I've seen for now (but I certainly miss some) we have something like : 
```
if(......)
{
  dt_iop_set_module_trouble_message(module, NULL, NULL, NULL);
}
else
{
  dt_iop_set_module_trouble_message(module, "trouble title", "trouble explanation", "trouble log error");
}
```

For this cases, we know exactly in the first part what trouble messages we want to remove.
But I agree that we might want cases where the trouble title, for some reason is not always the same, but comes from the same trouble test. Example : "exposure too hight" / "exposure too low"

At first sight, I would say that the simplest in this case would be to add a "id" text parameter to the trouble messages, that would not be shown to end users but used only to remove the right message.

If need we can also keep the possibility to remove *all* trouble messages from the module...


> Do we need some sort of inter-module communication?

no, trouble messages are internals to modules, afaik...

**Comment by dterrahe** [comment]
What exactly is the vision/design goal for trouble messages? Is there one or did this just start organically and has been growing to encompass more stuff. Initially flagging the individual module that had a problem when there were just two that might interact seemed a good idea, but I'm getting the feeling that this might quickly get out of hand and become overly complex. Are warning messages in the module header itself, when that might not even be visible, really the best approach? Not saying definitely it isn't, but maybe now is the time to step back and decide where this should go. And also to consider if interacting modules are really OK if they should really be exceptional and avoided as much as possible.

Another approach could for example be a message block/module at the top or bottom of the right panel. If two modules set confliction options, this could be highlighted in one message (with buttons to focus/expand the one or the other module). The module could contain multiple messages if there is more than one conflict. No conflicts -> module hidden.

**Comment by TurboGit** [comment]
> Are warning messages in the module header itself, when that might not even be visible, really the best approach?

It is always visible since there is an alert icon even when the module is collapsed.

> Another approach could for example be a message block/module at the top or bottom of the right panel. If two modules set confliction options, this could be highlighted in one message (with buttons to focus/expand the one or the other module).

Yes, or maybe just an icon just before the secondary-screen one which gets highlighted when some important messages are there.

**Comment by dterrahe** [comment]
> It is always visible since there is an alert icon even when the module is collapsed.

But the header could be in a different module group or scrolled out of view.

> Yes, or maybe just an icon just before the secondary-screen one which gets highlighted when some important messages are there.

Also an option. Both could be used so that when the status bar or the side panel is hidden, to other one would still be visible.

**Comment by domosbg** [comment]
For alerts like the double crop hint (if you are using c&r after crop), I think the way the messages actually are represented in and below the module header is good, because the message is directly shown in the scope of the users interaction.

To prevent alerts are not seen because the module scrolled out of screen, an error indicator in the module group selection buttons could help in combination with an general error indicator somewhere in the UI. Then it should be easy to navigate to the problematic modules.

Another point: is it actually possible to separate the severity of a trouble message? If not, I think it would be useful to separate at least between warning (orange) and an alert message (red)
