### ISSUE TITLE
Support for DJI Mini 2 and Mavic 2 Pro

### ISSUE THREAD

**Issue by cdhodgdon** [darktable-org/darktable#9941]
**Is your feature request related to a problem? Please describe.**
Love the program, have not found any issues with it at this time.

**Describe the solution you'd like**
Would like to see support added for lens corrections for the DJI Mavic 2 Pro and the DJI Mini 2.

**Alternatives**
None

**Additional context**
None

**Comment by johnny-bit** [comment]
I was under the impression that drones produced DNG files which are supported. For lens correction you have to follow https://github.com/darktable-org/darktable/wiki/Camera-support#lens-correction

Since it's lens-only issue and you have to provide necessary data to lensfun, closing here.

If I'm mistaken, please comment and I'll reopen
