### ISSUE TITLE
improve the activation of cropping tool (again)

### ISSUE THREAD

**Issue by dreamcat4** [darktable-org/darktable#9945]
**Is your feature request related to a problem? Please describe.**

"I'm always frustrated when i select the cropping tool. but cannot get its interactive guides and editing mode to actually appearand become editable"

**Describe the solution you'd like**

 it seems this feature still needs more work on it in the future. because one particular thing i noticed today is that the crop module itself cannot actually focus when you click on it's entry after adding into the new quick access panel feature

so i am wondering now (since it's so challenging), why not create a separate button within the crop module controls. which then manually toggles on/off the guides etc. So it could simply be called edit or set or guides toggle. Or whatever you prefer. And then also rename the existing guides control --> guides type. To make the distinction between those 2 controls a bit clearer.

**Alternatives**

Well what do you think? Because there seems to be different ways for which this feature could be improved. Many thanks for previously looking into this

**Additional context**

these matters have been investigated before by @elstoc and the specific code and logicaround enabling / disabling this UI editing may be rather difficult to deal with. so this also needs to be considered when developing improvements and further solutions in this area

references: #2766 and #4517

also i dont think it ever occured to me to try 'double clicking' anything. so if that is any help IDK. but certainly not intuitive if i actually missed that. but certainly thenew quick access menu in 3.6+ is not working or behaving like the real crop panel. and should be looked into again

**Comment by Nilvus** [comment]
We already have issues open about rewriting that part, so please continue discussion (if needed, after reading them) before. I will close this issue. Issue from @AlicVB here: https://github.com/darktable-org/darktable/issues/8834

And a new crop module (and guides options) is already in master (and so for future 3.8). See here: 8838 and about guides: 8891 or here (minor other pull request exist about those things): 9495

There's still work in progress on other related parts (rotate, ashift...) as you can see in #8834 and also draft pull request 9456

Of course, you're welcome (if you know how to do it safely) to test actual master and report in related discussions above, issues you see.

**Comment by elstoc** [comment]
Hmm I read this as less about showing and hiding the guide lines as about enabling and disabling the over-image cropping tools with a button rather than with gui focus. Of course we _can_ add that to #8834 but I'm not sure it's mentioned there right now.

**Comment by dreamcat4** [comment]
yes good catch - this was specifically what i suggested. it just seemed to me that a dedicated button could be a good way to ensure its allways accessible regardless of other potential problems. but it could also serve double duty as an indicator too at same time. so that during editing the user actually could positively see and associate the crop tool as being the specific one that is currently engaged (vs other possible tools they could also have open during their edits). food for thought

**Comment by Nilvus** [comment]
Hmm, I didn't understand that and yes it's a little different even if it remains related to #8834. I'm not sure if it's a good thing to add another button. I'm quite afraid that this will overload the UI for something that we could deal with existing settings for me. But I understand the idea anyway. @AlicVB: what do you think of that and do you prefer to include this on your #8834 issue or we reopen this one for discussion?

**Comment by AlicVB** [comment]
No I prefer to keep this FR separate from #8834 where the main goal is to drop c&r.
Here, we speak about cropping, which will only concern the crop module.

About the FR itself : 
I see your need, but from a code point of view, all the overlays things are really related to the module focus. Not to speak that in the crop case, we have to make some complex things in order to "deactivate" the crop and show the overlays...
So I'm not really in favor of a "simple" button things...

That said, at some point in the QAP development, Someone as suggested to add some sort of "module shortcuts buttons" in the panel. iirc the idea was to add modules icons in QAP bottom, side by side, and when clicking on it that would have shown the module under the icons, without leaving the QAP panel (not sure if I'm clear)
Maybe something like that could solve everything ?

**Comment by dreamcat4** [comment]
yes thanks for distinguishing this from the crop & rotate. as they are in fact different tools from one another

well i suppose from a user request POV you could break it down into 2 different levels of 'improve' being asked for here:

level 1 - cropping from the QAP is currently broken. because there seems no way ATM to activate the focus *at all*. so this is effectively unfinished spit and polish of the QAP or a bug such that the QAP being a new feature.... it does not yet fully support all of the available tools. only some of them

level 2 - actually make the cropping tool something that is intuitive to use (with a visual feedback indication that it is the one currently engaged). desirable to use, and efficient to use (without requiring extra unnecessary click, or a double click to re-activate it, or a click on such a tiny widget that you miss it half the time, etc)

so my suggestion about adding a dedicated button just seemed like the simplest and fastest to impement method (even if not ideal or forever) that i could think to suggest here to fullfill and solve all of those problems in the least cost fashion. since the button could also be drag gable into the QAP. to get that to work too. of course this is also me not knowing or understanding anything about the complex focusing mechanisms in the code here

but it may be entirely possible to solve the same general set of goals in a number of other different ways. and also zooming out you might want to implement a more general changes afffecting all such similar such tools that require a similar focussing behaviour with an overlay. not just only on the cropping tool. or only on there 2 cropping tools

so yes... having something at the bottom of the QAP to set the focus would solve level 1 critera. but being located in a different part of the screen from the rest of the chosen crop controls would not seem to fulfill the more lofty level 2 goals for making more on par with the better usability of cropping tools inside other major image editing / authoring programs

but my question is well... why not link a dedicated button within the crop panel to trigger the existing focusing code. how is that any harder than the linking it to any other onscreen gui widget? i suppose i'll never know!! hehe :)

**Comment by dterrahe** [comment]
Quite a lot has happened around cropping since this issue was filed. I tried reading the whole discussion, but couldn't really make out which specific (historic or not) problem it is describing and therefore can't tell whether that still exists in the current implementation. So in the current state, I think it is unlikely that anyone will pick this up to try to solve it, if there's still anything to solve. I think there's a much better chance of this getting attention, if it needs it, by opening a new, fresh issue that deals concretely with the current situation or to provide more detail in other open issues that propose adding buttons for specific modes. I would suggest the original poster do that, or anyone else who _does_ know what still needs fixing here.
